### ISSUE TITLE
[Feature Request] Benutzer definierte Start/Stop Sequenz beim Backup per Script Aufruf

### ISSUE THREAD

**Issue by jogicom** [simatec/ioBroker.backitup#100]
Ich betreibe ioBroker auf einer virtuellen Maschine auf einer Synology. Dort wird IObroker nicht als Dienst ausgeführt. Wäre es möglich, dass man Benutzer definierte scripts angeben könnte, mit denen IObroker vor dem Backup gestoppt und nach dem Backup wieder gestartet wird?
Bei mir ist es so, dass ich IObroker mit "pkill io" stoppen muss, und mit "node node_modules/iobroker.js-controller/controller.js >/opt/scripts/docker_iobroker_log.txt 2>&1 &" wieder gestartet wird. Wenn ich diese Anweisungen in Scripte verpacken könnte, die dann von backitup aufgerufen werden könnten, wäre ich sehr glücklich!

**Comment by simatec** [comment]
Du kannst die in lib liegenden shells händisch anpassen. Dort liegen start/stop/external shells. 

Dabei ist zu beachten, dass bei einem Update die Dateien neu geschrieben / überschrieben werden.
