### ISSUE TITLE
Installation on Synology/Portainer works but generates Error Messages 

### ISSUE THREAD

**Issue by knowhowseeker** [simatec/ioBroker.backitup#1000]
![image](https://github.com/simatec/ioBroker.backitup/assets/41070573/ad773557-273b-4cd1-aa21-5851ca0917ab)

No File location is provided in the configuration, but when starting backitup it generates the follwing error-log:
![image](https://github.com/simatec/ioBroker.backitup/assets/41070573/154684da-98f8-473f-a9cb-4917813ba632)

Portainer has the following entry:
![image](https://github.com/simatec/ioBroker.backitup/assets/41070573/9cc6dff7-5980-4b0c-bfe8-ff97eda15727)

When actually conducting a backup of iobroker it works and the GZ-Backup file is available:
![image](https://github.com/simatec/ioBroker.backitup/assets/41070573/f45ef91f-1ffa-4d27-895a-ff827145833d)

So why the error message in the log?

**Comment by simatec** [comment]
The server IP from YouTube NAS and the path to the mount are missing.
Is the package nfs-common installed?
