### ISSUE TITLE
SyntaxError: Unexpected token '?', "? ??"... is not valid JSON

### ISSUE THREAD

**Issue by maxpd1** [simatec/ioBroker.backitup#1001]
**Is your feature request related to a problem? Please describe.**
I want to import a backup file which was created by the backitup adapter but am receiving error message that I don't have a valid json file.

**Describe the solution you'd like**
The error message should contain the line which causes the error.

![image](https://github.com/simatec/ioBroker.backitup/assets/15956503/4d0e171a-e48c-45e4-bcd2-aef362f7dcc6)

I am not sure if its safe to use an online validator.
So I am stuck at the moment.

**Comment by simatec** [comment]
What exactly are you planning to do and what is your exact approach?
Please describe your mistake in more detail.
Please also specify the versions of backitup, js-controller and how old the backup is.

**Comment by maxpd1** [comment]
Hi simatec,

found the error on my side! I imported the backup as a configuration file, which can't work..

**Comment by mcbirne** [comment]
OK, das normale wiederherstellen brach ohne Fehler ab. Keine Ahnung was geholfen hat. Ich hab backitup neu installiert, den ioBroker mehrmals neu gestartet und den Loglevel von Backitup verändert. 
Aber nun läuft die Wiederherstellung.
