### ISSUE TITLE
No more backups possible

### ISSUE THREAD

**Issue by raschy** [simatec/ioBroker.backitup#1008]
I use Backitup version 2.8.1 and backup daily via ftp to a QNAP share. After a few days (currently 20) no more backups can be made because the maximum number of connections for the user are reached.

Error in log: 
backitup.0 (597638) [iobroker/ftp] Error: Sorry, the maximum number of clients (20) for this user are already connected. 

Is this an error or a wrong setting/handling

**Comment by simatec** [comment]
This is not a Backitup problem. There are too many FTP connections open. Simply restart your host system. 

But why FTP? Your NAS supports CIFS and I think NFS too. That would clearly be the better choice.

**Comment by raschy** [comment]
It was already clear to me that there were too many FTP connections open. I was wondering if the adapter wasn't disconnecting properly. To counteract this, I restart the Adpater every day. Restarting the host is probably not the solution.
But the reference to CIFS (if I get that set up) will hopefully get me further. Thanks for the quick reply.

**Comment by simatec** [comment]
If your NAS supports NFS, this is the best solution

**Comment by raschy** [comment]
Thank you, i will try NFS
