### ISSUE TITLE
Unterschiedliche js-controller-Versionen wird im Adapter nicht angezeigt als Fehler

### ISSUE THREAD

**Issue by tugsi** [simatec/ioBroker.backitup#1010]
Ich habe heute mein Docker-ioBroker mal upgedatet und im Vorfeld den js-controller auf die 5.0.15 gesetzt, im Docker war es aber die 5.0.12.
Im Backitup-Adapter dann die Sicherung zum wiederherstellen ausgewählt und es scheint erstmal zu laufen, aber selbst nach 15min oder mehr steht immer noch im Fenster nur "...restored..." und auch im Log passiert nichts.
Gehe ich in die Konsole und gebe dort "iobroker restore Backupfile" an, dann kommt die Fehlermeldung, dass die js-controller-Versionen nicht übereinstimmen und mit "--force" trotzdem wiederhergestellt werden kann.

Leider kommt diese Meldung nicht über den Adapter.

**Comment by simatec** [comment]
Welche Version von Backitup ist installiert? Es gab Änderungen in der v9 des Docker Images. 
Dafür muss die aktuelle latest von Backitup genutzt werden. Dort wurden Anpassungen vorgenommen

**Comment by tugsi** [comment]
Ich kann es leider nicht mehr zu 100% sagen, zuerst war eine ältere Version schon an Bord, aber ich meine, ich habe auch den Adapter upgedatet auf 2.8.7 beim zweiten Versuch. 
Aber da ich im Nachgang noch andere Probleme hatte, bin ich erstmal nochmal auf meine alte Version gegangen, sonst Ärger mit Frau ;) 
Werde dies aber explizit nochmal durchtesten, die v9.0.1 vom Docker, hat ja nur die 5.0.12 intus, aber ich hatte schon im alten System auf 5.0.15 hochgezogen. 
Gebe dann Rückmeldung hier, ob es auch mit Backitup 2.8.7 Probleme macht.

**Comment by buanet** [comment]
@tugsi Mal unabhängig davon, dass das Backitup-Log eine Meldung wie zur nicht passenden js-controller Version in jedem Fall zurück geben sollte, solltest du dir angewöhnen vor einem restore auch im neuen Container auf beta repo umzustellen und auf die aktuellen Versionen zu gehen. (Natürlich nur wenn du sonst auch im beta Repo unterwegs bist, wovon ich aufgrund deiner versionsangaben ausgehe)
Das Docker images selbst bringt immer nur die stable Versionen von js-controller und den default Adaptern mit.

Ein anderes wichtiges Thema ist hier aber auch die Kompatibilität der js-controller Versionen untereinander in Bezug auf den restore. Meines Erachtens sollte es mindestens innerhalb einer Minor Version ohne `--force` möglich sein einen restore auch bei abweichender js-controller Version durchzuführen.

@Apollon77 @foxriver76 Ein Thema zur Diskussion und/oder enhancement für den js-controller?

**Comment by Apollon77** [comment]
Am Ende gute Frage und Grundsatzfrage : stellt ein Backup exakt die Versionen/zustand her wie davor oder nicht ;-) und auch ein Patch Version unterschied ( wobei der Controller auch nicht sauber semantic versioniert ist) ist ein Unterschied.

**Comment by tugsi** [comment]
@buanet Da geb ich Dir voll Recht. Ich habe vergessen das umzustellen, dass ich aus dem Beta-Repo ziehe, total übersehen. 
Allerdings sollte ich ja trotzdem im Web-GUI die Fehlermeldung bekommen. 
Werde dies aber nochmal nachvollziehen, ob es auch mit der neuesten Version so war.
Ich sehe es ähnlich wie @Apollon77 , ein Restore stellt den Ursprungszustand her, wenn dann könnte man darüber reden, ob eine Meldung mit Bestätigungsanfrage bei einer (höheren) Minor Version in solch einen Falle kommt.

**Comment by buanet** [comment]
> Am Ende gute Frage und Grundsatzfrage : stellt ein Backup exakt die Versionen/zustand her wie davor oder nicht

Wenn man es so betrachtet, dann hätten wir in beiden Szenarien ein Problem...

1. Restore stellt Zustand und Versionen zum Zeitpunkt des Backups wieder her = Ist aktuell nicht der Fall, soweit ich weiß werden nach dem Restore die Adapter aus latent installiert (???),  js-controller bleibt untouched...
2. Restore stellt ausschließlich config wieder her = Adapter werden dazu aus latest nachinstalliert, js-controller meckert wenn Version nicht dem Backup entspricht.

😀 Ich denke wir haben hier eine Aufgabe...

Mfg, 
André

**Comment by foxriver76** [comment]
Adapter werden entsprechend dem gespeicherten `installedFrom` + Version nachinstalliert und nicht die neuste npm Version.

**Comment by buanet** [comment]
Ich hab mal hier was auf gemacht: https://github.com/ioBroker/ioBroker.js-controller/issues/2510

@foxriver76 OK, dann betrifft es nur den js-controller... Ist halt dann die Frage ob es möglich ist auch diesen beim Restored in der Version aus dem Backup zu installieren...

Mfg, 
André

**Comment by buanet** [comment]
@simatec New issue/enhancement?

https://github.com/ioBroker/ioBroker.js-controller/issues/2510#issuecomment-1784842723

During restore: Inform user if js-controller Version in Backup is different from installed one and let decide if --force flag should be used.

**Comment by tugsi** [comment]
So, jetzt habe ich es nochmal bewusst getestet.
Backup vom alten System mit 
- js-controller 5.0.16 

Neuen Docker 9.0.1 aufgebaut und gestartet, Repo auf BETA gestellt, Backitup (2.8.7) und Admin (6.12.1) auf die neueste Version hochgezogen, js-controller auf 5.0.12 gelassen.

Die Installation wird gemacht !  (Hatte wohl die Tage noch nicht die neueste Backitup mit dem fix für Docker v9 drauf)
Fehlermeldung erscheint auch im Log-Fenster, aber keine Unterbrechung oder Abfrage, er installiert durch, trotz kleinerer js-controller-Version  (wo der Konsolenbefehle` iobroker restore` dies unterbricht und mit `--force` gestartet werden möchte)

Also mein eigentliches Problem saß wie so oft vorm PC, ob ihr jetzt eine Abfrage erstellt, ob er wirklich auf die ältere Version installieren soll oder dies unterbricht mit dem Hinweis, erst js-controller auf Version xy bringen, das müsst ihr entscheiden. 
Ich persönlich hätte jetzt in meiner Installation erwartet, dass er unterbricht mit dem Hinweis auf eine unterschiedliche Version.

**Comment by simatec** [comment]
Backitup nutzt bereits eine ganze Weile den --force Flag
