### ISSUE TITLE
Not able to restore a healthy backup file from Syno (or Fritzbox NAS) with node.js 18.18.2

### ISSUE THREAD

**Issue by gittjoel** [simatec/ioBroker.backitup#1012]
Not able to restore a healthy backup file from Syno (or Fritzbox NAS) with node.js 18.18.2

This happened after a new image (Raspberri Pi Imager - Bookworm 64bit, minimal) was written and a new iob installation was done succesfully. 
The backup files can be seen after recovering the system.adapter.backitup.0.json in Backitup, and can be choosen. The process of recovering finishes quickly after 1 minute and iob is started again wiht no change!

After going back to node.js 18.18.1 in the same setting, the backup could be done as usual without any problems.

Tried this 3 times and always imaged new and installed a new copy of iob. 
Result was always the same, as described above.

Discussed this on iob Forum with T.B. (https://forum.iobroker.net/topic/69734/zu-aktueller-bug-in-node18-cifs-backitup/8)

**Comment by simatec** [comment]
Please test v2.9.0 with the mount option "Cache Loose"

**Comment by gittjoel** [comment]
Hi,
no chance with 2.9.0
Cannot see or reach the backup's in the mount at the Synoloy as mount is not working.
Never the less, tried a backup in this constellation and it is saved under /opt/iobroker/backups and stays there. See log!
With node.js 18.18.1 - **after a new install** backups at Syno with CIFS a rechable at once and can be restored.

**Log:**
Started iobroker ...
[DEBUG] [mount] - Wake on LAN wait 30 Seconds for NAS!
[DEBUG] [mount] - Wake on LAN MAC-Address: 00:11:32:1B:52:75
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=xxxx,password=****,cache=loose,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=2.0 //192.168.178.32/02_Datensicherung/iobroker/backupDir /opt/iobroker/backups"
[DEBUG] [mount] - first mount attempt with smb option failed. try next mount attempt without smb option ...
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=xxxx,password=****,cache=loose,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.178.32/02_Datensicherung/iobroker/backupDir /opt/iobroker/backups"
[ERROR] [mount] - [undefined Error: Command failed: sudo mount -t cifs -o username=xxxx,password=****,cache=loose,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.178.32/02_Datensicherung/iobroker/backupDir /opt/iobroker/backups
mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

[DEBUG] [mount] - Error: Command failed: sudo mount -t cifs -o username=xxxx,password=****,cache=loose,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.178.32/02_Datensicherung/iobroker/backupDir /opt/iobroker/backups
mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

[DEBUG] [iobroker] - host.raspberrypi 101 states saved

[DEBUG] [iobroker] - host.raspberrypi 145 objects saved

[DEBUG] [iobroker] - **Backup created: /opt/iobroker/backups/**iobroker_2023_11_02-12_46_57_backupiobroker.tar.gz

[DEBUG] [iobroker] - This backup can only be restored with js-controller version up from 4.1

[DEBUG] [iobroker] - done
[DEBUG] [cifs] - used copy path: /02_Datensicherung/iobroker/backupDir
[DEBUG] [cifs] - done
[ERROR] [clean] - Backup files not deleted from /opt/iobroker/backups because some errors.
[DEBUG] [clean] - done
[DEBUG] [whatsapp] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done

**Console:**
pi@raspberrypi:~ $ cd /opt/iobroker/backups
pi@raspberrypi:/opt/iobroker/backups $ ls
iobroker_2023_11_02-12_46_57_backupiobroker.tar.gz  iobroker_2023_11_02-13_13_37_backupiobroker.tar.gz
iobroker_2023_11_02-12_53_27_backupiobroker.tar.gz

**Comment by gittjoel** [comment]
OK, restored the configuration from a file  saved before with the above examole,. Found out, that the passwd maybe stored in that config-file was not restored rigth? Or is it never restored? So this might been a problem because of a wrong passwd!!! Maybe my bad? I have a special character in my passwd. Or did I oversee, that passwds ar notsaved  in the config-file?

**Comment by simatec** [comment]
Please enter your password again in the configuration and save the settings.
Afterwards, the restore should work as usual.

**Comment by gittjoel** [comment]
So the passswd has to be entered again always if a restore is done? Is that correct? 
Thanks and you can close heres then.
