### ISSUE TITLE
Possibility to upload backup files to /backup directory by admin interface

### ISSUE THREAD

**Issue by DutchmanNL** [simatec/ioBroker.backitup#1019]
In current way its needed to copy/past backup files to the system so backlit up is able to restore the data

From user experience this does not always fit and adds complexity

**Describe the solution you'd like**
Add possibility to upload backup files using backit-up to the backup directory

a button with file upload could be implemented to make it easier for our community to upload existing backups

**Comment by simatec** [comment]
v2.9.2 added

**Comment by DutchmanNL** [comment]
> v2.9.2 added

Lovely thank you!
