### ISSUE TITLE
Wunsch: integration nextcloud

### ISSUE THREAD

**Issue by quorle** [simatec/ioBroker.backitup#102]
Ihr leistet wirklich eine super Arbeit, mal so am Rande. 

Aber ich nutze zu Hause die NextCloud für meine datenspeicherung und würde gerne das Backup auf nextcloud lokal speichern lassen. Könntet ihr das integrieren?

**Comment by simatec** [comment]
Muss man mal schauen, ob das in node unterstützt wird

**Comment by quorle** [comment]
Das wäre wirklich eine Super Sache. Hoffe das ganze Klappt. Ich habe bislang nur das gefunden, wenn dir das etwas hilft:
[https://www.npmjs.com/package/node-nextcloud](url)

**Comment by Leviathan09** [comment]
Würde mich diesem Wunsch anschließen

**Comment by ratho** [comment]
ja wäre echt super

**Comment by OdomLinx** [comment]
Nextcloud unterstützt ja webdav, man könnte also das webdav mounten und dann wie ein lokales Verzeichnis behandeln. So als kleiner workarround, bis es evtl direkt im Adapter ist.

**Comment by uwe72** [comment]
next cloud integration (adapter) wäre klasse!

**Comment by Z18Aplha** [comment]
Würde mich auch über eine WEBDAV-Integration freuen. Habe drei Raspberrys auf drei Standorte verteilt und würde gerne alle auf mein NAS sichern. 
Aktuell geht es über einige Umwege, aber schön ist es nicht.

**Comment by Scrounger** [comment]
@simatec 
Mit [nextcloud-node-client](https://www.npmjs.com/package/nextcloud-node-client) lib ist das implementieren richtung nextcloud sehr einfach und komfortabel

**Comment by simatec** [comment]
Nextcloud ist auf der Todo und wird auch kommen.
Aktuell stehen aber noch andere Themen im Vordergrund

**Comment by Sacred-Shadow** [comment]
Wobei eine Unterstützung von WebDAV ja mehr als "nur" Nextcloud ermöglichen würde.
Viele Webspaces, Online Backupdienste oder Clouddienste bieten einen WebDAV Zugang an.

**Comment by djanknecht** [comment]
Hallo,
 
ich schließe mich hier an, WebDAV wäre wirklich eine super Option. Da ich selbst Owncloud nutze, würde eine Nextcloud Unterstützung nicht helfen. Aber WebDAV können beide. :-)

VG, Dirk

P.S. @simatec und die anderen Contributer: Danke für Eure Arbeit!

**Comment by djanknecht** [comment]
Danke für das Feature, funktioniert super!

**Comment by simatec** [comment]
Das freut mich 😉
