### ISSUE TITLE
CCU Backup - Cannot parse answer error

### ISSUE THREAD

**Issue by FabiSrun** [simatec/ioBroker.backitup#1025]
**Describe the bug**  
When backing up my ccu3 manually, I receive an error:
`[ERROR] [ccu] - Cannot parse answer: SyntaxError: Unexpected end of JSON input`
Before version 2.9.1 of backup and node v16.x the backup worked correctly.

**To Reproduce**  
1. Open setting of backup instance
2. Open the ccc tab
3. Click the button "Backup now" (I use the german interface "Jetzt sichern")
4. after mounting is successful, the error appears

**Expected behavior**  
To backup the ccu

**Screenshots & Logfiles**  
no screens taken

**Versions:**  
 - Adapter version: 2.9.1
 - JS-Controller version: 5.0.12
 - Node version: v18.17.1
 - Operating system: Raspi

**Additional context**

**Comment by simatec** [comment]
Check your Login.
User „Admin“ and Password from the User Admin

**Comment by simatec** [comment]
closed because no answer
