### ISSUE TITLE
jarvis file backup

### ISSUE THREAD

**Issue by Zefau** [simatec/ioBroker.backitup#1026]
**Is your feature request related to a problem? Please describe.**
No problem. Only an elaboration of the already existing backup for jarvis.

**Describe the solution you'd like**
I was writing a backup script for jarvis. Maybe you can implement it in backitup? 
The script will create dedicated text files for each required datapoint (such as jarvis.0.layout, jarvis.0.devices, etc.).

Of course has to be adapted in the conext of an iobroker adapter. Right now I have it running in iobroker.javascript.

```js
const fs = require('fs');
const path = require('path');

/*
 * CONFIG
 */
const backupFolder = '/opt/iobroker/backups/jarvis';
const states = [ 'jarvis.0.devices', 'jarvis.0.layout',	'jarvis.0.css', 'jarvis.0.widgets' ];

/**
 * BACKUP FOLDER
 */
function backupToFolder(states, root) {
    // create date for first level
    const date = new Date();
    const ts = date.getFullYear() + '-' + ('0' + (date.getMonth() + 1)).substr(-2) + '-' + ('0' + date.getDate()).substr(-2);
    const folder = root + '/' + ts;

    if (!fs.existsSync(folder)) {
        fs.mkdirSync(folder, { 'recursive': true });
    }

    // get states and write to file
    const promises = [];
    states.forEach(stateId => {
        // get value from state
        const val = getState(stateId).val;
        
        // write value to file
        promises.push(new Promise(resolve => fs.writeFile(path.join(folder, stateId + '.txt'), val.toString(), resolve)));
        promises.push(new Promise(resolve => fs.writeFile(path.join(root + '/_latest', stateId + '.txt'), val.toString(), resolve)));
    });

    return Promise.allSettled(promises);
}

/*
 *
 */
// Scheduler
schedule('0 3 * * *', () => { // daily at 3:00 in the night
    backupToFolder(states, backupFolder);
});

// Run instantly
backupToFolder(states, backupFolder);
```

**Comment by simatec** [comment]
Thanks for the code snippet.
Is the Jarvis backup in the adapter not correct?

**Comment by Zefau** [comment]
It backups the JSON files that jarvis itself stores on the file share. These files will be deleted with every adapter update due to an ioBroker setting. The value of the states will always be consistent and available though. Basically just another way to backup, but in my view a more realiable way.

**Comment by simatec** [comment]
OK, I understand your concern ... However, I had already rebuilt something some time ago in order to secure exactly the states.

Backitup currently backs up the following data from Jarvis:

* _BACKUP_DEVICES.json
* _BACKUP_LAYOUT.json
* _BACKUP_SETTINGS.json
* _BACKUP_STYLES.json
* _BACKUP_WIDGET.json
* all States from `jarvis.x.settings.*`
* `jarvis.x.devices`
* `jarvis.x.css`
* `jarvis.x.layout`
* `jarvis.x.notifications`
* `jarvis.x.widgets`
* `jarvis.x.scripts`
* `jarvis.x.theme`
* jarvis.x.info.pro

**Comment by Zefau** [comment]
perfect, I will close this then. Thanks!
