### ISSUE TITLE
Passwortübergabe für MySQL

### ISSUE THREAD

**Issue by PanDroids79** [simatec/ioBroker.backitup#1027]
**Is your feature request related to a problem? Please describe.**
Bei einem komplexeren Passwort für die MySQL-Datenbank führt der MySQL-Dump-Aufruf zu einem Fehler:

backitup.0 (1541330) [iobroker/mysql] Error: Command failed: mysqldump  -u iobroker -p**** iobroker -h localhost -P 3306 > /opt/iobroker/backups/mysql_2023_11_12-02_40_31_backupiobroker.sql
backitup.0 (1541330) [iobroker/mysql] mysqldump: Got error: 1045: "Access denied for user 'iobroker'@'localhost' (using password: YES)" when trying to connect

**Describe the solution you'd like**
Wenn ich den Befehl manuell über die Kommandozeile ausführe aber **-p PASSWORD** durch **--password='PASSWORD'** ersetze, dann funktioniert der Dump-Befehl. **PASSWORD** ist dann natürlich mein etwas komplexeres Password für die MySQL-Datenbank.

Kann der Aufruf in ioBroker.backitup entsprechend angepasst werden?

Verwendete MySQL-Datenbank: Ver 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64)

Vielen Dank

**Comment by simatec** [comment]
Setze dein Passwort in der Config von Backitup mal in Anführungszeichen

**Comment by PanDroids79** [comment]
Ja klar das funktioniert auch. Aber wäre es aus Anwendersicht nicht besser oder transparenter, wenn das in Anführungszeichensetzen im Hintergrund durch backitup gemacht wird?
Falls das nicht umsetzbar ist, wäre zumindest ein Hinweis hilfreich, dass bei Sonderzeichen im Passwort, dieses in einfache Anführungszeichen gesetzt werden muss.

**Comment by simatec** [comment]
Das nehme ich mit auf die Todo

**Comment by simatec** [comment]
Fix in v2.9.4
