### ISSUE TITLE
Make Backup download work for containerized ioBroker instances

### ISSUE THREAD

**Issue by hgschwibbe** [simatec/ioBroker.backitup#1028]
I have Synology NAS with an ioBroker container installation. When I try to download an archived backup I recognized that I am unable to download it because backitup opens a random port which is currently not forwarded from my Docker container:
![grafik](https://github.com/simatec/ioBroker.backitup/assets/1725648/5f9ca863-84e2-4e0c-b75a-318e73f3b963)

This is a problem because I can only forward single ports via Synology Container Manager, and when I configured one, I will get another random port after restart:
![grafik](https://github.com/simatec/ioBroker.backitup/assets/1725648/449c8078-46da-4529-9b0f-20f519596ce0)

**Comment by simatec** [comment]
In v2.9.3 is fix the Port for Docker
https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch#docker-unterst%C3%BCtzung
