### ISSUE TITLE
1) V2.9.4 - redis without pw not possible 

### ISSUE THREAD

**Issue by Ilovegym66** [simatec/ioBroker.backitup#1030]
1) 
working fine with V2.9.3, updated to 2.9.4 follow issue appears ( I have no pw set on the redis db, this works fine in the closed docker network):
`
Started iobroker ...
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.iobroker 33570 states saved

[DEBUG] [iobroker] - host.iobroker 40223 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2023_11_24-16_32_41_backupiobroker.tar.gz

[DEBUG] [iobroker] - This backup can only be restored with js-controller version up from 4.1

[DEBUG] [iobroker] - done
[DEBUG] [redis] - Start Redis Backup ...
[DEBUG] [redis] - Created redistmp directory
[ERROR] [redis] - Error: Command failed: redis-cli -u 'redis://redis:""@10.10.2.10:6379' --rdb /opt/iobroker/backups/redistmp/dump.rdb
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
AUTH failed: WRONGPASS invalid username-password pair or user is disabled.

`

looks like the "" are wrong, without this, the cmd should be run...

**Comment by simatec** [comment]
Fix in v2.9.5
