### ISSUE TITLE
Immer Adapter Neustart vor Backup?

### ISSUE THREAD

**Issue by hohmannc85** [simatec/ioBroker.backitup#1032]
Hallo, ich habe das problem, dass ich ein Backup erst machen kann, wenn ich den Adapter Neustarte, damit sind automatisches Updates nicht möglich. Er schreibt nur Starte Backup und dann passiert nichts. starte ich den adapter neu gehts rasch voran!
Ich hatte irgendwann mal eine alte Version gefunden bei der das Problem nicht mehr bestand, leider weiss ich die Versionsnummer nicht. Bei meinem Kumpel ist das dasselbe problem. Alles ist auf dem neusten Stand! Woran kann es liegen? oder gibt es informationen die ich mehr liefern kann?

**Comment by simatec** [comment]
Bitte Config als Json posten und den Debuglog aktivieren und hier posten

**Comment by hohmannc85** [comment]
Vielen Dank für die Antwort. Wo finde ich die Config als Json? in den Datenpunkten finde ich nix. Export sehe ich nicht und im opt/iobroker/iobroker-data/backitup finde ich nur skripte

**Comment by hohmannc85** [comment]
Oh danke. Wie geht das für nächstes mal?
Kommt sobald der Fehler wieder besteht!

**Comment by simatec** [comment]
Debuglog wäre noch wichtig...
