### ISSUE TITLE
Speicherverwaltung des Adapters hat anscheinend keine ordnungsgemäße Garbage Collection

### ISSUE THREAD

**Issue by ktrolp** [simatec/ioBroker.backitup#104]
Hallo,

wenn über den Adapter ein Backup erstellt wird (ich verwende Standard, Komplett und CCU) wird die RAM Nutzung der Instanz immer größer. Normalerweise verwendet der Adapter nach dem Start der Instanz ca. 35 MB. Nach Erstellen von Backups werden bis zu 100 MB belegt. Ein Neustart des Adapters gibt dann die zusätzlich belegten (60 MB's) wieder frei.

Bitte die Garbage Collecten das Adapters prüfen
Danke

**Comment by Apollon77** [comment]
GC wird von nodejs direkt gemacht. Der Adapter bzw JavaScript hat da keinen großen Einfluss darauf. Der Speicher wird zu einem späteren Zeitpunkt freigegeben. Wann entscheidet nodejs. 

Welche nodejs Version ist im einsatz?

**Comment by ktrolp** [comment]
Hallo,

 

Node.js: v8.15.0

 

Klaus

 
 

Gesendet: Donnerstag, 07. Februar 2019 um 19:46 Uhr
Von: "Ingo Fischer" <notifications@github.com>
An: "simatec/ioBroker.backitup" <ioBroker.backitup@noreply.github.com>
Cc: ktrolp <k.trolp@gmx.at>, Author <author@noreply.github.com>
Betreff: Re: [simatec/ioBroker.backitup] Speicherverwaltung des Adapters hat anscheinend keine ordnungsgemäße Garbage Collection (#104)


GC wird von nodejs direkt gemacht. Der Adapter bzw JavaScript hat da keinen großen Einfluss darauf. Der Speicher wird zu einem späteren Zeitpunkt freigegeben. Wann entscheidet nodejs.

Welche nodejs Version ist im einsatz?
