### ISSUE TITLE
Backup Redis with default user and password did not work

### ISSUE THREAD

**Issue by dajupp** [simatec/ioBroker.backitup#1045]
**Describe the bug**  
Error message during backup "AUTH failed: WRONGPASS invalid username-password pair or user is disabled."

**To Reproduce**  
Redis DB with requirepass password set, settings in BackItUp are set to user "default" and "password" from requirepass setting

**Expected behavior**  
Backup successfull

**Screenshots & Logfiles**  
redis-cli -u 'redis://default:"password"@x.x.x.x:6379'. 
the quotation marks are the problem. run the same command without in console works, no Error message

works in console, no error-> redis-cli -u 'redis://default:password@x.x.x.x:6379'

**Versions:**  
 - Adapter version: v2.9.6
 - JS-Controller version: 5.0.16
 - Node version: docker image v9.0.1

**Additional context**

**Comment by simatec** [comment]
What is „default“? Your Username from redis host?

**Comment by dajupp** [comment]
yes "default" is username for redis connection if you only set a password with requirepass 

"password" is my own generated one

the current command with " around password gets an error 
redis-cli -u 'redis://default:"password"@x.x.x.x:6379'

this command in commandline without " around password works
redis-cli -u 'redis://default:password@x.x.x.x:6379'

from redis.conf documentation
"# IMPORTANT NOTE: starting with Redis 6 "requirepass" is just a compatibility
# layer on top of the new ACL system. The option effect will be just setting
# the password for the default user. Clients will still authenticate using
# AUTH <password> as usually, or more explicitly with AUTH default <password>
# if they follow the new protocol: both will work."

**Comment by simatec** [comment]
Fix in v2.9.7
