### ISSUE TITLE
HistoryDB

### ISSUE THREAD

**Issue by rtwl21** [simatec/ioBroker.backitup#1050]
Der Standardspeicherpfad im History Adapter ist hier: /opt/iobroker/iobroker-data/history/
da man direkt im History Adapter das Feld für einen Benutzerdefinierten Pfad leer lassen kann und es dennoch dort gesichert wird, dachte ich, dass der Backitup Adapter auch auf diesen Speicherpfad zugreift, leider ist dem aber nicht so.

Man muss also zuvor bei der Anleitung vom History Adapter auf Github den Standard-Pfad suchen, und diesen im Backitup Adapter eintragen. Nur so werden auch die History-Daten per Backup gesichert.

Könnte man das für neue User vereinfachen, so dass der Backitup Adapter auch auf den standard-Pfad zugreift, sollte die entsprechende Pfadangabe im Adapter leer sein?

**Comment by simatec** [comment]
Eine Abfrage und Prüfung auf den korrekten Pfad ist in v.2.9.9 integriert wurden.

**Comment by rtwl21** [comment]
Danke fürs direkte umsetzen 👍
