### ISSUE TITLE
Node Red Backup is restored to the wrong folder

### ISSUE THREAD

**Issue by Marc-Berg** [simatec/ioBroker.backitup#1051]
The first Node-Red instance is created in the `/opt/ioboker/iobroker-data/node-red` folder and backed up cleanly. However, the restore is created in the folder `/opt/ioboker/iobroker-data/node-red.0` and is therefore not usable.

**Expected behavior**  
Restore the backup of the first instance in the `/opt/ioboker/iobroker-data/node-red` (without ".0")folder.

 - Adapter version: 2.9.8
 - JS-Controller version: 5.0.17
 - Node version: 18.19
 - Operating system: Linux
 
See also this forum thread:
[https://forum.iobroker.net/post/1103019](https://forum.iobroker.net/post/1103019)

**Comment by simatec** [comment]
Fix in v2.9.10
