### ISSUE TITLE
Backup Information wrong

### ISSUE THREAD

**Issue by Marsen76** [simatec/ioBroker.backitup#1053]
Hello.

At first, I'm sorry for my English. It's not the yellow from the egg. ;-)

I saw that's the backup information is wrong.
The last ioBroker backup had should be on December 04, the CCU backup on December 28. But it's twisted.

The ioBroker backup was on December 28 and the CCU backup on December 04.

Please note the pics.

Can you check this please? Or is this a mistake from me?

![Screenshot Backitup](https://github.com/simatec/ioBroker.backitup/assets/109294508/81976571-1e98-42bf-85d7-640695e21978)
![Screenshot CCU_Backup](https://github.com/simatec/ioBroker.backitup/assets/109294508/59b4c1c5-736e-4a0a-a459-e201870b3bc0)
![Screenshot iob_Backup](https://github.com/simatec/ioBroker.backitup/assets/109294508/e199bde2-563b-4b2d-97b5-96a6b3fb380a)

Adapter version: 2.9.8
JS-Controller version: 5.0.17
Node version: 18.19.0
Operating system: bookworm

Have a good start in the new year.

**Comment by simatec** [comment]
Nothing can be twisted... The data comes directly from the States:
````
backitup.0.history.ccuLastTime
backitup.0.history.iobrokerLastTime
````
