### ISSUE TITLE
iob Admin User Permission denied?

### ISSUE THREAD

**Issue by StephanWagner87** [simatec/ioBroker.backitup#1058]
Hi,

i am not able to Start a Backup with my own Admin User (Stephan). I am only able to start the Backup with the Standard Admin User of iob (admin). i already tried iob fix and set chmod to 777 to the Folders. 
Any suggestions?

User Overview:
![image](https://github.com/simatec/ioBroker.backitup/assets/49068001/a2137477-2cbe-432a-9192-6d137bb17e6c)

Own Admin User:
![image](https://github.com/simatec/ioBroker.backitup/assets/49068001/7b4c8c64-4406-4c19-9b27-92917b03351b)

Standard Admin User:
![image](https://github.com/simatec/ioBroker.backitup/assets/49068001/53ed22f8-f07b-4cf3-a103-8a25ef6e190d)

**Comment by simatec** [comment]
Only Admin can Backup and Restore

**Comment by simatec** [comment]
Please post your Config from Backitup in JSON File and the Debuglog from Backitup (not as Screenshot)

**Comment by simatec** [comment]
I have just tested it again... A user in the Admin group can create a backup without any problems.
Please check your settings and run `iob fix` if necessary.

Otherwise simply restart the iobroker and delete the browser cache.

**Comment by simatec** [comment]
I think you messed things up with your chmod. Try deleting the user and creating a new one.

**Comment by StephanWagner87** [comment]
> I think you messed things up with your chmod. Try deleting the user and creating a new one.

I deleted the User and created a new one but Receive the Same error

**Comment by simatec** [comment]
I think you bent something with the chmod.
Unfortunately, the problem is not due to Backitup.

**Comment by simatec** [comment]
Since this problem is more of a general iobroker or admin issue, I would suggest you ask in the forum. 
There are many helpful users there and also a lot of specialist knowledge at the start.
