### ISSUE TITLE
kein Grafana backup mit v.2.9.10

### ISSUE THREAD

**Issue by ohle64** [simatec/ioBroker.backitup#1059]
ubuntu 22.04.3 LTS, node v18.19.0, npm 10.2.3, js-controller 5.0.17, admin 6.13.15, web 6.2.3, ws 2.5.10
Nach update von 2.9.9 auf 2.9.10 folgendes Log für automatisches Backup(2:15 Uhr):
`2024-01-04 02:18:21.948  - [31merror[39m: backitup.0 (3105536) [iobroker/grafana] Error on Grafana Dashoard adaefc6a-dc24-413a-9a3e-e7f2ca9588be backup: AxiosError: Request failed with status code 404
2024-01-04 02:18:21.980  - [31merror[39m: backitup.0 (3105536) [iobroker/grafana] Error on Grafana Dashoard backup: TypeError: Cannot read properties of undefined (reading 'data')
2024-01-04 02:18:34.106  - [31merror[39m: backitup.0 (3105536) [iobroker/clean] Backup files not deleted from /opt/iobroker/backups because some errors.`
Nach Rückstellung auf 2.9.9 läuft das manuelle backup wieder normal durch.

**Comment by simatec** [comment]
Bitte installiere die v2.9.10 noch einmal ... Es hat sich zwischen den Versionen nix geändert, was mit dem Grafana Backup zu tun hat.

**Comment by ohle64** [comment]
Manuelles Backup lief jetzt mit v2.9.10 ohne Fehler durch. Ich warte noch das automatische Backup morgen früh ab, dann nehm ich den issue raus.

**Comment by ohle64** [comment]
Problem besteht weiterhin. Mit Version 2.9.9 jetzt auch die Error-Meldung - auch beim manuellen Backup. Das Problem ist die dependencies axios ^1.6.3. Wer installiert diese Abhängigkeiten ? js-controller ? vermute ich mal. In v 2.9.8 steht noch die axios1.6.2 drin und damit läuft das backup auch durch. Ab v 2.9.9 steht die axios 1.6.3 drin und da hakt es. Installiert ist bei mir die axios1.6.2. Es sind auch immer andere Grafana-Dashboards wo der Fehler ausgelöst wird.
Hier noch ein Auszug manuelles Backup 2.9.9. mit Fehler:
`[ERROR] [grafana] - Error on Grafana Dashoard d72215e1-0c0a-4bb4-9cb3-cc8f748d9e6e backup: AxiosError: Request failed with status code 500
[DEBUG] [grafana] - found Dashboard: stromverbrauch-monat
[ERROR] [grafana] - Error on Grafana Dashoard backup: TypeError: Cannot read properties of undefined (reading 'data')`

Das Gleiche mit backitup v2.9.10. manuelles Backup:
`[DEBUG] [grafana] - found Dashboard: stromverbrauch-letztesjahr
[ERROR] [grafana] - Error on Grafana Dashoard fbdb1a02-9f53-458f-95ff-1a96333153b3 backup: AxiosError: Request failed with status code 500
[DEBUG] [grafana] - found Dashboard: temperaturwohnung
[ERROR] [grafana] - Error on Grafana Dashoard backup: TypeError: Cannot read properties of undefined (reading 'data')
[DEBUG] [grafana] - start Grafana backup compress ...
[ERROR] [grafana] - Error on Grafana Dashoard b782dad3-df7b-4302-816c-f4f654befd04 backup: AxiosError: Request failed with status code 500
[DEBUG] [grafana] - found Dashboard: speicherdaten
[ERROR] [grafana] - Error on Grafana Dashoard de4e952a-8d32-4729-9978-b5b98cb2864d backup: AxiosError: Request failed with status code 500
[DEBUG] [grafana] - found Dashboard: system`

Bin jetzt zurück auf v2.9.8.

**Comment by simatec** [comment]
Poste mal bitte deine Settings als JSON File.

**Comment by ohle64** [comment]
Meine config:
[system.adapter.backitup.0.json](https://github.com/simatec/ioBroker.backitup/files/13841306/system.adapter.backitup.0.json)

**Comment by simatec** [comment]
Teste mal bitte mit der IP statt "localhost"

**Comment by ohle64** [comment]
Das scheint der Übeltäter gewesen zu sein. Habe jetzt 2 Durchläufe mit v2.9.10 gemacht und keine Fehler bei manuell. Ich warte noch den Morgen ab und schliesse dann den issue.
Bis hier erst mal -> Vielen Dank für die Unterstützung und die Fehlersuche!

**Comment by ohle64** [comment]
Gute Nachricht. Das Backup ist fehlerfrei durchgelaufen. Die IP-Adresse anstelle von localhost war das Problem.
Vielen Dank nochmal. Ihr macht einen super Service und einen super Adapter. Danke!
