### ISSUE TITLE
Question: Copy not working anymore

### ISSUE THREAD

**Issue by bruesche** [simatec/ioBroker.backitup#1064]
Hi there,

I switched from raspberry pi 4 (bullseye) to raspberry pi 5 (bookworm). Everything works fine but I cannot backup my settings with Backitup to an USB stick. I didn't change anything in my settings, usb stick is the same without formatting. 
Can anyone gibe me a hint what's wrong?
Here are my settings:
<img width="1181" alt="Bildschirmfoto 2024-01-17 um 18 34 18" src="https://github.com/simatec/ioBroker.backitup/assets/62746518/c8b2c8dc-04ed-45f5-992c-ac4a9c373dee">

then I get this error:
<img width="774" alt="Bildschirmfoto 2024-01-17 um 18 36 14" src="https://github.com/simatec/ioBroker.backitup/assets/62746518/4bc8db7e-c4df-4bc1-a9fe-7cdf9d17dfd3">

Thx for help

**Comment by bruesche** [comment]
USB Stick is mounted and accessible
<img width="486" alt="Bildschirmfoto 2024-01-17 um 18 42 06" src="https://github.com/simatec/ioBroker.backitup/assets/62746518/e7e4391d-535d-4a7a-acb4-c633e1aa480b">

**Comment by simatec** [comment]
Please post the full Debuglog from Backup and post the Output from

`ls -lah /media/pi/USBSTICK`

**Comment by bruesche** [comment]
Hi,

here is the screen from "ls". You can see that I switch the pi in December. 
<img width="695" alt="Bildschirmfoto 2024-01-17 um 20 05 20" src="https://github.com/simatec/ioBroker.backitup/assets/62746518/2ee0bb37-ec3d-4d67-8845-c6e3cb176692">


Output from DEBUG:
Started iobroker ...
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.piflur 13072 states saved

[DEBUG] [iobroker] - host.piflur 15412 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2024_01_17-20_06_40_backupiobroker.tar.gz

[DEBUG] [iobroker] - This backup can only be restored with js-controller version up from 4.1

[DEBUG] [iobroker] - done
[DEBUG] [javascripts] - Created javascript_tmp directory: "/opt/iobroker/backups/tmpScripts"
[DEBUG] [javascripts] - found Script: Administration_Test
[DEBUG] [javascripts] - found Script: Restart_Deconz
[DEBUG] [javascripts] - found Script: Restart_Deconz1
[DEBUG] [javascripts] - found Script: Anwesenheitssteuerung
[DEBUG] [javascripts] - found Script: API_Test
[DEBUG] [javascripts] - found Script: Heizung_Zeitsteuerung
[DEBUG] [javascripts] - found Script: Heizung_deaktivieren-Anwesenheitssteuerung_deaktivieren
[DEBUG] [javascripts] - found Script: Heizungssteuerung_Kontaktsensoren
[DEBUG] [javascripts] - found Script: Heizungssteuerung_ueber_VIS_Auswahl
[DEBUG] [javascripts] - found Script: Heizungsteuerung_Gruppe_VIS
[DEBUG] [javascripts] - found Script: Heizungsteuerung_Jugend_VIS
[DEBUG] [javascripts] - found Script: Kalender_Flex_Buero
[DEBUG] [javascripts] - found Script: Say_it_Test
[DEBUG] [javascripts] - found Script: Signal_Adapter
[DEBUG] [javascripts] - found Script: Signal_Test
[DEBUG] [javascripts] - found Script: Telegram_erster_Test
[DEBUG] [javascripts] - found Script: Telegramm_Fully_Browser_Cam
[DEBUG] [javascripts] - found Script: Konvertieren_von_Komma_zu_Simikolon
[DEBUG] [javascripts] - found Script: Licht_Badlicht_Anna
[DEBUG] [javascripts] - found Script: Licht_Farbwechsel
[DEBUG] [javascripts] - found Script: Licht_Kueche
[DEBUG] [javascripts] - found Script: Licht_Kuechenlicht__Zeitsteuerung_abends
[DEBUG] [javascripts] - found Script: Licht_Kuechenlicht__Zeitsteuerung_morgens
[DEBUG] [javascripts] - found Script: Licht_Kugeln_Zeitsteuerung
[DEBUG] [javascripts] - found Script: Licht_Schlafzimmer_LED_an
[DEBUG] [javascripts] - found Script: Licht_Wohnzimmer_FP2_komplett
[DEBUG] [javascripts] - found Script: Lichtgesteuerter_Bewegungsmelder_Flur
[DEBUG] [javascripts] - found Script: Lichtgesteuerter_Bewegungsmelder_Kueche
[DEBUG] [javascripts] - found Script: Lichtgesteuerter_Bewegungsmelder_Schlafzimmer_LED_Stripe
[DEBUG] [javascripts] - found Script: Lichtgesteuerter_FP2_Kueche
[DEBUG] [javascripts] - found Script: Presence_Wohzimmer_licht_ist_an
[DEBUG] [javascripts] - found Script: Test_LED_Lichterhöhung
[DEBUG] [javascripts] - found Script: Wecker_LED_Streifen_Fussende
[DEBUG] [javascripts] - found Script: Aqara_Cube_Kueche
[DEBUG] [javascripts] - found Script: Connect_FIRE_TV_nach_Neustart
[DEBUG] [javascripts] - found Script: Lautstärke_Sonos_Badezimmer
[DEBUG] [javascripts] - found Script: Lautstärke_Sonos_Kueche
[DEBUG] [javascripts] - found Script: Lautstärke_Sonos_Schlafzimmer
[DEBUG] [javascripts] - found Script: Lautstärke_Sonos_Wohnzimmer
[DEBUG] [javascripts] - found Script: Media_Buerotisch
[DEBUG] [javascripts] - found Script: Media_Jugendzimmer
[DEBUG] [javascripts] - found Script: Musik_Titel_setzen
[DEBUG] [javascripts] - found Script: Receiver_Steuerung
[DEBUG] [javascripts] - found Script: SonosGruppen
[DEBUG] [javascripts] - found Script: SonosSteuerung
[DEBUG] [javascripts] - found Script: Sonos_Gruppe_Badezimmer_aktiv
[DEBUG] [javascripts] - found Script: Sonos_Gruppe_Kueche_aktiv
[DEBUG] [javascripts] - found Script: Sonos_Gruppe_Schlafzimmer_aktiv
[DEBUG] [javascripts] - found Script: Sonos_Gruppe_Wohnzimmer_aktiv
[DEBUG] [javascripts] - found Script: Spotify
[DEBUG] [javascripts] - found Script: TV_Steuerung_LG
[DEBUG] [javascripts] - found Script: Luftreiniger_Anwesenheitssteuerung
[DEBUG] [javascripts] - found Script: Reinigen_Anwesenheitssteuerung
[DEBUG] [javascripts] - found Script: Sekunden_in_Datenpunkt
[DEBUG] [javascripts] - found Script: Bewegungssensor_Schlafzimmer_aktiv
[DEBUG] [javascripts] - found Script: FP2_Wohnzimmer
[DEBUG] [javascripts] - found Script: Alarmanlage_aus
[DEBUG] [javascripts] - found Script: Alarmanlage_ein
[DEBUG] [javascripts] - found Script: Alarmanlage_ein_mit_VIS
[DEBUG] [javascripts] - found Script: PinCode_Eingabe
[DEBUG] [javascripts] - found Script: Startbildschirm_einstellen
[DEBUG] [javascripts] - found Script: Szenenwahl
[DEBUG] [javascripts] - found Script: Alarmanlage
[DEBUG] [javascripts] - found Script: Bild
[DEBUG] [javascripts] - found Script: Flur
[DEBUG] [javascripts] - found Script: Jugendzimmer_Büro
[DEBUG] [javascripts] - found Script: Küche
[DEBUG] [javascripts] - found Script: Schlafzimmer
[DEBUG] [javascripts] - found Script: Start
[DEBUG] [javascripts] - found Script: Status
[DEBUG] [javascripts] - found Script: Wohnzimmer
[DEBUG] [javascripts] - found Script: Temperatur_Umrechnung
[DEBUG] [javascripts] - Try deleting the Javascript tmp directory: "/opt/iobroker/backups/tmpScripts"
[DEBUG] [javascripts] - Javascript tmp directory "/opt/iobroker/backups/tmpScripts" successfully deleted
[DEBUG] [javascripts] - Backup created: /opt/iobroker/backups/javascripts_2024_01_17-20_06_47_backupiobroker.tar.gz
[DEBUG] [javascripts] - done
[DEBUG] [nodered] - Created noderedtmp directory
[DEBUG] [nodered] - Node-Red tmp copy finish
[DEBUG] [nodered] - Backup created: /opt/iobroker/backups/nodered.0_2024_01_17-20_06_47_backupiobroker.tar.gz
[DEBUG] [nodered] - Try deleting the old node-red tmp directory: "/opt/iobroker/backups/noderedtmp0"
[DEBUG] [nodered] - node-red tmp directory "/opt/iobroker/backups/noderedtmp0" successfully deleted
[DEBUG] [nodered] - found node-red database: node-red.0
[DEBUG] [nodered] - done
[DEBUG] [cifs] - used copy path: /media/pi/USBSTICK
[ERROR] [cifs] - Path "/media/pi/USBSTICK" not found

**Comment by simatec** [comment]
Und was gibt folgendes aus?

`sudo -u iobroker ls -lah /media/pi/USBSTICK`

**Comment by bruesche** [comment]
pi@piflur:/media/pi/USBSTICK $ sudo -u iobroker ls -lah /media/pi/USBSTICK
ls: cannot access '/media/pi/USBSTICK': Permission denied

**Comment by bruesche** [comment]
da wird dann wohl der Fehler sein... 

Habe aber eigentlich schon den Ordner komplette Berechtigung gegeben:

pi@piflur:/media/pi $ ls -ltra
total 32
drwxr-xr-x  3 root root  4096 Dec 17 10:11 ..
drwxrwxrwx  1 pi   pi   24576 Dec 18 14:52 USBSTICK
drwxr-x---+ 3 root root  4096 Jan 17 16:00 .

**Comment by simatec** [comment]
Du könntest den User iobroker in die Gruppe pi packen

**Comment by bruesche** [comment]
Hab ich gerade mal versucht:
sudo usermod -aG pi iobroker

in /etc/group ist es auch dadurch sauber drin:
<img width="255" alt="Bildschirmfoto 2024-01-17 um 21 20 48" src="https://github.com/simatec/ioBroker.backitup/assets/62746518/172bba19-21bf-4c51-b2a5-1cfac0a58719">

und reboot ausgeführt. Trotzdem "permission denied" bei 
sudo -u iobroker ls -lah /media/pi/USBSTICK

**Comment by simatec** [comment]
Was die Rechte der einzelnen User angeht, kann dir eventuell @Grothesk242 weiterhelfen.

**Comment by Grothesk242** [comment]
Wie wird das Dateisystem gemountet?
```
mount
```
sagt?

**Comment by bruesche** [comment]
Hi,

mount sagt zum USB Stick folgendes:

/dev/sda1 on /media/pi/USBSTICK type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)

**Comment by Grothesk242** [comment]
Per udisks2 gemountet... 
Verwende ich nicht, ich würde das immer klassisch über die fstab machen. 
Hier findet sich aber näheres dazu, wie man per udisks2 auch die Rechte (polkit ist das Stichwort) ändert: 
https://wiki.archlinux.org/title/udisks

**Comment by simatec** [comment]
Packe doch den mount ganz simpel in die fstab und alles ist gut. Die fstab ist der klassische und richtige Weg für einen Auto mount beim booten

**Comment by Grothesk242** [comment]
Nö, du verwendest da auch einen Corner Case. Udisk kommt aus der
Desktop-GUI-Ecke.

Server = ohne GUI = ohne automount von Wechselmedien

bruesche ***@***.***> schrieb am Mo., 22. Jan. 2024, 18:00:

**Comment by simatec** [comment]
Der Link ist zwar schon etwas älter, aber noch immer der richtige Weg

**Comment by Grothesk242** [comment]
Im Grunde schon. Im Detail dürfte das mehr als 10Jahre später anders sein. ntfs-3g ist soweit ich weiß z.B. mittlerweile direkt im Kernel.

**Comment by bruesche** [comment]
Sorry aber ich habe ein frisch aufgesetztes Bookworm genutzt. USB Stick rein und gut war. Mehr habe ich doch gar nicht gemacht. 
manuell geht’s doch auch. Alles gut
