### ISSUE TITLE
Objekte im Baum kopieren

### ISSUE THREAD

**Issue by DEV2DEV-DE** [simatec/ioBroker.backitup#1068]
Da kam im Forum gerade der Wunsch auf, Objekte im Baum auch kopieren zu können.
Also z.B. einen ganzen Ordner, Gerät, Kanal oder auch nur einen einzelnen State auswählen und mit geänderter ID wieder einzufügen.

Mir käme dazu eine Art "search & replace" in den Sinn.
Nach dem Motto: Suche in der jeweiligen Ursprungs-ID nach "abc" und ersetze für die Ziel-ID die Treffer durch "xyz".

Sinn würde das Ganze natürlich nur für Objekte unterhalb von ``0_userdata`` machen.
Allerhöchstens noch für ``javascript``, aber darauf könnte man auch gut verzichten.

**Comment by simatec** [comment]
Hmm ich denke da ist dein Issue im Backup Adapter falsch. Das ist ein Thema für den Admin...

**Comment by DEV2DEV-DE** [comment]
Verklickt. Sorry!
