### ISSUE TITLE
Paperless

### ISSUE THREAD

**Issue by Mephisto090** [simatec/ioBroker.backitup#1071]
Hej,

cool wäre ein Automatisches Backupsystem für Paperless

https://docs.paperless-ngx.com/administration/#exporter

VG

**Comment by simatec** [comment]
Das ist ein Adapter, der deine Iobroker Installation und die dazugehörigen Komponeten wie Datenbanken usw. sichert und wiederherstellt.
Paperless steht hier in keinem Zusammenhang mit iobroker und wird somit nicht integriert werden.
