### ISSUE TITLE
Removal of old backups in combination with NAS copy only deletes in NAS directory.

### ISSUE THREAD

**Issue by jens-maus** [simatec/ioBroker.backitup#1074]
**Describe the bug**  
When backitup is configured to perform a standard ioBroker backup in combination with a "NAS (Copy)" to copy the final backup files to a NAS directory and also the automatic removal of old backup files is configured in the ioBroker backup settings section, backitup only removes old backups in the NAS directory and not in the temporary `/opt/iobroker/backups` path. This in fact already resulted in a full filesystem because over time the local directory is filled up constantly until the local disk space is exhausted.

**To Reproduce**  
1. Go to backitup settings and enable ioBroker backup with e.g. maximum number of kept backups set to 10 and also setup a "NAS (Copy)" operation with the "Delete old NAS backups" enabled as well.
2. Perform more than 10 backups and check the `/opt/iobroker/backups` path.
3. Note that while the NAS directory will only contain the last 10 backups, the `/opt/iobroker/backups` path will contain more than 10 backups.

**Expected behavior**  
Backitup should either also delete all old backups in the `/opt/iobroker/backups` path or should not keep backups at all in the local path in case a NAS(Copy) action is configured as well.

**Versions:**  
 - Adapter version: 2.10.8
 - JS-Controller version: 5.0.19
 - Node version: 18.19.0
 - Operating system: Ubuntu Linux 22.04.3

**Comment by simatec** [comment]
Can you please set the instance of Backitup to debug and post the log of the backup process.
Important here... The deletion process is only triggered during an automatic scheduled backup.

**Comment by jens-maus** [comment]
Thank you for the hin. I just enabled debug checkbox within the adapter config settings and noticed the following after a fresh scheduled backup run:

```
2024-02-01 09:41:50.785  - error: backitup.0 (29132) [iobroker/grafana] Error on Grafana Datasource Request
2024-02-01 09:41:50.815  - error: backitup.0 (29132) [iobroker/grafana] Error on Grafana Dashoard Request: AxiosError: Request failed with status code 401
2024-02-01 09:41:50.821  - error: backitup.0 (29132) [iobroker/grafana] cannot found Grafana Backup files
2024-02-01 09:41:54.940  - error: backitup.0 (29132) [iobroker/clean] Backup files not deleted from /opt/iobroker/backups because some errors.
2024-02-01 09:41:56.137  - error: telegram.1 (19195) Failed sending [chatId - XXXX]: Error: ETELEGRAM: 400 Bad Request: message is too long
```

Noticing now the message `Backup files not deleted from /opt/iobroker/backups because some errors.` it makes perfectly sense that the older backup files are not deleted from `/opt/iobroker/backups`. And that I didn't get any error send via telegram is also clear now because of the `message is too long` error message. Please note, however, that I have set "short notifications" in the backitup config. But it seems that the message is still somewhat too long in case of these kind of errors. However, disabling the unnoticed broken grafana backup connection finally triggered backitup to delete old backups also from `/opt/iobroker/backups`. 

Nevertheless, even thought that this issue point at some issues in my own installation here, allow me to suggest the following changes to prevent others from running into the same issues:

1. If notification is enabled but cannot be delivered (potentially because of a too long message) make sure to try to delivered an additional short generic message so that users notice that notification did not work out. Or make sure to split the too long message into several smaller pieces.
2. If NAS copy operation is correctly deleting old backups in the NAS disk space please consider still wiping backups in the `/opt/iobroker/backups` path, at least for the same type of backup files the NAS(copy) operation is doing a removal. Thus, just omit deletion of older backup files for the specific backup job that failed due to errors (in my case only grafana) but proceed in removal of files for which the individual backup job succeeded.

**Comment by simatec** [comment]
I understand your problem... However, the "bad request" for telegram is incomprehensible to me.
The message should not be too long. Is there any more information in the log? How long is the Telgram message actually? You should also be able to see that in the log... Or in the objects of the Telegram instance. 

I tried to reproduce the error and all I get is this short message.

````
BackItUp:
Your backup was not completely created. Please check the errors!!

grafana: Grafana is not available!
````

**Comment by KoMa1978** [comment]
I have a similar issue, I use "local" backup only (because a scp script grabs all the files) and the files from /opt/iobroker/backups are not getting deleted.

I've set days to 1 but nothing is deleted.

My error is:

`[iobroker/clean] Backup files not deleted from /opt/iobroker/backups because some errors.`

**Comment by KoMa1978** [comment]
You are right ... it was an issue with the "lokal" backup of the influxdb.
I switched to "remote" with IP 127.0.0.1 and it now works as expected including deletion (same settings like API-Token).

**Comment by Pali-33** [comment]
Hello,
i have similar problem, old backups will be not deleted from Google drive. My setting is maximal 45 backups, but momentan i have 69 backups on google drive.
`<html><body>

 
--
backitup.0 | 2024-02-27 00:17:35.543 | debug | [iobroker/historyJSON] done
backitup.0 | 2024-02-27 00:17:35.543 | debug | [iobroker/historyJSON] new history json values created
backitup.0 | 2024-02-27 00:17:35.377 | debug | [iobroker/historyHTML] done
backitup.0 | 2024-02-27 00:17:35.283 | debug | [iobroker/historyHTML] new history html values created
backitup.0 | 2024-02-27 00:17:33.914 | debug | [iobroker/clean] done
backitup.0 | 2024-02-27 00:17:33.909 | debug | [iobroker/clean] delete /opt/iobroker/backups/javascripts_2024_02_18-02_36_52_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:17:33.889 | debug | [iobroker/clean] delete /opt/iobroker/backups/historyDB_2024_02_14-02_36_19_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:17:33.861 | debug | [iobroker/clean] delete /opt/iobroker/backups/iobroker_2024_02_20-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:17:33.688 | debug | [iobroker/googledrive] done
backitup.0 | 2024-02-27 00:17:31.091 | debug | [iobroker/googledrive] Google Drive: Copy javascripts_2024_02_27-00_16_53_backupiobroker.tar.gz...
backitup.0 | 2024-02-27 00:17:00.521 | debug | [iobroker/googledrive] Google Drive: Copy historyDB_2024_02_27-00_16_18_backupiobroker.tar.gz...
backitup.0 | 2024-02-27 00:16:54.640 | debug | [iobroker/googledrive] Google Drive: Copy iobroker_2024_02_27-00_16_10_backupiobroker.tar.gz...
backitup.0 | 2024-02-27 00:16:53.285 | debug | [iobroker/javascripts] done
backitup.0 | 2024-02-27 00:16:53.284 | debug | [iobroker/javascripts] Backup created: /opt/iobroker/backups/javascripts_2024_02_27-00_16_53_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:16:53.284 | debug | [iobroker/javascripts] Javascript tmp directory "/opt/iobroker/backups/tmpScripts" successfully deleted
backitup.0 | 2024-02-27 00:16:53.279 | debug | [iobroker/javascripts] Try deleting the Javascript tmp directory: "/opt/iobroker/backups/tmpScripts"
backitup.0 | 2024-02-27 00:16:53.204 | debug | [iobroker/javascripts] found Script: Kuhlschrank
backitup.0 | 2024-02-27 00:16:53.204 | debug | [iobroker/javascripts] found Script: DTU_offline
backitup.0 | 2024-02-27 00:16:53.204 | debug | [iobroker/javascripts] found Script: pokus
backitup.0 | 2024-02-27 00:16:53.204 | debug | [iobroker/javascripts] found Script: bak-ShellyEM-offline
backitup.0 | 2024-02-27 00:16:53.203 | debug | [iobroker/javascripts] found Script: bak-Tag-Nacht_40W-ver
backitup.0 | 2024-02-27 00:16:53.203 | debug | [iobroker/javascripts] found Script: bak-HLG600_ON-OFF_40W-ver
backitup.0 | 2024-02-27 00:16:53.203 | debug | [iobroker/javascripts] found Script: bak-Ueberschuss_Laden_40W-ver
backitup.0 | 2024-02-27 00:16:53.203 | debug | [iobroker/javascripts] found Script: bak-HLG600_ON-OFF
backitup.0 | 2024-02-27 00:16:53.202 | debug | [iobroker/javascripts] found Script: bak-Ueberschuss_Laden
backitup.0 | 2024-02-27 00:16:53.202 | debug | [iobroker/javascripts] found Script: bak-Ueberschuss_Laden_open
backitup.0 | 2024-02-27 00:16:53.202 | debug | [iobroker/javascripts] found Script: bak-Dimmer-Laden_offline
backitup.0 | 2024-02-27 00:16:53.201 | debug | [iobroker/javascripts] found Script: Tag-Nacht
backitup.0 | 2024-02-27 00:16:53.201 | debug | [iobroker/javascripts] found Script: Raspi_Reboot_AUS
backitup.0 | 2024-02-27 00:16:53.201 | debug | [iobroker/javascripts] found Script: Alles_Aus
backitup.0 | 2024-02-27 00:16:53.200 | debug | [iobroker/javascripts] found Script: Alles_AN
backitup.0 | 2024-02-27 00:16:53.200 | debug | [iobroker/javascripts] found Script: SUN1000_ON-OFF
backitup.0 | 2024-02-27 00:16:53.200 | debug | [iobroker/javascripts] found Script: reboot2
backitup.0 | 2024-02-27 00:16:53.199 | debug | [iobroker/javascripts] found Script: reboot1
backitup.0 | 2024-02-27 00:16:53.199 | debug | [iobroker/javascripts] found Script: Zaehlerstand_aktuell
backitup.0 | 2024-02-27 00:16:53.198 | debug | [iobroker/javascripts] found Script: Ueberschuss_Laden
backitup.0 | 2024-02-27 00:16:53.196 | debug | [iobroker/javascripts] found Script: ShellyEM-offline
backitup.0 | 2024-02-27 00:16:53.126 | debug | [iobroker/javascripts] Created javascript_tmp directory: "/opt/iobroker/backups/tmpScripts"
backitup.0 | 2024-02-27 00:16:52.212 | debug | [iobroker/historyDB] done
backitup.0 | 2024-02-27 00:16:52.208 | debug | [iobroker/historyDB] Backup created: /opt/iobroker/backups/historyDB_2024_02_27-00_16_18_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:16:48.965 | debug | [iobroker/historyDB] Packed 34MB so far...
backitup.0 | 2024-02-27 00:16:38.964 | debug | [iobroker/historyDB] Packed 24MB so far...
backitup.0 | 2024-02-27 00:16:28.971 | debug | [iobroker/historyDB] Packed 11MB so far...
backitup.0 | 2024-02-27 00:16:18.961 | debug | [iobroker/historyDB] compress from historyDB started ...
backitup.0 | 2024-02-27 00:16:18.057 | debug | [iobroker/iobroker] done
backitup.0 | 2024-02-27 00:16:17.013 | debug | [iobroker/iobroker] This backup can only be restored with js-controller version up from 4.1
backitup.0 | 2024-02-27 00:16:17.010 | debug | [iobroker/iobroker] Backup created: /opt/iobroker/backups/iobroker_2024_02_27-00_16_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:16:14.913 | debug | [iobroker/iobroker] host.iobroker 977 objects saved
backitup.0 | 2024-02-27 00:16:12.983 | debug | [iobroker/iobroker] host.iobroker 740 states saved
backitup.0 | 2024-02-27 00:16:10.157 | debug | Backup has started ...
backitup.0 | 2024-02-27 00:16:10.085 | debug | The local storage check was completed successfully. On the host "iobroker" are currently 53009 MB free space available!
backitup.0 | 2024-02-27 00:15:29.456 | debug | detect last backup file: iobroker_2024_02_26-23_58_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.452 | debug | detect backup file 33 from googledrive: iobroker_2024_01_27-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.451 | debug | detect backup file 32 from googledrive: iobroker_2024_01_28-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.450 | debug | detect backup file 31 from googledrive: iobroker_2024_01_29-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.449 | debug | detect backup file 30 from googledrive: iobroker_2024_01_30-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.446 | debug | detect backup file 29 from googledrive: iobroker_2024_01_31-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.444 | debug | detect backup file 28 from googledrive: iobroker_2024_02_01-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.443 | debug | detect backup file 27 from googledrive: iobroker_2024_02_02-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.442 | debug | detect backup file 26 from googledrive: iobroker_2024_02_03-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.441 | debug | detect backup file 25 from googledrive: iobroker_2024_02_04-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.440 | debug | detect backup file 24 from googledrive: iobroker_2024_02_05-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.439 | debug | detect backup file 23 from googledrive: iobroker_2024_02_06-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.438 | debug | detect backup file 22 from googledrive: iobroker_2024_02_07-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.437 | debug | detect backup file 21 from googledrive: iobroker_2024_02_08-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.436 | debug | detect backup file 20 from googledrive: iobroker_2024_02_09-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.436 | debug | detect backup file 19 from googledrive: iobroker_2024_02_10-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.435 | debug | detect backup file 18 from googledrive: iobroker_2024_02_11-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.434 | debug | detect backup file 17 from googledrive: iobroker_2024_02_12-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.433 | debug | detect backup file 16 from googledrive: iobroker_2024_02_13-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.431 | debug | detect backup file 15 from googledrive: iobroker_2024_02_14-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.430 | debug | detect backup file 14 from googledrive: iobroker_2024_02_15-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.429 | debug | detect backup file 13 from googledrive: iobroker_2024_02_16-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.428 | debug | detect backup file 12 from googledrive: iobroker_2024_02_17-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.428 | debug | detect backup file 11 from googledrive: iobroker_2024_02_18-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.427 | debug | detect backup file 10 from googledrive: iobroker_2024_02_19-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.426 | debug | detect backup file 9 from googledrive: iobroker_2024_02_20-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.425 | debug | detect backup file 8 from googledrive: iobroker_2024_02_21-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.423 | debug | detect backup file 7 from googledrive: iobroker_2024_02_22-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.422 | debug | detect backup file 6 from googledrive: iobroker_2024_02_23-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.421 | debug | detect backup file 5 from googledrive: iobroker_2024_02_24-02_36_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.420 | debug | detect backup file 4 from googledrive: iobroker_2024_02_25-02_36_22_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.417 | debug | detect backup file 3 from googledrive: iobroker_2024_02_26-02_36_22_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.416 | debug | detect backup file 2 from googledrive: iobroker_2024_02_26-23_54_18_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:29.414 | debug | detect backup file 1 from googledrive: iobroker_2024_02_26-23_58_10_backupiobroker.tar.gz
backitup.0 | 2024-02-27 00:15:25.498 | info | [iobroker] backup will be activated at 00:16 every 1 day(s)
backitup.0 | 2024-02-27 00:15:25.473 | debug | Backitup has recognized a linux system


</body>
</html>`

**Comment by simatec** [comment]
Please post your Config in a JSON File

**Comment by Pali-33** [comment]
here my config (i have just edit the google drive token)
[system.adapter.backitup.0.json](https://github.com/simatec/ioBroker.backitup/files/14422723/system.adapter.backitup.0.json)

yesterday i have deleted the backitup instace and adapter too and rebootet. After that install backitup again, but no success, the old backups on google drive are not deleted.

**Comment by simatec** [comment]
Backups are never deleted during manual backups
https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch#l%C3%B6schen-alter-backups

**Comment by Pali-33** [comment]
Darf man hier auf Deutsch schreiben? Ich versuchs...
Ich weiss, dass die Backups nicht gelöscht werden bei manuell ausgelöstem Backup.
Bei mir wird jeden Tag um 02:37 der Backup AUTOMATISCH gestartet. Die alte Backups werden trotzdem nicht gelöscht (auf Google Drive). Mittlerweile habe ich dort 70 Backups, eingestellt sind 45.

Jetzt ist mir aufgefallen in meinem obigem .log, dass dort nur 33 backup files detectet werden, obwohl im Google Drive ca 68 ioBroker-backup-Files waren. Vielleicht ist dort das problem:

2024-02-27 00:15:29.452 - debug: backitup.0 (2470) detect backup file 33 from googledrive: iobroker_2024_01_27-02_36_10_backupiobroker.tar.gz

**Comment by simatec** [comment]
Lösche mal die Backups, die nicht erkannt werden händisch und beobachte es im Anschluss mal

**Comment by Pali-33** [comment]
sooo ... ich habe das jetzt ausgiebig getestet und festgestellt, dass es entweder so gewollt ist oder ist es ein BUG.
Zusammenfassung:
  Problem: wenn die Einstellung für Anzahl der Sicherungen mehr als 33 ist, werden die alten backups nicht gelöscht (auf google drive und ich glaube auch lokal).
  Ursache: BackItup erkennt nur die letzten 33 backups. Der erste erkannte Backup ist immer der aktuellste und dann werden nur 33 (bzw. 32) weitere ältere erkannt.
Wenn ich die Backups-Anzahl auf 33 oder weniger einstelle, dann funktioniert es fast so wie es soll. Dann werden die restlichen Backups bis 33 gelöscht. Falls allerdings noch weitere ältere existieren, diese werden nicht gelöscht (weil die auch nicht erkannt werden). 
Also nehmen wir an, ich habe insgesamt 40 backups gespeichert (auf google drive). In der Einstellung habe ich 30 Stück eingegeben. Bei nächstem automatischen Backup werden die Backups 31,32,33 gelöscht und 34 bis 40 bleiben unberührt. 
Bei eingestellten 34 Stück oder mehr wird nichts mehr gelöscht. Weil erkannt werden immer nur maximal letzte 33. Die eingestellte Anzahl von 34 wird nie erkannt und daher auch nichts gelöscht.

Fazit für mich: 
Wenn ich das jetzt verstehe, warum das so ist, kann ich damit leben. Ich werde einfach die Backup-Anzahl auf 32 Stellen, auf google drive  maximal 32/33 backups belassen und dann wird es gut funktionieren.
Falls gewünscht, kann ich gerne in Zukunft dieses Verhalten wieder prüfen ...

PS: ich werde jetzt noch schauen, wie das mit den lokalen backups aussieht. Weil ich den Eindruck habe, dass auch die lokalen backups nicht gelöscht wurden.

**Comment by Pali-33** [comment]
ok, danke für die Überprüfung ... dann ist das Problem bei mir.
Ich habe vor ein paar Tagen fast alle Backups gelöscht (lokal und auch Google drive) und die Anzahl der Backups auf 32 eingestellt. Das reicht mir auch (muss nicht 45 sein).  Wenn ich in einem Monat auf diese Anzahl komme, werde ich dann vielleicht nochmal testen mit 40-45. Und werde dann nochmal berichten.

**Comment by Pali-33** [comment]
Hi,
vor ein paar Tagen wurde die Anzahl von Backups wieder die eingestellte 32 erreicht. Bei dem nächsten Backup wurde dann der älteste gelöscht ... so weit alles gut.
Dann habe ich die Anzahl auf 35 geändert. Das wurde gestern erreicht. Heute bei dem nächsten Backup wurde nicht der älteste Backup gelöscht und daher habe ich jetzt auf Google-Drive 36 backups gespeichert. 
Ich glaube es wird so weiter laufen, es wird nichts mehr gelöscht. Erkannt werden wieder nur 33 Backups:

`2024-03-19 22:25:48.495  - debug: backitup.0 (10840) detect backup file 30 from googledrive: iobroker_2024_02_26-23_58_10_backupiobroker.tar.gz

2024-03-19 22:25:48.495  - debug: backitup.0 (10840) detect backup file 31 from googledrive: iobroker_2024_02_26-23_54_18_backupiobroker.tar.gz

2024-03-19 22:25:48.496  - debug: backitup.0 (10840) detect backup file 32 from googledrive: iobroker_2024_02_26-02_36_22_backupiobroker.tar.gz

2024-03-19 22:25:48.496  - debug: backitup.0 (10840) detect backup file 33 from googledrive: iobroker_2024_02_25-02_36_22_backupiobroker.tar.gz

2024-03-19 22:25:48.499  - debug: backitup.0 (10840) detect last backup file: iobroker_2024_03_19-02_37_10_backupiobroker.tar.gz
`
Falls das Problem bei mir liegt, kann ich damit leben, werde die Anzahl auf 32 stellen und alles wird gut.
Falls ich etwas versuchen/testen soll, mache ich gerne.

installierte Backitup version: 2.10.11
Node.js: v18.19.1
NPM: 10.2.4
