### ISSUE TITLE
Backup VIS-Views as separate ZIP files

### ISSUE THREAD

**Issue by KoMa1978** [simatec/ioBroker.backitup#1077]
Hi,

It would be great, if you can add an option similar to the "Javascript" option to backup VIS projects in separate zip files.

Yes I know all the files are already included in the backup but if we have ZIP files (similar to the ones I can download from the vis Editor Project Export), it would be much easier to import/restore only a single project.

Thanks a lot

**Comment by simatec** [comment]
We have discussed this several times in the dev meeting and have decided against it, as many dependencies and user errors can lead to problems when restoring.

The VIS is part of the iobroker backup.
If you want to back up the zip files, you can do this via the VIS webif.
