### ISSUE TITLE
Separate setting for different destinations regarding the number of backups

### ISSUE THREAD

**Issue by Tobsen1599** [simatec/ioBroker.backitup#1082]
**Is your feature request related to a problem? Please describe.**
The number of backups can only be set in general. I therefore have a problem if I want to store backups for a longer period of time but do not have the local storage space available.

**Describe the solution you'd like**
Due to limited storage space, it would be nice if the number of locally stored backups could be set separately from externally stored backups (in my case Webdav). This would allow me to always store e.g. 5 backups locally under opt/iobroker/backups and store a much larger number (e.g. 90 ) on my webdav target.

**Describe alternatives you've considered**
An alternative would be a script that regularly cleans up the folder opt/iobroker/backups.

**Comment by Tobsen1599** [comment]
Sorry, then I have expressed myself incomprehensibly. I would like to limit the number of backups both for the local storage and for WebDAV. However, each with a different number.

**Comment by simatec** [comment]
add in v3.0.12
