### ISSUE TITLE
can't connect to OneDrive Business!?

### ISSUE THREAD

**Issue by fmueller25** [simatec/ioBroker.backitup#1085]
i can't connect to OneDrive for Business. Any chance to set this up correctly?

Thanx

**Comment by simatec** [comment]
Please post the Debuglog and more Information...

**Comment by fmueller25** [comment]
the provided oauth2 link in the adapter is only for the live.com private Microsoft account not for MS business 365. So no debuglog without the correct link ;)

**Comment by simatec** [comment]
Is there a comparable authlink for business? no one is familiar with it.

**Comment by fmueller25** [comment]
It looks like this: https://login.microsoftonline.com/common/oauth2/v2.0/authorize

https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow

**Comment by simatec** [comment]
Can you please test whether authorization is possible with this address?
Copy the URL generated by Backitup and replace the first part with the URL from your post

`https://login.microsoftonline.com/common/oauth2/v2.0/authorize[?&scope=offline_access.....`

**Comment by fmueller25** [comment]
now i can login and create the app for entra, get back the code but it ends with following error
![Screenshot 2024-02-28 134650](https://github.com/simatec/ioBroker.backitup/assets/15609369/766bd80d-6a01-47f7-81d9-c94ebe76dc32)

**Comment by simatec** [comment]
According to your picture, you did not copy the complete code from the address bar.
You have to copy everything after `code=`

**Comment by fmueller25** [comment]
its the complete code after code=
0.AQsAeslnqT4CSU26I7Cis7wy2X3w950e_fVGoEViOoE7SqiEAA4.AgABAAIAAADnfolhJpSnRYB1SVj-Hgd8AgDs_wUA9P-mpZfU_lOcdOsUJlpkihkfUHHJY8-uAutTx45gGn_YhEFSeWVS3CSkq8zQr6gMwBEsRjs_MoHswfxcibMP9CquUTYpdIk48zTuWi6PRS8Q2S6XaNHLXEvoWGZyuTq3knu8xYqQO5Tu3qBNB_z-M4m45fCAic3V-ExilLyHsca7_JKC5V7yt3-f41hXsCneLaosHM-IX550ghOLebP8qnpniL0M17b_y9UL4dBbALmmM5BRdM_eIWpf9MH5EOaUPYCZUr29-NsXvP3LdNoKbdRE0bjEfkDw6gDMaciJ33mVJsx5DusuYa5Mr-22FFEbL4CXEv86vifjjX18nACjEG4HI7eywaulsHopktubm66BZhvXuEUmy-ISLubjEDPV5KRw0ezcAuXcYGXkykt2eY3ypvIW8AHNwxuDpvbIbtXMgNNS04JEMIen192YJOYJY7vDpwxa-CSknqYrJVN_JfWlL6PPlF26HAhLG0VXrlu_0RxYpw_Ut6BrDDpqms3-r15DUSAr2qSkSC0UKgVYLWtB7XP3bBGoNIpvwtnAHOiB0_AzlcdqDN5C4EXcZ3tqDo50aNci_aq_bhFsWujClFKngiUvVNy21OJ9ro-w58Hgia2XzM38bnxfQXuVzschzw_RC6BQMQK9y0Q-DTwWt6fcmGAARCCIqSqm66aKBxX3mKbQTkqeDOH-GDZQahgR-Udqly72HfkWxRpRFAIKTGI_5hHbRpB8KB2Mej11GmRrFfJy-SiwFf4nihJ-_vEj4nPnSzlifxz-BRw&session_state=23c0c67e-1408-45a6-a3f2-bd90022fe2f7

**Comment by fmueller25** [comment]
the same, error no answer

**Comment by fmueller25** [comment]
maybe you can search for the right transmission here at the onedrive linux client. it is working fine with the business onedrive:
https://github.com/abraunegg/onedrive/tree/master

**Comment by simatec** [comment]
This Code is to much ....
The address is this
`https://login.microsoftonline.com/common/oauth2/nativeclient?code=M.XXXX_BL2.2.U.XXXXXXXX-8db6-XXXX-6657-XXXXXXXXXXXX`

**Comment by simatec** [comment]
This is the same:
https://github.com/abraunegg/onedrive/blob/1a88d33be3e2c6747c5621ab9d97df9cd3ee727a/src/onedrive.d#L28
https://github.com/abraunegg/onedrive/blob/1a88d33be3e2c6747c5621ab9d97df9cd3ee727a/src/onedrive.d#L63

Please try the address:
`https://login.microsoftonline.com/common/oauth2/v2.0/authorize?scope=offline_access%20files.readwrite.all&response_type=code&prompt=login&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient&client_id=9df7f07d-fd1e-46f5-a045-623a813b4aa8`

**Comment by fmueller25** [comment]
complete response as follows:
https://login.microsoftonline.com/common/oauth2/nativeclient?code=0.AQsAeslnqT4CSU26I7Cis7wy2X3w950e_fVGoEViOoE7SqiEAA4.AgABAAIAAADnfolhJpSnRYB1SVj-Hgd8AgDs_wUA9P_22BnT5UopeYE2hovDI2oS9gUExmlyUmrPBG7NxmktF2KcjZmjuurEmbwEG8HUtWPc54fH3eg-qS0XES-uonv8Ifyw1NbufFh4vLulSqn4bItjlzVQQjHKXhRhHPZct3N93XZyCkGt5YPxZRNyltp4B7_ztpEtq3A0D4gSv2gKBD7WZQp1ihRKYT3W54nq7WmyV41r4JuXNkRFZzNh4J-1zaL9oCeMKYywV7n1m7dQ4meZEbnqKiJzVEmgL_4OdJ-OwNvR-e84Gk4AL54K0blpZUAe-CmupSTclxntcMNgLWJaQr0Go27ZanL3he-Cs3mKE2jKSYdMA9IbO928R433-p2IG2CWNw3oKJ4AwEWjmpeEDIRzJrBGaM21MWBuucZFYw-FW9tWn0MFbggSaATfMETjouEfYS8m_dASpIWnF6AbDq2JroM6RveyrH2pzc3rDZ-RDkcpjOLyD8gWonQsaKSx4NPVhjD5XpTFloSUCP6X78r00_nbQ5b4aK31zAe3WwJ2ZSnkEU_ATKr4BPC8Wc70qDdMTal6_Q8E58Ef41lyJw-h7SvUcEgm8wuYoqyZDZYQ8nqfG6JzBNAKyWoE3uI0FgyxSsj5B5cIyyUf0q5BFp5Aejz1F_6xUFN9GaUe4JWeLoAKrPOCZgEXGSQ3vqouQGl7ueCeKvBodcEUCfmXrtZZIZAhMj3uv6-KTFNI42VUuPVhgZEVaRz6We0weA6km_AGobZHwDJRGjAzPnTZq3DxsHXKo6aOPPJ1-QWGlw&session_state=23c0c67e-1408-45a6-a3f2-bd90022fe2f7

still with error no answe
