### ISSUE TITLE
Backups from FTP is shown only at 9.2.24. All Backups after this Date is not shown. 

### ISSUE THREAD

**Issue by Radeler** [simatec/ioBroker.backitup#1086]
**Describe the bug**  

Backups from FTP is shown only at 9.2.24. All Backups after this Date is not shown. 
Backup is making every day at 2.00 AM

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version> v2.10.11
 - JS-Controller version: <js-controller-version>  5.0.19
 - Node version: <node-version>   v18.19.1
 - Operating system: <os-name> Debian

**Additional context**  
![grafik](https://github.com/simatec/ioBroker.backitup/assets/145900302/34717eda-ca47-4b60-8e92-a94e0e0a19b0)

**Comment by simatec** [comment]
Please post your Debuglog from Backitup Start and the Config in JSON File

**Comment by Radeler** [comment]
I hope this is what you need, thanks.
[iobroker.current.log](https://github.com/simatec/ioBroker.backitup/files/14463495/iobroker.current.log)
[system.adapter.backitup.0.json](https://github.com/simatec/ioBroker.backitup/files/14463499/system.adapter.backitup.0.json)

**Comment by simatec** [comment]
Your backups will never be deleted. 

How much is there on the FTP? 
I wouldn't use FTP either. Better CIFS or NFS mount. 
what kind of NAS do you have?

**Comment by Radeler** [comment]
Your backups will never be deleted.      Yes i know
How much is there on the FTP?     1139 Files
what kind of NAS do you have?    Fritzbox Nas

**Comment by simatec** [comment]
1139 Backups??? Why??
Please use the CIFS mount of the FB for a backup. This will get rid of all worries and FTP is no longer needed.

Nowadays, FTP should only be an emergency solution if nothing else works

**Comment by Radeler** [comment]
Well, unfortunately the Fritzbox doesn't allow this via CIFS. Password and user are absolutely correct. It only works on the Fritz via FTP.
Error: Command failed: mount -t cifs -o username=xxxxx,password=****,domain=FRITZ.NAS,cache=loose,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.xx.xxx/Samsung_USB/IOBrokerBackup /opt/iobroker/backups mount.cifs: permission denied: no match for /opt/iobroker/backups found in /etc/fstab

**Comment by simatec** [comment]
https://github.com/simatec/ioBroker.backitup/wiki/Diverse-Anleitungen-für-ioBroker.backitup#cifs-smb-freigaben-unter-fritznas-7-auf-einer-fritzbox

For FB Noserverino an Cache loose = true
Mount as root true

`sudo apt update && sudo apt install cifs-utils`

**Comment by Radeler** [comment]
This three things was the solution. Thank you verry much. 

![grafik](https://github.com/simatec/ioBroker.backitup/assets/145900302/9f5d30a3-645e-4aec-a19a-6ad86039ae1b)
