### ISSUE TITLE
Backitup Adapter sichert sqlite.db nicht vollständig

### ISSUE THREAD

**Issue by jomahol** [simatec/ioBroker.backitup#1087]
Laut Protokoll läuft das Backup fehlerfrei durch.
Mit der Standardvorgabe unter "SQLITE3 Einstellungen/SQLite3 Dateipfad" = 'sqlite.db' wird zwar eine 'sqlite.db' im Sicherungs-Archiv abgelegt, das ist aber nicht die zu sichernde Datenbank sondern nur irgendeine Textdatei.

Um die Datenbank zu sichern, muss  unter "SQLite3 Dateipfad" der **komplette** Dateipfad eingetragen werden.
z.B. für Linux  "/opt/iobroker/iobroker-data/sqlite/sqlite.db"

**Comment by simatec** [comment]
Add in v2.11.0
