### ISSUE TITLE
Sentry-state does not synchronize between "Instances"-Screen and "Objects"

### ISSUE THREAD

**Issue by invidianer** [simatec/ioBroker.backitup#1093]
**Describe the bug**  
Sentry-state does not synchronize between "Instances"-Screen and "Objects" (system/adapter/backitup/0/plugins/sentry/enabled is EVERYTIME "false)". Also, if one turns Sentry on by clicking on the therefore icon under "Instances".

This behavior regarding other adapters was described here:
https://forum.iobroker.net/topic/46921/meldungen-an-sentry-iobroker-net-deaktivieren/20

EDIT: If one pause the adapter before, then Sentry can be switched on and off correctly (synchronization between "Instances"-Screen and "Objects" functions). If one try to switch it without pausing the adapter ("on the fly"), it does not.

**Comment by simatec** [comment]
Removed in v3.0.3, as it is configurable in the admin
