### ISSUE TITLE
influxDB v1 Restore does not work

### ISSUE THREAD

**Issue by unstressable** [simatec/ioBroker.backitup#1094]
Restore does not work:

`Started restore ...
[DEBUG] [influxDB] - Created tmp directory
[DEBUG] [influxDB] - Start infuxDB Restore ...
[DEBUG] [influxDB] - influxdb.0 is stopped
[ERROR] [influxDB] - 2024/03/24 22:05:33 error updating meta: DB metadata not changed. database may already exist
restore: DB metadata not changed. database may already exist

[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[DEBUG] [influxDB] - infuxDB Restore completed successfully
[EXIT] influxDB restore done
[DEBUG] [influxDB] - influxdb.0 started`

I manually deleted the existing database, stopped influx service, tested while running and anything else.

**Comment by simatec** [comment]
> error updating meta: DB metadata not changed. database may already exist

Die datenbank vorher bitte löschen...

**Comment by unstressable** [comment]
I did so, I did the restore manually over shell and influx, that worked.
