### ISSUE TITLE
Webdav Anbindung zu MagentaCloud funktioniert nicht mehr

### ISSUE THREAD

**Issue by heitec11** [simatec/ioBroker.backitup#1095]
Die Verbindung zur MagentaCloud per WebDav funktioniert seit gestern nicht mehr.
Ein Update auf 2.11 hat keine Veränderung gebracht.

cannot conntect to WebDAV: Error: Invalid response: 401 Unauthorized

Neue Eingabe von Benutzer und Passwort ohne Erfolg.

Könnte aber auch ein Problem bei der Telekom sein:
https://telekomhilft.telekom.de/t5/MagentaCLOUD/webDAV-Zugriff-gestoert/m-p/6667521#M76971

Browser Ok
WebDAV Fault
iPhone Ok

**Comment by simatec** [comment]
> Invalid response: 401 Unauthorized

Da steht der Fehler... Vielleicht verlangt Magenta eine andere Einwahl? https?
