### ISSUE TITLE
onedrive upload, wie funktioniert er

### ISSUE THREAD

**Issue by Jumbo125** [simatec/ioBroker.backitup#1107]
Hallo 
Super Projekt! 

Bitte um Verzeihung dass ich ein issue wegen einer Frage öffne.

Ich möchte gerne ein paar Daten auf die onedrive laden und schaffe es nicht ohne den umständlichen weg über azure.portal.... mit app registration.... 

Darf ich in meiner Verzweiflung fragen, wie ihr das gelöst habt? Mittels eines token????

Vielen Dank
Mit freundlichen Grüßen
Jumbo

**Comment by simatec** [comment]
Ohne App geht es nicht. Für Backitup wurde eine App erstellt und diese wird für den Adapter benutzt.

**Comment by Jumbo125** [comment]
ich scheitere an der erstellung eines php scripts mit upload zur onedrive. würden sie mir helfen? oder haben sie es ohne php realisiert. ich bin mittlerweile soweit das ich einen app-token erhalten, welcher aber nicht als authent. bearer funktioniert

**Comment by simatec** [comment]
Dieser Adapter ist in JavaScript geschrieben. PHP kommt nicht zum Einsatz.
Hier die OneDriveLib
https://github.com/simatec/ioBroker.backitup/blob/master/lib/oneDriveLib.js

**Comment by Jumbo125** [comment]
Danke dir

Die auth. Url ist interessant. simateccloud.de

Ich nehme an das ist euer Server.

**Comment by simatec** [comment]
Die URL ist nicht relevant... Du kannst die Daten auch in deinem Code fest einbauen

**Comment by Jumbo125** [comment]
verwendet ihr bei client id auch diesen schlüssel?
![image](https://github.com/simatec/ioBroker.backitup/assets/61667987/5337226f-a679-48e9-b4e6-07c25f75bc30)

und bei den permissons diese?
![image](https://github.com/simatec/ioBroker.backitup/assets/61667987/486d1235-ca2a-438e-ac29-3fa406129b65)

die onedrive ist nämlich nicht in der app gelistet und ich bekomme ständig invalid grant

**Comment by simatec** [comment]
Ja genau das ist die ClientID

**Comment by Jumbo125** [comment]
Habt ihr mehr Berechtigungen zugewiesen?
