### ISSUE TITLE
Backup fails with multiple Yahka instances

### ISSUE THREAD

**Issue by DutchmanNL** [simatec/ioBroker.backitup#1108]
**Describe the bug**  
Ich verwende mit grosser Freude den adapter, bisher auch keine Probleme Festellen können.
Auf einer installation mit mehreren Yahka Instanzen läuft das backup leider nicht durch:

```
Started iobroker ...
[DEBUG] [iobroker] - host.HomeMaster 5130 states saved

[DEBUG] [iobroker] - host.HomeMaster 5773 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2024_04_26-17_38_02_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [yahka] - found yahka database: yahka.0,yahka.1,yahka.2,yahka.3,yahka.4,yahka.5,yahka.6,yahka.7,yahka.10,yahka.11,yahka.12,yahka.13,yahka.14,yahka.15,yahka.20
```

Wie man hier sieht bleibt es bei mehreren Yahka Instanzen hängen. Sobald ich homekit deaktivieren laeuft das ioBroker backup sauber durch

Bei einer vergleichbaren test-umgebung mit weniger yahka Instanzen gibt es keine Probleme. 

```
Started iobroker ...
[DEBUG] [iobroker] host.HomeMaster 6633 states saved

[DEBUG] [iobroker] - host.HomeMaster 7801 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2024_04_26-17_49_49_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [yahka] - found yahka database: yahka.0,yahka.1,yahka.2,yahka.3,yahka.4,yahka.5,yahka.6
[DEBUG] [yahka] - done
[DEBUG] [webdav] - Start WebDAV Upload ...
```

Einzigen unterschied den ich in beiden setups erkenne:

- Es sind mehr Yahka Instanzen
- Die instances sind nicht durchgehen nummeriert

**Expected behavior**  
Backups sollte erstellt werden egal wieviele yahka Instanzen anwesend sind oder deren Konfiguration

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 2.11.0
 - JS-Controller version: 4.0.24
 - Node version: 18.17.1
 - Operating system: Docker

Bei eventuellen fragen bitte Kontakt über telegram oder discord

**Comment by simatec** [comment]
Fix for the next Release

**Comment by DutchmanNL** [comment]
> Fix for the next Release

you are a hero thank you soo much !!!
