### ISSUE TITLE
Anmeldung an NAS mit SMB Version 1.0 nicht möglich

### ISSUE THREAD

**Issue by TotKur** [simatec/ioBroker.backitup#1109]
Raspberry / Portainer / IOBroker
Die Anmeldung (mount) an das NAS Buffalo (die nur SMB V1.0 unterstützt) bringt folgende Meldung:
`[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=Datensicherung,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=1.0 //192.168.115.200/Datensicherung/Raspberry /opt/iobroker/backups"
[DEBUG] [mount] - first mount attempt with smb option failed. try next mount attempt without smb option ...
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=Datensicherung,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.115.200/Datensicherung/Raspberry /opt/iobroker/backups"
[ERROR] [mount] - [undefined Error: Command failed: sudo mount -t cifs -o username=Datensicherung,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.115.200/Datensicherung/Raspberry /opt/iobroker/backups
mount error: Server abruptly closed the connection.
This can happen if the server does not support the SMB version you are trying to use.
The default SMB version recently changed from SMB1 to SMB2.1 and above. Try mounting with vers=1.0.
mount error(112): Host is down
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
`
Das mounten auf der Konsole funktioniert mit:
` sudo mount -t cifs -o username=Datensicherung,password=Kennwort***,vers=1.0 //192.168.115.200/Datensicherung/Raspberry /home/pi/DRIVE/share
`

**Versions:**  
 - Adapter version: V2.11.0 
 - IOBroker V6.17.6
 - in einem Portainer V2.19.5
 - JS-Controller version: <V8.0.3
 - Operating system: 
`pi@raspbi5:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`

**Comment by simatec** [comment]
Dann versuche es mal mit dem Expert-Mount und trage dort deinen Konsolenbefehl ein....
`sudo mount -t cifs -o username=Datensicherung,password=Kennwort***,vers=1.0 //192.168.115.200/Datensicherung/Raspberry /opt/iobroker/backups`

**Comment by TotKur** [comment]
Konnte die Ursache und die entsprechende Lösung finden (getestet im Expert-Mount):
den bestehenden Konsolenbefehl:
`sudo mount -t cifs -o username=Datensicherung,password=kennwort***,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=1.0 //192.168.115.200/Datensicherung/Raspberry /opt/iobroker/backups`

mit den Zusatz ",nodfs" wie folgt erweitern:
`sudo mount -t cifs -o username=Datensicherung,password=kennwort***,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=1.0,nodfs //192.168.115.200/Datensicherung/Raspberry /opt/iobroker/backups`

Diese Änderung bitte für SMB Version 1.0 übernehmen

**Comment by simatec** [comment]
Das ist zu speziell und eher ein Thema direkt für dein NAS. Deshalb wird es da keine Anpassung geben. Expert Mount ist hier die richtige Option. Hier können spezielle Parameter selber gesetzt werden.
