### ISSUE TITLE
Restore on windows fails with "Exception-Code: EINVAL: spawn EINVAL"

### ISSUE THREAD

**Issue by ChriD** [simatec/ioBroker.backitup#1115]
The restore on windows fails with this error:

![image](https://github.com/simatec/ioBroker.backitup/assets/2505067/691c3496-e9a3-49d2-8706-bb210de0ea23)

That seems to be a problem due to a new node version. Solution should be included in this link.
https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

I changed the following and it works for windows now again.
Maybe the "spawn" option should only be set if "isWin" is true. Sorry that i do not make a pull request, but i am short of time
![image](https://github.com/simatec/ioBroker.backitup/assets/2505067/a43ddbdb-95b5-4c27-abfb-ea6657cc9de4)

**Comment by simatec** [comment]
Must be checked so that it also works properly under Linux

**Comment by mcm1957** [comment]
see releated windows fixes at i.e. @iobroker/testing and node-red

**Comment by simatec** [comment]
Fix for the next Release 
https://github.com/simatec/ioBroker.backitup/commit/4028d6b1c5a93714be9bb953ec77d42a697dc43a
