### ISSUE TITLE
After upgrade v2.11 to 3.0 influxdb2 backup doesnt work

### ISSUE THREAD

**Issue by cracyfloyd** [simatec/ioBroker.backitup#1117]
**Describe the bug**  
After the upgrade to version 3.0.0 i receive an error with backup my influxdb2 database (via remote other docker)

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
LOG:
07:53:59.995INFOguiBackup gestartet ...
07:54:00.025DEBUGmountdone
07:54:00.994DEBUGiobrokerhost.iobroker-node18 12331 states saved
07:54:01.193DEBUGiobrokerhost.iobroker-node18 15641 objects saved
07:54:02.454DEBUGiobrokerBackup created: /opt/iobroker/backups/iobroker_2024_05_29-07_54_00_backupiobroker.tar.gz
07:54:02.498DEBUGiobrokerThis backup can only be restored with js-controller version up from 4.1
07:54:03.499DEBUGiobrokerdone
07:54:03.652DEBUGinfluxDBInfluxDB-Backup for influxDB-iobroker is started ...
07:54:03.655DEBUGinfluxDBStart InfluxDB Backup ...
07:54:03.659DEBUGinfluxDBInfluxDB Backup tmp directory created
07:54:03.661DEBUGinfluxDBTry deleting the InfluxDB tmp directory: "/opt/iobroker/backups/influxDB_2024_05_29-07_54_03_influxDB-iobroker_backupiobroker"
07:54:03.665ERRORinfluxDBError: Command failed: influx backup --bucket iobroker --host http://172.18.0.12:8086 -t PW@R7lf}
p_ "/opt/iobroker/backups/influxDB_2024_05_29-07_54_03_influxDB-iobroker_backupiobroker"
/bin/sh: 1: Syntax error: "(" unexpected
07:54:03.668DEBUGinfluxDBInfluxDB-Backup for influxDB-iobroker is finish
07:54:03.671DEBUGinfluxDBInfluxDB-Backup for influxDB-fritzbox is started ...
07:54:03.673DEBUGinfluxDBTry deleting the InfluxDB tmp directory: "/opt/iobroker/backups/influxDB_2024_05_29-07_54_03_influxDB-fritzbox_backupiobroker"
07:54:03.712DEBUGinfluxDBInfluxDB tmp directory "/opt/iobroker/backups/influxDB_2024_05_29-07_54_03_influxDB-fritzbox_backupiobroker" successfully deleted
07:54:03.716ERRORinfluxDBError: Command failed: influx backup --bucket fritzboxdb --host http://172.18.0.12:8086 -t PW@R7lf}
p_ "/opt/iobroker/backups/influxDB_2024_05_29-07_54_03_influxDB-fritzbox_backupiobroker"
/bin/sh: 1: Syntax error: "(" unexpected
07:54:03.718DEBUGinfluxDBInfluxDB-Backup for influxDB-fritzbox is finish
07:54:03.720DEBUGinfluxDBdone
07:54:04.883ERRORgrafanaGrafana Backup cannot created. Please check your Configuration
07:54:04.950DEBUGgrafanadone

<img width="1278" alt="Bildschirmfoto 2024-05-29 um 07 48 55" src="https://github.com/simatec/ioBroker.backitup/assets/57620791/853a27c4-85ed-4f84-a963-d6d5bb116a5a">

If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 3.0.0
 - JS-Controller version: 5.0.19
 - Node version: v18.20.3
 - Operating system: Buanet Docker

**Additional context**

**Comment by simatec** [comment]
Fix in v3.0.1
