### ISSUE TITLE
Wunsch: Nächste Backuplauf für VIS

### ISSUE THREAD

**Issue by darkiop** [simatec/ioBroker.backitup#112]
Habe gerade meine VIS für das Backup überarbeitet und bin da auf den Gedanken gekommen in der VIS den Zeitpunkt des nächsten Backuplaufes anzuzeigen.

**Comment by smartboart** [comment]
Hatte ich im Forum auch schon angestoßen.Eine Verstellung der Zeiten in vis fände ich auch gut...

**Comment by peoples0815** [comment]
Als aktuellen Workaround könntet ihr ja ein Script nehmen welches seine Auslöseuhrzeit über angelegte Datenpunkte bezieht, diese könntet ihr dann über Vis ändern. 
Zur Wunschzeit dann einfach die OneClick-Buttons "auslösen".
