### ISSUE TITLE
Version 3.0 Fix Yahka Backup

### ISSUE THREAD

**Issue by Baenker** [simatec/ioBroker.backitup#1120]
Hallo,

kurze Frage zur Version 3.0 bzw dem Yahka Fix.
Ich konnte kein Issue dazu finden. Was genau wurde gefixt? Und seit wann bestand das Problem?

Hintergrund: Homekit kann meine Geräte seit dem letzten Restore nicht mehr steuern. Ich vermute zwar das es nicht am Backup bzw dessen Restore liegt, aber ich suche in alle Richtungen. Habe vor gut zwei Wochen auf das aktuelle Docker Image hochgezogen.

**Comment by simatec** [comment]
Bei dem Fix ging es nur um Instanzen Erkennung. Sprich wenn jemand mehr als eine Instanz von Yahla laufen hat

**Comment by Baenker** [comment]
Ah. Ok. Danke für die Info. Dann hat es nicht mit meinen Problem zu tun.
