### ISSUE TITLE
MYSQL: Konfiguration kann nicht automatisch ermittelt werden

### ISSUE THREAD

**Issue by Norb1204** [simatec/ioBroker.backitup#1121]
Beim Ermitteln der MYSQL Konfiguration mittels Taste in den Instanzeinstellungen vom Adapter kommt eine Warnmeldung "Keine Konfiguration gefunden" und eine Meldung im log. MariaDB ist installiert und korrekt eingestellt im Adapter, Backup funktioniert auch ist halt nur die Warnmeldung die kommt.

<img width="789" alt="image" src="https://github.com/simatec/ioBroker.backitup/assets/132662785/081d7573-1e88-4126-9bed-e9c7bcc6482a">

<img width="785" alt="image" src="https://github.com/simatec/ioBroker.backitup/assets/132662785/7fd21df5-1034-4bfd-bf4e-1724ab27ff88">

**Versions:**  
 - Adapter version: 3.01
 - JS-Controller version: 5.0.19
 - Node version: v18.20.3
 - Operating system: Debian “bookworm”

**Comment by simatec** [comment]
Die Warnung im Log kommt aktuell noch vom admin Adapter und wird gefixt.
Die Meldung in Backitup kommt, wennn du den sql Adapter nicht installiert und konfiguriert hast.

Mit dem Button "Konfiguration ermitteln, übernimmt Backitup die Einstellungen aus dem SQL Adapter und du musst die Felder nicht manuell ausfüllen.

**Comment by Norb1204** [comment]
Der SQL Adapter ist installiert und konfiguriert, deshalb wundert mich die Meldung "Konfiguration nicht gefunden".
Wie gesagt, es funktioniert alles (SQL, Backup usw.), es kommt halt nur die Meldung wenn ich den Button betätige.

Ich hatte vor kurzem von Debian 10 nach 12 hochgezogen (natürlich komplett neu installiert), seitdem ist mir das aufgefallen.

**Comment by simatec** [comment]
Funktioniert es mit v2.11 von Backitup. In v3.0 ist sehr viel am Code umgestellt wurden. Teste mal bitte mit 2.11, damit wir den Fehler eingrenzen können

**Comment by Norb1204** [comment]
Ja, mit 2.11 gehts:

<img width="787" alt="image" src="https://github.com/simatec/ioBroker.backitup/assets/132662785/bc5569a6-a7dc-4d3d-8e95-7de27ed7efb2">

**Comment by simatec** [comment]
Fix in v3.0.2
