### ISSUE TITLE
Setup for Pushover notifications is not saved

### ISSUE THREAD

**Issue by KLIS-IT** [simatec/ioBroker.backitup#1122]
**Describe the bug**  
While setting notifications using pushover, I used instance pushover.0
After saving and reopening settings, instance is empty.
No notifications will be sent.

**To Reproduce**  
1. Go to 'Einstellungen'
2. Click on 'Benachrichtigungen'
3. Select instance 'pushover.0'
4. Click on 'Speichern und Schließen'
5. Go to 'Einstellungen'
6. Click on 'Benachrichtigungen'
7. See empty instance field

**Expected behavior**  
selected instance should be saved and shown

**Screenshots & Logfiles**  
![image](https://github.com/simatec/ioBroker.backitup/assets/20384874/45864cf7-be31-469c-975f-7651d5d76c09)

**Versions:**  
 - Adapter version: 3.0.1
 - JS-Controller version: 5.0.19
 - Node version: v18.20.3
 - Operating system: Raspbian GNU/Linux 10 (buster)

**Comment by simatec** [comment]
Unfortunately I can't recreate it... In my test instances, the pushover instance is saved...

**Comment by KLIS-IT** [comment]
Hi @simatec 

I've created new instance and within it also pushover.0 is saved and notification was sent.
Seems to be an issue to old instance.

BR
