### ISSUE TITLE
Auth token request for OneDrive not working

### ISSUE THREAD

**Issue by KLIS-IT** [simatec/ioBroker.backitup#1123]
**Describe the bug**  
After activation of OneDrive as backup destination a link for requesting Auth token is presented.
Once clicked and access approval in MS account only an empty page is shown.
Unfortunately no auth token is displayed.
Application was successfully added to authorized apps.

**Expected behavior**  
Auth token should be shown

**Screenshots & Logfiles**  
![image](https://github.com/simatec/ioBroker.backitup/assets/20384874/f0fff09c-1570-409c-bd8c-6959971d04d9)

**Versions:**  
Adapter version: 3.0.1
JS-Controller version: 5.0.19
Node version: v18.20.3
Operating system: Raspbian GNU/Linux 10 (buster)
Chrome for Windows: 125.0.6422.142
Edge for Windows: 125.0.2535.79

**Comment by simatec** [comment]
Onedrive displays the token in the redirecting URL at the top of the browser address bar

https://login.microsoftonline.com/common/oauth2/nativeclient?code=XXXXXXXXXXXXXXXXXXXXXXX

It is also in the documentation and in the config of Backitup

**Comment by KLIS-IT** [comment]
Hi @simatec 
Thanks for hint.
With code from URL it's working.
Unfortunately I can't find this hint in doc
![image](https://github.com/simatec/ioBroker.backitup/assets/20384874/b0b4a448-e5c9-4040-b35c-19e99e10cb54)

Best regards
