### ISSUE TITLE
entering auth token GoogleDrive not working

### ISSUE THREAD

**Issue by KLIS-IT** [simatec/ioBroker.backitup#1124]
**Describe the bug**  
After activation of Google Drive as backup destination a link for requesting Auth token is presented.
Once clicked and access approval in Google account only a base64 encoded JSON string is shown.
It is unclear if encoded string or it's content should be entered in adapter settings.
In addition field 'Geben Sie den Code von dieser Seite hier ein' is not accepting any input.

**Expected behavior**  
Auth token should be entered

**Screenshots & Logfiles**  
![image](https://github.com/simatec/ioBroker.backitup/assets/20384874/306ae7aa-0920-4323-822a-8c526fa8c644)

**Versions:**  
Adapter version: 3.0.1
JS-Controller version: 5.0.19
Node version: v18.20.3
Operating system: Raspbian GNU/Linux 10 (buster)
Chrome for Windows: 125.0.6422.142
Edge for Windows: 125.0.2535.79

**Comment by simatec** [comment]
The token issued in the browser must be entered.
This is also stated in the Backitup documentation

**Comment by KLIS-IT** [comment]
Hi @simatec 

Unfortunately filed where I should enter code is not accepting data or is at least not showing any inserted data

**Comment by simatec** [comment]
Fix in v3.0.2

**Comment by KLIS-IT** [comment]
when release 3.0.2 will be available in beta channel?

**Comment by simatec** [comment]
I think in the next 2-3 days
