### ISSUE TITLE
Backup Historie - Fenster bleibt leer

### ISSUE THREAD

**Issue by mbhomie007** [simatec/ioBroker.backitup#1125]
Fenster bleibt leer nach Aufruf der "Backup Historie"

![image](https://github.com/simatec/ioBroker.backitup/assets/64688879/f2087957-05a1-4e5d-a19a-07707e353e88)

![image](https://github.com/simatec/ioBroker.backitup/assets/64688879/a0120ee3-1658-4ec1-a6ce-fa03ac795173)

![image](https://github.com/simatec/ioBroker.backitup/assets/64688879/b617b043-aae3-4647-ade0-6a7f6dac4ed1)

![image](https://github.com/simatec/ioBroker.backitup/assets/64688879/5caba98a-7284-4eb0-8641-16e876e56da8)

**Comment by simatec** [comment]
Kann ich erstmal nicht bestätigen... Mach mal einen Upload des Adapters und teste erneut...

![image](https://github.com/simatec/ioBroker.backitup/assets/39792461/72b7e538-7428-4b05-9de2-e925461f88e8)

**Comment by mbhomie007** [comment]
Ein Neustart des Adapters bringt leider keine Besserung.

**Comment by simatec** [comment]
Du musst einen Upload machen. Im Tab Adapter des iobrokers den Pfeil hoch Button nutzen

**Comment by simatec** [comment]
Ansonsten bitte posten, wie wurde die Version installiert, welche Node Version, Admin Version und js-controller Version sind installiert? 
Debug Konsole des Browsers bitte die eventuellen Fehlermeldungen posten

**Comment by mbhomie007** [comment]
> Du musst einen Upload machen. Im Tab Adapter des iobrokers den Pfeil hoch Button nutzen 

Habe nun einen Upload gemacht, leider keine Besserung.

**Comment by mbhomie007** [comment]
> Ansonsten bitte posten, wie wurde die Version installiert, welche Node Version, Admin Version und js-controller Version sind installiert? 
> Debug Konsole des Browsers bitte die eventuellen Fehlermeldungen posten

Admin 6.17.14
node: v18.20.3
js-controller: 5.0.19

Keine Fehler im Log oder in der Browser Konsole.

**Comment by simatec** [comment]
Was sagt v3.0.2? Wird da ebenfalls bei dir keine Historie angezeigt?

**Comment by mbhomie007** [comment]
Bei 3.0.2 das gleiche Verhalten.

Ich meine ab V3 war das Problem aufgetreten.

**Comment by mbhomie007** [comment]
Unter admin 7.0.1 das gleiche Verhalten.

![image](https://github.com/simatec/ioBroker.backitup/assets/64688879/04b401bf-3d49-4cb8-a7f5-79d2ceec1088)

**Comment by mbhomie007** [comment]
[{"date":"11. Juni 2024 um 03:00 Uhr","name":"iobroker_2024_06_11-03_00_20_backupiobroker.tar.gz","type":"iobroker","storage":"NAS / Kopieren","filesize":null,"error":"none","timestamp":1718067643709},{"date":"10. Juni 2024 um 18:00 Uhr","name":"homematic_2024_06_10-18_00_22_3.75.7.20240601_backupiobroker.tar.sbk","type":"ccu","storage":"NAS / Kopieren","filesize":null,"error":"none","timestamp":1718035243949},{"date":"10. Juni 2024 um 03:00 Uhr","name":"iobroker_2024_06_10-03_00_20_backupiobroker.tar.gz","type":"iobroker","storage":"NAS / Kopieren","filesize":"3 MB","error":"none","timestamp":1717981236250},{"date":"09. Juni 2024 um 18:00 Uhr","name":"homematic_2024_06_09-18_00_22_3.75.7.20240601_backupiobroker.tar.sbk","type":"ccu","storage":"NAS / Kopieren","filesize":"7 MB","error":"none","timestamp":1717948839713},{"date":"09. Juni 2024 um 03:00 Uhr","name":"iobroker_2024_06_09-03_00_20_backupiobroker.tar.gz","type":"iobroker","storage":"NAS / Kopieren","filesize":"3 MB","error":"none","timestamp":1717894836493},{"date":"08. Juni 2024 um 18:00 Uhr","name":"homematic_2024_06_08-18_00_22_3.75.7.20240601_backupiobroker.tar.sbk","type":"ccu","storage":"NAS / Kopieren","filesize":"7 MB","error":"none","timestamp":1717862439373},{"date":"08. Juni 2024 um 03:00 Uhr","name":"iobroker_2024_06_08-03_00_20_backupiobroker.tar.gz","type":"iobroker","storage":"NAS / Kopieren","filesize":"3 MB","error":"none","timestamp":1717808436231},{"date":"07. Juni 2024 um 18:00 Uhr","name":"homematic_2024_06_07-18_00_22_3.75.7.20240601_backupiobroker.tar.sbk","type":"ccu","storage":"NAS / Kopieren","filesize":"7 MB","error":"none","timestamp":1717776039767},{"date":"07. Juni 2024 um 03:00 Uhr","name":"iobroker_2024_06_07-03_00_20_backupiobroker.tar.gz","type":"iobroker","storage":"NAS / Kopieren","filesize":"3 MB","error":"none","timestamp":1717722036377},{"date":"06. Juni 2024 um 18:00 Uhr","name":"homematic_2024_06_06-18_00_22_3.75.7.20240601_backupiobroker.tar.sbk","type":"ccu","storage":"NAS / Kopieren","filesize":"7 MB","error":"none","timestamp":1717689639760},{"date":"06. Juni 2024 um 03:00 Uhr","name":"iobroker_2024_06_06-03_00_20_backupiobroker.tar.gz","type":"iobroker","storage":"NAS / Kopieren","filesize":"3 MB","error":"none","timestamp":1717635636479},{"date":"05. Juni 2024 um 18:00 Uhr","name":"homematic_2024_06_05-18_00_22_3.75.7.20240601_backupiobroker.tar.sbk","type":"ccu","storage":"NAS / Kopieren","filesize":"7 MB","error":"none","timestamp":1717603239805},{"date":"05. Juni 2024 um 03:00 Uhr","name":"iobroker_2024_06_05-03_00_20_backupiobroker.tar.gz","type":"iobroker","storage":"NAS / Kopieren","filesize":"3 MB","error":"none","timestamp":1717549236179},{"date":"04. Juni 2024 um 18:00 Uhr","name":"homematic_2024_06_04-18_00_22_3.75.7.20240601_backupiobroker.tar.sbk","type":"ccu","storage":"NAS / Kopieren","filesize":"7 MB","error":"none","timestamp":1717516839986},{"date":"04. Juni 2024 um 03:00 Uhr","name":"iobroker_2024_06_04-03_00_20_backupiobroker.tar.gz","type":"iobroker","storage":"NAS / Kopieren","filesize":"3 MB","error":"none","timestamp":1717462836681},{"date":"03. Juni 2024 um 18:00 Uhr","name":"homematic_2024_06_03-18_00_22_3.75.7.20240601_backupiobroker.tar.sbk","type":"ccu","storage":"NAS / Kopieren","filesize":"7 MB","error":"none","timestamp":1717430440178},{"date":"03. Juni 2024 um 03:00 Uhr","name":"iobroker_2024_06_03-03_00_20_backupiobroker.tar.gz","type":"iobroker","storage":"NAS / Kopieren","filesize":"3 MB","error":"none","timestamp":1717376436410},{"date":"02. Juni 2024 um 18:00 Uhr","name":"homematic_2024_06_02-18_00_22_3.75.7.20240420_backupiobroker.tar.sbk","type":"ccu","storage":"NAS / Kopieren","filesize":"7 MB","error":"none","timestamp":1717344039923},{"date":"02. Juni 2024 um 03:00 Uhr","name":"iobroker_2024_06_02-03_00_20_backupiobroker.tar.gz","type":"iobroker","storage":"NAS / Kopieren","filesize":"3 MB","error":"none","timestamp":1717290040256},{"date":"01. Juni 2024 um 18:00 Uhr","name":"homematic_2024_06_01-18_00_22_3.75.7.20240420_backupiobroker.tar.sbk","type":"ccu","storage":"NAS / Kopieren","filesize":"7 MB","error":"none","timestamp":1717257639799},{"date":"01. Juni 2024 um 03:00 Uhr","name":"iobroker_2024_06_01-03_00_20_backupiobroker.tar.gz","type":"iobroker","storage":"NAS / Kopieren","filesize":"3 MB","error":"none","timestamp":1717203644967},{"date":"31. Mai 2024 um 18:00 Uhr","name":"homematic_2024_05_31-18_00_22_3.75.7.20240420_backupiobroker.tar.sbk","type":"ccu","storage":"NAS / Kopieren","filesize":"7 MB","error":"none","timestamp":1717171239889},{"date":"31. Mai 2024 um 03:00 Uhr","name":"iobroker_2024_05_31-03_00_20_backupiobroker.tar.gz","type":"iobroker","storage":"NAS / Kopieren","filesize":"3 MB","error":"none","timestamp":1717117236552},{"date":"30. Mai 2024 um 18:00 Uhr","name":"homematic_2024_05_30-18_00_22_3.75.7.20240420_backupiobroker.tar.sbk","type":"ccu","storage":"NAS / Kopieren","filesize":"7 MB","error":"none","timestamp":1717084839651},{"date":"30. Mai 2024 um 03:00 Uhr","name":"iobroker_2024_05_30-03_00_20_backupiobroker.tar.gz","type":"iobroker","storage":"NAS / Kopieren","filesize":"3 MB","error":"none","timestamp":1717030837632}]

**Comment by simatec** [comment]
> ![image](https://private-user-images.githubusercontent.com/64688879/338620897-4168c26d-69bb-4c2d-b635-0ccb960a376b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTU4OTYsIm5iZiI6MTcxODExNTU5NiwicGF0aCI6Ii82NDY4ODg3OS8zMzg2MjA4OTctNDE2OGMyNmQtNjliYi00YzJkLWI2MzUtMGNjYjk2MGEzNzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE0MTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMTQ4MTQ5ZmQ5M2RkNjM0MmFmYzZkNGQwYjZiNTQ4YjA3MzdiNTJmYzFjMmRmMjYyNTdkMDk3MzQ3YmE2NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BzVpouv3LdXHMK_rtsvNS12bV88Dr0F83Zpzupf0tbI)

Die Warnungen kannst du ignorieren ... die kommen vom Admin Adapter

**Comment by mbhomie007** [comment]
Unter HAUPTEINSTELLUNGEN werden nicht mehr die aktivierten Sicherungen angezeigt:
![image](https://github.com/simatec/ioBroker.backitup/assets/64688879/5e25dad9-12d2-41e9-8558-13addf053ce6)

![image](https://github.com/simatec/ioBroker.backitup/assets/64688879/eac1d34b-42d4-414d-beba-4e430f87f2cc)

**Comment by simatec** [comment]
> Unter HAUPTEINSTELLUNGEN werden nicht mehr die aktivierten Sicherungen angezeigt: ![image](https://private-user-images.githubusercontent.com/64688879/338621558-5e25dad9-12d2-41e9-8558-13addf053ce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTYwMTMsIm5iZiI6MTcxODExNTcxMywicGF0aCI6Ii82NDY4ODg3OS8zMzg2MjE1NTgtNWUyNWRhZDktMTJkMi00MWU5LTg1NTgtMTNhZGRmMDUzY2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE0MjE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YTFjZmY1YTI3ZmNmZTBmOTRmMTBjZDA4YWMzNmIxMTYwMGNlM2E3YTlkOWU0MzlhOGUyYmY5ODc2ZDRlNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.izJILhREED14J_T8mx-0sMdA9b0Tv9CXVJGIdYQdv_E)
> 

Admin 7.0.1 wurde zurückgezogen, da es Fehler hat
https://github.com/ioBroker/ioBroker.admin/issues/2496

Bitte wieder zurück auf v6.17.14 gehen

**Comment by simatec** [comment]
Bitte installiere mal die aktuelle Version von Backitup über Github... Da sollte nun die History funktionieren

Und gehe bitte zurück auf admin v6.17.14

**Comment by mbhomie007** [comment]
Super, läuft wieder mit der aktuellen GitHub Version. 
![image](https://github.com/simatec/ioBroker.backitup/assets/64688879/55f5fcad-8e02-4dd5-b40f-2e4d3f49dde2)

Bin auch wieder zurück auf die admin v6.17.14

Vielen Dank für deine schnelle Hilfe! 💯

**Comment by simatec** [comment]
Sehr gut ... Mal kurz zur Erklärung... Es lag am Object für die Backup-Quelle... Diese wurde bei dir als string und nicht als Object erkannt, da du nur eine Quelle hast. Das Problem trat bisher nicht auf, da alle meine Testsysteme mehr als eine Backup Quelle haben und dadurch der Wert ein Object und kein string ist. Habe nur einen Check drin, der das prüft...

**Comment by mbhomie007** [comment]
@simatec
Leider doch zu früh gefreut...

![Screenshot_20240612_030715_Chrome.jpg](https://github.com/simatec/ioBroker.backitup/assets/64688879/23c94df9-cefb-42b8-a4a8-55610d12b7a8)

![Screenshot_20240612_031222_Chrome.jpg](https://github.com/simatec/ioBroker.backitup/assets/64688879/30dbbf2c-190f-45f1-8631-ddaf697d28e8)




backitup.0
2024-06-12 03:00:30.978	error	[iobroker/clean] Backup files not deleted from /opt/iobroker/backups because some errors.

backitup.0
2024-06-12 03:00:22.434	error	[iobroker/iobroker] Node.js v18.20.3

backitup.0
2024-06-12 03:00:22.425	error	[iobroker/iobroker] }

backitup.0
2024-06-12 03:00:22.425	error	[iobroker/iobroker] syscall: 'uv_cwd'

backitup.0
2024-06-12 03:00:22.425	error	[iobroker/iobroker] code: 'ENOENT',

backitup.0
2024-06-12 03:00:22.424	error	[iobroker/iobroker] errno: -2,

backitup.0
2024-06-12 03:00:22.424	error	[iobroker/iobroker] at async ModuleLoader.import (node:internal/modules/esm/loader:337:24) {

backitup.0
2024-06-12 03:00:22.423	error	[iobroker/iobroker] at ModuleJob.run (node:internal/modules/esm/module_job:195:25)

backitup.0
2024-06-12 03:00:22.423	error	[iobroker/iobroker] at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:203:29)

backitup.0
2024-06-12 03:00:22.422	error	[iobroker/iobroker] at Module._load (node:internal/modules/cjs/loader:1019:12)

backitup.0
2024-06-12 03:00:22.422	error	[iobroker/iobroker] at Module.load (node:internal/modules/cjs/loader:1203:32)

backitup.0
2024-06-12 03:00:22.421	error	[iobroker/iobroker] at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)

backitup.0
2024-06-12 03:00:22.421	error	[iobroker/iobroker] at Module._compile (node:internal/modules/cjs/loader:1364:14)

backitup.0
2024-06-12 03:00:22.420	error	[iobroker/iobroker] at Object.<anonymous> (/opt/iobroker/node_modules/yargs/build/index.cjs:1:60970)

backitup.0
2024-06-12 03:00:22.420	error	[iobroker/iobroker] at process.cwd (/opt/iobroker/node_modules/graceful-fs/polyfills.js:10:19)

backitup.0
2024-06-12 03:00:22.419	error	[iobroker/iobroker] at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)

backitup.0
2024-06-12 03:00:22.419	error	[iobroker/iobroker] Error: ENOENT: no such file or directory, uv_cwd

backitup.0
2024-06-12 03:00:22.418	error	[iobroker/iobroker] ^

backitup.0
2024-06-12 03:00:22.418	error	[iobroker/iobroker] cachedCwd = rawMethods.cwd();

backitup.0
2024-06-12 03:00:22.407	error	[iobroker/iobroker] node:internal/bootstrap/switches/does_own_process_state:126

**Comment by simatec** [comment]
Das ist leider ein Problem, was seit längerem bekannt ist und ein Thema von nodejs ist. Hier hilft nur ein Neustart des iobrokers bzw. zur Sicherheit des gesamten Systems

**Comment by mbhomie007** [comment]
Okay, danke dir für die Rückmeldung. Mal sehen ob es diese Nacht wieder klappt.

**Comment by mbhomie007** [comment]
Hallo @simatec 
mir ist noch aufgefallen, dass seit dem fix rechts die Dateigröße nicht mehr angezeigt wird.
Bin auf der aktuellen v3.0.5

![image](https://github.com/simatec/ioBroker.backitup/assets/64688879/454fde87-a7e4-423b-97ee-36c669efee21)

**Comment by simatec** [comment]
Ist mit v3.0.5 bereits gefixt

**Comment by mbhomie007** [comment]
Vielen Dank für die Rückmeldung.
Dann müsste es ja morgen wieder zu sehen sein. Ich bin gespannt. Vielen Dank!
