### ISSUE TITLE
V3.0.4 GUI Elemente fehlen

### ISSUE THREAD

**Issue by winnyschuster** [simatec/ioBroker.backitup#1132]
Bei der neuen Version fehlen einige GUI Elemente im Admin (Instanz Settings), z.B. bei iobroker der Starte Jetzt Button. Bei OneDrive fehlen die Elemente zum erlangen des Codes(siehe PIC). Getestet mit Github Version und NPM. Ein Backup vom TAB aus gelingt ohne Probleme nach Onedrive
![backitup](https://github.com/simatec/ioBroker.backitup/assets/7774086/54b450d4-2cfb-458b-a671-2c9590dde80b)

**Comment by simatec** [comment]
Welche Admin Version hast du laufen?
Bitte mal den Cache des Browser leeren

**Comment by winnyschuster** [comment]
Admin=6.14.17, wie beim Test heute Morgen. Es wird folgende Datei nicht gefunden : http://localhost:8081/adapter/backitup/custom/static/js/src_AdapterExist_jsx-src_BackupNow_jsx-src_CheckConfigInvisible_jsx-src_DetectConfig_jsx-src_-1b9e72.374c6e97.chunk.js

Löschen des Cache und Browserwechsel haben nichts gebracht

**Comment by winnyschuster** [comment]
ich habs :-) beim build/PrebuildOnly wird durch die gulpfile.js bestimmt welche Dateien letztendlich im Build Ordner landen. [Mit dieser Zeile](https://github.com/simatec/ioBroker.backitup/blob/de6c0ef95b836a07e1e279d2fedfbdcc0dcc0498/gulpfile.js#L113) werden aber nur die src_Components_xxxxxxx Dateien kopiert, nicht jedoch die src_AdapterExist_xxxxxx Dateien. Ein Einfügen einer neuen Zeile behebt das Problem. Warum das heute morgen anders war kann wohl nur Bluefox beantworten. In der Zeile darüber werden allerdings vendors-src_AdapterExist_xxxxx Dateien kopiert was hier aber nicht greift

**Comment by simatec** [comment]
3.0.4 ist leider beim Build beschädigt wurden... v3.0.5 wird den fehler beheben

**Comment by simatec** [comment]
Fix in v3.0.5

**Comment by winnyschuster** [comment]
Funktioniert!

**Comment by simatec** [comment]
> ich habs :-) beim build/PrebuildOnly wird durch die gulpfile.js bestimmt welche Dateien letztendlich im Build Ordner landen. [Mit dieser Zeile](https://github.com/simatec/ioBroker.backitup/blob/de6c0ef95b836a07e1e279d2fedfbdcc0dcc0498/gulpfile.js#L113) werden aber nur die src_Components_xxxxxxx Dateien kopiert, nicht jedoch die src_AdapterExist_xxxxxx Dateien. Ein Einfügen einer neuen Zeile behebt das Problem. Warum das heute morgen anders war kann wohl nur Bluefox beantworten. In der Zeile darüber werden allerdings vendors-src_AdapterExist_xxxxx Dateien kopiert was hier aber nicht greift
> 
> Im JS-Adapter fehlen da auch immer wieder Dateien, auch durch die gulpfile.js verursacht, deshalb kam ich relativ schnell dahinter

Ja so war es. Ich muss da mal schauen, woran das liegt. Wenn ich ein Build für Github mache, wird die Datei beginnend mit vendors_src_AdapterExit… erzeugt. Mache ich aber ein Build mit dem Release-Script wird die Datei src_AdaperExit… erzeugt. Damit kam Gulp nicht klar. Ich überlege mir da für zukünftige Relases mal was

**Comment by winnyschuster** [comment]
als Workaround evtl: `*src_AdapterExist_*`. Besser wäre es natürlich dem Buildprozess auf die Schliche zu kommen. Ich habe leider keine Erfahrung mit Github, aber Bluefox weiss das vielleicht !??!
