### ISSUE TITLE
Consider better "COMPLETED" message or clear instruction for User to wair for adapter installations etc.

### ISSUE THREAD

**Issue by mcm1957** [simatec/ioBroker.backitup#1133]
**Is your feature request related to a problem? Please describe.**
Users very often restore a backup and try to use the system after backitup reports completion. Butr at this time the iobroker System will be startiung to install adapters which could last ome noticeable time.

**Describe the solution you'd like**
Backitup restore should report completione at the time the complete system is restored (including aapter install and other work required

**Describe alternatives you've considered**
If a real "complete" Message is nopt possible, a cler warning should be outpu to wait for further installation and an information should be added hwo a normal user can check this condition. Maybe some interaction with iobroker-core would be required and should be planned.

**Additional context**
i.e. see https://forum.iobroker.net/topic/71004/file-tab_m-html-not-found/17

**Comment by simatec** [comment]
Once the restore is complete, only the Admin Adapter and Backitup are installed.
The other adapters will follow the restart of the ioBroker.
I will add an information after the restore is completed that all adapters are now reinstalling and that this may take a while until everything is available again.

**Comment by mcm1957** [comment]
Yes I know that the rest of the installation is performed afterwards.
But as I see at forum many users are confused. So if you can improvesomthing without extrem additional work it would be fine I guess.

**Comment by simatec** [comment]
add in v3.0.6
![image](https://github.com/simatec/ioBroker.backitup/assets/39792461/f22a02bb-a9ff-4b45-8bab-1c8d01fa9a79)
