### ISSUE TITLE
History wird nicht gesichert

### ISSUE THREAD

**Issue by accessburn** [simatec/ioBroker.backitup#1135]
Es scheint, laut Protokoll, nach history und vor DB ein Slash zu fehlen. In den Settings ist es jedoch drin.

Folgende Fehlermeldung steht im Protokolle:

`
Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
backitup.0 | 2024-07-17 08:45:23.516 | error | [iobroker/clean] Backup files not deleted from /opt/iobroker/backups because some errors.
backitup.0 | 2024-07-17 08:45:22.581 | error | [iobroker/ftp] File "/opt/iobroker/backups/historyDB_2024_07_17-08_45_20_backupiobroker.tar.gz" not found
backitup.0 | 2024-07-17 08:45:20.737 | error | [iobroker/historyDB] [IGNORED] Backitup cannot found source "undefined" for compress!

`

![image](https://github.com/user-attachments/assets/e805740e-4caf-4dca-a413-7ba377f78994)

**Comment by simatec** [comment]
Bitte überprüfe den Pfad zum History Backup. 
Dieser muss identisch der Konfiguration deines History Adapters sein.

**Comment by accessburn** [comment]
![image](https://github.com/user-attachments/assets/af95a32e-5c69-4943-ae30-e7921a03365b)

Aktuell lautet die schreibweise in der Instanz "history.admin/" ist dass denn schon richtig?
Denn nach dem anpassen und erneuten durchlaufen lautet die Fehlermeldung genau gleich.

**Comment by simatec** [comment]
Zeige doch mal bitte auf der CLI, wo die History Daten liegen. 
Das erste Bild in den Objekten hat nichts mit dem Pfad zu tun.

**Comment by accessburn** [comment]
oh, davon ging ich tatsächlich aus :-o

![image](https://github.com/user-attachments/assets/9793d1ab-8a07-4ceb-b1e8-766f8d5e7d8c)

**Comment by simatec** [comment]
Trage in Backitup und im History Adapter den kompletten Pfad ein

`/opt/iobroker/iobroker-data/history`

**Comment by simatec** [comment]
Und bitte niemals als root auf der CLI arbeiten

**Comment by accessburn** [comment]
> Und bitte niemals als root auf der CLI arbeiten

Standard-Login im Terminal auf dem Synology-Docker

**Comment by accessburn** [comment]
> Trage in Backitup und im History Adapter den kompletten Pfad ein
> 
> `/opt/iobroker/iobroker-data/history`

Dass scheint geholfen zu haben. Keine Fehlermeldung mehr!
