### ISSUE TITLE
Google Drive Anbindung funktioniert nicht

### ISSUE THREAD

**Issue by garfield7791** [simatec/ioBroker.backitup#1137]
Beim Versuch, die App bei Google zu autorisieren, kommt immer folgender Fehler:
Diese App ist blockiert
Diese App hat versucht, auf vertrauliche Daten in Ihrem Google-Konto zuzugreifen. Zum Schutz Ihres Kontos haben wir den Zugriff blockiert.

**Comment by simatec** [comment]
Schaue bitte in deinen Google Einstellungen, ob du die App versehentlich blockiert hast

**Comment by garfield7791** [comment]
Habe nichts blockiert

**Comment by simatec** [comment]
Zeige bitte mal, was dort für Apps eingetragen sind. Backitup ist von Google geprüft und freigegeben wurden.

**Comment by garfield7791** [comment]
Meinst du die Liste der Drittanbieter Apps in den Google Einstellungen? Dort ist Backitup nicht aufgeführt.
Die Fehlermeldung kommt, wenn ich versuche die App zu autorisieren...

**Comment by michije** [comment]
Habe den gleichen Fehler, die App taucht gar nicht erst in der Liste der Drittanbieter Apps auf :/

**Comment by simatec** [comment]
Des Weiteren bitte den Debuglog und alle Systeminformationen inkl. Versionen

**Comment by garfield7791** [comment]
iobroker v6.17.14 (läuft in VM mit Ubuntu Linux 20.04.6 auf Synology)
Backitup v2.11
[iobroker.2024-07-28.log.txt](https://github.com/user-attachments/files/16403100/iobroker.2024-07-28.log.txt)

**Comment by garfield7791** [comment]
![Screenshot 2024-07-28 134452](https://github.com/user-attachments/assets/1b39efab-1eef-47b9-8901-e91327ff1cdb)
![Screenshot 2024-07-28 134503](https://github.com/user-attachments/assets/094bf8d8-8524-462d-b653-6857d2fc3337)
![Screenshot 2024-07-28 134509](https://github.com/user-attachments/assets/d6e28da6-8f99-49ba-93b7-d2bd64c72a01)
![Screenshot 2024-07-28 134513](https://github.com/user-attachments/assets/240eba6a-bf2a-4187-8231-d7aed0b0c72f)

**Comment by garfield7791** [comment]
Sorry mit dem Log hat erst was nicht geklappt. Nochmal hier:
[iobroker.2024-07-28.log.txt](https://github.com/user-attachments/files/16403121/iobroker.2024-07-28.log.txt)

**Comment by simatec** [comment]
Da scheint es bei Google aktuell Probleme zu geben.
Die App ist verifiziert und von Google freigegeben.
Man kann es aber umgehen, in dem man auf "Erweitert" klickt (siehe erstes Bild) 
Dort kann man dann wie im zweiten Bild zu sehen, auf "ioBroker BackItUp öffnen (unsicher)" klicken.

Ich gebe das mal weiter, damit geprüft wird, warum Google diese Meldung ausgibt.

<img width="546" alt="Bildschirmfoto 2024-07-28 um 14 31 30" src="https://github.com/user-attachments/assets/d046dfd6-906c-4ed9-8d14-11153b562341">
<img width="526" alt="Bildschirmfoto 2024-07-28 um 14 31 20" src="https://github.com/user-attachments/assets/7367bbc3-07a2-4726-b8bf-66cd9c261c1e">

**Comment by garfield7791** [comment]
Das klappt bei mir leider nicht, diese Option wird mir nicht angezeigt (Google Chrome).

**Comment by unstressable** [comment]
Wieso wurde das geclosed?
Der Fehler ist doch noch da, oder habt ihr eine Lösung?

**Comment by simatec** [comment]
Hier wurde Nix geschlossen

**Comment by unstressable** [comment]
hab das "closed" hier rechts fehlinterpretiert :(

**Comment by vibraHome** [comment]
Ich hab das gleiche Problem. Bestehende Instanzen sichern immer noch auf Google Drive. Neue Instanzen bringen die oben genannten Fehlermeldungen "Diese App ist blockiert".

**Comment by simatec** [comment]
Wir sind im Austausch mit Google....

**Comment by MisterX7X7X** [comment]
hey and hello, i have also the same problem... thx for your support!!! :)

**Comment by MisterX7X7X** [comment]
hallo gibt es vielleicht zu diesem thema ein update...? danke euch schon mal jetzt. schönes wochenende :)

**Comment by simatec** [comment]
Nach einigen hin und her mit Google sollte nun alles wieder funktionieren.
Bitte testet und gebt kurz euer Feedback hier

**Comment by michije** [comment]
Funktioniert bei mir :)

**Comment by simatec** [comment]
@michije Kommen noch Fehlermeldungen oder Warnungen?

**Comment by ds-1982** [comment]
Bei mir funktioniert es auch wieder, keine Fehler oder Warnungen.

**Comment by vibraHome** [comment]
Funktioniert wieder tadellos. Vielen Dank für die Mühen.

**Comment by simatec** [comment]
Dann ist das Issue damit erledigt...

**Comment by garfield7791** [comment]
Funktioniert aiuch bei mir wieder. Herzlichen Dank für den Fix!
