### ISSUE TITLE
Node 18 no longer supported (due to minimatch used by webdav) ?

### ISSUE THREAD

**Issue by mcm1957** [simatec/ioBroker.backitup#1140]
Backitup (current github revision) requires webdav 5.7.0
webdav requires minimatch 10.0.1 (according to package.lock.json)
minimatch requires node 20 or 22

So - as far as I see - backitup will no longer run at node 18. 

Please verify / investigate. Maybe I'm wrong...

One solution would be to require node 20 (eingines clause). But this would conflict mit ioBroker officially still supporting node 18.

See https://forum.iobroker.net/topic/76190/instanz-backitup-wurde-gestoppt 
In that case backitup 2.x.x was used but failed due to minimatch and node 18.

**Comment by simatec** [comment]
I have reinserted version 5.6.0 and added it as a fixed version.
Furthermore, I asked the developer of Webdav for a downgrade of minimatch, because Node 18 is not End of Life

https://github.com/perry-mitchell/webdav-client/issues/382

**Comment by simatec** [comment]
Fix in v3.0.15

**Comment by mcm1957** [comment]
Thanks for the ultra fast response
