### ISSUE TITLE
CCU3 Backup does not work

### ISSUE THREAD

**Issue by Jennsi** [simatec/ioBroker.backitup#1143]
Hello,

CCU 3 Backup does not work. The backup of the iobroker system, as well as other things such as Javascripts or history data work. Without problems. The messages during the backup attempt are below. Backitup v3.0.16

System:

PlatformBetriebssystem:linux
Architektur:arm64
CPUs:4
Geschwindigkeit:1800 MHz
Modell:Cortex-A72
RAM:7.6 GB
System-Betriebszeit:17 T. 12:08:57
Node.js:v20.16.0
time:1723059291726
timeOffset:-60
NPM:10.8.1
Adapter-Anzahl:626
Datenträgergröße:58.3 GB
Freier Festplattenspeicher:38.3 GB
Aktive Instanzen:16
Pfad:/opt/iobroker/
Betriebszeit:00:01:06
aktiv:true
_nodeCurrent:20.16.0
_nodeNewest:20.16.0
_nodeNewestNext:20.16.0
_npmCurrent:10.8.1
_npmNewest:10.8.1
_npmNewestNext:10.8.1

Messages during the update, with no apparent errors:
````
22:38:59.323
INFO
gui
Backup gestartet ...
22:39:01.888
DEBUG
ccu
CCU-Backup started ...
22:39:01.905
DEBUG
ccu
done
22:39:02.711
DEBUG
ftp
done
22:39:03.424
DEBUG
clean
done
22:39:03.629
DEBUG
historyHTML
new history html values created
22:39:03.652
DEBUG
historyHTML
done
22:39:03.837
DEBUG
historyJSON
new history json values created
22:39:03.854
DEBUG
historyJSON
done
22:39:06.346
DEBUG
notification
Admin notification will be sent
22:39:06.385
DEBUG
notification
done
22:39:06.682
INFO
gui
Das Backup wurde erfolgreich erstellt!
````

**Comment by Jennsi** [comment]
The problem is that no backup file is created. It worked until the end of January this year and then stopped. I also noticed it late.

Here some more Information from the log:

23:19:59.394
INFO
gui
Backup gestartet ...
23:20:01.371
DEBUG
ccu
CCU-Backup started ...
23:20:01.560
DEBUG
ccu
Error: self-signed certificate
23:20:01.605
DEBUG
ccu
done
23:20:02.308
DEBUG
ftp
done
23:20:03.213
DEBUG
clean
done
23:20:03.376
DEBUG
historyHTML
new history html values created
23:20:03.463
DEBUG
historyHTML
done
23:20:03.627
DEBUG
historyJSON
new history json values created
23:20:03.679
DEBUG
historyJSON
done
23:20:06.141
DEBUG
notification
Admin notification will be sent
23:20:06.190
DEBUG
notification
done
23:20:06.441
INFO
gui
Das Backup wurde erfolgreich erstellt!

**Comment by simatec** [comment]
`Error: self-signed certificate `

here is your Problem… 
Do you have https active? Please post your config as json file

**Comment by Jennsi** [comment]
Yes, HTTPS ist active. Now I've turned it into http and it already works. Ist IT Not possible to use HTTPS?Am 09.08.24, 06:30 schrieb simatec ***@***.***>:

  
  Error: self-signed certificate 
  here is your Problem…
    Do you have https active? Please post your config as json file

**Comment by simatec** [comment]
https is possible.... However, if your CCU only has a self-signed certificate (which is the case by default), then you must also configure this in Backitup.

**Comment by Marsen76** [comment]
The same here.
But I can (de)activating http. The checkbox is missing.

Https in ccu is not active.

**Comment by simatec** [comment]
Which checkbox is missing where exactly?

**Comment by simatec** [comment]
Die Konfiguration kann nur gefunden werden, wenn eine Homematic Instanz auf dem Host läuft.
Ansonsten teste bitte die v3.0.19... die kommt gerade ins latest

**Comment by simatec** [comment]
done in v3.0.19

**Comment by Jennsi** [comment]
Hallo! Da es ja offensichtlich auch auf Deutsch geht, mache ich das jetzt auch so. Also bei mir funktioniert es nur, wenn ich in der CCU die Umleitung auf https deaktiviere und den Haken in der Backupanwendung bei https weglasse.

 

Von: simatec ***@***.***> 
Gesendet: Sonntag, 18. August 2024 17:43
An: simatec/ioBroker.backitup ***@***.***>
Cc: Jennsi ***@***.***>; Author ***@***.***>
Betreff: Re: [simatec/ioBroker.backitup] CCU3 Backup does not work (Issue #1143)

 

done in v3.0.19

**Comment by simatec** [comment]
Wenn deine CCU nur selbstsigniertes Zertifikat hat, musst du das für https auch in Backitup konfigurieren und zulassen
