### ISSUE TITLE
ioBroker Multihost - Slave wird nicht gesichert

### ISSUE THREAD

**Issue by Toysman** [simatec/ioBroker.backitup#1144]
**Describe the bug**  
Backitup führt Sicherung laut GUI durch, tatsächlich treten Fehler auf

**To Reproduce**  

**Expected behavior**  
ioBroker als Multihost - auf dem Master Backitup 3.0.16 eine 2.Instanz installiert und als Slave eingerichtet - bei manuellen Backup wird dieses als erfolgreich angezeigt, im Log sind entsprechende Fehler zu erkennen und in der Dropbox (neuer Token wurde in der "Slave" Instanz hinterlegt) werden keine Backups angelegt. 

Auf dem Mastersystem wird hingegen alles einwandfrei ausgeführt.

**Screenshots & Logfiles**  
Screenshots siehe unten

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <6.0.9>
 - Node version: <18.20.4>
 - Operating system: <Ubuntu 22.04 LTS als Container unter Proxmox 8.2.4>

**Additional context**  

![Bildschirmfoto 2024-08-10 um 14 52 40](https://github.com/user-attachments/assets/7f15a51d-3e0c-4011-9d1a-bbfd7efb5ae9)
![Bildschirmfoto 2024-08-12 um 16 16 50](https://github.com/user-attachments/assets/b44c9fcc-4440-4bb8-bc7e-de7036aa9eea)

**Comment by simatec** [comment]
Bitte den vollständigen Debuglog vom Backup hier als Code in Text posten

**Comment by Toysman** [comment]
ich hoffe das ist so richtig :-o

2024-08-12 17:35:03.867 - debug: backitup.1 (1737) Backup has started ...
2024-08-12 17:35:07.330 - debug: backitup.1 (1737) [iobroker/clean] done
2024-08-12 17:35:07.612 - debug: backitup.1 (1737) [iobroker/historyHTML] new history html values created
2024-08-12 17:35:08.108 - debug: backitup.1 (1737) [iobroker/historyHTML] done
2024-08-12 17:35:08.681 - debug: backitup.1 (1737) [iobroker/historyJSON] new history json values created
2024-08-12 17:35:08.682 - debug: backitup.1 (1737) [iobroker/historyJSON] done
2024-08-12 17:35:11.187 - debug: backitup.1 (1737) [iobroker/notification] done
2024-08-12 17:35:11.340 - error: backitup.1 (1737) uncaught exception: Cannot read properties of undefined (reading 'split')
2024-08-12 17:35:11.340 - error: backitup.1 (1737) TypeError: Cannot read properties of undefined (reading 'split')
at createBackupLog (/opt/iobroker/node_modules/iobroker.backitup/lib/execute.js:55:37)
at Immediate.executeScripts (/opt/iobroker/node_modules/iobroker.backitup/lib/execute.js:570:5)
at processImmediate (node:internal/timers:485:21)
2024-08-12 17:35:11.340 - error: backitup.1 (1737) Cannot read properties of undefined (reading 'split')
2024-08-12 17:35:11.391 - info: backitup.1 (1737) cleaned everything up...
2024-08-12 17:35:11.391 - info: backitup.1 (1737) terminating
2024-08-12 17:35:11.391 - debug: backitup.1 (1737) Plugin sentry destroyed
2024-08-12 17:35:11.392 - warn: backitup.1 (1737) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-08-12 17:35:12.237 - error: host.ioBroker_Peckeloh_Slave Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'split')
2024-08-12 17:35:12.237 - error: host.ioBroker_Peckeloh_Slave Caught by controller[0]: at createBackupLog (/opt/iobroker/node_modules/iobroker.backitup/lib/execute.js:55:37)
2024-08-12 17:35:12.237 - error: host.ioBroker_Peckeloh_Slave Caught by controller[0]: at Immediate.executeScripts (/opt/iobroker/node_modules/iobroker.backitup/lib/execute.js:570:5)
2024-08-12 17:35:12.237 - error: host.ioBroker_Peckeloh_Slave Caught by controller[0]: at processImmediate (node:internal/timers:485:21)
2024-08-12 17:35:12.237 - error: host.ioBroker_Peckeloh_Slave instance system.adapter.backitup.1 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-08-12 17:35:12.238 - info: host.ioBroker_Peckeloh_Slave Restart adapter system.adapter.backitup.1 because enabled

**wo finde ich den die Conig als json?**

**Comment by simatec** [comment]
Die kannst du dir in der Config und im Backup Tab runterladen

**Comment by simatec** [comment]
Gibt es auch einen Log vom Master? Die Instanz 1 scheint ja der Slave zu sein

**Comment by simatec** [comment]
Bitte installiere die v3.0.17. Dort ist der Fehler für ein Slave Backup behoben

**Comment by simatec** [comment]
Bitte um ein kurzes Feedback, damit ich das Issue schließen kann

**Comment by Toysman** [comment]
bin beruflich unterwegs, komme erst Freitag zurück.... Rückmeldung erfolgt selbstverständlich

**Comment by Toysman** [comment]
so wieder daheim....

Adapter auf 3.0.17 angeboben... Instanz 1 ist auf 3.0.16 geblieben, Instanz 2 wurde auf 3.0.17 aktualisiert 

Backup auf Instanz 2 (Slave) wird immer noch nicht ausgeführt

backitup.1	2921	2024-08-14 18:13:34.465	debug	[iobroker] exec: done
backitup.1	2921	2024-08-14 18:13:34.314	debug	[iobroker/notification] done
backitup.1	2921	2024-08-14 18:13:31.806	debug	[iobroker/historyJSON] done
backitup.1	2921	2024-08-14 18:13:31.805	debug	[iobroker/historyJSON] new history json values created
backitup.1	2921	2024-08-14 18:13:31.095	debug	[iobroker/historyHTML] done
backitup.1	2921	2024-08-14 18:13:30.311	debug	[iobroker/historyHTML] new history html values created
backitup.1	2921	2024-08-14 18:13:29.959	debug	[iobroker/clean] done
backitup.1	2921	2024-08-14 18:13:29.656	debug	[iobroker/dropbox] done
backitup.1	2921	2024-08-14 18:13:26.494	debug	Backup has started ...
backitup.1	2921	2024-08-14 18:13:20.109	debug	BackItUp has recognized a linux system
backitup.1	2921	2024-08-14 18:13:20.103	info	starting. Version 3.0.17 in /opt/iobroker/node_modules/iobroker.backitup, node: v20.16.0, js-controller: 6.0.9
backitup.1	2921	2024-08-14 18:13:10.965	debug	Plugin sentry Initialize Plugin (enabled=true)
backitup.1	2921	2024-08-14 18:13:09.675	debug	States connected to redis: 192.168.0.99:9000
backitup.1	2921	2024-08-14 18:13:09.358	debug	States create User PubSub Client
backitup.1	2921	2024-08-14 18:13:09.358	debug	States create System PubSub Client
backitup.1	2921	2024-08-14 18:13:09.127	debug	Redis States: Use Redis connection: 192.168.0.99:9000
backitup.1	2921	2024-08-14 18:13:08.983	debug	Objects connected to redis: 192.168.0.99:9001
backitup.1	2921	2024-08-14 18:13:08.899	debug	Objects client initialize lua scripts
backitup.1	2921	2024-08-14 18:13:08.731	debug	Objects create User PubSub Client
backitup.1	2921	2024-08-14 18:13:08.731	debug	Objects create System PubSub Client
backitup.1	2921	2024-08-14 18:13:08.610	debug	Objects client ready ... initialize now
backitup.1	2921	2024-08-14 18:13:08.523	debug	Redis Objects: Use Redis connection: 192.168.0.99:9001
	
[2024_08_14-backitup.1.json](https://github.com/user-attachments/files/16615904/2024_08_14-backitup.1.json)

**Comment by simatec** [comment]
Bitte Master und Slave aktualisieren

**Comment by simatec** [comment]
Des Weiteren benötige ich den Log von Instanz 2

**Comment by Toysman** [comment]
> Bitte Master und Slave aktualisieren

ist erledigt, hatte ich übersehen

**Comment by Toysman** [comment]
> Des Weiteren benötige ich den Log von Instanz 2

[2024_08_14-backitup.1.json](https://github.com/user-attachments/files/16617748/2024_08_14-backitup.1.json)

das Backup wird um's verrecken nicht in der Dropbox gespeichert....

Nur für mein Grundverständnis:
in Instanz 2 hinterlege ich einen eigenständigen Token der Dropbox, richtig?
im Pfad habe ich einen eigenen Unterordner für den Slave angelegt (in der Dropbox entsprechend)
Instanz 1 (Master) wird perfekt (Manuell) ausgeführt, ebenfalls automatisch
Instanz 2 (Slave) in der Backup Historie werden die Backups aufgeführt, jedoch ist das Log leer

<img width="758" alt="Bildschirmfoto 2024-08-14 um 21 11 31" src="https://github.com/user-attachments/assets/05b2fdb6-debf-416a-87bf-da0a44e8bf41">

**Comment by simatec** [comment]
Jede Backup Instanz braucht einen eigenen Token und eine eigene Konfiguration von Dropbox

**Comment by Toysman** [comment]
das sollte dann gegeben sein

**Comment by simatec** [comment]
Bei der Konfiguration der Dropbox musst du als Type Standard auswählen. Bitte lies dir die Doku von Backitup durch. 
 https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch
 
Bisher habe ich auch keine Logs von dir erhalten

**Comment by Toysman** [comment]
> Bei der Konfiguration der Dropbox musst du als Type Standard auswählen. Bitte lies dir die Doku von Backitup durch. https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch
> 
> Bisher habe ich auch keine Logs von dir erhalten

hab jetzt lange mal getestet und diverse Varianten durchgespielt

**Master mit Backitup.0**
Basis ist Ubuntu 22.04 LTS
Node.js: v18.20.4
NPM: 10.7.0

Dropbox Einstellungen --> Standard-Dropbox-API-für-Backitup --> es erscheint ausschließlich eine Seite zum erzeugen eines Tokens --> Dropbox APP Einstellungen sind hier nicht möglich --> den erzeugten Token in Backitup hinterlegt

manuelles Backup gestartet in einen hinterlegten TEST Ordner --> es wird KEIN Backup in der Dropbox angelegt

12:40:43.430 INFO gui Backup gestartet ...
12:40:45.155 DEBUG iobroker host.ioBroker Aplerbeck 10811 states saved
12:40:45.314 DEBUG iobroker host.ioBroker Aplerbeck 13078 objects saved
12:40:46.403 DEBUG iobroker Backup created: /opt/iobroker/backups/iobroker_2024_08_15-12_40_43_Master_backupiobroker.tar.gz
12:40:46.447 DEBUG iobroker This backup can only be restored with js-controller version up from 4.1
12:40:47.434 DEBUG iobroker done
12:40:48.490 DEBUG zigbee found zigbee database: zigbee.0
12:40:48.530 DEBUG zigbee done
12:40:49.265 DEBUG javascripts Created javascript_tmp directory: "/opt/iobroker/backups/tmpScripts"
12:40:49.332 DEBUG javascripts found Script: Homematic_Batteriestatus
12:40:49.442 DEBUG javascripts found Script: Homematic_Erreichbarkeit
_hier habe ich die Liste gekürzt_
12:40:55.784 DEBUG javascripts
Try deleting the Javascript tmp directory: "/opt/iobroker/backups/tmpScripts"
12:40:55.788 DEBUG javascripts Javascript tmp directory "/opt/iobroker/backups/tmpScripts" successfully deleted
12:40:55.826 DEBUG javascripts Backup created: /opt/iobroker/backups/javascripts_2024_08_15-12_40_49_Master_backupiobroker.tar.gz
12:40:55.832 DEBUG javascripts done
12:40:57.403 DEBUG dropbox Dropbox: Copy iobroker_2024_08_15-12_40_43_Master_backupiobroker.tar.gz...
12:40:59.487 DEBUG dropbox Dropbox: Copy zigbee.0_2024_08_15-12_40_48_Master_backupiobroker.tar.gz...
12:41:00.238 DEBUG dropbox Dropbox: Copy javascripts_2024_08_15-12_40_49_Master_backupiobroker.tar.gz...
12:41:01.055 DEBUG dropbox done
12:41:01.379 WARN clean No older backup files are deleted, because this backup was started manually
12:41:01.401 DEBUG clean done
12:41:01.508 DEBUG historyHTML new history html values created
12:41:01.598 DEBUG historyHTML done
12:41:01.749 DEBUG historyJSON new history json values created
12:41:01.798 DEBUG historyJSON done 
12:41:04.259 DEBUG notification done
12:41:04.410 INFO gui Das Backup wurde erfolgreich erstellt!

[2024_08_15-backitup.0.json](https://github.com/user-attachments/files/16624463/2024_08_15-backitup.0.json)

Dropbox Einstellungen --> Benutzerdefinierte App mit langlebigen Token --> es erscheint die Seite zum erzeugen einer APP --> _Schritt 6: Im Tab-Reiter "Settings" die "Access token expiration" auf "No expiration" stellen_  gibt es nicht mehr --> den erzeugten Token in Backitup hinterlegt

manuelles Backup gestartet --> es wird **EIN** Backup in dem APP-Ordner in Dropbox angelegt

[DEBUG] [iobroker] host.ioBroker Aplerbeck 10829 states saved
[DEBUG] [iobroker] host.ioBroker Aplerbeck 13078 objects saved
[DEBUG] [iobroker] Backup created: /opt/iobroker/backups/iobroker_2024_08_15-13_16_33_Master_backupiobroker.tar.gz
[DEBUG] [iobroker] This backup can only be restored with js-controller version up from 4.1
[DEBUG] [iobroker] done
[DEBUG] [zigbee] found zigbee database: zigbee.0
[DEBUG] [zigbee] done
[DEBUG] [javascripts] Created javascript_tmp directory: "/opt/iobroker/backups/tmpScripts"
[DEBUG] [javascripts] found Script: Homematic_Batteriestatus
[DEBUG] [javascripts] found Script: Homematic_Erreichbarkeit
_hier habe ich die Liste gekürzt_
[DEBUG] [javascripts] Try deleting the Javascript tmp directory: "/opt/iobroker/backups/tmpScripts"
[DEBUG] [javascripts] Javascript tmp directory "/opt/iobroker/backups/tmpScripts" successfully deleted
[DEBUG] [javascripts] Backup created: /opt/iobroker/backups/javascripts_2024_08_15-13_16_39_Master_backupiobroker.tar.gz
[DEBUG] [javascripts] done
[DEBUG] [dropbox] Dropbox: Copy iobroker_2024_08_15-13_16_33_Master_backupiobroker.tar.gz...
[DEBUG] [dropbox] Dropbox: Copy zigbee.0_2024_08_15-13_16_38_Master_backupiobroker.tar.gz...
[DEBUG] [dropbox] Dropbox: Copy javascripts_2024_08_15-13_16_39_Master_backupiobroker.tar.gz...
[DEBUG] [dropbox] done
[WARN] [clean] No older backup files are deleted, because this backup was started manually
[DEBUG] [clean] done
[DEBUG] [historyHTML] new history html values created
[DEBUG] [historyHTML] done
[DEBUG] [historyJSON] new history json values created
[DEBUG] [historyJSON] done

[2024_08_15-backitup.0(1).json](https://github.com/user-attachments/files/16624596/2024_08_15-backitup.0.1.json)

Keine der beiden oben getesteten Varianten funktioniert auf dem SLAVE mit Backitup.1 

Aufgefallen ist mir, das auf dem Slave, weil komplett neu aufgesetzt, Node.js und NPM aktueller sind.
Basis ist Bebian 12.2
Node.js: v20.16.0
NPM: 10.8.1

13:29:33.208 INFO gui Backup gestartet ...
13:29:36.896 DEBUG dropbox done
13:29:37.195 DEBUG clean done 
13:29:37.586 DEBUG historyHTML new history html values created
13:29:38.002 DEBUG historyHTML done
13:29:38.647 DEBUG historyJSON new history json values created
13:29:38.674 DEBUG historyJSON done
13:29:41.110 DEBUG notification done
13:29:41.354 INFO gui Das Backup wurde erfolgreich erstellt!

Die im Adapter hinterlegten Protokolle sind allesamt leer...

[2024_08_15-backitup.1.json](https://github.com/user-attachments/files/16624677/2024_08_15-backitup.1.json)

es sieht so aus, als ob kein Backup generiert wird - könnte das mit Node.js in zusammenhang stehen?

**Comment by Toysman** [comment]
so... aus dem Master mit backitup.0 auf Standard-API umgestellt - Sicherung funktioniert

den Slave komplett neu aufgesetzt, neue Backitup Instanz auf den Slave installiert - Standard-API konfiguriert - nix passiert, sprich das LOG ist leer und es wird kein Backup angelegt

**Comment by simatec** [comment]
Wird kein Backup ausgeführt oder wird es in der Dropbox nicht gesichert? Welche Backups hast du auf dem Slave aktiviert?

**Comment by simatec** [comment]
So ich habe mir mal deine Slave Instanz 1 angeschaut. Du hast keine einzige Backup Option aktiv. Da kann auch nix gesichert werden. 

Lies dir bitte die Doku für ein Slave (Multihost) Backup durch…

https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch#multihost-unterst%C3%BCtzung

**Comment by Toysman** [comment]
hmmm.... da war der Fehler vor dem Bildschirm, peinlich für mich... steht da, aber wird nicht wahrgenommen
