### ISSUE TITLE
Backup command is incorrect when token is missing

### ISSUE THREAD

**Issue by klein0r** [simatec/ioBroker.backitup#1146]
**Describe the bug**  

When no token is configured, the backup command is not correct:

https://github.com/simatec/ioBroker.backitup/blob/b8e01a8b7172edab884380d840641f251df7d4ca/lib/scripts/12-influxDB.js#L71-L73

Leads to

```
influx backup --bucket iobroker -t "/opt/iobroker/backups/influxDB_2024_08_14-21_39_40_backupiobroker"
```

In this case the path is used as the token (which is never correct).

```
21:39:40.856 ERRORinfluxDBError: Command failed: influx backup --bucket iobroker -t "/opt/iobroker/backups/influxDB_2024_08_14-21_39_40_backupiobroker"
Error: backup path must be specified as a single positional argument
```

**Expected behavior**  

Option `-t` is not provided:

```
influx backup --bucket iobroker "/opt/iobroker/backups/influxDB_2024_08_14-21_39_40_backupiobroker"
```

**Versions:**  
 - Adapter version: 3.0.18
 - JS-Controller version: 6.0.10
 - Node version: 20.16.0

**Comment by simatec** [comment]
Thank you Matthias for your issue.
I have fixed the bug in v3.0.19.
The token is only required for a remote backup.

Furthermore, I have also adjusted the InfluxDB Config so that the host, port and token are not displayed during a local backup.

**Comment by simatec** [comment]
I just had another look at the documentation of the InfluxDB 2 backup...
Are you sure that your local command works without a token?

As far as I know, the token is also required for a local backup.

**Comment by simatec** [comment]
I have added a validator for the token in the jsonConfig. This ensures that the token is also entered

**Comment by mcm1957** [comment]
> I have added a validator for the token in the jsonConfig. This ensures that the token is also entered

Not 100% ...
I always recommend to validate things at code (i.e. adapter startup) too (!) as the configuration could be changed at object level too and any import / export will not trigger the jsonConfig validator too.

Validation at jsonConfig is ok and require for good user experience, bute validation at code is (in my opinnion) recommended for code stability.

**Comment by simatec** [comment]
It is also integrated in the code

**Comment by simatec** [comment]
done in v3.0.19
