### ISSUE TITLE
InfluxDB Backup not working

### ISSUE THREAD

**Issue by Foradh** [simatec/ioBroker.backitup#1147]
Hi,
I´m facing an issue since the last update to v.3.0.16 that the InfluxDB backup is no longer working due to an authorization issue.
I get the follwing failure message in iobroker.
`[iobroker] Error: Command failed: influx backup --bucket iobroker -t XXXXX "/opt/iobroker/backups/influxDB_2024_08_15-08_23_36_backupiobroker"2024/08/15 08:23:36 INFO: Downloading metadata snapshotError: failed to backup metadata: failed to download metadata snapshot: 401 Unauthorized: read:authorizations is unauthorized`

Of course I have already checked my configuration and except backitup all (Grafana, iobroker InfluxDB adapter) is running well. I use the same API token like in the InfluxDB adapter but I have also created a new all access token in InfluxDB, but always the same issue.

My current setup and verions are:
Raspberry Pi 5
Raspberry OS bookworm up to date
InfluxDB v2.7.9
Backitup v3.0.16
Node.js v20.16.0
JS controller v6.0.9

Could you support me in that case?

Thanks in advance and best regards
Foradh

**Comment by simatec** [comment]
InfluxDB 2.x requires the root token, also known as the operator token.
Only this token is authorised to create a backup.
If you have accidentally deleted it, you can restore it as described in the instructions in the link.
https://github.com/simatec/ioBroker.backitup/wiki/Diverse-Anleitungen-f%C3%BCr-ioBroker.backitup#operator-token-f%C3%BCr-influxdb-2x-wiederherstellen

I also ask you to post your config as json.

You write that it no longer works after the update to v3.0.16. Nothing has changed in the InfluDB backup.

Please post the debug log from the backup and check whether the token displayed in the log matches the one from the configuration.

**Comment by Foradh** [comment]
Hi Simatec,
thanks a lot for your fast reply. After I took the operator token everything went back to normal, strange I was sure that I don´t change anything after updating to v3.0.16.

Best regards
Foradh
