### ISSUE TITLE
i18n inconsistencies

### ISSUE THREAD

**Issue by mcm1957** [simatec/ioBroker.backitup#1148]
backitup has the following i18n files

- admin/src/i18n/\<language\>/translation.json
  Those files are synced with weblate.
  Looks like those files are delived to user too.

- src-admin/src/i18n/\<language\>,json

This looks very inconsistent. Please check which files should be the real source and let me know to adapt weblate eventually.
Please prefer <lang>/translatioon.json format as this is used by most adapters - if possible.

**Comment by simatec** [comment]
The i18n translations are not inconsistent.
The different areas are served here.

1. /src/src/i18n ---> React Tab translation
2. /src-admin/src/i18n ---> Translation of the React components in the config --- synchronized with /admin/custom/i18n after the build. 
3. /admin/i18n/<language> ---> jsonConfig translation

**Comment by mcm1957** [comment]
OK,
Then the changes with react require to add 2 more components to weblate as now 3 source directories exist,
Thanks for clarification.

**Comment by simatec** [comment]
yes...

1. /src/src/i18n/<language>.json
2. /src-admin/src/i18n/<language>.json
3. /admin/i18n/<language>/translations.json
