### ISSUE TITLE
ioBroker.backitup und Linux Manjaro?

### ISSUE THREAD

**Issue by jolichter** [simatec/ioBroker.backitup#1149]
Hallo, ich nutze ioBroker seit etwa einem Jahr auf einem Pi4 mit Linux Manjaro ARM. Weitere Informationen dazu findet ihr hier: [forum.iobroker.net](https://forum.iobroker.net/topic/51315/iobroker-auf-manjaro-und-raspberry-4). Nun habe ich eine Frage zu einem kleinen Problem, das ich beim Installieren oder Aktualisieren des backitup-Adapters erhalte.

Der backitup-Adapter funktioniert und ich kann meine Backups per FTP auf einem NAS erstellen. Beim Installations- oder Update-Vorgang erscheinen jedoch regelmäßig folgende Debian-Warnungen:

```
/bin/sh: Zeile 1: apt: Kommando nicht gefunden.
/bin/sh: Zeile 1: yum: Kommando nicht gefunden.
Cannot detect dpkg: /bin/sh: Zeile 1: dpkg: Kommando nicht gefunden.
host.manjaro-arm Could not install required OS packages: No dpkg detected
```

Mir ist bewusst, dass Debian die bevorzugte und unterstützte Plattform ist, aber vielleicht weiß jemand, welches Paket hier versucht wird zu installieren. So könnte ich es möglicherweise manuell unter Manjaro installieren.

Hat das eventuell auch etwas mit dieser Admin-Meldung zu tun? Die lautet: "Der Adapter kann den genauen Gerätestatus nicht anfordern, der Status wird anhand des zuletzt gesendeten Befehls vermutet."
![Backitup](https://github.com/user-attachments/assets/1696738e-3c2d-4f21-a0cd-a37d4c544611)

Vielen Dank im Voraus für eure Hilfe!

Nachtrag: Im Manjaro Paketbeschreibungstext von `dpkg` wird ausdrücklich davor gewarnt, dieses Tool zur Installation von Debian-Paketen auf einem Arch-basierten System wie Manjaro zu verwenden. Der Hinweis ist eindeutig: `dpkg` ist primär für Benutzer gedacht, die .deb-Pakete erstellen oder modifizieren möchten, nicht für die Installation dieser Pakete auf Arch-Systemen. Die Verwendung von `dpkg` zum Installieren von Debian-Paketen könnte das System ernsthaft beschädigen.

---
Systeminfo
- Admin: 7.0.22
- Backitup: 3.0.19
- js-controller: 6.0.9
- Node.js: 20.11.1
- NPM: 10.4.0
- OS: Manjaro ARM Linux aarch64 (6.6.33-2-MANJARO-RPI4)

**Comment by simatec** [comment]
Zu Manjaro kann ich leider nichts sagen... Eventuell kann dir da @Grothesk242 helfen...

**Comment by jolichter** [comment]
Hallo simatec, danke für deine Rückmeldung!

Ich habe backitup mit aktiviertem Debug-Modus deinstalliert und erneut installiert. Leider erhalte ich weiterhin keine detaillierteren Meldungen, sondern nur diese:

```
2024-08-22 21:38:36.414 - error: host.manjaro-arm iobroker /bin/sh: Zeile 1: apt: Kommando nicht gefunden.
2024-08-22 21:38:36.430 - error: host.manjaro-arm iobroker /bin/sh: Zeile 1: yum: Kommando nicht gefunden.
2024-08-22 21:38:36.433 - info: host.manjaro-arm iobroker No supported packet manager found
2024-08-22 21:38:36.448 - error: host.manjaro-arm iobroker Cannot detect dpkg: /bin/sh: Zeile 1: dpkg: Kommando nicht gefunden.
2024-08-22 21:38:36.452 - error: host.manjaro-arm iobroker host.manjaro-arm Could not install required OS packages: No dpkg detected
```

Wenn ich das richtig verstehe, stammen diese Meldungen von ioBroker selbst, der darauf hinweist, dass ich kein Debian-System verwende.

Dieses Verhalten ist mir bisher nur beim backitup-Adapter aufgefallen. Da die Meldungen keine negativen Auswirkungen haben und lediglich etwas verwirrend sind, werde ich das Issue demnächst schließen.

Ihr macht alle eine großartige Arbeit, und ich denke, ich kann mit diesem Problemchen leben. Da vermutlich kaum jemand sonst Manjaro mit ioBroker verwendet, möchte ich keine unnötigen Ressourcen verschwenden.

Falls doch jemand noch Vorschläge oder Ideen dazu hat, freue ich mich über Hinweise.

**Comment by Grothesk242** [comment]
Das dürfte vom installer kommen. Der hat jedenfalls da Bezüge zu apt und yum drin. Natürlich nicht zu pacman. 
Wir können das aber gerne auch im Forum mal anschauen. Das ist eher kein Backitup-spezifischer 'Bug'.

**Comment by jolichter** [comment]
Ja, gerne! Dann würde ich gerne den bestehenden [Thread](https://forum.iobroker.net/topic/51315/iobroker-auf-manjaro-und-raspberry-4) im Forum dafür nutzen.

**Comment by jolichter** [comment]
Ich möchte mich bei Euch bedanken und das Thema schließen, lasst uns im Forum weitermachen.
