### ISSUE TITLE
MySQL Sektion, Option "Tabellen zeilenweise abrufen" unklar

### ISSUE THREAD

**Issue by Erwin40** [simatec/ioBroker.backitup#1151]
Ich wüsste zu gerne welche mysqldump option dahinter steckt ;-)
Könnte man nicht hier einen Tooltip einbauen?

**Comment by simatec** [comment]
Es handelt sich hierbei um die Option` --quick`

Die Option `--quick` bei `mysqldump` hat den Zweck, den Speicherbedarf zu reduzieren, wenn große Datenbanken gesichert werden. Sie bewirkt, dass die Zeilen der Tabellen direkt aus der Datenbank gelesen und in die Ausgabe geschrieben werden, ohne dass sie vorher im Speicher zwischengespeichert werden.

Funktionsweise:
* Ohne --quick: mysqldump liest die gesamte Tabelle in den Speicher, bevor die Daten in das Dump-File geschrieben werden. Bei sehr großen Tabellen kann dies zu einem hohen Speicherverbrauch führen.
* Mit --quick: mysqldump liest jede Zeile einzeln aus der Tabelle und schreibt sie sofort in das Dump-File. Dadurch wird verhindert, dass der Speicher voll läuft, was insbesondere bei sehr großen Tabellen von Vorteil ist.

Zusammenfassung:
Die Verwendung von --quick ist besonders nützlich, wenn der verfügbare Arbeitsspeicher begrenzt ist oder wenn sehr große Datenbanken gesichert werden, da dadurch der Speicherverbrauch während des Dump-Prozesses minimiert wird.
