### ISSUE TITLE
influxdb und grafana backup

### ISSUE THREAD

**Issue by Jennsi** [simatec/ioBroker.backitup#1152]
Hallo,

ich weiß nicht was ich falsch mache, aber bei der Sicherung der influxdb kommt folgende Fehlermeldung:
````
influxDB: Error: Command failed: influx backup --bucket iobroker2 --host http://192.168.178.75:8086 -t E1nSxF5UDMX89l8_swqhPzbbOX7UeMys58V2dMLPGrq-Qy9UZmY3qGlDeGoAwLatAXRnnZkbJFOc-VMDqr-Wow== "/opt/iobroker/backups/influxDB_2024_08_30-21_08_39_backupiobroker"
2024/08/30 21:08:39 INFO: Downloading metadata snapshot
Error: failed to backup metadata: failed to download metadata snapshot: 401 Unauthorized: read:authorizations is unauthorized
````
Ich habe schon mehrfach den API Token neu generiert und alle anderen Eingaben kontrolliert. Der Token hat Adminrechte.

Danke.

**Comment by Jennsi** [comment]
Ich habe nochmal alles neu installiert. Mittlerweile laufen alle Backups. Auch von Grafana. Siehe hierzu das logging. Hier ist zu entnehmen, dass offensichtlich die Rechte zum lesen nicht vorliegen. Die Verbindung zu Grafana und zum iobroker laufen alle ohne Probleme....

21:10:37.348
INFO
gui
Backup gestartet ...
21:10:41.515
DEBUG
iobroker
host.iobroker2 5188 states saved
21:10:44.399
DEBUG
iobroker
host.iobroker2 5990 objects saved
21:10:48.596
DEBUG
iobroker
Backup created: /opt/iobroker/backups/iobroker_2024_09_01-20_10_36_backupiobroker.tar.gz
21:10:48.613
DEBUG
iobroker
This backup can only be restored with js-controller version up from 4.1
21:10:49.622
DEBUG
iobroker
done
21:10:49.825
DEBUG
influxDB
InfluxDB-Backup started ...
21:10:49.835
DEBUG
influxDB
InfluxDB Backup tmp directory created
[DEBUG] [influxDB] -
21:10:49.889
ERROR
influxDB
Error: Command failed: influx backup --bucket iobroker2 -t 42WvlZbQreHU11-m2Ce7Y4-wfeRuuWnxyXXiEyBFchjmZctxHneCYVW1f0B1GaSts97FJvq5x5Kz08Gw4LOTyw== "/opt/iobroker/backups/influxDB_2024_09_01-20_10_48_backupiobroker"
2024/09/01 20:10:49 INFO: Downloading metadata snapshot
Error: failed to backup metadata: failed to download metadata snapshot: 401 Unauthorized: read:authorizations is unauthorized
21:10:49.897
DEBUG
influxDB
done
21:10:51.155
DEBUG
grafana
Start Grafana Backup ...
21:10:51.162
DEBUG
grafana
Created dashboards_manually_restore directory
21:10:51.167
DEBUG
grafana
Created datasource directory
21:10:51.170
DEBUG
grafana
Grafana is available ... Status: 200
21:10:51.545
DEBUG
grafana
found Dashboard: dashboard-one
21:10:51.600
DEBUG
grafana
start Grafana backup compress ...
21:10:56.688
DEBUG
grafana
Backup created: /opt/iobroker/backups/grafana_2024_09_01-20_10_50_backupiobroker.tar.gz
21:10:56.695
DEBUG
grafana
Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
21:10:56.738
DEBUG
grafana
Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
21:10:56.746
DEBUG
grafana
done
21:10:57.198
DEBUG
javascripts
Created javascript_tmp directory: "/opt/iobroker/backups/tmpScripts"
21:10:57.230
DEBUG
javascripts
found Script: Steuerung_Badlüftung
21:10:57.377
DEBUG
javascripts
found Script: Durchnitt_PV_berechnen
21:10:57.608
DEBUG
javascripts
found Script: Durchschnitt_Bezug_berechnen
21:10:57.676
DEBUG
javascripts
found Script: Steuerung_Heizstab_Akku
21:10:57.834
DEBUG
javascripts
found Script: Steuerung_Heizstab_Bezug
21:10:57.979
DEBUG
javascripts
found Script: Steuerung_Kellerentfeuchtung
21:10:58.146
DEBUG
javascripts
Try deleting the Javascript tmp directory: "/opt/iobroker/backups/tmpScripts"
21:10:58.153
DEBUG
javascripts
Javascript tmp directory "/opt/iobroker/backups/tmpScripts" successfully deleted
21:10:58.186
DEBUG
javascripts
Backup created: /opt/iobroker/backups/javascripts_2024_09_01-20_10_56_backupiobroker.tar.gz
21:10:58.195
DEBUG
javascripts
done
21:10:58.836
DEBUG
ftp
FTP connected.
21:10:58.843
DEBUG
ftp
Send iobroker_2024_09_01-20_10_36_backupiobroker.tar.gz
21:10:58.983
ERROR
ftp
File "/opt/iobroker/backups/influxDB_2024_09_01-20_10_48_backupiobroker.tar.gz" not found
21:10:59.006
DEBUG
ftp
Send grafana_2024_09_01-20_10_50_backupiobroker.tar.gz
21:10:59.043
DEBUG
ftp
Send javascripts_2024_09_01-20_10_56_backupiobroker.tar.gz
21:10:59.077
DEBUG
ftp
done
21:10:59.983
DEBUG
clean
done
21:11:00.182
DEBUG
historyHTML
new history html values created
21:11:00.190
DEBUG
historyHTML
done
21:11:00.376
DEBUG
historyJSON
done
21:11:02.844
DEBUG
notification
Admin notification will be sent
21:11:02.896
DEBUG
notification
done
21:11:03.034
INFO
gui
Das Backup wurde erfolgreich erstellt!

**Comment by Jennsi** [comment]
Keine Lösung?

**Comment by Jennsi** [comment]
Vielen Dank. Scheint jetzt zu laufen. Bin halt kein Programmierer.

**Comment by simatec** [comment]
Alles gut… dafür gibt es die Doku
