### ISSUE TITLE
Energiefluss-erweitert als Sicherung mit aufnehmen

### ISSUE THREAD

**Issue by SKB-CGN** [simatec/ioBroker.backitup#1156]
Hi,
wäre es dir möglich, die Daten des 'Energiefluss-erweitert'-Adapter in die Sicherungsoptionen mit aufzunehmen?

Die Dateien liegen als Platintext im JSON-Format vor.

Welche Infos benötigst du noch?

Danke im Voraus!

**Comment by simatec** [comment]
Wo werden die Daten gespeichert?

**Comment by SKB-CGN** [comment]
Die Daten liegen in
```/opt/iobroker/iobroker-data/energiefluss-e
rweitert.<InstanceNo>```

und beinhalten 2 Ordner ```backup``` und ```userFiles```.

```backup``` enthält die Textdateien mit den Daten im JSON-Format und ```userFiles``` Bilder, die der Benutzer hochgeladen hat.

**Comment by simatec** [comment]
Die Daten werden doch aber im iobroker Backup gesichert. Also sollten sie bei dem Speichpfad

**Comment by SKB-CGN** [comment]
Sollten sie - denke ich.

Wieso gibt es denn eine eigene Option für Jarvis in dem Falle? Die Daten liegen ja auch nur eine Ebene höher?

Daher kam mein Gedanke dazu.

**Comment by simatec** [comment]
In Jarvis wird noch einiges mehr gesichert. Ich weiß, dass viele den Wunsch haben, am liebsten einzelne Backups für alle möglichen Adapter und Settings zu bekommen. Wir haben uns aber irgendwann mal darauf geeinigt, dass alles dass, was im iobroker Backup enthalten ist, nicht extra gesichert wird. 

Ich schaue mir die Tage deinen Adapter mal genauer an und werde das Thema auch im Entwickler Meeting mal ansprechen

**Comment by SKB-CGN** [comment]
Ich kann da durchaus beide Seiten verstehen.

Da ich in letzter Zeit allerdings auch häufiger mal gelesen hatte, das den Leuten irgendwie das Backup vom Energiefluss fehlt (was ich irgendwie nicht nachvollziehen kann) dachte ich, ich frage bei Dir einmal nach, damit wir dies besprechen können 😉

Melde Dich gerne diesbezüglich zurück!

**Comment by SKB-CGN** [comment]
Hi,
hattest Du schon Gelegenheit, einmal zu schauen?

**Comment by simatec** [comment]
Welche Daten des Adapters liegen wo und was ist davon nicht im iobroker Backup?

**Comment by SKB-CGN** [comment]
Die Daten des Adapters liegen hier:

https://github.com/simatec/ioBroker.backitup/issues/1156#issuecomment-2336606847

**Comment by simatec** [comment]
Und diese Daten sind nicht im iobroker Backup?

**Comment by SKB-CGN** [comment]
Doch, natürlich!

Ich denke, die User kommen da etwas durcheinander, weil's nicht getrennt gelistet ist.

**Comment by simatec** [comment]
Da die Daten bereits im ioBroker Backup vollumfänglich vorhanden sind, ist keine weitere Implementierung geplant
