### ISSUE TITLE
Gotifiy

### ISSUE THREAD

**Issue by Mephisto090** [simatec/ioBroker.backitup#1157]
Hallo,

nach dem speichern wird die gotify Instanz immer gelöscht (Siehe Bild)

Ich habe 2 Instanzen gotify.0 und gotify.1

![image](https://github.com/user-attachments/assets/e6dd841e-7e02-4304-8918-3b03237b2037)

**Comment by Mephisto090** [comment]
Es wird auch keine Benachrichtigung versendet

**Comment by simatec** [comment]
Welche Version ist installiert?

**Comment by Mephisto090** [comment]
![image](https://github.com/user-attachments/assets/3458169d-ddfe-46a0-bb8d-03fd98209dee)

**Comment by simatec** [comment]
Bitte installiere die aktuelle Beta. Da ist der Fehler bereits behoben. Kommt sicher die Tage ins Stable

**Comment by Mephisto090** [comment]
funktioniert. Danke :(
