### ISSUE TITLE
Google Drive: backitup legt existierendes Verzeichnis neu an

### ISSUE THREAD

**Issue by Horgul123** [simatec/ioBroker.backitup#1165]
Mir ist zufällig aufgefallen, dass in Google Drive keine Backups waren.

Ich habe deswegen den Pfad in backitup noch einmal neu eingegeben, um sicher zu sein:
/Backup/Iobroker
In Google Drive unter "Ablage" gibt es den Ordner "Backup" und darunter "Iobroker" bereits, habe ich durch "umbenennen" in Drive nocheinmal kontrolliert um wegen Groß-/Kleinschreibung usw. sicher zu sein.
Dennoch wird ein neuer Ordner inkl. Unterordner angelegt.
Einmal der "richtige" Ordner (ist leer), einmal der von Backitup angelegte mit den Backups.

![Screenshot 2024-10-09 072830](https://github.com/user-attachments/assets/1b2ce513-35fa-4161-a32b-350ad20d056f)
![Screenshot 2024-10-09 072853](https://github.com/user-attachments/assets/7538cbc2-e899-4463-9420-37a1b6ec1bf8)

Ich weiß nicht, seit wann das Problem besteht, da wie gesagt keine Backups vorhanden waren, es aber auch keine Fehlermeldung gab, dass die Backups nicht hochgeladen werden konnten.
Ich sichere die parallel lokal auf einem NAS via FTP, da sind die Backups vorhanden.

**Versions:**  
 - Adapter version: 3.0.25
 - JS-Controller version: 7.0.0
 - Node version: v20.18.0
 - Operating system: Debian

**Comment by simatec** [comment]
Bitte autorisiere die Google Drive App erneut. Bei Google gab es ein paar Änderungen

**Comment by Horgul123** [comment]
@simatec Ändert nix.....

**Comment by simatec** [comment]
Lege mal einen Pfad an, der noch nicht existiert... Denke da hat Google ein problem mit.
Lege am besten in Backitup den Pfad fest und erstelle keine Ordner in Google. 

Hier ein Beispielpfad: `/Backups/ioBroker`

**Comment by Horgul123** [comment]
@simatec Das geht. Ist aber irgendwie doof, da ich einen Ordner "Backups" habe, wo ich in verschiedenen Unterordnern dann die verschiedenen Backups drin habe...

Schade, dass das hier mit dem Pfad irgendwie nicht geht,

**Comment by Horgul123** [comment]
Wäre ne Option. Weißt Du, wie das dann für andere Apps aussieht, die da Sachen in bestehende Ordner speichern? In die bestehenden Ordner können sie es aktuell.

**Comment by simatec** [comment]
Google prüft jede APP und jede App hat andere Rechte. Von daher kann man das nicht pauschal sagen.
Die Backitup App hat die Rechte, eigene Dateien und Ordner zu erstellen, ändern und zu löschen. Nicht aber darf die Backitup App auf andere Dateien in deinem Account zugreifen.

**Comment by simatec** [comment]
Issue ist meiner Meinung nach erledigt und wird geschlossen...
