### ISSUE TITLE
Backup is not closing FTP Connection

### ISSUE THREAD

**Issue by jack-blackson** [simatec/ioBroker.backitup#1166]
**Describe the bug**  
When I check my Synology NAS, I can see that there are lots of open connections from the FTP Backup coming from ioBroker. I checked the debug log, but there everything looks good. Is there any kind of setting I can set?

**To Reproduce**  
1. Start Backup  manually
2. Backup stopps successfully, backup is available on NAS
3. Connection stays open

**Versions:**  
 - Adapter version: 3.0.22
 - JS-Controller version: 6.0.11
 - Node version: 18.17.1
 - Operating system: linux

**Comment by jack-blackson** [comment]
Hello!

Sure, here are the requested files.

[backitup.0.json](https://github.com/user-attachments/files/17332218/backitup.0.json)

``
19:53:29.504INFOguiBackup gestartet ...
[DEBUG] [iobroker] start with {"type":"creator","workDir":"/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js","time":"02:00","cronjob":"00 48 02 */1 * *","ownCron":false,"debugging":true,"slaveBackup":"Single","everyXDays":"1","deleteBackupAfter":0,"ftp":{"enabled":true,"type":"storage","host":"192.168.1.104","debugging":true,"deleteOldBackup":false,"ftpDeleteAfter":10,"advancedDelete":false,"ownDir":true,"bkpType":"Minimal","dir":"/ioBroker/Backup/Standard","dirMinimal":"/ioBroker/Backup/Standard","user":"ioBroker","pass":"****","port":"65034","secure":false,"signedCertificates":true,"ignoreErrors":false},"ignoreErrors":false,"dir":"/opt/iobroker","historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"allTelegramUsers","onlyError":true,"telegramWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"email.0","NoticeType":"longEmailNotice","emailReceiver":"alexander.kolb@outlook.at","emailSender":"kolbalexander@msn.com","onlyError":true,"emailWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"","NoticeType":"longWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"gotify":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"gotify.0","NoticeType":"longGotifyNotice","onlyError":false,"gotifyWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"signal":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"signal-cmb.0","NoticeType":"longSignalNotice","onlyError":true,"signalWaiting":10000,"hostName":"","ignoreErrors":false,"systemLang":"de"},"matrix":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"matrix-org.0","NoticeType":"longMatrixNotice","onlyError":false,"matrixWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"discord":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"discord.0","NoticeType":"longWhatsappNotice","target":"","onlyError":false,"discordWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"notification":{"type":"message","ignoreErrors":false,"bashDir":"/opt/iobroker/iobroker-data/backitup","entriesNumber":"25","systemLang":"de"},"backupDir":"/opt/iobroker/backups","timestamp":1728582809726}
19:53:36.127DEBUGiobrokerhost.raspberrypi 11232 states saved
19:53:41.751DEBUGiobrokerhost.raspberrypi 10807 objects saved
19:54:00.576DEBUGiobrokerBackup created: /opt/iobroker/backups/iobroker_2024_10_10-19_53_29_backupiobroker.tar.gz
19:54:00.584DEBUGiobrokerThis backup can only be restored with js-controller version up from 4.1
19:54:01.689DEBUGiobrokerdone
[DEBUG] [ftp] start with {"type":"storage","host":"192.168.1.104","debugging":true,"deleteOldBackup":false,"ftpDeleteAfter":10,"advancedDelete":false,"ownDir":true,"bkpType":"Minimal","dir":"/ioBroker/Backup/Standard","dirMinimal":"/ioBroker/Backup/Standard","user":"ioBroker","pass":"****","port":"65034","secure":false,"signedCertificates":true,"ignoreErrors":false,"deleteBackupAfter":0}
19:54:04.270DEBUGftpFTP connected.
19:54:04.312DEBUGftpSend iobroker_2024_10_10-19_53_29_backupiobroker.tar.gz
19:54:05.383DEBUGftpdone
19:54:06.314WARNcleanNo older backup files are deleted, because this backup was started manually
19:54:06.340DEBUGcleandone
19:54:06.457DEBUGhistoryHTMLnew history html values created
19:54:06.555DEBUGhistoryHTMLdone
[DEBUG] [historyHTML] start with {"type":"creator","workDir":"/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js","time":"02:00","cronjob":"00 48 02 */1 * *","ownCron":false,"debugging":true,"slaveBackup":"Single","everyXDays":"1","deleteBackupAfter":0,"ftp":{"enabled":true,"type":"storage","host":"192.168.1.104","debugging":true,"deleteOldBackup":false,"ftpDeleteAfter":10,"advancedDelete":false,"ownDir":true,"bkpType":"Minimal","dir":"/ioBroker/Backup/Standard","dirMinimal":"/ioBroker/Backup/Standard","user":"ioBroker","pass":"****","port":"65034","secure":false,"signedCertificates":true,"ignoreErrors":false},"ignoreErrors":false,"dir":"/opt/iobroker","historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de","time":"10. Oktober 2024 um 19:54 Uhr"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"allTelegramUsers","onlyError":true,"telegramWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"email.0","NoticeType":"longEmailNotice","emailReceiver":"alexander.kolb@outlook.at","emailSender":"kolbalexander@msn.com","onlyError":true,"emailWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"","NoticeType":"longWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"gotify":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"gotify.0","NoticeType":"longGotifyNotice","onlyError":false,"gotifyWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"signal":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"signal-cmb.0","NoticeType":"longSignalNotice","onlyError":true,"signalWaiting":10000,"hostName":"","ignoreErrors":false,"systemLang":"de"},"matrix":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"matrix-org.0","NoticeType":"longMatrixNotice","onlyError":false,"matrixWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"discord":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"discord.0","NoticeType":"longWhatsappNotice","target":"","onlyError":false,"discordWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"notification":{"type":"message","ignoreErrors":false,"bashDir":"/opt/iobroker/iobroker-data/backitup","entriesNumber":"25","systemLang":"de"},"backupDir":"/opt/iobroker/backups","timestamp":1728582809726,"influxDBEvents":[],"mySqlEvents":[],"pgSqlEvents":[]}
19:54:06.723DEBUGhistoryJSONnew history json values created
19:54:06.765DEBUGhistoryJSONdone
[DEBUG] [historyJSON] start with {"type":"creator","workDir":"/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js","time":"02:00","cronjob":"00 48 02 */1 * *","ownCron":false,"debugging":true,"slaveBackup":"Single","everyXDays":"1","deleteBackupAfter":0,"ftp":{"enabled":true,"type":"storage","host":"192.168.1.104","debugging":true,"deleteOldBackup":false,"ftpDeleteAfter":10,"advancedDelete":false,"ownDir":true,"bkpType":"Minimal","dir":"/ioBroker/Backup/Standard","dirMinimal":"/ioBroker/Backup/Standard","user":"ioBroker","pass":"****","port":"65034","secure":false,"signedCertificates":true,"ignoreErrors":false},"ignoreErrors":false,"dir":"/opt/iobroker","historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de","time":"10. Oktober 2024 um 19:54 Uhr"},"telegram":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"allTelegramUsers","onlyError":true,"telegramWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"email.0","NoticeType":"longEmailNotice","emailReceiver":"alexander.kolb@outlook.at","emailSender":"kolbalexander@msn.com","onlyError":true,"emailWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"","NoticeType":"longWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"gotify":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"gotify.0","NoticeType":"longGotifyNotice","onlyError":false,"gotifyWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"signal":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"signal-cmb.0","NoticeType":"longSignalNotice","onlyError":true,"signalWaiting":10000,"hostName":"","ignoreErrors":false,"systemLang":"de"},"matrix":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"matrix-org.0","NoticeType":"longMatrixNotice","onlyError":false,"matrixWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"discord":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"discord.0","NoticeType":"longWhatsappNotice","target":"","onlyError":false,"discordWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"notification":{"type":"message","ignoreErrors":false,"bashDir":"/opt/iobroker/iobroker-data/backitup","entriesNumber":"25","systemLang":"de"},"backupDir":"/opt/iobroker/backups","timestamp":1728582809726,"influxDBEvents":[],"mySqlEvents":[],"pgSqlEvents":[]}
19:54:07.221DEBUGemail[iobroker] used E-Mail-Instance: email.0
19:54:07.226DEBUGemaildone
[DEBUG] [email] start with {"type":"creator","workDir":"/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js","time":"02:00","cronjob":"00 48 02 */1 * *","ownCron":false,"debugging":true,"slaveBackup":"Single","everyXDays":"1","deleteBackupAfter":0,"ftp":{"enabled":true,"type":"storage","host":"192.168.1.104","debugging":true,"deleteOldBackup":false,"ftpDeleteAfter":10,"advancedDelete":false,"ownDir":true,"bkpType":"Minimal","dir":"/ioBroker/Backup/Standard","dirMinimal":"/ioBroker/Backup/Standard","user":"ioBroker","pass":"****","port":"65034","secure":false,"signedCertificates":true,"ignoreErrors":false},"ignoreErrors":false,"dir":"/opt/iobroker","historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"allTelegramUsers","onlyError":true,"telegramWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"email.0","NoticeType":"longEmailNotice","emailReceiver":"alexander.kolb@outlook.at","emailSender":"kolbalexander@msn.com","onlyError":true,"emailWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de","time":"10. Oktober 2024 um 19:54 Uhr"},"pushover":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"","NoticeType":"longWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"gotify":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"gotify.0","NoticeType":"longGotifyNotice","onlyError":false,"gotifyWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"signal":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"signal-cmb.0","NoticeType":"longSignalNotice","onlyError":true,"signalWaiting":10000,"hostName":"","ignoreErrors":false,"systemLang":"de"},"matrix":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"matrix-org.0","NoticeType":"longMatrixNotice","onlyError":false,"matrixWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"discord":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"discord.0","NoticeType":"longWhatsappNotice","target":"","onlyError":false,"discordWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"notification":{"type":"message","ignoreErrors":false,"bashDir":"/opt/iobroker/iobroker-data/backitup","entriesNumber":"25","systemLang":"de"},"backupDir":"/opt/iobroker/backups","timestamp":1728582809726,"influxDBEvents":[],"mySqlEvents":[],"pgSqlEvents":[]}
[DEBUG] [notification] start with {"type":"creator","workDir":"/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js","time":"02:00","cronjob":"00 48 02 */1 * *","ownCron":false,"debugging":true,"slaveBackup":"Single","everyXDays":"1","deleteBackupAfter":0,"ftp":{"enabled":true,"type":"storage","host":"192.168.1.104","debugging":true,"deleteOldBackup":false,"ftpDeleteAfter":10,"advancedDelete":false,"ownDir":true,"bkpType":"Minimal","dir":"/ioBroker/Backup/Standard","dirMinimal":"/ioBroker/Backup/Standard","user":"ioBroker","pass":"****","port":"65034","secure":false,"signedCertificates":true,"ignoreErrors":false},"ignoreErrors":false,"dir":"/opt/iobroker","historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"allTelegramUsers","onlyError":true,"telegramWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"email.0","NoticeType":"longEmailNotice","emailReceiver":"alexander.kolb@outlook.at","emailSender":"kolbalexander@msn.com","onlyError":true,"emailWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"","NoticeType":"longWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"gotify":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"gotify.0","NoticeType":"longGotifyNotice","onlyError":false,"gotifyWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"signal":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"signal-cmb.0","NoticeType":"longSignalNotice","onlyError":true,"signalWaiting":10000,"hostName":"","ignoreErrors":false,"systemLang":"de"},"matrix":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"matrix-org.0","NoticeType":"longMatrixNotice","onlyError":false,"matrixWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"discord":{"enabled":true,"notificationsType":"E-Mail","type":"message","instance":"discord.0","NoticeType":"longWhatsappNotice","target":"","onlyError":false,"discordWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"notification":{"type":"message","ignoreErrors":false,"bashDir":"/opt/iobroker/iobroker-data/backitup","entriesNumber":"25","systemLang":"de","time":"10. Oktober 2024 um 19:54 Uhr"},"backupDir":"/opt/iobroker/backups","timestamp":1728582809726,"influxDBEvents":[],"mySqlEvents":[],"pgSqlEvents":[]}
19:54:09.245DEBUGnotificationdone
19:54:09.405INFOguiDas Backup wurde erfolgreich erstellt!
``

**Comment by jack-blackson** [comment]
`

backitup.0 | 2024-10-10 19:58:48.183 | debug | [iobroker] exec: done
-- | -- | -- | --
backitup.0 | 2024-10-10 19:58:48.027 | debug | [iobroker/notification] done
backitup.0 | 2024-10-10 19:58:45.955 | debug | [iobroker/email] done
backitup.0 | 2024-10-10 19:58:45.954 | debug | [iobroker/email] [iobroker] used E-Mail-Instance: email.0
backitup.0 | 2024-10-10 19:58:45.494 | debug | [iobroker/historyJSON] done
backitup.0 | 2024-10-10 19:58:45.492 | debug | [iobroker/historyJSON] new history json values created
backitup.0 | 2024-10-10 19:58:45.324 | debug | [iobroker/historyHTML] done
backitup.0 | 2024-10-10 19:58:45.226 | debug | [iobroker/historyHTML] new history html values created
backitup.0 | 2024-10-10 19:58:45.065 | debug | [iobroker/clean] done
backitup.0 | 2024-10-10 19:58:45.064 | warn | [iobroker/clean] No older backup files are deleted, because this backup was started manually
backitup.0 | 2024-10-10 19:58:44.155 | debug | [iobroker/ftp] done
backitup.0 | 2024-10-10 19:58:42.707 | debug | [iobroker/ftp] Send iobroker_2024_10_10-19_58_08_backupiobroker.tar.gz
backitup.0 | 2024-10-10 19:58:42.704 | debug | [iobroker/ftp] FTP connected.
backitup.0 | 2024-10-10 19:58:40.088 | debug | [iobroker/iobroker] done
backitup.0 | 2024-10-10 19:58:39.043 | debug | [iobroker/iobroker] This backup can only be restored with js-controller version up from 4.1
backitup.0 | 2024-10-10 19:58:39.040 | debug | [iobroker/iobroker] Backup created: /opt/iobroker/backups/iobroker_2024_10_10-19_58_08_backupiobroker.tar.gz
backitup.0 | 2024-10-10 19:58:18.990 | debug | [iobroker/iobroker] host.raspberrypi 10807 objects saved
backitup.0 | 2024-10-10 19:58:15.623 | debug | [iobroker/iobroker] host.raspberrypi 11240 states saved
backitup.0 | 2024-10-10 19:58:08.053 | debug | Backup has started ...



`

**Comment by simatec** [comment]
Fix in next Release
