### ISSUE TITLE
Backitup macht kein Backup mehr

### ISSUE THREAD

**Issue by Bersserker-s** [simatec/ioBroker.backitup#1169]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by simatec** [comment]
Was soll man mit so einem Issue anfangen? 🧐

**Comment by Bersserker-s** [comment]
Ich weiß nicht wie ich das beschreiben soll es sichert halt nichts mehr es will beginnen und dann wird es nie fertig Mit freundlichen Grüßen MarcelHerbort Am 13.10.2024 um 10:21 schrieb simatec ***@***.***>:﻿
Was soll man mit so einem Issue anfangen? 🧐

**Comment by simatec** [comment]
Poste bitte den Debuglog vom Backupprozess und deine Config von Backitup

**Comment by simatec** [comment]
Reminder...

**Comment by Bersserker-s** [comment]
![IMG_0457](https://github.com/user-attachments/assets/7bd1c02f-c5f6-46d7-9b27-64b0d1d5cbc3)

**Comment by simatec** [comment]
Was willst du mir mit dem Screenshot sagen? Ich kann mit solchen Infos nix anfangen.
Bitte liefere mir einen vernünftigen Debuglog, deine Config als JSON File und die vollständige Ausgabe von `iob diag`

Sollte ich wieder bloß einen unkommentierten Screenshot bekommen, werde ich das Issue schließen

**Comment by Bersserker-s** [comment]
Davon hab ich keinen Plan ich hab das alles einfach nach Anleitung zusammengestellt und bin froh das es läuft…Ich habe ein raspi 4 und alles läuft im Beta betrieb mehr kann ich leider nicht bieten Mit freundlichen Grüßen MarcelHerbort Am 17.10.2024 um 08:52 schrieb simatec ***@***.***>:﻿
Was willst du mir mit dem Screenshot sagen? Ich kann mit solchen Infos nix anfangen.
Bitte liefere mir einen vernünftigen Debuglog, deine Config als JSON File und die vollständige Ausgabe von iob diag
Sollte ich wieder bloß einen unkommentierten Screenshot bekommen, werde ich das Issue schließen

**Comment by simatec** [comment]
Da ist ja schon der erste große Fehler. Du schreibst selber, dass du keinen Plan hast, bist aber als beta Tester unterwegs.
Warum machst du sowas? Gerade für Anfänger ist die Stable Repo exorbitant wichtig.

Welche Version von Backitup ist installiert? Aktuell ist Beta v3.0.26. Ist die bei dir installiert?

Gehe auf die Konsole und führe den Befehl `iob diag` aus, damit ich sehen kann, was auf deinem System läuft.

**Comment by simatec** [comment]
Da keine Informationen geliefert werden, ist das Issue geschlossen.
