### ISSUE TITLE
3.0.28 - Backup page is empty 

### ISSUE THREAD

**Issue by Grothesk242** [simatec/ioBroker.backitup#1186]
**Describe the bug**  
3.0.28 - Backup page is empty 
When seleting the Backitup-Page from the side menu, the frame is black. 
Regression - 3.0.27 is working as expected.

**To Reproduce**  
Install 3.0.28, try to open Backitup from the side menu. 

**Versions:**  
 - Adapter version: 3.0.28
 - JS-Controller version: 7.0.3
 - Node version: 20.18.1
 - Operating system: RaspberryOS 12 'Bookworm'

**Additional context**  
No messages in the log file.

**Comment by Grothesk242** [comment]
Browser Konsole tells me:
```
GET
http://chet:8081/adapter/backitup/static/css/main.bd1167d4.css
[HTTP/1.1 404 Not Found 14ms]
Laden fehlgeschlagen für das <script> mit der Quelle "http://chet:8081/adapter/backitup/static/js/main.4c8661db.js".
```

**Comment by simatec** [comment]
Which admin version is installed?

**Comment by Grothesk242** [comment]
admin 7.4.2

**Comment by Grothesk242** [comment]
Works again with: 
```
iobroker.backitup@3.0.29 (git+ssh://git@github.com/simatec/ioBroker.backitup.git#74aebcde3b4f1ef9f92e5fa6d3c1e5993b20b0f2)
```
