### ISSUE TITLE
iobroker backup is 0 byte // tar.create is not a function

### ISSUE THREAD

**Issue by linos22** [simatec/ioBroker.backitup#1191]
**Describe the bug**  
Every backup from iobroker is created with a size of 0 bytes. please see log below with the error.
I tried to reinstall npm package tar-fs mutliple times, but no chance

**Screenshots & Logfiles**  

host.iobroker 12249 states saved
host.iobroker 13834 objects saved
host.iobroker Cannot pack directory /opt/iobroker/node_modules/iobroker.js-controller/tmp/backup: tar.create is not a function
**host.iobroker Backup not created: tar.create is not a function**
Cannot create backup: tar.create is not a function

**Versions:**  
 - Adapter version: 3.0.26
 - JS-Controller version: 6.0.6
 - Node version: 20.15.1
 - Operating system: debian

**Comment by linos22** [comment]
Updated to 3.0.31 and tried again -> no luck

**Comment by simatec** [comment]
Please test the CLI Command `iob Backup `

**Comment by linos22** [comment]
![grafik](https://github.com/user-attachments/assets/0b9716cb-2861-45f4-9cb0-4cd87ca58612)
Sorry, it is the same

**Comment by simatec** [comment]
If the CLI command also returns the error, it is not a problem with Backitup.
It looks like your system is defective.
Please try `iob fix` or reinstall the js-controller
