### ISSUE TITLE
Komplett Backup

### ISSUE THREAD

**Issue by cyberax17** [simatec/ioBroker.backitup#122]
First: great tool this is very useful!

However, I have issues when I want to run the complete / Komplett-Backup.
It starts doing something and then stops with 
```
[DEBUG] [total] - TAR started...
[DEBUG] [total] - Ignore dir: /home/xxx/backups
[DEBUG] [total] - Packed 0MB so far...
```

The minimum backup runs through perfectly.

Any ideas what could be the reason?
Where could I get more detailed logs, or can I run the complete backup from terminal showing more logs?
Could it be a rights issue? 
Biobroker runs as user Iobroker but is part of sudo group.

Many thanks for your assistance in advance!

adapter version: 1.1.2

**Comment by simatec** [comment]
Was mir auffällt ist, dass deine Installation nicht dem Standard entspricht.
Eigentlich müsste iobroker unter /opt/iobroker installiert sein.
Poste mal den kompletten Log.
Gibt es errors?

**Comment by cyberax17** [comment]
Keine Errors im Log und auch nicht vom system. Das macht ja die Fehlersuche ein bisschen frickelig...
Sobald ich Zeit hab werde ich mal den kompletten Log vom manuellen Backup Lauf Posten. 
Wie gesagt das minimal Backup läuft prima durch.
In der Tat ist die Installation nicht Standard, wollte ihn nur mal testen und dann ist er plötzlich zur Produktivumgebung geworden...naja vielleicht werde ich ihn mal demnächst neu installieren :-)
