### ISSUE TITLE
"Standard Backup" funktioniert; "Komplett Backup" nicht

### ISSUE THREAD

**Issue by fischmir** [simatec/ioBroker.backitup#125]
Hallo zusammen,

wie gesagt; ansicht funktioniert backitup (danke an der Stelle!!), aber beim "Komplett Backup" weigert er sich:

backitup.0 | 2019-03-12 20:43:52.164 | debug | redis pmessage  io.backitup.0.oneClick.* io.backitup.0.oneClick.total  {"val":false,"ack":true,"ts":1552419832163,"q":0,"from":"system.adapter.backitup.0","lc":1552419832163}
-- | -- | -- | --
backitup.0 | 2019-03-12 20:43:52.161 | debug | [total] exec: done
backitup.0 | 2019-03-12 20:43:52.140 | debug | redis pmessage  io.backitup.0.oneClick.* io.backitup.0.oneClick.total  {"val":true,"ack":false,"ts":1552419832139,"q":0,"from":"system.adapter.admin.1","lc":1552419832139}
backitup.0 | 2019-03-12 20:41:04.575 | debug | system.adapter.admin.1: logging true
backitup.0 | 2019-03-12 20:41:04.573 | debug | redis pmessage  io.*.logging io.system.adapter.admin.1.logging  {"val":true,"ack":true,"ts":1552419664571,"q":0,"from":"system.adapter.admin.1","lc":1552419664571}

Welche Infos kann ich noch bereitstellen?

Viele Grüße,
Christian

**Comment by simatec** [comment]
An diesem Log kann ich nichts erkennen ...

**Comment by fischmir** [comment]
Ok, was könnte ich tun? Ist halt komisch, dass das Standard-Backup klappt, aber nicht beim Komplett-Backup. Was könnten denn dafür die Gründe sein?

**Comment by simatec** [comment]
Willst du das backup lokal anlegen oder extern?
Schalte mal direkt in den Haupteinstellungen des Adapters auf debug. 
Wenn du redis nicht nutzt, kann es sein, dass du iobroker stop bei einem kompletten Backup aktivieren musst.

**Comment by fischmir** [comment]
Extern auf einem NAS (synology). Ich nutze redis NICHT und habe "IOBroker Stop" aktiviert, aber es klappt trotzdem nicht. Meine erste initiale Meldung kommt bereits aus dem Log, als der Adapter mit Loglevel "Debug" unterwegs war. Hier nochmal der Ausschnitt nach Neustart des Adapters:


backitup.0 | 2019-03-15 08:19:56.797 | debug | redis pmessage  messagebox.system.adapter.backitup.0  messagebox.system.adapter.backitup.0  {"command":"getTelegramUser","message":null,"from":"system.adapter.admin.1","callback":{"message":null,"id":2
-- | -- | -- | --
backitup.0 | 2019-03-15 08:19:35.713 | debug | [total] 10 35 10 */1 * *
backitup.0 | 2019-03-15 08:19:35.705 | info | [total] backup was activated at 10:35 every 1 day(s)
backitup.0 | 2019-03-15 08:19:35.705 | debug | [minimal] 10 40 10 */1 * *
backitup.0 | 2019-03-15 08:19:35.674 | info | [minimal] backup was activated at 10:40 every 1 day(s)
backitup.0 | 2019-03-15 08:19:35.631 | info | starting. Version 1.1.2 in /opt/iobroker/node_modules/iobroker.backitup, node: v8.11.1
backitup.0 | 2019-03-15 08:19:35.506 | info | States connected to redis: 127.0.0.1:6379
backitup.0 | 2019-03-15 08:19:35.493 | debug | statesDB connected
backitup.0 | 2019-03-15 08:19:35.456 | debug | objectDB connected
backitup.0 | 2019-03-15 08:19:31.974 | info | terminating
backitup.0 | 2019-03-15 08:19:31.512 | debug | system.adapter.admin.1: logging true
backitup.0 | 2019-03-15 08:19:31.511 | debug | redis pmessage  io.*.logging io.system.adapter.admin.1.logging  {"val":true,"ack":true,"ts":1552634371510,"q":0,"from":"system.adapter.admin.1","lc":1552634371510}
backitup.0 | 2019-03-15 08:18:52.405 | debug | redis pmessage  messagebox.system.adapter.backitup.0  messagebox.system.adapter.backitup.0  {"command":"getTelegramUser","message":null,"from":"system.adapter.admin.1","callback":{"message":null,"id":2
backitup.0 | 2019-03-15 08:18:47.566 | debug | system.adapter.admin.1: logging false
backitup.0 | 2019-03-15 08:18:47.565 | debug | redis pmessage  io.*.logging io.system.adapter.admin.1.logging  {"val":false,"ack":true,"ts":1552634327564,"q":0,"from":"system.adapter.admin.1","lc":1552634327564}
backitup.0 | 2019-03-15 08:18:35.105 | debug | system.adapter.admin.1: logging true
backitup.0 | 2019-03-15 08:18:35.104 | debug | redis pmessage  io.*.logging io.system.adapter.admin.1.logging  {"val":true,"ack":true,"ts":1552634315104,"q":0,"from":"system.adapter.admin.1","lc":1552634315104}

Hilft das weiter?

**Comment by simatec** [comment]
Was mir auffällt, dass es sinnvoller wäre die Zeiten zu tauschen.
Erst das minimal und dann ca. 30 Minuten versetzt das total.
Ansonsten sagt der log nix aus, da ich nicht sehen kann, was beim total backup passiert.
Wenn bräuchte ich den Log vom total Backup.
Dein Log zeigt nur das starten oder neustarten von backitup.

**Comment by xxPunikaxx** [comment]
Hab scheinbar genau das gleiche Problem. Meine Standard Backups werden in meine Dropbox hochgeladen. Full Backups (mit Stop ioBroker at Backup aktiviert) werden nicht erstellt/hochgeladen.

**Comment by simatec** [comment]
Auch mit stop geht es ... gerade getestet. 
Allerdings dauert dann der Stop länger, da erst nach vollständigen Upload iobroker wieder gestartet wird.

**Comment by fischmir** [comment]
Ich habe das Backup auf 11h geschoben; das MinimalBackup auf 10h. Das sind die einzigen Meldungen vom Log um 11h.


2019-03-20 11:00:10.079  - debug: backitup.0 [total] exec: done
--
2019-03-20 11:00:10.083  - debug:  backitup.0 redis pmessage  io.backitup.0.oneClick.*  io.backitup.0.oneClick.total  {"val":true,"ack":true,"ts":1553076010081,"q":0,"from":"system.adapter.backitup.0","lc":1553076010081}
2019-03-20 11:00:10.084  - debug:  backitup.0 redis pmessage  io.backitup.0.oneClick.*  io.backitup.0.oneClick.total  {"val":false,"ack":true,"ts":1553076010082,"q":0,"from":"system.adapter.backitup.0","lc":1552890562407}


Passiert ist aber leider nix. Was könnte ich noch versuchen?

**Comment by simatec** [comment]
Von wann ist deine iobroker Installation?
Ist sie noch recht neu oder schon älter?
Wenn sie neu ist, installiere den Installer Fix von iobroker. 

Sonst kannst du auch noch einmal testen, was passiert, wenn du iobroker für das total backup nicht stoppst

**Comment by truegreyhound** [comment]
Habe selbiges Problem schon länger, vielleicht gibt es ja schon neue Ideen:
**Installation**:
- Installation unter User iobroker
- node-Installation unter User iobroker, Version 8.15.1
- OS: Debian 4.7.2-5
- JS Controller: 1.5.7
- backitup: 1.1.3

Das Problem besteht unabhängig ob ioBroker gestoppt wird oder nicht.

**Log**:
`Gestartet...
[DEBUG] [total] start with {"type":"creator","time":"03:17","debugging":true,"everyXDays":"1","nameSuffix":"XOU4","deleteBackupAfter":0,"history":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.2","SilentNotice":true,"NoticeType":"longTelegramNotice","User":"allTelegramUsers","onlyError":false,"telegramWaiting":0,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"email.0","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"stopIoB":false,"emailWaiting":0,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"systemLang":"de"},"dir":"/opt/iobroker","redis":{"enabled":true,"ftp":{"enabled":false,"type":"storage","source":"Local","host":"192.168.xxx.xxx","deleteOldBackup":false,"ownDir":false,"bkpType":"Minimal","dir":"","dirMinimal":"/backupDir/minimal","dirTotal":"/backupDir/total","user":"iobroker","pass":"geheim","port":"21"},"cifs":{"enabled":false,"mountType":"CIFS","type":"storage","source":"Local","mount":"192.168.xxx.xxx","fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"*","wolTime":"25","smb":"vers=2.0","sudo":true,"deleteOldBackup":true,"ownDir":true,"bkpType":"Minimal","dir":"bu/iobroker/Odroid_XU4/complete","dirMinimal":"bu/iobroker/Odroid_XU4/Standard","dirTotal":"bu/iobroker/Odroid_XU4/complete","user":"iobroker","pass":"geheim"},"dropbox":{"enabled":false,"type":"storage","source":"Local","deleteOldBackup":false,"accessToken":"","ownDir":false,"bkpType":"Minimal","dir":"","dirMinimal":"","dirTotal":""},"path":"/opt/iobroker/iobroker-data/states.rdb"},"stopIoB":false,"backupDir":"/opt/iobroker/backups"}
[DEBUG] [total] - TAR started...
[DEBUG] [total] - Ignore dir: /opt/iobroker/backups
[DEBUG] [total] - src: /opt/iobroker; dest: /opt/iobroker/backups/total_2019_03_27-11_30_02_XOU4_backupiobroker.tar.gz
[DEBUG] [total] - Packed 4MB so far...
`
Und an dieser Stelle bleibt targz hängen. 

`# lsof|grep gz` liefert dann noch
`io.backit  6002        iobroker   16w      REG        8,1  4768026   12326456 /opt/iobroker/backups/total_2019_03_27-11_30_02_XOU4_backupiobroker.tar.gz
node       6002 6003   iobroker   16w      REG        8,1  4768026   12326456 /opt/iobroker/backups/total_2019_03_27-11_30_02_XOU4_backupiobroker.tar.gz
node       6002 6004   iobroker   16w      REG        8,1  4768026   12326456 /opt/iobroker/backups/total_2019_03_27-11_30_02_XOU4_backupiobroker.tar.gz
node       6002 6005   iobroker   16w      REG        8,1  4768026   12326456 /opt/iobroker/backups/total_2019_03_27-11_30_02_XOU4_backupiobroker.tar.gz
node       6002 6006   iobroker   16w      REG        8,1  4768026   12326456 /opt/iobroker/backups/total_2019_03_27-11_30_02_XOU4_backupiobroker.tar.gz
node       6002 6007   iobroker   16w      REG        8,1  4768026   12326456 /opt/iobroker/backups/total_2019_03_27-11_30_02_XOU4_backupiobroker.tar.gz
node       6002 6063   iobroker   16w      REG        8,1  4768026   12326456 /opt/iobroker/backups/total_2019_03_27-11_30_02_XOU4_backupiobroker.tar.gz
node       6002 6064   iobroker   16w      REG        8,1  4768026   12326456 /opt/iobroker/backups/total_2019_03_27-11_30_02_XOU4_backupiobroker.tar.gz
node       6002 6065   iobroker   16w      REG        8,1  4768026   12326456 /opt/iobroker/backups/total_2019_03_27-11_30_02_XOU4_backupiobroker.tar.gz
node       6002 6066   iobroker   16w      REG        8,1  4768026   12326456 /opt/iobroker/backups/total_2019_03_27-11_30_02_XOU4_backupiobroker.tar.gz`

Ob das richtig ist, kann ich nicht beurteilen. Mit ` tar cvzf /opt/iobroker-oxu4-2019-03-27.tgz --exclude=/opt/iobroker/backups /opt/iobroker` kann ich aber ohne Probleme ein Backup erstellen, sollte aus meiner Sicht technisch identisch sein. 
Habe auch überprüft, dass es keine Dateien gibt, auf die der User iobroker nicht zumindest Leserechte hat.

In den Beschreibungen habe ich nicht gefunden, ob es für bestimmte Version Einschränkungen (JS Controller, etc.) oder k.o.-Kriterien gibt.

**Comment by simatec** [comment]
Hast du den Installer Fix bereits installiert?
Dieser reguliert einige Probleme mit Rechten des Users iobroker.

**Comment by truegreyhound** [comment]
ja, ist installiert
Gibt es eine Möglichkeit, wenn auch nur Testweise, den Aufruf von 20_total.js mit root-Rechten mal laufen zu lassen?

**Comment by fischmir** [comment]
Hallo zusammen, 

ich habe  den Installer-Fix installiert und nun klappt es! (https://forum.iobroker.net/topic/20211/iobroker-installation-fixer-beta-verf%C3%BCgbar)

Zumindest beim manuellen Start funktioniert es nun; ich gehe davon aus, dass es nun auch bei der Einplanung funktioniert. IOBroker stoppe ich NICHT.

Danke für die Unterstützung!
Christian
