### ISSUE TITLE
BackupZeit fehlerhaft

### ISSUE THREAD

**Issue by t1m02k16** [simatec/ioBroker.backitup#130]
Ich möchte das ein Backup um 03:00 gemacht wird. Also nachts. Gemacht wird es jedoch um 15 Uhr

**Comment by simatec** [comment]
Dann stimmt auf deinem System etwas nicht mit deiner Zeitzoneneinstellung.
Damit hat backitup nix zutun.

**Comment by t1m02k16** [comment]
![image](https://user-images.githubusercontent.com/19432480/54422750-71276700-470f-11e9-9267-cc3d70500e69.png)
eigentlich nicht...
