### ISSUE TITLE
Fehler beim "Backups Abrufen"

### ISSUE THREAD

**Issue by t1m02k16** [simatec/ioBroker.backitup#131]
Moin,
ich habe folgende Fehlermeldung. 

Schritte: Wiederherstellen -> Ftp -> Minimal -> Backups abrufen
Fehlermeldung:
![image](https://user-images.githubusercontent.com/19432480/54528985-e3ea4980-497e-11e9-8ad8-d9573016cdf9.png)

Backups werden ohne Fehlermeldung geschrieben und befinden sich auch auf dem NAS.

**Comment by simatec** [comment]
Wie werden die Backups auf dem NAS gespeichert? Auch per FTP?
Ich habe das ganze nachgestellt und kann keinen Fehler feststellen.
Hast du nach der Auswahl von FTP im Wiederherstellungstab die Einstellungen gespeichert?
Benutzt du Extrapfade oder ein Pfad für alle Backuptypen?

**Comment by t1m02k16** [comment]
Sry... 
habe vorher nicht gespeichert...
Erst speichern, dann abrufen! Klappt perfekt!
Trotzdem danke für deinen Super schnellen support!!!!
