### ISSUE TITLE
Adaptereinstellungen fehlen nach Restore

### ISSUE THREAD

**Issue by eXTreMe-1337** [simatec/ioBroker.backitup#132]
Habe gerade ein Komplett-Backup wiederhergestellt, nachdem ein Stromausfall meinen iobroker komplett zerschossen hatte, dabei musste ich feststellen, dass die Adapter und ihre Einstellungen nicht mit wiederhergestellt wurden. Die Ordner der jeweiligen Adapter unter opt/iobroker/iobroker-data/files waren vorhanden aber leer. habe diese dann aus einem früheren backup des iobroker-data ordners auf meinem PC wiederhergestellt, dann musste ich feststellen, dass scheinbar die zugehörigen Dateien der Adapter im ordner node_modules auch nicht funktionieren... damit beschäftige ich mich nun.....
Gibt es eine erklärung warum die Ordner unter "iobroker-data/files" leer sind?
Habe auch ein anderes komplett-backup von 3 tagen vorher ausprobiert, gleiches problem.
Kann ich irgendwelche hilfreichen logs zur verfügung stellen?

**Comment by simatec** [comment]
Wenn das komplett backup durchlief, poste bitte mal den Log. 
Beim komplett backup wird der vollständige Ordner von iobroker gesichert. 
Ausgeschlossen wird nur der Ordner backups. 
Grundsätzlich ist aber bei einem neu aufsetzen des Systems immer ein Standard Backup zur Wiederherstellung der bessere Weg.
