### ISSUE TITLE
Fehlermeldung, nach dem Aufspielen, von Minimalbackup

### ISSUE THREAD

**Issue by senger1985** [simatec/ioBroker.backitup#135]
Folgende Fehlermeldung erscheint, wenn ich via Adapter ein Backup aufspielen möchte.

2019-03-27 10:53:32.234 - error: backitup.0 [ERROR] [minimal] Cannot parse /opt/iobroker/node_modules/iobroker.type-detector/io-package.json:Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.type-detector/io-package.json'
2019-03-27 10:53:32.241 - warn: backitup.0 Cannot read log file: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.backitup/lib/total.json'

**Comment by simatec** [comment]
Von wann ist das Backup und was passiert, wenn du es über Konsole mit dem Befehl „sudo iobroker restore 0“ probierst?

**Comment by senger1985** [comment]
Das Backup ist von heute morgen 2:00 Uhr
Wenn ich es über die Console einspiele, habe ich keine Probleme/Fehlermeldungen

**Comment by simatec** [comment]
Welche Version von backitup nutzt du?
Welche Versionen von node, nodejs, npm und dem js-Controller dind installiert?

Poste auch mal bitte den kompletten Log vom restore

**Comment by senger1985** [comment]
Adapter: 1.1.3
Node: 8.15.1
NodeJS: 8.15.1
npm: 6.9.0
Controller: 1.5.7

Die komplette Log habe ich leider nicht mehr.

**Comment by simatec** [comment]
Kannst du den Restore bitte nochmal starten, denn ohne kompletten Log ist die Fehlersuche schwer. 
Tratt der Fehler einmal auf oder hast du nach einem Adapterneustart das ganze ein weiteres mal probiert. 

So wie ich es sehe, wurde die total.json nicht erstellt oder es gibt ein Rechteproblem ubd dementsprechend kein Zugriff.

**Comment by senger1985** [comment]
backitup.0 | 2019-03-27 19:40:03.251 | info | [minimal] backup was activated at 2:00 every 1 day(s)
-- | -- | -- | --
backitup.0 | 2019-03-27 19:40:03.052 | info | starting. Version 1.1.3 in /opt/iobroker/node_modules/iobroker.backitup, node: v8.15.1
host.senger1985 | 2019-03-27 19:40:02.107 | info | instance system.adapter.backitup.0 started with pid 6538
host.senger1985 | 2019-03-27 19:40:00.108 | info | instance system.adapter.backitup.0 terminated with code 0 (OK)
host.senger1985 | 2019-03-27 19:39:59.578 | info | stopInstance system.adapter.backitup.0 killing pid 6496
host.senger1985 | 2019-03-27 19:39:59.578 | info | stopInstance system.adapter.backitup.0
host.senger1985 | 2019-03-27 19:39:59.570 | info | object change system.adapter.backitup.0
backitup.0 | 2019-03-27 19:39:33.833 | info | [minimal] backup was activated at 2:00 every 1 day(s)
backitup.0 | 2019-03-27 19:39:33.419 | warn | Cannot read log file: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.backitup/lib/total.json'
backitup.0 | 2019-03-27 19:39:33.412 | error | [ERROR] [minimal] Cannot parse /opt/iobroker/node_modules/iobroker.type-detector/io-package.json:Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.type-detector/io-p
backitup.0 | 2019-03-27 19:39:33.300 | info | starting. Version 1.1.3 in /opt/iobroker/node_modules/iobroker.backitup, node: v8.15.1

**Comment by simatec** [comment]
Stelle mal bitte die Instanz von backitup mal auf debug.
Der Log sagt nix leider nix aus.
Ich habe es gerade mal nachgestellt und konnte den Fehler nicht reproduzieren ...
Anstonsten wäre noch ein Löschen des Adapters und der Instanz und dann neu installieren.

Hast du den Installerfix installiert?
`curl -sL https://iobroker.net/fix.sh | bash -`

**Comment by senger1985** [comment]
Mehr wirft der Adapter in der Log nicht aus, auch nicht im debug

**Comment by simatec** [comment]
Hast du die Instanz oder in den Adaptereinstellungen auf debug?
Was hast du da mit iobroker.type-detector?
Den Pfad gibt es nicht.

Und nochmal die Frage ... Hast du den Installerfix drauf?

**Comment by senger1985** [comment]
Die Instanz habe ich auf debug.
Liegt es vielleicht daran, dass ich den ioBroker, auf einer VM, unter Proxmox, laufen lasse?
Nein, Installerfix habe ich nicht drauf.(Wozu ist der gut?)

**Comment by simatec** [comment]
Um Rechteprobleme zu beheben.
Bitte installiere diesen mal 
`curl -sL https://iobroker.net/fix.sh | bash -`
und testen dann den Restore

**Comment by simatec** [comment]
> Die Instanz habe ich auf debug.
> Liegt es vielleicht daran, dass ich den ioBroker, auf einer VM, unter Proxmox, laufen lasse?
Nein hab ich auch einiges ...

**Comment by senger1985** [comment]
Hab den Installerfix installiert und erneut ein Backup aufgespielt.
Fehler bleibt bestehen.
Der Backup-Ordner ist auch auf 777.

**Comment by simatec** [comment]
Irgendwas scheint an deinem Backup nicht in Ordnung zu sein.
Den Ordner /opt/iobroker/node_modules/iobroker.type-detector gibt es auf keinen meiner Sytseme.
Was hast du da auf deinem alten iobroker installiert?

**Comment by simatec** [comment]
Kannst du denn das backup auf deinem alten System wiederherstellen?

**Comment by senger1985** [comment]
Das alte System existiert nicht mehr. Da der PI, für ein anderes Projekt gebraucht wurde.
Der type-detector soll irgendwas, mit dem Material-Adapter zu tun haben.(laut Beschreibung)

**Comment by simatec** [comment]
Die Datei /opt/iobroker/node_modules/iobroker.type-detector/io-package.json gibt es nicht.
Laut github exitiert diese Datei garnicht.
Dementsprechend wirft er deshalb irgendwie den Fehler raus.
Warum dies beim Restore über Konsole geht, ist mir ein Rätsel.
Backitup nutzt den identischen Weg.
Ich gebe das mal an die Dev Experten im iobroker weiter.

**Comment by senger1985** [comment]
Alles klar.
Danke, für deine Mühe.

**Comment by simatec** [comment]
Der Fehler wurde von @GermanBluefox im js-controller gefixt und wird mit der nächsten version vom js-controller behoben sein.

https://github.com/ioBroker/ioBroker.js-controller/commit/a488d85d9cc599a31cb0a6b5b4a5889cc056f294
