### ISSUE TITLE
Wunsch: Integration von "Ignore dir"

### ISSUE THREAD

**Issue by nkleber78** [simatec/ioBroker.backitup#136]
In manchen fällen, wie z.b. bei mir wäre es sinnvoll wenn einzelne Verzeichnisse ignoriert werden könnten. Wie ich sehe gibt es die Funktion ja schon, denn das Verzeichnis backups wird bereits ignoriert. In meinem fall wäre es wichtig, denn ich habe usb devices verlinkt in ein IOBroker Verzeichnis. Aber die devices (z.b. dev/ttyUSB0 kann das system nicht sichern. Daher sollte es eine möglichkeit geben dieses zu ignorieren

**Comment by simatec** [comment]
Ist nicht geplant, da man keine Verzeichnisse in den iobroker verlinken sollte.
Am besten du verlinkst es an einen anderen Ort.
