### ISSUE TITLE
Backup Komplett funktioniert nicht mehr

### ISSUE THREAD

**Issue by quorle** [simatec/ioBroker.backitup#138]
Ich habe heute feststellen müssen, dass leider das komplette Backup nicht mehr funktioniert.
Ich habe den Adapter einmal auf DEBUG gestellt, jedoch wird in der Log nichts geschrieben.

Ich habe heute einmal das komplette Backup manuell gestartet, jedoch wird nur der ioBroker anscheinlich gestoppt ( läuft für mich weiter, da die "rotierenden Kreise" nicht kommen. Es wird auch keine Telegramnachricht versendet. Drückt man auf Schließen des Fensters, läuft alles wie immer weiter. Speicherplatz wäre genügend vorhanden.

**Comment by simatec** [comment]
Ich bräuchte mehr Infos von dir. 
Was für Versionen von node, nodejs, npm und js-Controller sind installiert?
Welche Plattform nutzt du? Wann wurde dein iobroker in etwa aufgesetzt?

Hat es auf dem selben System funktioniert? Wenn ja, was für Updates wurden seitdem durchgeführt?

**Comment by quorle** [comment]
Also ioBroker läuft auf einem intel NUC mit I5 unter Proxmox.
Versionen:
Node: v8.15.1
NPM: 6.4.1
NodeJS: v8.15.1
js-controller: 4.1.12
Backitup: 1.1.3

Die Backups hatten schon einmal geklappt, ohne Probleme auf diesem System. 
Das System wurde so wie es momentan ist im Dezember 2018 aufgesetzt.
Es wurden nur die Adapter und das Debian System regelmäßig mit Updates versorgt.

**Comment by simatec** [comment]
Diese js Controller Version gibt es nicht. 
Hast du den Installer Fix installiert. Im Dezember gab es ein paar Probleme mit den Rechten. Wenn nicht, installiere mal den Fix

**Comment by quorle** [comment]
Sorry, habe mich mit dem js-controller vertan, habe die Version 1.5.7

Habe nun mal das FIX-Script laufen lassen und nun funktioniert es wieder. 

Ich kann mich nur für die schnelle Hilfe bedanken.
