### ISSUE TITLE
Feature Request: Username Domain Support

### ISSUE THREAD

**Issue by tsvsj** [simatec/ioBroker.backitup#143]
Hi,

thanks for this great adapter! Unfortunately I cannot use it, because my NAS uses Active Directory for user authentication. The cifs-mount need the option "domain=<DOMAIN>", which is currently not supported or configurable within the adapter.

Unfortunately I'm not familiar with the development of adapters and therefore can't figure out how and where to do the change. I thought of writing the update and send a merge request to the repo, but for now I don't know anything about the adapter development...

Thanks in advance.

Regards

**Comment by tsvsj** [comment]
Ok. I got that working, by editing 
`/opt/iobroker/node_modules/iobroker.backitup/lib/list/cifs.js` (Lines 158 and 160)
`/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/01-mount.js` (Lines 72 and 74)
directly and statically. After a restart of ioBroker it works fine now.

But do you see a chance to add the option to the configuration, to make my change aware for updates?

**Comment by tsvsj** [comment]
Unfortunately the dev does not respond to issues. Maybe this project should be forked to a community adapter.

This issue still persists in new installs and I don't see to use it like that.

**Comment by simatec** [comment]
I'm already responding to problems.  But one by one please.  It's a hobby for all of us

**Comment by simatec** [comment]
> Ok. I got that working, by editing
> `/opt/iobroker/node_modules/iobroker.backitup/lib/list/cifs.js` (Lines 158 and 160)
> `/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/01-mount.js` (Lines 72 and 74)
> directly and statically. After a restart of ioBroker it works fine now.
> 
> But do you see a chance to add the option to the configuration, to make my change aware for updates?

please post your changes here so I can check them

**Comment by tsvsj** [comment]
That's true and I'm honoring your work - really. But you need to be honest as well, that not responding for almost one year is far away from one by one. I didn't want to blame you.

Do you see a chance to add the domain parameter as well?

**Comment by tsvsj** [comment]
> > Ok. I got that working, by editing
> > `/opt/iobroker/node_modules/iobroker.backitup/lib/list/cifs.js` (Lines 158 and 160)
> > `/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/01-mount.js` (Lines 72 and 74)
> > directly and statically. After a restart of ioBroker it works fine now.
> > But do you see a chance to add the option to the configuration, to make my change aware for updates?
> 
> please post your changes here so I can check them

Unfortunately I didn't have them anymore, because it was in an old installation of ioBroker, already deleted.

It's just the option "domain=<DOMAIN>" in the mount command.

**Comment by tsvsj** [comment]
`mount -t cifs -o username=<USERNAME>,password=<PASSWORD>,domain=<DOMAIN> ...`
Optionally the option to use a credentials file would be great, but is not strictly necessary.

Thanks!

**Comment by simatec** [comment]
I can add this function to the WebUi as an option.

**Comment by tsvsj** [comment]
Very much appreciated! Thank you!

**Comment by simatec** [comment]
Added at 1.4.0
