### ISSUE TITLE
iPad/Safari: Konfig-Page unvollständig

### ISSUE THREAD

**Issue by eric2905** [simatec/ioBroker.backitup#145]
Im Admin ist die Konfig-Seite auf einem iPad mit Safari als Browser nicht nutzbar.
Das Menü in der Kopfzeile liegt z.T. außerhalb des sichtbaren Bereiches und kann nicht seitlich gescrollt werden.

![F6EAE12D-F6F1-4BFE-A4B5-09D14F2963FE](https://user-images.githubusercontent.com/18639287/56073794-a922d800-5da9-11e9-9db4-de961c7c46db.jpeg)

**Comment by simatec** [comment]
Das ist kein Problem von backitup, sondern ein generelles Problem bei Safari in Verbindung mit iobroker
