### ISSUE TITLE
Nach Backup und Admin restart starten teilweise und sporadisch Instanzen nicht mehr

### ISSUE THREAD

**Issue by XerXes777** [simatec/ioBroker.backitup#146]
Moin Moin,

nach einen geplanten Komplettbackup bekomme ich immer mit verschieden Instanzen, das diese schon gestertet sind. Mal es ist es node oder mal homematic.

Dies ist schon länger so und habe jetzt erst herausgefunden, dass das der Backitup Adapter ist.

Kann manuel den admin mit allen Instanzen zich mal manuell neustarten ohne das diese meldungen kommen.

wenn aber der neustart mit backitup durchgeführt wird kommt es sporadisch dazu, das irgendeine instanz dann merkert, das diese bereits läuft.

was kann ich tun?

**Comment by simatec** [comment]
Bitte Log posten ...
