### ISSUE TITLE
feature request: Kontrolle der Logindaten FTP

### ISSUE THREAD

**Issue by t1m02k16** [simatec/ioBroker.backitup#148]
Moin, mir ist heute aufgefallen, dass ich die FTP Login Daten vom NAS aus versehen gelöscht habe. 
"backitup" habt mir seit ca 2 Monaten keine Fehlermeldung ausgegeben, dass das Backup nicht überspielt werden konnte. Wäre cool, wenn man so etwas implementieren könnte.
Vielen Dank
Gruß

**Comment by simatec** [comment]
Wenn die Dateien nicht übertragen werden können, gibt es einen error, der z.B. per telegram, Email oder Pushover übermittelt werden kann.
