### ISSUE TITLE
Zigbee backup not working

### ISSUE THREAD

**Issue by Hambootje** [simatec/ioBroker.backitup#149]
Hi,

On my setup the backup is not working when I enable the new "save zigbee database" feature.
When I manually start the minimal backup, the process hangs on the zigbee backup:

```
......
[DEBUG] [minimal] - Backup created: /opt/iobroker/backups/minimal_2019_05_06-21_34_06_backupiobroker.tar.gz

[DEBUG] [minimal] - done
[DEBUG] [zigbee] start with {"type":"creator","path":"/opt/iobroker/iobroker-data"}
```

Could this be related to the fact that I have my zigbee instance running on an iobroker slave?

**Comment by simatec** [comment]
For backup your zigebee Database on slave, Your backitup Instance must run on slave

**Comment by Hambootje** [comment]
Yes, got it. Sorry for the trouble. To make the backup adapter a bit more (new) user friendly a could be build in that checks if the zigbee database is present on the instance selected.
