### ISSUE TITLE
Backup-File was not copied to other directory

### ISSUE THREAD

**Issue by Pascal51882** [simatec/ioBroker.backitup#15]
Hi I installed the adapter in ioBroker and started my first Backup.
In the Standard and Full BAckup i get always the same error at the transfer to my NAS.
The NAS is the same Device (OMV is on it).

Here the log:

|FTP|false|false||||||||/opt/iobroker]

[DEBUG] --- Minimal Backup started ---

[DEBUG] Backup created: /opt/iobroker/backups/minimal-2018_07_29-10_54_06_backupiobroker.tar.gz

[DEBUG] success --- Minimal Backup created ---

[DEBUG] --- Delete old backups ---

[ERROR] find: '': No such file or directory

[DEBUG] error --- Checking and deletion of the old backup files was NOT successful ---

[DEBUG] --- Starting Backup-File FTP-Upload ---

[DEBUG] minimal-2018_07_29-10_32_43_backupiobroker.tar.gz
minimal-2018_07_29-10_33_14_backupiobroker.tar.gz
minimal-2018_07_29-10_33_30_backupiobroker.tar.gz
minimal-2018_07_29-10_34_00_backupiobroker.tar.gz
minimal-2018_07_29-10_34_21_backupiobroker.tar.gz
minimal-2018_07_29-10_54_06_backupiobroker.tar.gz
minimalStandard.tar.gz

[DEBUG] error --- Backup-File was not copied to other directory ---

[EXIT] 0

**Comment by BramTown** [comment]
Ich klinke mich hier mal mit ein, da auch bei mir die Backups nicht auf meinem NAS ankommen.
Und ich könnte mit vorstellen, das liegt an einer falschen Konfiguration der NAS Verbindung (ganz gleich ob CIFS oder FTP).

Ich bin ein "normalsterblicher Anwender" und verstehe die Beschreibung in der Doku:
_Pfadangaben (Schreibweise beachten):
- CIFS: "Freigabename/Pfadangabe"
- FTP: "/Pfadangabe"_
nicht einmal ansatzweise ...

Ich habe null Ahnung was ich nun eigentlich eintragen soll/muss 
Und schon gar nicht WIE es eingetragen werden muss.
Erfolgen die Pfadangaben mit Schrägstriche links- oder rechstherum ( \ / ) ???
Muss eine Pfadangabe ggf. mit einem Schrägstrich Beginnen und Enden??)

Könnt ihr ggf. Beispiele mit Screenshots anfügen?

Mitunter bekommt Ihr Entwickler für eure klasse Arbeit nicht einmal ansatzweise die Anerkennung und den Lob den ihr verdient, da die Anwender es durch eine womöglich kleine fehlende Information nicht zum fliegen bekommen?!? 

:-)

**Comment by simatec** [comment]
The error messages when deleting old backups are currently not to be considered. these will be fixed in the next version.

Example for FTP path:

/backup/iobroker/minimal

Example for CIFS path:

Backup/iobroker/minimal 
(For cifs start without backslash)

**Comment by BramTown** [comment]
Thanks for your reply

still no chance to connect via CIFS
"ERROR: mount permission denied"
"ERROR Backup Path was not connected"

the user is administrator on my NAS

screenshotwith setting is  attached 
![backup_nas](https://user-images.githubusercontent.com/30980239/43365516-4a817702-932e-11e8-9147-d5d29ca73bbc.JPG)

**Comment by BramTown** [comment]
with the same settings (including starting "/" in the path) now it works fine in FTP mode

**Comment by Ilovegym66** [comment]
Tip: to use with ftp upper directorys, try //mnt/sda1/daten/backup/iobroker for example..

**Comment by Pascal51882** [comment]
I have it like in my screenshot down below.

**Comment by simatec** [comment]
@BramTown 
Please test the Host from your NAS an not the IP.
For using cifs: start path without / 

Test your mount manuel
mount -t cifs -o user=your username,password=yourpassword,rw,file_mode=0777,dir_mode=0777,vers=1.0 //your IP our Host/your path /your mountpath

**Comment by FuLLHDvs480p** [comment]
Hallo,

ist es möglich das Backup auch auf an einer FritzBox angeschossenen USB-Stick aufzuspielen?
Dort gibts es ja FritzNAS aber der Dateipfad funktioniert nicht richtig.

**Comment by simatec** [comment]
for Problem: "ERROR: mount permission denied"
https://wiki.ubuntuusers.de/Samba_Client_cifs/#mount-error-13-Permission-denied

**Comment by simatec** [comment]
Support for backitup: 
https://forum.iobroker.net/viewtopic.php?f=23&t=15256#p159468

**Comment by simatec** [comment]
@Pascal51882 
error Fix Please update version 0.2.7

**Comment by Pascal51882** [comment]
![image](https://user-images.githubusercontent.com/41856419/44001320-fe783ed8-9e2f-11e8-9807-d2a1454cb7eb.png)
I have it now like in the picture.
The path is the first folder on my NAS which host name is NAS.
The new log:
Gestartet...
[DEBUG] Creating minimal backup [minimal||1|NAS|BackupioBroker|ioBroker|pw||||CIFS|false|false||||||||/opt/iobroker]

[DEBUG] --- Mount Backup-Path on CIFS ---

[ERROR] mount: wrong fs type, bad option, bad superblock on //NAS/BackupioBroker,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

[DEBUG] error --- Backup path was not connected to CIFS server ---

[DEBUG] --- Minimal Backup started ---

[DEBUG] Backup created: /opt/iobroker/backups/minimal-2018_08_12-13_03_53_backupiobroker.tar.gz

[DEBUG] success --- Minimal Backup created ---

[DEBUG] --- Delete old backups ---

[DEBUG] success --- Checking and deletion of the old minimal backup files was successful ---

[EXIT] 0
