### ISSUE TITLE
Idea: Check platform before full restore

### ISSUE THREAD

**Issue by Horgul123** [simatec/ioBroker.backitup#150]
After trying to import a full backup on a different platform I got a strange error message. I've got the tipp, that a full backup can only be restored on the same platform

Idea: 
Add information about the platform/OS in the backup and check this when someone tries a restore.
If something chances, the user should get a warning (e.g. Platform/OS from the backup is different from the current platform. Restoring a full backup can cause errors and is not recommended. Please use a minimal backup. Do you really what to start the restore of the full backup?)

I this this is not a big thing but it could avoid some problems and questions. Normally I would expect that a full backup is better for a restore than a minimal backup :)

**Comment by simatec** [comment]
Fullbackup is no longer supported
