### ISSUE TITLE
Verbesserungsvorschlag: nfs Benutzerdaten

### ISSUE THREAD

**Issue by eumats** [simatec/ioBroker.backitup#152]
Aktuell kann man den Benutzer und das Passwort nur bei der Konfiguration von cifs eintragen und das wirkt dann auch für nfs. Das kann (hat bei mir) zu Verwirrung führen.
Mein Vorschlag wäre das man auch bei nfs Benutzt und Passwort sehen/defilieren könnte.

**Comment by simatec** [comment]
Die Aussage ist nicht korrekt.
Für nfs werden keine Userdaten verwendet.
nfs und cifs sind komplett unterschiedliche Prozesse.

NFS:
https://github.com/simatec/ioBroker.backitup/blob/bddaf8690b9d3a5961748126819ce87decbc2373/lib/scripts/01-mount.js#L95

CIFS:
https://github.com/simatec/ioBroker.backitup/blob/bddaf8690b9d3a5961748126819ce87decbc2373/lib/scripts/01-mount.js#L72

**Comment by eumats** [comment]
Sorry. War mein Fehler. Wieder was gelernt...
