### ISSUE TITLE
Wunsch: CCU Backup für debmatic

### ISSUE THREAD

**Issue by mijado** [simatec/ioBroker.backitup#153]
Hallo, danke für das super Backup Adapter.
Es wäre schön, wenn es noch das CCU Backup für debmatic unterstützen würde.

**Comment by simatec** [comment]
Laut meinen Infos wird unter debmatic das Backup identisch über das WebUI ausgeführt. 
Sollte damit auch ganz normal über backitup machbar sein. 
IP deiner debmatic eintragen und Benutzernamen und Passwort deiner WebUI.

**Comment by mijado** [comment]
Hallo simatec, stimmt hat geklappt - Wunsch erfüllt:-)
Habe ich eigentlich schon gemacht - vermutlich Layer 8 Fehler:-(
Danke
