### ISSUE TITLE
Restore of complete backup not working

### ISSUE THREAD

**Issue by easybeat** [simatec/ioBroker.backitup#159]
Hi
I made a complete backup to dropbox and then started ioBroker from a clone sd card from a few days ago and tried to restore this complete backup. But nothing happens and it looks like backitup does crash after a few mins.

Is there a log to check what it is doing or is restore function not working?

Thanks for help.
Beat

**Comment by fischhai** [comment]
Hi,

the same here on a Pi4B with Dietpi.

Best regards
fischhai

**Comment by simatec** [comment]
Please restore a new System with the Standard backup and not with total
