### ISSUE TITLE
Feature Request: Backup to S3 bucket

### ISSUE THREAD

**Issue by souhl** [simatec/ioBroker.backitup#162]
Hi,

it would be nice to be able to connect a S3 target (like Amazon S3) to store the backup.

Thanks
Sascha

**Comment by simatec** [comment]
Aufgrund dessen, dass es offiziell keine Unterstützung für S3 als npm Packet gibt, wird die Integration vorläufig nicht erfolgen.
Iobroker soll ein sicheres System sein und ohne offiziellen Support durch Amazon bin ich nicht dafür, dies in Backitup zu integrieren

**Comment by platdesign** [comment]
Ich würde mich über eine S3-Unterstützung auch freuen. 

Offizielle S3-Clients:
- [aws-sdk](https://www.npmjs.com/package/aws-sdk)
- [minio](https://www.npmjs.com/package/minio)

**Comment by souhl** [comment]
Das AWS S3 SDK gibt es auch als NPM. Damit kann man auf jeden S3 kompatiblen Speicher zugreifen. Gerne kann ich ein AWS S3 kompatibles Bucket zur Verfügung stellen. https://www.npmjs.com/package/@aws-sdk/client-s3
