### ISSUE TITLE
Google Drive 2. Instanz

### ISSUE THREAD

**Issue by vr6syncro** [simatec/ioBroker.backitup#167]
Moin, 

Google Drive mit der ersten Instanz geht wunderbar.
Wenn ich allerdings eine 2. Instanz konfigurieren will funktioniert das nicht. Man klickt auf den Button für Token holen ab dann passiert aber nichts weiter.

Keinerlei Einträge in den Logs auch mit debug nicht.

**Comment by simatec** [comment]
Kannst du die Settings aus der ersten Instanz nicht einfach importieren?

**Comment by vr6syncro** [comment]
das hatte ich nicht getestet sind aber andere settings bei der 2. instanz. manuelle token eingabe geht aber auch nicht da es noch kein feld dafür gibt.
