### ISSUE TITLE
Backitup funktioniert nach dem Update nicht mehr 

### ISSUE THREAD

**Issue by petkoh85** [simatec/ioBroker.backitup#168]
Ich erhalte seit dem letzten Update folgende Fehler im Log:

host.ioBroker-Cubie | 2019-08-14 06:56:18.875 | info | Restart adapter system.adapter.backitup.0 because enabled
-- | -- | -- | --
host.ioBroker-Cubie | 2019-08-14 06:56:18.873 | error | instance system.adapter.backitup.0 terminated with code 1 ()
host.ioBroker-Cubie | 2019-08-14 06:56:18.871 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/googleapis/build/src/index.js:19:22)
host.ioBroker-Cubie | 2019-08-14 06:56:18.869 | error | Caught by controller[0]:     at require (internal/module.js:20:19)
host.ioBroker-Cubie | 2019-08-14 06:56:18.867 | error | Caught by controller[0]:     at Module.require (module.js:504:17)
host.ioBroker-Cubie | 2019-08-14 06:56:18.866 | error | Caught by controller[0]:     at Function.Module._load (module.js:445:3)
host.ioBroker-Cubie | 2019-08-14 06:56:18.864 | error | Caught by controller[0]:     at tryModuleLoad (module.js:453:12)
host.ioBroker-Cubie | 2019-08-14 06:56:18.862 | error | Caught by controller[0]:     at Module.load (module.js:494:32)
host.ioBroker-Cubie | 2019-08-14 06:56:18.860 | error | Caught by controller[0]:     at Object.Module._extensions..js (module.js:586:10)
host.ioBroker-Cubie | 2019-08-14 06:56:18.859 | error | Caught by controller[0]:     at Module._compile (module.js:549:28)
host.ioBroker-Cubie | 2019-08-14 06:56:18.857 | error | Caught by controller[0]:     at Object.runInThisContext (vm.js:97:10)
host.ioBroker-Cubie | 2019-08-14 06:56:18.856 | error | Caught by controller[0]:     at createScript (vm.js:56:10)
host.ioBroker-Cubie | 2019-08-14 06:56:18.854 | error | Caught by controller[0]: SyntaxError: Unexpected identifier
host.ioBroker-Cubie | 2019-08-14 06:56:18.852 | error | Caught by controller[0]:           ^^^^^^^^^^^^^
host.ioBroker-Cubie | 2019-08-14 06:56:18.850 | error | Caught by controller[0]:     async discoverAsync(url) {
host.ioBroker-Cubie | 2019-08-14 06:56:18.845 | error | Caught by controller[0]: /opt/iobroker/node_modules/googleapis/build/src/googleapis.js:93
host.ioBroker-Cubie | 2019-08-14 06:56:16.918 | info | instance system.adapter.backitup.0 started with pid 10922

**Comment by simatec** [comment]
Welche node Version hast du installiert?

**Comment by petkoh85** [comment]
Version 6.16

**Comment by petkoh85** [comment]
Habe gerade ein Update gemacht. Jetzt läuft alles!

**Comment by simatec** [comment]
Node 6 Support wurde mit der Version 1.2.0 eingestellt.
