### ISSUE TITLE
Redis Backup "No source for compress"

### ISSUE THREAD

**Issue by MubiTec** [simatec/ioBroker.backitup#169]
Hi, 

I tried to do a backup my redis data, but I get a message via telegram:

"redis: No source for compress!"

Same issue at V1.1.4 and 1.2.0

Any idea what to do? There are no further logs in iobroker log.

Thanks in advance!

...PS: when I start the adapter, states connect: "States connected to redis: 127.0.0.1:6379"...

**Comment by simatec** [comment]
You must change the redis path in settings from backitup

**Comment by MubiTec** [comment]
And what is the right path? To the storage of the backups? It the same like the working standard backup.

**Comment by simatec** [comment]
Yout Path to the Redis Database
