### ISSUE TITLE
Google Drive Autorisierung funktioniert nicht

### ISSUE THREAD

**Issue by Gizimo** [simatec/ioBroker.backitup#170]
Hi,

wenn ich versuche den API Key zu bekommen damit die Autorisierung bei Google funktioniert dann bekomme ich die Meldung von Google:

Die Anmeldung mit Google ist für diese App vorübergehend deaktiviert
Die Verwendung von Google Log-in wurde für diese App noch nicht bestätigt.

Was da los!?

**Comment by simatec** [comment]
Das hat nix mit backitup sondern mit Google zu tun.

**Comment by Gizimo** [comment]
Andere Applikationen kann man aber mit Google Autorisieren, daher denke ich schon das es nichts direkt mit Google zu tun hat

**Comment by simatec** [comment]
Werde es mal auf einen weiteren System testen

**Comment by GermanBluefox** [comment]
Ich muss noch mein Google App zertifiziert bekommen. Bis ich das nicht mache, wird es leider für die neue User nicht mehr gehen

**Comment by Ahrenfelde** [comment]
Hi,

zu wann hast du die zertifizierung geplant?
Ich würde gern den Adapter mit G-Drive verwenden.

**Comment by simatec** [comment]
Ich konnte bei meinem Testsystem heute mit Google Autorisieren ... Es wird zwar gemeckert, dass die App von Google noch nicht geprüft ist, aber es ging, wie in den Screenshots zu sehen.

![backitup](https://user-images.githubusercontent.com/39792461/64526045-908bff00-d302-11e9-9b37-fcf5e1435fdb.JPG)
![backitup2](https://user-images.githubusercontent.com/39792461/64526057-97b30d00-d302-11e9-8cb7-6dd1e9d1a6c2.JPG)
![backitup3](https://user-images.githubusercontent.com/39792461/64526065-9d105780-d302-11e9-86e2-bec6f8c30ec5.JPG)

**Comment by Gizimo** [comment]
Ich hab leider nicht die Option das zu überspringen.... Bei mir kommt da nix mit Erweiteern etc....

**Comment by Ahrenfelde** [comment]
Bei mir auch nicht, welchen Browser benutzt du?

**Comment by Gizimo** [comment]
Habs auf Chrome und IE versucht

**Comment by simatec** [comment]
Bei mir lief es unter Chrome durch ...

**Comment by Gizimo** [comment]
grade nochmal versucht..... geht nicht 

Die Verwendung von Google Log-in wurde für diese App noch nicht bestätigt.

**Comment by simatec** [comment]
Ich werde mal mit Google Kontakt aufnehmen

**Comment by simatec** [comment]
Eventuell hilft bis Google da was macht das hier ...

<img width="976" alt="Bildschirmfoto 2019-09-15 um 14 01 41" src="https://user-images.githubusercontent.com/39792461/64921394-0c82bd00-d7c3-11e9-9005-443fb1116c29.png">

**Comment by Ahrenfelde** [comment]
Hallo,
nein das hilft nicht, hatte die Option schon aktiviert.
Melde dich bitte, wenn Google was gemacht hat, aktuell habe ich den Adapter wieder runtergeschmissen, möchte ihn aber gern nutzen!
Der Adapter ist wirklich gut gemacht, vielen Dank dafür!!!!
Zur not muss ich mir hier doch noch nen NAS einrichten und lokal speichern :)
Grüße
Jan

**Comment by grillmeister1** [comment]
Gibt es schon was neues mit der Anbindung zu Google Drive?
Ich habe den Adapter schon seit einem Jahr und Probiere immer und immer wieder mal. 
Hab es sonst mit einer Nas probiert und nicht zu laufen gekriegt und jetzt sitze ich schon wieder mit dem Versuch zu Google Drive. 

Wäre auch dankbar wenn einer eine echt gute Anleitung hätte. Habe schon einige durch. 🙈

**Comment by simatec** [comment]
Aktuell liegt es an google.. Die müssen das als App freigeben. 
Zwecks NAS komme mal ins Forum, da wird dir geholfen und lese die Anleitung von backitup hier auf Github

**Comment by Gizimo** [comment]
Wie ist hier der Status? liegt das noch bei google? 

Danke für das Update

**Comment by simatec** [comment]
Bisher gibt es keine Antwort von Google. Was sagt ein Versuch backitup mit deinem Konto zu verknüpfen?

**Comment by Gizimo** [comment]
Die App wurde von Google noch nicht freigeschaltet.... das bekomme ich als Meldung

**Comment by Starcon79** [comment]
Bei mir das gleiche. Hoffe Google meldet sich bald.

**Comment by bytegetter** [comment]
Bei gSuite ging es mit rclone nur, nachdem ich die API aus der URL in Google eingetragen hatte.

**Comment by simatec** [comment]
> Bei gSuite ging es mit rclone nur, nachdem ich die API aus der URL in Google eingetragen hatte.

Kannst du den Weg hier bitte mal genauer beschreiben?
Solange Google die App noch nicht freigegeben hat, wäre das ja dann sicher ein alternativer Weg, um google drive für backitup nutzen zu können

**Comment by bytegetter** [comment]
Dort die OAuth-ID eintragen:

https://admin.google.com/AdminHome?hl=de#Oauth2ScopeManagement:subtab=trusted

Anders hatte ich das mit der gSuite Stundenlang mit rclone nicht hinbekommen. Geiche Fehlerneldung wie oben. Ob das mit dem normalen gDrive funktioniert kann ich nicht sagen. Vielleicht gibt es da noch einen anderen Weg.

**Comment by mswiege** [comment]
Kann ich bestätigen. Hat bei mir (mit GSuite) so nun auch geklappt. Danke
Die OAuth-ID findet man innerhalb der URL die backitup anzeigt.

**Comment by bytegetter** [comment]
Freut mich, dass das so klappt.

Gibts für das normale Drive auch eine Lösung?

**Comment by sabphil22** [comment]
Inzwischen funktioniert das Backup auf google drive

**Comment by simatec** [comment]
Eine Meldung von Google gab es bisher wohl nicht. Konntest du die App mit deinem Account verknüpfen?

**Comment by sabphil22** [comment]
Ja ging gestern Abend ohne Probleme.

**Comment by simatec** [comment]
@GermanBluefox Hab es auch gerade noch einmal getestet und es ist nun durch Google freigegeben.

**Comment by unstressable** [comment]
Problem ist aktuell wieder vorhanden!
Ist die App wieder von Google gesperrt?

**Comment by simatec** [comment]
https://github.com/simatec/ioBroker.backitup/issues/1137
