### ISSUE TITLE
Passwort bei CIFS darf kein '&' enthalten

### ISSUE THREAD

**Issue by sbormann** [simatec/ioBroker.backitup#171]
Das Backup hat bei mir immer abgebrochen, bis ich gemerkt habe, dass der Mount-Befehl bei dem '&' im Passwort fehlgeleitet wird. Habe das Passwort dann mit Anführungszeichen gespeichert, damit lief es. Das könnte der Adapter noch selbst erledigen: Benutzername und Passwort in Anführungszeichen an den Mount-Befehl übergeben.

Dann noch eine kleine Sicherheitslücke: In der eMail mit der kompletten Fehlermeldung war das Passwort zu lesen!

Ansonsten: Mega Adapter!!! Daumen hoch und vielen Dank!!!

**Comment by simatec** [comment]
Passwort mit den Sonderzeichen ist bekannt. Ich schaue mal, ob wir das zukünftig im Adapter lösen können. 
Ansonsten schonmal vielen dank für dein Feedback und das Lob 😬

**Comment by simatec** [comment]
Sollte mit Version 1.2.1 gefixt sein ...
