### ISSUE TITLE
Redis Backup: OS X path must contain filename

### ISSUE THREAD

**Issue by Pix---** [simatec/ioBroker.backitup#172]
Wer ioBroker auf dem Mac nutzt und ein Redis-Backup einstellt, muss im Feld für die Pfadangabe zur Redis-Datei (dumb.rdb) auch unbedingt den Dateinamen selbst mit angeben

![Bildschirmfoto 2019-09-05 um 13 23 31](https://user-images.githubusercontent.com/8090989/64337793-5eb42900-cfe0-11e9-97c1-e2894214ca38.jpg)

Ohne die Angabe des Dateinamens und nur des Pfads hat das Backup-Skript einen Kopiervorgang gestartet, der das System zum Absturz gebracht hat. Es wurde kopiert, bis kein freier Festplattenspeicher mehr vorhanden war (bei mir >180GB).

Ich empfehle, die Beschreibung des Einstellungsfeldes zu präzisieren (Platzhalter?) und mindestens die Dokumentation zu erweitern.

Pix

**Comment by simatec** [comment]
Ist der im Bild oben gezeigte dateipfad der richtige?
Dann ist es klar, denn es wird alles im Pfad /Users/pix gesichert.

Ich schaue mal, was wir da noch für Sicherheiten einbauen können.

**Comment by Pix---** [comment]
In meinem Fall stimmt der Pfad, ist ja individuell.
![Bildschirmfoto 2019-11-18 um 12 33 27](https://user-images.githubusercontent.com/8090989/69049286-ce428d80-09ff-11ea-96bd-aa7b4adb2329.png)

**Comment by neopholus** [comment]
Hallo, ich habe mich ein wenig in Redis eingelesen und aus Gründen der Datensicherheit habe ich AOF (Append-Only-File) aktiviert. Redis würde im Falle eines Falles dann den letzten Dump heranziehen und aufgrund der AOF-Datei alle Änderungen bis zum Absturz "nachfahren" können. Ohne diese Datei fehlen alle Änderungen seit dem letzten Dump.
Siehe [https://redis.io/topics/persistence](https://redis.io/topics/persistence)

Diese Datei legt Redis im selben Verzeichnis ab wie dump.rdb.

Mit dieser Datei scheint Backitup ein Problem zu haben. Ich habe nun, wie von Pix vorgeschlagen, `/var/lib/redis/dump.rdb`
angegeben. Dann ist zumindest der Dump gesichert. 

Falls das AOF aktiv ist und in dem Verzeichnis liegt hängt das Redis Backup mit einer Aufgabe, dass bisher 0 MB gepackt sind eine laange Zeit und dann bricht Backup einfach ab. Ich vermute, das AOF-File ist von Redis immer geöffnet gehalten. Also kann entweder Backitup das File gar nicht lesen oder findet kein korrektes Ende....

Vielleicht ist das bei Pix genauso? Hast du AOF aktiviert?
