### ISSUE TITLE
Backup stuck while compressing SQL

### ISSUE THREAD

**Issue by kugelkopf123** [simatec/ioBroker.backitup#173]
Nodejs 10.16.3
NPM 6.9.0
Backupit 1.2.0
RaspiPi 3b+

```
2019-09-13 12:02:27.046 - debug: backitup.0 [minimal/mysql] Packed 14MB so far...
--
2019-09-13 12:02:37.052 - debug: backitup.0 [minimal/mysql] Packed 14MB so far...
2019-09-13 12:02:47.052 - debug: backitup.0 [minimal/mysql] Packed 14MB so far...

```
Get this in my log on debug sinds 10oClock when the backup starts. That happens nearly every day. Running backupit on debug mode. Thats all i get from this error in the log.

I have restart the Adapter to end this.

**Comment by simatec** [comment]
Test the new Installer Fix for mysqldump

**Comment by kugelkopf123** [comment]
> Test the new Installer Fix for mysqldump

I dont get it. What do you mean? Where can i find it? Had searched in this Git but couldnt find something.

**Comment by simatec** [comment]
`curl -sL https://iobroker.net/fix.sh | bash -`
