### ISSUE TITLE
Fullbackup not stored in Dropbox

### ISSUE THREAD

**Issue by machnetz** [simatec/ioBroker.backitup#177]
I'm in trouble with the fullbackup function. A fullbackup was scheduled and correctly executed, the file is stored local in /opt/iobroker/backups:

-rw-r--r-- 1 iobroker iobroker 440446632 Okt  7 11:45 total_2019_10_07-11_30_16_Full__backupiobroker.tar.gz

The logfile file says: 
[DEBUG] [total/total] Packed 415MB so far...
[DEBUG] [total/total] Packed 417MB so far...
[DEBUG] [total/total] Packed 419MB so far...
[DEBUG] [total/total] done
[DEBUG] [total/dropbox] Copy total_2019_10_07-11_30_16_Full__backupiobroker.tar.gz...
...but there was NO FILE transferred into the dropbox. 

A test with a "normal" backup was successful:
-rw-r--r-- 1 iobroker iobroker   1088035 Okt  7 11:28 minimal_2019_10_07-11_28_10_Standard__backupiobroker.tar.gz
-rw-r--r-- 1 iobroker iobroker      1178 Okt  7 11:28 zigbee.0_2019_10_07-11_28_15_backupiobroker.tar.gz
...and finally transferred to my dropbox. I received also a message from telegram that says, the files are copied correctly. Yes they are!

And what I'm not understand: if the files were successfully transferred to e.g. dropbox - why are they additional located in the local filesystem and waste my space?? I mean, this is why I do an external backup ... 

Regards, machnetz

**Comment by simatec** [comment]
What is your Version of backitup, node, nodejs, nom and js-controller?

**Comment by machnetz** [comment]
Ah, sorry. I forget to post these informations:

> backitup - 1.2.0

> node - v8.15.0
> nodejs 

> npm - 6.11.3

> js-controller

iobroker -version 1.4.2

**Comment by simatec** [comment]
Please make a Update for node and js-controller

**Comment by machnetz** [comment]
The same - the fullbackupfile was created in /opt/iobroker/backups/total_2019_10_07-16_05_15_Full__backupiobroker.tar.gz but not transferred to dropbox. Logfile says:

[DEBUG] [total/total] Packed 416MB so far...
[DEBUG] [total/total] Packed 419MB so far...
[DEBUG] [total/total] done
[DEBUG] [total/dropbox] Copy total_2019_10_07-16_05_15_Full__backupiobroker.tar.gz...

 npm -v
6.9.0
node -v
v10.16.3
iobroker -version
1.5.14

**Comment by machnetz** [comment]
So,
a fullbackup was scheduled for today. The file is created but was not transferred to dropbox. 
A minimal backup was scheduled, created and transferred, I was notified by telegram.

**Comment by simatec** [comment]
I'll build in debug logs so we can test what's going on

**Comment by 30er** [comment]
Hi I face the same issue. Backup files is created but not stored in dropbox

```
npm -v
6.9.0
node -v
v10.16.3
iobroker -version
2.0.29
```

**Comment by machnetz** [comment]
> I'll build in debug logs so we can test what's going on
Hm, sorry - where do i find these logs?

**Comment by simatec** [comment]
Fullbackup is no longer supported
