### ISSUE TITLE
Cannot use special chars in password for ccu backup

### ISSUE THREAD

**Issue by udochrist** [simatec/ioBroker.backitup#179]

**Comment by simatec** [comment]
Please more Info!!!

**Comment by udochrist** [comment]
Hi,
Sorry. I did not yes press save on the issue entry screen. Somehow github must have autosaved the issue while I was away. Funny thing....

so: i have a "$" sign in the password of my admin account (at the end fwiw)

Using an iPad and safari I am not able to enter the "$" sign in the password field at all.
When I do the same on a Mac using safari I can enter the correct password but I get 

```
[ERROR] [ccu] - [IGNORED] invalid credentials or too many sessions
[DEBUG] [clean] start with {"deleteBackupAfter":0}
[DEBUG] [clean] - done
```

in the log creating a backup by hand. When I use a password without $ but i.e. a # the backup succeeds..
I think this are two separate issues
1/ allowed character classes on the web-gui using different os
2/ handling of $ as a char in the pw

cheers
udo

**Comment by udochrist** [comment]
I need to take the second part back. the issue was "Admin" vs. "admin". I was not aware that the ccu cares for upper/lower-case username. the password with $ at the end is handled fine.

I cannot however enter the $ sign using an iPad in the configuration gui of the instance.

**Comment by simatec** [comment]
you have to take the login data from your web interface and enter it at backitup

**Comment by simatec** [comment]
try typing the password with quotes in backitup

**Comment by udochrist** [comment]
working, thanks. seems to have been an issue with the iPad/ios6 keyboard.
