### ISSUE TITLE
Iobroker friert ein mit Synology NFS-Verbindung

### ISSUE THREAD

**Issue by meia24** [simatec/ioBroker.backitup#181]
Hallo,
Ich versuche seit Stunden, backitup mit einer Synology als NAS zu konfigurieren und zum Laufen zu bringen. Leider friert iobroker jedesmal komplett ein und muss vom Strom getrennt werden.
Vielleicht kann mir jemand helfen:

* Ich teste mit backitup standard-backup, alles andere zunächst deaktiviert.
* NAS/copy deaktiviert: es wird ein minimal-backup im `/opt/iobroker/backups` angelegt, backup läuft durch
* NAS/Copy aktiviert mit: NFS, lokale IP der Synology `192.168.1.xy`, `Mount als root` aktiviert, Pfad `/volume1/backup_pi` (`backup_pi` als gemeinsamen Ordner auf der Synology angelegt mit NFS-Rechten). > beim Start des standard-backup zeigt der debugger, das gemounted wird. Dann friert irgendwann der Browser ein. Auch per Putty oder WinSCP kommt man dann nicht mehr auf den Raspi. Man muss den Strom trennen.

Ich habe andererseits in putty einmal das mounten und kopieren getestet, dies war erfolgreich:
* iobroker backup
* sudo mount 192.168.1.xy:/volume1/backup_pi /mnt
* cd /opt/iobroker/backups
* sudo cp $(ls -1t | head -1) /mnt

Ergebnis: Datei auf Synology kopiert. Es kann also nicht an komplett falscher Konfiguration der Synology liegen.

Jemand einen Tipp
Danke, Meia

**Comment by simatec** [comment]
Zeige bitte mal deine Config von backitup
