### ISSUE TITLE
mysqldump.tar.gz filename problem

### ISSUE THREAD

**Issue by 30er** [simatec/ioBroker.backitup#183]
The file inside the mysql.tar.gz has a filename of "."
it cant be extracted on windows

iobroker runs on rpi4 4GB

```
npm       6.9.0
node      10.16.3
iobroker  2.0.29
mysqldump 10.15 Distrib 10.0.28-MariaDB
```

```
adapters (LATEST)
admin    3.6.0
BackItUp 1.2.2
```

Standard backup log:
https://www.codepile.net/pile/Xo3VleLg

**Comment by simatec** [comment]
This Format is ok for a restore with backitup
