### ISSUE TITLE
CIFS password with special characters // SMB version

### ISSUE THREAD

**Issue by p0rys** [simatec/ioBroker.backitup#184]
Hello, 

since I updated to version 1.2.1 and/or 1.2.2 the controller is not able to mount my NAS folder anymore. I figuered out that the new special character handling is not working for me. Before the update, I manually added a single quotes to my password to escape it ( ' ), which was working fine. Since 1.2.1 it is automatically escaped by double quotes ( " ) which is not working (yes, i removed my "old" single quotes...). Is it maybe possible to use single instead of double quotes for password escaping?

Thank you and greetings,
p0rys

**Comment by simatec** [comment]
fix is finish
