### ISSUE TITLE
If you need my support please open an issue here and I will help.

### ISSUE THREAD

**Issue by GermanBluefox** [simatec/ioBroker.backitup#19]
With following text @germanbluefox.
Ok @simatec ?
I cannot communicate good via forum :)
Du kannst auch auf Deutsch schreiben.

**Comment by simatec** [comment]
@GermanBluefox 
Danke für den Hinweis.
Werden wir zukünftig machen

Aktuell gibt es ein problem mit dem aktualisieren der Backupzeit für den Dateinamen.
Die Zeit wird nicht rechtzeitig aktualisiert, so dass die Angaben im Dateinamen nicht korrekt sind.
Die Zeit wird in der main.js (ab Zeile 454) definiert.
Branch: Multiplatform
