### ISSUE TITLE
Fullbackup support ends?

### ISSUE THREAD

**Issue by fraeggle** [simatec/ioBroker.backitup#197]
Habe mit Verwunderung gesehen, dass in der neuen Version Fullbackup nicht mehr integriert ist.
Gab es einen bestimmten Grund dafür?
Ich habe seither nur Fullbackup verwendet, da auf diese Art eigentlich eine Wiederherstellung schneller und einfacher war. Das System lief mit allen Adaptern und hinterlegten Bildern, etc....

Schade. 
Gruß Peter

**Comment by fraeggle** [comment]
Muss in den Objekten auch noch etwas gelöscht/angepasst werden?
![grafik](https://user-images.githubusercontent.com/40692505/69747415-a2817f00-1146-11ea-8dea-395dc3df48ee.png)

**Comment by simatec** [comment]
Die Objekte können einfach gelöscht werden
