### ISSUE TITLE
total backup verschwunden

### ISSUE THREAD

**Issue by ltsalvatore** [simatec/ioBroker.backitup#199]
hallo zusammen.. 
ich habe vorhin die neuste version 1.3.0 (22.11.2019) installiert und direkt getestet, ob diese auch sauber die backups erstellt.
dabei ist mir aufgefallen, dass der reiter "total backup" fehlt..

**Comment by simatec** [comment]
Bitte readme und changelog lesen

**Comment by jnsw** [comment]
hab gelesen, dass der support geendet ist, finde aber nichts dazu, **warum** dies geschehen ist. gab es zu viele probleme? ist downgraden theoretisch möglich? oder gibt es bereits alternativen?

**Comment by simatec** [comment]
Ja das ganz normale iobroker Backup reicht, um alles wiederherzustellen.

**Comment by dbarchmann** [comment]
Ich habe noch ein "TotalBackup", welches ich mit der aktuellen version einspielen wollte. Leider erkennt die aktuelle Version das Backup File nicht. Gibt es eine Möglichkeit das alte Backup irgendwie einzuspielen?

**Comment by simatec** [comment]
Du kannst es mit den bekannten Linux Befehlen direkt in das Verzeichnis iobroker entpacken
