### ISSUE TITLE
Bug Redis & FTP

### ISSUE THREAD

**Issue by simatec** [simatec/ioBroker.backitup#21]
@GermanBluefox 

Nach deinem Pull Request haben wir einen Bug beim Redis Backup, den ich nicht definieren kann.

ost.ioBroker-RasPi | 2018-08-05 21:21:23.414 | error | instance system.adapter.backitup.1 terminated with code 0 (OK)
-- | -- | -- | --
host.ioBroker-RasPi | 2018-08-05 21:21:23.414 | error | Caught by controller[0]: at processImmediate [as _immediateCallback] (timers.js:745:5)
host.ioBroker-RasPi | 2018-08-05 21:21:23.414 | error | Caught by controller[0]: at tryOnImmediate (timers.js:768:5)
host.ioBroker-RasPi | 2018-08-05 21:21:23.414 | error | Caught by controller[0]: at runCallback (timers.js:819:39)
host.ioBroker-RasPi | 2018-08-05 21:21:23.413 | error | Caught by controller[0]: at Immediate.executeScripts [as _onImmediate] (/opt/iobroker/node_modules/iobroker.backitup/main.js:694:22)
host.ioBroker-RasPi | 2018-08-05 21:21:23.413 | error | Caught by controller[0]: at Object.command (/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/30-redis.js:36:49)
host.ioBroker-RasPi | 2018-08-05 21:21:23.413 | error | Caught by controller[0]: TypeError: Cannot read property 'fileNames' of undefined
backitup.1 | 2018-08-05 21:21:22.876 | error | TypeError: Cannot read property 'fileNames' of undefined at Object.command (/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/30-redis.js:36:49) at Immediate.executeScripts [as _onImmed
backitup.1 | 2018-08-05 21:21:22.875 | error | uncaught exception: Cannot read property 'fileNames' of undefined

Der FTP Upload ist seit dem Pull Request ohne Funktion.
Auch hier kann ich den Fehler leider nicht finden

**Comment by GermanBluefox** [comment]
Please see: https://github.com/simatec/ioBroker.backitup/pull/22

**Comment by simatec** [comment]
@GermanBlufox

Thanx for your Fix ...
