### ISSUE TITLE
history Eintrag ist immer mit Bestätigt=false

### ISSUE THREAD

**Issue by Hirsch-DE** [simatec/ioBroker.backitup#213]
Hallo,
in der admin-Webseite werden die Werte bei History immer rot Dargestellt, da dere Wert "Bestätigt" false ist.
Könnte man nicht bei erfolgreichem Backup die Werte beim setzen nicht mit Bestätigt = true setzen? Ist Optisch auf jedenfall besser.

MfG
Thomas Hirschfeld

**Comment by simatec** [comment]
Ab Version 1.3.6 vorhanden ...
