### ISSUE TITLE
Voreinsteinstellung History-Daten-Backup

### ISSUE THREAD

**Issue by Hirsch-DE** [simatec/ioBroker.backitup#214]
Hallo,
mir ist aufgefallen, dass die Voreinstellung nicht "/opt/iobroker/iobroker-data/history" lautet, was aber sicher der richtige Pfad bei den meisten sein sollte!

MfG
Thomas Hirschfeld

**Comment by simatec** [comment]
Ab Version 1.3.3 enthalten
