### ISSUE TITLE
Restore von Google Drive funktioniert nicht

### ISSUE THREAD

**Issue by Gizimo** [simatec/ioBroker.backitup#220]
Hi,
nachdem ja das Backup nach Google Drive funktioniert wollte ich mal schauen wie man das wieder zurück sichert. Wenn ich hier aber auf wiederherstellen gehe dann sehe ich die Backups nicht.
Ich hab extra Google Drive ausgewählt.
Er Zeigt mir aber nur einen Order an der Leer ist.

Gruß

**Comment by simatec** [comment]
Wenn du als Backup Quelle Google drive gewählt hast, erst speichern, dann abrufen

**Comment by Gizimo** [comment]
Hab ich gemacht, ich sehe dann einen Order der heisst "googledrive" dort klick  ich drauf, ist aber leer...

**Comment by simatec** [comment]
Schalte die Adapter-Instanz mal auf debug und poste hier bitte dem Log bei Abruf der Google Drive Daten

**Comment by Gizimo** [comment]
Also irgendwie spruckt der bei mir nichts aus.... so sieht zumindest das Restor Fenster aus:
![image](https://user-images.githubusercontent.com/49814433/71207859-14616a00-22a8-11ea-997e-a85152f91109.png)

**Comment by simatec** [comment]
Hast du nach Auswahl der Backup Quelle gespeichert?

**Comment by Gizimo** [comment]
Jup. wie man sieht spuckt der nicht viel aus:

`

backitup.0 | 2019-12-19 21:54:58.762 | debug | (5648) [ccu] 10 30 01 */3 * *
-- | -- | -- | --
backitup.0 | 2019-12-19 21:54:58.760 | info | (5648) [ccu] backup was activated at 01:30 every 3 day(s)
backitup.0 | 2019-12-19 21:54:58.760 | debug | (5648) [iobroker] 10 00 02 */1 * *
backitup.0 | 2019-12-19 21:54:58.754 | info | (5648) [iobroker] backup was activated at 02:00 every 1 day(s)
backitup.0 | 2019-12-19 21:54:58.740 | info | (5648) starting. Version 1.3.6 in C:/Program Files/iobroker/SmartHome/node_modules/iobroker.backitup, node: v10.17.0
backitup.0 | 2019-12-19 21:54:58.711 | debug | (5648) States connected to redis: 127.0.0.1:9000
backitup.0 | 2019-12-19 21:54:58.705 | debug | (5648) statesDB connected
backitup.0 | 2019-12-19 21:54:58.704 | debug | (5648) States create PubSub Client
backitup.0 | 2019-12-19 21:54:58.703 | debug | (5648) Objects connected to redis: 127.0.0.1:9001
backitup.0 | 2019-12-19 21:54:58.702 | debug | (5648) Redis States: Use Redis connection: 127.0.0.1:9000
backitup.0 | 2019-12-19 21:54:58.701 | debug | (5648) objectDB connected
backitup.0 | 2019-12-19 21:54:58.697 | debug | (5648) Objects client initialize lua scripts
backitup.0 | 2019-12-19 21:54:58.696 | debug | (5648) Objects create PubSub Client
backitup.0 | 2019-12-19 21:54:58.695 | debug | (5648) Objects client ready ... initialize now
backitup.0 | 2019-12-19 21:54:58.683 | debug | (5648) Redis Objects: Use Redis connection: 127.0.0.1:9001

`

**Comment by simatec** [comment]
Das nur der Log von speichern mit Neustart des Adapters. Nicht aber vom abrufen der Google Drive Dateien

**Comment by Gizimo** [comment]
Wie komm ich an das Log drann? ich hab den Adapter schon auf Debug gestellt.... mehr spruckt der aber nicht aus

**Comment by simatec** [comment]
Unter Instanzen den Adapter von Info auf debug schalten

**Comment by Gizimo** [comment]
hab ich gemacht, da hatte ich dir oben das Ergebnis geschickt. Ich sag ja, da kommt nichts an Infos...

**Comment by simatec** [comment]
Zeige mal den Inhalt deiner Google Drive Sicherungen
