### ISSUE TITLE
Restore bei Verwendung als Addon in der Rasberrymatic

### ISSUE THREAD

**Issue by fraeggle** [simatec/ioBroker.backitup#222]
Hi
Ich teste gerade die Raspberrymatic mit dem IOBroker Addon.
Ich versuche gerade verzweifelt über einen Restore den IOBroker auf der Raspberrymatic wieder herzustellen.
Ich kann das Restore aufrufen, es startet auch, aber wenn sich die Seite http://192.XXX.XXX.XXX:8091/backitup-restore öffnet, kommt zum einen "kann keine Verbindung zu..... aufbauen" und die Restore anzeige bleibt so stehen:
![grafik](https://user-images.githubusercontent.com/40692505/70846907-89731080-1e5e-11ea-8601-0570bf0603c4.png)
Irgendwann verschwindet noch das kleine Popup rechts....  aber es wird kein Restore gemacht.
Firewall in der HM sind deaktiviert.
Backup selber funktioniert.
hab auch schon zum testen die Partition als RW eingehängt.

Gruß Peter

**Comment by simatec** [comment]
Was passiert im Log? Wird iobroker beendet?
Hast du mal den Installerfix drüberlaufen lassen?
Im Forum habe ich eine Anleitung geschrieben, wie man einen Restore richtig ausführt.

**Comment by fraeggle** [comment]
Hab gerade gelesen, dass dies wohl nicht beim HM-Addon nicht funktionieren soll.
Fürs Log müsste ich dann nochmal versuchen. Bin diese Woche nur viel unterwegs.
Also fix hab ich installiert. 
Nein , so wie es aussieht wird iobroker gar nicht beendet.
Hier  https://homematic-forum.de/forum/viewtopic.php?f=65&t=36434&hilit=backitup&start=20 wird beschrieben, wie man das Backup dann einspielen kann. Funktioniert auch nach der Anleitung von zautrix.
Aber danke für deine schnelle Antwort.
