### ISSUE TITLE
Bei Output_Line [DEBUG] ist das Ergebnis vom Backup immer false

### ISSUE THREAD

**Issue by Hirsch-DE** [simatec/ioBroker.backitup#224]
Obwohl das Backup der CCU erfolgreich war und es bei output.line mit `[DEBUG]` beginnt, ist das Ergebnis backitup.0.history.ccuSuccess immer false.

MfG
Thomas Hirschfeld

**Comment by Coffee-lover** [comment]
Ich habe genau das gleiche Phänomen mit dem iobroker Backup. (backitup.0.history.iobrokerSuccess)
Entsprechend ist auch der Datenpunkt backitup.0.history.iobrokerLastTime immer "error: 05. Januar 2020 um 02:15 Uhr"

VG

**Comment by simatec** [comment]
Stell mal die Instanz bitte auf debug und poste mal den Debug-Log vom Backup Vorgang.

**Comment by Coffee-lover** [comment]
![image](https://user-images.githubusercontent.com/34901346/71779070-d5742980-2fb4-11ea-90bd-e63fc690175b.png)
Du meinst diesen Hacken, oder?
Das ist merkwürdig: Obwohl ich das Backup händisch gestartet habe, taucht im LOG auf Debug-Level nichts im Backitup Adapter auf.

**Comment by simatec** [comment]
Nein unter den Instanzen den Adapter von Info auf debug stellen. 
Eventuell vorher in den Instanzen noch die Experten Einstellungen aktivieren, damit du die Spalte Log siehst

**Comment by Coffee-lover** [comment]
Got it.

`
backitup.0 | 2020-01-05 12:25:01.006 | debug | (3136) [iobroker] exec: done
-- | -- | -- | --
backitup.0 | 2020-01-05 12:25:01.004 | debug | (3136) [iobroker/history] backitup.0.history.html
backitup.0 | 2020-01-05 12:25:00.872 | debug | (3136) [iobroker/telegram] done
backitup.0 | 2020-01-05 12:25:00.865 | debug | (3136) sendTo "send" to system.adapter.telegram.0 from system.adapter.backitup.0
backitup.0 | 2020-01-05 12:25:00.857 | debug | (3136) [iobroker/telegram] [iobroker] used Telegram-Instance: telegram.0
backitup.0 | 2020-01-05 12:25:00.836 | debug | (3136) [iobroker/clean] done
backitup.0 | 2020-01-05 12:25:00.814 | debug | (3136) [iobroker/ftp] done
backitup.0 | 2020-01-05 12:25:00.450 | debug | (3136) [iobroker/ftp] Send iobroker_2020_01_05-12_24_49_iobrokerRevival_backupiobroker.tar.gz
backitup.0 | 2020-01-05 12:25:00.443 | debug | (3136) [iobroker/ftp] FTP connected.
backitup.0 | 2020-01-05 12:25:00.329 | debug | (3136) [iobroker/iobroker] done
backitup.0 | 2020-01-05 12:24:59.249 | debug | (3136)  [iobroker/iobroker] Backup created:  /opt/iobroker/backups/iobroker_2020_01_05-12_24_49_iobrokerRevival_backupiobroker.tar.gz
backitup.0 | 2020-01-05 12:24:53.792 | debug | (3136) [iobroker/iobroker] host.iobrokerGen2Revival 8782 objects saved
backitup.0 | 2020-01-05 12:24:53.752 | debug | (3136) [iobroker/iobroker] host.iobrokerGen2Revival 7600 states saved
backitup.0 | 2020-01-05 12:24:47.525 | debug | (3136) sendTo "getTelegramUser" to system.adapter.admin.0 from system.adapter.backitup.0: {"263799182":"Raimund"}
backitup.0 | 2020-01-05 12:24:45.598 | debug | (3136) FTP connected.
backitup.0 | 2020-01-05 12:24:45.368 | debug | (3136) [iobroker] 10 15 02 */1 * *
backitup.0 | 2020-01-05 12:24:45.345 | info | (3136) [iobroker] backup was activated at 02:15 every 1 day(s)
backitup.0 | 2020-01-05 12:24:45.268 | info | (3136) starting. Version 1.3.6 in /opt/iobroker/node_modules/iobroker.backitup, node: v10.17.0
backitup.0 | 2020-01-05 12:24:43.994 | debug | (3136) States connected to redis: 127.0.0.1:9000
backitup.0 | 2020-01-05 12:24:43.939 | debug | (3136) statesDB connected
backitup.0 | 2020-01-05 12:24:43.938 | debug | (3136) States create PubSub Client
backitup.0 | 2020-01-05 12:24:43.922 | debug | (3136) Objects connected to redis: 127.0.0.1:9001
backitup.0 | 2020-01-05 12:24:43.918 | debug | (3136) Redis States: Use Redis connection: 127.0.0.1:9000
backitup.0 | 2020-01-05 12:24:43.916 | debug | (3136) objectDB connected
backitup.0 | 2020-01-05 12:24:43.891 | debug | (3136) Objects client initialize lua scripts
backitup.0 | 2020-01-05 12:24:43.890 | debug | (3136) Objects create PubSub Client
backitup.0 | 2020-01-05 12:24:43.885 | debug | (3136) Objects client ready ... initialize now
backitup.0 | 2020-01-05 12:24:43.767 | debug | (3136) Redis Objects: Use Redis connection: 127.0.0.1:9001
backitup.0 | 2020-01-05 12:24:36.323 | info | (3085) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
backitup.0 | 2020-01-05 12:24:36.322 | info | (3085) terminating
backitup.0 | 2020-01-05 12:24:35.819 | info | (3085) Got terminate signal TERMINATE_YOURSELF
`

**Comment by hannibal72** [comment]
Hallo,
ich habe dasselbe Phänomen wie Coffee-lover mit dem iobroker Backup. Hier mein LOG:

`Gestartet...
[DEBUG] [iobroker] start with {"type":"creator","time":"06:00","debugging":true,"everyXDays":"1","nameSuffix":"BackitUp_Backup","deleteBackupAfter":0,"ftp":{"enabled":true,"type":"storage","source":null,"
host":"IP-Adresse-meines-NAS","debugging":true,"deleteOldBackup":false,"ownDir":true,"bkpType":"Minimal","dir":"ioBrokerBackups/StandardBU","dirMinimal":"ioBrokerBackups/StandardBU","user":"USERNAME","pass":"****","port":"XY"},
"dir":"/opt/iobroker","redis":{"enabled":false,"type":"creator","ftp":{"enabled":true,"type":"storage","source":null,"host":"IP-Adresse-meines-NAS","debugging":true,"deleteOldBackup":false,"ownDir":true,
"bkpType":"Minimal","dir":"ioBrokerBackups/StandardBU","dirMinimal":"ioBrokerBackups/StandardBU","user":"USERNAME","pass":"****","port":"XY"},"cifs":{"enabled":false,"mountType":"NFS","type":"storage",
"source":null,"mount":"IP-Adresse-meines-NAS","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"XYZ","wolTime":"25","smb":"vers=1.0",
"sudo":false,"deleteOldBackup":false,"ownDir":false,"bkpType":"Minimal","dir":"/volume1/ioBrokerBackups","dirMinimal":"volume1/USERNAME/ioBrokerBackups","user":"USERNAME","pass":"****"},
"dropbox":{"enabled":false,"type":"storage","source":null,"debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},
"googledrive":{"enabled":false,"type":"storage","source":null,"debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},
"path":"/var/lib/redis/dump.rdb"},"historyDB":{"enabled":false,"type":"creator","ftp":{"enabled":true,"type":"storage","source":null,"host":"IP-Adresse-meines-NAS","debugging":true,"deleteOldBackup":false,
"ownDir":true,"bkpType":"Minimal","dir":"ioBrokerBackups/StandardBU","dirMinimal":"ioBrokerBackups/StandardBU","user":"USERNAME","pass":"****","port":"XY"},"cifs":{"enabled":false,"mountType":"NFS",
"type":"storage","source":null,"mount":"IP-Adresse-meines-NAS","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"XYZ","wolTime":"25",
"smb":"vers=1.0","sudo":false,"deleteOldBackup":false,"ownDir":false,"bkpType":"Minimal","dir":"/volume1/ioBrokerBackups","dirMinimal":"volume1/USERNAME/ioBrokerBackups","user":"USERNAME","pass":"****"},
"dropbox":{"enabled":false,"type":"storage","source":null,"debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},
"googledrive":{"enabled":false,"type":"storage","source":null,"debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},
"path":"media/usb/history"},"zigbee":{"enabled":false,"type":"creator","ftp":{"enabled":true,"type":"storage","source":null,"host":"IP-Adresse-meines-NAS","debugging":true,"deleteOldBackup":false,"ownDir":true,
"bkpType":"Minimal","dir":"ioBrokerBackups/StandardBU","dirMinimal":"ioBrokerBackups/StandardBU","user":"USERNAME","pass":"****","port":"XY"},"cifs":{"enabled":false,"mountType":"NFS","type":"storage",
"source":null,"mount":"IP-Adresse-meines-NAS","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"XYZ","wolTime":"25","smb":"vers=1.0","sudo":false,
"deleteOldBackup":false,"ownDir":false,"bkpType":"Minimal","dir":"/volume1/ioBrokerBackups","dirMinimal":"volume1/USERNAME/ioBrokerBackups","user":"USERNAME","pass":"****"},
"dropbox":{"enabled":false,"type":"storage","source":null,"debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},
"googledrive":{"enabled":false,"type":"storage","source":null,"debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir",
"dirMinimal":"/backupDir/minimal"},"path":"/opt/iobroker/iobroker-data"},"history":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de"},
"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"MeinName","onlyError":false,
"telegramWaiting":0,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"email.0","NoticeType":"longEmailNotice","emailReceiver":"Email@Adresse.ABC",
"emailSender":"Email@Adresse.ABC","onlyError":false,"emailWaiting":0,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"pushover.0",
"SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":true,"pushoverWaiting":0,"systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2020_01_08-14_13_36_BackitUp_Backup_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [ftp] start with {"type":"storage","source":null,"host":"IP-Adresse-meines-NAS","debugging":true,"deleteOldBackup":false,"ownDir":true,"bkpType":"Minimal","dir":"ioBrokerBackups/StandardBU",
"dirMinimal":"ioBrokerBackups/StandardBU","user":"USERNAME","pass":"****","port":"XY","deleteBackupAfter":0}
[DEBUG] [ftp] - FTP connected.
[DEBUG] [ftp] - Send iobroker_2020_01_08-14_13_36_BackitUp_Backup_backupiobroker.tar.gz
[DEBUG] [ftp] - done
[DEBUG] [clean] - done
[DEBUG] [telegram] - [iobroker] used Telegram-Instance: telegram.0
[DEBUG] [telegram] - done
[DEBUG] [history] - backitup.0.history.html
[EXIT] 0
[DEBUG] [telegram] start with {"type":"creator","time":"06:00","debugging":true,"everyXDays":"1","nameSuffix":"BackitUp_Backup","deleteBackupAfter":0,"ftp":{"enabled":true,
"type":"storage","source":null,"host":"IP-Adresse-meines-NAS","debugging":true,"deleteOldBackup":false,"ownDir":true,"bkpType":"Minimal","dir":"ioBrokerBackups/StandardBU",
"dirMinimal":"ioBrokerBackups/StandardBU","user":"USERNAME","pass":"****","port":"XY"},"dir":"/opt/iobroker","redis":{"enabled":false,"type":"creator","ftp":{"enabled":true,"type":"storage",
"source":null,"host":"IP-Adresse-meines-NAS","debugging":true,"deleteOldBackup":false,"ownDir":true,"bkpType":"Minimal","dir":"ioBrokerBackups/StandardBU","dirMinimal":"ioBrokerBackups/StandardBU",
"user":"USERNAME","pass":"****","port":"XY"},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":null,"mount":"IP-Adresse-meines-NAS","debugging":true,
"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"XYZ","wolTime":"25","smb":"vers=1.0","sudo":false,"deleteOldBackup":false,"ownDir":false,
"bkpType":"Minimal","dir":"/volume1/ioBrokerBackups","dirMinimal":"volume1/USERNAME/ioBrokerBackups","user":"USERNAME","pass":"****"},"dropbox":{"enabled":false,"type":"storage",
"source":null,"debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},"googledrive":{"enabled":false,"type":"storage",
"source":null,"debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},"path":"/var/lib/redis/dump.rdb"},
"historyDB":{"enabled":false,"type":"creator","ftp":{"enabled":true,"type":"storage","source":null,"host":"IP-Adresse-meines-NAS","debugging":true,"deleteOldBackup":false,"ownDir":true,"bkpType":"Minimal",
"dir":"ioBrokerBackups/StandardBU","dirMinimal":"ioBrokerBackups/StandardBU","user":"USERNAME","pass":"****","port":"XY"},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":null,
"mount":"IP-Adresse-meines-NAS","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"XYZ","wolTime":"25","smb":"vers=1.0","sudo":false,"deleteOldBackup":false,
"ownDir":false,"bkpType":"Minimal","dir":"/volume1/ioBrokerBackups","dirMinimal":"volume1/USERNAME/ioBrokerBackups","user":"USERNAME","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":null,"debugging":true,
"deleteOldBackup":false,"accessToken":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},"googledrive":{"enabled":false,"type":"storage","source":null,"debugging":true,
"deleteOldBackup":false,"accessJson":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},"path":"media/usb/history"},"zigbee":{"enabled":false,"type":"creator",
"ftp":{"enabled":true,"type":"storage","source":null,"host":"IP-Adresse-meines-NAS","debugging":true,"deleteOldBackup":false,"ownDir":true,"bkpType":"Minimal","dir":"ioBrokerBackups/StandardBU",
"dirMinimal":"ioBrokerBackups/StandardBU","user":"USERNAME","pass":"****","port":"XY"},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":null,"mount":"IP-Adresse-meines-NAS","debugging":true,
"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"XYZ","wolTime":"25","smb":"vers=1.0","sudo":false,"deleteOldBackup":false,"ownDir":false,"bkpType":"Minimal","dir":"/volume1/ioBrokerBackups",
"dirMinimal":"volume1/USERNAME/ioBrokerBackups","user":"USERNAME","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":null,"debugging":true,"deleteOldBackup":false,"accessToken":"****",
"ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},"googledrive":{"enabled":false,"type":"storage","source":null,"debugging":true,"deleteOldBackup":false,"accessJson":"****",
"ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},"path":"/opt/iobroker/iobroker-data"},"history":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de"},
"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"MeinName","onlyError":false,"telegramWaiting":0,
"systemLang":"de","time":"08. Januar 2020 um 14:13 Uhr"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"email.0","NoticeType":"longEmailNotice","emailReceiver":"Email@Adresse.ABC",
"emailSender":"Email@Adresse.ABC","onlyError":false,"emailWaiting":0,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"pushover.0","SilentNotice":false,
"NoticeType":"longPushoverNotice","deviceID":"","onlyError":true,"pushoverWaiting":0,"systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [history] start with {"type":"creator","time":"06:00","debugging":true,"everyXDays":"1","nameSuffix":"BackitUp_Backup","deleteBackupAfter":0,"ftp":{"enabled":true,"type":"storage","source":null,
"host":"IP-Adresse-meines-NAS","debugging":true,"deleteOldBackup":false,"ownDir":true,"bkpType":"Minimal","dir":"ioBrokerBackups/StandardBU","dirMinimal":"ioBrokerBackups/StandardBU","user":"USERNAME","pass":"****",
"port":"XY"},"dir":"/opt/iobroker","redis":{"enabled":false,"type":"creator","ftp":{"enabled":true,"type":"storage","source":null,"host":"IP-Adresse-meines-NAS","debugging":true,"deleteOldBackup":false,
"ownDir":true,"bkpType":"Minimal","dir":"ioBrokerBackups/StandardBU","dirMinimal":"ioBrokerBackups/StandardBU","user":"USERNAME","pass":"****","port":"XY"},"cifs":{"enabled":false,"mountType":"NFS","type":"storage",
"source":null,"mount":"IP-Adresse-meines-NAS","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"XYZ","wolTime":"25","smb":"vers=1.0","sudo":false,"deleteOldBackup":false,
"ownDir":false,"bkpType":"Minimal","dir":"/volume1/ioBrokerBackups","dirMinimal":"volume1/USERNAME/ioBrokerBackups","user":"USERNAME","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":null,
"debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},"googledrive":{"enabled":false,"type":"storage","source":null,
"debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},"path":"/var/lib/redis/dump.rdb"},"historyDB":{"enabled":false,
"type":"creator","ftp":{"enabled":true,"type":"storage","source":null,"host":"IP-Adresse-meines-NAS","debugging":true,"deleteOldBackup":false,"ownDir":true,"bkpType":"Minimal","dir":"ioBrokerBackups/StandardBU",
"dirMinimal":"ioBrokerBackups/StandardBU","user":"USERNAME","pass":"****","port":"XY"},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":null,"mount":"IP-Adresse-meines-NAS","debugging":true,
"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"XYZ","wolTime":"25","smb":"vers=1.0","sudo":false,"deleteOldBackup":false,"ownDir":false,"bkpType":"Minimal","dir":"/volume1/ioBrokerBackups",
"dirMinimal":"volume1/USERNAME/ioBrokerBackups","user":"USERNAME","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":null,"debugging":true,"deleteOldBackup":false,"accessToken":"****",
"ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},"googledrive":{"enabled":false,"type":"storage","source":null,"debugging":true,"deleteOldBackup":false,"accessJson":"****",
"ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},"path":"media/usb/history"},"zigbee":{"enabled":false,"type":"creator","ftp":{"enabled":true,"type":"storage",
"source":null,"host":"IP-Adresse-meines-NAS","debugging":true,"deleteOldBackup":false,"ownDir":true,"bkpType":"Minimal","dir":"ioBrokerBackups/StandardBU","dirMinimal":"ioBrokerBackups/StandardBU",
"user":"USERNAME","pass":"****","port":"XY"},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":null,"mount":"IP-Adresse-meines-NAS","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup",
"wakeOnLAN":false,"macAd":"XYZ","wolTime":"25","smb":"vers=1.0","sudo":false,"deleteOldBackup":false,"ownDir":false,"bkpType":"Minimal","dir":"/volume1/ioBrokerBackups","dirMinimal":"volume1/USERNAME/ioBrokerBackups",
"user":"USERNAME","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":null,"debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir",
"dirMinimal":"/backupDir/minimal"},"googledrive":{"enabled":false,"type":"storage","source":null,"debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir",
"dirMinimal":"/backupDir/minimal"},"path":"/opt/iobroker/iobroker-data"},"history":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de","time":"08. Januar 2020 um 14:13 Uhr"},
"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"MeinName","onlyError":false,
"telegramWaiting":0,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"email.0","NoticeType":"longEmailNotice","emailReceiver":"Email@Adresse.ABC",
"emailSender":"Email@Adresse.ABC","onlyError":false,"emailWaiting":0,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"pushover.0","SilentNotice":false,
"NoticeType":"longPushoverNotice","deviceID":"","onlyError":true,"pushoverWaiting":0,"systemLang":"de"},"backupDir":"/opt/iobroker/backups"}`
