### ISSUE TITLE
Neustart nach Update mit DropBox Fehlermeldungen im Log

### ISSUE THREAD

**Issue by ToTXR4Y** [simatec/ioBroker.backitup#227]
Folgende Fehlermeldungen kommen immer nach einem Update des Adapters.
DropBox kommt bei mir nicht zum Einsatz, daher gehe ich davon aus das ein entsprechender Eintrag nicht automatisiert auf einen definierten Wert gesetzt wird.

backitup.0 | 2019-12-17 09:00:15.146 | error | at processImmediate (timers.js:658:5)
-- | -- | -- | --
backitup.0 | 2019-12-17 09:00:15.146 | error | at tryOnImmediate (timers.js:676:5)
backitup.0 | 2019-12-17 09:00:15.146 | error | at runCallback (timers.js:706:11)
backitup.0 | 2019-12-17 09:00:15.146 | error | at Immediate.executeScripts (/opt/iobroker/node_modules/iobroker.backitup/lib/execute.js:176:37)
backitup.0 | 2019-12-17 09:00:15.146 | error | (32457) TypeError: Cannot read property 'dropbox' of null
backitup.0 | 2019-12-17 09:00:15.144 | error | (32457) uncaught exception: Cannot read property 'dropbox' of null

**Comment by simatec** [comment]
Das war ein Bug in Version 1.3.3. Bitte auf 1.3.4 updaten.
