### ISSUE TITLE
Backup hangs starting with 1.3.3

### ISSUE THREAD

**Issue by peer69** [simatec/ioBroker.backitup#228]
After Updating to 1.3.3 / 1.3.4 backups stop / hang right after showing this log entry: 

`[DEBUG] [iobroker] - done
[DEBUG] [mysql] - done
[DEBUG] [mysql] - MySql File deleted!
[DEBUG] [redis] - Packed 20MB so far...`

Version 1.3.2 works fine.

**Comment by simatec** [comment]
Please let the installer fix run

`curl -sL https://iobroker.net/fix.sh | bash -`

**Comment by peer69** [comment]
Did not work for me. Backup works if I disable redis backup. 
Iobroker user has group access to redis db in /var/lib/redis.

**Comment by simatec** [comment]
There were no changes in the versions for the redis backup

Change in backitup  the redis-path to "/var/lib/redis/dump.rdb"

```
sudo usermod -a -G redis iobroker
curl -sL https://iobroker.net/fix.sh | bash -
sudo reboot
```

**Comment by peer69** [comment]
Redis path was set to /var/lib/redis, not to /var/lib/redis/dump.rdb. Now that its set to the file instead of the directory backup seems to be working again with 1.3.4. Thank you!
