### ISSUE TITLE
Compact mode is not working in Version 1.3.6

### ISSUE THREAD

**Issue by Marty56** [simatec/ioBroker.backitup#231]
When activating compact mode I receive the following error log:

2019-12-22 08:59:24.838	info	(9691) [iobroker] backup was activated at 02:00 every 7 day(s)
backitup.0	2019-12-22 08:59:24.669	info	(9691) starting. Version 1.3.6 in /opt/iobroker/node_modules/iobroker.backitup, node: v10.17.0
javascript.0	2019-12-22 08:59:13.059	info	(817) script.js.test.Test2: Error log dection:undefined
javascript.0	2019-12-22 08:59:13.057	info	(817) script.js.test.Test2: Error log dection:host.ioBroker-RasPi4.compactgroup1 Cannot start backitup.0 in compact mode. Fallback to normal start! : ENOENT: no such file or directory, open '/opt/iob
host.ioBroker-RasPi4.compactgroup1	2019-12-22 08:59:13.045	info	instance system.adapter.backitup.0 started with pid 9691
2019-12-22 08:59:13.013	error	ndefined
host.ioBroker-RasPi4.compactgroup1	2019-12-22 08:59:13.012	error	Cannot start backitup.0 in compact mode. Fallback to normal start! : ENOENT: no such file or directory, open '/opt/iobroker/node_modules/google-auth-library/node_modules/lru-cache/index.js'
host.ioBroker-RasPi4	2019-12-22 08:59:12.978	info	instance system.adapter.backitup.0 is handled by compact group controller pid 762
host.ioBroker-RasPi4	2019-12-22 08:59:12.964	info	"system.adapter.backitup.0" enabled

**Comment by simatec** [comment]
Please use the Installer Fix

**Comment by Marty56** [comment]
Thanks!
That resolved the problem
