### ISSUE TITLE
Backup friert bei Sicherung ein wenn Zigbee Database mitgesichert wird

### ISSUE THREAD

**Issue by MC-1984** [simatec/ioBroker.backitup#232]
Hallo,

seit dem Update auf die Version 1.3.6 (von der letzten Version im default repository) friert das Backup ein sobald save zigbee database ausgewählt ist.

`Started...
[DEBUG] [iobroker] - host.raspberrypi4-iobroker 2594 states saved

[DEBUG] [iobroker] - host.raspberrypi4-iobroker 2163 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2019_12_28-14_31_50_backupiobroker.tar.gz

[DEBUG] [iobroker] - done`

Da ich neu hier bin: Ist deutsch okay, oder sollen Fehler besser auf englisch gemeldet werden? 

Viele Grüße

Markus

**Comment by simatec** [comment]
Deutsch ist völlig in Ordnung. 
Poste mal bitte den kompletten Debug Log.

**Comment by MC-1984** [comment]
Hallo Simatec,

wow, das ging ja mal schnell!

Hier das debug log - es passiert dann einfach über Stunden nichts mehr:

`Started...
[DEBUG] [iobroker] start with {"type":"creator","time":"12:00","debugging":true,"everyXDays":"1","deleteBackupAfter":0,"googledrive":{"enabled":true,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"dir":"/opt/iobroker","redis":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"local","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":"local","mount":"","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":false,"deleteOldBackup":false,"ownDir":false,"dir":"sharename/backupDir","dirMinimal":"sharename/backupDir","user":"","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":true,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"path":"/var/lib/redis"},"historyDB":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"local","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":"local","mount":"","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":false,"deleteOldBackup":false,"ownDir":false,"dir":"sharename/backupDir","dirMinimal":"sharename/backupDir","user":"","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":true,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"path":"media/usb/history"},"zigbee":{"enabled":true,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"local","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":"local","mount":"","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":false,"deleteOldBackup":false,"ownDir":false,"dir":"sharename/backupDir","dirMinimal":"sharename/backupDir","user":"","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":true,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"path":"/opt/iobroker/iobroker-data"},"history":{"enabled":true,"type":"message","entriesNumber":"40","systemLang":"en"},"telegram":{"enabled":true,"notificationsType":"Pushover","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":null,"onlyError":false,"telegramWaiting":0,"systemLang":"en"},"email":{"enabled":true,"notificationsType":"Pushover","type":"message","instance":"email.0","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"systemLang":"en"},"pushover":{"enabled":true,"notificationsType":"Pushover","type":"message","instance":"pushover.0","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"systemLang":"en"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [iobroker] - host.raspberrypi4-iobroker 2594 states saved

[DEBUG] [iobroker] - host.raspberrypi4-iobroker 2163 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2019_12_28-14_42_17_backupiobroker.tar.gz

[DEBUG] [iobroker] - done`

Viele Grüße

Markus

**Comment by simatec** [comment]
Gibt es denn eine zigbee Datenbank?
Hast du mal probiert dein ganzes System neu zustarten?
Eventuell gibt es auch ein Problem mit der Rechtevergabe und der Installer Fix kann Abhilfe schaffen

**Comment by MC-1984** [comment]
Das System habe ich vor zwei Wochen erst aufgesetzt. An den Rechten sollte es daher nicht liegen. System habe ich schon neu gestartet. Ich verwende den deconz Adapter. Ich bin davon ausgegangen, dass die Daten des Adapters mit zigbee Datenbank gemeint sind?

**Comment by simatec** [comment]
Nein deconz ist zwar auch für den Zigbee Funkstandard, aber verbindet sich direkt mit der Phoscon App, in der deine Geräte angelegt sind. 
Wenn du keinen Zigbee Adapter nutzt, musst du die Option deaktivieren. Werde da in der nächsten Version aber ne Abfrage zur Sicherheit einbauen
