### ISSUE TITLE
history.html als json

### ISSUE THREAD

**Issue by darkiop** [simatec/ioBroker.backitup#233]
Feature Request:
backitup.0.history.html als json-Objekt um es in einer Tabelle über VIS sauber darstellen zu können, z.B. mit Hilfe von https://github.com/Scrounger/ioBroker.vis-materialdesign#table

**Comment by simatec** [comment]
Guter Vorschlag. Nehme ich mir mit auf die Todo ...

**Comment by darkiop** [comment]
Super, vielen Dank!

**Comment by simatec** [comment]
Ist ab Version 1.4.0 mit enthalten ...
