### ISSUE TITLE
Featurerequest Datumsformat

### ISSUE THREAD

**Issue by damadmax** [simatec/ioBroker.backitup#234]
Könnte man die Zeitangaben (z.B.: "backitup.0.history.iobrokerLastTime") der letzten Backups mittels Formatstring ausgeben?
Oder alternativ mittels Date.toJSON(). So wäre es einfacher das Datum per Skript weiter zu verarbeiten bzw. entsprechend zu formatieren.

Danke

**Comment by simatec** [comment]
Kannst du bitte ein Beispiel posten, wie du dir das genau vorstellst?

**Comment by damadmax** [comment]
Ich denke am einfachsten wäre ein weiterer State, der das Datum des letzten Backups unformatiert (json) enthält. Dafür ist wohl die .toJSON() Methode von Date ( @https://www.w3schools.com/jsref/jsref_tojson.asp) am sinnvollsten. Den Wert kann man dann wiederum einfach parsen und nach eigenen Vorstellungen formatieren. 

So sollte es eigentlich gehen:

main.js:78+ `adapter.setState(`history.${type}LastTimeJSON`, new Date().toJSON(), true);`

**Comment by simatec** [comment]
Ab Version 1.4.0 wird eine history als json ausgegeben. Diese könntest du nach der Zeit filtern und auswerten ...
