### ISSUE TITLE
Hinweis zu "Backup auf gleichem Filesystem wie iobroker"?!

### ISSUE THREAD

**Issue by Apollon77** [simatec/ioBroker.backitup#235]
macht es ggf Sinn einen speziellen Hinweis im Admin anzuzeigen wenn jemand ein backup "lokal" macht das man Ihm eine warnung anzeigt das das nicht empfohlen ist?!

**Comment by simatec** [comment]
Das wäre sicher sehr sinnvoll. 
Ich finde die Idee auch super 👍🏻

**Comment by simatec** [comment]
@Apollon77 soll dieser Hinweis beim Speichern der Einstellungen als PopUp kommen oder bei der Ausführung des Backup im Log als Warnung kommen?

**Comment by Apollon77** [comment]
man könnte es auch in der UI Rot anzeigen wenn das lokale gewählt ist.Ich denke Log sieht "keiner" ... also wenn irgendwie im Admin

**Comment by simatec** [comment]
@Apollon77  Ich habe es in Version 1.8.4 eingebaut und es wird beim öffnen der backitup Config im admin angezeigt.
Also erfolgt dies bereits beim ersten Start von backitup

![image](https://user-images.githubusercontent.com/39792461/104017052-b6a40680-51b7-11eb-9551-6a8ea702705f.png)

**Comment by Apollon77** [comment]
thx vllt den text bissl erweitern wie

Laut den EInstellungen werden Backups aktuell im gleichen lokalen Dateisystem gespeichert welches auch die Quelle der Sicherung ist. Im Falls eines Dateisystem-Fehlers kann auf die backups dann auch nicht mehr zugegriffen werden<p>Es wird empfohlen einen externen Speicherplatz als Backup-Ziel zu nutzen.

(unpolished)

**Comment by simatec** [comment]
Hab das ganze noch etwas schöner gemacht ...
Den text passe ich auch noch einmal an ... Wird ne sehr lange Zeile in words ;-)

![image](https://user-images.githubusercontent.com/39792461/104026920-ed354d80-51c6-11eb-856f-a99a6a11820e.png)

**Comment by simatec** [comment]
So habe die Grafik und den Text noch einmal angepasst.
@Apollon77 Ist das so OK?

<img width="1131" alt="Bildschirmfoto 2021-01-09 um 20 34 05" src="https://user-images.githubusercontent.com/39792461/104107096-3b774900-52ba-11eb-8171-b7e183635671.png">

**Comment by Apollon77** [comment]
perfect
