### ISSUE TITLE
Fehler "TypeError: Cannot read property 'split' of undefined" bei lokalem Serverpfad

### ISSUE THREAD

**Issue by AlonesomeGermany** [simatec/ioBroker.backitup#236]
Ab der Adapterversion >1.3.0 bekomme ich folgenden Fehler:

Host | Datum | Fehler | Beschreibung
-- | -- | -- | --
host.home-server | 2020-01-12 15:57:25.661 | error | Caught by controller[0]:     at listOnTimeout (timers.js:263:5)
host.home-server | 2020-01-12 15:57:25.661 | error | Caught by controller[0]:     at tryOnTimeout (timers.js:300:5)
host.home-server | 2020-01-12 15:57:25.661 | error | Caught by controller[0]:     at ontimeout (timers.js:436:11)
host.home-server | 2020-01-12 15:57:25.661 | error | Caught by controller[0]:     at Timeout.setTimeout [as _onTimeout]  (/opt/iobroker/node_modules/iobroker.backitup/lib/list.js:86:55)
host.home-server | 2020-01-12 15:57:25.661 | error | Caught by controller[0]:     at result (/opt/iobroker/node_modules/iobroker.backitup/main.js:639:35)
host.home-server | 2020-01-12 15:57:25.661 | error | Caught by controller[0]:     at Array.forEach (<anonymous>)
host.home-server | 2020-01-12 15:57:25.661 | error | Caught by controller[0]:     at Object.keys.forEach.type (/opt/iobroker/node_modules/iobroker.backitup/main.js:642:26)
host.home-server | 2020-01-12 15:57:25.661 | error | Caught by controller[0]:     at Array.forEach (<anonymous>)
host.home-server | 2020-01-12 15:57:25.661 | error | Caught by controller[0]:     at data.(anonymous  function).iobroker.data.(anonymous function).iobroker.filter.forEach.f  (/opt/iobroker/node_modules/iobroker.backitup/main.js:643:42)
host.home-server | 2020-01-12 15:57:25.661 | error | Caught by controller[0]:     at getName (/opt/iobroker/node_modules/iobroker.backitup/main.js:618:27)
host.home-server | 2020-01-12 15:57:25.659 | error | Caught by controller[0]: TypeError: Cannot read property 'split' of undefined

Wenn ich auf <= 1.3.0 downgrade, verschwindet der Fehler wieder.
Aktiv ist nur die Option "NAS/Copy", unter "Pfad" ist ein lokaler Pfad, der auch auf dem Server liegt, angegeben.

Anbei noch die Verisonsnummern der Komponenten:
Betriebssystem
    linux
Architektur
    x64
CPUs
    2
Geschwindigkeit
    2268 MHz
Modell
    Intel(R) Pentium(R) CPU G3220 @ 3.00GHz
RAM
    11.61 GB
Node.js
    v10.18.0
NPM
    6.13.4

**Comment by simatec** [comment]
Gehe mal in den Tab wiederherstellen und setze mal die Backup Quelle auf dein NAS. 
Ich gehe davon aus, dass bei Backup Quelle aktuell nix ausgewählt ist.

**Comment by AlonesomeGermany** [comment]
Danke für den Hinweis, das war tatsächlich der Fall. Nur leider ist der Fehler dadurch nicht weg :-(

**Comment by simatec** [comment]
Dann probiere mal als Auswahl lokal. 
Ich schaue mir die Abfrage die Tage noch einmal an

**Comment by AlonesomeGermany** [comment]
Leider auch keine Änderung. Fehler ist immer noch da.
Kein Problem, ich downgrade erstmal. Daher kein Zeitdruck ;-)

**Comment by simatec** [comment]
Welche Version hat den Fehler? Nutzt du den Compact Modus für Backitup?

**Comment by simatec** [comment]
Ab Version 1.3.2 gab es eine Änderung im Filename des Backups.
Ändere mal deine bestehenen Backups von "minimal...." auf "iobroker...."
Dann ist auch die Fehlermeldung weg.
Die Fehlermeldung sagt aus, dass kein Backup gefunden wird.

**Comment by AlonesomeGermany** [comment]
Danke für den Hinweis, ich habe die Namen bei allen bestehenden Backups geändert (z.B. iobroker_2020_01_12-16_11_00_backupiobroker.tar.gz). Leider ist der Fehler immer noch da.
Was vielleicht noch interessant ist: Weder unter der Option "Lokal" noch "NAS" sehe ich die bestehenden Backups. Könnte also tatsächlich ein Problem beim Einlesen sein. Hab gerade nochmal die Berechtigung auf den Ordner geprüft; der passt aber und wurde in letzter Zeit auch nicht verändert.

**Comment by AlonesomeGermany** [comment]
Hab die Ursache jetzt gefunden; in meinem Backup-Ordner lagen noch zwei weitere Ordner. Diese scheint er einzlesen und nicht verarbeiten zu können. Vielleicht kann man ja das bei der nächsten Version abfangen
