### ISSUE TITLE
History States updated on start of backup, and not after successful backup

### ISSUE THREAD

**Issue by Mic-M** [simatec/ioBroker.backitup#24]
I have noticed that the history states (backitup.0.history.html, backitup.0.history.totalLastTime, etc.) are updated on backup start, and not once the backup is successfully completed.
My concern is that if the backup fails, the history html would still show in vis that backup has been executed.
Recommendation is to update the state **after** the backup is successfully completed.

Thanks.

P.S. the same happens in the log, it just shows "backitup.0 | 2018-08-06 20:06:18.732 | info | [minimal] oneClick backup started", but not if successfully completed, which would be way more important.

**Comment by peoples0815** [comment]
You're right, this change is part of one of the newer versions
