### ISSUE TITLE
mySQL backup causes errors "too many connections"

### ISSUE THREAD

**Issue by dwm66** [simatec/ioBroker.backitup#242]
During the time the SQL backup is running, the sql.0 adapter throws a lot of errors:

Example:
`2020-02-07 02:02:04.370 - error: sql.0 (621) Error: ER_CON_COUNT_ERROR: Too many connections`

There are literally hundreds of these errors happening.

This is caused by the mysqldump, which locks all tables during the database dump. Dumping a large database causes the connection attemps to stack up and reach the limit.

A probable fix can be adding a "--quick --single-transaction" to the mysqldump command.

> The --quick options just speeds up the process of retrieving the data from the database (see here), the real improvement comes from the --single-transaction option: instead of locking the database, mysqldump then uses the transaction mechanism to isolate the backup from concurrent changes to the database. **Note that this only works if you're using InnoDB tables**.

(from http://mwibbels.blogspot.com/2010/12/mysql-mysqldump-and-dropping-database.html)

I tried that by running the command manually, looks ok. 
Could this be integrated to the backitup adapter?

TNX!

**Comment by simatec** [comment]
please post your code suggestions here

**Comment by dwm66** [comment]
lib/scripts/30-mysql.js:

Line 16 is

> child_process.exec(`${options.exe ? options.exe : 'mysqldump'}  -u ${options.user} -p${options.pass} ${options.dbName} -h ${options.host} -P ${options.port} > ${fileNameMysql}`, (error, stdout, stderr) => {

change to

	child_process.exec(`${options.exe ? options.exe : 'mysqldump'}  -u ${options.user} -p${options.pass} ${options.dbName} -h ${options.host} -P ${options.port} --quick --single-transaction > ${fileNameMysql}`, (error, stdout, stderr) => {

The question is if this needs to be optional. If it can happen that the DB creates not InnoDB tables (don't know ...), it's necessary to turn that off.

**Comment by simatec** [comment]
added at Release 1.4.0
