### ISSUE TITLE
Fehlermeldung im Log nach update auf 1.4.0

### ISSUE THREAD

**Issue by lhoem** [simatec/ioBroker.backitup#250]
Hallo,

habe gerade upgedatet. Danach kommt seitdem folgende Fehlermeldung:

backitup.0 | 2020-03-01 08:27:22.955 | error | (29314) Error: Login incorrect.
-- | -- | -- | --
backitup.0 | 2020-03-01 08:27:19.461 | info | (29314) starting. Version 1.4.0 in /opt/iobroker/node_modules/iobroker.backitup, node: v10.16.3

Als Backup Ziel ist FTP eingestellt.
Gibt es diese Meldung auch bei anderen?
Gruß
lhoem

**Comment by simatec** [comment]
Bitte poste mal deine JS-Controller und Node Version. 
Des Weiteren stelle bitte die Instanz von Backitup auf debug und poste bitte den Log, wenn die Fehlermeldung auftritt. 
Wann tritt der Fehler auf? Bei der Backupausführung oder beim Start des Adapters?

**Comment by lhoem** [comment]
Hallo,

Node.jsv10.16.3 
JS 4.4.2

Fehler tritt direkt beim Start / Neustart des Adapters auf.

backitup.0 | 2020-03-01 14:18:33.092 | error | (29507) Error: Login incorrect.
-- | -- | -- | --
backitup.0 | 2020-03-01 14:18:27.635 | info | (29507) [ccu] backup was activated at 01:30 every 3 day(s)
backitup.0 | 2020-03-01 14:18:27.596 | info | (29507) starting. Version 1.4.0 in /opt/iobroker/node_modules/iobroker.backitup, node: v10.16.3
backitup.0 | 2020-03-01 14:18:26.968 | debug | (29507) statesDB connected
backitup.0 | 2020-03-01 14:18:26.967 | debug | (29507) States connected to redis: 127.0.0.1:9000
backitup.0 | 2020-03-01 14:18:26.958 | debug | (29507) States create System PubSub Client
backitup.0 | 2020-03-01 14:18:26.957 | debug | (29507) States create User PubSub Client
backitup.0 | 2020-03-01 14:18:26.950 | debug | (29507) Redis States: Use Redis connection: 127.0.0.1:9000
backitup.0 | 2020-03-01 14:18:26.948 | debug | (29507) objectDB connected
backitup.0 | 2020-03-01 14:18:26.944 | debug | (29507) Objects connected to redis: 127.0.0.1:9001
backitup.0 | 2020-03-01 14:18:26.932 | debug | (29507) Objects client initialize lua scripts
backitup.0 | 2020-03-01 14:18:26.932 | debug | (29507) Objects create User PubSub Client
backitup.0 | 2020-03-01 14:18:26.932 | debug | (29507) Objects create System PubSub Client
backitup.0 | 2020-03-01 14:18:26.929 | debug | (29507) Objects client ready ... initialize now
backitup.0 | 2020-03-01 14:18:26.903 | debug | (29507) Redis Objects: Use Redis connection: 127.0.0.1:9001

**Comment by simatec** [comment]
Welche Version war vorher installiert?
Backitup will beim Start das letzte erstellte Backup prüfen. So wie es ausschaut, bekommt backitup keinen Zugriff auf den FTP Server ... Prüfe mal bitte, ob dies auch bei der Erstellung des Backups auftritt ...
