### ISSUE TITLE
historyDB: Error: 

### ISSUE THREAD

**Issue by mobidicker** [simatec/ioBroker.backitup#254]
Nachdem ich gestern backitup installiert habe kam heute folgende Fehlermeldung:

BackItUp:
Das Backup wurde nicht vollständig erstellt. Bitte überprüfe die Fehlermeldungen!!

historyDB: Error: EACCES: permission denied, scandir '/media/usbdisk/lost+found'

Aus meiner Sicht hat das Programm keine Schreibbrechtigung. Was kann ich ändern und wie?

**Comment by simatec** [comment]
Du musst dem User iobroker Schreibrechte auf dem Stick geben

**Comment by mobidicker** [comment]
Wie????Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [simatec/ioBroker.backitup] historyDB: Error:  (#254)Von: simatec An: "simatec/ioBroker.backitup" Cc: mobidicker ,Author Du musst dem User iobroker Schreibrechte auf dem Stick geben

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/simatec/ioBroker.backitup/issues/254?email_source=notifications\u0026email_token=ANZWQ5SKPVCQAHOZK4X3DRDRFP6GJA5CNFSM4K7Y4KSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENQQBIA#issuecomment-593559712",
"url": "https://github.com/simatec/ioBroker.backitup/issues/254?email_source=notifications\u0026email_token=ANZWQ5SKPVCQAHOZK4X3DRDRFP6GJA5CNFSM4K7Y4KSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENQQBIA#issuecomment-593559712",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by simatec** [comment]
Man sollte schon in ganzen Sätzen kommunizieren ...
