### ISSUE TITLE
Umlaute werde nicht angezeigt

### ISSUE THREAD

**Issue by senger1985** [simatec/ioBroker.backitup#255]
Unter backitup.0.history.iobrokerLastTime und backitup.0.info.iobrokerNextTime werden die Umlaute nicht mehr richtig dargestellt.

Beispiel:
06. M**ae**rz 2020 um 2:00 Uhr

Vor ein paar Updates stand da noch:
06. M**ä**rz 2020 um 2:00 Uhr

**Comment by simatec** [comment]
Da wurde nichts geändert ...

**Comment by senger1985** [comment]
Komisch, dann weiß ich nicht, warum er bei mir die Umlaute nicht anzeigt.
