### ISSUE TITLE
MYSQL backup bei iobroker unter Docker

### ISSUE THREAD

**Issue by RaiRoo** [simatec/ioBroker.backitup#256]
Hallo,
ich habe iobroker unter Docker auf Synology laufen. Backitup funktioniert wunderbar, habe lediglich Probleme beim Backup von MYSQL. Folgende Fehlermeldung:
[ERROR] [mysql] - [IGNORED] Error: Command failed: /usr/local/mariadb10/bin/  -u iobroker -p***** iobroker -h localhost -P 3307 > /opt/iobroker/backups/mysql_2020_03_06-17_30_31_backupiobroker.sql
/bin/sh: 1: /usr/local/mariadb10/bin/: not found
Liegt vermutlich daran, dass iobroker unter Docker läuft. Gibt es hier einen Workaround?
RaiRoo

**Comment by simatec** [comment]
Auf deinem System müssen die mysql clients installiert sein.

**Comment by RaiRoo** [comment]
Wow … danke für die schnelle Hilfe!!!

**Comment by simatec** [comment]
Kein Problem 😬
