### ISSUE TITLE
please add postgress BackUp

### ISSUE THREAD

**Issue by dfrozen** [simatec/ioBroker.backitup#257]
please add Postgres. Not everyone uses MySql. The functionality of the iobroker SQL adapter offers a choice of 4 DB type, but BackUp does not have this choice

**Comment by dfrozen** [comment]
In the branch I created myself, I made the appropriate changes. I ask for verification, I'm not a very good programmer. I checked the backup. I did not check the recovery from the copy.

**Comment by simatec** [comment]
Please post the complete command line for the backup here

**Comment by dfrozen** [comment]
for backup `pg_dump --dbname=postgresql://user:password@.host:.port/dbName > fileName`
for restore `pg_restore --dbname=postgresql://user:password@host:port/dbName < fileName`
for CreateNewDB` psql -c "create database dbName" -dbname=postgresql://user:password@.host:.port/` but create new DB work if you login on PGAdmin

**Comment by dfrozen** [comment]
my fork worked
![image](https://user-images.githubusercontent.com/28303847/76868505-18d1fa80-6878-11ea-92b1-6de4c3ae7be8.png)
![image](https://user-images.githubusercontent.com/28303847/76868580-31daab80-6878-11ea-8560-ad9996d0e8fa.png)

**Comment by simatec** [comment]
added at 1.8.1
