### ISSUE TITLE
Feature Request: timestamp zum history.json hinzufügen

### ISSUE THREAD

**Issue by Scrounger** [simatec/ioBroker.backitup#260]
@simatec 

Könntest du bitte dem history.json objekt noch den raw timestamp zusätzlich zu date hinzufügen?
Hintergrund ist, dass man den timestamp sehr einfach in sein eigenes gewünschtes Format umwandeln kann. Akutell ist die umwandlung des date sehr aufwendig und vorallem sprachen abhängig.

Du könntest mir auch sagen wo im Code du das history.json erstellst, dann mach ich nen pr.
Hab das aber nicht in deinem Code finden können.

**Comment by simatec** [comment]
Werde ich mit einplanen ...
