### ISSUE TITLE
Speichern betätigen obwohl nichts geändert

### ISSUE THREAD

**Issue by obodeldog** [simatec/ioBroker.backitup#269]
Folgendes verstehe ich nicht: Wieso muss ich speichern, wenn ich nichts verändert habe. Ich öffne den Adapter, gehe auf "Wiederherstellen", dann "Abrufen" und dann kommt diese Meldung
![image](https://user-images.githubusercontent.com/35403739/77437677-39a0cf80-6de5-11ea-96a7-5166b2295333.png)

**Comment by simatec** [comment]
Dann hast du sicher auf FTP in der Backupquelle umgestellt ...

**Comment by obodeldog** [comment]
:-) Nee.

**Comment by simatec** [comment]
Problem sollte mit der neusten version gefixt sein.
GGfs. den Adapter komplett löschen und neu installieren ...
