### ISSUE TITLE
Domain wird nicht gespeichert.

### ISSUE THREAD

**Issue by el-Presi** [simatec/ioBroker.backitup#270]
Problem:

Eingeben einer Domain jetzt möglich (eine Domain ist für mich mit TLD-Endung aber ohne Punkt am Ende - also keine FQDN) - ein Beispiel wäre gut, denn ich denke mir, dass viele geneigt wären, den NETBIOS Namen dort einzugeben.

Wie auch immer. Nach klicken auf Speichern schlagen Anmeldungen fehl, da die Domain nicht im Befehl auftaucht - auch bei Speichern und Schließen ist das Feld beim nächsten mal leer. Sowohl bei deiner Domain, als auch bei einem NETBIOS Namen..

**Comment by simatec** [comment]
Gefixt in Version 1.4.5
