### ISSUE TITLE
Zeitplan wird ignoriert.

### ISSUE THREAD

**Issue by el-Presi** [simatec/ioBroker.backitup#271]
Ich habe im Zeitplan eingetragen "Backup alle "1" Tage" (bei mir steht im Feld aber nur eine     1       also ohne "".

Dennoch werden bei mir nur alle 14 Tage Backups gemacht.

**Comment by simatec** [comment]
Bitte die Instanz von Backitup auf debug stellen u d hier den Log vom start des Adapters posten

**Comment by el-Presi** [comment]
Auch nach den beiden Zeiten passiert einfach genau nichts.. Adapter steht auf debug.

`
backitup.0 | 2020-04-01 18:37:24.051 | info | (102935) [ccu] backup was activated at 18:39 every 1 day(s)
backitup.0 | 2020-04-01 18:37:24.038 | info | (102935) [iobroker] backup was activated at 18:38 every 1 day(s)
backitup.0 | 2020-04-01 18:37:23.921 | info | (102935) starting. Version 1.4.5 in /opt/iobroker/node_modules/iobroker.backitup, node: v10.19.0

`

**Comment by simatec** [comment]
Gehe mal wie folgt vor:

- Instanz löschen
- Adapter löschen
- Installer Fix laufen lassen
- restart des Systems 
- Backitup neu installieren 

Wahrscheinlich ist bei irgendeinem Update von node oder ähnlichen was schief gelaufen und wurde nicht richtig kompiliert.
