### ISSUE TITLE
Komme nach update nicht auf die oberfläche

### ISSUE THREAD

**Issue by Babu242** [simatec/ioBroker.backitup#273]
Einen schönen gute Tag
Ich habe den Iobroker auf einem Windowsrechner laufen
das lief auch schon seit 6–7 Monaten einwandfrei,
leider ist jetzt das System abgestürzt und ich bekomme das back up nicht hin.

Das Back-up habe ich mit backitup erstellt mit einem NAS und mit ftp darauf zugegriffen.
Das Hatte auch alles gut funktioniert.
Ich habe das Backup aufspielen wollen das hat nicht funktioniert.
Mittlerweile habe ich den iobroker und auch den Rechner neu aufgesetzt nix geht.
Hier der die das Log
[Backitup Restore.pdf](https://github.com/simatec/ioBroker.backitup/files/4408079/Backitup.Restore.pdf)
<img width="548" alt="host this" src="https://user-images.githubusercontent.com/62934905/78012123-d236d280-7344-11ea-9d15-34f38d518361.PNG">
<img width="716" alt="listen instzances" src="https://user-images.githubusercontent.com/62934905/78012137-d5ca5980-7344-11ea-8030-b9eaab3e414f.PNG">
<img width="772" alt="status" src="https://user-images.githubusercontent.com/62934905/78012151-d9f67700-7344-11ea-9273-68a9db882775.PNG">

Vielen dank für eure hilfe

**Comment by simatec** [comment]
Was sagt dein Log? 
Stoppe mal Admin mit iobroker stop admin.0 und starte dann admin.0 mal neu. Bitte die Ausgaben aus der Log Datei auch hier posten

**Comment by Babu242** [comment]
Hallo Simatec also ich habe jetzt ein log im Ordner log gefunden
[iobroker.2020-03-31.log] der ist aber von heute morgen
(https://github.com/simatec/ioBroker.backitup/files/4408925/iobroker.2020-03-31.log)

Dan habe ich das 

<img width="719" alt="admi 0 stop" src="https://user-images.githubusercontent.com/62934905/78025379-3912b680-735a-11ea-9e63-73768363d82b.PNG">

oder was hast du gemeint ?

LG Babu

**Comment by simatec** [comment]
Starte mal deinen Adapter admin mit:

`iobroker start admin`

und versuche dann auf das WebIF zukommen.
Falls es nicht gehen sollte, poste die Logdatei nochmal. Da sollten dann ja neue Einträge vorhanden sein.

**Comment by Babu242** [comment]
Hallo hab ich gemacht ich komm nicht auf das WebIF
meiner Meinung hat sich auch im log nichts geändert
[iobroker.2020-03-31.log](https://github.com/simatec/ioBroker.backitup/files/4409510/iobroker.2020-03-31.log)

**Comment by Babu242** [comment]
Ich habe den Rechner neu gestartet  und Dan hat sich auch etwas im log veränder
[iobroker.2020-03-31.log](https://github.com/simatec/ioBroker.backitup/files/4409606/iobroker.2020-03-31.log)

**Comment by simatec** [comment]
OK, mit welche IP versuchst du admin aufzurufen?

**Comment by Babu242** [comment]
also 
http://192.168.178.43:8081/#tab-introdas ist die ursprüngliche wenn  der iobroker neu instaliert ist und noch kein update gemacht ist
nach updateversuch weg

auf dem rechner selbst
http://localhost:8081
geht auch nix

**Comment by simatec** [comment]
Laut Log ist da aber hinten die 70. 
Ist denn iobroker vor dem Restore erreichbar?

**Comment by Babu242** [comment]
wenn ich den iobroker neu aufsetzte und noch nichts gemacht habe außer die Installation + adapter backitup  erreiche ihn ohne Probleme
sobald ich das update starte ist er weg 
mit der 70 habe ich auch schon probiert kein Zugriff

**Comment by simatec** [comment]
OK, dann setze mal bitte neu auf und führe mal den Restore über die Konsole aus

`iobroker restore 0`

Nur mal zur Sicherheit, damit wir Fehler beim Adapter ausschließen können

**Comment by Babu242** [comment]
also ich habe den iobroker jetzt deinstalliert und wieder neu installiert
ich erreiche ihn ohne Probleme
ich habe den befehl ausgeführt ohne ein Backup gemacht zu haben und ohne den backitup Adapter installieren  alles läuft was aber was  auffällt jetzt mit der 70 am ende

**Comment by simatec** [comment]
Hatte ja vorher schon geschrieben, dass dort die 70 am Ende der IP ist. 
Hast du jetzt den Restore deines Backups über Konsole gemacht?
Wenn ja, war es denn erfolgreich und alle Adapter und Einstellungen von deinem alten System sind wieder vorhanden?
Werde aus deinem letzten Kommentar nicht so richtig schlau

**Comment by Babu242** [comment]
Sorry das ich mich unklar ausdrücke 
also ich habe den iobroker jetzt deinstalliert und wieder neu installiert
ich erreiche ihn ohne Probleme
das Heist hier  habe ich noch kein backitup installiert und noch nicht den befehl ausgeführt

ich habe den befehl ausgeführt ( iobroker restore 0)
kein Adapter installiert und kein Backup in einem Ordner
alles wie gehabt alles läuft aber da kein backup da auch keine Veränderung

aber ich klaube jetzt kapiert zu haben das du möchtest das ich das backup von backitup in den ordner packe und es so ausführe  ( iobrker restore 0)
Richtig?

**Comment by simatec** [comment]
Genau ... um einen Fehler beim restore mit Backitup auszuschließen, wäre hier der manuelle Restore am sinnvollsten

**Comment by Babu242** [comment]
ok jetzt bin ich mir nur nicht sicher in welchen Ordner ich das backup legen soll
und ob ich es umbenennen muss

**Comment by simatec** [comment]
Es muss ebenfalls in den Ordner backups. Identisch wie bei Backitup

**Comment by Babu242** [comment]
Guten Morgen 
das mit dem backup habe ich hinbekommen leider mit dem selben Ergebnis
 das ich nicht mehr auf das WebIf komme
[iobroker.2020-03-31.log](https://github.com/simatec/ioBroker.backitup/files/4413354/iobroker.2020-03-31.log)

**Comment by simatec** [comment]
Also da ist irgenwas sehr eigenartig bei dir.
Auch wenn es hier nicht her passt, da es nichts mit backitup zu tun hat, probiere ich zu helfen.

Mache mal bitte folgendes

`
iobroker host this
iobroker add admin
iobroker set admin.1 --port 8089 --ssl false
iobroker restart admin.1
`


Im Anschluss sollte dein iobroker über folgende Adresse erreichbar sein.

`http://192.168.178.70:8089`

Wenn dies der Fall ist, schauen wir uns gemeinsam deine Config von admin.0 an

**Comment by Babu242** [comment]
Hallo simatec 
das geht auch nicht
vielen dank für deine hilfe und zeit
ich habe mich entschlossen von vorne anzufangen und mache gerade alles neu
bleib Gesund und nochmals danke
