### ISSUE TITLE
NFS/CIFS Backup nicht möglich

### ISSUE THREAD

**Issue by candlestorm** [simatec/ioBroker.backitup#282]
Hallo Zusammen,

ich habe den Adapter nun installiert und erhalte obwohl Passwort/Verzeichnis etc. korrekt hinterlegt ist die folgende Fehlermeldung:

backitup.0 | 2020-04-17 09:50:24.235 | error | Try 'mount --help' for more information.
-- | -- | -- | --
backitup.0 | 2020-04-17 09:50:24.235 | error | mount: bad usage
backitup.0 | 2020-04-17 09:50:24.235 | error | (18615) Error: Command failed: sudo mount -t cifs -o username=iobroker,password=****,rw,file_mode=0777,dir_mode=0777 //192.xxx.xxx.xx/Backup iobroker/ /opt/iobroker/backups

Stimmt hier irgendetwas mit dem Befehl nicht?
Habe schon alle möglichen Varianten probiert aber die Fehlermeldung bleibt.
Benutz Ubuntu als OS.

Viele Grüße!
Tobias

**Comment by simatec** [comment]
Bitte installiere die cifs-utils laut Doku

**Comment by candlestorm** [comment]
Habe ich installiert.
Mittlerweile durch rumprobieren habe ich auch die Lösung.

sudo mount -t cifs -o username=iobroker,password=****,rw,file_mode=0777,dir_mode=0777 //192.xxx.xxx.xx/Backup iobroker/ /opt/iobroker/backups

funktioniert nicht als Befehl, weil mein Ordner auf der Synology Diskretion "Backup iobroker" ein Leerzeichen enthält. Hier müsste der Adapter dann "//192.xxx.xxx.xx/Backup iobroker/" den Pfad in Anführungszeichen setzen, was er aber nicht automatisch macht. Ich habe nun einfach den Ordner ohne Leerzeichen umbenannt und es funktioniert.
