### ISSUE TITLE
Sicherungen pro Instanz machen

### ISSUE THREAD

**Issue by ldittmar81** [simatec/ioBroker.backitup#286]
Das Sichern von mehrere CCUs erlauben.

**Comment by simatec** [comment]
Eine Möglichkeit wäre, dass man mehrere IP‘s eintragen könnte und die werden nacheinander abgearbeitet. Nachteil, Benutzer und Passwort sollten identisch sein. Oder ich schaue mal, ob man das über die Instanzen von hm lösen könnte. Mache mir die Tage mal gedanken

**Comment by Caspar78** [comment]
Moin,
das geht wunderbar über Instanzen.
Also in deinem Fall einfach zwei Instanzen installieren und in der zweiten dann eben nur das CCU Backup aktivieren (Wenn die erste Instanz bereits das Broker Backup übernimmt).
Wichtig ist dabei auch das die Backups der CCUs zu unterschiedlichen Zeiten laufen....Siehe Dateiname

Was hier allerdings sehr wünschenswert wäre, wenn man den Dateinamen (der Backupdatei) beeinflussen könnte, denn aktuell kann man die nur anhand des timestamps im Dateinamen unterscheiden.

**Comment by ldittmar81** [comment]
Hmm... was ist wenn man 2 Zigbees oder mal zwei Javascript Instanzen (gibt es oft)? Hmm... es wäre echt cool, wenn man die Sicherungen pro Instanz machen könnte.

**Comment by simatec** [comment]
Zigbee und Jarvis geht mit mehreren Instanzen. 
Javascript schreibe ich mit auf die Todo

**Comment by ldittmar81** [comment]
Und die CCU? 🙏

**Comment by simatec** [comment]
Version 2.2.0
