### ISSUE TITLE
Was ist alles im Backup enthalten - es wird nichts wiederhergestellt

### ISSUE THREAD

**Issue by 9steff2** [simatec/ioBroker.backitup#288]
Nach einem Fehler des JS-Controllers ist der ioBroker nicht mehr aufrufbar....

Habe noch eine 2 Instanz auf einem anderen Server installiert und wollte dort das Backup aufspielen, dieses hat aber nur 3 MB?

Restore über Console läuft durch aber es ist nichts wiederhergestellt....was klappt da nicht?

**Comment by simatec** [comment]
Poste mal den Log. Es dauert eine Weile nach dem Abschluss des Restores, da alle Adapter neu installiert werden

**Comment by 9steff2** [comment]
Danke für die schnelle Antwort, darauf war ich nicht vorbereitet :-)

Das lasse ich dir morgen früh zukommen, bin gerade in die Arbeit gefahren....
Also ich hab die Konsole aufgemacht
pkill io 
iobroker restore 0

dann die iobroker Instanz komplett neu gestartet, ab dann meinst du einfach lange warten?
Sind dann alle Adapter wieder da und auch Visualisierung mit den Skripten?

**Comment by simatec** [comment]
Ja nach dem Restore werden alle Adapter installiert. Einstellungen und Scripte werden aus dem Backup wiederhergestellt

**Comment by 9steff2** [comment]
ok das mit den 2 Stunden warten, hatte ich bei einem 3 MB großen Update nicht gedacht :-)

Gedult hätte ich mitbringen müssen, das hatte ich irgendwie aufgrund des Schocks nicht.....er hat jetzt sehr viel wiederhergestellt, muss jetzt alles Punkt für Punkt kontrollieren, ob wirklich alles wieder da ist :-)

Vielen Dank dir auf jeden Fall, auch für die sehr schnelle Antwort!!!
