### ISSUE TITLE
CCU Backup, upload auf Dropbox funktioniert nicht

### ISSUE THREAD

**Issue by Hosenroller** [simatec/ioBroker.backitup#290]
Hallo, dies ist mein erster Beitrag auf Github. Ich hoffe das passt so.

mein CCU Backup wird lokal erstellt und abgelegt aber nicht auf dropbox hochgeladen.

- Das Backup von iobroker funktioniert und wird auch hochgeladen
- in den Logs finde ich nichts obwohl Debugging aktiv ist
- das Problem hatte ich mit der 1.4.* als auch mit der 1.5 Version
- in der Pushover Meldung steht das dass Backup erstellt wurde und auf dropbox gespeichert
- in objekct ccuLastTime + iobrokerLastTime steht "error:" + Uhrzeit

DANKE für eure Hilfe und bleibt gesund.

**Comment by Hosenroller** [comment]
* Mit Version 1.5.3 erhalte ich die Meldung mit Pushover
BackItUp:
Das Backup wurde nicht vollständig erstellt. Bitte überprüfe die Fehlermeldungen!!

dropbox: [object Object]

**Comment by simatec** [comment]
Mit großer Wahrscheinlichkeit kann keine Verbindung zur Dropbox hergestellt werden, da irgendwas bei der Einrichtung nicht korrekt lief.

Bitte richte die Dropbox genau nach Anleitung aus der Readme von Backitup ein.
Dann funktioniert auch die Dropbox
