### ISSUE TITLE
Laut Benachrichtigung wurde ein Backup auf der NAS erstellt - es ist aber keins da?

### ISSUE THREAD

**Issue by Koalabaer** [simatec/ioBroker.backitup#292]
Hallo,

gibt es einen Default-Pfad falls ein Backup erstellt werden soll, die NAS aber nicht startet oder erreichbar ist? Laut Message über Telegramm wurde ein Backup erstellt, aber es ist keins da...

VG und danke

Koala

**Comment by simatec** [comment]
Der Standard Backup-Pfad im iobroker ist /opt/iobroker/backups.
Dort liegen die lokal gespeicherten Backups
