### ISSUE TITLE
mysql backupfiles (.tar.gz) are damaged

### ISSUE THREAD

**Issue by mamaretti** [simatec/ioBroker.backitup#295]
Backup ist created fine 

but mysql_{TIME}_backupiobroker.tar.gz files are currupted.

iobroker_{TIME}_backupiobroker.tar.gz files could be extracted and content seams to be ok

`mysqldump -uUSERr -pPASS iobroker -h localhost -P 3306 --quick --single-transaction > dump.sql`

via commandline ist working and dump is ok.

Thx

**Comment by simatec** [comment]
Please run the iobroker Installer fix

**Comment by simatec** [comment]
Please run the iobroker Installer fix and ceck your Config from Backitup

**Comment by mamaretti** [comment]
i have done this

**Comment by simatec** [comment]
is the error still present?
Please send a debuglog ...

**Comment by mamaretti** [comment]
### iobroker log

backitup.0 | 2020-06-15 17:11:14.459 | info | (9100) [iobroker] backup was activated at 22:00 every 1 day(s)
backitup.0 | 2020-06-15 17:11:14.423 | info | (9100) starting. Version 1.5.4 in /opt/iobroker/node_modules/iobroker.backitup, node: v12.18.0, js-controller: 3.1.4
backitup.0 | 2020-06-15 17:11:14.414 | info | (9100) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
backitup.0 | 2020-06-15 17:11:09.653 | info | (1904) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
backitup.0 | 2020-06-15 17:11:09.652 | info | (1904) terminating
backitup.0 | 2020-06-15 17:11:09.652 | info | (1904) cleaned everything up...
backitup.0 | 2020-06-15 17:11:09.648 | info | (1904) Got terminate signal TERMINATE_YOURSELF


### backitup log

Gestartet...
[DEBUG] [mount] - Wake on LAN wait 25 Seconds for NAS!
[DEBUG] [mount] - Wake on LAN MAC-Address: 20:DE:20:DE:20:DE
[DEBUG] [mount] start with {"mountType":"CIFS","type":"storage","source":"cifs","mount":"//MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****"}
[DEBUG] [mount] - done
[DEBUG] [iobroker] start with {"type":"creator","time":"22:00","debugging":true,"everyXDays":"1","deleteBackupAfter":0,"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"//MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****","context":{"fileNames":[],"errors":{},"done":["mount"],"types":[]},"adapter":null},"mysql":{"enabled":true,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"nameSuffix":"","mysqlQuick":false,"mysqlSingleTransaction":false,"dbName":"iobroker","user":"iobroker","pass":"****","deleteBackupAfter":5,"host":"localhost","port":"3306","exe":""},"dir":"/opt/iobroker","redis":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"path":"/var/lib/redis"},"historyDB":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"path":"media/usb/history"},"zigbee":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"path":"/opt/iobroker/iobroker-data"},"history":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"Pushover","type":"message","instance":"","SilentNotice":false,"NoticeType":"longTelegramNotice","User":null,"onlyError":true,"telegramWaiting":0,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"Pushover","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Pushover","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [iobroker] - host.MYHOST 1245 states saved

[DEBUG] [iobroker] - host.MYHOST 1143 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2020_06_15-17_12_01_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [mysql] - done
[DEBUG] [cifs] - done
[DEBUG] [clean] - done
[DEBUG] [mysql] - MySql File deleted!
[DEBUG] [pushover] - done
[DEBUG] [history] - backitup.0.history.html
[DEBUG] [history] - backitup.0.history.json
[EXIT] 0
[DEBUG] [umount] - mount activ... umount in 60 Seconds!!
[DEBUG] [cifs] start with {"mountType":"CIFS","type":"storage","source":"cifs","mount":"//MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****","backupDir":"/opt/iobroker/backups","deleteBackupAfter":0}
[DEBUG] [pushover] start with {"type":"creator","time":"22:00","debugging":true,"everyXDays":"1","deleteBackupAfter":0,"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"//MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****","context":{"fileNames":["/opt/iobroker/backups/iobroker_2020_06_15-17_12_01_backupiobroker.tar.gz","/opt/iobroker/backups/mysql_2020_06_15-17_12_04_backupiobroker.tar.gz"],"errors":{},"done":["mount","iobroker","mysql"],"types":["iobroker","mysql"]},"adapter":null},"mysql":{"enabled":true,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"nameSuffix":"","mysqlQuick":false,"mysqlSingleTransaction":false,"dbName":"iobroker","user":"iobroker","pass":"****","deleteBackupAfter":5,"host":"localhost","port":"3306","exe":""},"dir":"/opt/iobroker","redis":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"path":"/var/lib/redis"},"historyDB":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"path":"media/usb/history"},"zigbee":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"path":"/opt/iobroker/iobroker-data"},"history":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"Pushover","type":"message","instance":"","SilentNotice":false,"NoticeType":"longTelegramNotice","User":null,"onlyError":true,"telegramWaiting":0,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"Pushover","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Pushover","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"systemLang":"de","time":"15. Juni 2020 um 17:12 Uhr"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [history] start with {"type":"creator","time":"22:00","debugging":true,"everyXDays":"1","deleteBackupAfter":0,"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"//MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****","context":{"fileNames":["/opt/iobroker/backups/iobroker_2020_06_15-17_12_01_backupiobroker.tar.gz","/opt/iobroker/backups/mysql_2020_06_15-17_12_04_backupiobroker.tar.gz"],"errors":{},"done":["mount","iobroker","mysql"],"types":["iobroker","mysql"]},"adapter":null},"mysql":{"enabled":true,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"nameSuffix":"","mysqlQuick":false,"mysqlSingleTransaction":false,"dbName":"iobroker","user":"iobroker","pass":"****","deleteBackupAfter":5,"host":"localhost","port":"3306","exe":""},"dir":"/opt/iobroker","redis":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"path":"/var/lib/redis"},"historyDB":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"path":"media/usb/history"},"zigbee":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"path":"/opt/iobroker/iobroker-data"},"history":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de","time":"15. Juni 2020 um 17:12 Uhr"},"telegram":{"enabled":true,"notificationsType":"Pushover","type":"message","instance":"","SilentNotice":false,"NoticeType":"longTelegramNotice","User":null,"onlyError":true,"telegramWaiting":0,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"Pushover","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Pushover","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [umount] start with {"mountType":"CIFS","type":"storage","source":"cifs","mount":"//MYNAS.local","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":true,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","deleteOldBackup":true,"ownDir":false,"dir":"/iobroker_BU/iobroker_Backups","dirMinimal":"sharename/backupDir","user":"iobroker","pass":"****","backupDir":"/opt/iobroker/backups"}
