### ISSUE TITLE
Explanation for backup via CIFS vs. FTP

### ISSUE THREAD

**Issue by Seqway** [simatec/ioBroker.backitup#30]
Can you please put on the main page under iobroker / backitup minimum a hint or a direct link to the readme-file ?
Why ? Because the implementation is different when you use CIFS or FTP:

At the beginning of the path you DONT need a "/" when you use CIFS but YOU NEED a "/" when using FTP.
I think that helps a lot for users implementing this adapter

**Comment by simatec** [comment]
Yes ... comming in the next Version
