### ISSUE TITLE
Redis Backup funktioniert nicht, wenn AOF aktiviert ist

### ISSUE THREAD

**Issue by neopholus** [simatec/ioBroker.backitup#301]
Hallo,

ich habe mich ein wenig in Redis eingelesen und aus Gründen der Datensicherheit habe ich AOF (Append-Only-File) aktiviert. Redis würde im Falle eines Falles dann den letzten Dump heranziehen und aufgrund der AOF-Datei alle Änderungen bis zum Absturz "nachfahren" können. Ohne diese Datei fehlen alle Änderungen seit dem letzten Dump.
Siehe [https://redis.io/topics/persistence](https://redis.io/topics/persistence)

Diese Datei legt Redis im selben Verzeichnis ab wie dump.rdb.

Mit dieser Datei scheint Backitup ein Problem zu haben. 
Wenn man in backitup statt einen Pfad einen Dateinamen `/var/lib/redis/dump.rdb`
angibt, wird zumindest der Dump gesichert. Das AOF-File fehlt aber.

Falls das AOF aktiv ist und in dem Verzeichnis liegt und nur der Verzeichnisname angegeben wird, hängt das Redis Backup mit einer Aufgabe, dass bisher 0 MB gepackt sind eine laaange Zeit und dann bricht Backup einfach ab. Ich vermute, das AOF-File ist von Redis immer geöffnet gehalten. Also kann entweder Backitup das File gar nicht lesen oder findet kein korrektes Ende....

Viele Grüße
Stefan

**Comment by simatec** [comment]
Ich schaue mir das an und versuche dafür eine Lösung zu finden ...

**Comment by simatec** [comment]
Grundsätzlich habe ich gelesen, dass AOF Aktivierung nicht empfohlen wird. 
In Backitup ist dagegen auch empfohlen in den settings den Redispfad inkl. Dateinamen anzugeben

**Comment by neopholus** [comment]
Danke für's draufschauen. Dann schalte ich AOF wieder ab.
