### ISSUE TITLE
FTP Connection after backup not closed

### ISSUE THREAD

**Issue by jack-blackson** [simatec/ioBroker.backitup#302]
Hey!

I am using FTP to do the backup from iobroker (on RaspPi) to my Synology NAS. What I can see is that everytime the FTP user logges in, it stayes there as an open conneciton, and the user is not logging of or closing the connection any more, until after some days the NAS closes it. Would it be possible to close the connection after finishing the backup?

**Comment by simatec** [comment]
Please run iobroker Installer fix
