### ISSUE TITLE
Adapter Instanz RAM-Verbrauch zu hoch?

### ISSUE THREAD

**Issue by Mic-M** [simatec/ioBroker.backitup#304]
Hi,
erst mal nur eine Feststellung, und kein "Issue/Problem". 

OS: Debian (Proxmox CT), RAM: 4 GB, Node.js: v12.16.1, js-controller 3.0.18
Sytem Uptime: 25 Tage

Beim zufälligen Blick in die Adapter-Instanzen fällt der backitup-Adapter mit **97 MB RAM-Nutzung** auf, restliche Adapter sind so alle bei ~ 40-60 MB (außer Admin, Web, JS).
Nach Neustart der Instanz: nach paar Minuten bleibt es auf ~ 73 MB (für 30 min. geprüft).
Also im Vergleich zu anderen Adaptern auch nach Neustart signifikant höher.

**Frage:**
Woran könnte das liegen?
Eigentlich läuft da doch nur ein Timer/Schedule, der wartet, bis -- in meinem Fall 3:00 / 3:30 Uhr -- eintritt. Warum also sollte der Adapter außerhalb dieser Zeiten deutlich mehr RAM verbrauchen, als alle anderen Adapter?

**Comment by simatec** [comment]
Die RAM Aufteilung von Linux ist manchmal verwirrend. Ich habe das Anfangs auch kritisch gesehen, aber es ist auf allen Testsystemen bei mir gleich.

**Comment by Mic-M** [comment]
danke für deine schnelle Antwort. Ich hab eh genügend RAM, dachte nur an die Raspi-Nutzer. Aber Linux-Speicherverwaltung blicke ich auch nicht so wirklich, hab nur bislang mit genommen, dass sie sehr effizient ist, aber verwirrend sein kann, wie du ja jetzt wieder bestätigst ;-)

**Comment by Mic-M** [comment]
Hab mir mal kurz die [main.js](https://github.com/simatec/ioBroker.backitup/blob/master/main.js) angesehen. 
Was auffällt ist, dass alle 10 Sekunden ein Timer ausgeführt wird ([Link zur Zeile](https://github.com/simatec/ioBroker.backitup/blob/5e9a8a1a482fe6adb643122dcde3cfa41afc3ee9/main.js#L850)) und da [umount()](https://github.com/simatec/ioBroker.backitup/blob/5e9a8a1a482fe6adb643122dcde3cfa41afc3ee9/lib/list/cifs.js#L192).
Evtl. was damit zu tun? 

Verstehe nämlich aus Entwickler-Seite nicht, warum hier bei meiner Konfiguration alle 10 Sekunden eine Funktion ausgeführt werden sollte.

Siehe hier meine Konfig:
```
  "native": {
    "debugLevel": false,
    "notificationEnabled": false,
    "mySqlEnabled": false,
    "redisEnabled": true,
    "historyEnabled": true,
    "zigbeeEnabled": true,
    "cifsEnabled": true,
    "ftpEnabled": false,
    "dropboxEnabled": false,
    "googledriveEnabled": false,
    "historyEntriesNumber": "25",
    "minimalEnabled": true,
    "minimalTime": "04:00",
    "minimalEveryXDays": "1",
    "minimalDeleteAfter": "30",
    "minimalNameSuffix": "",
    "ccuEnabled": true,
    "ccuTime": "03:30",
    "ccuEveryXDays": "7",
    "ccuDeleteAfter": "5",
    "ccuHost": "xxx",
    "ccuUser": "xxx",
    "ccuPassword": "",
    "mySqlHost": "localhost",
    "mySqlPort": "xxx",
    "mySqlName": "xxx",
    "mySqlUser": "",
    "mySqlPassword": "",
    "mySqlDumpExe": "",
    "mysqlQuick": false,
    "mysqlSingleTransaction": false,
    "redisPath": "/var/lib/redis",
    "historyPath": "xxxx",
    "notificationsType": "Telegram",
    "telegramInstance": "",
    "telegramUser": null,
    "telegramNoticeType": "longTelegramNotice",
    "telegramWaitToSend": "0",
    "telegramSilentNotice": false,
    "telegramOnlyError": false,
    "pushoverInstance": "",
    "pushoverNoticeType": "longPushoverNotice",
    "pushoverWaitToSend": "0",
    "pushoverDeviceID": "",
    "pushoverSilentNotice": false,
    "pushoverOnlyError": false,
    "emailReceiver": "xxx@xxx.com",
    "emailSender": "xxx@xxx.com",
    "emailInstance": "email.0",
    "emailNoticeType": "longEmailNotice",
    "emailWaitToSend": "0",
    "emailOnlyError": false,
    "connectType": "CIFS",
    "cifsMount": "xxxx",
    "cifsDomain": "",
    "cifsUser": "xxxx",
    "cifsPassword": "xxxxx",
    "smbType": "vers=2.0",
    "sudoMount": true,
    "cifsDeleteOldBackup": true,
    "cifsOwnDir": false,
    "wakeOnLAN": false,
    "macAd": "20:DE:20:DE:20:DE",
    "wolWait": "25",
    "cifsMinimalDir": "xxx",
    "cifsCcuDir": "xxx",
    "cifsDir": "xxx",
    "ftpHost": "",
    "ftpPort": "xx",
    "ftpUser": "",
    "ftpPassword": "",
    "ftpDeleteOldBackup": false,
    "ftpOwnDir": false,
    "ftpMinimalDir": "xxx",
    "ftpCcuDir": "xxx",
    "ftpDir": "xxx",
    "dropboxAccessToken": "",
    "dropboxDeleteOldBackup": false,
    "dropboxOwnDir": false,
    "dropboxMinimalDir": "xxx",
    "dropboxCcuDir": "xxx",
    "dropboxDir": "xxx",
    "googledriveAccessJson": "",
    "googledriveDeleteOldBackup": false,
    "googledriveOwnDir": false,
    "googledriveMinimalDir": "xxx",
    "googledriveCcuDir": "xxx",
    "googledriveDir": "xxx",
    "restoreSource": null,
    "startAllRestore": false
  }

```

**Comment by simatec** [comment]
Das ist ein timeout und kein interval. 
Hier wird beim start des Adapters 10 Sekunden gewartet und nicht alle 10 Sekunden gestartet

**Comment by Mic-M** [comment]
Habs auch grad gecheckt, danke, siehe oben ;-) Deine Antwort hat sich überschnitten
