### ISSUE TITLE
Zigbee ExtPanID, Channel, Transport Key not included

### ISSUE THREAD

**Issue by HansBorjes** [simatec/ioBroker.backitup#305]
I had to uninstall zigbee, re-install and restore zigbee network from backup.

It seems that ExtPanID, Channel, Transport Key are not included in the backup. For users that do not store these data separately it makes the backup pointless.

After restore the devices are there but no connections.

Please include these important data. If you have security concerns: ask the user whether it shall be included in the backup or user wants to keep the keys separately. (If not remembered the ExtPanID is also kind of a key :-) ).

**Comment by simatec** [comment]
the adapter settings of the Zigbee adapter are included in the standard iobroker backup and not in the backup of the zigbee database.  If you have to delete an adapter and then want to reinstall it, you can save the config manually beforehand.
