### ISSUE TITLE
Wiederherstellen im Docker

### ISSUE THREAD

**Issue by stsch83** [simatec/ioBroker.backitup#307]
aktuell kann man scheinbar kein Backup von einen RPI im Docker Container von buanet wieder einspielen. Gibt es evtl. eine Möglichkeit das von Hand zu machen oder hab ich jetzt pech gehabt. Hab Backups aber kann sie nicht einspielen?!?!!?

**Comment by simatec** [comment]
Warum sollte docker nicht funktionieren? Lege den Standard Backup Ordner an und lege dort deine Backups ab.
Danach kannst du entweder manuell über Konsole oder über das WebIf von Backitup die Wiederherstellung durchführen.

https://forum.iobroker.net/topic/27271/howto-iobroker-restore-unter-linux-durchf%C3%BChren
