### ISSUE TITLE
SMB1 wird nicht verwendet

### ISSUE THREAD

**Issue by Marty56** [simatec/ioBroker.backitup#308]
Ich habe noch eine alte TimeCapsule, die leider nur SMB1 kann.
Mit Debian 10 scheint minSMB auf SMB2 zu stehen, was ja auch ok ist.

Wenn ich die SMB1 Option anwähle, kann sich backitup nicht mit einem SMB1 Server verbinden, weil in dem von Backitup abgesetzten mount Befehl die Option, vers=1.0, fehlt.

Es wäre schön, wenn die hinzugefügt würde.

**Comment by simatec** [comment]
Was genau bringt dich zu der Annahme, dass backitup die SMB Version nicht setzt?
Bitte poste dem dementsprechenden Log dazu.

**Comment by Marty56** [comment]
Ich sehe das im Error Log wo der mount Befehl ohne vers=1.0 abgesetzt wird.
Wenn ich den Mount Befehl, den backitup erzeugt, im Terminal paste bekomme ich eine Fehlermeldung.
Hänge ich dann an den mount Befehl vers=1.0 an funktioniert es.

**Comment by Marty56** [comment]
Ich benutze jetzt einen Worarround. Habe mit fstab ein Verzeichnis gemountet und benutze den Copy Modus beim Nas

**Comment by Marty56** [comment]
Der Fehler scheint nur aufzutauchen, wenn man den "compact" modus aktiviert hat.
Wenn ich den deaktiviere funktioniert es wieder.


  |   |   |  
-- | -- | -- | --
backitup.2 | 2020-05-27 11:04:11.852 | error | mount: /opt/iobroker/backups: mount(2) system call failed: Der Rechner ist nicht aktiv.
backitup.2 | 2020-05-27 11:04:11.852 | error | (COMPACT) Error: Command failed: sudo mount -t cifs -o username=xxxxxx,password='xxxxxxxxx',rw,file_mode=0777,dir_mode=0777 //192.168.10.108/martin/Backups/Homeautomation/Muenchen/iobroker/ /op
backitup.2 | 2020-05-27 11:04:11.576 | info | (COMPACT) [ccu] backup was activated at 01:30 every 3 day(s)
backitup.2 | 2020-05-27 11:04:11.562 | info | (COMPACT) [iobroker] backup was activated at 02:00 every 1 day(s)
backitup.2 | 2020-05-27 11:04:11.532 | info | (COMPACT) starting. Version 1.5.8 in /opt/iobroker/node_modules/iobroker.backitup, node: v12.16.3, js-controller: 3.1.4

**Comment by simatec** [comment]
Stelle den Log mal auf debug, dann sieht man erwas mehr

**Comment by Marty56** [comment]
Seltsam. Ich kann das Verhalten nicht mehr so richtig nachstellen.

Was ich gemacht habe.
1. debug level eingestellt.
2. den compact modus ausgeschaltet
3. den compact modus eingeschaltet.

Der Adapter konnte jetzt mounten und macht auch das Backup.
Er ist aber bei der Umschalterei ziemlich heftig abgestürzt, so dass js-controller neugestartet wurde.

Die Settings im Backitup Adapter habe ich dabei nicht angefasst.
So ganz kapiere ich das nicht.

[backitup.log](https://github.com/simatec/ioBroker.backitup/files/4689355/backitup.log)

**Comment by simatec** [comment]
Das könnte eventuell für den js-controller interessant sein.
Mach da mal bitte ein Issue auf

**Comment by Marty56** [comment]
Ich glaube, dass ist nicht so einfach.

Heute hatte ich wieder einen "PSI" Effekt mit dem Adapter.
Ich habe das Backup der CCU aktiviert und in dem NAS Tab unterschiedliche Pfade für CCU und iobroker angegeben.Der Adapter lief im Compact Modus.

Daraufhin kam wieder der mount Fehler.
Ich habe den Compact Modus deaktiviert. Danach lief der Adapter ohne Probleme.

Vielleicht versuchst Du selber mal eine Config im Adapter zu ändern, während er im Compact Modus ist.

**Comment by Marty56** [comment]
Noch eine Randbedingung, die eine Rolle zu spielen scheint, ist, dass ich zwei backitup Instanzen habe. Heute Nacht hatte ich einen Crash (js-controller Restart). Jetzt habe den Compact Modus von beiden Instanzen deaktiviert. Mal sehn, ob es jetzt stabil läuft

**Comment by simatec** [comment]
Ich kann den Fehler leider nicht nachstellen

**Comment by simatec** [comment]
Grundsätzlich sollte man aber auch die Empfehlungen zur Verwendung des Compact-Modus berücksichtigen. Compact ist zwar für schwache Systeme Resourcenschonend, aber ein Nachteil liegt in der Stabilität.
