### ISSUE TITLE
Feature Request: Integration eines Influx-Datenbak backups

### ISSUE THREAD

**Issue by XxJooO** [simatec/ioBroker.backitup#309]
Hallo zusammen, sicher wurde das schon mal erfragt, finde aber keine Hinweise dazu:

Wenn ein backup der history-Daten und der mySQL-Danbank möglich ist, warum gibt es dann keine Integration eines Influx-Datenbank-Backups?

Vielen Dank

**Comment by simatec** [comment]
Es steht auf der todo. Wird sich auch irgendwann unterstützt werden.

**Comment by HouseFox** [comment]
Hallo simatec, eine "Influx DB" Integration würde ich mir auch wünschen.

Vielen Dank und Gruß

**Comment by simatec** [comment]
Wie sicherst du bisher die Influx DB? Gibt es Möglichkeiten dafür Backups zu machen?
ich nutze Influx selber nicht.

**Comment by XxJooO** [comment]
Ich habe influxDB unter Proxmox installiert und sichere sie damit. Es gibt Linux-Befehle für das Erstellen eines Backups. Da fehlen mir aber die ausreichenden Linux-Kenntnisse mich damit zu beschäftigen. Deshalb bin ich froh, über Proxmox sichern zu können. ioBroker wird auch über Proxmox gesichert. Aber es ist mir lieber, dass der backitup-Adapter hervorragende Arbeit verrichtet. Und ich würde mir wünschen, nicht den kompletten Linux-Balast sichern zu müssen, sondern nur die Datenbank und die Einstellungen. Eben wie bei backitup…

 

Von: simatec <notifications@github.com> 
Gesendet: Dienstag, 16. Juni 2020 12:25
An: simatec/ioBroker.backitup <ioBroker.backitup@noreply.github.com>
Cc: XxJooO <j.urmersbach@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [simatec/ioBroker.backitup] Feature Request: Integration eines Influx-Datenbak backups (#309)

 

Wie sicherst du bisher die Influx DB? Gibt es Möglichkeiten dafür Backups zu machen?
ich nutze Influx selber nicht.

**Comment by Laserlicht** [comment]
Würde mich ebenso über eine richtige Integrierung in den Adapter freuen! 🙂

**Comment by simatec** [comment]
ist in Version 1.8.1 integriert ...
