### ISSUE TITLE
Tasks for release JavaScript Version

### ISSUE THREAD

**Issue by GermanBluefox** [simatec/ioBroker.backitup#31]
Todo: 
- [x] - translate missing texts
- [x] - extend configuration with DeleteOldBackup
- [x] - clean / delete at minimal or total with redis and / or mysql has bugs
- [x] - sleep between the script calls
- [x] - OS Windows: backup type total does not ignore the backup directory when compressing
- [ ] - Analyse errors and tasks in reporters (telegram and history)
- [x] - update documentation

Optional but important:
- [ ] - write tests (at least for cifs)

**Comment by simatec** [comment]
Translate is finish
Config for DelteOldBackup is finish

**Comment by simatec** [comment]
- [ ] - clean / delete at minimal or total with redis and / or mysql has bugs
- [ ] - sleep between the script calls
- [ ] - OS Windows: backup type total does not ignore the backup directory when compressing

**Comment by GermanBluefox** [comment]
What do you mean with "sleep between the script calls" ?

**Comment by simatec** [comment]
It happens from time to time that the next script starts too fast and the other script is still running. This often happens when umount. in this case, the umount fails. so I wanted to put in the loop a sleep of 3-5 seconds

**Comment by GermanBluefox** [comment]
This must be solved with a semaphore/flag. By start of the task the flag is set.
No other task will be started till the flag is true. Just test every 10 seconds if the task could be started

**Comment by GermanBluefox** [comment]
Windows "backups" and "sleep between the script calls" should be fixed

**Comment by simatec** [comment]
backup test for Release

- [ ] - total backup
- [ ] - minimal backup
- [ ] - mysql backup
- [ ] - Redis backup
- [ ] - CCU backup
- [ ] - FTP
- [ ] - CIFS
- [ ] - NFS
- [ ] - path copy
- [ ] - clean FTP
- [ ] - clean CIFS
- [ ] - clean NFS
- [ ] - clean copy path
- [ ] - clean local

**Comment by simatec** [comment]
Restore test for Release

- [ ] - total restore
- [ ] - minimal restore
- [ ] - mysql restore
- [ ] - Redis restore
- [ ] - FTP list
- [ ] - CIFS list
- [ ] - NFS list
- [ ] - copy path list
- [ ] - local list

**Comment by simatec** [comment]
@Germanbluefox

We have few of Bugs:

- Restore: umount for nfs or cifs is not working
- iobroker stop for total backup on Windows und Linux is not working (iobroker is stop but not created a backup and not restart after backup)

**Comment by simatec** [comment]
Iobroker stop for total backup is working now
