### ISSUE TITLE
Warnmeldunge

### ISSUE THREAD

**Issue by Pocky2507** [simatec/ioBroker.backitup#311]
Kann mir jemand erklären was das für Warnmeldungen sind?
Es sind alle Instanzen (bis auf admin.1) installiert die er hier anmeckert.

`
host.rockpro64	2020-06-05 10:34:44.697	warn	Objects 127.0.0.1:46242 Error from InMemDB: Error: ERROR readDir id=web.0: Not exists
host.rockpro64	2020-06-05 10:34:44.696	warn	Objects 127.0.0.1:46242 Error from InMemDB: Error: ERROR readDir id=enigma2.5: Not exists
host.rockpro64	2020-06-05 10:34:44.696	warn	Objects 127.0.0.1:46242 Error from InMemDB: Error: ERROR readDir id=enigma2.4: Not exists
host.rockpro64	2020-06-05 10:34:44.695	warn	Objects 127.0.0.1:46242 Error from InMemDB: Error: ERROR readDir id=enigma2.3: Not exists
host.rockpro64	2020-06-05 10:34:44.695	warn	Objects 127.0.0.1:46242 Error from InMemDB: Error: ERROR readDir id=enigma2.2: Not exists
host.rockpro64	2020-06-05 10:34:44.695	warn	Objects 127.0.0.1:46242 Error from InMemDB: Error: ERROR readDir id=enigma2.1: Not exists
host.rockpro64	2020-06-05 10:34:44.694	warn	Objects 127.0.0.1:46242 Error from InMemDB: Error: ERROR readDir id=enigma2.0: Not exists
host.rockpro64	2020-06-05 10:34:44.693	warn	Objects 127.0.0.1:46242 Error from InMemDB: Error: ERROR readDir id=admin.1: Not exists
host.rockpro64	2020-06-05 10:34:44.693	warn	Objects 127.0.0.1:46242 Error from InMemDB: Error: ERROR readDir id=admin.0: Not exists
host.rockpro64	2020-06-05 10:34:44.683	warn	Objects 127.0.0.1:46242 Error from InMemDB: Error: ERROR readDir id=0_userdata.0: Not exists`

**Comment by simatec** [comment]
Bitte Issue im richtigen Adapter aufmachen
