### ISSUE TITLE
Milestones verwenden

### ISSUE THREAD

**Issue by Sacred-Shadow** [simatec/ioBroker.backitup#312]
Hey,

es wäre cool wenn hier im Projekt die Milestones verwendet würden.
Bei vielen Sachen gab es die Antwort, dass es auf der Todo Liste steht.

Mit den Milestones könnte man das ein wenig sehen und auch "planen".

**Comment by simatec** [comment]
Werde ich drüber nachdenken ...
Unabhängig davon ist es aber unser aller Hobby
