### ISSUE TITLE
Grafana Integration

### ISSUE THREAD

**Issue by HouseFox** [simatec/ioBroker.backitup#313]
Hallo simatec, ist es möglich "Grafana" mit auf die todo Liste aufzunehmen? 

Vielen Dank und Gruß

**Comment by simatec** [comment]
Wie sieht denn das Backup von Grafana aus?
Gibt es Backupmöglichkeiten außerhalb der GUI von Grafana?

**Comment by FreunderNacht** [comment]
Ich habe da mal in einem Forum etwas gelesen wie es gehen könnte:

[https://community.grafana.com/t/backup-restore-grafana-server/121](url)

[http://sysadmin-snippets.com/?p=27](url)

Vieleicht hilft das weiter.


Gruß

Freund der Nacht
