### ISSUE TITLE
Please add zwave and zwave2 database backup option

### ISSUE THREAD

**Issue by ChristianGrieger** [simatec/ioBroker.backitup#314]
It would be great to have also zwave and zwave2 adapter backup option.

https://www.npmjs.com/package/iobroker.zwave
https://github.com/AlCalzone/ioBroker.zwave2

Thank you.

**Comment by AlCalzone** [comment]
Z-Wave2 has the following setting in `io-package.json`:
```
"dataFolder": "zwave2.%INSTANCE%",
```
So I think this is already handled.
