### ISSUE TITLE
CIFS SMBMOUNT to Fritzbox NAS with 1.5.8

### ISSUE THREAD

**Issue by jobado1000** [simatec/ioBroker.backitup#317]
Hi there,
tried to mount backup share at Fritzbox NAS. Backitup failed always with mounting so I tried mount manually.
Found out that the SMBoption might be incorrect set in 01-mount.js.

this worked for me:
`sudo mount -t cifs -o username=iobroker,password=*******,rw,file_mode=0777,dir_mode=0777,vers=1.0 //10.10.134.1/fritz.nas/JOBNAS/iobroker /opt/iobroker/backups`

After inserting the **vers=1.0** it worked. Unfortunately you disabled the log output for the first CIFS-Mount command with the SMB-Option so I could not verify what exactly the first mount command looks like. 

`backitup.0 | 2020-07-01 23:12:51.204 | error | mount error(112): Host is down
backitup.0 | 2020-07-01 23:12:51.204 | error | (4839) Error: Command failed: sudo mount -t cifs -o username=iobroker,password=****,rw,file_mode=0777,dir_mode=0777 //10.10.134.1/fritz.nas/JOBNAS/iobroker /opt/iobroker/backups
backitup.0 | 2020-07-01 23:12:50.452 | info | (4839) [iobroker] backup was activated at 02:00 every 1 day(s)`

Found the CIFS Mount for Fritzbox here: [https://www.andwil.de/weblog/linux-fritznas-mounten-cifs](url)

Maybe you can have a look or provide me a code where the log output for the first mount is also printed.
Thanks and best
Jochen

**Comment by simatec** [comment]
Please post your config from Backitup

**Comment by vipdo2k** [comment]
Hi, 
i have solved it in the file 'io-package.json' on line 242.
changed from "smbType": "vers=1.0"  to -> "smb": "vers=1.0" 
now the options.smb can be found and it works

you can also change the files 'lib/scripts/01-mount.js' and 'lib/list/cifs.js'
change the options.smb to options.smbType
this should also solve the problem

**Comment by simatec** [comment]
That is not correct.  the value is transferred here and must not be changed in the io package.  Please do not give such false tips here.

https://github.com/simatec/ioBroker.backitup/blob/35efe5735fade312feabe68e660cf72f1682ecc6/main.js#L430
