### ISSUE TITLE
mySQL Backups werden erstellt, dann gepackt und sind anschließend leer

### ISSUE THREAD

**Issue by tardar** [simatec/ioBroker.backitup#319]
Hi zusammen,

ich habe ein Problem mit dem Adapter.
Ich sichere meine ioBroker Installation, sehe auf dem NAS, wie die SQL Datei (Dump der DB) erstellt und danach gepackt wird.
Versuche ich dann die Datei zu öffnen, ist sie leer.

Sie hat zwar eine entsprechende Dateigröße (20MB9, kann aber nicht geöffnet werden.

Würde mich freuen, wenn da jemand helfen kann - vielleicht eine Fehlfunktion, vielleicht auch etwas anderes.
Ich kann gerne weitere Infos liefern, wenn ihr mehr wissen müsst ;)

Im execute Fenster während des backups steht am Ende des mySQL Backups nur "Done" - also keine Fehlermeldung oder ähnliches.

Danke und viele Grüße
Tardar

**Comment by tardar** [comment]
Anbei eine Meldung vom macOs eigenen Entpacker:
https://www.bilder-upload.eu/bild-562927-1595865650.png.html

Die Dateiinfos:
https://www.bilder-upload.eu/bild-ca866b-1595865885.png.html

Hat da jemand eine Idee ?

Danke Euch und beste Grüße

**Comment by simatec** [comment]
Das ist so korrekt. Es gibt die Datei im Archiv mit einem „Punkt“ als Dateinamen

**Comment by tardar** [comment]
Warum kann die Datei denn nicht geöffnet werden?
Den Ablageort habe ich auf dem NAS.
