### ISSUE TITLE
Pfadangabe bei externer Redis DB?

### ISSUE THREAD

**Issue by manoloxxl** [simatec/ioBroker.backitup#322]
Hi,
ich nutze iobroker sowie Redis in getrennten Docker-Containern. Der Docker-Container kann auf den Rediscontainer entsprechend zugreifen (IP & Port)

Beim sichern von Redis erhalte ich eine Fehlermeldung. Angegeben in Backitup ist der voreingestellte Lokale Pfad.

Über Google konnte ich dazu zwei Lösungen finden:
1) Stell den richtigen Pfad ein
2) konfiguriere die „Remote“ Redis Anbindung gemäß Backitup Doku

In der Doku konnte ich dazu jedoch keinerlei Hinweise finden und weiß leider auch nicht wie genau der Pfad auf die andere IP von Backitup erwartet wird.

Übersehe ich etwas in der Doku? 

Grüße
Manuel

**Comment by simatec** [comment]
Redis kann nur lokal gesichert werden
