### ISSUE TITLE
Benachrichtigungen -> Telegram: Auswahl von Empfängern nicht möglich

### ISSUE THREAD

**Issue by dklinger** [simatec/ioBroker.backitup#326]
Die Auswahlbox "Telegramempfänger" zeigt bei mir keine Namen an, sondern sieht so aus:
![image](https://user-images.githubusercontent.com/2249766/90184839-0b348880-ddb6-11ea-8b1d-487054e2483d.png)

Zuerst dachte ich nur an einen Anzeigefehler, aber bei Auswahl der firstName-Optionen bekommt keiner der beiden User die Benachrichtung.

**Comment by sly-1** [comment]
Bei mir sieht es genau so aus. 
Ursache scheint der fehlende öffentliche Benutzername der Telegram User zu sein. 
Wenn kein öffentlicher Benutzername festgelegt wurde, steht im json Objekt des Telegram Adapters firstName:<Vorname>. 
Im backitup Adapter wird anscheinend genau dieser Teil vom json Objekt für die Empfänger Anzeige/Auswahl verwendet. 
Daher werden nur Nachrichten versendet, wenn "Alle Empfänger" eingestellt wird. 
Wenn einer der firstName Einträge verwendet wird, werden keine Nachrichten versendet. 

Könnt ihr das irgendwie im backitup Adapter korrigieren? 
Mal eben eine öffentlichen Benutzernamen in Telegram festlegen, kann nicht die Lösung sein.

**Comment by simatec** [comment]
Backitup holt sich die Daten vom Telegram Adapter ...
Um genau zu sein aus folgenden Objekt:

`telegram.0.communicate.users`

Also am Ende kann da weder Backitup nichts machen und auch der Telegram Adapter nicht. Konfiguriert bitte Telegram dementsprechend ...

**Comment by sly-1** [comment]
@simatec Danke für deine Rückmeldung. 
Aber kannst du hier evtl. noch einmal helfen? 
Bei mir wird im backitup Adapter noch immer firstName angezeigt. 
Wenn ich einen der firstName Einträge auswähle, wird keine Nachricht gesendet. Der Telegram Adapter meldet Unbekannter Empfänger. 
Wenn ich im Telegram Adapter die Funktion "Username anstatt Vorname von Benutzern speichern" aktiviere, wird im backitup Adapter zusätzlich zu den firstName Einträgen auch der Username angezeigt (dazu muss der User einen öffentlichen Benutzernamen in Telegram definiert haben!). An diesen Empfänger wird dann die Benachrichtigung gesendet. 
Mit der Einstellung "Username anstatt Vorname von Benutzern speichern" im Telegram Adapter funktioniert aber kein Script mehr, in welchen ich Telegram verwende. Da ich in allen den Vornamen als Empfänger verwende. Dies aber nun nicht mehr funktioniert, da ja jetzt der Username gespeichert/verwendet wird. Bedeutet, alle Empfänger müssen eine öffentlichen Benutzernamen festgelegt haben und ich muss alle Skripte anpassen. 
Was stimmt hier nicht bzw. was muss ich ändern, dass backitup nicht firstName anzeigt/verwendet sondern den Vornamen, den auch der Telegram Adapter richtig anzeigt?
