### ISSUE TITLE
iobroker minimal backup will not be put to cifs

### ISSUE THREAD

**Issue by linos22** [simatec/ioBroker.backitup#33]
Hello,

the backups will be created unter /root/backups but the NAS gets mounted under /opt/iobroker/backup.
So the backups remain in the filesystem and will not be pushed to the NAS.
It only affects the minimal backup. the total backup also works fine

![ohne titel](https://user-images.githubusercontent.com/42517601/44310468-090dde00-a3d7-11e8-8085-a9123a5980ea.jpg)

Here you can see the different used paths.

CCU backup and full backup works fine.

Best regards

**Comment by linos22** [comment]
it only affects the minimal backup. the total backup also works fine

**Comment by linos22** [comment]
![ohne titel](https://user-images.githubusercontent.com/42517601/44310468-090dde00-a3d7-11e8-8085-a9123a5980ea.jpg)

Here you can see the different used paths

**Comment by simatec** [comment]
Fix in newer Version
