### ISSUE TITLE
Please add included zwave devices backup

### ISSUE THREAD

**Issue by jolichter** [simatec/ioBroker.backitup#332]
The zwave devices are only linked in iobroker and a backup of all included devices is only possible via [z-wave.me](https://z-wave.me/) (as far as I know). Is it possible that you include this?

Thanks Jo

**Comment by jolichter** [comment]
OK, no one cares.

**Comment by simatec** [comment]
zwave is already part of iobroker backup

**Comment by jolichter** [comment]
Sorry, maybe a misunderstanding?
 
The list of devices and their relationships in the network, are stored inside the Z-Wave transceiver chip and therefore cannot be easily read out and restored with normal smart home gateways like ioBroker.

I can only find the data from the new zwave2 adapter and its cache files in the backup:
![screenshot_ioBroker_backup](https://user-images.githubusercontent.com/1485851/120704846-60fa2e80-c4b7-11eb-9858-f84727b3571b.jpg)

Therefore, I do it by z-wave.me.
