### ISSUE TITLE
Restore with error

### ISSUE THREAD

**Issue by simatec** [simatec/ioBroker.backitup#34]
@GermanBluefox 

button "Get list" with error ...

backitup.1 | 2018-08-19 21:11:02.124 | error | at RedisClient.emit (events.js:217:7)
-- | -- | -- | --
backitup.1 | 2018-08-19 21:11:02.124 | error | at emitThree (events.js:136:13)
backitup.1 | 2018-08-19 21:11:02.124 | error | at RedisClient.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:598:25)
backitup.1 | 2018-08-19 21:11:02.124 | error | at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3400:34)
backitup.1 | 2018-08-19 21:11:02.124 | error | at Adapter.emit (events.js:211:7)
backitup.1 | 2018-08-19 21:11:02.124 | error | at emitOne (events.js:116:13)
backitup.1 | 2018-08-19 21:11:02.124 | error | at Adapter.adapter.on.obj (/opt/iobroker/node_modules/iobroker.backitup/main.js:73:17)
backitup.1 | 2018-08-19 21:11:02.124 | error | at module.exports (/opt/iobroker/node_modules/iobroker.backitup/lib/list.js:28:36)
backitup.1 | 2018-08-19 21:11:02.124 | error | at Object.list (/opt/iobroker/node_modules/iobroker.backitup/lib/list/ftp.js:7:9)
backitup.1 | 2018-08-19 21:11:02.124 | error | at setImmediate (timers.js:844:11)
backitup.1 | 2018-08-19 21:11:02.124 | error | TypeError: "callback" argument must be a function
backitup.1 | 2018-08-19 21:11:02.118 | error | pmessage messagebox.system.adapter.backitup.1 {"command":"list","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":102,"ack":false,"time":1534705862108},"_id":69295156} "c

**Comment by GermanBluefox** [comment]
Fixed?

simatec <notifications@github.com> schrieb am So., 19. Aug. 2018, 21:13:

**Comment by simatec** [comment]
after Restart backitup is only this error


backitup.1 | 2018-08-19 22:06:05.796 | debug | sendTo "list" to system.adapter.admin.0 from system.adapter.backitup.1
-- | -- | -- | --
backitup.1 | 2018-08-19 22:06:05.256 | error | Not implemented
backitup.1 | 2018-08-19 22:06:05.249 | error | Not implemented
backitup.1 | 2018-08-19 22:06:05.193 | error | Not implemented

**Comment by simatec** [comment]
Sorry that was my mistake.
I had a pull from the git and then just the adapter upload.

After a restart of the adapter, the error was gone.

I just had to get the list tested.
I had not done more
