### ISSUE TITLE
In Beschreibung fehlt Zigbee Datenbank

### ISSUE THREAD

**Issue by pinguin21** [simatec/ioBroker.backitup#346]
In der Beschreibung DE und EN fehlt was genau der Hacken "Zigbee Datenbank" macht.

![grafik](https://user-images.githubusercontent.com/37812212/94251805-5ef0d080-ff23-11ea-8670-4abe8366583c.png)

**Comment by simatec** [comment]
Sie sichert die Zigbee Geräte Config des Adapters
