### ISSUE TITLE
MySQL "Konfiguration ermitteln" ermittelt falschen Port

### ISSUE THREAD

**Issue by dwm66** [simatec/ioBroker.backitup#35]
Folgende Konfiguration:
- SQL Adapter konfiguriert auf MySQL mit Port 0 (Null), also Standard Port.

Als Standard-Port hat MySQL Port 3306.

In backitup wird aber (durch die "automatische" Konfiguration Port 3307 eingetragen, was natürlich das Backup des SQL Servers fehlschlagen läßt.
=> Kleine Unschönheit :)

CU
Werner

**Comment by simatec** [comment]
Können wir beim Update anpassen. 
Aber du kannst ja auch manuell im Menü den Port ändern
