### ISSUE TITLE
Backup results in 0kb tar.gz

### ISSUE THREAD

**Issue by ThoSt81** [simatec/ioBroker.backitup#352]
**Describe the bug**  
I am running IObroker in Docker and have /opt/iobroker bound to a folder on my docker host. This folder is an NFS mount on my NAS.
Everything is working fine but when running a backup with "backitup" I can see the file being created (2MB, /opt/iobroker/backups) and then packed into the final *_backupiobroker.tar.gz which is 0kb and not useable/corrupt.

I can create a backup to the same folder by executing "iobroker backup" inside the container.
The resulting tar.gz. is created in /opt/iobroker/backups just fine and can be used normally.

I cannot figure out why backitup is having issues. The log does not show any errors with permissions etc.

**Comment by simatec** [comment]
Bitte mal im Forum nach Lösungen für den Einsatz von iobroker im Docker fragen bzw. suchen

**Comment by ThoSt81** [comment]
Hat sich erledigt. Nach erneuter Installation geht es nun. Grund: unbekannt.
