### ISSUE TITLE
Unmount network drive after backup finished

### ISSUE THREAD

**Issue by Koalabaer** [simatec/ioBroker.backitup#353]
**Is your feature request related to a problem? Please describe.**
My NAS (Synology DS218) dont go sleep again because the network drive is still mapped (i guess) and in general it would be a great feature to unmount the network drive after the backup finished.

**Describe the solution you'd like**
After the update has finished or it wasnt working (doesnt matter) - just when the process finished unmount the network drive. Just a checkbox next to the mount option.

**Describe alternatives you've considered**
no alternatives

**Additional context**
no further context needed

Thanks

Koala

**Comment by simatec** [comment]
Backitup für immer einen umount nach Abschluss des Backups aus. Hier liegt sicher ein Fehler in deinem System vor

**Comment by Koalabaer** [comment]
Hi, mittlerweile funktioniert es auch wie es soll - danke dennoch! (habe aber ehrlich gesagt nichts bewusst geändert...)
