### ISSUE TITLE
CCU Backup Google Drive not possible

### ISSUE THREAD

**Issue by cribito79** [simatec/ioBroker.backitup#354]
Erstellen eines CCU / Raspberrymatic Backups auf Google Drive wird nicht durchgeführt. Ein ioBroker  Backup wird manuell tadellos erstellt. Automatisch leider nicht.

What can I do?

![Bildschirmfoto von 2020-10-22 23-12-25](https://user-images.githubusercontent.com/73363015/97045172-916b0900-1575-11eb-8599-02c69fc9bba2.png)

**Comment by meistermopper** [comment]
Das ging mir letzte Nach ebenso. Offenbar vergisst der Adapter bei dem Update auf 1.7.0 das Kennwort. Ich habe es neu gesetzt, und es funktioniert wieder.
