### ISSUE TITLE
Error: Maximum number of tries exceeded. Please contact the site manager.

### ISSUE THREAD

**Issue by simone1999** [simatec/ioBroker.backitup#357]
Hi,
I'm using the backitup Adapter with a remote FTP server.
On Backup the Backup is generated but when the Backup should be uploaded via ftp the following error gets thrown:

Error: Maximum number of tries exceeded. Please contact the site manager.

I'm using version 1.6.7 but the same error also got thrown in 1.4.5.

Thanks for the great Adapter!

**Comment by simatec** [comment]
This is a problem from your ftp-server
