### ISSUE TITLE
beta versionen lassen sich nicht upgraden

### ISSUE THREAD

**Issue by udochrist** [simatec/ioBroker.backitup#366]
**Describe the bug**  
laut adapter screen steht ein update an. beim updaten ist dann aber bereits angeblich alles up2date.
ich vermute es liegt an der versionsnummer. ich glaube hier sollte besser 1.8.X anstelle 1.8.0-betaX verwendet werden.

**To Reproduce**  
upgradeversuch über die adapter liste

**Expected behavior**  
version wird aktualisiert

**Screenshots & Logfiles**  
![Bildschirmfoto 2020-12-06 um 17 11 06](https://user-images.githubusercontent.com/869637/101285666-bbefe900-37e6-11eb-9b12-1339be4d5aae.png)
![Bildschirmfoto 2020-12-06 um 17 11 38](https://user-images.githubusercontent.com/869637/101285672-c14d3380-37e6-11eb-910a-faf516e7973e.png)

**Versions:**  
 - Adapter version: 1.8.0-beta1
 - JS-Controller version: 3.1.6
 - Node version: 12.19.0
 - Operating system: alpine

**Additional context**  
iobroker info-adapter zeigt an das alles up2date ist, adapter-liste zeigt ein upgrade (siehe screenshot)

**Comment by simatec** [comment]
Liegt am admin und kann leider nicht durch Backitup behoben werden. Die nächsten Tage kommt die 1.8.1 ... damit ist es kein Problem mehr
