### ISSUE TITLE
bug: say backup is ok, but nothing copied..

### ISSUE THREAD

**Issue by Ilovegym66** [simatec/ioBroker.backitup#37]
Hi, at first, it's a real great Idea to implement the backup/restore functions for the database etc in the adapters!

I found a big Bug, because I've maintenance on my NAS, is was down a night, and the Adapter send me a telegram message with "backup completed... " but nothing transfered! 
I can't found the file on the local iobroker ( Linux Mint 18.3 in proxmox, npm 6.4 node 8.11.4 ) and on the powered-off NAS is it definitely not.. :-) 
In the logfile is from iobroker is nothing, no error or something else.. 
Setup for the Backup was minimal backup of the system, transfer method is ftp.
Now I've upgraded my NAS and switched to CIFS, works fine. 
Check this, please, you can reproduce the fault, if you set an wrong path, and the system can't copy the file, but telegram send a message with backup completed...

**Comment by simatec** [comment]
What version do you use?
