### ISSUE TITLE
Wunsch: Sicherung von SD-Karte (Raspberry Pi)

### ISSUE THREAD

**Issue by Kusi-Schweiz** [simatec/ioBroker.backitup#371]
Ist es möglich eine Integration zu erstellen, womit zusätzlich zum ioBroker-Backup auch ein Backup der gesamten SD-Karte vom Raspberry Pi erstellt werden kann?

**Comment by simatec** [comment]
Das ist nicht das Konzept von Backitup. 
Backitup arbeitet Plattformübergreifend und ist für die Sicherung deines iobrokers und deiner dazugehörigen Datenbanken etc. zuständig. 
Für das sichern der kompletten SD eines Raspberrys gibt es im Netz aber jeder Menge Tools, die man per Cronjob automatisieren kann.
