### ISSUE TITLE
Where ist the backup files stored?

### ISSUE THREAD

**Issue by Matt77CHE** [simatec/ioBroker.backitup#373]
Hi there

i would like to restore my iobroker...
I've installed iobroker with docker on my synology nas.
Backitup guide says the backup should be located at opt/iobroker/backups/....
But where can I find this path? - where do i have to look for it?
In the iobroker objects? somewhere on my nas?
I also would have to copy my backup into this folder...
I was trying now somehow to restore my iobroker for hours and nothing worked so far (backup from google drive, from a file located on my nas...)
need serious help...

what I did so far is to reinstall docker & iobroker on my nas; setting up basics from iobroker and installed backitup adapter...

regards
Matt

**Comment by Matt77CHE** [comment]
... when I try to restore it from google drive, it opens a new window with port 8091.... why t.f. 8091?;
I changed port of iobroker to 8091 (instead of 8081) and getting then : Cannot GET /backitup-restore

**Comment by simatec** [comment]
Please read the doku from backitup and the restore from iobroker

**Comment by Matt77CHE** [comment]
Thank you;
But I now still do not know where I can find the folder opt/iobroker/backups/
or where I should create it....

**Comment by simatec** [comment]
The folder is in the main directory.  In which path is your iobroker installation located?

**Comment by Matt77CHE** [comment]
I've installed it with docker on my synology nas

**Comment by simatec** [comment]
please try to clarify your problem in the forum.  Your problem has nothing to do with backitup

**Comment by Matt77CHE** [comment]
so then the "Cannot GET /backitup-restore" is not a backitup problem?

**Comment by simatec** [comment]
Yes ... it is a Problem with Ports in the Docker
