### ISSUE TITLE
Add setup menue for back up folders from filesystem , which can be named in the config area of this adapter

### ISSUE THREAD

**Issue by smartboart** [simatec/ioBroker.backitup#374]
Hello,
i am using several folders on my iobroker machine for storing / download files or json lists. 
I would like to back up this folders also with this powerfull nice apapter. 
Maybe it is possible to add some coniguration points in the setup menue to name some folders somebody would like to backup too.

**Comment by simatec** [comment]
you can use the history backup or the redis backup, for example.  folders are backed up in both variants.

**Comment by smartboart** [comment]
oh yes. Many thanks for this usefull idea..that works for me... I already use redis, but the history setting i can use for this...Is there a way to backup more folders? For the moment one is enough, but later maybe i need some more...
