### ISSUE TITLE
Wiederherstellung aus Dropnox funktioniert nicht

### ISSUE THREAD

**Issue by Sundancer78** [simatec/ioBroker.backitup#375]
Bei dem Versuch ein Backup aus der Dropbox wiederherzustellen kam diese Fehlermeldung:

Log Backitup Restore:
======================

[DEBUG] [iobroker] Start ioBroker Restore ...
[ERROR] [iobroker] host.iobroker-pi Cannot extract from file "/opt/iobroker/backups/iobroker_2020_12_21-22_34_37_backupiobroker.tar.gz"
[DEBUG] [iobroker] ioBroker Restore completed successfully
[EXIT] 9 **** Restore completed successfully!! ****

The log can be closed ...

Die Sicherung wurde fehlerfrei erstellt und in der Dropbox gespeichert, die Backupdatei hat eine Größe von 2,3 MB und lässt sich auch herunterladen.

Lokal im ioBroker Backup- Verzeichnis, ist die Backupdatei nur 90 byte groß. Ich nehme mal an, dass das Backup vor dem rücksichern aus der Dropbox lokal gespeichert wird?!

**Comment by simatec** [comment]
Wie in dem Howto von mir geschrieben, rate ich den Restore lokal auszuführen. 
Lege die Backupdatei lokal ab und wiederhole den Restore. 
sollte auch dort ein Fehler auftreten, führe den Restore mal über die Konsole aus und poste bitte den Log. 

`iobroker restore <backupname>`
