### ISSUE TITLE
Dedicated support for ioBroker.jarvis

### ISSUE THREAD

**Issue by Zefau** [simatec/ioBroker.backitup#377]
**Is your feature request related to a problem? Please describe.**
The Feature request is not related to a problem.

**Describe the solution you'd like**
I would like to kindly ask if you could consider a dedicated backup for ioBroker.jarvis within ioBroker.backitup. At the moment the jarvis adapter creates 4 json files in `/opt/iobroker/iobroker-data/files/jarvis` (probably more in future, but always `.json` files):

- `_BACKUP_DEVICES.json`
- `_BACKUP_LAYOUT.json`
- `_BACKUP_SETTINGS.json`
- `_BACKUP_STYLES.json`

I would appreciate if these files could be included in the backup routines of ioBroker.backitup. They only need to be copied from the given path (respectively copied back in case of a restore).

**Describe alternatives you've considered**
The alternative for me would a backup routine for these files within ioBroker.jarvis, which I would like to avoid, because I need to add FTP / Dropbox / etc. functionalities, which is not the core of what jarvis is.

**Additional context**
The feature request of ioBroker.jarvis may be found here: https://github.com/Zefau/ioBroker.jarvis/issues/478

**Comment by simatec** [comment]
that shouldn't be a problem and I can take it with me on the todo.  Are there only files with the extension .json in the path?

**Comment by Zefau** [comment]
No, the path contains the jarvis compiled build version (= jarvis installation) and the root folders contains more `json` files (not only the backup files). Though, all relevant files will always start with `_BACKUP_`.

Thanks in advanced!

**Comment by simatec** [comment]
OK thats is not a Problem.

**Comment by simatec** [comment]
I've looked at the whole thing. The path "/opt/iobroker/iobroker-data/files/jarvis" does not exist for me. 
My Devsystem is "redis/redis".
So it looks like you have to look again where you put the backups. If the objects are not "file", they will be written in redis.

**Comment by Zefau** [comment]
Ok, danke für die Info. Habe selbst redis nur für States im Einsatz, nicht für Objekte. Da muss ich nochmal in der Community nachhaken, ob die Backups dann überhaupt bei einem Update verloren gehen.

**Comment by simatec** [comment]
Eine Möglichkeit wäre noch, die eventuell in einen separaten Ordner zu schreiben. 
Aktuell könnte ich nur die states für layout, devices usw. auslesen. Aber das wären dann ja nicht die kompletten Backups sondern nur die aktuellen states

**Comment by Zefau** [comment]
Jo, das wäre nur eine Momentaufnahme.

Existiert denn `/opt/iobroker/iobroker-data/files` und nur der jarvis Ordner fehlt oder existiert der gesamte `iobroker-data` Pfad nicht?

**Comment by simatec** [comment]
Der Ordner files existiert. Habes es mal auf meinen Systemen mit jarvis verglichen. Leider läuft überall redis

**Comment by Zefau** [comment]
Laut Apollon77 kannst du (scheinbar) mittels `readFile` unabhängig davon ob es als Datei oder im redis liegt darauf zugreifen:

```js
adapter.readFile('jarvis', '_BACKUP_LAYOUT.json', null, (err, contents) => { ... });
```

So ich lese ich die Konfiguration ebenfalls ein:

https://github.com/Zefau/ioBroker.jarvis/blob/1811e92d5dea02b6005e472f8b0e17d3750e7d7d/jarvis.js#L83

![image](https://user-images.githubusercontent.com/14368811/103684130-5c266280-4f8b-11eb-975b-0b4aa13193ee.png)

**Comment by Zefau** [comment]
;-)

![image](https://user-images.githubusercontent.com/14368811/103684220-86782000-4f8b-11eb-9f5b-80e5985fcd6b.png)

**Comment by simatec** [comment]
OK schaue ich mal an. WriteFile müsste ja dann im Umkehrschluss auch für den Restore möglich sein.

**Comment by Zefau** [comment]
Jo, genau. Damit speichere ich mir das auch weg.

**Comment by simatec** [comment]
Gut ich schaue, wie wir das sauber in Backitup lösen können. Würde aber dann wie alle anderen Optionen mit dem iobroker backup mitgesichert werden. Restore wäre dann einzeln möglich.

**Comment by simatec** [comment]
@Zefau Kannst du mir mal den kompletten Inhalt des Jarvis Ordners posten? Ich überlege, ob ich das Backup eventuell andersherum aufziehe und mit targz alles ignoriere außer die json

**Comment by Zefau** [comment]
Mit `adapter.readDir` würdest du das dann machen?

Ordner sieht so aus:

![image](https://user-images.githubusercontent.com/14368811/103772734-44ea8200-502a-11eb-8c00-6f68a49b3a67.png)

**Comment by simatec** [comment]
hmm hänge da noch ein wenig ... mit readFile bekomme ich die Daten aus dem redis nicht
Eventuell hat da @Apollon77 noch eine Idee ... Ich teste aber mal weiter ...

**Comment by Zefau** [comment]
Werden bei dir denn verfügbare Backups in der Adapterkonfiguration der Instanz angezeigt?

![image](https://user-images.githubusercontent.com/14368811/103775751-cb08c780-502e-11eb-911b-c13b9c556b74.png)

**Comment by simatec** [comment]
ja hab einige Backups drin

![image](https://user-images.githubusercontent.com/39792461/103776533-ddcfcc00-502f-11eb-88ac-7b364a47e3d5.png)

**Comment by Zefau** [comment]
Also wenn die Liste so trotz der Verwendung von redis für Objekte bei dir verfügbar ist, dann funktioniert zumindest `adapter.readFile` (https://github.com/Zefau/ioBroker.jarvis/blob/1811e92d5dea02b6005e472f8b0e17d3750e7d7d/jarvis.js#L83).

Kann mir sonst vorstellen, dass du aus deinem Adapter heraus nicht auf den Namespace von jarvis zugreifen darfst?

**Comment by simatec** [comment]
hab erstmal dazu was im Javascript gebaut um zu testen. Daran könnte es liegen. Eventuell können wir dazu einfach mal in Discord uns treffen und gemeinsam mal schauen, wie wir das lösen

**Comment by simatec** [comment]
@Zefau Kannst du mir mal bitte den Inhalt der Backupdateien zeigen? Ich bin nun ein Stück weiter und kann die Dateien auslesen.
Möchte nur mal den Inhalt vergleichen, ob alles sauber ausgelesen wird, da mir der Inhalt etwas komisch ausschaut

**Comment by Zefau** [comment]
Die Inhalte sehen strukturell so aus wie die Datenpunkte `jarvis.0.layout`, `jarvis.0.settings`, bzw. `jarvis.0.layout`. Also eine JSON Struktur mit deinen Daten. Außer `jarvis.0.css`. Das ist normal Text.

**Comment by simatec** [comment]
OK ich habe im Backup einige Backshlash ... Bin mir da unsicher zwecks der Formatierung.
Kannst du mal testen ... Aktuell nur das Backup. Restore fehlt noch. Aber da du ja kein Redis nutzt, könntest du ja Testweise den Inhalt des Backups zurück kopieren und schauen, ob die Dateien sauber sind

Änderungen liegen auf dem DEV Branch
https://github.com/simatec/ioBroker.backitup/tarball/dev

**Comment by simatec** [comment]
Ab Version 1.8.4 verfügbar ...
