### ISSUE TITLE
Automatic upload to dropbox not possible

### ISSUE THREAD

**Issue by chierdie** [simatec/ioBroker.backitup#378]
The backup it created successfully according to the history log:

`[{"date":"31. Dezember 2020 um 04:00 Uhr","name":"iobroker_2020_12_31-04_00_10_backupiobroker.tar.gz","type":"iobroker","storage":"Dropbox: Ja","filesize":"1MB","error":"none"},
{"date":"30. Dezember 2020 um 10:36 Uhr","name":"iobroker_2020_12_30-10_36_23_backupiobroker.tar.gz","type":"iobroker","storage":"Dropbox: Ja","filesize":"1MB","error":"none"},
{"date":"30. Dezember 2020 um 04:00 Uhr","name":"iobroker_2020_12_30-04_00_10_backupiobroker.tar.gz","type":"iobroker","storage":"Dropbox: Ja","filesize":"1MB","error":"none"},
{"date":"29. Dezember 2020 um 10:17 Uhr","name":"iobroker_2020_12_29-10_17_03_backupiobroker.tar.gz","type":"iobroker","storage":"Dropbox: Ja","filesize":"1MB","error":"none"},
{"date":"29. Dezember 2020 um 10:15 Uhr","name":"iobroker_2020_12_29-10_15_13__Backup_backupiobroker.tar.gz","type":"iobroker","storage":"Dropbox: Ja","filesize":"1MB","error":"none"},
{"date":"29. Dezember 2020 um 09:41 Uhr","name":"iobroker_2020_12_29-09_41_19__Backup_backupiobroker.tar.gz","type":"iobroker","storage":"Dropbox: Ja","filesize":"1MB","error":"none"},
{"date":"29. Dezember 2020 um 09:39 Uhr","name":"iobroker_2020_12_29-09_39_38__Backup_backupiobroker.tar.gz","type":"iobroker","storage":"Dropbox: Ja","filesize":"1MB","error":"none"},
{"date":"29. Dezember 2020 um 02:00 Uhr","name":"iobroker_2020_12_29-02_00_10_backupiobroker.tar.gz","type":"iobroker","storage":"Dropbox: Ja","filesize":"1MB","error":"none"},
{"date":"28. Dezember 2020 um 14:44 Uhr","name":"iobroker_2020_12_28-14_44_50_backupiobroker.tar.gz","type":"iobroker","storage":"Dropbox: Ja","filesize":"1MB","error":"none"},
{"date":"28. Dezember 2020 um 14:43 Uhr","name":"iobroker_2020_12_28-14_43_17_backupiobroker.tar.gz","type":"iobroker","storage":"Dropbox: Ja","filesize":"1MB","error":"none"},
{"date":"28. Dezember 2020 um 14:40 Uhr","name":"iobroker_2020_12_28-14_40_20_backupiobroker.tar.gz","type":"iobroker","storage":"Dropbox: Ja","filesize":"1MB","error":"none"},
{"date":"28. Dezember 2020 um 14:31 Uhr","name":"iobroker_2020_12_28-14_31_09_backupiobroker.tar.gz","type":"iobroker","storage":"Dropbox: Ja","filesize":"1MB","error":"none"},
{"date":"28. Dezember 2020 um 14:24 Uhr","name":"iobroker_2020_12_28-14_24_46_backupiobroker.tar.gz","type":"iobroker","storage":"Dropbox: Ja","filesize":"1MB","error":"none"}]`

but only the manual executed backups via "Jetzt sichern" button are saved to the dropbox folder. The settings to generate the backup automatically every night at 04.00 starting at 2020_12_30 are not working and the backup is not saved to the dropbox folder.

**Comment by simatec** [comment]
In deiner angehängten json sehe ich keinen Fehler

**Comment by simatec** [comment]
Bitte den Log vom Backupprozess hier posten
