### ISSUE TITLE
Backup/Restore Grafana Dashboards

### ISSUE THREAD

**Issue by quorle** [simatec/ioBroker.backitup#379]
**Describe the solution you'd like**

Mittels Konsole kann man für Grafana ein Backup der Dashboards realisieren. Dies muss mit einem Script erledigt werden. Da dieser Adapter ja eigentlich schon alles vereint, was man an Backup´s machen kann, sollte diese Option eventuell mit in den Adapter gepackt werden. 
Bei einem Ausfall des Systemes von Grafana, könnte man somit, alle Dashboards widerherstellen und müsste nicht alle Dashboards neu konfigurieren und gestalten.

Hier einmal drei Wege, um Backups zu erzeugen:

1. https://www.neteye-blog.com/2018/12/how-to-back-up-all-of-your-grafana-dashboards/
2. http://cactusprojects.com/backup-restore-grafana/
3. https://www.bachmann-lan.de/grafana-backup-dashboards-data-sources/

Ich hoffe dies wird implementiert werden.

**Comment by simatec** [comment]
Ich sehe ein Grafana Backup nicht so richtig in Backitup. Backitup arbeitet ja Plattformübergreifend und wenn Grafana nicht auf dem gleichen System läuft, dann wäre ein Backup nur über ssh Umwege möglich. 
Es gibt zwar Möglichkeiten ssh in Backitup einzubinden, aber ich bin mir da zwecks Userfreundlichkeit und Handling des Adapters unsicher. 

Ein Backup wäre also nur möglich, wenn Grafana auf dem gleichen System läuft.
