### ISSUE TITLE
Test influx backup with 1.8.3 (Windows)

### ISSUE THREAD

**Issue by ente34** [simatec/ioBroker.backitup#380]
**Describe the bug**  
DEBUG] [influxDB] - Created InfuxDB Backup dir
[DEBUG] [influxDB] - exec: "C:\Program Files\influx\influxdb-1.8.3-1\influxd.exe" backup -portable -database iobroker C:/Program Files/iobroker/SmartHome1/backups/influxDB_2021_01_03-16_19_01_backupiobroker
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[ERROR] [influxDB] - [IGNORED] Error: Command failed: "C:\Program Files\influx\influxdb-1.8.3-1\influxd.exe" backup -portable -database iobroker C:/Program Files/iobroker/SmartHome1/backups/influxDB_2021_01_03-16_19_01_backupiobroker
backup: Exactly one backup path is required.

[DEBUG] [clean] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[EXIT] 0

1. Missing quotes around backup path with spaces
2. Exit Code is zero although influx backup fails

**To Reproduce**  
1. Manually start backup

**Versions:**  
 - Adapter version: <1.8.3>
 - JS-Controller version: <3.1.6> 
 - Node version: <v12.20.0>
 - Operating system: <Windows 20H2>

**Comment by simatec** [comment]
Take out the quotation marks in the path to influx exe.

**Comment by ente34** [comment]
Thanks for your fast response, but the quotation marks are necessary:

[DEBUG] [iobroker] - done
[DEBUG] [influxDB] - Start infulxDB Backup ...
[DEBUG] [influxDB] - Created InfuxDB Backup dir
[DEBUG] [influxDB] - exec: C:\Program Files\influx\influxdb-1.8.3-1\influxd.exe backup -portable -database iobroker C:/Program Files/iobroker/SmartHome1/backups/influxDB_2021_01_03-17_25_48_backupiobroker
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[ERROR] [influxDB] - [IGNORED] Error: Command failed: C:\Program Files\influx\influxdb-1.8.3-1\influxd.exe backup -portable -database iobroker C:/Program Files/iobroker/SmartHome1/backups/influxDB_2021_01_03-17_25_48_backupiobroker
Der Befehl "C:\Program" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

[DEBUG] [clean] - done
[DEBUG] [email] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[EXIT] 0

**Comment by simatec** [comment]
Your path to the exe is not ok

**Comment by ente34** [comment]
I know, but you told me "Take out the quotation marks in the path to influx exe"
With quotation marks the path to the exe is OK, but the path to the backup not.
Here the output from the command line with both pathes quoted:
c:\Program Files\iobroker\SmartHome1>"C:\Program Files\influx\influxdb-1.8.3-1\influxd.exe" backup -portable -database iobroker "C:/Program Files/iobroker/SmartHome1/backups/influxDB_2021_01_03-17_25_48_backupiobroker"
2021/01/04 08:53:17 backing up metastore to C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\meta.00
2021/01/04 08:53:17 backing up db=iobroker
2021/01/04 08:53:17 backing up db=iobroker rp=autogen shard=808 to C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\iobroker.autogen.00808.00 since 0001-01-01T00:00:00Z
2021/01/04 08:53:17 backing up db=iobroker rp=autogen shard=809 to C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\iobroker.autogen.00809.00 since 0001-01-01T00:00:00Z
2021/01/04 08:53:17 backing up db=iobroker rp=autogen shard=810 to C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\iobroker.autogen.00810.00 since 0001-01-01T00:00:00Z
2021/01/04 08:53:17 backing up db=iobroker rp=autogen shard=811 to C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\iobroker.autogen.00811.00 since 0001-01-01T00:00:00Z
2021/01/04 08:53:17 backing up db=iobroker rp=autogen shard=812 to C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\iobroker.autogen.00812.00 since 0001-01-01T00:00:00Z
2021/01/04 08:53:17 backing up db=iobroker rp=autogen shard=813 to C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\iobroker.autogen.00813.00 since 0001-01-01T00:00:00Z
2021/01/04 08:53:17 backing up db=iobroker rp=autogen shard=814 to C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\iobroker.autogen.00814.00 since 0001-01-01T00:00:00Z
2021/01/04 08:53:17 backing up db=iobroker rp=autogen shard=815 to C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\iobroker.autogen.00815.00 since 0001-01-01T00:00:00Z
2021/01/04 08:53:17 backing up db=iobroker rp=autogen shard=816 to C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\iobroker.autogen.00816.00 since 0001-01-01T00:00:00Z
2021/01/04 08:53:17 backing up db=iobroker rp=autogen shard=817 to C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\iobroker.autogen.00817.00 since 0001-01-01T00:00:00Z
2021/01/04 08:53:17 backing up db=iobroker rp=autogen shard=818 to C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\iobroker.autogen.00818.00 since 0001-01-01T00:00:00Z
2021/01/04 08:53:17 backing up db=iobroker rp=autogen shard=819 to C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\iobroker.autogen.00819.00 since 0001-01-01T00:00:00Z
2021/01/04 08:53:17 backup complete:
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.meta
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.s808.tar.gz
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.s809.tar.gz
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.s810.tar.gz
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.s811.tar.gz
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.s812.tar.gz
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.s813.tar.gz
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.s814.tar.gz
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.s815.tar.gz
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.s816.tar.gz
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.s817.tar.gz
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.s818.tar.gz
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.s819.tar.gz
2021/01/04 08:53:17     C:\Program Files\iobroker\SmartHome1\backups\influxDB_2021_01_03-17_25_48_backupiobroker\20210104T075317Z.manifest
###########################
Here the output with the unquoted backup path (original error message):

c:\Program Files\iobroker\SmartHome1>"C:\Program Files\influx\influxdb-1.8.3-1\influxd.exe" backup -portable -database iobroker C:/Program Files/iobroker/SmartHome1/backups/influxDB_2021_01_03-17_25_48_backupiobroker
backup: Exactly one backup path is required.
###########################
Here the output with both pathes unquoted:

c:\Program Files\iobroker\SmartHome1>C:\Program Files\influx\influxdb-1.8.3-1\influxd.exe backup -portable -database iobroker C:/Program Files/iobroker/SmartHome1/backups/influxDB_2021_01_03-17_25_48_backupiobroker
Der Befehl "C:\Program" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

**Comment by simatec** [comment]
You have a space in “Program Files”. That doesn't work and that's why the path doesn't work that way either

**Comment by ente34** [comment]
Yes, but "c:\program files" it is the usual installation path with windows, right?

c:\Program Files\iobroker\SmartHome1>dir "c:\Program Files"
 Datenträger in Laufwerk C: ist C_DISC_ARBURG_WIN10
 Volumeseriennummer: 26BE-6ECF

 Verzeichnis von c:\Program Files

03.01.2021  16:11    <DIR>          .
03.01.2021  16:11    <DIR>          ..
10.11.2018  11:02    <DIR>          7-Zip
17.01.2020  10:44    <DIR>          AnyBurn
04.12.2020  14:50    <DIR>          Application Verifier
16.08.2020  18:12    <DIR>          Calibre2
07.11.2020  09:24    <DIR>          Common Files
08.06.2018  13:45    <DIR>          CONEXANT
13.04.2020  09:03    <DIR>          DIFX
14.09.2020  18:32    <DIR>          Dolby
07.11.2020  19:32    <DIR>          Git
17.01.2020  16:26    <DIR>          HandBrake
08.06.2018  14:11    <DIR>          IBM
21.11.2020  14:41    <DIR>          influx
14.09.2020  18:28    <DIR>          Intel
07.12.2019  15:51    <DIR>          Internet Explorer
04.12.2020  15:22    <DIR>          iobroker

...

So, what do you suggest?

**Comment by simatec** [comment]
I'll see what I can adapt to this in the code

**Comment by ente34** [comment]
Thanks!
Please don't forget the second point.
I have configured "Notifications only on errors", but I didn't get a notification.

**Comment by simatec** [comment]
Please send a full log from the Backup with iobroker-backup etc.

**Comment by ente34** [comment]
backitup.0	2021-01-05 12:51:00.635	debug	(2500) [iobroker] exec: done
backitup.0	2021-01-05 12:51:00.309	debug	(2500) [iobroker/historyJSON] done
backitup.0	2021-01-05 12:51:00.308	debug	(2500) [iobroker/historyJSON] new history json values created
backitup.0	2021-01-05 12:51:00.153	debug	(2500) [iobroker/historyHTML] done
backitup.0	2021-01-05 12:51:00.152	debug	(2500) [iobroker/historyHTML] new history html values created
backitup.0	2021-01-05 12:50:59.526	debug	(2500) [iobroker/email] done
backitup.0	2021-01-05 12:50:57.361	debug	(2500) [iobroker/clean] done
backitup.0	2021-01-05 12:50:56.416	debug	(2500) [iobroker/influxDB] konnte nicht gefunden werden.
backitup.0	2021-01-05 12:50:56.416	debug	(2500) [iobroker/influxDB] Der Befehl "C:\Program" ist entweder falsch geschrieben oder
backitup.0	2021-01-05 12:50:56.415	debug	(2500) [iobroker/influxDB] [IGNORED] Error: Command failed: C:\Program Files\influx\influxdb-1.8.3-1\influxd.exe backup -portable -database iobroker C:/Program Files/iobroker/SmartHome1/backups/influ
backitup.0	2021-01-05 12:50:56.415	debug	(2500) [iobroker/influxDB] InfluxDB tmp directory was successfully deleted
backitup.0	2021-01-05 12:50:56.413	debug	(2500) [iobroker/influxDB] Try deleting the InfluxDB tmp directory
backitup.0	2021-01-05 12:50:56.370	debug	(2500) [iobroker/influxDB] exec: C:\Program Files\influx\influxdb-1.8.3-1\influxd.exe backup -portable -database iobroker C:/Program Files/iobroker/SmartHome1/backups/influxDB_2021_01_05-12_50_56_bac
backitup.0	2021-01-05 12:50:56.369	debug	(2500) [iobroker/influxDB] Created InfuxDB Backup dir
backitup.0	2021-01-05 12:50:56.362	debug	(2500) [iobroker/influxDB] Start infulxDB Backup ...
backitup.0	2021-01-05 12:50:55.416	debug	(2500) [iobroker/iobroker] done
backitup.0	2021-01-05 12:50:54.382	debug	(2500) [iobroker/iobroker] Backup created: C:\Program Files\iobroker\SmartHome1\backups\iobroker_2021_01_05-12_50_52_backupiobroker.tar.gz
backitup.0	2021-01-05 12:50:53.758	debug	(2500) [iobroker/iobroker] host.NB03490 675 objects saved
backitup.0	2021-01-05 12:50:53.749	debug	(2500) [iobroker/iobroker] host.NB03490 553 states saved

**Comment by simatec** [comment]
Please install from Github Source "https://github.com/simatec/ioBroker.backitup/tarball/dev" an check again

**Comment by ente34** [comment]
With restore is the same problem:

======================
Log Backitup Restore:
======================

[DEBUG] [influxDB] tmpDir: C:/Program Files/iobroker/SmartHome1/backups/influxDBtmp
[DEBUG] [influxDB] Created tmp directory
[DEBUG] [influxDB] Start infuxDB Restore ...
[ERROR] [influxDB] Der Befehl "C:\Program" ist entweder falsch geschrieben oder
[ERROR] [influxDB] konnte nicht gefunden werden.
[DEBUG] [influxDB] Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] InfluxDB tmp directory was successfully deleted
[DEBUG] [influxDB] infuxDB Restore completed successfully
[EXIT] influxDB restore done **** Restore completed successfully!! ****

The log can be closed ...

**Comment by simatec** [comment]
Restore is not fixed

**Comment by ente34** [comment]
Could you please fix the error notifications (note: missing with sql and postgreSql too):
`			//FIX1
			**options.context.errors.influxDB = error.toString();**
			callback(error, stderr);
			callback = null;
		} else {
			let timer = setInterval(() => {
				if (fs.existsSync(fileName)) {
					const stats = fs.statSync(fileName);
					const fileSize = Math.floor(stats.size / (1024 * 1024));
					log.debug('Packed ' + fileSize + 'MB so far...');
				}
			}, 10000);

			targz.compress({
				src: `${tmpDir}xxx`,
				dest: fileName,
			}, (err, stdout, stderr) => {

				clearInterval(timer);

				if (err) {
					//FIX2
					**options.context.errors.influxDB = err.toString();**
					if (callback) {
						callback(err, stderr);
						callback = null;
`
