### ISSUE TITLE
History Daten mit Umlauten nicht im Backupfile

### ISSUE THREAD

**Issue by tobi119** [simatec/ioBroker.backitup#382]
Bin per Zufall darauf gestoßen, dass im History Backup "historyDB_2021_01_04-02_00_18_backupiobroker.tar.gz" alle Dateien mit Umlauten im Datei-Namen fehlen.
Z.B. zum Datenpinkt "0_userdata.0.WW-Wärmepumpe.Verbrauch"
in History-Verzeichnis des RPi4 sind sie vorhanden: "history.0_userdata.0.WW-Wärmepumpe.Verbrauch.json"

Adapter Version: 1.7.0

**Comment by simatec** [comment]
Umlaute sind in Dateinamen oder bzw. In Objekten nie ratsam

**Comment by tobi119** [comment]
Ja - ist mir klar geworden!
Habe leider schon 2 Monate Daten
Ist also die Frage, ob ich umbauen muss oder ob dies eine nächste Version des Adapters unterstützen kann.
Danke

**Comment by simatec** [comment]
Ich kann es versuchen, aber nodejs mag das mit dem Umlauten leider auch nicht so

**Comment by tobi119** [comment]
Hatte bisher an keiner Stelle Probleme; werde es in Zukunft natürlich vermeiden.

**Comment by tobi119** [comment]
Danke für den Hinweis.
Ja ist ein Problem des Unzippers; mit WinRar ab Version 5.60 sind die Dateien vorhanden.
(getestet mit WinRar 6.0 und tar unter Linux)

Daher mit Dank an alle abgeschlossen.
