### ISSUE TITLE
wake-up for target device

### ISSUE THREAD

**Issue by daniel-lo** [simatec/ioBroker.backitup#39]
I backup to a NAS that is allowed to fall in deep sleep. This NAS is also used for other backups. For those other tools it was necessary to wake up explicitly the target NAS before writing to it. Otherwise the backup failed (probably timeout). How is this managed in backitup script? Maybe it would be a good idea to allow running a script or initiating a command before the backup.

**Comment by simatec** [comment]
Is not planned.
Can not you run a cron on your system that wakes up the NAS before the backup is created?

**Comment by GermanBluefox** [comment]
There is a simple https://github.com/sbmaxx/wake-on-lan package.
@daniel-lo you can extend backitup with PR to support this feature.
The problem is only to wait somehow till the NAS is available on LAN after it waked up.

**Comment by daniel-lo** [comment]
Regrets but WOL didn't work to to successfully start a backup after deep sleep. What I do now is:
/sbin/curl -I http://192.168.178.xx:80
Which works very reliable.
What does "extend with PR" mean?

**Comment by scheilch** [comment]
extend with Pull Request - means you implement that feature and requests a merge of your code into the adapter.
