### ISSUE TITLE
Feature request: Backup mit Nextcloud

### ISSUE THREAD

**Issue by JB1985** [simatec/ioBroker.backitup#391]
Es wäre schön wenn man neben Dropbox und Google Drive auch Nextcloud unterstützen könnte um seine Backup Daten zu transferieren.

Wenn Nextcloud nicht vorhanden ist, biete ich gerne ein Zugang an.

**Comment by simatec** [comment]
Nextcloud ist in Planung und aktuell gerade im Dev Branch

**Comment by JB1985** [comment]
Mal ganz dumm gefragt ... Wie bekomme ich die dev installiert?

**Comment by simatec** [comment]
Über folgende URL kannst du die Beta installieren ..

https://github.com/simatec/ioBroker.backitup/tarball/dev

**Comment by JB1985** [comment]
Will nicht:

Fertig mit Fehler: host.raspberrypi Cannot install https://github.com/simatec/ioBroker.backitup/tarball/dev: 0

**Comment by simatec** [comment]
![image](https://user-images.githubusercontent.com/39792461/104925079-a30a5400-599e-11eb-991d-51fd0fa1c368.png)

![image](https://user-images.githubusercontent.com/39792461/104925150-bd443200-599e-11eb-90b5-4bd9facc3621.png)

![image](https://user-images.githubusercontent.com/39792461/104925213-d3ea8900-599e-11eb-822c-748d5ec131a3.png)

**Comment by JB1985** [comment]
Danke, funktioniert 1a!

[DEBUG] [webdav] - Start WebDAV Upload ...
[DEBUG] [webdav] - WebDAV: Copy iobroker_2021_01_18-15_11_52_backupiobroker.tar.gz...
[DEBUG] [webdav] - WebDAV: Copy redis_2021_01_18-15_12_02_backupiobroker.tar.gz...

**Comment by simatec** [comment]
Ist aber noch nicht final ... der Upload ist aktuell noch zu Ram-lastig und muss noch umgebaut werden.
Gibt aber leider einen Bug im webDAV Packet ...

**Comment by hAMMERlized** [comment]
Moin,

wollte mal fragen, ob die Nextcloud noch realisiert wird? ist immerhin ein Jahr her der letzte Post.

**Comment by simatec** [comment]
Nextcloud wird seit über einem Jahr unterstützt

**Comment by hAMMERlized** [comment]
Sorry. Hab die webDav Option tatsächlich übersehen :/

Funktioniert einwandfrei. Danke 👍🏼
