### ISSUE TITLE
NFS/CIFS - Backup Pfade wählbar Zigbee/InfluxDB

### ISSUE THREAD

**Issue by ToTXR4Y** [simatec/ioBroker.backitup#392]
Hallo,

es wäre prima wenn man (ähnlich wie für ioBroker/CCU Backups) auch einen Pfad für ZigBee/influxDB wählen könnte für das jeweilige Backup.

**Comment by simatec** [comment]
Diese Backups sind Optionen zum eigentlichen iobroker Backup
