### ISSUE TITLE
SQL Bachup schlägt fehl

### ISSUE THREAD

**Issue by Sasch72** [simatec/ioBroker.backitup#393]
Hallo!
Seit ein paar Tagen schlägt das SQL Backup fehl.  Folgende Meldung wird ausgegeben:

[ERROR] [mysql] - [IGNORED] Error: Command failed: mysqldump  -u ioBroker -p**** iobroker -h 192.168.XXX.XX -P 3307 --quick > /opt/iobroker/backups/mysql_2021_01_21-21_03_11_backupiobroker.sql
/bin/sh: 1: mysqldump: not found

Hat jemand eine Idee wo das Problem liegt? Vielen Dank im Voraus!

**Comment by simatec** [comment]
mysqldump muss auf dem System installiert sein.

**Comment by Sasch72** [comment]
Ich glaube das funktioniert nicht. Ich habe ja meine MariaDB 10 auf meiner Synology installiert. Somit kann ich ja eigentlich gar kein Backup machen, da die Daten ja nicht auf dem ioBroker liegen. Sehe ich das richtig?

**Comment by simatec** [comment]
Doch kannst du. Wie gesagt, installiere mysqldump welches im mysql client Packet enthalten ist

**Comment by simatec** [comment]
`sudo apt-get install mysql-client `

**Comment by Sasch72** [comment]
Das Mysql-Client Paket wollte er nicht. Dann habe ich das MariaDB10 Client Paket installiert. Jetzt schein es zu funktionieren....
Danke !
