### ISSUE TITLE
add a option to backup a folder from /opt/iobroker/iobroker-data/

### ISSUE THREAD

**Issue by benjholl** [simatec/ioBroker.backitup#394]
if a backup is restored, the adapter iobroker.yahka will not work. 
In Order to restore the yahka adaper, a backup of the folder "yahka.X.hapdata" in /opt/iobroker/iobroker-data/ is needed as well. 
also see: [iobroker.yahka readme](https://github.com/jensweigele/ioBroker.yahka/blob/master/README.md#backup--restore)

For reasons like this (and maybe some others as well), it would be great having a option to backup any selected folder within the filesystem as archive

**Comment by simatec** [comment]
Du kannst dafür das Backup der History-Daten oder von Scripten nutzen. Bei beiden kann man einen Pfad angeben, der gesichert werden soll.
