### ISSUE TITLE
Wiederherstellen - Liste der Backups erscheint nicht

### ISSUE THREAD

**Issue by mef18** [simatec/ioBroker.backitup#395]
Meine Backups liegen auf einem NAS welches mit SMB gemounted ist.
Der letzte Backup war auch erfolgreich und ich sehe die Files auf dem NAS
Wenn ich auf dem Wiederherstellen Tab Sicherungen abrufen klicker erscheinen keine Backups

Im Debug Log finde ich folgende Meldungen:

backitup.0 | 2021-01-26 08:37:31.891 | debug | (10164) umount successfully completed
-- | -- | -- | --
backitup.0 | 2021-01-26 08:37:29.786 | debug | (10164) mount activ... umount in 2 Seconds!!
backitup.0 | 2021-01-26 08:37:22.125 | debug | (10164) detect last backup file: iobroker_2021_01_26-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.117 | debug | (10164) detect backup file 27: iobroker_2021_01_26-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.115 | debug | (10164) detect backup file 26: iobroker_2021_01_25-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.114 | debug | (10164) detect backup file 25: iobroker_2021_01_24-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.101 | debug | (10164) detect backup file 24: iobroker_2021_01_23-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.100 | debug | (10164) detect backup file 23: iobroker_2021_01_22-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.098 | debug | (10164) detect backup file 22: iobroker_2021_01_21-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.097 | debug | (10164) detect backup file 21: iobroker_2021_01_20-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.096 | debug | (10164) detect backup file 20: iobroker_2021_01_19-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.094 | debug | (10164) detect backup file 19: iobroker_2021_01_16-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.092 | debug | (10164) detect backup file 18: iobroker_2021_01_15-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.091 | debug | (10164) detect backup file 17: iobroker_2021_01_12-02_00_21_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.090 | debug | (10164) detect backup file 16: iobroker_2021_01_10-02_00_21_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.088 | debug | (10164) detect backup file 15: iobroker_2021_01_08-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.087 | debug | (10164) detect backup file 14: iobroker_2021_01_07-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.086 | debug | (10164) detect backup file 13: iobroker_2021_01_06-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.085 | debug | (10164) detect backup file 12: iobroker_2021_01_05-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.083 | debug | (10164) detect backup file 11: iobroker_2021_01_04-02_00_21_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.082 | debug | (10164) detect backup file 10: iobroker_2021_01_03-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.081 | debug | (10164) detect backup file 9: iobroker_2021_01_02-02_00_21_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.079 | debug | (10164) detect backup file 8: iobroker_2020_12_31-02_00_20_mefsmarth-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.078 | debug | (10164) detect backup file 7: iobroker_2020_12_30-02_00_20_iobroker-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.076 | debug | (10164) detect backup file 6: iobroker_2020_12_29-02_00_20_iobroker-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.075 | debug | (10164) detect backup file 5: iobroker_2020_12_28-02_00_21_iobroker-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.073 | debug | (10164) detect backup file 4: iobroker_2020_12_28-02_00_20_iobroker-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.072 | debug | (10164) detect backup file 3: iobroker_2020_12_27-02_00_20_iobroker-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.070 | debug | (10164) detect backup file 2: iobroker_2020_12_26-10_51_38_iobroker-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:22.068 | debug | (10164) detect backup file 1: iobroker_2020_12_26-10_48_11_iobroker-pi_backupiobroker.tar.gz
backitup.0 | 2021-01-26 08:37:20.035 | debug | (10164) mount successfully completed
backitup.0 | 2021-01-26 08:37:19.801 | debug | (10164) [iobroker] 10 00 02 */1 * *
backitup.0 | 2021-01-26 08:37:19.775 | info | (10164) [iobroker] backup was activated at 02:00 every 1 day(s)
backitup.0 | 2021-01-26 08:37:19.677 | info | (10164) starting. Version 1.7.0 in /opt/iobroker/node_modules/iobroker.backitup, node: v12.20.1, js-controller: 3.1.6
backitup.0 | 2021-01-26 08:37:19.278 | debug | (10164) Plugin sentry Initialize Plugin (enabled=true)

**Versions:**  
 - Adapter version: 1.7
 - JS-Controller version: 3.1.6 -->
 - Node version: <node-version> v12.20.1
 - Operating system: Raspbian GNU/Linux 10 (buster)"

**Additional context**

**Comment by simatec** [comment]
Lösche eventuelle alte Ordner in dem Verzeichnis oder andere Dateien, die nix mit Backitup zu tun haben

**Comment by simatec** [comment]
Gefixt in Version 2.0.0-beta11
