### ISSUE TITLE
OAuth Error Google Drive

### ISSUE THREAD

**Issue by OberstVonGatow** [simatec/ioBroker.backitup#401]
Unfortunately after some time i always get OAuth Errors in the Log and no Backups are created in Google Drive
If i renew my token it works again for some time.
Maybe this is more a general Google Drive Problem but it would be nice if i could get a Telegram Message (Telegram Messages are enabled) or something other than just Error in the Log.
Also in the Google Drive Tab there is no evidence that the token is expired "Access token: Vorhanden"

Log:

```
2021-02-03 02:00:19.130 - error: Unhandled promise rejection. This error
originated either by throwing inside of an async function without a
catch block, or by rejecting a promise which was not handled with .catch().
2021-02-03 02:00:19.134 - error: backitup.0 (20443) unhandled promise
rejection: Rate Limit Exceeded
2021-02-03 02:00:19.228 - error: backitup.0 (20443) Error: Rate Limit
Exceeded
at Gaxios._request (/opt/iobroker/node_modules/gaxios/src/gaxios.ts:140:15)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at OAuth2Client.requestAsync
(/opt/iobroker/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18)
2021-02-03 02:00:19.230 - info: backitup.0 (20443) cleaned everything up...
2021-02-03 02:00:19.268 - info: backitup.0 (20443) terminating
2021-02-03 02:00:19.270 - info: backitup.0 (20443) Terminated
(NO_ERROR): Without reason
2021-02-03 02:00:19.805 - error: host.pihost Caught by controller[0]:
This error originated either by throwing inside of an async function
without a catch block, or by rejecting a promise which was not handled
with .catch(). The promise rejected with the reason:
2021-02-03 02:00:19.810 - error: host.pihost Caught by controller[1]:
Error: Rate Limit Exceeded
2021-02-03 02:00:19.811 - error: host.pihost Caught by controller[1]: at
Gaxios._request (/opt/iobroker/node_modules/gaxios/src/gaxios.ts:140:15)
2021-02-03 02:00:19.811 - error: host.pihost Caught by controller[1]: at
runMicrotasks ()
2021-02-03 02:00:19.811 - error: host.pihost Caught by controller[1]: at
processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-02-03 02:00:19.811 - error: host.pihost Caught by controller[1]: at
OAuth2Client.requestAsync
(/opt/iobroker/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18)
2021-02-03 02:00:19.812 - info: host.pihost instance
system.adapter.backitup.0 terminated with code 0 (NO_ERROR)
2021-02-03 02:00:19.812 - info: host.pihost Restart adapter
system.adapter.backitup.0 because enabled
2021-02-03 02:00:49.880 - info: host.pihost instance
system.adapter.backitup.0 started with pid 13148
2021-02-03 02:00:53.427 - info: backitup.0 (13148) starting. Version
2.0.0-beta.2 in /opt/iobroker/node_modules/iobroker.backitup, node:
v12.20.1, js-controller: 3.1.6
2021-02-03 02:00:53.509 - info: backitup.0 (13148) [iobroker] backup was
activated at 02:00 every 1 day(s)
```

Regards
Fabian

**Comment by simatec** [comment]
Please post your config

**Comment by OberstVonGatow** [comment]
Config (I removed personal infos with XXXXXX):

{
"_id": "system.adapter.backitup.0",
"common": {
"name": "backitup",
"version": "2.0.0-beta.2",
"title": "BackItUp",
"authors": [
"simatec nais@gmx.net",
"peoples0815 peoples0815github@gmail.com",
"bluefox dogafox@gmail.com"
],
"docs": {
"en": "docs/en/backitup.md",
"de": "docs/de/backitup.md"
},
"platform": "Javascript/Node.js",
"mode": "daemon",
"compact": true,
"icon": "backitup.png",
"materialize": true,
"messagebox": true,
"stopBeforeUpdate": true,
"enabled": true,
"extIcon": "https://raw.githubusercontent.com/simatec/ioBroker.backitup/master/admin/backitup.png",
"keywords": [
"Backup",
"IoBroker",
"Homematic"
],
"readme": "https://github.com/simatec/ioBroker.backitup/blob/master/README.md",
"loglevel": "info",
"type": "general",
"license": "MIT",
"installedFrom": "https://github.com/simatec/ioBroker.backitup/tarball/master",
"installedVersion": "2.0.0-beta.2",
"host": "pihost",
"osDependencies": {
"linux": [
"cifs-utils",
"nfs-common"
]
},
"plugins": {
"sentry": {
"dsn": "https://e8510540c3a343aa8ce5678a4b3c8107@sentry.iobroker.net/36"
}
}
},
"native": {
"minimalEnabled": true,
"ccuEnabled": false,
"redisEnabled": false,
"javascriptsEnabled": false,
"zigbeeEnabled": false,
"jarvisEnabled": true,
"historyEnabled": true,
"influxDBEnabled": false,
"mySqlEnabled": false,
"pgSqlEnabled": false,
"grafanaEnabled": false,
"cifsEnabled": false,
"ftpEnabled": false,
"dropboxEnabled": false,
"googledriveEnabled": true,
"webdavEnabled": true,
"notificationEnabled": true,
"debugLevel": false,
"sentry_enable": true,
"historyEntriesNumber": "25",
"minimalTime": "02:00",
"minimalEveryXDays": "1",
"minimalDeleteAfter": "10",
"minimalNameSuffix": "",
"ccuTime": "01:30",
"ccuEveryXDays": "3",
"ccuDeleteAfter": "5",
"ccuHost": "",
"ccuUser": "Admin",
"ccuPassword": "",
"mySqlHost": "localhost",
"mySqlPort": "3306",
"mySqlName": "iobroker",
"mySqlUser": "",
"mySqlPassword": "",
"mySqlDumpExe": "",
"mysqlQuick": false,
"mysqlSingleTransaction": false,
"pgSqlHost": "",
"pgSqlPort": "5432",
"pgSqlName": "",
"pgSqlUser": "",
"pgSqlPassword": "",
"pgSqlDumpExe": "",
"grafanaHost": "",
"grafanaPort": "3000",
"grafanaUsername": "admin",
"grafanaPassword": "",
"grafanaApiKey": "",
"influxDBType": "local",
"influxDBHost": "localhost",
"influxDBPort": "8088",
"influxDBName": "iobroker",
"influxDBDumpExe": "",
"redisPath": "/var/lib/redis",
"historyPath": "/opt/iobroker/iobroker-data/history",
"javascriptsPath": "",
"notificationsType": "Telegram",
"telegramInstance": "telegram.0",
"telegramUser": "allTelegramUsers",
"telegramNoticeType": "longTelegramNotice",
"telegramWaitToSend": "0",
"telegramSilentNotice": false,
"telegramOnlyError": true,
"whatsappInstance": "",
"whatsappNoticeType": "longWhatsappNotice",
"whatsappWaitToSend": "0",
"whatsappOnlyError": false,
"pushoverInstance": "",
"pushoverNoticeType": "longPushoverNotice",
"pushoverWaitToSend": "0",
"pushoverDeviceID": "",
"pushoverSilentNotice": false,
"pushoverOnlyError": false,
"emailReceiver": "xxx@xxx.com",
"emailSender": "xxx@xxx.com",
"emailInstance": "",
"emailNoticeType": "longEmailNotice",
"emailWaitToSend": "0",
"emailOnlyError": false,
"connectType": "NFS",
"cifsMount": "",
"cifsDomain": "",
"cifsUser": "",
"cifsPassword": "",
"smbType": "vers=1.0",
"sudoMount": false,
"cifsDeleteOldBackup": false,
"cifsOwnDir": false,
"wakeOnLAN": false,
"macAd": "20:DE:20:DE:20:DE",
"wolWait": "25",
"cifsMinimalDir": "sharename/backupDir",
"cifsCcuDir": "sharename/backupDir",
"cifsDir": "sharename/backupDir",
"ftpHost": "",
"ftpPort": "21",
"ftpUser": "",
"ftpPassword": "",
"ftpDeleteOldBackup": false,
"ftpOwnDir": false,
"ftpMinimalDir": "/backupDir/iobroker",
"ftpCcuDir": "/backupDir/ccu",
"ftpDir": "/backupDir",
"webdavURL": "https://XXXXXX.owncube.com/remote.php/dav/files/Fabian",
"webdavUsername": "Fabian",
"webdavPassword": "XXXXXX",
"webdavDeleteOldBackup": true,
"webdavOwnDir": false,
"webdavMinimalDir": "/backupDir/iobroker",
"webdavCcuDir": "/backupDir/ccu",
"webdavDir": "/Apps/Backups/iobroker/backup/",
"dropboxAccessToken": "",
"dropboxDeleteOldBackup": false,
"dropboxOwnDir": false,
"dropboxMinimalDir": "/backupDir/iobroker",
"dropboxCcuDir": "/backupDir/ccu",
"dropboxDir": "/backupDir",
"googledriveAccessJson": "{"access_token":"XXXXXX","refresh_token":"XXXXXX","scope":"https://www.googleapis.com/auth/drive\",\"token_type\":\"Bearer\",\"expiry_date\":1612397708966}",
"googledriveDeleteOldBackup": true,
"googledriveOwnDir": false,
"googledriveMinimalDir": "/backupDir/iobroker",
"googledriveCcuDir": "/backupDir/ccu",
"googledriveDir": "/iobroker/backup",
"restoreSource": "webdav",
"startAllRestore": false
}
}

**Comment by OberstVonGatow** [comment]
I think the problem is within the schedule.
If i start the backup manual everything works like a charm.
(i updated from github and run version 2.0.0-beta.2)

But started with the schedule i only get this errors and no files are saved in Drive:

backitup.0 | 2021-02-06 02:00:53.067 | info | (6434) [iobroker] backup was activated at 02:00 every 1 day(s)
-- | -- | -- | --
backitup.0 | 2021-02-06 02:00:52.982 | info | (6434) starting. Version 2.0.0-beta.2 in /opt/iobroker/node_modules/iobroker.backitup, node: v12.20.1, js-controller: 3.1.6
host.pihost | 2021-02-06 02:00:49.630 | info | instance system.adapter.backitup.0 started with pid 6434
host.pihost | 2021-02-06 02:00:19.570 | info | Restart adapter system.adapter.backitup.0 because enabled
host.pihost | 2021-02-06 02:00:19.569 | info | instance system.adapter.backitup.0 terminated with code 0 (NO_ERROR)
host.pihost | 2021-02-06 02:00:19.569 | error | Caught by controller[1]:     at OAuth2Client.requestAsync  (/opt/iobroker/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18)
host.pihost | 2021-02-06 02:00:19.568 | error | Caught by controller[1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
host.pihost | 2021-02-06 02:00:19.568 | error | Caught by controller[1]:     at runMicrotasks (<anonymous>)
host.pihost | 2021-02-06 02:00:19.567 | error | Caught by controller[1]:     at Gaxios._request (/opt/iobroker/node_modules/gaxios/src/gaxios.ts:140:15)
host.pihost | 2021-02-06 02:00:19.567 | error | Caught by controller[1]: Error: Rate Limit Exceeded
host.pihost | 2021-02-06 02:00:19.558 | error | Caught by controller[0]: This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch(). The promise rejecte
backitup.0 | 2021-02-06 02:00:19.006 | info | (31594) Terminated (NO_ERROR): Without reason
backitup.0 | 2021-02-06 02:00:19.004 | info | (31594) terminating
backitup.0 | 2021-02-06 02:00:18.990 | info | (31594) cleaned everything up...
backitup.0 | 2021-02-06 02:00:18.989 | error | at OAuth2Client.requestAsync (/opt/iobroker/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18)
backitup.0 | 2021-02-06 02:00:18.989 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
backitup.0 | 2021-02-06 02:00:18.989 | error | at runMicrotasks (<anonymous>)
backitup.0 | 2021-02-06 02:00:18.989 | error | at Gaxios._request (/opt/iobroker/node_modules/gaxios/src/gaxios.ts:140:15)
backitup.0 | 2021-02-06 02:00:18.989 | error | (31594) Error: Rate Limit Exceeded
backitup.0 | 2021-02-06 02:00:18.931 | error | (31594) unhandled promise rejection: Rate Limit Exceeded
Unhandled | 2021-02-06 02:00:18.928 | error | promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

**Comment by simatec** [comment]
This Problem is from GoogleDrive Api. Please try a other time for Backup. Example: 3:23

**Comment by OberstVonGatow** [comment]
Thanks i will try another time 👌
