### ISSUE TITLE
WebDav Connection Error 404

### ISSUE THREAD

**Issue by OberstVonGatow** [simatec/ioBroker.backitup#402]
Hi,
i only get WebDav connection errors.
I tried to connect to my nextcloud server. 
Unfortunately even with debug logging there is not much information:
(25200) cannot conntect to WebDAV: Error: Request failed with status code 404

Regards
Fabian

**Comment by simatec** [comment]
Please post your Config from Backitup

**Comment by OberstVonGatow** [comment]
What i don't understand is that if i start the manual backup from the instance it works.
It writes the files as to the WebDav directory but still gives me an error in the logs:
`(16709) cannot conntect to WebDAV: Error: Request failed with status code 404`

Config (I removed personal infos with XXXXXX): 

{
  "_id": "system.adapter.backitup.0",
  "common": {
    "name": "backitup",
    "version": "2.0.0-beta.2",
    "title": "BackItUp",
    "authors": [
      "simatec <nais@gmx.net>",
      "peoples0815 <peoples0815github@gmail.com>",
      "bluefox <dogafox@gmail.com>"
    ],
    "docs": {
      "en": "docs/en/backitup.md",
      "de": "docs/de/backitup.md"
    },
    "platform": "Javascript/Node.js",
    "mode": "daemon",
    "compact": true,
    "icon": "backitup.png",
    "materialize": true,
    "messagebox": true,
    "stopBeforeUpdate": true,
    "enabled": true,
    "extIcon": "https://raw.githubusercontent.com/simatec/ioBroker.backitup/master/admin/backitup.png",
    "keywords": [
      "Backup",
      "IoBroker",
      "Homematic"
    ],
    "readme": "https://github.com/simatec/ioBroker.backitup/blob/master/README.md",
    "loglevel": "info",
    "type": "general",
    "license": "MIT",
    "installedFrom": "https://github.com/simatec/ioBroker.backitup/tarball/master",
    "installedVersion": "2.0.0-beta.2",
    "host": "pihost",
    "osDependencies": {
      "linux": [
        "cifs-utils",
        "nfs-common"
      ]
    },
    "plugins": {
      "sentry": {
        "dsn": "https://e8510540c3a343aa8ce5678a4b3c8107@sentry.iobroker.net/36"
      }
    }
  },
  "native": {
    "minimalEnabled": true,
    "ccuEnabled": false,
    "redisEnabled": false,
    "javascriptsEnabled": false,
    "zigbeeEnabled": false,
    "jarvisEnabled": true,
    "historyEnabled": true,
    "influxDBEnabled": false,
    "mySqlEnabled": false,
    "pgSqlEnabled": false,
    "grafanaEnabled": false,
    "cifsEnabled": false,
    "ftpEnabled": false,
    "dropboxEnabled": false,
    "googledriveEnabled": true,
    "webdavEnabled": true,
    "notificationEnabled": true,
    "debugLevel": false,
    "sentry_enable": true,
    "historyEntriesNumber": "25",
    "minimalTime": "02:00",
    "minimalEveryXDays": "1",
    "minimalDeleteAfter": "10",
    "minimalNameSuffix": "",
    "ccuTime": "01:30",
    "ccuEveryXDays": "3",
    "ccuDeleteAfter": "5",
    "ccuHost": "",
    "ccuUser": "Admin",
    "ccuPassword": "",
    "mySqlHost": "localhost",
    "mySqlPort": "3306",
    "mySqlName": "iobroker",
    "mySqlUser": "",
    "mySqlPassword": "",
    "mySqlDumpExe": "",
    "mysqlQuick": false,
    "mysqlSingleTransaction": false,
    "pgSqlHost": "",
    "pgSqlPort": "5432",
    "pgSqlName": "",
    "pgSqlUser": "",
    "pgSqlPassword": "",
    "pgSqlDumpExe": "",
    "grafanaHost": "",
    "grafanaPort": "3000",
    "grafanaUsername": "admin",
    "grafanaPassword": "",
    "grafanaApiKey": "",
    "influxDBType": "local",
    "influxDBHost": "localhost",
    "influxDBPort": "8088",
    "influxDBName": "iobroker",
    "influxDBDumpExe": "",
    "redisPath": "/var/lib/redis",
    "historyPath": "/opt/iobroker/iobroker-data/history",
    "javascriptsPath": "",
    "notificationsType": "Telegram",
    "telegramInstance": "telegram.0",
    "telegramUser": "allTelegramUsers",
    "telegramNoticeType": "longTelegramNotice",
    "telegramWaitToSend": "0",
    "telegramSilentNotice": false,
    "telegramOnlyError": true,
    "whatsappInstance": "",
    "whatsappNoticeType": "longWhatsappNotice",
    "whatsappWaitToSend": "0",
    "whatsappOnlyError": false,
    "pushoverInstance": "",
    "pushoverNoticeType": "longPushoverNotice",
    "pushoverWaitToSend": "0",
    "pushoverDeviceID": "",
    "pushoverSilentNotice": false,
    "pushoverOnlyError": false,
    "emailReceiver": "xxx@xxx.com",
    "emailSender": "xxx@xxx.com",
    "emailInstance": "",
    "emailNoticeType": "longEmailNotice",
    "emailWaitToSend": "0",
    "emailOnlyError": false,
    "connectType": "NFS",
    "cifsMount": "",
    "cifsDomain": "",
    "cifsUser": "",
    "cifsPassword": "",
    "smbType": "vers=1.0",
    "sudoMount": false,
    "cifsDeleteOldBackup": false,
    "cifsOwnDir": false,
    "wakeOnLAN": false,
    "macAd": "20:DE:20:DE:20:DE",
    "wolWait": "25",
    "cifsMinimalDir": "sharename/backupDir",
    "cifsCcuDir": "sharename/backupDir",
    "cifsDir": "sharename/backupDir",
    "ftpHost": "",
    "ftpPort": "21",
    "ftpUser": "",
    "ftpPassword": "",
    "ftpDeleteOldBackup": false,
    "ftpOwnDir": false,
    "ftpMinimalDir": "/backupDir/iobroker",
    "ftpCcuDir": "/backupDir/ccu",
    "ftpDir": "/backupDir",
    "webdavURL": "https://XXXXXX.owncube.com/remote.php/dav/files/Fabian",
    "webdavUsername": "Fabian",
    "webdavPassword": "XXXXXX",
    "webdavDeleteOldBackup": true,
    "webdavOwnDir": false,
    "webdavMinimalDir": "/backupDir/iobroker",
    "webdavCcuDir": "/backupDir/ccu",
    "webdavDir": "/Apps/Backups/iobroker/backup/",
    "dropboxAccessToken": "",
    "dropboxDeleteOldBackup": false,
    "dropboxOwnDir": false,
    "dropboxMinimalDir": "/backupDir/iobroker",
    "dropboxCcuDir": "/backupDir/ccu",
    "dropboxDir": "/backupDir",
    "googledriveAccessJson": "{\"access_token\":\"XXXXXX",\"refresh_token\":\"XXXXXX",\"scope\":\"https://www.googleapis.com/auth/drive\",\"token_type\":\"Bearer\",\"expiry_date\":1612397708966}",
    "googledriveDeleteOldBackup": true,
    "googledriveOwnDir": false,
    "googledriveMinimalDir": "/backupDir/iobroker",
    "googledriveCcuDir": "/backupDir/ccu",
    "googledriveDir": "/iobroker/backup",
    "restoreSource": "webdav",
    "startAllRestore": false
  }
}

**Comment by OberstVonGatow** [comment]
PS: I updated from github and now run version 2.0.0-beta.2

**Comment by simatec** [comment]
Lets Entcrypt your Hostname and check your Login Data

**Comment by OberstVonGatow** [comment]
Login Data should be correct because with manual backup files are getting uploaded.

**Comment by simatec** [comment]
https://en.m.wikipedia.org/wiki/HTTP_404

**Comment by simatec** [comment]
which cloud do you want to address?

**Comment by simatec** [comment]
The domain you are using must have all Lets Encrypt certificates.  You can configure this in Nextcloud

**Comment by OberstVonGatow** [comment]
The Nextcloud Server has a SSL Zertifikate.
Right now i can't reproduce the error. The Backup works as planed.
(But i changed nothing in the config so i have no clue why the error came in the first place.)
I will see if the error is coming back the next couple days, if not i will close this issue.
Anyway thank you for your response and support 👍😊
