### ISSUE TITLE
Kein Popup Fenster

### ISSUE THREAD

**Issue by Cupra-Bo** [simatec/ioBroker.backitup#407]
Hallo, 
ich versuche gerade von ner VM auf nen Docker umzuziehen

Backup aufs NAS gemacht funtzt ohne Probleme nur beim Wiederherstellen im Docker geht ja normal dieses Popup (neuer Tab) auf wo dann der Fortschritt gezeigt wird, hier kommt bei mir nur "Fehler: Verbindung fehlgeschlagen"

Ich hab im Container schon den Port "8091" per TCP durchgereicht leider ohne Erfolg 

Evtl kann mir hier jemand helfen ;) 

Gruß

**Comment by simatec** [comment]
Frag mal im Forum nach deiner Portweiterleitung. Ich kenne Docker leider nicht. 
im Forum gibt es aber einige User, die Docker nutzen

**Comment by Cupra-Bo** [comment]
normal muss man nur host und Docker Port freigeben dann sollte das gehen ;) 

Welches Forum meinst du ? 

Gruß

**Comment by simatec** [comment]
iobroker.net
