### ISSUE TITLE
Zibee-Backup nur auf dem Host möglich

### ISSUE THREAD

**Issue by guergen1** [simatec/ioBroker.backitup#425]
Erst einmal Danke für den Backitup-Adapter, läuft sehr gut!
Allerdings habe ich ein Master-Slave-System und würde gerne auch automatisch auf dem Slave-System den Zigbee-Bereich sichern. Bei mir ist die Konstallation(Master-Slave) leider nicht anders möglich, da im Master-System der Zigbee-USB-Stick nicht erkannt wird und ich deshalb ein Slave-System nur für den Zigbee-Adpter generieren musste.

**Comment by simatec** [comment]
Ja zigbee geht nur auf dem gleichen System, da auf das Filesystem zugegriffen wird. Zigbee wird allerdings auch mit dem iobroker backup gesichert
