### ISSUE TITLE
Grafana Notification Channel ins Backup integrieren

### ISSUE THREAD

**Issue by marlan99** [simatec/ioBroker.backitup#427]
Mit der Version 2.0.0 funktioniert das Backup der Dashboards und des xxx einwandfrei.
Auch der restore hat wie erwartet funktioniert.

Eingerichtete Notification Channel werden noch nicht mitgesichert.
Wäre schön wenn dies ebenfalls implementiert würde.

**Comment by simatec** [comment]
Wie kann man die Notification Channel per API auslesen?
Hast du einen Link?

**Comment by marlan99** [comment]
Ich musste jetzt etwas in meinen scripts kramen und weiss nicht ob ich es wieder hinkriege.

Ich hatte dazumal die datasources (nur als Vergleich) wie folgt exportiert:
```
for id in $(fetch_fields $KEY 'datasources' 'id'); do
        DS=$(echo $(fetch_fields $KEY "datasources/${id}" 'name')|sed 's/ /-/g').json
        echo $DS
        curl -f -k -H "Authorization: Bearer ${KEY}" "${HOST}/api/datasources/${id}" | jq '' > "$DIR/datasources/${id}.json"
    done
```

und ähnlich dazu die Notification channels:
```
    for id in $(fetch_fields $KEY 'alert-notifications' 'id'); do
        FILENAME=${id}.json
        echo $FILENAME
        curl -f -k -H "Authorization: Bearer ${KEY}" "${HOST}/api/alert-notifications/${id}" | jq 'del(.created,.updated)' > "$DIR/alert-notifications/$FILENAME"
    done
```

Beim import dann mit der datasource und notification channel:
```
    if [[ ${CURL_EXIT} = 22 && $TYPE = "datasources" ]]; then
        echo "409 conflict error is normal. Retrying as update."
        id=$(basename $file .json)
        curl_wrap "$FILE" "$KEY" "${HOST}/api/$TYPE/$id" PUT
    elif [[ ${CURL_EXIT} = 22 && $TYPE = "alert-notifications" ]]; then
        echo "500 server error is normal. Retrying as update."
        id=$(basename $file .json)
        curl_wrap "$FILE" "$KEY" "${HOST}/api/$TYPE/$id" PUT
    fi
```

Ich hoffe das hilft? Sonst einfach nochmal melden wenn du mehr infos benötigst

**Comment by simatec** [comment]
Leider fehlt bisher in den aktuellen Grafana Versionen die Unterstützung für alert-notifications via API.
Da wurde einiges umgebaut und wird so nicht mehr funktionieren.

Da Backitup kompatibel zu allen Versionen sein muss, sehe ich hier erstmal von weiteren Aktivitäten ab.
Ich schließe das Issue bis sich eventuell neue Möglichkeiten ergeben.

Hier nur mal die Unterschiede zu Version 7.x und 8.x

Version 7
![image](https://user-images.githubusercontent.com/39792461/152998895-212bce89-6981-48cf-92e3-8ae1ac094d1e.png)

Version 8
![image](https://user-images.githubusercontent.com/39792461/152999068-4c18ea01-ddf1-4826-9119-d1607d30ce9e.png)
