### ISSUE TITLE
temp. Speicherpfad für influxdb-Backup anpassbar machen

### ISSUE THREAD

**Issue by gmflie** [simatec/ioBroker.backitup#428]
Ich habe eine 23GB große influxdb, dadurch wird bei dem Backup die Partition mit iobroker vollgeschrieben, um mehr Flexibilität zu gewinnnen, wäre die Angabe des temp. Speicherpfades für das influxdb-Backup (oder auch andere) praktisch.
Zus. eine Möglichkeit die Anzahl der online gehaltenen Backups (in /opt/iobroker/backup) undabhängig von der "offline"-Anzahl (FTP, NAS/Copy, ....) einstellen zu können.

**Comment by simatec** [comment]
Verwende bitte NFS oder CIFS mount. 
damit wird temporär nicht mehr auf dein System geschrieben, sondern direkt auf dein NAS. Bei FTP und Co, wird immer erst lokal geschrieben und dann kopiert
