### ISSUE TITLE
Benachrichtigung pro Sicherungsvorgang

### ISSUE THREAD

**Issue by myssv** [simatec/ioBroker.backitup#429]
Moin zusammen,

ich habe 2 Sicherungen eingerichtet. Einmal auf Google Drive und einmal per WebDAV.

Die Benachrichtigungen sind aktiviert aber ich bekomme nur eine Nachricht:
"BackItUp:
Eine neue iobroker Sicherung wurde am 20. Februar 2021 um 21:19 Uhr erstellt und in Google Drive gespeichert."

Es wäre schön, wenn auch für den zweiten Vorgang eine entsprechende Nachricht käme!

**Comment by simatec** [comment]
Ist in dem nächsten Release gefixt
