### ISSUE TITLE
Influxdb sichern

### ISSUE THREAD

**Issue by Annotator1971** [simatec/ioBroker.backitup#430]
Hallo Simatec!

Gleich vorweg:
Ich bin neu hier und mache gerade meine ersten Erfahrungen mit Raspberry/Homematic & Co.

Danke für diesen Adapter, habe iobroker, influxdb und Grafana auf einem Raspberry4 laufen und möchte damit alles sichern.

Ich habe mir gerade Version 1.8.5 installiert und finde aber bei den Haupteinstellungen keine influxdb zum sichern.
![image](https://user-images.githubusercontent.com/79480741/108768061-80e49280-7557-11eb-8fbf-60b1c252e0e6.png)

Wie installiert man sich eigentlich Version 2?
Ich würde auch gerne Grafana sichern, aber mit dem Befehl "npm i iobroker.backitup" habe ich nur Version 1.8.5 bekommen.

Hast du da einen Tipp für mich?

Beste Grüße Annotator

**Comment by simatec** [comment]
Stelle dein Verfahrensort auf beta (latest) und aktualisiere deine Adapterliste.
Dann bekommst du die Version 2.0.0 zur Installation angeboten.
