### ISSUE TITLE
stable release

### ISSUE THREAD

**Issue by laha83** [simatec/ioBroker.backitup#433]
ich finde es klasse, dass Ihr alle diesen Adapter entwickelt. Ich habe jedoch gesehen, dass das aktuelle stable release 1.7.0 ist. Hier stehen leider noch nicht die Funktionen zur Sicherung von Grafana und influxdb zur Verfügung. Wann ist hier mit einem stable release von einer neueren Version zu rechnen? 1.8.5 oder 2.0.0. oder höher...

**Comment by simatec** [comment]
Version 2.0.x ist für das Stable geplant. Wird sicher in ein paar Wochen ins stable gehen. 
Es werden noch ein paar kleinere Bugs gefixt und die Beta Phase im latest noch ein wenig abgewartet. Bisher sieht es aber sehr gut aus.

**Comment by laha83** [comment]
Klasse. Vielen Dank für die schnelle Antwort.

 

 

Von: simatec <notifications@github.com> 
Gesendet: Montag, 1. März 2021 20:39
An: simatec/ioBroker.backitup <ioBroker.backitup@noreply.github.com>
Cc: laha83 <laha@salabaka.de>; Author <author@noreply.github.com>
Betreff: Re: [simatec/ioBroker.backitup] stable release (#433)

 

Version 2.0.x ist für das Stable geplant. Wird sicher in ein paar Wochen ins stable gehen.
Es werden noch ein paar kleinere Bugs gefixt und die Beta Phase im latest noch ein wenig abgewartet. Bisher sieht es aber sehr gut aus.
