### ISSUE TITLE
Verbesserungsvorschlag: telegram, Benutzer definieren + Text variable gestalten

### ISSUE THREAD

**Issue by eumats** [simatec/ioBroker.backitup#44]
Erst danke auf diesen Wege für den tollen Adapter. Er erleichtert das Backup ungemein!

Ich hätte noch 2x "Wünsche":
1. Es wäre super, wenn man den telegram Benutzernamen mit angeben könnte. Denn Admin-Meldungen, wie z.B. dass das Backup funktioniert hat, braucht meine Frau nicht zu bekommen... ;-)
2. Zzgl. wäre es toll, wenn man den Text der Telegram Nachricht selbst definieren könnte. Dann kann man die Meldungen nach den eigenen Wünschen anpassen. Denn für mich persönlich sind die Meldungen zu lang und haben zu viele Detailinformationen.

Es wäre cool, wenn die Wünsche bei Gelegenheit umgesetzt werden könnten! ;-)

**Comment by simatec** [comment]
Wir schauen uns das mal an und werden probieren, deine Wünsche zu berücksichtigen

**Comment by lolax80** [comment]
Bei mir steht firstname anstatt der Name eines Nutzers
