### ISSUE TITLE
Backup CCU

### ISSUE THREAD

**Issue by skaminista** [simatec/ioBroker.backitup#440]
**Describe the bug**  
iobroker etc klappt.
Wenn ich versuche die CCU zu backupen kommt:
Started ccu ...
[ERROR] [ccu] - [IGNORED] Cannot parse answer: SyntaxError: Unexpected end of JSON input
[DEBUG] [ftp] - done
[DEBUG] [cifs] - done
[DEBUG] [clean] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[EXIT] 0

**Versions:**  
 - Adapter version: 2.0.2
 - JS-Controller version: 3.1.4
 - Node version: v14.15.4
 - Operating system: pivccu3

**Comment by simatec** [comment]
Poste bitte mal deine Config von Backitup für die ccu. Hast du https an der ccu aktiv?

**Comment by skaminista** [comment]
Liegt einseitig an der https Umleitung. Wenn sie aus ist geht es 

Von meinem Mobiltelefon gesendet

**Comment by simatec** [comment]
https wird im Moment nicht unterstützt.
