### ISSUE TITLE
restore javascript 2.0.5

### ISSUE THREAD

**Issue by arto5754** [simatec/ioBroker.backitup#443]
Wiederherstellung von javascript mit Backitup:
Resultat: Files liegen im Spiegelpfad im Dateisystem sind aber im Script-Editor nicht vorhanden.
Ein touch [ (**find . -name '*.js' -exec touch {} \**] auf die Dateien im Spiegelpfad behebt allerdings das Problem.
Ist es möglich dieses nach der Wiederherstellung automatisch auszuführen?

**Comment by simatec** [comment]
Wird in der nächsten Version folgen ...
