### ISSUE TITLE
CCU Backup Fehler nach Update auf V2.0.5

### ISSUE THREAD

**Issue by Bjoern2006** [simatec/ioBroker.backitup#445]
**Fehlermeldung**  
Nach dem Update gestern auf V2.0.5 funktioniert ein Backup der CCU nicht mehr.
Die Schritte die angezeigt werden bin so durch gegangen, keine Besserung!

**Screenshots & Logfiles**  
![Backitup_Error](https://user-images.githubusercontent.com/28015256/111901799-64465800-8a3a-11eb-9b4a-a5d2d199c1b5.JPG)

**Versions:**  
 - Adapter version: 2.0.5
 - JS-Controller version: 3.2.16
 - Node version: 12.21.0
 - Operating system: Linux (Pi 4 8GB)

Jemand eine Idee?

**Comment by simatec** [comment]
Laut Log ist es nicht das CCU Backup sondern Grafana. 
Das „Axios“ Packet scheint zu fehlen. 
lösche mal Backitup in den Instanzen und unter Adaptern und installiere im Anschluss mal neu

**Comment by Bjoern2006** [comment]
Vielen Dank, habe das so durchgeführt. Scheint bis jetzt zu funktionieren!
