### ISSUE TITLE
No update to 2.0.5

### ISSUE THREAD

**Issue by Gunternerd** [simatec/ioBroker.backitup#446]
Hi, i cannot update to 2.0.5. 

npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/iobroker.backitup: Integrity verification failed for sha512....

--- an many more text.

Does somebody have an idea?

**Comment by simatec** [comment]
Please delete Backitup and install new

**Comment by Gunternerd** [comment]
it was deleted. Nothing there from backitup.

**Comment by simatec** [comment]
Then you have to reinstall it afterwards

**Comment by Gunternerd** [comment]
I try it and this is the Error in the putty console.

**Comment by simatec** [comment]
Install with Gui in iobroker

**Comment by Gunternerd** [comment]
![errorgui](https://user-images.githubusercontent.com/81087542/111919491-9089c500-8a8a-11eb-8a42-dbb742e3c6c6.jpg)

**Comment by simatec** [comment]
Please try this for install

`
cd /opt/iobroker
sudo -u iobroker npm cache clean --force
`
