### ISSUE TITLE
JavaScript Sicherung V2.0.5

### ISSUE THREAD

**Issue by Bjoern2006** [simatec/ioBroker.backitup#447]
Ich möchte gerne die JavaScripte mit sichern, dafür gibt es ja auch eine extra Kladde.
Was muss bei **"Javascript Dateipfad"** angegeben werden?
Oder soll einfach das Standardmäßige **(/media/usb/scripts)** stehen bleiben?

**Comment by simatec** [comment]
https://github.com/simatec/ioBroker.backitup/blob/master/docs/de/backitup.md#Javascript-Backup
