### ISSUE TITLE
clean: Error: EISDIR: illegal operation on a directory, unlink '/opt/iobroker/backups/zigbee.0_2020_12_13-03_51_07_backupiobroker'

### ISSUE THREAD

**Issue by jupzup** [simatec/ioBroker.backitup#448]
Version 2.0.5

clean: Error: EISDIR: illegal operation on a directory, unlink '/opt/iobroker/backups/zigbee.0_2020_12_13-03_51_07_backupiobroker'

**Comment by simatec** [comment]
Bitte den vollständigen Debug Log posten

**Comment by jupzup** [comment]
Hi anbei ein Log von heute:

`



backitup.0 | 2021-03-25 03:50:54.259 | debug | (17271) [iobroker] exec: done
backitup.0 | 2021-03-25 03:50:54.107 | debug | (17271) [iobroker/umount] done
backitup.0 | 2021-03-25 03:50:54.105 | debug | (17271) [iobroker/umount] umount successfully completed
email.0 | 2021-03-25 03:50:49.609 | info | (24895) sent to xxxx@xxxx.de
backitup.0 | 2021-03-25 03:50:49.018 | debug | (17271) [iobroker/umount] mount activ, umount is started ...
backitup.0 | 2021-03-25 03:50:48.803 | debug | (17271) [iobroker/historyJSON] done
backitup.0 | 2021-03-25 03:50:48.797 | debug | (17271) [iobroker/historyJSON] new history json values created
backitup.0 | 2021-03-25 03:50:48.638 | debug | (17271) [iobroker/historyHTML] done
backitup.0 | 2021-03-25 03:50:48.637 | debug | (17271) [iobroker/historyHTML] new history html values created
email.0 | 2021-03-25 03:50:48.008 | info | (24895) Send email: {"text":"BackItUp:\nYour backup was not completely created. Please check the errors!!\n\nclean: Error: EISDIR: illegal operation on a directory, unlink '/opt/iobroker/backups/zigb
backitup.0 | 2021-03-25 03:50:48.008 | debug | (17271) [iobroker/email] done
backitup.0 | 2021-03-25 03:50:48.006 | debug | (17271) sendTo "send" to system.adapter.email.0 from system.adapter.backitup.0
backitup.0 | 2021-03-25 03:50:47.846 | debug | (17271) [iobroker/clean] done
backitup.0 | 2021-03-25 03:50:47.845 | debug | (17271) [iobroker/clean] Error: EISDIR: illegal operation on a directory, unlink '/opt/iobroker/backups/zigbee.0_2020_12_13-03_51_07_backupiobroker'
backitup.0 | 2021-03-25 03:50:47.843 | debug | (17271) [iobroker/clean] delete /opt/iobroker/backups/zigbee.0_2020_12_13-03_51_07_backupiobroker
backitup.0 | 2021-03-25 03:50:47.824 | debug | (17271) [iobroker/clean] delete /opt/iobroker/backups/zigbee.0_2021_03_15-03_50_46_backupiobroker.tar.gz
backitup.0 | 2021-03-25 03:50:47.821 | debug | (17271) [iobroker/clean] delete /opt/iobroker/backups/zigbee.0_2021_03_16-03_50_46_backupiobroker.tar.gz
backitup.0 | 2021-03-25 03:50:47.809 | debug | (17271) [iobroker/clean] delete /opt/iobroker/backups/historyDB_2021_03_15-03_50_32_backupiobroker.tar.gz
backitup.0 | 2021-03-25 03:50:47.806 | debug | (17271) [iobroker/clean] delete /opt/iobroker/backups/historyDB_2021_03_16-03_50_32_backupiobroker.tar.gz
backitup.0 | 2021-03-25 03:50:47.790 | debug | (17271) [iobroker/clean] delete /opt/iobroker/backups/redis_2021_03_15-03_50_31_backupiobroker.tar.gz
backitup.0 | 2021-03-25 03:50:47.786 | debug | (17271) [iobroker/clean] delete /opt/iobroker/backups/redis_2021_03_16-03_50_32_backupiobroker.tar.gz
backitup.0 | 2021-03-25 03:50:47.772 | debug | (17271) [iobroker/clean] delete /opt/iobroker/backups/iobroker_2021_03_15-03_50_20_iobroker-master_backupiobroker.tar.gz
backitup.0 | 2021-03-25 03:50:47.768 | debug | (17271) [iobroker/clean] delete /opt/iobroker/backups/iobroker_2021_03_16-03_50_20_iobroker-master_backupiobroker.tar.gz
backitup.0 | 2021-03-25 03:50:47.140 | debug | (17271) [iobroker/cifs] done
backitup.0 | 2021-03-25 03:50:46.235 | debug | (17271) [iobroker/zigbee] done
backitup.0 | 2021-03-25 03:50:46.234 | debug | (17271) [iobroker/zigbee] found zigbee database: zigbee.0
backitup.0 | 2021-03-25 03:50:46.226 | debug | (17271) [iobroker/zigbee] The following files were found for the backup: backup_2020_12_13-17_11_24.tar.gz,backup_2020_12_13-17_12_11.tar.gz,backup_2020_12_13-17_21_16.tar.gz,backup_2020_12_13-18_30_
backitup.0 | 2021-03-25 03:50:46.070 | debug | (17271) [iobroker/historyDB] done
backitup.0 | 2021-03-25 03:50:46.068 | debug | (17271) [iobroker/historyDB] Backup created: /opt/iobroker/backups/historyDB_2021_03_25-03_50_32_backupiobroker.tar.gz
backitup.0 | 2021-03-25 03:50:42.790 | debug | (17271) [iobroker/historyDB] Packed 5MB so far...
backitup.0 | 2021-03-25 03:50:32.787 | debug | (17271) [iobroker/historyDB] The following files were found for the backup: 20190703,20190704,20190706,20190707,20190708,20190729,20190826,20190915,20190916,20190917,20190918,20190919,20190920,201909
backitup.0 | 2021-03-25 03:50:32.634 | debug | (17271) [iobroker/redis] done
backitup.0 | 2021-03-25 03:50:32.633 | debug | (17271) [iobroker/redis] redis tmp directory "/opt/iobroker/backups/redistmp" successfully deleted
backitup.0 | 2021-03-25 03:50:32.610 | debug | (17271) [iobroker/redis] Try deleting the redis tmp directory: "/opt/iobroker/backups/redistmp"
backitup.0 | 2021-03-25 03:50:32.609 | debug | (17271) [iobroker/redis] Backup created: /opt/iobroker/backups/redis_2021_03_25-03_50_32_backupiobroker.tar.gz
backitup.0 | 2021-03-25 03:50:32.425 | debug | (17271) [iobroker/redis] The following files were found for the backup: dump.rdb
backitup.0 | 2021-03-25 03:50:32.348 | debug | (17271) [iobroker/redis] Created redistmp directory
backitup.0 | 2021-03-25 03:50:32.343 | debug | (17271) [iobroker/redis] Start Redis Backup ...
backitup.0 | 2021-03-25 03:50:31.740 | debug | (17271) [iobroker/iobroker] done
backitup.0 | 2021-03-25 03:50:30.696 | debug | (17271) [iobroker/iobroker] Backup created: /opt/iobroker/backups/iobroker_2021_03_25-03_50_20_iobroker-master_backupiobroker.tar.gz
backitup.0 | 2021-03-25 03:50:24.686 | debug | (17271) [iobroker/iobroker] host.ioBroker-master 10639 objects saved
backitup.0 | 2021-03-25 03:50:24.603 | debug | (17271) [iobroker/iobroker] host.ioBroker-master 9431 states saved
backitup.0 | 2021-03-25 03:50:20.358 | debug | (17271) [iobroker/mount] done
backitup.0 | 2021-03-25 03:50:20.355 | debug | (17271) [iobroker/mount] mount successfully completed
backitup.0 | 2021-03-25 03:50:10.100 | debug | (17271) Backup has started ...


`

**Comment by simatec** [comment]
Lösche auf deinem NAS den Ordner "zigbee.0_2020_12_13-03_51_07_backupiobroker" manuell. Backitup hat den Ordner aufgrund des Ordnernamens als Backup identifiziert und kann diesen nicht löschen.
