### ISSUE TITLE
Backup data from sec. host (slave)

### ISSUE THREAD

**Issue by eric2905** [simatec/ioBroker.backitup#451]
It would be great, that the backitup adapter will backup also files, etc. from a secondary host (slave).

I have a sec. host, which hosts only the Zigbee adapter.
At the moment, I must have a second backitup instance on the slave, to save the Zigbee DB.

If it could be backed up in on session from the master, would be great.

**Comment by simatec** [comment]
Unfortunately, this is not possible without further ado. Backitup saves the complete folder "zigbee_x" on your slave.
Since this folder is not on the file system of your master, the master has no access to it either.

**Comment by Anzic23** [comment]
Any suggestions on how to back up zigbee on slave?

**Comment by simatec** [comment]
Version 2.2.0
