### ISSUE TITLE
Backup to Dropbox - Error [object Object], No backup file was found

### ISSUE THREAD

**Issue by Videonisse** [simatec/ioBroker.backitup#452]
I have the same (or similar) error as in Issue: https://github.com/simatec/ioBroker.backitup/issues/410

I'm using Backitup v2.1.0, js.controller v3.2.16, node v12.21.0

Log says: "error	(1560) [object Object]" two times and then "No backup file was found"

A backup file is created, but it might be first after the error is written in the log. From Console:
```
xxx@iobrokerv3:/opt/iobroker/backups$ ls
iobroker_2021_03_29-00_18_16_backupiobroker.tar.gz
```

Log-file:
`backitup.0	2021-03-29 00:18:42.118	debug	(1560) system.adapter.admin.0: logging true
backitup.0	2021-03-29 00:18:25.050	debug	(1560) [iobroker] exec: done
backitup.0	2021-03-29 00:18:24.749	debug	(1560) [iobroker/historyJSON] done
backitup.0	2021-03-29 00:18:24.749	debug	(1560) [iobroker/historyJSON] new history json values created
backitup.0	2021-03-29 00:18:24.596	debug	(1560) [iobroker/historyHTML] done
backitup.0	2021-03-29 00:18:24.595	debug	(1560) [iobroker/historyHTML] new history html values created
backitup.0	2021-03-29 00:18:23.841	debug	(1560) [iobroker/clean] done
backitup.0	2021-03-29 00:18:23.540	debug	(1560) [iobroker/dropbox] done
backitup.0	2021-03-29 00:18:23.539	debug	(1560) [iobroker/dropbox] Dropbox: [object Object]
backitup.0	2021-03-29 00:18:21.777	debug	(1560) [iobroker/dropbox] Dropbox: Copy iobroker_2021_03_29-00_18_16_backupiobroker.tar.gz...
backitup.0	2021-03-29 00:18:19.673	debug	(1560) [iobroker/iobroker] done
backitup.0	2021-03-29 00:18:18.862	debug	(1560) system.adapter.admin.0: logging false
backitup.0	2021-03-29 00:18:18.650	debug	(1560) [iobroker/iobroker] Backup created: /opt/iobroker/backups/iobroker_2021_03_29-00_18_16_backupiobroker.tar.gz
backitup.0	2021-03-29 00:18:17.512	debug	(1560) [iobroker/iobroker] host.iobrokerv3 1655 objects saved
backitup.0	2021-03-29 00:18:17.498	debug	(1560) [iobroker/iobroker] host.iobrokerv3 1034 states saved
backitup.0	2021-03-29 00:18:16.001	debug	(1560) Backup has started ...
backitup.0	2021-03-29 00:18:12.169	debug	(1560) telegram-instance:
backitup.0	2021-03-29 00:16:39.114	debug	(1560) [iobroker] exec: done
backitup.0	2021-03-29 00:16:38.812	debug	(1560) [iobroker/historyJSON] done
backitup.0	2021-03-29 00:16:38.812	debug	(1560) [iobroker/historyJSON] new history json values created
backitup.0	2021-03-29 00:16:38.659	debug	(1560) [iobroker/historyHTML] done
backitup.0	2021-03-29 00:16:38.658	debug	(1560) [iobroker/historyHTML] new history html values created
backitup.0	2021-03-29 00:16:37.903	debug	(1560) [iobroker/clean] done
backitup.0	2021-03-29 00:16:37.602	debug	(1560) [iobroker/dropbox] done
backitup.0	2021-03-29 00:16:37.599	debug	(1560) [iobroker/dropbox] Dropbox: [object Object]
backitup.0	2021-03-29 00:16:36.409	debug	(1560) [iobroker/dropbox] Dropbox: Copy iobroker_2021_03_29-00_16_30_backupiobroker.tar.gz...
backitup.0	2021-03-29 00:16:34.301	debug	(1560) [iobroker/iobroker] done
backitup.0	2021-03-29 00:16:33.273	debug	(1560) [iobroker/iobroker] Backup created: /opt/iobroker/backups/iobroker_2021_03_29-00_16_30_backupiobroker.tar.gz
backitup.0	2021-03-29 00:16:31.982	debug	(1560) [iobroker/iobroker] host.iobrokerv3 1655 objects saved
backitup.0	2021-03-29 00:16:31.970	debug	(1560) [iobroker/iobroker] host.iobrokerv3 1034 states saved
backitup.0	2021-03-29 00:16:30.469	debug	(1560) Backup has started ...
backitup.0	2021-03-29 00:16:19.842	debug	(1560) telegram-instance:
backitup.0	2021-03-29 00:16:19.246	debug	(1560) No backup file was found
backitup.0	2021-03-29 00:16:17.245	error	(1560) [object Object]
backitup.0	2021-03-29 00:16:17.245	error	(1560) [object Object]
backitup.0	2021-03-29 00:16:16.688	info	(1560) [iobroker] backup was activated at 02:00 every 1 day(s)
backitup.0	2021-03-29 00:16:16.633	info	(1560) starting. Version 2.1.0 in /opt/iobroker/node_modules/iobroker.backitup, node: v12.21.0, js-controller: 3.2.16
backitup.0	2021-03-29 00:16:16.520	debug	(1560) Plugin sentry Initialize Plugin (enabled=true)
backitup.0	2021-03-29 00:16:16.333	debug	(1560) statesDB connected
backitup.0	2021-03-29 00:16:16.332	debug	(1560) States connected to redis: 127.0.0.1:6379
backitup.0	2021-03-29 00:16:16.328	debug	(1560) States create User PubSub Client
backitup.0	2021-03-29 00:16:16.328	debug	(1560) States create System PubSub Client
backitup.0	2021-03-29 00:16:16.323	debug	(1560) Redis States: Use Redis connection: 127.0.0.1:6379
backitup.0	2021-03-29 00:16:16.322	debug	(1560) objectDB connected
backitup.0	2021-03-29 00:16:16.317	debug	(1560) Objects connected to redis: 127.0.0.1:9001
backitup.0	2021-03-29 00:16:16.291	debug	(1560) Objects client initialize lua scripts
backitup.0	2021-03-29 00:16:16.290	debug	(1560) Objects create User PubSub Client
backitup.0	2021-03-29 00:16:16.289	debug	(1560) Objects create System PubSub Client
backitup.0	2021-03-29 00:16:16.288	debug	(1560) Objects client ready ... initialize now
backitup.0	2021-03-29 00:16:16.232	debug	(1560) Redis Objects: Use Redis connection: 127.0.0.1:9001`

**Comment by simatec** [comment]
I have updated the documentation on using the Dropbox and setting up the app. There were changes in the Dropbox API. Please set up according to the instructions

https://github.com/simatec/ioBroker.backitup/blob/master/docs/de/backitup.md#Dropbox

**Comment by Videonisse** [comment]
Works now nicely, thanks!
