### ISSUE TITLE
Javascript Backup - Dateigröße wächst massiv

### ISSUE THREAD

**Issue by rande83** [simatec/ioBroker.backitup#455]
Hi.

Ich sichere meine Scripte mit und wurde heute von einer Fehlermeldung überrascht. Wie sich herausstellte war mein NAS voll. Grund dafür ist das Javascript Backup, das jeden Tag um ein vielfaches größer wurde und heute sogar knapp 100GB erreichte.

Ich habe nun das Mitsichern von Javascript erstmal deaktiviert.

Hat jemand eine Idee woran es liegen könnte?

Beste Grüße

**Comment by simatec** [comment]
Falsche Pfadangabe in der Config von Backitup

**Comment by Cisalpinos** [comment]
Hallo simatec
Hatte das identische Problem bei meiner Imstallation. 
Falsche Pfadangabe stimmt wahrscheinlich als Grund, aber ich hatte das Problem gleich, nachdem ich den JS Adapter (ohne Änderung der Konfiguration, out of the box) installiert habe und beim backitup über "Ermitteln der Konfiguration" die Daten der JS Instanz übernommen habe. 

Es wäre schön, wenn die Voreinstellungen so gewählt wären, dass man nicht per se in dieses Problem läuft.
Vielleicht kann man das anpassen? 
Ansonsten gefällt mir backitup richtig gut!

Viele Grüße

**Comment by rande83** [comment]
Hi. Danke für die comments. Aktuell konnte ich das Problem noch nicht lösen.

Lese ich das jetzt richtig raus, das ich in backitup nicht auf "Ermitteln der Konfiguration" gehen sollte, sondern den Pfad einfach nur händisch eintragen soll?

Ich bin noch etwas verunsichert über den eigentlichen Werdegang.


In den Einstellungen des JS Adapters lege ich doch einen lokalen Pfad (SD vom Raspberry) fest in dem die Scripte gesichert werden sollen. Und in backitup wiederum lege ich doch fest wo sich die Scripte befinden, damit der Adapter diese auf mein NAS schieben kann.

Oder habe ich das schon einen Denkfehler?


Beste Grüße.

**Comment by simatec** [comment]
Ich schaue mal, dass ich das beim nächsten Update integrieren kann

**Comment by simatec** [comment]
@rande83 der Pfad sollte schon auf einen Ordner verweisen, in dem nur die Skripte liegen. Wenn da noch andere Sachen im Pfad sind, werden diese mitgesichert.

**Comment by rande83** [comment]
Ok. Genau das hatte ich auch gemacht. Ich habe mich via ssh auf meinem Raspi auch versichert, dass die Scripte vom JS Adapter auch dorthin geschrieben werden. Alles in Ordnung - Scripte samt Ordnerstruktur wurden korrekt angelegt. Dennoch wuchs die Dateigröße der durch backitup angelegten Archive  (JS Backup) auf mein NAS ins unermessliche.

**Comment by simatec** [comment]
Dann poste hier mal bitte deine genaue Config von Backitup und dem JavaScript Adapter

**Comment by rande83** [comment]
![Screenshot_20210410-233708611.jpg](https://user-images.githubusercontent.com/62604250/114285306-82f6a800-9a56-11eb-8780-52b4c0f88101.jpg)

![Screenshot_20210410-233802545.jpg](https://user-images.githubusercontent.com/62604250/114285307-8853f280-9a56-11eb-876e-5997968f33dd.jpg)

![Screenshot_20210410-233839937.jpg](https://user-images.githubusercontent.com/62604250/114285309-8d18a680-9a56-11eb-89b3-a92a7d3f4d38.jpg)

![Screenshot_20210410-233923977~2.jpg](https://user-images.githubusercontent.com/62604250/114285310-9144c400-9a56-11eb-99c3-8f5c3b71c4f8.jpg)


Hier mal meine Config.

Beste Grüße.

**Comment by simatec** [comment]
Ja damit sicherst du alle Backups in einer Endlosschleife
/opt/iobroker/backups sollte nur für Backups sein. 
Du musst einen Pfad zum spiegeln angeben. 

Ich empfehle dir /opt/iobroker/iobroker-data/scripts

Dieser Pfad muss aber in beiden Adaptern identisch sein

**Comment by rande83** [comment]
Ok, ich ändere das mal und teste...

Vielen Dank schonmal für die Hilfe. Dann saß der Fehler doch 30cm vor dem Bildschirm. 😁😉

**Comment by Cisalpinos** [comment]
Was da passiert, ist relativ klar, aber ein Fehler 30cm vor dem Bildschirm sehe ich hier nicht.
 
Die Standardeinstellung für den Spiegelpfad im JS-Adapter lautet nun mal "/opt/iobroker/backups/". 
Diese Voreinstellung führt dann im Zusammenspiel der beiden Adapter zu dem Problem, wenn mit "Ermitteln der Konfiguration" der Pfad nach backitup übernommen wird (und da dieser Pfad mit dem Bachup-Pfad von backitup identisch ist, beginnt das Spiel). 

Ich denke, der JS-Adapter benötigt eine andere Vorbelegung, z.B.  "/opt/iobroker/backups/js-mirror", dann würde das Hochschauckeln schon nicht mehr beginnen.

**Comment by simatec** [comment]
Ich kann das so nicht bestätigen. Der Pfad im JavaScript Adapter ist im Standard leer.

 https://github.com/ioBroker/ioBroker.javascript/blob/06791094b03aad8311f3780bc6348a18dfd5f5cb/io-package.json#L342

Hier musst du also selber mal diesen Pfad eingtragen haben

**Comment by Cisalpinos** [comment]
Hallo simatec
Da hol mich doch der große Schlumpf. Du hast recht!
Leider hab ich aber auch nicht den Hauch einer Erinnerung daran, dass ich dort mal aktiv einen Pfad eingetragen hätte (und dann noch diesen).
Da muss ich wohl schon mehr als im Halbschlaf gewesen sein. :-(
Sorry für die Verwirrung! ...damit stimmt das mit den 30cm usw. doch mal wieder.

**Comment by simatec** [comment]
Ab Version 2.1.1 wird dies abgefangen ...
