### ISSUE TITLE
MySQL Backup unter Debian Buster

### ISSUE THREAD

**Issue by Siggi0904** [simatec/ioBroker.backitup#456]
Hallo,
unter Debian Buster kann man `sudo apt-get install mysql-client` nicht mehr installieren.
Dadurch kommt beim Backup kein Fehler, nur das Backup beträgt 0b an der sql-Datei.

Wäre gut, wenn `apt-get install default-mysql-client` unterstützt wird.
Dies installiert mariadb-client-10.3 als Fork von MySQL.

Ggf. sollten die Docs beim MySQL-Backup erweitert werden.

![grafik](https://user-images.githubusercontent.com/4992106/113586400-be940b00-962d-11eb-9161-98ff8a4e0bd7.png)

**Comment by simatec** [comment]
Danke für den Hinweis ... Habe es in der Doku angepasst
