### ISSUE TITLE
InfluxDB-Backup - input/output error

### ISSUE THREAD

**Issue by rnc11** [simatec/ioBroker.backitup#457]
Das Backup meiner Influx - Datenbank schlägt fehl. Der ioBroker und die Influx-DB laufen auf dem gleichen Server (Raspberry-Pi 4 4GB).

Hier ist der Auszug aus dem Backup-Log:
[DEBUG] [iobroker] - done
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[ERROR] [influxDB] - [IGNORED] Error: Command failed: influxd backup -portable -database iobroker "/opt/iobroker/backups/influxDB_2021_04_06-18_14_12_Standard-Backup_backupiobroker"
backup: copy: read /opt/iobroker/backups/influxDB_2021_04_06-18_14_12_Standard-Backup_backupiobroker/meta.00: input/output error

**Versionen:**  
 - Adapter version: 2.1.0 (inkl. Github Version)
 - JS-Controller version: 3.2.16
 - Node version: v10.24.0
 - Operating system: Raspbian 10 (buster)

**Zusätzliche Info's:**
Ich kann den Influx-Backup-Befehl erfolgreich über das CLI absetzen:
influxd backup -portable -database iobroker "/opt/iobroker/backups/influxDB_2021_04_06-18_14_12_Standard-Backup_backupiobroker"
In der influxdb.conf habe ich bereits erfolglos diverse Einstellungen bei bind-address getestet. Aktuell ist bind-address = "0.0.0.0:8088" eingestellt.
Ich verwende Backitup aktuell für: ioBroker, Homematic CCU, Javascript, Grafana (neuerdings).

**Comment by simatec** [comment]
done ...
https://forum.iobroker.net/post/614349
