### ISSUE TITLE
Can't backup Grafana

### ISSUE THREAD

**Issue by ingiz71** [simatec/ioBroker.backitup#459]
For some reason the backup of Grafana does not work:
The Settings (see attached file) are ok. No problem to log into Grafana with 192.168.71.58:3000 and the user "admin".
I tried with and without API key but always the same result:

**Logfile:**
Started iobroker ...
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.RaspberryPi4-IOBroker 6662 states saved

[DEBUG] [iobroker] - host.RaspberryPi4-IOBroker 7000 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_04_10-07_03_06_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Backup created: /opt/iobroker/backups/influxDB_2021_04_10-07_03_18_backupiobroker.tar.gz
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[DEBUG] [influxDB] - done
[DEBUG] [zigbee] - found zigbee database: zigbee.0
[DEBUG] [zigbee] - done
**_[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
[DEBUG] [grafana] - Error on Grafana Dashoard Request: Error: Request failed with status code 401
[DEBUG] [grafana] - start Grafana backup compress ...
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[DEBUG] [grafana] - cannot found Grafana Backup files
[DEBUG] [grafana] - done_**
[DEBUG] [cifs] - done
[DEBUG] [clean] - done
[DEBUG] [pushover] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[DEBUG] [umount] - mount activ, umount is started ...
[DEBUG] [umount] - umount successfully completed
[DEBUG] [umount] - done
[EXIT] 0

Do you have any idea why it does not work?
Thanks for your help

**Comment by ingiz71** [comment]
Sorry, forgott the screenshot...

![Grafana Backup Settings](https://user-images.githubusercontent.com/59662851/114259733-59933900-99d0-11eb-9b24-3092277ff3bd.jpg)

**Comment by simatec** [comment]
You have no Apikey in your Config

**Comment by ingiz71** [comment]
Thanks for your quick feedback. As already mentioned above it did also not work with Apikey. However, your answer helped me to solve the problem 😊. Due to a mix-up I tried an api key  of another Grafana installation... Sorry for that!

**Comment by florian84z** [comment]
Ich habe leider das gleiche / ein ähnliches Problem. Config im Adapter ist mMn richtig eingestellt, API Key ist auch in der GUI erzeugt.

Was kann das sein?

Started iobroker ...
[DEBUG] [iobroker] - host.raspberrypi 13921 states saved

[DEBUG] [iobroker] - host.raspberrypi 16289 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_04_13-11_41_24_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Backup created: /opt/iobroker/backups/influxDB_2021_04_13-11_41_36_backupiobroker.tar.gz
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[DEBUG] [influxDB] - done
[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
[DEBUG] [grafana] - Error on Grafana Datasource Request
[DEBUG] [grafana] - found Dashboard: e-gerate
[DEBUG] [grafana] - found Dashboard: raspberry-4
[DEBUG] [grafana] - found Dashboard: temperaturen
[DEBUG] [grafana] - found Dashboard: gas-and-strom
[DEBUG] [grafana] - found Dashboard: spritpreise-zeven
[DEBUG] [grafana] - start Grafana backup compress ...
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[DEBUG] [grafana] - cannot found Grafana Backup files
[DEBUG] [grafana] - done
[DEBUG] [jarvis] - found Jarvis Instance: 0
[DEBUG] [jarvis] - start Jarvis Backup for Instance 0...
[DEBUG] [jarvis] - Backup created: /opt/iobroker/backups/jarvis.0_2021_04_13-11_41_45_backupiobroker.tar.gz
[DEBUG] [jarvis] - done
[DEBUG] [javascripts] - javascript directory "" not found
[DEBUG] [javascripts] - done
[DEBUG] [googledrive] - Google Drive: Copy iobroker_2021_04_13-11_41_24_backupiobroker.tar.gz...
[DEBUG] [googledrive] - Google Drive: Copy influxDB_2021_04_13-11_41_36_backupiobroker.tar.gz...
[DEBUG] [googledrive] - Google Drive: Copy jarvis.0_2021_04_13-11_41_45_backupiobroker.tar.gz...
[ERROR] [googledrive] - Google Drive: File "/opt/iobroker/backups/javascripts_2021_04_13-11_41_45_backupiobroker.tar.gz" not found
[DEBUG] [googledrive] - done
[DEBUG] [clean] - done
[DEBUG] [pushover] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[EXIT] 0

**Comment by florian84z** [comment]
![image](https://user-images.githubusercontent.com/23108104/114541372-f0712700-9c56-11eb-9fbe-64f18d79c761.png)

**Comment by florian84z** [comment]
backitup.0 | 2021-04-13 12:10:55.497 | debug | (29555) [iobroker/grafana] done
-- | -- | -- | --
backitup.0 | 2021-04-13 12:10:55.496 | debug | (29555) [iobroker/grafana] cannot found Grafana Backup files
backitup.0 | 2021-04-13 12:10:55.495 | debug | (29555) [iobroker/grafana] Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
backitup.0 | 2021-04-13 12:10:55.489 | debug | (29555) [iobroker/grafana] Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
backitup.0 | 2021-04-13 12:10:55.483 | debug | (29555) [iobroker/grafana] start Grafana backup compress ...
backitup.0 | 2021-04-13 12:10:55.480 | debug | (29555) [iobroker/grafana] found Dashboard: temperaturen
backitup.0 | 2021-04-13 12:10:55.465 | debug | (29555) [iobroker/grafana] found Dashboard: raspberry-4
backitup.0 | 2021-04-13 12:10:55.441 | debug | (29555) [iobroker/grafana] found Dashboard: e-gerate
backitup.0 | 2021-04-13 12:10:55.418 | debug | (29555) [iobroker/grafana] found Dashboard: gas-and-strom
backitup.0 | 2021-04-13 12:10:55.370 | debug | (29555) [iobroker/grafana] found Dashboard: spritpreise-zeven
backitup.0 | 2021-04-13 12:10:54.863 | debug | (29555) [iobroker/grafana] Error on Grafana Datasource Request
backitup.0 | 2021-04-13 12:10:54.670 | debug | (29555) [iobroker/grafana] Grafana is available ... Status: 200
backitup.0 | 2021-04-13 12:10:54.618 | debug | (29555) [iobroker/grafana] start Grafana request ...
backitup.0 | 2021-04-13 12:10:54.616 | debug | (29555) [iobroker/grafana] Created datasource directory
backitup.0 | 2021-04-13 12:10:54.615 | debug | (29555) [iobroker/grafana] Created dashboards_manually_restore directory
backitup.0 | 2021-04-13 12:10:54.614 | debug | (29555) [iobroker/grafana] Created dashboard directory
backitup.0 | 2021-04-13 12:10:54.612 | debug | (29555) [iobroker/grafana] Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
backitup.0 | 2021-04-13 12:10:54.610 | debug | (29555) [iobroker/grafana] Start Grafana Backup ...

**Comment by ichtyp** [comment]
> Ich habe leider das gleiche / ein ähnliches Problem. Config im Adapter ist mMn richtig eingestellt, API Key ist auch in der GUI erzeugt.
> 
> Was kann das sein?
> 
> Started iobroker ... [DEBUG] [iobroker] - host.raspberrypi 13921 states saved
> 
> [DEBUG] [iobroker] - host.raspberrypi 16289 objects saved
> 
> [DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_04_13-11_41_24_backupiobroker.tar.gz
> 
> [DEBUG] [iobroker] - done [DEBUG] [influxDB] - Start InfluxDB Backup ... [DEBUG] [influxDB] - InfluxDB Backup tmp directory created [DEBUG] [influxDB] - Backup created: /opt/iobroker/backups/influxDB_2021_04_13-11_41_36_backupiobroker.tar.gz [DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory [DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted [DEBUG] [influxDB] - done [DEBUG] [grafana] - Start Grafana Backup ... [DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp" [DEBUG] [grafana] - Created dashboard directory [DEBUG] [grafana] - Created dashboards_manually_restore directory [DEBUG] [grafana] - Created datasource directory [DEBUG] [grafana] - start Grafana request ... [DEBUG] [grafana] - Grafana is available ... Status: 200 [DEBUG] [grafana] - Error on Grafana Datasource Request [DEBUG] [grafana] - found Dashboard: e-gerate [DEBUG] [grafana] - found Dashboard: raspberry-4 [DEBUG] [grafana] - found Dashboard: temperaturen [DEBUG] [grafana] - found Dashboard: gas-and-strom [DEBUG] [grafana] - found Dashboard: spritpreise-zeven [DEBUG] [grafana] - start Grafana backup compress ... [DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp" [DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted [DEBUG] [grafana] - cannot found Grafana Backup files [DEBUG] [grafana] - done [DEBUG] [jarvis] - found Jarvis Instance: 0 [DEBUG] [jarvis] - start Jarvis Backup for Instance 0... [DEBUG] [jarvis] - Backup created: /opt/iobroker/backups/jarvis.0_2021_04_13-11_41_45_backupiobroker.tar.gz [DEBUG] [jarvis] - done [DEBUG] [javascripts] - javascript directory "" not found [DEBUG] [javascripts] - done [DEBUG] [googledrive] - Google Drive: Copy iobroker_2021_04_13-11_41_24_backupiobroker.tar.gz... [DEBUG] [googledrive] - Google Drive: Copy influxDB_2021_04_13-11_41_36_backupiobroker.tar.gz... [DEBUG] [googledrive] - Google Drive: Copy jarvis.0_2021_04_13-11_41_45_backupiobroker.tar.gz... [ERROR] [googledrive] - Google Drive: File "/opt/iobroker/backups/javascripts_2021_04_13-11_41_45_backupiobroker.tar.gz" not found [DEBUG] [googledrive] - done [DEBUG] [clean] - done [DEBUG] [pushover] - done [DEBUG] [historyHTML] - new history html values created [DEBUG] [historyHTML] - done [DEBUG] [historyJSON] - new history json values created [DEBUG] [historyJSON] - done [EXIT] 0

Moin,
das gleiche habe ich auch, was hat bei dir geholfen?

Hier der Logoutput:

Started iobroker ...
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.iobroker 32205 states saved

[DEBUG] [iobroker] - host.iobroker 42380 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2022_06_19-16_43_40_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [influxDB] - InfluxDB-Backup started ...
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Packed 84MB so far...
[DEBUG] [influxDB] - Packed 168MB so far...
[DEBUG] [influxDB] - Packed 251MB so far...
[DEBUG] [influxDB] - Backup created: /opt/iobroker/backups/influxDB_2022_06_19-16_43_54_backupiobroker.tar.gz
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[DEBUG] [influxDB] - InfluxDB-Backup for is finish
[DEBUG] [influxDB] - done
[DEBUG] [grafana] - Start Grafana Backup ...
**[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
_[DEBUG] [grafana] - Error on Grafana Datasource Request_
[DEBUG] [grafana] - found Dashboard: freenas-status-2
[DEBUG] [grafana] - found Dashboard: freenas-status
[DEBUG] [grafana] - found Dashboard: tollesdashboard
[DEBUG] [grafana] - found Dashboard: freenas-local
[DEBUG] [grafana] - found Dashboard: ips16
[DEBUG] [grafana] - start Grafana backup compress ...
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[DEBUG] [grafana] - cannot found Grafana Backup files
[DEBUG] [grafana] - done**
[DEBUG] [cifs] - used copy path: /mnt/iobbackup
[DEBUG] [cifs] - Copy iobroker_2022_06_19-16_43_40_backupiobroker.tar.gz...
[DEBUG] [cifs] - Copy influxDB_2022_06_19-16_43_54_backupiobroker.tar.gz...
[DEBUG] [cifs] - done
[DEBUG] [clean] - done
[DEBUG] [telegram] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[DEBUG] [umount] - done
[EXIT] 0


Der Fehler ist leider recht unspezifisch, ich weiß nicht wo ich ansetzen soll :-/

Danke und viele Grüße!

**Comment by simatec** [comment]
Hast dein Api User in Grafana eine Gültigkeit und ist der Apikey mit Adminrechten erzeugt?
Hat dein Grafana Passwort Sonderzeichen?

**Comment by ichtyp** [comment]
Hi,API Key ist als Admin eingerichtet und gilt 10 Jahre. Passwort ist alphanumerisch, 20 Zeichen lang. Keine Sonderzeichen. Kann ich dir irgendwelche weitere logs liefern die helfen? Danke auf jeden Fall fürs ansehen!Am 19.06.2022 19:17 schrieb simatec ***@***.***>:

Hast dein Api User in Grafana eine Gültigkeit und ist der Apikey mit Adminrechten erzeugt?

Hat dein Grafana Passwort Sonderzeichen?

**Comment by simatec** [comment]
Konfiguriere mal den API Key neu und füge diesen erneut in Backitup ein. Zur Sicherheit auch noch das Passwort erneuern und in Backitup konfigurieren. Der User für das Backup sollte der admin von Grafana sein

**Comment by ichtyp** [comment]
Das hat geholfen! Ich bin mir zwar sicher die Kombi schon probiert zu haben, aber was solls, wenn Passwort erneuen was bringt, dann sei es so. Danke 😊

 

Von: simatec ***@***.***> 
Gesendet: Sonntag, 19. Juni 2022 22:03
An: simatec/ioBroker.backitup ***@***.***>
Cc: ichtyp ***@***.***>; Comment ***@***.***>
Betreff: Re: [simatec/ioBroker.backitup] Can't backup Grafana (#459)

 

Konfiguriere mal den API Key neu und füge diesen erneut in Backitup ein. Zur Sicherheit auch noch das Passwort erneuern und in Backitup konfigurieren. Der User für das Backup sollte der admin von Grafana sein
