### ISSUE TITLE
Unnötige MySQL Warnmeldung "Using a password on the command line interface can be insecure "

### ISSUE THREAD

**Issue by Fiiti** [simatec/ioBroker.backitup#46]
Beim logging kommt die Warnmeldung "Using a password on the command line interface can be insecure ".
Da dann der Dump kommt und erst einmal kurz gar nichts passiert, ist hier eine Missverständlichkeit vorhanden.

Hier gibt es anscheinend eine gute Lösung:
https://gist.github.com/nestoru/4f684f206c399894952d 

Vielleicht magst Du diese integrieren?

So long.

**Comment by simatec** [comment]
Danke für den Hinweis. Wir schauen uns das an ...
