### ISSUE TITLE
InfluxDB wird nicht gesichert/kein Cronjob

### ISSUE THREAD

**Issue by DanielWeeber** [simatec/ioBroker.backitup#464]
Wenn ich ein InfluxDB anlege zeigt er nicht im Log, dass er es sicher wird (der Cronjob)

Was mach ich falsch?

<img width="1949" alt="Bildschirmfoto 2021-04-15 um 16 02 28" src="https://user-images.githubusercontent.com/2935130/114882301-1b4cae00-9e04-11eb-9a3c-0450d685f2f5.png">
<img width="927" alt="Bildschirmfoto 2021-04-15 um 16 02 22" src="https://user-images.githubusercontent.com/2935130/114882310-1daf0800-9e04-11eb-8cff-83d29cf6812a.png">
<img width="1433" alt="Bildschirmfoto 2021-04-15 um 16 02 12" src="https://user-images.githubusercontent.com/2935130/114882315-1e479e80-9e04-11eb-850d-0229a1974c65.png">

**Comment by simatec** [comment]
Du musst den Log auf debug stellen. Des Weiteren musst du für das Backup den Remote Port 8088 belassen und dass ganze auch in deiner Influx Config freigeben. Die Anleitung findest du im der Doku von Backitup

**Comment by DanielWeeber** [comment]
Die bind-address passt, ich nutze das in einem Docker Container. 8086 und 8088 sind offen. Aber der Cronjob wird ja gar nicht erst erstellt?
Auch nicht mit Port 8088 in der BackItUp Config

**Comment by DanielWeeber** [comment]
Vom ioBroker Container aus selbst geht es auch.

<img width="1147" alt="Bildschirmfoto 2021-04-16 um 09 46 39" src="https://user-images.githubusercontent.com/2935130/114990286-aa0b0a80-9e98-11eb-9c84-5d8402d87a82.png">

**Comment by DanielWeeber** [comment]
Das Grafana und InfluxDB ist Teil des ioBroker Backups... *facepalm

Funktioniert..

**Comment by simatec** [comment]
Ja das sind alles Optionen, die beim iobroker Backup mit gesichert werden
