### ISSUE TITLE
mysql backup not working with $ in password

### ISSUE THREAD

**Issue by Sickboy78** [simatec/ioBroker.backitup#466]
**Describe the bug**  
When the mysql password contains a '$' as a special character, the following error occurs:
mysqldump: Got error: 1045: Access denied for user 'iobroker'@'localhost' (using password: YES) when trying to connect

**To Reproduce**  
1. Change your mysql password to contain a $
2. Start a backitup backup for mysql
3. You get the error "mysqldump: Got error: 1045: Access denied for user 'iobroker'@'localhost' (using password: YES) when trying to connect"

**Expected behavior**  
Backup works.

**Additional context**  
I guess '$' should be escaped since it has a special meaning when used on the cli.
Manual escaping '$' with '\\$' in the backitup password for mysql is a workaround.

**Comment by simatec** [comment]
Please try entering the password with quotation marks in the Backitup Config

**Comment by Sickboy78** [comment]
Single quotation marks **'** work, double **"** not. Anyway, thats just another workaround like escaping with \\$.
