### ISSUE TITLE
Löschen alter Backups aus /opt/iobroker/backups

### ISSUE THREAD

**Issue by CarstensCar** [simatec/ioBroker.backitup#469]
Ich benutze den Adapter in der latest Version 2.1.3 und mache täglich Backups 1x auf dem NAS, 1x ins Google Drive und 1x in die Dropbox. Vom Iobroker sollen 50 Backups vorgehalten werden, vom Homematic Backup 5 Stck.

Alles Backups funktionieren und liegen auch jeweils da wo sie hin sollen.

Leider liegen sie aber auch weiterhin im /opt/iobroker/backups - Verzeichnis.

Ich lösche die da jetzt regelmäßig raus, frage mich aber, ob das so richtig ist.

War das nicht früher mal so, dass die Backups aus dem VErzeichnis rausgelöscht wurden, nachdem sie auf die externen Laufwerke verschoben/kopiert wurden?

Viele Grüße

Frank

**Comment by simatec** [comment]
Wie sicherst du denn auf dem NAS? Per FTP?

**Comment by CarstensCar** [comment]
korrekt. per FTP.

BEi der Option NAS/Copy habe ich ab und an loginprobleme

**Comment by simatec** [comment]
Per FTP wird das Backup lokal erstellt und dann via FTP kopiert. 
Wenn die lokalen Backups gelöscht werden sollen, kannst du das in dem jeweiligen Backup Tab (CCU und iobroker) festlegen

**Comment by CarstensCar** [comment]
Sorry, die von dir genannte Option kann ich leider nicht entdecken.

**Comment by simatec** [comment]
Im Tab iobroker kannst du die Anzahl der Backups angeben, die erhalten bleiben sollen.
