### ISSUE TITLE
Beim Restore mehr Infos anzeigen über den Status

### ISSUE THREAD

**Issue by SurfGargano** [simatec/ioBroker.backitup#470]
Ist es möglich beim Restore anzuzeigen, wo er gerade ist ?
Man sieht nur die Meldung 'Started restore' und dann den rotierenden Kreis.

**Comment by simatec** [comment]
Du musst in deinem Browser Popups erlauben. Dann öffnet sich ein neuer Tab, indem du den Log siehst
