### ISSUE TITLE
Please include hostname in messenger notification

### ISSUE THREAD

**Issue by Grothesk242** [simatec/ioBroker.backitup#475]
**Is your feature request related to a problem? Please describe.**
When running several hosts it would be nice to see which host backupped 

**Describe the solution you'd like**
Include the host name in the notification. 

Something like: 
Der Host $HOSTNAME hat eine Sicherung am $DATE um $TIME erstellt und unter $BACKUPDIRECTORY gespeichert.

**Comment by simatec** [comment]
added at 2.1.13 
you can write your Hostname on Name Sufix in the settings of Backitup
