### ISSUE TITLE
circurlar dependency

### ISSUE THREAD

**Issue by daniel-lo** [simatec/ioBroker.backitup#478]
$ ./iobroker upgrade
ERROR: Circular dependency detected between adapters "backitup"
2.1.5 -> 2.1.6

Update ist aber durchgelaufen

**Comment by simatec** [comment]
Bitte den kompletten Log posten und bitte angeben, welche node Version, npm Version und js-controller Version installiert sind

**Comment by daniel-lo** [comment]
Node.js: v12.22.1
NPM: 6.14.12
Host 3.3.2

Log hab ich leider nicht mehr.

**Comment by simatec** [comment]
Kannst du erstmal ignorieren ...
