### ISSUE TITLE
Grafana Backup

### ISSUE THREAD

**Issue by gedongi** [simatec/ioBroker.backitup#479]
Hallo Zusammen,
ich habe ein Problem beim Backup von Grafana.

Logfile:
Started iobroker ...
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.RASPI4 8208 states saved

[DEBUG] [iobroker] - host.RASPI4 8383 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_05_04-16_35_28_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
[DEBUG] [grafana] - found Dashboard: temperatur
[DEBUG] [grafana] - found Dashboard: energie
[DEBUG] [grafana] - found Dashboard: tanken
[DEBUG] [grafana] - found Dashboard: 002-raum
[DEBUG] [grafana] - found Dashboard: 001-aussen
[DEBUG] [grafana] - found Dashboard: 002-pv-ertrag
[DEBUG] [grafana] - found Dashboard: 001-energie
[DEBUG] [grafana] - found Dashboard: 001-tankstellen
[DEBUG] [grafana] - found Dashboard: 003-pv-einspeisung
[DEBUG] [grafana] - found Dashboard: 004-pv-eigenverbrauch
[DEBUG] [grafana] - found Dashboard: 003-heisswasser
[DEBUG] [grafana] - start Grafana backup compress ...

Compress wird nicht beendet. Muss manuell beendet werden.

Das Backup soll mit cifs auf meine Nas(Fritzbox) gespeichert werden.
Dort wird der grafana_tmp Ordner korrekt angelegt mit 3 Unterordner welche die Dashboards und die datasource beinhalten.
Weiterhin wird auch das komprimierte file im Ordner angelegt. Dieses kann aber nicht geöffnet werden, mit der Meldung unerwartetes Archivende.

Raspi 4B/4GB, Buster
Backitup Version 2.1.0
Grafana oss Version 7.5.5
Node.js Version 12.22.1
JS-controller Version 3.2.16

Einstellungen Grafana
![image](https://user-images.githubusercontent.com/37265486/117023199-2d31ba80-acf9-11eb-875c-b15e511d2d58.png)

Ich hoffe jemand kann helfen.
Danke...

**Comment by simatec** [comment]
Mach mal bitte ein Update auf Version 2.1.6. 
In der Version 2.1.0 gab es teilweise Probleme beim Compress. 
Die Version 2.1.6 kommt die nächsten Tage auch ins Stable

**Comment by gedongi** [comment]
Mit der Version 2.1.6 das gleiche Verhalten wie oben beschrieben.
Was kann ich noch probieren?
Grüße

**Comment by simatec** [comment]
Speicherst du lokal oder auf einem NAS?
Zeige mir mal bitte den Inhalt des Backup Ordners mit:

`ls -la /opt/iobroker/backups`

Hast du den `iobroker fix` mal laufen lassen?

**Comment by gedongi** [comment]
Ich speichere auf meine Nas.

Iobroker fix nochmal laufen lassen. Keine Änderung.

Inhalt von Backups siehe screendump im Anhang.


Gruss

simatec ***@***.***> schrieb am Mi., 5. Mai 2021, 12:13:

**Comment by simatec** [comment]
Bitte nicht als Angang posten. 
bitte hier als Log einfügen

**Comment by gedongi** [comment]
![Screenshot_20210505_163057_com sonelli juicessh](https://user-images.githubusercontent.com/37265486/117283797-6e93a880-ae66-11eb-8230-4e582aab2075.jpg)

**Comment by gedongi** [comment]
Noch eine Idee?

**Comment by simatec** [comment]
Zeige mal bitte die Konfiguration von Backitup für das NAS und die Einstellung in deiner Fritzbox.

**Comment by gedongi** [comment]
![Screenshots_2021-05-18-09-45-13](https://user-images.githubusercontent.com/37265486/118612706-556fed80-b7be-11eb-9390-8c856ea3d702.png)


Welche Einstellung der Fritzbox brauchst du?

**Comment by simatec** [comment]
Installiere mal bitte die aktuelle latest Version. Dort gibt es in den NAS-Einstellungen speziell für die Fritzbox die "noserverino" Option, die aktiviert werden muss

**Comment by gedongi** [comment]
Ich habe die 2.1.10 installiert aber besagte option gibt es bei mir nicht unter nas/kopieren.

**Comment by simatec** [comment]
![image](https://user-images.githubusercontent.com/39792461/118657698-fc1eb300-b7eb-11eb-9fba-6429cbce270b.png)

**Comment by gedongi** [comment]
Definitiv keine auswahl in meinem adapter zu finden unter nas/kopieren. Installierte adapter 2.1.10

**Comment by gedongi** [comment]
![Screenshots_2021-05-18-20-28-34](https://user-images.githubusercontent.com/37265486/118704726-ba0b6680-b817-11eb-8a0e-896f906acbd8.png)

**Comment by simatec** [comment]
Schaue dir die Config mal auf einem Rechner an. 
Die Option gibt es definitiv

**Comment by gedongi** [comment]
![20210518_210249](https://user-images.githubusercontent.com/37265486/118708876-8f6fdc80-b81c-11eb-8da7-a9e425673d4e.jpg)


PC Foto

**Comment by gedongi** [comment]
![Screenshots_2021-05-18-21-08-13](https://user-images.githubusercontent.com/37265486/118709396-32285b00-b81d-11eb-95f7-31b956e7f3f5.png)


PC Foto

**Comment by gedongi** [comment]
![Screenshots_2021-05-18-21-23-41](https://user-images.githubusercontent.com/37265486/118711117-7b79aa00-b81f-11eb-81bc-09d5740d0fd4.png)



PC Foto

**Comment by simatec** [comment]
Mach mal einen Upload des Adapters

**Comment by gedongi** [comment]
Upload fertig

**Comment by gedongi** [comment]
Ok. Auswahl ist angekommen. Ich probiere jetzt das grafana backup.

**Comment by gedongi** [comment]
Passt jetzt. Danke schön für die unterstützung und deine arbeit...weiter so...
