### ISSUE TITLE
Kein Backup in Dropbox

### ISSUE THREAD

**Issue by Knallochse** [simatec/ioBroker.backitup#480]
Es wird kein Iobroker Backup auf Dropbox abgelegt.
Log Ausgabe:
`[DEBUG] [dropbox] - Dropbox: Copy iobroker_2021_05_05-08_34_03_backupiobroker.tar.gz...
[ERROR] [dropbox] - Dropbox: [object Object]`
Das Backup der CCU wird aber problemlos auf Dropbox abgelegt

**Versions:**  
 - Adapter version: <2.1.6>
 - JS-Controller version: <3.2.16> 
 - Node version: <12.22.1>
 - Operating system: <Docker>

**Comment by simatec** [comment]
Zeige mal bitte deine App Einstellungen in der Dropbox. Auch den Tab für Berechtigungen bitte

**Comment by Knallochse** [comment]
![image](https://user-images.githubusercontent.com/36857242/117127431-5bb4a180-ad9c-11eb-87d1-525aaeeedb2b.png)

Wie schon oben geschrieben wird ja das CCU-Backup (durch Backitup) ohne Probleme nach Dropbox kopiert.

**Comment by simatec** [comment]
Und die Settings bitte

**Comment by Knallochse** [comment]
![Screen1](https://user-images.githubusercontent.com/36857242/117251677-49427280-ae45-11eb-9dd5-10657ab91bd8.jpg)
![Screen2](https://user-images.githubusercontent.com/36857242/117251693-4d6e9000-ae45-11eb-8d05-9955134e4d0d.jpg)

**Comment by simatec** [comment]
Hast du deine Pfadangaben in Backitup schon geprüft?
Ich werde in der nächsten Version den Fehlerlog mal etwas umbauen, um mehr Infos zu bekommen.

**Comment by Knallochse** [comment]
Ich schreibe bei Dropbox alles in einen Ordner. Habe gerade nochmal kontrolliert. CCU Backup wird kopiert - Iobroker Backup nicht.

Ich habe gerade einen Test mit Google Drive durchgeführt. Hier ist alles OK (CCU & Iobroker Backup werden abgelegt)

**Comment by simatec** [comment]
Kannst du mal bitte mit verschiedenen Pfaden testen?

![image](https://user-images.githubusercontent.com/39792461/117258090-e0f78f00-ae4c-11eb-8096-1006e90ca334.png)

**Comment by Knallochse** [comment]
Test mit verschiedenen Pfaden für Dropbox.
![image](https://user-images.githubusercontent.com/36857242/117260656-96c3dd00-ae4f-11eb-8133-3f51269fe43b.png)

CCU Backup - ja
Iobroker Backup nein
`[DEBUG] [dropbox] - Dropbox: Copy iobroker_2021_05_06-09_29_57_backupiobroker.tar.gz...
[ERROR] [dropbox] - Dropbox: [object Object]`

**Comment by simatec** [comment]
Lasse mal bitte den `iobroker fix` laufen. Ich denke da passt etwas mit deinen Rechten nicht.
Zeige mal bitte mit `ls -la /opt/iobroker/backups` den Inhalt deines Backup Ordners

**Comment by Knallochse** [comment]
![image](https://user-images.githubusercontent.com/36857242/117264694-c2e15d00-ae53-11eb-9232-4eef6d105366.png)

Ich habe kein Rechteproblem. Im /backups Odner sind nur noch ältere Backup Dateien, da ich seit einiger Zeit die Backups aufs NAS sichere

**Comment by Knallochse** [comment]
![image](https://user-images.githubusercontent.com/36857242/117269226-63d21700-ae58-11eb-9729-1e99b59b68b2.png)
Hier nochmal mit aktuellen Backups.

Ich fasse nochmals zusammen.

Homematic Backup
NAS - funktioniert
Dropbox - funktioniert
Google Drive - funktioniert

IoBroker Backup
NAS - funktioniert
Dropbox - **funktioniert nicht**
Google Drive - funktioniert

**Comment by simatec** [comment]
Da du Docker nutzt, kann es hier doch ein Rechteproblem geben. Eventuell auch auf deinem NAS.
Um das NAS ausschließen zu können, würde ich dir mal bitten, das NAS in Backitup auszuschalten und nur lokal sichern.
Wenn dann auf Dropbox übertragen wird, dann liegt es am NAS.
Was sagt der Speicherplatz in deiner Dropbox?

**Comment by Knallochse** [comment]
So Iobroker Backup in Dropbox (NAS Sicherung ausgeschaltet) geht nicht.
`[DEBUG] [dropbox] - Dropbox: Copy iobroker_2021_05_06-12_09_05_backupiobroker.tar.gz...
[ERROR] [dropbox] - Dropbox: [object Object]`

Speicher in Dropbox ist ausreichend vorhanden.
![image](https://user-images.githubusercontent.com/36857242/117281817-5884e880-ae64-11eb-8b21-f37fa5a32314.png)

**Comment by simatec** [comment]
Installiere mal bitte über Githab aus dem DEV-Branch die Version.
Dort habe ich einen Error Log eingebaut, in dem man nun sehen sollte, wo es hängt 
Dev-Branch URL: https://github.com/simatec/ioBroker.backitup/tarball/dev
![image](https://user-images.githubusercontent.com/39792461/117285510-62a8e600-ae68-11eb-98ae-c301efc2fa18.png)
Im Anschluss einen Upload machen.

**Comment by Knallochse** [comment]
Jetzt kommt diese Meldung.

- [DEBUG] [dropbox] - Dropbox: Copy iobroker_2021_05_06-12_55_34_backupiobroker.tar.gz...
- [ERROR] [dropbox] - upload Dropbox: {}
- [DEBUG] [dropbox] - done

**Comment by simatec** [comment]
Ok, nicht wirklich ausagekräftig ...

Was mir aber noch aufgefallen ist ... Dein iobroker Backup ist laut dem Screenshot 420 Mb groß?
Wie groß ist dein Backup was du hochladen willst?
Mir kommt das sehr groß vor und ich kann dir erhlich gesagt nicht beantworten, wie die Dropbox Api damit umgehen kann

**Comment by Knallochse** [comment]
Ich schau mal ob ich abspecken kann. Muss jetzt arbeiten und melde mich morgen früh.

**Comment by Knallochse** [comment]
Ich konnte mein Backup auf 186MB drücken, und nun funktioniert der Dropbox Backup.
Zu Datei-Größenbeschränkungen auf Dropbox habe ich das [hier](https://help.dropbox.com/de-de/installs-integrations/sync-uploads/upload-limitations#:~:text=Hinweis%3A%20Jede%20Datei%2C%20die%20Sie,einer%20Gr%C3%B6%C3%9Fenbeschr%C3%A4nkung%20von%20350%20GB.) gefunden.

**Comment by simatec** [comment]
Darf ich fragen, was du da alles drin hast? Mir kommt das viel zu groß vor.

**Comment by Knallochse** [comment]
Die größten Dateien sind animierte GIF´s (z.Bsp. für Wetterzustände) für meine VIS.
Darauf möchte ich aber nicht verzichten.
