### ISSUE TITLE
backitup.0.history.json / storage value = ["Google Drive"]

### ISSUE THREAD

**Issue by darkdan2000** [simatec/ioBroker.backitup#484]
The value "storage" in the data point backitup.0.history.json seems to be generated incorrectly when backing up to GoogleDrive. So I get an "undefined" in VIS for the storage value in my table. The square brackets [] should be removed here. Or should this be so?

[{"date":"09. Mai 2021 um 10:18 Uhr","name":"iobroker_2021_05_09-10_16_24_backupiobroker.tar.gz","type":"iobroker","storage":**[**"Google Drive"**]**,"filesize":"20MB","error":"none","timestamp":1620548286458}]

**Comment by simatec** [comment]
Fix in Version 2.1.12
