### ISSUE TITLE
Dokumentation: Hinweis auf möglichen Fehler bei Javascript Sicherung

### ISSUE THREAD

**Issue by pseisam** [simatec/ioBroker.backitup#485]
Man könnte eventuell einen kleinen Hinweis bei der Javascript-Sicherung ergänzen:

Und zwar ist es so, wenn man im Javascript Adapter beim Mirroring einen Pfad angibt, auf dem das Modul keine Schreibrechte hat (ich hatte da das Home-Verzeichnis des Standardusers vom Raspberry genommen), dann schlägt das Spiegeln aller Javascripte in den Ordner fehl. Blöderweise führt das dazu, dass die original Javascripte auch direkt gelöscht werden. Das ist vor einem Backup eher unschön.

Natürlich ist das eher ein Fehler des Javascript Adapters (war übrigens noch die 4er Version), aber ein kurzer Hinweis darauf kann in der Doku nicht schaden.

**Comment by simatec** [comment]
Ab Version 2.2.0 wird der Spiegelpfad nicht mehr benötigt. 
Backitup sichert direkt aus dem System.
