### ISSUE TITLE
Jarvis wird nicht gesichert

### ISSUE THREAD

**Issue by msiemers** [simatec/ioBroker.backitup#487]
Ich habe im Adapter angehalten, das Jarvis gesichert werden soll. 
Wenn ich die iOBroker Sicherung durchführe, wird Jarvis nicht mit gesichert.

**Comment by simatec** [comment]
Was steht im Debug Log?

**Comment by msiemers** [comment]
Wo finde ich das?

**Comment by simatec** [comment]
Du musst die Instanz von Backitup auf debug stellen und den Log vom Backupprozess hier posten

**Comment by msiemers** [comment]
Started iobroker ...
[DEBUG] [mount] start with {"mountType":"CIFS","type":"storage","source":"cifs","mount":"//192.168.1.27","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=3.0","sudo":true,"cifsDomain":"","clientInodes":true,"deleteOldBackup":true,"ownDir":true,"bkpType":"Minimal","dir":"/Dokumente/Marco/Datensicherung/smarthome/iobroker","dirMinimal":"/Dokumente/Marco/Datensicherung/smarthome/iobroker","user":"******","pass":"****"}
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] start with {"type":"creator","time":"02:00","debugging":true,"everyXDays":"1","deleteBackupAfter":0,"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"//192.168.1.27","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=3.0","sudo":true,"cifsDomain":"","clientInodes":true,"deleteOldBackup":true,"ownDir":true,"bkpType":"Minimal","dir":"/Dokumente/Marco/Datensicherung/smarthome/iobroker","dirMinimal":"/Dokumente/Marco/Datensicherung/smarthome/iobroker","user":"*****","pass":"****","context":{"fileNames":[],"errors":{},"done":["mount"],"types":[]},"adapter":null},"dir":"/opt/iobroker","jarvis":{"enabled":true,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal","user":"","pass":"****","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"192.168.1.27","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=3.0","sudo":true,"cifsDomain":"","clientInodes":true,"deleteOldBackup":true,"ownDir":true,"bkpType":"Minimal","dir":"/Dokumente/Marco/Datensicherung/smarthome/iobroker","dirMinimal":"/Dokumente/Marco/Datensicherung/smarthome/iobroker","user":"**+*+*","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},"webdav":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal"},"path":"/opt/iobroker/iobroker-data"},"historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"none","onlyError":false,"telegramWaiting":0,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longWhatsappNotice","onlyError":false,"whatsappWaiting":0,"systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [iobroker] - host.smarthome 3543 states saved

[DEBUG] [iobroker] - host.smarthome 6110 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_05_17-20_18_55_backupiobroker.tar.gz

[DEBUG] [iobroker] - done

**Comment by simatec** [comment]
Da fehlt noch etwas. 
mach mal bitte den Debug in der Backitup Konfiguration aus und nur den Debug der Adapter Instanz

**Comment by msiemers** [comment]
Dann kommt nur noch dieses.

Started iobroker ...
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.smarthome 3543 states saved

[DEBUG] [iobroker] - host.smarthome 6110 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_05_17-21_09_16_backupiobroker.tar.gz

[DEBUG] [iobroker] - done

**Comment by simatec** [comment]
Dann ist Jarvis nicht aktiv? 
welche Version von Jarvis und Backitup hast du installiert?

**Comment by msiemers** [comment]
Doch der Haken ist gesetzt.

Version Backitup: 2.1.10
Version Jarvis: 2.2.0

**Comment by simatec** [comment]
Lass mal bitte folgendes laufen

`iobroker fix`

**Comment by msiemers** [comment]
Habe ich durchgeführt.

Folgendes Ergebins:

Started iobroker ...
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.smarthome 3545 states saved

[DEBUG] [iobroker] - host.smarthome 6113 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_05_17-23_41_45_backupiobroker.tar.gz

[DEBUG] [iobroker] - done

**Comment by simatec** [comment]
Der Backupprozess wird bei dir nicht abgeschlossen.
Zeige mal bitte deine Konfiguration.

Des Weiteren deaktiviere mal bitte das Jarvis Backup und schaue, ob dann der Prozess abgeschlossen wird

**Comment by msiemers** [comment]
Wenn ich Jarvis deaktiviere gehts.

Started iobroker ...
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.smarthome 3549 states saved

[DEBUG] [iobroker] - host.smarthome 6113 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_05_18-20_44_55_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [cifs] - done
[DEBUG] [clean] - done
[DEBUG] [telegram] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[DEBUG] [umount] - mount activ, umount is started ...
[DEBUG] [umount] - umount successfully completed
[DEBUG] [umount] - done
[EXIT] 0

Welche Konfiguration wird benötigt?

**Comment by msiemers** [comment]
@simatec Bei dem Versuch Daten zurückzusichern gibts folgende Meldung:

Error: {"errno":-1,"code":"EPERM","syscall":"utime","path":"/opt/iobroker/backups/jarvis_0/"}

Gibt es eventuell irgendwelche Rechtsprobleme?
