### ISSUE TITLE
Backitup startet und stoppt Sekundenweise in Dauerschleife

### ISSUE THREAD

**Issue by quorle** [simatec/ioBroker.backitup#49]
Mein Adapter stoppt und startet Sekundenweise. Das war vor dem letzten Update nicht.

Logmeldungen:

`

host.raspberry_io.Broker_CCU2 | 2018-10-05 08:57:17.178 | info | Restart adapter system.adapter.backitup.0 because enabled
-- | -- | -- | --
host.raspberry_io.Broker_CCU2 | 2018-10-05 08:57:17.178 | error | instance system.adapter.backitup.0 terminated with code 7 (Adapter already running)
upnp.0 | 2018-10-05 08:57:17.140 | info | Found new device: "http://192.168.2.1:35247/rootDesc.xml"
backitup.0 | 2018-10-05 08:57:17.122 | error | already running
upnp.0 | 2018-10-05 08:57:17.109 | info | Found new device: "http://192.168.2.1:35247/rootDesc.xml"
backitup.0 | 2018-10-05 08:57:17.075 | debug | statesDB connected
upnp.0 | 2018-10-05 08:57:17.033 | info | Found new device: "http://192.168.2.1:35247/rootDesc.xml"
backitup.0 | 2018-10-05 08:57:16.962 | debug | objectDB connected

`

Version Backitup:      0.3.5

**Comment by simatec** [comment]
Starte mal dein iobroker neu und installiere ggfs. backitup neu.
Des Weiteren könntest du backitup mal in der Instanz auf debug stellen, damit wir einen aussagekräftigen Log haben.
