### ISSUE TITLE
cifs mount - mount: only root can use "--options" option

### ISSUE THREAD

**Issue by chrisx51** [simatec/ioBroker.backitup#494]
Hello, my tests with Manual mounting my synology cifs drive have been succesfull finally.
But seems backitup is using some mechanism that prevents non-root from using the mount.
I have this in my log:

<html><body>

backitup.0 | 2021-05-16 23:17:49.053 | error | mount: only root can use "--options" option
-- | -- | -- | --
backitup.0 | 2021-05-16 23:17:49.053 | error | (28278) Error: Command failed: mount -t cifs -o  username=iobroker,password=****,rw,file_mode=0777,dir_mode=0777  //**MYSERVER***/Backup\iobroker /opt/iobroker/backups

</body>
</html>

This is my manual mount with root working:
`sudo mount -t cifs //**MYSERVER***/Backup/iobroker /var/backups --verbose -o vers=1.0,username=iobroker,password=mypassword
mount.cifs kernel mount options: ip=2a02:8071:6c3:9300:211:32ff:fe3b:6ac8,unc=\\**MYSERVER***\Backup,vers=1.0,user=iobroker,prefixpath=iobroker,pass=********
`

I found that fstab needs to be updated so it allows non-root to mount using options, but this is not possible by using the full mount form:
[https://community.hpe.com/t5/General/mount-only-root-can-do-that-why/m-p/4467749/highlight/true#M17566](url)

is there anything i can do to make it work?

**Comment by simatec** [comment]
The user iobroker needs a sudo for the mount.
Please activate the sudo-mount option in the NAS settings of Backitup

**Comment by chrisx51** [comment]
> 
> 
> The user iobroker needs a sudo for the mount.
> Please activate the sudo-mount option in the NAS settings of Backitup

thank you @simatec , i just tested with this option, but i now get another error:
`Started iobroker ...
[DEBUG] [mount] - first mount attempt with smb option failed. try next mount attempt without smb option ...
[ERROR] [mount] - [undefined Error: Command failed: sudo mount -t cifs -o username=iobroker,password=****,rw,file_mode=0777,dir_mode=0777 //***SERVER***/Backup\iobroker /opt/iobroker/backups
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
[ERROR] [mount] - [IGNORED] Error: Command failed: sudo mount -t cifs -o username=iobroker,password=****,rw,file_mode=0777,dir_mode=0777 //***SERVER***/Backup\iobroker /opt/iobroker/backups
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
[DEBUG] [iobroker] - host.raspberry2 5751 states saved
[DEBUG] [iobroker] - host.raspberry2 6701 objects saved
[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_05_24-17_45_04_backupiobroker.tar.gz`

Anything else wrong now? Still the manual mount as shown above works fine, also with creating files on the NAS.

**Comment by simatec** [comment]
Please show your complete config

**Comment by chrisx51** [comment]
@simatec Please see below:
![grafik](https://user-images.githubusercontent.com/56371432/119624370-5bdb1680-be09-11eb-94fc-c16e0b568c0e.png)
Or is there another place that gives better overview?

**Comment by Grothesk242** [comment]
Try putting a slash, not a backslash
Backup/iobroker

SMB 1.0 is most likely the wrong protocol version. The whole world should have moved to smb > 2.0
