### ISSUE TITLE
Permission denied?

### ISSUE THREAD

**Issue by StephanWagner87** [simatec/ioBroker.backitup#496]
Hi,
i just installed BackitUp 2.1.6 on my Raspberry PI. Which permissions are needed for the ioBroker User? I dont want to give him full admin Rights. 
<img width="694" alt="image" src="https://user-images.githubusercontent.com/49068001/118599707-45e9a800-b7b0-11eb-8a8c-876ab4819b44.png">

**Comment by simatec** [comment]
Can you please set the instance of backitup to debug and post me the complete debug log from the backup process

Which js-controller version is installed?

Have you already run the iobroker fix?

`iobroker fix`

What does your Backitup config look like? Do you store locally or on a NAS?

**Comment by StephanWagner87** [comment]
Hi,
thanks for your fast reply.
this is the debug log and Node.js v12.22.1 is installed. I runed iobroker fix already and i try to do a backup to google drive and Dropbox.

backitup.0 | 2021-05-18 09:16:01.630 | info | (8965) [iobroker] backup was activated at 02:40 every 7 day(s)
-- | -- | -- | --
backitup.0 | 2021-05-18 09:16:01.523 | info | (8965) starting. Version 2.1.6 in /opt/iobroker/node_modules/iobroker.backitup, node: v12.22.1, js-controller: 3.2.16
backitup.0 | 2021-05-18 09:15:54.339 | info | (8767) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
backitup.0 | 2021-05-18 09:15:54.337 | info | (8767) terminating
backitup.0 | 2021-05-18 09:15:54.335 | info | (8767) cleaned everything up...
backitup.0 | 2021-05-18 09:15:54.333 | info | (8767) Got terminate signal TERMINATE_YOURSELF
backitup.0 | 2021-05-18 09:15:41.875 | info | (8767) [iobroker] backup was activated at 02:40 every 7 day(s)
backitup.0 | 2021-05-18 09:15:41.793 | info | (8767) starting. Version 2.1.6 in /opt/iobroker/node_modules/iobroker.backitup, node: v12.22.1, js-controller: 3.2.16
backitup.0 | 2021-05-18 09:12:05.902 | info | (27143) Got terminate signal TERMINATE_YOURSELF
backitup.0 | 2021-05-18 09:12:05.868 | info | (27143) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
backitup.0 | 2021-05-18 09:12:05.665 | info | (27143) cleaned everything up...

**Comment by simatec** [comment]
Unfortunately, this is not the debug log from the backup process
