### ISSUE TITLE
Influxdb Backup

### ISSUE THREAD

**Issue by gedongi** [simatec/ioBroker.backitup#499]
Hallo Zusammen,
ich habe ein Problem beim Backup von InfluxDB.

Started iobroker ...
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.RASPI4 8539 states saved

[DEBUG] [iobroker] - host.RASPI4 8810 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_05_22-10_26_58_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[ERROR] [influxDB] - [IGNORED] Error: Command failed: influxd backup -portable -database iobroker "/opt/iobroker/backups/influxDB_2021_05_22-10_27_15_backupiobroker"
2021/05/22 10:27:16 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2s and retrying (0)...
2021/05/22 10:27:18 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2s and retrying (1)...
2021/05/22 10:27:20 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2s and retrying (2)...
2021/05/22 10:27:22 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2s and retrying (3)...
2021/05/22 10:27:24 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2s and retrying (4)...
2021/05/22 10:27:26 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2s and retrying (5)...
2021/05/22 10:27:28 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 3.01s and retrying (6)...
2021/05/22 10:27:31 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 11.441s and retrying (7)...
2021/05/22 10:27:42 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 43.477s and retrying (8)...
2021/05/22 10:28:26 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2m45.216s and retrying (9)...
2021/05/22 10:31:11 error (copy backup to file: err=<nil>, n=0) when backing up db: iobroker, rp autogen, shard 2. continuing backup on remaining shards
2021/05/22 10:31:12 backup failed: copy backup to file: err=<nil>, n=0
backup: copy backup to file: err=<nil>, n=0

[DEBUG] [cifs] - done
[ERROR] [clean] - Backup files not deleted from /opt/iobroker/backups because some errors.
[DEBUG] [clean] - done
[DEBUG] [email] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[DEBUG] [umount] - mount activ, umount is started ...
[DEBUG] [umount] - umount successfully completed
[DEBUG] [umount] - done

Das Backup soll mit cifs auf meine Nas(Fritzbox) gespeichert werden.
Die Influx Datenbank liegt auf einem USB Stick gemounted am Raspi.

Raspi 4B/4GB, Buster
Backitup Version 2.1.10
InfluxDB Version 1.9.5
Node.js Version 12.22.1
JS-controller Version 3.2.16

InfluxDB Einstellungen
![image](https://user-images.githubusercontent.com/37265486/119220164-6a63be00-bae9-11eb-8d01-37aab29742e1.png)

Backitup InfluxDB Einstellungen
![image](https://user-images.githubusercontent.com/37265486/119220174-80717e80-bae9-11eb-982f-5923e5e82faf.png)

Ich hoffe jemand kann helfen.
Danke...

**Comment by simatec** [comment]
Ist Influx auf dem System installiert? Wie kann ich die Aussage verstehen, dass die db auf einem USB Stick ist?

**Comment by simatec** [comment]
Prüfe mal, ober der User iobroker die Rechte für en USB-Stick besitzt.

**Comment by gedongi** [comment]
Der USB stick wird mit INFLUXDB/INFLUXDB gemountet. Ich habe ihn ebenfalls gerade mit IOBROKER/IOBROKER gemountet.
Damit tritt das Problem auf das Grafana nicht mehr auf die Datenbank zugreifen kann. Beim Backup mit Backitup kamen folgende Meldungen...

Started iobroker ...
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.RASPI4 8611 states saved

[DEBUG] [iobroker] - host.RASPI4 8799 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_06_01-12_16_59_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[ERROR] [influxDB] - [IGNORED] Error: Command failed: influxd backup -portable -database iobroker "/opt/iobroker/backups/influxDB_2021_06_01-12_17_24_backupiobroker"
2021/06/01 12:17:24 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2s and retrying (0)...
2021/06/01 12:17:26 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2s and retrying (1)...
2021/06/01 12:17:28 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2s and retrying (2)...
2021/06/01 12:17:30 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2s and retrying (3)...
2021/06/01 12:17:32 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2s and retrying (4)...
2021/06/01 12:17:34 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2s and retrying (5)...
2021/06/01 12:17:36 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 3.01s and retrying (6)...
2021/06/01 12:17:39 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 11.441s and retrying (7)...
2021/06/01 12:17:50 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 43.477s and retrying (8)...
2021/06/01 12:18:34 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2m45.216s and retrying (9)...
backup: dial tcp [::1]:8088: connect: connection refused

[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
[DEBUG] [grafana] - found Dashboard: 005-pv-eigenvbrauch
[DEBUG] [grafana] - found Dashboard: energie
[DEBUG] [grafana] - found Dashboard: 001-aussen
[DEBUG] [grafana] - found Dashboard: 004-kuhlschrank
[DEBUG] [grafana] - found Dashboard: 003-heisswasser
[DEBUG] [grafana] - found Dashboard: 001-tankstellen
[DEBUG] [grafana] - found Dashboard: tanken
[DEBUG] [grafana] - found Dashboard: temperatur
[DEBUG] [grafana] - found Dashboard: 001-energie
[DEBUG] [grafana] - found Dashboard: 004-pv-eigenverbrauch
[DEBUG] [grafana] - found Dashboard: 003-pv-einspeisung
[DEBUG] [grafana] - found Dashboard: 002-pv-ertrag
[DEBUG] [grafana] - found Dashboard: 002-raum
[DEBUG] [grafana] - start Grafana backup compress ...
[DEBUG] [grafana] - Backup created: /opt/iobroker/backups/grafana_2021_06_01-12_21_22_backupiobroker.tar.gz
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[DEBUG] [grafana] - done
[DEBUG] [javascripts] - Backup created: /opt/iobroker/backups/javascripts_2021_06_01-12_21_29_backupiobroker.tar.gz
[DEBUG] [javascripts] - done
[DEBUG] [cifs] - done
[ERROR] [clean] - Backup files not deleted from /opt/iobroker/backups because some errors.
[DEBUG] [clean] - done
[DEBUG] [email] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[DEBUG] [umount] - mount activ, umount is started ...
[DEBUG] [umount] - umount successfully completed
[DEBUG] [umount] - done
[EXIT] 0 


Gruß

**Comment by gedongi** [comment]
Nach update auf die Backitup Version 2.1.13 folgender Stand
INFLUXDB wird bei mir weiterhin nicht gesichert...

Started iobroker ...
[DEBUG] [mount] - mount activ... umount is started before mount!!
[DEBUG] [mount] - umount successfully completed
[DEBUG] [mount] - noserverino option: true
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=****,password=****,noserverino,rw,file_mode=0777,dir_mode=0777,vers=3.1.1 //192.168.178.1/FBML-01/NASPAS/08_HOMEMATIC/04_BACKUP/IOBROKER/RASPI4 /opt/iobroker/backups"
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.RASPI4 8602 states saved

[DEBUG] [iobroker] - host.RASPI4 8878 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_07_06-14_28_48_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[ERROR] [influxDB] - [IGNORED] Error: Command failed: influxd backup -portable -database iobroker "/opt/iobroker/backups/influxDB_2021_07_06-14_29_22_backupiobroker"
2021/07/06 14:29:23 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2s and retrying (0)...
2021/07/06 14:29:25 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2s and retrying (1)...
2021/07/06 14:29:27 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2s and retrying (2)...
2021/07/06 14:29:29 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2s and retrying (3)...
2021/07/06 14:29:31 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2s and retrying (4)...
2021/07/06 14:29:33 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2s and retrying (5)...
2021/07/06 14:29:35 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 3.01s and retrying (6)...
2021/07/06 14:29:38 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 11.441s and retrying (7)...
2021/07/06 14:29:49 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 43.477s and retrying (8)...
2021/07/06 14:30:33 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Waiting 2m45.216s and retrying (9)...
2021/07/06 14:33:18 error (copy backup to file: err=<nil>, n=0) when backing up db: iobroker, rp autogen, shard 2. continuing backup on remaining shards
2021/07/06 14:33:19 backup failed: copy backup to file: err=<nil>, n=0
backup: copy backup to file: err=<nil>, n=0

[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
[DEBUG] [grafana] - found Dashboard: 005-pv-eigenvbrauch
[DEBUG] [grafana] - found Dashboard: 002-raum
[DEBUG] [grafana] - found Dashboard: 001-energie
[DEBUG] [grafana] - found Dashboard: energie
[DEBUG] [grafana] - found Dashboard: 001-aussen
[DEBUG] [grafana] - found Dashboard: 003-pv-einspeisung
[DEBUG] [grafana] - found Dashboard: 003-heisswasser
[DEBUG] [grafana] - found Dashboard: 001-tankstellen
[DEBUG] [grafana] - found Dashboard: 002-pv-ertrag
[DEBUG] [grafana] - found Dashboard: 004-kuhlschrank
[DEBUG] [grafana] - found Dashboard: 004-pv-eigenverbrauch
[DEBUG] [grafana] - found Dashboard: tanken
[DEBUG] [grafana] - found Dashboard: temperatur
[DEBUG] [grafana] - start Grafana backup compress ...
[DEBUG] [grafana] - Backup created: /opt/iobroker/backups/grafana_2021_07_06-14_33_22_backupiobroker.tar.gz
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[DEBUG] [grafana] - done
[DEBUG] [javascripts] - Backup created: /opt/iobroker/backups/javascripts_2021_07_06-14_33_30_backupiobroker.tar.gz
[DEBUG] [javascripts] - done
[DEBUG] [cifs] - done
[ERROR] [clean] - Backup files not deleted from /opt/iobroker/backups because some errors.
[DEBUG] [clean] - done
[DEBUG] [email] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[DEBUG] [umount] - mount activ, umount is started ...
[DEBUG] [umount] - umount successfully completed
[DEBUG] [umount] - done
[EXIT] 0

Zur Backup Laufzeit wird ein Ordner angelegt mit den 3 files aber am Ende wird er wider komplett gelöscht.
![image](https://user-images.githubusercontent.com/37265486/124601808-8dafb600-de68-11eb-85fb-842bc19f3051.png)

**Comment by simatec** [comment]
In Version 2.1.13 wurde da auch nichts geändert. Das Problem liegt an deinen Rechten in Kombination mit dem USB Stick und nicht an Backitup.

**Comment by gedongi** [comment]
Ja, da wird wohl sowas sein. Kannst du einen Tipp geben wie die Rechte sein sollten vom USB Stick? Was benötigt Backitup?
Im Moment sieht es so aus...
![image](https://user-images.githubusercontent.com/37265486/124617171-03228300-de77-11eb-88ab-fa54a9a29165.png)

Wenn ich Besitzer/Gruppe ändere dann kann aber Influx nicht mehr auf den USB Stick zugreifen.

**Comment by simatec** [comment]
Backitup hat da keinen Einfluss ... Der User "iobroker" benötigt die Rechte.

Teste erstmal ein manuelles Backup.

Erstelle ein Verzeichnis mit dem user "iobroker"

`sudo -u iobroker mkdir /opt/iobroker/backups/influxbackup`

Danach versuche mit dem User "iobroker" ein Backup auszuführen:

`sudo -u iobroker influxd backup -portable -database iobroker /opt/iobroker/backups/influxbackup`
