### ISSUE TITLE
Check if option 'noserverino' get honoured in SMB mounts

### ISSUE THREAD

**Issue by Grothesk242** [simatec/ioBroker.backitup#500]
When a SMB-Share geht mounted with option 'noserverino' set, the mount looks like this: 

```
echad@chet:~ $ mount | grep ^//
//192.168.178.1/FRITZ.NAS/usbbackup/iobrokerbackup/chet on /opt/iobroker/backups type cifs (rw,relatime,vers=3.1.1,cache=strict,username=iobroker,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.178.1,file_mode=0777,dir_mode=0777,soft,nounix,mapposix,rsize=65536,wsize=65536,bsize=1048576,echo_interval=60,actimeo=1)
```
No clear sign of noserverino being honoured. 

When the option is not set, the mount looks like this: 
```
echad@chet:~ $ mount | grep ^//
//192.168.178.1/FRITZ.NAS/usbbackup/iobrokerbackup/chet on /opt/iobroker/backups type cifs (rw,relatime,vers=3.1.1,cache=strict,username=iobroker,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.178.1,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,rsize=65536,wsize=65536,bsize=1048576,echo_interval=60,actimeo=1)
```
serverino is mentioned in the mount options. 
I'm not sure but I think noserverino-Option should appear the same way it's sibling does.

**Comment by simatec** [comment]
In version 2.1.12 I added some debug logs for the mount.
Can you please test the version?

Installation via Github (dev branch)

https://github.com/simatec/ioBroker.backitup/tarball/dev

**Comment by Grothesk242** [comment]
I installed 2.12 via Beta Repo. Does the git version differ?

Am Di., 1. Juni 2021 um 11:44 Uhr schrieb simatec ***@***.***

**Comment by simatec** [comment]
the version in the beta repo is correct

**Comment by Grothesk242** [comment]
I only get 

```
[Di Jun  1 20:44:09 2021] CIFS: VFS: bogus file nlink value 0
[Di Jun  1 20:44:10 2021] CIFS: VFS: bogus file nlink value 0
[Di Jun  1 20:44:22 2021] CIFS: VFS: bogus file nlink value 0
[Di Jun  1 20:44:24 2021] CIFS: VFS: bogus file nlink value 0
[Di Jun  1 20:44:26 2021] CIFS: VFS: bogus file nlink value 0
[Di Jun  1 20:44:28 2021] CIFS: VFS: bogus file nlink value 0
[Di Jun  1 20:44:36 2021] CIFS: VFS: bogus file nlink value 0
```
when google drive is accessing the mount point /opt/iobroker/backups 
Both backups (the FritzNAS one and the Google Drive one) are fully functional. I'd say leave it like that. I can live with the reoccuring entries in dmesg.
