### ISSUE TITLE
Grafana Backup nicht möglich

### ISSUE THREAD

**Issue by pruse007** [simatec/ioBroker.backitup#501]
Hallo,
Grafana Backup läuft nicht durch ioBroker, Homatic CCU und InfluxDB werden gesichert.
Grafana 7.5.7
ioBroker 4.2.1
Speicherort: Google Drive

grafana Config :
 
Server: 192.168.1.42
Port: 3000
Grafana Benutzername : backitup 
Passwort: XXXXXXXXXX
Grafana API-Key: XXXXXXXXXXXXXX wurde in grafana erstellt
 
 [DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
[DEBUG] [grafana] - Error on Grafana Datasource Request
[DEBUG] [grafana] - found Dashboard: test
[DEBUG] [grafana] - found Dashboard: dashboard
[DEBUG] [grafana] - start Grafana backup compress ...
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[DEBUG] [grafana] - cannot found Grafana Backup files
[DEBUG] [grafana] – done
 

Gruß Jens

**Comment by simatec** [comment]
Hast du den Api Key als Admin erstellt?
Lasse mal `iobroker fix` zusätzlich laufen, um ggfs. ein Rechteproblem zu beheben. 
Der ApiKey muss mit vollen Lese und Schreibrechten erstellt sein.
