### ISSUE TITLE
Cannot parse answer: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Rooby69** [simatec/ioBroker.backitup#503]
When backup the CCU the I get an error
[ERROR] [ccu] - [IGNORED] Cannot parse answer: SyntaxError: Unexpected token < in JSON at position 0

Setup CCU on Raspberry (Debmatic) and IoBroker on the same Raspberry.
Use NAS with CIF for storage.

The full log when trigger a CCU backup:
Started ccu ...
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[ERROR] [ccu] - [IGNORED] Cannot parse answer: SyntaxError: Unexpected token < in JSON at position 0
[DEBUG] [cifs] - done
[DEBUG] [clean] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[DEBUG] [umount] - mount activ, umount is started ...
[DEBUG] [umount] - umount successfully completed
[DEBUG] [umount] - done
[EXIT] 0

Note: Backup of ioBroker was succesful but not CCU.

**Comment by simatec** [comment]
Please post your config from Backitup.
Do you have the https option active in the CCU? Backitup does not currently support this.
Please check username and password. The same data must be used here as with the web interface of your CCU.

**Comment by Rooby69** [comment]
Hi 
thanks for your help.
I found the issue now. The problem was I have changed the port of the CCU to 8080 and after I updated the IP address with :8080 then it worked.
Issue can be closed.
