### ISSUE TITLE
PostgreSQL Backup startet nicht

### ISSUE THREAD

**Issue by gmoerth** [simatec/ioBroker.backitup#508]
**Describe the bug**  
PostgreSQL Backup startet nicht

**To Reproduce**  
1. Aktivert
2. Server, Post, Name, Benutzer, Passwort ausgefüllt 
3. gespeichert und Backup gestartet
4. keine Fehlermeldung, alle anderen backups werden ausgeführt. (bei mir ioBroker, Homematic, CCU, Redis, History Daten, PostgreSQL, Grafana.

**Expected behavior**  
testweise habe ich die "30-pgsql.js" in "30-mysql.js" umbenannt und meine Daten hard coded in Zeile 16 eingefügt.
Damit funktioniert es 👍 

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <2.1.12>
 - JS-Controller version: <3.3.11> 
 - Node version: <12.22.1> 
 - Operating system: <os-name>
PlatformBetriebssystem:linux
Architektur:arm
CPUs:4
Geschwindigkeit:1500 MHz
Modell:ARMv7 Processor rev 3 (v7l)
RAM:3.7 GB
System-Betriebszeit:10 T. 17:13:57
Node.js:v12.22.1
NPM:6.14.12
Datenträgergröße:14.3 GB
Festplatte frei:5.4 GB
Adapter-Anzahl:418
Betriebszeit:10 T. 18:13:31
Aktive Instanzen:15
Pfad:/opt/iobroker/

**Additional context**

**Comment by simatec** [comment]
Fix in Version 2.1.13
