### ISSUE TITLE
No scheduled backups and no proper restore for InfluxDB 

### ISSUE THREAD

**Issue by Niko11111** [simatec/ioBroker.backitup#509]
I had some problems with my raspberry recently. So I decided to go back to an 1 month old backedup image and then restore to an 1 week old iobroker backup. (one week old, because that is how long the pi wasn't working.) The iobroker restore worked fine but the influxdb restore does not work.
First in the Log it tells me that the database already exists so I used "drop database" in influx. And after another restore It gives me a lot of errors an Grafana does not show me any data. So something is not working right

Plus: for the last month the scheduled backups function does not work for me. It is set up, but it does not back up.

I am new in the hole iobroker stuff. So please forgive me, but what logs do you need?

**Comment by simatec** [comment]
The old database must not exist for an influx restore.  
The Influx Adapter must be stopped, otherwise it would create the database again and again, which leads to an error when restoring.  

Everything is described in detail in the documentation on Backitup.

**Comment by Niko11111** [comment]
Thanks for the quick responds. I thought I did stop the adapter. I did as you sad and it did work. But I found the problem. I needed to reconnect the influxdb database in Grafana. 

Do you have any ideas how I can fix the not working scheduled backup?
Thanks for the great work!

**Comment by simatec** [comment]
I would run "iobroker fix" and restart the entire system.

If this does not solve the problem, uninstall Backitup in the instances and in the adapters and then reinstall.
