### ISSUE TITLE
Grafana 8.0 Backup nicht mehr möglich 

### ISSUE THREAD

**Issue by pruse007** [simatec/ioBroker.backitup#510]
Hallo,
seit dem Update auf Grafana 8.0 läuft das backup für Grafana nicht mehr, Backup ioBroker, Homatic CCU und InfluxDB werden gesichert.
Grafana 8.0.0
ioBroker 4.2.1
BackItUp 2.1.12

Speicherort: Google Drive

grafana Config :

Server: 192.168.1.18
Port: 3000
Grafana Benutzername : backitup "Admin"
Passwort: XXXXXXXXXX
Grafana API-Key: XXXXXXXXXXXXXX wurde in grafana mit Admin Rolle erstellt

[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
[DEBUG] [grafana] - Error on Grafana Dashoard backup: Error: Request failed with status code 404
[DEBUG] [grafana] - start Grafana backup compress ...
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[DEBUG] [grafana] - cannot found Grafana Backup files
[DEBUG] [grafana] - done

Gruß

Jens

**Comment by simatec** [comment]
Kann es sein, dass du dazu auch im Forum geschrieben hast?

**Comment by pruse007** [comment]
Hallo,nein habe in keinem Forumüber mein Problem  geschrieben. Welches Forum sollte das sein. Gruß Jens Am 13.06.2021 21:52 schrieb simatec ***@***.***>:
Kann es sein, dass du dazu auch im Forum geschrieben hast?

**Comment by simatec** [comment]
Ab Version 2.1.13 wird Grafana 8.x unterstützt. In Version 8 von Grafana gab es dort Änderungen
