### ISSUE TITLE
Nach bzw. während Backup IOBroker stürzt komplett ab und startet neu

### ISSUE THREAD

**Issue by Bjoern2006** [simatec/ioBroker.backitup#511]
Seit dem Update auf Version 2.1.11 stürzt mein komplettes IOBroker System bei einem IOBroker-Backup komplett ab.
Bei den vorherigen Versionen war das nie der Fall.

Die Einstellungen wurden nicht geändert.

Bitte schnellstmöglich beheben.

Edit: Auch bei Version 2.1.12 ist dasselbe Probleme.

**Comment by simatec** [comment]
Was soll denn behoben werden?
Kein Log, keine Infos …
Bitte einen ausführlichen Debuglog posten

**Comment by Bjoern2006** [comment]
2021-06-13 21:10:43.888 - info: backitup.0 (21791) cleaned everything up...
2021-06-13 21:10:45.398 - info: backitup.0 (21791) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
2021-06-13 21:10:48.805 - error: backitup.0 (21791) Objects database error: connect ECONNREFUSED 127.0.0.1:9001


2021-06-13 21:10:48.866 -&nbsp;warn: backitup.0 (21791) get state error: DB closed
2021-06-13 21:10:48.867 -&nbsp;warn: backitup.0 (21791) get state error: DB closed
2021-06-13 21:10:48.868 -&nbsp;warn: backitup.0 (21791) redis get backitup.0.history.html, error - DB closed
2021-06-13 21:10:48.869 -&nbsp;warn: backitup.0 (21791) get state error: DB closed
2021-06-13 21:10:48.870 -&nbsp;warn: backitup.0 (21791) get state error: DB closed
2021-06-13 21:10:48.888 -&nbsp;warn: backitup.0 (21791) get state error: DB closed
2021-06-13 21:10:48.889 -&nbsp;warn: backitup.0 (21791) get state error: DB closed
2021-06-13 21:10:48.889 -&nbsp;warn: backitup.0 (21791) get state error: DB closed
2021-06-13 21:10:48.890 -&nbsp;warn: backitup.0 (21791) get state error: DB closed
2021-06-13 21:10:48.891 -&nbsp;warn: backitup.0 (21791) get state error: DB closed
2021-06-13 21:10:48.891 -&nbsp;warn: backitup.0 (21791) get state error: DB closed
2021-06-13 21:10:48.892 -&nbsp;warn: backitup.0 (21791) get state error: DB closed
2021-06-13 21:10:48.892 -&nbsp;warn: backitup.0 (21791) get state error: DB closed
2021-06-13 21:10:48.893 -&nbsp;warn: backitup.0 (21791) get state error: DB closed

2021-06-13 21:10:53.820 - error: backitup.0 (21791) Cannot check object existence of "backitup.0.output.line": Connection is closed.


Mehr kann ich aus dem Log nicht raus lesen bzw. veröffentlichen!

**Comment by Bjoern2006** [comment]
Was behoben werden soll?
Das ein Backup meines IOBroker Systems wieder möglich ist...

**Comment by simatec** [comment]
Da scheint bei deinem Update mächtig was schief gegangen zu sein. 
versuche ein Upload von Backitup. 
sollte die nix bringen, den Adapter mal in den Instanzen und in den Adaptern deinstallieren und im Anschluss neu installieren. 
Aus irgendwelchen Gründen fehlen Objekte, die sich nicht von alleine löschen. Kann es sein, dass du da eventuell Objekte gelöscht hast?

**Comment by Bjoern2006** [comment]
Ok sehr merkwürdig.
Ich habe definitiv keine Objekte gelöscht. Dann werd ich das mal versuchen und den Adapter komplett deinstallieren.

Werde Rückmeldung geben, sobald ich was neues weiß.

**Comment by simatec** [comment]
> Da scheint bei deinem Update mächtig was schief gegangen zu sein oder Objekte wurde gelöscht.
> versuche ein Upload von Backitup.
> sollte die nix bringen, den Adapter mal in den Instanzen und in den Adaptern deinstallieren und im Anschluss neu installieren.
> Aus irgendwelchen Gründen fehlen Objekte, die sich nicht von alleine löschen. Kann es sein, dass du da eventuell Objekte gelöscht hast?

Du weißt aber schon, dass man erstmal Input liefern sollte und es sich bei iobroker um ein OpenSource Projekt handelt, wo alle Entwickler in ihrer Freizeit an iobroker arbeiten

**Comment by simatec** [comment]
> Was behoben werden soll?
> Das ein Backup meines IOBroker Systems wieder möglich ist...

Du weißt aber schon, dass man erstmal Input liefern sollte und es sich bei iobroker um ein OpenSource Projekt handelt, wo alle Entwickler in ihrer Freizeit an iobroker arbeiten

**Comment by Bjoern2006** [comment]
> > Was behoben werden soll?
> > Das ein Backup meines IOBroker Systems wieder möglich ist...
> 
> Du weißt aber schon, dass man erstmal Input liefern sollte und es sich bei iobroker um ein OpenSource Projekt handelt, wo alle Entwickler in ihrer Freizeit an iobroker arbeiten

Jaja das ist mir bewusst, habe ja selbst einen Adapter.

**Comment by Bjoern2006** [comment]
> > Da scheint bei deinem Update mächtig was schief gegangen zu sein oder Objekte wurde gelöscht.
> > versuche ein Upload von Backitup.
> > sollte die nix bringen, den Adapter mal in den Instanzen und in den Adaptern deinstallieren und im Anschluss neu installieren.
> > Aus irgendwelchen Gründen fehlen Objekte, die sich nicht von alleine löschen. Kann es sein, dass du da eventuell Objekte gelöscht hast?

Ok sehr merkwürdig.
Ich habe definitiv keine Objekte gelöscht. Dann werd ich das mal versuchen und den Adapter komplett deinstallieren.

Werde Rückmeldung geben, sobald ich was neues weiß.

**Comment by Bjoern2006** [comment]
> > Da scheint bei deinem Update mächtig was schief gegangen zu sein oder Objekte wurde gelöscht.
> > versuche ein Upload von Backitup.
> > sollte die nix bringen, den Adapter mal in den Instanzen und in den Adaptern deinstallieren und im Anschluss neu installieren.
> > Aus irgendwelchen Gründen fehlen Objekte, die sich nicht von alleine löschen. Kann es sein, dass du da eventuell Objekte gelöscht hast?

**Log der Neuinstallation:**

backitup.0	2021-06-13 22:13:30.629	info	(12073) [ccu] backup was activated at 01:00 every 10 day(s)
backitup.0	2021-06-13 22:13:30.601	info	(12073) [iobroker] backup was activated at 02:00 every 1 day(s)
backitup.0	2021-06-13 22:13:30.514	info	(12073) starting. Version 2.1.12 in /opt/iobroker/node_modules/iobroker.backitup, node: v12.22.1, js-controller: 3.2.16
host.raspberrypi	2021-06-13 22:13:26.338	info	instance system.adapter.backitup.0 started with pid 12073
host.raspberrypi	2021-06-13 22:13:23.901	info	instance system.adapter.backitup.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
backitup.0	2021-06-13 22:13:23.278	info	(11918) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
backitup.0	2021-06-13 22:13:23.264	info	(11918) terminating
backitup.0	2021-06-13 22:13:23.262	info	(11918) cleaned everything up...
backitup.0	2021-06-13 22:13:23.259	info	(11918) Got terminate signal TERMINATE_YOURSELF
host.raspberrypi	2021-06-13 22:13:23.252	info	stopInstance system.adapter.backitup.0 send kill signal
host.raspberrypi	2021-06-13 22:13:23.228	info	stopInstance system.adapter.backitup.0 (force=false, process=true)

backitup.0	2021-06-13 22:11:50.633	info	(11918) [iobroker] backup was activated at 02:40 every 1 day(s)
backitup.0	2021-06-13 22:11:50.512	info	(11918) starting. Version 2.1.12 in /opt/iobroker/node_modules/iobroker.backitup, node: v12.22.1, js-controller: 3.2.16
host.raspberrypi	2021-06-13 22:11:46.315	info	instance system.adapter.backitup.0 started with pid 11918
host.raspberrypi	2021-06-13 22:11:44.292	info	iobroker exit 0
host.raspberrypi	2021-06-13 22:11:43.262	info	iobroker host.raspberrypi object system.adapter.backitup.0 created
host.raspberrypi	2021-06-13 22:11:43.198	info	iobroker host.raspberrypi Set default value of backitup.0.info.ccuNextTime: none
host.raspberrypi	2021-06-13 22:11:43.169	info	iobroker host.raspberrypi Set default value of backitup.0.info.iobrokerNextTime: none
host.raspberrypi	2021-06-13 22:11:43.140	info	iobroker host.raspberrypi Set default value of backitup.0.history.html: Noch kein Backup
host.raspberrypi	2021-06-13 22:11:43.109	info	iobroker host.raspberrypi Set default value of backitup.0.history.json: []
host.raspberrypi	2021-06-13 22:11:43.080	info	iobroker host.raspberrypi Set default value of backitup.0.history.ccuLastTime: No backups yet
host.raspberrypi	2021-06-13 22:11:43.050	info	iobroker host.raspberrypi Set default value of backitup.0.history.iobrokerLastTime: No backups yet
host.raspberrypi	2021-06-13 22:11:43.018	info	iobroker host.raspberrypi Set default value of backitup.0.history.ccuSuccess: false
host.raspberrypi	2021-06-13 22:11:42.989	info	iobroker host.raspberrypi Set default value of backitup.0.history.iobrokerSuccess: false
host.raspberrypi	2021-06-13 22:11:42.959	info	iobroker host.raspberrypi Set default value of backitup.0.oneClick.ccu: false
host.raspberrypi	2021-06-13 22:11:42.929	info	iobroker host.raspberrypi Set default value of backitup.0.oneClick.iobroker: false
host.raspberrypi	2021-06-13 22:11:42.899	info	iobroker host.raspberrypi Set default value of backitup.0.output.line:
host.raspberrypi	2021-06-13 22:11:42.842	info	iobroker host.raspberrypi object system.adapter.backitup.0.alive created
host.raspberrypi	2021-06-13 22:11:42.808	info	iobroker host.raspberrypi object system.adapter.backitup.0.connected created
host.raspberrypi	2021-06-13 22:11:42.770	info	iobroker host.raspberrypi object system.adapter.backitup.0.compactMode created
host.raspberrypi	2021-06-13 22:11:42.736	info	iobroker host.raspberrypi object system.adapter.backitup.0.cpu created
host.raspberrypi	2021-06-13 22:11:42.702	info	iobroker host.raspberrypi object system.adapter.backitup.0.cputime created
host.raspberrypi	2021-06-13 22:11:42.668	info	iobroker host.raspberrypi object system.adapter.backitup.0.memHeapUsed created
host.raspberrypi	2021-06-13 22:11:42.634	info	iobroker host.raspberrypi object system.adapter.backitup.0.memHeapTotal created
host.raspberrypi	2021-06-13 22:11:42.600	info	iobroker host.raspberrypi object system.adapter.backitup.0.memRss created
host.raspberrypi	2021-06-13 22:11:42.566	info	iobroker host.raspberrypi object system.adapter.backitup.0.uptime created
host.raspberrypi	2021-06-13 22:11:42.530	info	iobroker host.raspberrypi object system.adapter.backitup.0.inputCount created
host.raspberrypi	2021-06-13 22:11:42.496	info	iobroker host.raspberrypi object system.adapter.backitup.0.outputCount created
host.raspberrypi	2021-06-13 22:11:42.462	info	iobroker host.raspberrypi object system.adapter.backitup.0.eventLoopLag created
host.raspberrypi	2021-06-13 22:11:42.427	info	iobroker host.raspberrypi object system.adapter.backitup.0.sigKill created
host.raspberrypi	2021-06-13 22:11:42.386	info	iobroker host.raspberrypi object system.adapter.backitup.0.logLevel created
host.raspberrypi	2021-06-13 22:11:42.351	info	iobroker host.raspberrypi object backitup.0.info created
host.raspberrypi	2021-06-13 22:11:42.321	info	iobroker host.raspberrypi object backitup.0.info.latestBackup created
host.raspberrypi	2021-06-13 22:11:42.291	info	iobroker host.raspberrypi object backitup.0.info.ccuNextTime created
host.raspberrypi	2021-06-13 22:11:42.261	info	iobroker host.raspberrypi object backitup.0.info.iobrokerNextTime created
host.raspberrypi	2021-06-13 22:11:42.222	info	iobroker host.raspberrypi object backitup.0.history created
host.raspberrypi	2021-06-13 22:11:42.191	info	iobroker host.raspberrypi object backitup.0.history.html created
host.raspberrypi	2021-06-13 22:11:42.161	info	iobroker host.raspberrypi object backitup.0.history.json created
host.raspberrypi	2021-06-13 22:11:42.130	info	iobroker host.raspberrypi object backitup.0.history.ccuLastTime created
host.raspberrypi	2021-06-13 22:11:42.100	info	iobroker host.raspberrypi object backitup.0.history.iobrokerLastTime created
host.raspberrypi	2021-06-13 22:11:42.070	info	iobroker host.raspberrypi object backitup.0.history.ccuSuccess created
host.raspberrypi	2021-06-13 22:11:42.039	info	iobroker host.raspberrypi object backitup.0.history.iobrokerSuccess created
host.raspberrypi	2021-06-13 22:11:42.005	info	iobroker host.raspberrypi object backitup.0.oneClick created
host.raspberrypi	2021-06-13 22:11:41.974	info	iobroker host.raspberrypi object backitup.0.oneClick.ccu created
host.raspberrypi	2021-06-13 22:11:41.943	info	iobroker host.raspberrypi object backitup.0.oneClick.iobroker created
host.raspberrypi	2021-06-13 22:11:41.912	info	iobroker host.raspberrypi object backitup.0.output created
host.raspberrypi	2021-06-13 22:11:41.880	info	iobroker host.raspberrypi object backitup.0.output.line created
host.raspberrypi	2021-06-13 22:11:41.867	info	iobroker host.raspberrypi create instance backitup
host.raspberrypi	2021-06-13 22:11:39.775	info	iobroker add backitup --host raspberrypi

host.raspberrypi	2021-06-13 22:11:02.585	info	Updating repository "stable" under "http://download.iobroker.net/sources-dist.json"
host.raspberrypi	2021-06-13 22:11:01.837	info	iobroker exit 0
host.raspberrypi	2021-06-13 22:11:00.678	info	iobroker upload [0] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/adapter-settings.js adapter-settings.js application/javascript
host.raspberrypi	2021-06-13 22:11:00.620	info	iobroker upload [1] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/backitup.png backitup.png image/png
host.raspberrypi	2021-06-13 22:11:00.562	info	iobroker upload [2] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/backitup.svg backitup.svg image/svg+xml
host.raspberrypi	2021-06-13 22:11:00.505	info	iobroker upload [3] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/index.html index.html text/html
host.raspberrypi	2021-06-13 22:11:00.446	info	iobroker upload [4] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/index_m.html index_m.html text/html
host.raspberrypi	2021-06-13 22:11:00.375	info	iobroker upload [5] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/index_m.js index_m.js application/javascript
host.raspberrypi	2021-06-13 22:11:00.313	info	iobroker upload [6] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/style.css style.css text/css
host.raspberrypi	2021-06-13 22:10:59.688	info	iobroker upload [7] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/tab_m.html tab_m.html text/html
host.raspberrypi	2021-06-13 22:10:59.628	info	iobroker upload [8] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/tab_m.js tab_m.js application/javascript
host.raspberrypi	2021-06-13 22:10:59.525	info	iobroker upload [9] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/words.js words.js application/javascript
host.raspberrypi	2021-06-13 22:10:02.317	info	iobroker npm install simatec/ioBroker.backitup#master --loglevel error --prefix "/opt/iobroker" (System call)
host.raspberrypi	2021-06-13 22:10:02.309	info	iobroker NPM version: 7.14.0
host.raspberrypi	2021-06-13 22:10:01.394	info	iobroker install simatec/ioBroker.backitup#master
host.raspberrypi	2021-06-13 22:09:59.380	info	iobroker url "https://github.com/simatec/ioBroker.backitup/tarball/master" backitup

host.raspberrypi	2021-06-13 22:07:21.449	info	iobroker exit 0
host.raspberrypi	2021-06-13 22:07:07.014	info	iobroker npm uninstall iobroker.backitup --loglevel error --prefix "/opt/iobroker" (System call)
host.raspberrypi	2021-06-13 22:07:06.934	info	object deleted system.adapter.backitup.0
host.raspberrypi	2021-06-13 22:07:06.927	info	iobroker host.raspberrypi Deleting 27 state(s).
host.raspberrypi	2021-06-13 22:07:04.878	info	iobroker host.raspberrypi object backitup.admin deletedhost.raspberrypi Deleting 35 object(s).
host.raspberrypi	2021-06-13 22:07:04.869	info	iobroker host.raspberrypi object backitup deleted
host.raspberrypi	2021-06-13 22:07:04.860	info	iobroker host.raspberrypi file backitup.admin deleted
host.raspberrypi	2021-06-13 22:07:04.725	info	iobroker host.raspberrypi Counted 1 objects of backitup
host.raspberrypi	2021-06-13 22:07:03.414	info	iobroker host.raspberrypi Counted 15 states (system.adapter.backitup.*) from states
host.raspberrypi	2021-06-13 22:07:03.383	info	iobroker host.raspberrypi Counted 12 states (io.backitup.*) from states
host.raspberrypi	2021-06-13 22:07:03.371	info	iobroker host.raspberrypi Counted 15 states of system.adapter.backitup
host.raspberrypi	2021-06-13 22:07:03.336	info	iobroker host.raspberrypi Counted 12 states of backitup
host.raspberrypi	2021-06-13 22:07:03.288	info	iobroker host.raspberrypi Counted 4 channels of backitup
host.raspberrypi	2021-06-13 22:07:03.205	info	iobroker host.raspberrypi Counted 1 adapter for backitup
host.raspberrypi	2021-06-13 22:07:03.182	info	iobroker host.raspberrypi Counted 1 meta of backitup
host.raspberrypi	2021-06-13 22:07:03.127	info	iobroker host.raspberrypi Counted 1 instances of backitup
host.raspberrypi	2021-06-13 22:07:03.089	info	iobroker Delete adapter "backitup"

**Comment by Bjoern2006** [comment]
**DEBUG beim Sichern:**

Started iobroker ...
[DEBUG] [mount] - nfs-mount command: "sudo mount 192.168.178.30:/nfs/IOBroker/IOBroker_CCU2_BackItUp/ /opt/iobroker/backups"
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.raspberrypi 7998 states saved

[DEBUG] [iobroker] - host.raspberrypi 9040 objects saved

**Danach schmiert IOBroker komplett ab...**

**Comment by Bjoern2006** [comment]
**DEBUG beim Sichern:**

Started iobroker ...
[DEBUG] [mount] - nfs-mount command: "sudo mount 192.168.1xx.xx:/nfs/IOBroker/IOBroker_CCU2_BackItUp/ /opt/iobroker/backups"
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.raspberrypi 7998 states saved

[DEBUG] [iobroker] - host.raspberrypi 9040 objects saved

**Danach schmiert IOBroker komplett ab...**

**Comment by simatec** [comment]
Hast du mal den iobroker fix laufen lassen?
Ich kann aus deinen Logs keinen Fehler erkennen.

**Comment by Bjoern2006** [comment]
> Hast du mal den iobroker fix laufen lassen?
> Ich kann aus deinen Logs keinen Fehler erkennen.

Ja habe ich eben laufen lassen - leider immer noch keine Verbesserung.

**Comment by simatec** [comment]
Dann muss an deinem System was krumm sein.
Hast du in letzter Zeit ein Update von node oder vom js-controllers gemacht?
Andere Updates eventuell?

**Comment by Bjoern2006** [comment]
Also mein System läuft fehlerfrei seit Monaten - das einzige was nicht funktioniert, ist dieser Adapter.
Nein habe kein Update von Node bzw. JS-Controller gemacht.

**Comment by Bjoern2006** [comment]
> Dann muss an deinem System was krumm sein.
> Hast du in letzter Zeit ein Update von node oder vom js-controllers gemacht?
> Andere Updates eventuell?

Also mein System läuft fehlerfrei seit Monaten - das einzige was nicht funktioniert, ist dieser Adapter.
Nein habe kein Update von Node bzw. JS-Controller gemacht.

**Comment by simatec** [comment]
OK das heißt aber nicht zwingend, dass der Adapter das verursacht. Was hast du für ein System? PI?
Wie ist deine RAM Auslastung? SD-Karte?

schaue doch mal mit htop, wie sich dein RAM beim Backup verhält. So wie ich das sehe, geht dein System beim Backup entweder mangels RAM oder aufgrund einer sterbenden SD in die Knie

**Comment by nhet** [comment]
Hallöchen, 
ich habe selbiges Problem feststellen können.
Ich habe einen RPI4 mit 8GB RAM und noch 40GB auf der SD frei.
Während des Backups knabbert sich der jscontroller sämtlichen restlichen RAM auf. Das sind in diesem Fall gut 6GB. Ist die Speichergrenze erreicht wird der Dienst neu gestartet.

Vielleicht kann @simatec ja was erkennen?


`backitup.0 | 2021-09-15 12:07:56.153 | warn | get state error: DB closed
-- | -- | -- | --
backitup.0 | 2021-09-15 12:07:56.152 | warn | redis get backitup.0.history.html, error - DB closed
backitup.0 | 2021-09-15 12:07:56.150 | warn | get state error: DB closed
backitup.0 | 2021-09-15 12:07:56.149 | warn | get state error: DB closed
backitup.0 | 2021-09-15 12:07:52.671 | info | Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
backitup.0 | 2021-09-15 12:07:51.167 | info | cleaned everything up...
backitup.0 | 2021-09-15 12:07:51.021 | error | States database error: read ECONNRESET
backitup.0 | 2021-09-15 12:05:55.358 | info | [iobroker] backup was activated at 02:40 every 1 day(s)
backitup.0 | 2021-09-15 12:05:55.297 | info | starting. Version 2.1.17 in /opt/iobroker/node_modules/iobroker.backitup, node: v12.22.6, js-controller: 3.3.18
backitup.0 | 2021-09-15 12:05:50.699 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
backitup.0 | 2021-09-15 12:05:50.697 | info | terminating
backitup.0 | 2021-09-15 12:05:50.696 | info | cleaned everything up...
backitup.0 | 2021-09-15 12:05:50.694 | info | Got terminate signal TERMINATE_YOURSELF
backitup.0 | 2021-09-15 12:05:55.358 | info | [iobroker] backup was activated at 02:40 every 1 day(s)
backitup.0 | 2021-09-15 12:05:55.297 | info | starting. Version 2.1.17 in /opt/iobroker/node_modules/iobroker.backitup, node: v12.22.6, js-controller: 3.3.18
backitup.0 | 2021-09-15 12:05:50.699 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
backitup.0 | 2021-09-15 12:05:50.697 | info | terminating
backitup.0 | 2021-09-15 12:05:50.696 | info | cleaned everything up...
backitup.0 | 2021-09-15 12:05:50.694 | info | Got terminate signal TERMINATE_YOURSELF
` 
`Started iobroker ...
[DEBUG] [iobroker] start with {"type":"creator","time":"02:40","debugging":true,"everyXDays":"1","deleteBackupAfter":0,"dir":"/opt/iobroker","historyDB":{"enabled":true,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"local","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":false,"mountType":"CIFS","type":"storage","source":"local","mount":"192.168.0.222","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"/Volume_1/BackUp/iobroker","dirMinimal":"sharename/backupDir","user":"sonja","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"webdav":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"path":"/opt/iobroker/hisData/"},"javascripts":{"enabled":true,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"local","host":"","debugging":true,"deleteOldBackup":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","user":"","pass":"****","port":"21"},"cifs":{"enabled":false,"mountType":"CIFS","type":"storage","source":"local","mount":"192.168.0.222","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"/Volume_1/BackUp/iobroker","dirMinimal":"sharename/backupDir","user":"sonja","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"webdav":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"filePath":"/opt/iobroker/jsMirror"},"historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"allTelegramUsers","onlyError":false,"telegramWaiting":0,"hostName":"","systemLang":"de"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"hostName":"","systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [iobroker] - host.raspberrypi 1162 states saved

[DEBUG] [iobroker] - host.raspberrypi 1510 objects saved
`

**Comment by nhet** [comment]
So, jetzt ist das Backup erfolgreich durchgelaufen. Es scheint so zu sein, dass das Backup Probleme mit großen Datenmengen hat. Ich hatte noch in der ring Instance Videos und Snapshots von meiner Türklingel. Das waren in Summe ca. 5GB. Nachdem ich die gelöscht hatte, wurde auch korrekt gebackupt. Kann man da was vom Backup ausschließen? @simatec
