### ISSUE TITLE
Upload to google Drive (iobroker missing)

### ISSUE THREAD

**Issue by Day1983** [simatec/ioBroker.backitup#514]
Hallo,

ich hab Deinen Adapter auf der Version 2.1.11 laufen.
Das Problem liegt bei der nächtlichen upload zu google Drive - hier wir das Backup von Javaskrip + Zigbee i.O. nach Drive hoch geladen, ABER das Backup v. IOBROKER wird nicht hochgeladen.
Bei einem manuellen Start (Jetzt sichern) klappt das Backup zu Driver perfekt - alle 3 Dateien werden hochgeladen.
Die Datei "IOBROKER" hat gerade einmal 549 KB!

Ich hab bereits die Instanz gelöscht und alles neu eingegeben - keine Veränderung.
Hab auch eine "krumme" Uhrzeit als Backup genommen - keine Veränderung.

Im LOG stehen keine Fehler.

Ein Downgrade auf 2.1.0 hab ich getestet - keine veränderung.

Komisch ist nur - bis Mitte MAI hatte alles Supi funktioniert - jetzt nicht mehr.

**Versions:**  
 - Adapter version: <2.1.11>
 - JS-Controller version: <js-controller-version> 
 - Node version: <12.22.1> // NPM 6.14.12
 - Operating system: <PI4 mit bastians lite (ohne Docker); >

**Additional context**

**Comment by Day1983** [comment]
korrektur... Seit der neuinstall der Instanz funzt das manuelle Backup auch nicht mehr

![image](https://user-images.githubusercontent.com/77491820/122517467-5a6bcb00-d010-11eb-8942-4dfa1f8e284c.png)

**Comment by simatec** [comment]
Kannn den fehler nicht bestätigen ...
Wechsele mal auf eine krumme Backupzeit. Google scheint zu solchen festen Zeiten wie 02:00 überlastet zu sein.

Nimm mal eine Zeit wie 03:44

![image](https://user-images.githubusercontent.com/39792461/122520347-c7349480-d013-11eb-91f1-e936b2d6b4de.png)

**Comment by Day1983** [comment]
Guten Morgen,

ich hab den IOBROKER fixer mal drüber laufen lassen - iobroker neustart und jetzt funzt zumind. das manuelle Backup wieder...

Ich hab die Backupzeit seit 4 Tagen auf 3:33Uhr  stehen - leider war immer nur das Java+Zigbee bei drive hoch geladen - der IOBROKER fehlte weiterhin.

mal schauen, was nächste Nacht passiert. Vielleicht hat der Fixer was gebracht.

**Comment by Day1983** [comment]
Hallo,

hier meine Rückmeldung - nachdem der FIXER durchgelaufen war, ich die Backupzeit nochmal auf eine andere "krumme" Zeit eingestellt hatte, lief das Backup mit allen 3 Dateien (IOBROKER, JAVA-Skript, Zigbee) Problemlos!  2 Tage/Nächte lang.

Heute morgen wieder das alte Problem - IOBROKER Datei wurde nicht mit zu Drive hochgeladen - nur Java + Zigbee sind in Drive.

noch eine Idee?
Könnte noch ein Update auf deine 2.1.13 machen?!?

**Comment by Day1983** [comment]
Hallo zusammen,

es funktioniert immer noch nicht.
Was hab ich bis jetzt probiert:
1.)
- Instanz gelöscht,
- Objektbaum gelöscht,
- Adapter deinstall,
- IOBROKER FIXER laufen lassen,
- adapter in Vers 2.1.13 install + Instanz install,
- krumme Uhrzeit als Backup Uhrzeit
- Adapter täglich neustart (3min vor nächtlichen Backup)
So hat es 1x funktioniert. Am 2. Tage/Nacht schon nicht mehr

npm noch auf Ver. 12 - ist 14.xx besser?

Jemand noch eine Idee?

Es fehlt "nur" das IOBROKER Backup, die beiden anderen (JAVA + ZIGBEE) sind täglich auf Google DRIVE.

**Comment by Day1983** [comment]
![image](https://user-images.githubusercontent.com/77491820/123506829-730a5f80-d666-11eb-83e9-67274df2bb4e.png)

**Comment by simatec** [comment]
Zeige mal bitte die Ausgabe von:
`ls -la /opt/iobroker/backups`

**Comment by Day1983** [comment]
`pi@raspberrypi:~ $ ls -la /opt/iobroker/backups
insgesamt 19940
drwxrwxr-x+   3 iobroker iobroker    4096 Jun 27 01:23 .
drwxrwxr-x+ 217 iobroker iobroker    4096 Jun 27 00:03 ..
-rw-rwxr--+   1 iobroker iobroker 6271243 Jun 19 03:33 iobroker_2021_06_19-03_33                                                                                                                                                             _10_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker 6283398 Jun 23 01:23 iobroker_2021_06_23-01_23                                                                                                                                                             _10_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker 6291057 Jun 25 01:23 iobroker_2021_06_25-01_23                                                                                                                                                             _10_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  270550 Jun 26 01:23 javascripts_2021_06_26-01                                                                                                                                                             _23_24_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  271261 Jun 26 10:06 javascripts_2021_06_26-10                                                                                                                                                             _06_48_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  271317 Jun 27 01:23 javascripts_2021_06_27-01                                                                                                                                                             _23_24_backupiobroker.tar.gz
drwxrwxr-x+  11 iobroker iobroker    4096 Mai 12 19:24 scripte
-rw-rw-r--+   1 iobroker iobroker  238978 Jun 26 01:23 zigbee.0_2021_06_26-01_23                                                                                                                                                             _23_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  241665 Jun 26 10:06 zigbee.0_2021_06_26-10_06                                                                                                                                                             _48_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  241645 Jun 27 01:23 zigbee.0_2021_06_27-01_23                                                                                                                                                             _23_backupiobroker.tar.gz
pi@raspberrypi:~ $
pi@raspberrypi:~ $
`

**Comment by simatec** [comment]
Bitte checke mal die Rechte für den Backupordner ...
Sollte so in etwa aussehen:
`ls -la /opt/iobroker/backups
insgesamt 35340
drwxrwxr-x+ 2 iobroker iobroker    4096 Jun 14 09:20 .
drwxrwxrwx+ 8 iobroker iobroker    4096 Jun 27 18:22 ..
-rwxrwxr-x+ 1 iobroker iobroker 4352720 Feb 19 12:56 2021_02_19-12_55_59_backupi                       obroker-migration.tar.gz
-rw-rwxr--+ 1 iobroker iobroker 4492679 Apr 18 15:06 2021_04_18-15_06_52_backupi                       obroker-migration.tar.gz
-rw-rwxr--+ 1 iobroker iobroker 4492873 Apr 18 15:26 2021_04_18-15_26_03_backupi                       obroker-migration.tar.gz
-rw-rwxr--+ 1 iobroker iobroker 4478761 Apr 18 16:52 2021_04_18-16_52_35_backupi                       obroker-migration.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker    9205 Jan 25 19:06 grafana_2021_01_22-17_00_03                       _backupiobroker.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker    3891 Jan 23 15:09 grafana_2021_01_23-14_09_01                       _backupiobroker.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker 2652160 Dez  1  2020 homematic_2020_12_01-08_45_                       11_3.53.34_backupiobroker.tar.sbk
-rwxrwxr-x+ 1 iobroker iobroker 2652160 Jan  9 08:45 homematic_2021_01_09-08_45_                       11_3.53.34_backupiobroker.tar.sbk
-rwxrwxr-x+ 1 iobroker iobroker 4218971 Jan  8 15:22 iobroker_2021_01_08-15_22_0                       1_dev_backupiobroker.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker 4227979 Jan  9 12:20 iobroker_2021_01_09-12_20_1                       0_dev_backupiobroker.tar.gz
-rw-rwxr--+ 1 iobroker iobroker 4466487 Jun 14 09:20 iobroker_2021_06_14-09_20_1                       4_dev_backupiobroker.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker    2849 Jan  8 15:22 jarvis.0_2021_01_08-15_22_0                       7_backupiobroker.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker    2849 Jan  9 12:20 jarvis.0_2021_01_09-12_20_1                       6_backupiobroker.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker    1032 Jan  8 15:22 jarvis.1_2021_01_08-15_22_0                       7_backupiobroker.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker    1033 Mär 17 16:52 jarvis.1_2021_02_18-21_16_0                       2_backupiobroker.tar.gz
-rw-rwxr--+ 1 iobroker iobroker    1033 Apr 25 15:25 jarvis.1_2021_02_19-21_16_0                       3_backupiobroker.tar.gz
-rw-rwxr--+ 1 iobroker iobroker    1034 Apr 18 13:25 jarvis.1_2021_04_16-14_26_2                       3_backupiobroker.tar.gz
-rw-rwxr--+ 1 iobroker iobroker    1034 Apr 18 13:21 jarvis.1_2021_04_17-14_26_2                       3_backupiobroker.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker   20181 Jan 26 16:09 javascripts_2021_01_26-16_0                       3_07_backupiobroker.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker   19264 Jan 26 20:21 javascripts_2021_01_26-17_2                       5_31_backupiobroker.tar.gz
-rw-rwxr--+ 1 iobroker iobroker   23099 Apr 13 16:03 javascripts_2021_04_13-14_2                       6_24_backupiobroker.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker     188 Nov 30  2020 zigbee.0_2020_11_30-12_53_1                       5_backupiobroker.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker     188 Jan 27 12:33 zigbee.0_2021_01_22-16_59_5                       8_backupiobroker.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker     189 Nov 30  2020 zigbee.1_2020_11_30-12_53_1                       5_backupiobroker.tar.gz
-rwxrwxr-x+ 1 iobroker iobroker     189 Jan 27 12:32 zigbee.1_2021_01_22-16_59_5                       8_backupiobroker.tar.gz
pi@iobroker-dev:~$
`

**Comment by Day1983** [comment]
hmmm,
beim dem Thema würde ich Deine Hilfe benötigen. Da kenn ich mich "0" aus.
Was muss ich wie eingeben?

`drwxrwxr-x+   3 iobroker iobroker    4096 Jun 28 01:23 .
drwxrwxr-x+ 218 iobroker iobroker    4096 Jun 28 00:03 ..
**-rw-rwxr--+   1 iobroker iobroker 6271243 Jun 19 03:33 iobroker_2021_06_19-03_33_10_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker 6283398 Jun 23 01:23 iobroker_2021_06_23-01_23_10_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker 6291057 Jun 25 01:23 iobroker_2021_06_25-01_23_10_backupiobroker.tar.gz**
-rw-rw-r--+   1 iobroker iobroker  271261 Jun 26 10:06 javascripts_2021_06_26-10_06_48_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  271317 Jun 27 01:23 javascripts_2021_06_27-01_23_24_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  271317 Jun 28 01:23 javascripts_2021_06_28-01_23_24_backupiobroker.tar.gz
drwxrwxr-x+  11 iobroker iobroker    4096 Mai 12 19:24 scripte
-rw-rw-r--+   1 iobroker iobroker  241665 Jun 26 10:06 zigbee.0_2021_06_26-10_06_48_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  241645 Jun 27 01:23 zigbee.0_2021_06_27-01_23_23_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  244403 Jun 28 01:23 zigbee.0_2021_06_28-01_23_24_backupiobroker.tar.gz
`

**Comment by Day1983** [comment]
`drwxrwxr-x+   3 iobroker iobroker    4096 Jun 28 01:23 .
drwxrwxr-x+ 218 iobroker iobroker    4096 Jun 28 00:03 ..
-rw-rwxr--+   1 iobroker iobroker 6271243 Jun 19 03:33 iobroker_2021_06_19-03_33_10_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker 6283398 Jun 23 01:23 iobroker_2021_06_23-01_23_10_backupiobroker.tar.gz

-rw-rw-r--+   1 iobroker iobroker 6291057 Jun 25 01:23 iobroker_2021_06_25-01_23_10_backupiobroker.tar.gz

-rw-rw-r--+   1 iobroker iobroker  271261 Jun 26 10:06 javascripts_2021_06_26-10_06_48_backupiobroker.tar.gz

-rw-rw-r--+   1 iobroker iobroker  271317 Jun 27 01:23 javascripts_2021_06_27-01_23_24_backupiobroker.tar.gz

-rw-rw-r--+   1 iobroker iobroker  271317 Jun 28 01:23 javascripts_2021_06_28-01_23_24_backupiobroker.tar.gz

drwxrwxr-x+  11 iobroker iobroker    4096 Mai 12 19:24 scripte

-rw-rw-r--+   1 iobroker iobroker  241665 Jun 26 10:06 zigbee.0_2021_06_26-10_06_48_backupiobroker.tar.gz

-rw-rw-r--+   1 iobroker iobroker  241645 Jun 27 01:23 zigbee.0_2021_06_27-01_23_23_backupiobroker.tar.gz

-rw-rw-r--+   1 iobroker iobroker  244403 Jun 28 01:23 zigbee.0_2021_06_28-01_23_24_backupiobroker.tar.gz
`

**Comment by simatec** [comment]
Versuche mal folgendes:

`sudo chmod 755 /opt/iobroker/backups
sudo chmod 755 /opt/iobroker/backups/
sudo chmod 755 /opt/iobroker/backups/*`

**Comment by Day1983** [comment]
hab das gemacht.

Jetzt sieht es so aus:
(alles Grün dargestellt)

`drwxr-xr-x+   3 iobroker iobroker    4096 Jun 28 01:23 .
drwxrwxr-x+ 218 iobroker iobroker    4096 Jun 28 00:03 ..
-rwxr-xr-x+   1 iobroker iobroker 6271243 Jun 19 03:33 iobroker_2021_06_19-03_33_10_backupiobroker.tar.gz

-rwxr-xr-x+   1 iobroker iobroker 6283398 Jun 23 01:23 iobroker_2021_06_23-01_23_10_backupiobroker.tar.gz

-rwxr-xr-x+   1 iobroker iobroker 6291057 Jun 25 01:23 iobroker_2021_06_25-01_23_10_backupiobroker.tar.gz

-rwxr-xr-x+   1 iobroker iobroker  271261 Jun 26 10:06 javascripts_2021_06_26-10_06_48_backupiobroker.tar.gz

-rwxr-xr-x+   1 iobroker iobroker  271317 Jun 27 01:23 javascripts_2021_06_27-01_23_24_backupiobroker.tar.gz

-rwxr-xr-x+   1 iobroker iobroker  271317 Jun 28 01:23 javascripts_2021_06_28-01_23_24_backupiobroker.tar.gz

drwxr-xr-x+  11 iobroker iobroker    4096 Mai 12 19:24 scripte

-rwxr-xr-x+   1 iobroker iobroker  241665 Jun 26 10:06 zigbee.0_2021_06_26-10_06_48_backupiobroker.tar.gz

-rwxr-xr-x+   1 iobroker iobroker  241645 Jun 27 01:23 zigbee.0_2021_06_27-01_23_23_backupiobroker.tar.gz

-rwxr-xr-x+   1 iobroker iobroker  244403 Jun 28 01:23 zigbee.0_2021_06_28-01_23_24_backupiobroker.tar.gz
`

**Comment by simatec** [comment]
Der Ordner Scripte sollte aus dem Backup-Verzeichnis raus.
Spiegele deine Scripte z.B. in /home/username(Bsp. pi)/scripte

Dann sollte auch dein Google Upload so funktionieren

**Comment by Day1983** [comment]
Hallo,

ich hab einen anderen ORDENR zum Spiegeln angelegt.

Jetzt erstellt er kein Backup vom Iobroker mehr:
`drwxrwxr-x+   2 iobroker iobroker   4096 Jun 29 12:21 .

drwxrwxr-x+ 220 iobroker iobroker   4096 Jun 29 12:07 ..

-rw-rw-r--+   1 iobroker iobroker 271292 Jun 29 12:21 javascripts_2021_06_29-12_21_16_backupiobroker.tar.gz

-rw-rw-r--+   1 iobroker iobroker 250068 Jun 29 12:21 zigbee.0_2021_06_29-12_21_16_backupiobroker.tar.gz
`

Und die 2 unteren POS werden "rot" dargestellt.

Jetzt hab ich den FIXER nochmal drüber laufen lassen.

Jetzt ging es wieder... Alle Uploads online.


Melde mich die Tage, ob es jetzt täglich funzt.



Danke Dir.

**Comment by Day1983** [comment]
Guten MOrgen,

sorry ich muss schon wieder nerven...
es funktioniert 1 Tag lang, nach dem der Fixer gelaufen ist - am folge tag funz es nicht mehr. Die datei IOBROKER wird nicht erstellt...

![image](https://user-images.githubusercontent.com/77491820/124084436-4338ce80-da4f-11eb-8bef-afb3a3c33b3e.png)

**Comment by Day1983** [comment]
Leider keine Besserung.
Hier mein letztes Vorgehen:
(Reihenfolge)

- Instanz gelöscht,
- Adapter gelöscht,
- IOBROKER gestoppt,
- Ordner "Backups" gelöscht (über Konsole),
- Iobroker fixer,
- iobroker gestartet,
- Adapter über Github URL installiert (Vers 2.1.13),
- Instanz als "1" installiert (nicht "0"),
- Einstellungen ==> krumme Uhrzeit + Scripte Ordner außerhalb des Backups Ordner,
- dann funktioniert es eine Nacht - in der 2. Nacht schon nicht mehr,

Jemand noch eine andere Idee?

`drwxrwxr-x+   2 iobroker iobroker    4096 Jul  3 01:23 .
drwxrwxr-x+ 224 iobroker iobroker    4096 Jul  3 00:09 ..
-rw-rw-r--+   1 iobroker iobroker 6321775 Jul  1 21:36 iobroker_2021_07_01-21_35_57_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker 6323689 Jul  2 01:23 iobroker_2021_07_02-01_23_10_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  271303 Jul  1 21:36 javascripts_2021_07_01-21_36_16_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  271303 Jul  2 01:23 javascripts_2021_07_02-01_23_30_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  271303 Jul  3 01:23 javascripts_2021_07_03-01_23_24_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  261101 Jul  1 21:36 zigbee.0_2021_07_01-21_36_16_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  261091 Jul  2 01:23 zigbee.0_2021_07_02-01_23_30_backupiobroker.tar.gz
-rw-rw-r--+   1 iobroker iobroker  264059 Jul  3 01:23 zigbee.0_2021_07_03-01_23_23_backupiobroker.tar.gz
`

**Comment by Day1983** [comment]
Hallo zusammen,

heute morgen leider wieder ein Ernüchterung.
Die Datei "IOBROKER" fehlt wieder.

Vorgehen war wie oben beschrieben, nur hatte ich in den Einstellungen das Backup von "Javascript" + "Zigbee" nicht aktiviert.
In der ersten Nacht hat das Backup wieder funktioniert - in der 2. Nacht nicht mehr.

Ich bin ratlos.

hat keiner mehr eine Idee?
(Wie kann man die Dateien vom Adapter in der Konsole finden und löschen?)
Vielleicht wäre das noch eine Möglichkeit?

neue Reihenfolge

Instanz gelöscht,
Adapter gelöscht,
IOBROKER gestoppt,
Ordner "Backups" gelöscht (über Konsole),
### **Daten/Ordner vom Backitup Adapter löschen (wo ist der?)**
Iobroker fixer,
iobroker gestartet,
Adapter über Github URL installiert (Vers 2.1.13),
Instanz als "1" installiert (nicht "0"),
Einstellungen ==> krumme Uhrzeit + Scripte Ordner außerhalb des Backups Ordner,

**Comment by simatec** [comment]
Irgendwas verbiegt dir immer wieder die Rechte ...
Versuche mal folgendes:

`
sudo chmod 755 /opt/iobroker/backups
sudo chmod 755 /opt/iobroker/backups/
sudo chmod 755 /opt/iobroker/backups/*
sudo chown iobroker:iobroker /opt/iobroker/backups
sudo chown iobroker:iobroker /opt/iobroker/backups/
sudo chown iobroker:iobroker /opt/iobroker/backups/*
`

**Comment by Day1983** [comment]
Danke erstmal für Deine Hilfe.

Ich hab vor 8 Tagen ein manuelles Backup erstellt und anschließend mein System geflashed und das Backup geladen.
Dann hat es innerhalb  der 8 Tagen 6x funktioniert.

komisch ist nur, vorgestern hat es nicht funktioniert letzte Nacht hat es wieder funktioniert (ohne das System angerührt zu haben).

ich beobachte das weiter und melde mich.

Danke Dir.

**Comment by Day1983** [comment]
HAllo,

leider läuft mein neu aufgesetztes System seit 3 Tage wieder mit dem gleichen Fehler auf - kann auch kein manuelles Backup erstellen.

Ich habe jetzt mal die Befehle von Deiner Antwort in die Konsole eingegeben und teste jetzt.

Ich melde mich.

> Irgendwas verbiegt dir immer wieder die Rechte ...
> Versuche mal folgendes:
> 
> `sudo chmod 755 /opt/iobroker/backups sudo chmod 755 /opt/iobroker/backups/ sudo chmod 755 /opt/iobroker/backups/* sudo chown iobroker:iobroker /opt/iobroker/backups sudo chown iobroker:iobroker /opt/iobroker/backups/ sudo chown iobroker:iobroker /opt/iobroker/backups/*`

**Comment by Day1983** [comment]
Hallo @simatec ,

leider hat es wieder nicht funktioniert - ein paar Tage sah alles gut aus, dann unerwartet hat es nicht mehr funktioniert. Wieder kein Backup auf Drive. Eine Manuelles Backup ging auch nicht mehr.

Ich hab mir erstmal mit einem Blockly beholfen, dass alle 2 Tage die Befehle:
- sudo chown iobroker:iobroker /opt/iobroker/backups 
- sudo chown iobroker:iobroker /opt/iobroker/backups/ 
- sudo chown iobroker:iobroker /opt/iobroker/backups/*
an die die Konsole sendet.

Mal schauen wie lange das gut geht.


Hast Du noch eine andere Idee?


Vielen Dank.

**Comment by simatec** [comment]
Es scheint mir so, als ob irgendwas externes deine Rechte immer wieder ändert.
Hast du noch etwas laufen, was auf den Pfad zugreift?

Um jegliche Fehlerquellen auszuschließen, würde ich ein Backup deiner SD machen und das System nach offizieller Anleitung neu aufsetzen.
Dann mit Backitup das letzte Backup einspielen und alles sollte gut sein.
