### ISSUE TITLE
Possible Source of high memory usage

### ISSUE THREAD

**Issue by theimo1221** [simatec/ioBroker.backitup#515]
**Describe the bug**  
It seems as if backitup might result in high memory consumption of iobroker.js-controller.

As visible in the screenshots below, my memory consumption got higher an higher. 
In the newer screenshots you can see the memory usage starting to peak again around 4 AM which is the time of my iobroker Backup using Backitup.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/20605452/122637822-f3721300-d0f0-11eb-9d6f-c3f7c956524b.png)
![image](https://user-images.githubusercontent.com/20605452/122637830-f836c700-d0f0-11eb-9a17-be3245f54c76.png)
![image](https://user-images.githubusercontent.com/20605452/122637835-02f15c00-d0f1-11eb-9772-fccf7aa192b5.png)
![image](https://user-images.githubusercontent.com/20605452/122637838-097fd380-d0f1-11eb-9177-8d355ef62c29.png)

**Versions:**  
 - Adapter version: 2.1.13
 - JS-Controller version: 3.3.12
 - Node version: v14.17.1
 - Operating system: linux (Proxmox LXC)

**Additional context**

**Comment by simatec** [comment]
The iobroker backup unfortunately requires a lot of RAM.  Backitup uses the backup method of the js-controller.  If you run the console command "iobroker backup", the RAM will behave similarly.  During the backup, large amounts of data are filtered and rewritten to the backup.  You could automatically restart Backitup once a day to free up unused RAM.

**Comment by theimo1221** [comment]
Running `free -m` does only give back small portion of locked up memory.

If restarting this would result in memory properly getting freed, why can't we just clear those internal objects/structures, so that the process gives the memory free by himself?

**Comment by simatec** [comment]
I will encourage this in the iobroker dev team and see what is possibly possible with the js controller

**Comment by Apollon77** [comment]
In my eyes thinks normal Linux behavior. Free -m output is relevant. 

Backitup is doing a lot of file actions and so Linux is filling up mem with filesystem cache as it usually does. So the question is what is the issue? Is it „just that all available RAM the machine has available is also used“? If yes then congrats. Your Linux system works as expected and you should read https://www.linuxatemyram.com/ ;-)

**Comment by theimo1221** [comment]
![image](https://user-images.githubusercontent.com/20605452/123506882-c11f6300-d666-11eb-983f-9482b659b0f8.png)
The size of the backups rapidly increased as well, while I personally can't think of any new addition to ioBroker which would explain it.

**Comment by simatec** [comment]
Could it be that you save history data or something similar in the iobroker directory?  Your backup is way too big in my opinion

**Comment by simatec** [comment]
With a backup size of more than 2 GB, it's no wonder that your RAM goes to its knees during the backup process

**Comment by Apollon77** [comment]
> RAM goes to its knees 

Sorry but STILL unproofed that is really gets "short on RAM" or if it is "just used".
because if it would be really getting short on RAM then @simatec you have a place in your code that loads stuff into RAM before writinignit out. In my last optimization round I eliminated all these cases by using streams so that never the full file was in RAM

@theimo1221 the backups are normal tar archives ... check  whats in and you will see what causes the increae in size

**Comment by simatec** [comment]
@Apollon77 
The backup process of the js controller is started here
https://github.com/simatec/ioBroker.backitup/blob/a7c481ac1f31f1f36e20754eea522b6713a3a761/lib/scripts/10-iobroker.js#L16

**Comment by Apollon77** [comment]
I mean more in general :-) The controller backup process is NOT loading big data in RAM

**Comment by simatec** [comment]
OK, then there must be a general problem with @theimo1221 , since the js controller requires 83.6% RAM here ...

**Comment by theimo1221** [comment]
Checked it today again, the ram usage went above 5 GB but doesn't use 100% anymore, as I increased lxc to 8GB.

![image](https://user-images.githubusercontent.com/20605452/124097999-6c139080-da5c-11eb-9929-4525e159cfa9.png)
![image](https://user-images.githubusercontent.com/20605452/124098103-89e0f580-da5c-11eb-98bf-f7a7a0724822.png)

Will analyze the next backup regarding memory usage.

**Comment by Apollon77** [comment]
Only "free -m" is telling details

**Comment by theimo1221** [comment]
I tried to run a manual "backup now" and it resulted in an 2,5MB Backup File (not that 2,9 GB as before) and Memory remained low in consumption.

I'll keep an eye on it, and will take a look tomorow morning, after automatic backup this night.

**Comment by simatec** [comment]
Your Backitup config and which js-controller, node, npm and Backitup version are installed would also be interesting.

Please post the config of Backitup as json and your version status

**Comment by theimo1221** [comment]
@simatec Looking into the tmp/backup/files folder I found this one:
![image](https://user-images.githubusercontent.com/20605452/130347553-1b29c613-84a9-4938-b28f-bd4c3c3b6b26.png)

So due to whatever reason some of the iobroker.ring data are not in correct folders, which would get ignored by the backup

**Comment by simatec** [comment]
https://github.com/simatec/ioBroker.backitup/issues/515#issuecomment-872293028

**Comment by theimo1221** [comment]
Sorry, I just meant it as an explanation to why this might be happening: As I think I have to check why the ring adapter doesn't save to a location which get's ignored by backitup.

Node.js v14.17.5 
JSController: 3.3.15
npm 6.14.14
BackItUp: 2.1.17
[system.adapter.backitup.0.txt](https://github.com/simatec/ioBroker.backitup/files/7026854/system.adapter.backitup.0.txt)

**Comment by simatec** [comment]
The path for the temporary backup files is correct.  Backitup performs the exactly identical backup method of the js-controller.

**Comment by simatec** [comment]
Please check why your ring adapter causes so much data

**Comment by theimo1221** [comment]
@simatec What would be the correct path, which would be ignored by backup?


`/opt/iobroker/iobroker-data/ring_0/`
Or should it be 
`/opt/iobroker/iobroker-data/files/ring_0/`

**Comment by Apollon77** [comment]
WHy the data should be ignored? They are in the iobroker stoage and so they are normally backupped ...

**Comment by theimo1221** [comment]
Well, in the first instance I want the snapshots and video recordings of my cameras to not be deleted automatically.
Until I update the ring adapter to automatically store those recordings onto e.g. some NAS I have to download them periodically before deleting them manually.
Still I wouldn't rate those recordings that important, that it should be in a normal ioBroker Backup.
If I need to access one of those files in case of a crash of iobroker I still have around 30 days to retrieve those from Ring.

So, what would be the proper solution for this? Where to store those recording to be ignored by backup, or could we add some functionallity to exclude certain elements form backup?

**Comment by Apollon77** [comment]
I would only write data into iobroker storage thatare really accessed by iobroker. Thisnk about users with a redis - there all those files will en d in the RAM ... in your case the redis would alone need 2,6GB RAM to just hold these "unneeded" files.

SO I would use an other directly outside of the iobroker storage for stuff you do not need in iobroker and are just for other reasons there

**Comment by theimo1221** [comment]
While I agree on the basic idea, there is the problem of those recordings beeing partially beeing part of iobroker (e.g. retrieving last screenshot using a link and iobroker.web adapter) while those once beeing older are more outside iobroker....

So in my ring adapter V2 rewrite I'll ensure the current active ones will be within iobroker directory while those long term archiv files can be stored outside.

**Comment by Apollon77** [comment]
But "last screenshot" can be one file which gets constantly overwritten. done :-)) maybe even easier for visus?

And again:"Just" RAM used by linux means nothing ... it is file cache. only "free -m" counts to see real usage - an so all these Proxmox graphs are good but misleading
