### ISSUE TITLE
Backup der YAML-Files von ESPhome-Adapter

### ISSUE THREAD

**Issue by darkman242** [simatec/ioBroker.backitup#518]
es wäre wünschenswert wenn die YAML-Files vom ESPhome-Adapter mit gesichert werden könnten

**Comment by simatec** [comment]
Wo befinden sich die YAML-Files im System?

**Comment by darkman242** [comment]
die YAML-Files befinden sich direkt unter /opt/iobroker/iobroker-data/esphome.0

**Comment by simatec** [comment]
Die Files werden bei einem iobroker Backup mitgesichert und befinden sich im iobroker Backup
