### ISSUE TITLE
Backup Ordner für yahka-Adapter (Apple Homekit)

### ISSUE THREAD

**Issue by Baenker** [simatec/ioBroker.backitup#519]
Nach Neuinstallation und Restore aus dem Backup muss man manuell aus dem alten System (falls man vorher daran denkt), den Ordner "yahka.X.hapdata" nach "/opt/iobroker/iobroker-data" kopieren damit der yahka-Adapter funktioniert. Ohne das kopieren muss man alle Geräte in Homekit neu anlegen und die alten löschen. Außerdem muss man die Mac-Adresse im Yahka-Adapter ändern.

Es wäre schön wenn es eine Option gäbe, das Verzeichnis mit zusichern und bei einem restore automatisch zurück kopiert würde bzw wenn das Backup prüft ob es das Verzeichnis gibt und es direkt mit sichert.

**Comment by nemodil** [comment]
BackItUp hat mir schon mehrer male aus der Patsche geholfen, und ich möchte mich an die Stelle für die gute Arbeit bedanken!
Leider sind mir beim ersten Crash, in meinen Anfängen mit ioBroker, alle Homekit Geräte verloren gegangen. Seitdem kopiere ich die Yahka-Dateien bei jeder Änderung manuel an einen sicheren Ort.
Eine Erweiterung in BackItUp würde mich und bestimmt auch alle Yahka Nutzer sehr freuen :-)

**Comment by simatec** [comment]
Nehme ich mit auf die Todo

**Comment by simatec** [comment]
Version 2.2.0

**Comment by unstressable** [comment]
Der Fehler scheint noch immer da zu sein, zumindest habe ich noch wie vor genau das Problem.
Umgezogen von Raspi4 auf neue Hardware mit Docker Image.

Netzwerk ist auf Host eingestellt, sollten also alle Ports offen sein.
Backitup in der Version: 2.10.11
Hab extra nach dem ioBroker Restore nochmal ein einzelnes YAHKA Restore probiert.

Geht leider nicht.

**Comment by mcm1957** [comment]
@unstressable 
Du bist dir bewusst dass dieses issue 2021 (!) geschlossen wurde ?

Bei einem aktuellenvProblem öffne ein neues Issue u gib die betroffenen Versionen von Adapter und core an

**Comment by unstressable** [comment]
@mcm1957 
Jap, aber das Problem besteht leider noch bzw. wieder.

**Comment by Baenker** [comment]
Du irrst. Es war nie ein Problem. Ich hatte damals den Entwickler gebeten im Adapter das Backup von Yahka aufzunehmen. Das hat er gemacht (hatte es mit der Version 2.2 getestet). Wenn also nach dem Restore die Dateien im o. g. Verzeichnis landen kann Backitup auch nichts dazu das Yahka ein Problem hat. Das Problem liegt also wenn bei Yahka. Das Verzeichnis hast Du ja bestimmt kontrolliert oder? Hier solltest Du wieder zu machen.

**Comment by mcm1957** [comment]
Issue ist eh zu....
Commwnts hier sind eh eher wirkungslos ...

**Comment by unstressable** [comment]
Recht habt ihr, es lag an meiner Dockerkonfiguration.

Genauer gesagt am fehlenden Wert:
`       AVAHI: true `

Hier die Compose:

`version: '3'

services:
  iobroker:
    container_name: iobroker
    image: buanet/iobroker
    hostname: Eck29-ioBroker
    network_mode: "host"
    restart: unless-stopped
    
    volumes:
      - data:/opt/iobroker  

    environment:
       AVAHI: true       
          
#Volume lokal erzeugen:
volumes:
     data:`
