### ISSUE TITLE
Restore Beschreibung, nicht komplett

### ISSUE THREAD

**Issue by chrvidal** [simatec/ioBroker.backitup#52]
Hi,
ich habe heute ein Minimal Backup auf ioBroker aufspielen müssen,
Es fehlt in der Restore Beschreibung meiner Meinung nach noch ein Punkt.
Nachdem das Backup eingespielt wurde muss man noch `iobroker upload all` machen,
bei mir ging ohne den Befehl nichts.

**Comment by simatec** [comment]
Danke für den Hinweis... werden wir anpassen
