### ISSUE TITLE
Sicherungszeit um bestimmten Tag erweitern

### ISSUE THREAD

**Issue by eifel-tech** [simatec/ioBroker.backitup#521]
Aktuell kann man in einigen Reitern eine Sicherungs(uhr)zeit angeben. Dabei wird der aktuelle Wochentag verwendet. Möchte ich bspw. eine Sicherung meiner Daten an jedem Montag (also wöchentlich) um 2:00 Uhr stelle ich als Sicherungszeit 02:00 Uhr ein und bei Tage 7. Nun muss ich diese Konfigänderung aber auch Montags speichern, sonst wird ein anderer Tag verwendet. Wird iobroker außerdem zwischendurch mal neu gestartet, wird die Sicherung plötzlich immer an diesem Tag um 2 Uhr durchgeführt.
Ich würde mir wünschen, dass man neben Uhrzeit auch einen oder mehrere Wochentag(e) festlegen kann, an denen das Backup ausgeführt werden soll. 
Alternativvorschlag: Man konfiguriert die Zeiten über einen Cron-Eintrag ähnlich der Spalte "Zeitplanung" in der Admin-Instanzen-Tabelle.

**Comment by simatec** [comment]
Das Thema hatten wir schon ein paar mal. Es ist nicht die Philosophie von Backitup.
Empfehlung ist jeden Tag ein Backup zu fahren ...

**Comment by eifel-tech** [comment]
Danke für die Antwort, auch wenn ich diese "Philosophie" nicht nachvollziehen kann. Wenn die Empfehlung eine tägliche Sicherung wäre, müsste konsequenterweise auch das Feld `"Tage" (Sicherung alle x Tage ausführen)`  entfernt werden ;-)
