### ISSUE TITLE
Start adapter for backup and stop it after that to save RAM

### ISSUE THREAD

**Issue by jlssmt** [simatec/ioBroker.backitup#523]
**Is your feature request related to a problem? Please describe.**
No. Just high RAM consumption of the adapter.
RAM usage is the third highest of my adapters. After admin and javascript adapter...

**Describe the solution you'd like**
A raspberrypi or other systems have very limited amount of RAM.
It should be a target of adapters to minimize the RAM usage.
The adapter should only start at a defined time, do the backup and stop after that.
So the adapter isn't running all the time.

**Describe alternatives you've considered**
Nuffin

**Additional context**
![image](https://user-images.githubusercontent.com/42897917/127869384-f32635e6-5d9d-482f-9179-e840e5cfe84d.png)

**Comment by simatec** [comment]
The RAM usage is absolutely in the normal range.  Packing the backups just needs some RAM.  You can have the adapter restart automatically once a day.  But converting the adapter to schedule does not correspond to the philosophy of Backitup.

**Comment by jlssmt** [comment]
I'm not packing any backups. It's 82MB in idle...

**Comment by simatec** [comment]
82 Mb is absolutely normal and perfectly fine.  node just needs a little more RAM than e.g. C ++

**Comment by jlssmt** [comment]
While idling it's using more RAM than every other adapter.

![image](https://user-images.githubusercontent.com/42897917/127912255-589ffdb8-227d-430f-aa10-175231ef82f3.png)

**Comment by simatec** [comment]
we're only talking about reserved RAM here.  Take a look with htop.  There you can see the actual usage.

**Comment by jlssmt** [comment]
ehm. in idle still more than all others.

![image](https://user-images.githubusercontent.com/42897917/127913797-a5255c4f-49c8-4497-a6d0-945396da3f80.png)

**Comment by simatec** [comment]
restart the adapter.  You can also do this automatically once a day.  of course, the reserved RAM is recalculated after a backup.  Linux has an intelligent RAM management here.

**Comment by jlssmt** [comment]
restarting adapter changes nothing. and rebooting raspi neither.

**Comment by jlssmt** [comment]
Nevermind. It was just a feature request.
A backup adapter should be small and fast in my opinion and only starts if it does backups. But thanks for the work anyways and keep it up. I'll stay with the internal backup ;-)

**Comment by simatec** [comment]
Here are a few more detailed facts about the actual memory consumption

![image](https://user-images.githubusercontent.com/39792461/127990661-b72f0349-378b-4809-8d83-38df487866ed.png)

https://en.wikipedia.org/wiki/Resident_set_size

https://www.baeldung.com/java-heap-used-committed-max

**Comment by jlssmt** [comment]
@simatec 
thanks for this clarification.
i cross checked the heap values with other adapters. It's still very very high in idle (especially for a backup adapter).

**Comment by simatec** [comment]
But you mustn't forget that we're not talking about a simple tool that executes the "iobroker backup" command via the GUI.

Many options are supported here and many storage options such as GoogleDrive, Dropbox, Nextcloud, NAS (CIFS, NFS), FTP etc.

These are all modules in the adapter that are loaded and also require memory.

So I can't quite understand your statement.

**Comment by jlssmt** [comment]
I just can go along with your argumentation if we talk about the backup process. But I'm talking about resources while idling.

**Comment by simatec** [comment]
Of course, the modules all load when the adapter starts

**Comment by jlssmt** [comment]
I know. And in my opinion, this is an inefficient approach.
All modules should only be load while backing up and stopped after that.

More further: the whole adapter only should start when backing up. But I know, that this can't be easily implemented, also because users already use it in production.

**Comment by simatec** [comment]
With the functions that the adapter brings, it definitely has to work as a daemon.

With the functions that the adapter brings, it definitely has to work as a daemon.

I think the discussion does not lead to any result here either.

RAM usage under Linux is always relative.

If you have a system with 1 Gb RAM, Backitup only uses part of it.

For example, Backitup calls up all storage sources when it starts in order to check the backups.

Modules are loaded here, which of course are then also in the reserved RAM.

Linux releases the reserved RAM again if necessary, which is why I cannot understand the whole discussion here.

Please read up on Linux's RAM management.

Then you will see that we are talking past each other here

**Comment by jlssmt** [comment]
It's not about Linux or RAM management.
It's just about efficient programming, closing currently not used resources and efficient application architecture.

But yes, I think we don't come to a result here.

**Comment by Apollon77** [comment]
@jlssmt Honestly? We talk abot 60MB RAM usage? Because Node.js alone needs roughly 30 MB basic RAM ... And becaude of the usage of JavaScript the whole garbage collection and such is done by Node.js and the adapter do not have any option.

In fact I would invite you to review the code and bring up places where you think it is not "efficient" anough.

**Comment by jlssmt** [comment]
@Apollon77 
I installed the adapter, because I saw it was recommended for backups. 
And I uninstalled it because I saw it uses so much RAM. And runs all the time.
Nevermind, it was only a feature request. No bug.
The topic is closed for me. 
I already noted my suggestions of improvement.

**Comment by simatec** [comment]
Can you please test version 2.1.14?
We looked for a vulnerability and found it in the "googleapis".

There were also further optimizations when loading the individual modules

**Comment by jlssmt** [comment]
Tested.
Initial RAM usage is ok now.
But after starting backup it rests with all required resources for the backup process.

Btw. this is useless:
```
let Client = require('ftp');
Client = null;
```

**Comment by simatec** [comment]
It is normal for the backup process to use RAM.

After starting the adapter: 62 MB
After the backup process: 69 MB

I think there is really no problem here ... We don't need to discuss 7 MB RAM if a reasonable iobroker system should have at least 2 GB, but more likely 4 GB.

PS: `Client = null` does not exist in the code

**Comment by jlssmt** [comment]
yeah. I just tested it shortly and only used iobroker backup + dropbox upload.
dunno if we talk about more than 7MB if you use more modules.

Client = null was in a previous commit. sorry.
