### ISSUE TITLE
Backup to NAS (Synology) failed

### ISSUE THREAD

**Issue by MiRen76** [simatec/ioBroker.backitup#527]
When I try to run a NAS-backup for the iobroker I get the following error message:

2021-08-05 08:16:55.432 - error: backitup.0 (6734) Error: Command failed: sudo mount -t cifs -o username=my-username,password=*,rw,file_mode=0777,dir_mode=0777 //IP-of-my-nas/homes/iobroker/backup /opt/iobroker/backups
--
mount error(1): Operation not permitted
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

The target is a Synology NAS located in my local network. The same network iobroker is working with. I installed iobroker based on an ubuntu 20.04.

**Comment by simatec** [comment]
Please show your configuration

**Comment by MiRen76** [comment]
My config:

{
  "_id": "system.adapter.backitup.0",
  "common": {
    "name": "backitup",
    "version": "2.1.13",
    "title": "BackItUp",
    "authors": [
      "simatec <nais@gmx.net>",
      "peoples0815 <peoples0815github@gmail.com>",
      "bluefox <dogafox@gmail.com>"
    ],
    "osDependencies": {
      "linux": [
        "cifs-utils",
        "nfs-common"
      ]
    },
    "docs": {
      "en": "docs/en/backitup.md",
      "de": "docs/de/backitup.md"
    },
    "platform": "Javascript/Node.js",
    "mode": "daemon",
    "compact": true,
    "icon": "backitup.png",
    "materialize": true,
    "messagebox": true,
    "stopBeforeUpdate": true,
    "connectionType": "local",
    "dataSource": "assumption",
    "materializeTab": true,
    "adminTab": {
      "name": {
        "en": "Backup",
        "de": "Backup",
        "ru": "Резервное копирование",
        "pt": "Cópia de segurança",
        "nl": "Back-up",
        "fr": "Sauvegarde",
        "it": "Backup",
        "es": "Respaldo",
        "pl": "Utworzyć kopię zapasową"
      },
      "ignoreConfigUpdate": true,
      "singleton": false,
      "fa-icon": "</i><img style='width:24px;margin-bottom:-6px;' src='/adapter/backitup/backitup.svg'><i>"
    },
    "adminUI": {
      "config": "materialize",
      "tab": "materialize"
    },
    "enabled": false,
    "extIcon": "https://raw.githubusercontent.com/simatec/ioBroker.backitup/master/admin/backitup.png",
    "keywords": [
      "Backup",
      "IoBroker",
      "Homematic"
    ],
    "readme": "https://github.com/simatec/ioBroker.backitup/blob/master/README.md",
    "loglevel": "info",
    "type": "general",
    "license": "MIT",
    "plugins": {
      "sentry": {
        "dsn": "https://e8510540c3a343aa8ce5678a4b3c8107@sentry.iobroker.net/36"
      }
    },
    "installedFrom": "iobroker.backitup@2.1.13",
    "installedVersion": "2.1.13",
    "host": "iobroker",
    "logLevel": "info"
  },
  "native": {
    "minimalEnabled": true,
    "ccuEnabled": false,
    "redisEnabled": false,
    "javascriptsEnabled": false,
    "zigbeeEnabled": false,
    "jarvisEnabled": false,
    "historyEnabled": false,
    "influxDBEnabled": false,
    "mySqlEnabled": false,
    "pgSqlEnabled": false,
    "grafanaEnabled": false,
    "cifsEnabled": true,
    "ftpEnabled": false,
    "dropboxEnabled": false,
    "googledriveEnabled": false,
    "webdavEnabled": false,
    "notificationEnabled": true,
    "debugLevel": true,
    "sentry_enable": true,
    "historyEntriesNumber": "25",
    "minimalTime": "02:00",
    "minimalEveryXDays": "3",
    "minimalDeleteAfter": "5",
    "minimalNameSuffix": "iobroker_LXC",
    "ccuTime": "01:30",
    "ccuEveryXDays": "3",
    "ccuDeleteAfter": "10",
    "ccuHost": "",
    "ccuUser": "Admin",
    "ccuPassword": "",
    "mySqlHost": "localhost",
    "mySqlPort": "3306",
    "mySqlName": "iobroker",
    "mySqlUser": "",
    "mySqlPassword": "",
    "mySqlDumpExe": "",
    "mysqlQuick": false,
    "mysqlSingleTransaction": false,
    "pgSqlHost": "",
    "pgSqlPort": "5432",
    "pgSqlName": "",
    "pgSqlUser": "",
    "pgSqlPassword": "",
    "pgSqlDumpExe": "",
    "grafanaHost": "",
    "grafanaPort": "3000",
    "grafanaUsername": "admin",
    "grafanaPassword": "",
    "grafanaApiKey": "",
    "influxDBType": "local",
    "influxDBHost": "localhost",
    "influxDBPort": "8088",
    "influxDBName": "iobroker",
    "influxDBDumpExe": "",
    "deleteOldDataBase": false,
    "redisPath": "/var/lib/redis",
    "redisAOFactive": false,
    "historyPath": "media/usb/history",
    "javascriptsPath": "/media/usb/scripts",
    "notificationsType": "Pushover",
    "telegramInstance": "",
    "telegramUser": "none",
    "telegramNoticeType": "longTelegramNotice",
    "telegramWaitToSend": "0",
    "telegramSilentNotice": false,
    "telegramOnlyError": false,
    "whatsappInstance": "",
    "whatsappNoticeType": "longWhatsappNotice",
    "whatsappWaitToSend": "0",
    "whatsappOnlyError": false,
    "pushoverInstance": "pushover.0",
    "pushoverNoticeType": "longPushoverNotice",
    "pushoverWaitToSend": "0",
    "pushoverDeviceID": "",
    "pushoverSilentNotice": false,
    "pushoverOnlyError": false,
    "emailReceiver": "xxx@xxx.com",
    "emailSender": "xxx@xxx.com",
    "emailInstance": "",
    "emailNoticeType": "longEmailNotice",
    "emailWaitToSend": "0",
    "emailOnlyError": false,
    "connectType": "CIFS",
    "cifsMount": "myIP such as 255.255.255.0",
    "cifsDomain": "",
    "smbType": "vers=1.0",
    "cifsUser": "myuser",
    "cifsPassword": "mypassword-phrase",
    "noserverino": false,
    "sudoMount": true,
    "cifsDeleteOldBackup": false,
    "cifsOwnDir": false,
    "wakeOnLAN": false,
    "macAd": "20:DE:20:DE:20:DE",
    "wolWait": "25",
    "cifsMinimalDir": "sharename/backupDir",
    "cifsCcuDir": "sharename/backupDir",
    "cifsDir": "/homes/iobroker/backup",
    "ftpHost": "",
    "ftpPort": "21",
    "ftpUser": "",
    "ftpPassword": "",
    "ftpDeleteOldBackup": false,
    "ftpOwnDir": false,
    "ftpMinimalDir": "/backupDir/iobroker",
    "ftpCcuDir": "/backupDir/ccu",
    "ftpDir": "/backupDir",
    "webdavURL": "https://example.com/remote.php/dav/files/username/",
    "webdavUsername": "username",
    "webdavPassword": "",
    "webdavDeleteOldBackup": false,
    "webdavOwnDir": false,
    "webdavMinimalDir": "/backupDir/iobroker",
    "webdavCcuDir": "/backupDir/ccu",
    "webdavDir": "/backupDir",
    "dropboxAccessToken": "",
    "dropboxDeleteOldBackup": false,
    "dropboxOwnDir": false,
    "dropboxMinimalDir": "/backupDir/iobroker",
    "dropboxCcuDir": "/backupDir/ccu",
    "dropboxDir": "/backupDir",
    "googledriveAccessJson": "",
    "googledriveDeleteOldBackup": false,
    "googledriveOwnDir": false,
    "googledriveMinimalDir": "/backupDir/iobroker",
    "googledriveCcuDir": "/backupDir/ccu",
    "googledriveDir": "/backupDir",
    "restoreSource": "cifs",
    "startAllRestore": false
  }
}

**Comment by simatec** [comment]
You're probably running an unprivileged LXC container. The easiest solution is to use a privileged container instead. However, there might be other solutions; take a look e.g. at [this thread/post](https://forum.proxmox.com/threads/presenting-a-cifs-share-to-a-container.37195/#post-182890) in the proxmox forums.

**Comment by MiRen76** [comment]
OK, thanks. Running priviliged LXC has fixed the issue.
