### ISSUE TITLE
Fehlende Unterstützung des Farbschemas (Admin5)

### ISSUE THREAD

**Issue by crunchip77** [simatec/ioBroker.backitup#529]
Admin 5 Farbschema wird noch nicht unterstützt, da viele das dunkle Design bevorzugen, wäre das wünschenswert, wenn möglich.

**Comment by simatec** [comment]
Da wird dran gearbeitet ... Aktuell fehlt es noch an Unterstützung von Admin 5 für "None react Adapter"

**Comment by simatec** [comment]
Volle Unterstützung in Version 2.1.17
Support muss im Admin noch freigeschaltet werden
