### ISSUE TITLE
Backup's ausserhalb von /opt/iobroker/backups schreiben

### ISSUE THREAD

**Issue by tp1de** [simatec/ioBroker.backitup#53]
Ich benutze ioBroker im docker. Das Verzeichnis /opt/iobroker ist auf ein Nas-Volume gemapped. 
Backup's sollten in ein anderes Verzeichnis geschrieben werden können:
z.B. /opt/backitup 
um Backup's sauber vom ioBroker-Datenverzeichnis trennen zu können.

**Comment by simatec** [comment]
Das ist bei backitup nicht gewollt. 
Das Standard Backupverzeichnis im iob ist /opt/iobroker/backups und da hält sich auch der Adapter dran. 
Wenn du es auslagern willst, kannst du direkt mit nfs oder cifs auf ein NAS schreiben.

**Comment by tp1de** [comment]
Verstehe ich so nicht, da im Docker-Container ein NFS-mount nicht funktioniert! 
In einer virtuellen Maschine funktioniert das problemlos, im Docker nicht.

Bleibt also nur die Möglichkeit im Container ein lokales Verzeichnis zum NAS zu mappen, um dort zu schreiben. Dazu müsste aber das lokale Schreibverzeichnis im Adapter änderbar sein! Denkt bitte nochmal darüber nach.

**Comment by simatec** [comment]
Wie gesagt, da wir auch den iobroker Standard beim Restore und Backup umsetzen, wird hier auch der Standardpfad nicht änderbar werden. 
Tut mir leid, das ist halt im iob so gewollt ...
