### ISSUE TITLE
Bildschirm Darstellung

### ISSUE THREAD

**Issue by Klaus-Lucas** [simatec/ioBroker.backitup#530]
Unter Admin5 öffne ich die Konfigurationsseite eines bestehenden Backups und sehe diese englische Seite:
![klu_008](https://user-images.githubusercontent.com/36620907/128842741-7d926134-13df-45a4-bdc5-482195a12df4.jpg)

Nach einem Refresh der Seite oder einer gewissen Wartezeit, wird die abgespeckte Seite (mit meiner Konfig) in Deutsch gezeigt:
![klu_009](https://user-images.githubusercontent.com/36620907/128842774-d1b3d0de-d84d-42f4-b010-adf73333767b.jpg)

**Versions:**  
 - Adapter version: 2.1.13
 - JS-Controller version: 3.3.15
 - Node version: 16.6.1
 - Operating system: Raspi 10 Buster

**Comment by simatec** [comment]
Das sieht mir nach einem Performance-Problem aus.
Beim Aufruf von Backitup wird erstmal deine Config und ein paar settings geladen.

Wenn dies zu langsam erfolgt, kann es zu diesem Problem kommen.

Was hast du denn für Hardware und wie sieht deine Auslastung vom System aus?

**Comment by Klaus-Lucas** [comment]
Habe generell den Eindruck, dass seit Umstellung auf V5 die Bildschirmwechsel sehr träge sind.
Auf dem Raspi Installiert ist InfluxDB, iobroker, Grafana. 

Hardware:
Modell/Produktname    Raspberry Pi 4 Model B Rev 1.4
Version    d03114
Seriennummer    10000000f14f0f08
Ist virtuelle Maschine    false
Hersteller    Raspberry Pi Foundation
system.raspberry-processor    BCM2711
system.raspberry-type    4B
system.raspberry-revision    1.4

Plattform    linux
Verteilung    Raspbian GNU/Linux
Release    10
Codename    buster
Kernel-release    5.10.52-v7l+
Architektur    arm

Laufende Prozesse:
Anzahl aller Prozesse     154
Anzahl aller Prozesse schlafen    98
Anzahl aller Prozesse unbekannt status    0
Anzahl aller Laufenden Prozesse     1
Anzahl aller Prozesse blockiert     0

![klu_010](https://user-images.githubusercontent.com/36620907/128851989-b55f285e-3a99-41c0-8d9a-850ed3d1b188.jpg)

![klu_011](https://user-images.githubusercontent.com/36620907/128852009-42a2bc86-55aa-4af4-998e-c9b613b1f376.jpg)

![klu_013](https://user-images.githubusercontent.com/36620907/128852423-241ec715-ef9e-4367-84f5-94a5524df9d8.jpg)

Festplatte: 
dev0
Name    sda
Typ    disk
Größe    238.47 GB
Physische Art    HDD
Modell    Intenso_SSD_SATAIII
Protokoll    usb

Windows 10 Pro (21H1).
Browser ist der Firefox 90.0.2 im Einsatz.
PC Hardware:
Asus ROK STRIX B550-F
AMD Ryzen 7 5800X
HyperX FURY 32GB
WD Black SN850 NVMe SSD WDS100T1X0E - SSD - 1TB - intern - M.2 2280 - PCI Express 4,0 x4 (NVMe) (WDS100T1X0E)

**Comment by simatec** [comment]
Werte sehen eigentlich gut aus. Bekommst du eventuell Fehlermeldungen in der Browser Konsole beim Aufruf oder generell mit admin 5?

**Comment by Klaus-Lucas** [comment]
Ja, jeder PC, von dem ich mich anmelde, bekommt solche Meldungen:
![klu_008](https://user-images.githubusercontent.com/36620907/128855267-4fcd7ef6-6bc4-42dc-9eff-b1c1182a0c2f.jpg)

**Comment by simatec** [comment]
Die Fehlermeldungen sind bereits bekannt und es existiert ein Issue dazu.
Im meine aber nicht den iobroker Log, sondern die Browserkonsole (F12)

**Comment by Klaus-Lucas** [comment]
Keine Fehlermeldungen. Momentan ist das Problem auch scheinbar weg. Danke das du dich drum gekümmert hast.

Ich habe in /opt/iobroker/backups mein NFS Share gemountet und mache für Backitup eine lokale Sicherung.
Daher werde ich jedesmal gewarnt, wenn ich die Konfig-Seite öffne. Wäre es nicht sinvoll eine Schaltfläche dafür
zu haben, die die Prüfung ausschaltet?

**Comment by simatec** [comment]
Du musst die Config eigentlich nur einmalig öffnen, um alles zu konfigurieren.
Danach kannst du alles im Tab-Menü bedienen ...
Auf der linken Tableiste kannst du Backitup direkt auswählen.

![image](https://user-images.githubusercontent.com/39792461/128866021-1c3e008f-cfec-42a8-9844-c8e28b1d50e8.png)

**Comment by Klaus-Lucas** [comment]
Diese Meldung kommt in beiden Ansichten:
![klu_001](https://user-images.githubusercontent.com/36620907/128866443-8698af99-163d-45d8-a79b-c15d79c9e65a.jpg)

**Comment by simatec** [comment]
Stimmt ... hatte ich vergessen ;-)
