### ISSUE TITLE
No restore 

### ISSUE THREAD

**Issue by MubiTec** [simatec/ioBroker.backitup#536]
New setup of iobroker. try to restore influxdb from backup. I use influxdb 1.
I tried to restore it with Backitup 2.1.13 + 2.1.17
Both times it started with "Started restore ..." but nothing happens, only this in Debug-log:

backitup.0	2021-08-23 10:16:07.201	debug	sendTo "list" to system.adapter.admin.0 from system.adapter.backitup.0
backitup.0	2021-08-23 10:16:05.087	debug	FTP: connected.
backitup.0	2021-08-23 10:16:04.539	debug	Backup list be read ...
backitup.0	2021-08-23 10:16:02.881	debug	sendTo "getTelegramUser" to system.adapter.admin.0 from system.adapter.backitup.0: {"671102863":{"firstName":"Marcel","userName":"Mubitec"}}
backitup.0	2021-08-23 10:16:02.879	debug	telegram-instance: telegram.0
Versions:			
Adapter version:
JS-Controller version:
Node version:
Operating system:
Additional context
Plattform
linux
Betriebssystem
linux
Architektur
x64
CPUs
2
Geschwindigkeit
3292 MHz
Modell
Common KVM processor
RAM
7.77 GB
System-Betriebszeit
01:49:33
Node.js
v14.17.5 (Empfohlene Version v12.22.5)
NPM
6.14.14
Datenträgergröße
10.77 GB
freier Festplattenspeicher
6.88 GB
Anzahl der Adapter
436
Betriebszeit
01:49:34
Aktive Instanzen
25
location
/opt/iobroker/
Hostname
io

**Comment by simatec** [comment]
Please check your config for Influx in Backitup and make sure that influxd is running on your system

**Comment by MubiTec** [comment]
OK, so I want to check if the password is the same. Is there any possibility to see the Passwort of the influxdb? I backup all adapter settings.is there a possibility to get the used password

**Comment by simatec** [comment]
no the password is encrypted
Check the password with login to influx

**Comment by MubiTec** [comment]
That's not possible, because the old installation is broken:-(

**Comment by simatec** [comment]
After a restore from iobroker, the password is restored in the Influx Adapter.  You can then read the data into Backitup

**Comment by MubiTec** [comment]
OK, I will test it.
But as I understand it right, I had to install influxdb on iobroker host machine, right? And there I have to add the same user with the password as on "old" machine. And this password I do not now.

**Comment by simatec** [comment]
you can also create a new user and assign a new password.  It is important that these are identical in the Influx Adapter and in Backitup and that the database name is identical.

**Comment by MubiTec** [comment]
so I did a new installation of influxdb and create a new user. put it in the influxdb-adapter and the connection is ok.
After that I choose the backitup adapter and tried to restort the backup, but nothing happens, same as written in first post.

do you have any other idea what I can do?

**Comment by simatec** [comment]
The database must not exist during a restore
