### ISSUE TITLE
Löschung alter Backups klappt nicht

### ISSUE THREAD

**Issue by guergen1** [simatec/ioBroker.backitup#538]
Wenn die Sicherungsquelle "lokal" ist, werden die alten Sicherungen nicht gelöscht!
V 2.1.17
NPM 6.14.15
node.js: 12.22.6
js-controller: 3.3.15

**Comment by simatec** [comment]
Bitte poste deine Settings und den Debug Log

**Comment by guergen1** [comment]
Aufgefallen ist es als ich für den Nachbarn ein System aufgesetzt habe und erst mal Lokal gesichert habe. Ich habe bei mir jetzt für die Versuche das NAS-Sichern (auf 192.168.1.92) ausgeschaltet und auf Lokal gesichert. Menge der 
Was mich auch wundert, dass in meinem Log eine alte NAS-Adresse (192.168.1.90) eingetragen ist...

Einstellungen für den Test: 
![grafik](https://user-images.githubusercontent.com/34395245/133918579-56c8b574-3c8f-4dc9-9a2f-24aebc9ce53b.png)
![grafik](https://user-images.githubusercontent.com/34395245/133918662-b9e8495d-584b-4771-b872-e0ea663686b4.png)



Hier das Debug-Log der 7. Sicherung: 
`
<html><body>


2021-09-19 08:43:32.521  - debug: backitup.0 (31232) Redis Objects: Use Redis connection: 0.0.0.0:9001
--
2021-09-19 08:43:32.550  - debug: backitup.0 (31232) Objects client ready ... initialize now
2021-09-19 08:43:32.552  - debug: backitup.0 (31232) Objects create System PubSub Client
2021-09-19 08:43:32.552  - debug: backitup.0 (31232) Objects create User PubSub Client
2021-09-19 08:43:32.554  - debug: backitup.0 (31232) Objects client initialize lua scripts
2021-09-19 08:43:32.577  - debug: backitup.0 (31232) Objects connected to redis: 0.0.0.0:9001
2021-09-19 08:43:32.581  - debug: backitup.0 (31232) objectDB connected
2021-09-19 08:43:32.583  - debug: backitup.0 (31232) Redis States: Use Redis connection: 0.0.0.0:9000
2021-09-19 08:43:32.594  - debug: backitup.0 (31232) States create System PubSub Client
2021-09-19 08:43:32.595  - debug: backitup.0 (31232) States create User PubSub Client
2021-09-19 08:43:32.656  - debug: backitup.0 (31232) States connected to redis: 0.0.0.0:9000
2021-09-19 08:43:32.657  - debug: backitup.0 (31232) statesDB connected
2021-09-19 08:43:33.399  - debug: backitup.0 (31232) Plugin sentry Initialize Plugin (enabled=true)
2021-09-19 08:43:33.618  - info:  backitup.0 (31232) starting. Version 2.1.17 in  /opt/iobroker/node_modules/iobroker.backitup, node: v12.22.6,  js-controller: 3.3.18
2021-09-19 08:43:33.679  - info: backitup.0 (31232) [iobroker] backup was activated at 00:22 every 1 day(s)
2021-09-19 08:43:33.709  - debug: backitup.0 (31232) [iobroker] 10 22 00 */1 * *
2021-09-19 08:43:33.713  - debug: backitup.0 (31232) No backup file was found
2021-09-19 08:43:42.075  - debug: backitup.0 (31232) Backup has started ...
2021-09-19 08:43:45.101  - debug: backitup.0 (31232) [iobroker/iobroker] host.iobroker 28377 states saved
2021-09-19 08:43:45.139  - debug: backitup.0 (31232) [iobroker/iobroker] host.iobroker 21581 objects saved
2021-09-19 08:43:50.562  - debug:  backitup.0 (31232) [iobroker/iobroker] Backup created:  /opt/iobroker/backups/iobroker_2021_09_19-08_43_42_backupiobroker.tar.gz
2021-09-19 08:43:51.654  - debug: backitup.0 (31232) [iobroker/iobroker] done
2021-09-19 08:43:53.414  - debug:  backitup.0 (31232) [iobroker/javascripts] Backup created:  /opt/iobroker/backups/javascripts_2021_09_19-08_43_53_backupiobroker.tar.gz
2021-09-19 08:43:53.415  - debug: backitup.0 (31232) [iobroker/javascripts] done
2021-09-19 08:43:54.317  - debug: backitup.0 (31232) [iobroker/clean] done
2021-09-19 08:43:54.772  - debug: backitup.0 (31232) [iobroker/telegram] [iobroker] used Telegram-Instance: telegram.0
2021-09-19 08:43:54.778  - debug: backitup.0 (31232) [iobroker/telegram] done
2021-09-19 08:43:55.082  - debug: backitup.0 (31232) [iobroker/historyHTML] new history html values created
2021-09-19 08:43:55.082  - debug: backitup.0 (31232) [iobroker/historyHTML] done
2021-09-19 08:43:55.235  - debug: backitup.0 (31232) [iobroker/historyJSON] new history json values created
2021-09-19 08:43:55.236  - debug: backitup.0 (31232) [iobroker/historyJSON] done
2021-09-19 08:43:55.536  - debug: backitup.0 (31232) [iobroker] exec: done


</body>
</html>`

Und hier das Backup-Log der 10.Sicherung:
`Started iobroker ...
[DEBUG] [iobroker] start with {"type":"creator","time":"00:22","debugging":true,"everyXDays":"1","deleteBackupAfter":0,"dir":"/opt/iobroker","javascripts":{"enabled":true,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"192.168.1.90","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/Volume_1/backup/iobroker","dirMinimal":"/backupDir/iobroker","user":"backup","pass":"****","port":"21"},"cifs":{"enabled":false,"mountType":"CIFS","type":"storage","source":"cifs","mount":"192.168.1.92","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=2.0","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":true,"ownDir":false,"dir":"/backup/iobroker/","dirMinimal":"sharename/backupDir","user":"backup","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"webdav":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"filePath":"/home/iobroker/scripte"},"historyHTML":{"enabled":true,"type":"message","entriesNumber":"5","systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"5","systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.0","SilentNotice":true,"NoticeType":"longTelegramNotice","User":"Ralf","onlyError":true,"telegramWaiting":0,"hostName":"","systemLang":"de"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"hostName":"","systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"whatsapp-cmb.0","NoticeType":"longWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [iobroker] - host.iobroker 28377 states saved

[DEBUG] [iobroker] - host.iobroker 21581 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_09_19-09_00_05_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [javascripts] - Backup created: /opt/iobroker/backups/javascripts_2021_09_19-09_00_18_backupiobroker.tar.gz
[DEBUG] [javascripts] - done
[DEBUG] [clean] - done
[DEBUG] [telegram] - [iobroker] used Telegram-Instance: telegram.0
[DEBUG] [telegram] - done
[DEBUG] [telegram] start with {"type":"creator","time":"00:22","debugging":true,"everyXDays":"1","deleteBackupAfter":0,"dir":"/opt/iobroker","javascripts":{"enabled":true,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"192.168.1.90","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/Volume_1/backup/iobroker","dirMinimal":"/backupDir/iobroker","user":"backup","pass":"****","port":"21"},"cifs":{"enabled":false,"mountType":"CIFS","type":"storage","source":"cifs","mount":"192.168.1.92","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=2.0","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":true,"ownDir":false,"dir":"/backup/iobroker/","dirMinimal":"sharename/backupDir","user":"backup","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"webdav":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"filePath":"/home/iobroker/scripte"},"historyHTML":{"enabled":true,"type":"message","entriesNumber":"5","systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"5","systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.0","SilentNotice":true,"NoticeType":"longTelegramNotice","User":"Ralf","onlyError":true,"telegramWaiting":0,"hostName":"","systemLang":"de","time":"19. September 2021 um 09:00 Uhr"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"hostName":"","systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"whatsapp-cmb.0","NoticeType":"longWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[DEBUG] [historyHTML] start with {"type":"creator","time":"00:22","debugging":true,"everyXDays":"1","deleteBackupAfter":0,"dir":"/opt/iobroker","javascripts":{"enabled":true,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"192.168.1.90","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/Volume_1/backup/iobroker","dirMinimal":"/backupDir/iobroker","user":"backup","pass":"****","port":"21"},"cifs":{"enabled":false,"mountType":"CIFS","type":"storage","source":"cifs","mount":"192.168.1.92","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=2.0","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":true,"ownDir":false,"dir":"/backup/iobroker/","dirMinimal":"sharename/backupDir","user":"backup","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"webdav":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"filePath":"/home/iobroker/scripte"},"historyHTML":{"enabled":true,"type":"message","entriesNumber":"5","systemLang":"de","time":"19. September 2021 um 09:00 Uhr"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"5","systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.0","SilentNotice":true,"NoticeType":"longTelegramNotice","User":"Ralf","onlyError":true,"telegramWaiting":0,"hostName":"","systemLang":"de"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"hostName":"","systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"whatsapp-cmb.0","NoticeType":"longWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [historyJSON] start with {"type":"creator","time":"00:22","debugging":true,"everyXDays":"1","deleteBackupAfter":0,"dir":"/opt/iobroker","javascripts":{"enabled":true,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"cifs","host":"192.168.1.90","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/Volume_1/backup/iobroker","dirMinimal":"/backupDir/iobroker","user":"backup","pass":"****","port":"21"},"cifs":{"enabled":false,"mountType":"CIFS","type":"storage","source":"cifs","mount":"192.168.1.92","debugging":true,"fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=2.0","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":true,"ownDir":false,"dir":"/backup/iobroker/","dirMinimal":"sharename/backupDir","user":"backup","pass":"****"},"dropbox":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessToken":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"webdav":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"googledrive":{"enabled":false,"type":"storage","source":"cifs","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker"},"filePath":"/home/iobroker/scripte"},"historyHTML":{"enabled":true,"type":"message","entriesNumber":"5","systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"5","systemLang":"de","time":"19. September 2021 um 09:00 Uhr"},"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.0","SilentNotice":true,"NoticeType":"longTelegramNotice","User":"Ralf","onlyError":true,"telegramWaiting":0,"hostName":"","systemLang":"de"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"hostName":"","systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"whatsapp-cmb.0","NoticeType":"longWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[EXIT] 0`

**Comment by simatec** [comment]
Bei manueller Ausführung des Backups werden keine alten Backups gelöscht. 
Dies geschieht nur während des automatischen Backups
