### ISSUE TITLE
Sicherung von beliebigen Ordner

### ISSUE THREAD

**Issue by derdoerk** [simatec/ioBroker.backitup#539]
Hallo, 

ich habe auf meinem IObroker den RingAdapter lauf wo ich Bilder und videos ablege. 

Nun würde ich dieses Ordner gerne ins Netzwerk auf meiner Nas Sichern, sodass dieser mit gesichert wird. 

Ist dieses möglich?

Gruß
Dirk

**Comment by simatec** [comment]
Du kannst hierzu z.B. das History Backup zweckentfremden. 
Dafür trägst du im Tab History einfach den Pfad deines Ring Adapters ein.
