### ISSUE TITLE
google drive: too many permissions

### ISSUE THREAD

**Issue by n0-m4d** [simatec/ioBroker.backitup#540]
**Describe the bug**  
some might say this is not a bug. at least its it is a security issue...:
access rights granted to backitup when using google drive as backup medium are too wide.

**To Reproduce**  
1. choose google drive as backup medium
2. check app access rights at google security: https://myaccount.google.com/permissions
3. compare access rights with whatsapp access rights (see screen below)

**Expected behavior**  
backitup should have same access rights like e.g. whatsapp: only created files may be edited, viewed, deleted
backitup has access to ALL files!!

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/11576763/134662389-9d15e61c-f01f-43b2-810c-959bbaa1a8e0.png)

**Versions:**  
 - Adapter version: v2.1.17

**Comment by simatec** [comment]
According to the code, Backitup only uses the files it has created itself.  Everything can be found in the code because it is open source

**Comment by n0-m4d** [comment]
i do not doubt that the devs have best intentions. open source is great but suspicious people dont wanna check the code on every update and backitup and its reputation could benefit from requiring just the really necessary permissions.
