### ISSUE TITLE
Popupblocker blockiert Restore-Anzeige

### ISSUE THREAD

**Issue by unstressable** [simatec/ioBroker.backitup#541]
Beim ersten Restore, den ich benötigt habe hat mir der Popupblocker vom Chrome die Restore Anzeige blockiert. Diese hier meine ich:
![image](https://user-images.githubusercontent.com/50423935/135752983-f540c385-fe14-4a95-a37f-5695b9ed9ed8.png)

Einmal erlaubt funktioniert alles, aber dieser erste Restore-Vorgang ist nicht mehr zu sehen.

Hilfreich wäre es, wenn vor dem eigentlichen Restore eine Meldung kommt mit der man die Chance bekommt dem Popupblocker die Erlaubnis zu geben.

**Comment by simatec** [comment]
Kommt mit Version 2.2.x
