### ISSUE TITLE
JavaScript Restore funktioniert nicht komplett

### ISSUE THREAD

**Issue by unstressable** [simatec/ioBroker.backitup#542]
Der Restore der JavaScripte funktioniert nicht, solange im Spiegelordner noch die alten Scripts liegen. Die Scripte werden dann nicht überschrieben.

Der Adapter sollte so angepasst werden, dass vor dem Restore der Spiegelordner der JavaScript Instanz geleert wird:
`pi@ioBroker-RasPi4:/home/iobroker/skripte $ sudo rm -r *`

**Comment by simatec** [comment]
Backup von Scripten wird in Version 2.2.x komplett geändert
