### ISSUE TITLE
Backup of CCU3 (RM) with non-admin user on CCU3 silently fails

### ISSUE THREAD

**Issue by srunschke** [simatec/ioBroker.backitup#544]
**Describe the bug**  
When backing up a CCU3 (RaspberryMatic in my case) with a user that doesn't have Administrator rights, the backup just silently fails without any notice. The backup file gets created, but contains only a HTML page.

**To Reproduce**  
1. Have a RaspberryMatic running, using a user with user rights only
2. Configure BackItUp to backup that CCU3 with said user
3. Run backup

**Expected behavior**  
Since an administrative user is needed to run a backup, the adapter should notice the missing permissions and throw an error. If that's not possible, it should at least notice that the backup was unsuccessful.

**Screenshots & Logfiles**  
Log from running as non-admin user:

`Started ccu ...
[DEBUG] [ccu] - CCU Version: 3.59.6.20210911
[DEBUG] [ccu] - Requesting backup from CCU
[DEBUG] [ccu] - done
[DEBUG] [clean] - done
[DEBUG] [telegram] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[EXIT] 0`

This backup is actually done within 2 seconds - so it is surely not successful.

The created backup file has the following content:

`
< !DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
< html>
< div class="CLASS10600">< a href="#" onclick="javascript:reloadPage();">Weiter< /a>< /div>
< /html>
`

**Versions:**  
 - Adapter version: 2.1.17
 - JS-Controller version: 3.3.18
 - Node version: 12.22.1
 - Operating system: official docker image v5.1.0

**Comment by uneart** [comment]
@srunschke Only to rule out a possible issue duplicate: Do you connect to your CCU via http or https?
Consider to check in the error log if there is an `Error: self signed certificate` present (which would mean this could be at least related to #545). I see a similar behavior in my log, but with the mentioned Error message right before it.

**Comment by srunschke** [comment]
@uneart I'm currently using http with no automatic redirection to https.

Just noticed that if you insert HTML code here, it gets interpreted - even in code tags...

**Comment by srunschke** [comment]
Hm, I don't get it why this was closed. It has absolutely nothing to do with certificates, since I don't even use https...

**Comment by simatec** [comment]
sorry someone mixed up issues and caused some confusion.  I'll look at the topic again.

**Comment by simatec** [comment]
Fix in Version 2.3.x
