### ISSUE TITLE
CCU Backup: Allow usage of self-signed certificates on CCU (https support in local networks)

### ISSUE THREAD

**Issue by uneart** [simatec/ioBroker.backitup#545]
### Problem description

I am using a Homematic CCU3 (running RaspberryMatic) with a local network IP (e.g. 192.168.…) with https activated. This means there is a self-signed SSL certificate installed on it by RaspberryMatic for the IP address.
When trying to do a CCU backup using BackItUp, I get the following error:

```
[ERROR] [ccu] - [IGNORED] Error: self signed certificate
```

It seems that BackItUp can't connect to the CCU over the local network IP when using a self-signed certificate.

---

### Solution I'd like

I would either like to have an option to allow self-signed certificates or – even better – somehow allow only the specific certificate of the CCU.

---

### Alternatives I've considered

The only other option I could think of would be to use http on the CCU => Not really an option as I see a vast decrease in network security then.

---

#### Versions

- NodeJS: v14.15.5
- iobroker: v3.3.18
- BackItUp adapter: v2.1.17
- CCU3: RaspberryMatic v3.59.6.20210911

Error message screenshot:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/1692044/136470397-be62c5ca-b7b4-46ad-9f6e-dd6a15df3959.png">

**Comment by srunschke** [comment]
> How should Backitup determine whether the named user has admin rights? I will write it in the documentation that the user needs admin rights

When logging into the CCU3 it returns a javascript, which contains the user level.

`/**
--
   * User Privilege Level. Gibt die Nutzerrechte des angemeldeten Nutzers an.
   **/
   ul = 8;
   userId = 1004;
    
   /**
   * Privilegstufen.
   **/
   UPL_NONE  = 0;
   UPL_GUEST = 1;
   UPL_USER  = 2;
   UPL_ADMIN = 8;`

**Comment by simatec** [comment]
@uneart Can you post a result with version 2.2.1?

**Comment by drhainka** [comment]
Hello, I tested version 2.2.1. the CCU3 backup is made but a file with 0 kb is created. 
![image](https://user-images.githubusercontent.com/75637168/137767830-02b061fe-0edc-4321-9bce-072d1af5cc8e.png)

**Comment by simatec** [comment]
Can you please test version 2.2.2 of Github and give feedback here?

**Comment by drhainka** [comment]
Great, the CCU backup works over HTTPS :-)

**Comment by simatec** [comment]
Please Check the Backupfile. Is the File ok?
