### ISSUE TITLE
Plötzlich keine Backups mehr.

### ISSUE THREAD

**Issue by McWoolf** [simatec/ioBroker.backitup#547]
Hallo Leute!

Ich verwende den Backitup Adapter schon geraume Zeit. Lief bis 4.Oktober prächtig.
Hier hat der Adapter auch das letzte Backup gemacht. Seit dem kein Backup, keine Fehler nichts.
Selbst wenn ich das Backup per Hand anstoße, fängt das Backup zwar an, aber bleibt anscheinend in einer Schleife hängen und wird nicht fertig. Das einzige Backup, das er noch zieht, ist die InfluxDB. Das wars.
![Fehler](https://user-images.githubusercontent.com/73942255/136516950-3705c340-a3c4-4d7d-a689-5f5188cc6f6b.png)
![Fehler1](https://user-images.githubusercontent.com/73942255/136516964-4f8105a8-b4cb-4ec4-9c1c-64ee10dc3aa7.PNG)
Ich hoffe es kann mir jemand helfen.

**Comment by simatec** [comment]
https://forum.iobroker.net/topic/46685/gelöst-no-connection-to-database?page=1

**Comment by McWoolf** [comment]
Danke für den Link, hab ich auch schon 5 mal durchgeackert, aber geholfen hat nix.
bzw. blicke ich da nicht ganz durch

**Comment by simatec** [comment]
Stelle bitte deinen Frage im iobroker Forum.
Es ist nicht Adapter spezifisch und dementsprechend passt das Issue hier leider an der Stelle nicht so richtig.

Im Forum kann man dir sicher helfen.
