### ISSUE TITLE
Main settings: problem with the checkbox ioBroker

### ISSUE THREAD

**Issue by MK-66** [simatec/ioBroker.backitup#550]
In den Haupteinstellungen: Was soll gesichert werden?
The checkbox ioBroker cannot be unchecked.
This occurs only in V2.2.0 and V2.2.1
Browser: Chrome, Edge, Firefox. System is all up to date (beta).
In V2.1.17 unchecking was still ok. 

![backitup -- uncheck box](https://user-images.githubusercontent.com/56516310/136601253-46a1b0e2-2483-4c21-adee-4e67401a307e.png)

**Comment by simatec** [comment]
fixed in next Version
