### ISSUE TITLE
influxdb 2 backup support

### ISSUE THREAD

**Issue by krobipd** [simatec/ioBroker.backitup#551]
hello

thank you for your great adapter.
it seems that backup influxdb 2.0 is not supported? as there is no mention what influxdb version is supported.

I found that information about the backup usability
https://docs.influxdata.com/influxdb/v2.0/backup-restore/backup/

**Comment by simatec** [comment]
Support comes with version 2.2.2

**Comment by MarkSau** [comment]
Hi..erstmal danke für den super Adapter. Ist schon oft hilfreich gewesen. 
Wann könnte denn die Sicherung von Influxdb v2 innerhalb von Backupit kommen? 
Ich könnte mich auch als Tester zur Verfügung stellen.

**Comment by simatec** [comment]
Ich denke, dass ich mich nach Weihnachten ran setzen werde

**Comment by MarkSau** [comment]
Gibt es hierzu schon einen Lösungsansatz?

**Comment by nkleber78** [comment]
Hätte da auch Interesse daran...

**Comment by nkleber78** [comment]
@simatec Ist der Support von influxdb2 trotzdem noch im Fokus? Wie sieht der Plan von deiner Seite aus bis wann das kommen könnte?

**Comment by simatec** [comment]
Der Support ist bereits integriert und aktuell noch im Dev-Branch. Da ich gerade an Version 2.3.x arbeite und dieses Thema ein Meilenstein war, wurde es von mir geschlossen
