### ISSUE TITLE
Backup GoogleDrive

### ISSUE THREAD

**Issue by hugo419752** [simatec/ioBroker.backitup#554]
**Backup doesn't work propperly**  
After renewing the google drive acces the backup works for exactly one time.
After that i get the following error:

Started iobroker ...
[DEBUG] [iobroker] - host.raspberrypi 4117 states saved

[DEBUG] [iobroker] - host.raspberrypi 4662 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2021_10_22-08_25_53_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [googledrive] - Google Drive: Copy iobroker_2021_10_22-08_25_53_backupiobroker.tar.gz...
[ERROR] [googledrive] - Google Drive: Error: The specified parent is not a folder.
[DEBUG] [googledrive] - done
[DEBUG] [clean] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[EXIT] 0

**Expected behavior**  
I expect to get more backups saved than the first one.

**Versions:**  
 - Adapter version: <2.1.17>
 - JS-Controller version: <3.3.18>
 - Node version: <12.22.06>

**Comment by simatec** [comment]
Please check your path an Google Account

**Comment by hugo419752** [comment]
What do you mean with check the path?
The first backup file is saved in the right folder. And the second backup file occured the error message.

**Comment by simatec** [comment]
![image](https://user-images.githubusercontent.com/39792461/140510904-070ee80c-a843-451f-bd1a-1fd8f27212ca.png)
![image](https://user-images.githubusercontent.com/39792461/140511063-92b0b715-09a0-47b3-a032-57255f9e75c3.png)

**Comment by hugo419752** [comment]
Ok, path was checked. It's correct. 
But that isn't the problem. The first backup file is saved in the correct folder. Exactly as the system should work. But at every next try to save a new backup file, the above mentioned error occures.

**Comment by simatec** [comment]
try to relink Backitup to your Google account

**Comment by hugo419752** [comment]
I now relinked the Google account. Same thing. First backup is saved. After that every next attempt leads into an error. Are there special settings @ the Google account needed?

**Comment by simatec** [comment]
If you google for the error, you will see that the error does not affect Backitup.  The bug affects the Google API.  Please show me your complete configuration of Backitup as json.

**Comment by hugo419752** [comment]
Im pretty new to this. 
How do i find the json from Backitup?

**Comment by simatec** [comment]
![image](https://user-images.githubusercontent.com/39792461/141278288-800caf09-f9bc-43bd-a570-b91a370a44f0.png)

**Comment by hugo419752** [comment]
How can I provide the file?

**Comment by simatec** [comment]
Here on Github ... You can clean your personal data

**Comment by hugo419752** [comment]
enclosed the json file 
[system.adapter.backitup.0.zip](https://github.com/simatec/ioBroker.backitup/files/7520472/system.adapter.backitup.0.zip)

**Comment by hugo419752** [comment]
Hello, updated to Version 2.2.2.
Case closed. Everything works fine.

Thx
