### ISSUE TITLE
Backitup - Fehlermeldung Zigbee

### ISSUE THREAD

**Issue by baerenwaldfreund** [simatec/ioBroker.backitup#568]
Beim Aufrufen der Einstellungen des backitup-Adapters erscheint folgende Fehlermeldung:

`Auf diesem Host wurde keine zigbee-Instanz gefunden. Bitte überprüfen Sie Ihr System`

Es ist aber eine zigbee-Instanz installiert. Das Backup läuft ohne Probleme durch. Es erscheint lediglich die falsche Fehlermeldung.

Der Fehler tritt bei meinen beiden ioBroker-Slaves auf, welche beide auf einem RPi3 bzw. RPi3+ laufen.

**Comment by Andy200877** [comment]
Bei mit das gleiche....
Bei mir läuft das Hauptsystem (Master) auf einem NUC im Keller.
Ein RPi läuft im Wohnbereich als Slave. Dort läuft die zigbee.0 Instanz.
Ein weiterer RPi läuft in einem Anbau. Dort läuft meine zigbee.1 Instanz.

Beim Adapter (Version 2.2.2 auf allen System) kommt überall die Meldung das keine zigbee-Intanz gefunden werden kann.

Das Backup läuft auch durch, aber es enthält nur die shepherd.db von zigbee.0
Von der 2. Zigbee Instanz wird KEIN BACKUP angelegt. :-(

**Comment by simatec** [comment]
@Andy200877 Bitte in der Doku von Backitup den Bereich Master / Slave Backup mal durchlesen

**Comment by OlfrygtACAB** [comment]
moin moin, jetzt habe ich auch dieses problem.
die doku hilft mir leider auch nicht weiter.
gibt es lösungsvorschläge

**Comment by simatec** [comment]
Bitte genauer beschreiben, wo dein Problem liegt und welcher Fehler auftritt

**Comment by simatec** [comment]
Welche Version von Backitup ist installiert?

**Comment by OlfrygtACAB** [comment]
v2.3.3

**Comment by simatec** [comment]
Bitte den Log prüfen. Ab Version 2.3.x werden Fehler strikter behandelt
Die Warnung mit Zigbee schaue ich mir an. Ist aber nur ne reine Popup Meldung und hat keinen Einfluss auf ein backup

**Comment by OlfrygtACAB** [comment]
Auf diesem Host wurde keine zigbee-Instanz gefunden. Bitte überprüfen Sie Ihr System

**Comment by simatec** [comment]
> Auf diesem Host wurde keine zigbee-Instanz gefunden. Bitte überprüfen Sie Ihr System

Ist wie gesagt nur ein Info Popup und nicht relevant

**Comment by simatec** [comment]
> also wenn ich im backitup adapter de harken bei zigbee wegmache, macht er die updates wie er soll. sobald ich ihn wieder setze heisst es wieder keine zigbee instanz gefunden und nichts geht mehr.
> 
> `
> 
> backitup.0	2022-03-02 09:50:36.904	info	[iobroker] backup was activated at 00:00 every 1 day(s)
> backitup.0	2022-03-02 09:50:36.785	info	starting. Version 2.3.3 in /opt/iobroker/node_modules/iobroker.backitup, node: v14.19.0, js-controller: 4.0.15
> backitup.0	2022-03-02 09:50:29.964	info	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
> backitup.0	2022-03-02 09:50:29.961	info	terminating
> backitup.0	2022-03-02 09:50:29.957	info	cleaned everything up...
> backitup.0	2022-03-02 09:50:29.955	info	Got terminate signal TERMINATE_YOURSELF`

Bitte zeige den Debuglog
