### ISSUE TITLE
Unterschiedliche Anzahl der Sicherungen lokal und remote 

### ISSUE THREAD

**Issue by fu-zhou** [simatec/ioBroker.backitup#569]
Hallo, vielen Dank für den tollen Adapter, der mir schon so manches Leid erspart hat!
Ich lasse jeden Tag eine Sicherung laufen und beschränke die Anzahl der Sicherungen auf 5. Meine SQL Datenbank hat jetzt 11GB, die komprimierte Version 1,7GB. Davon werden 5 Versionen auf dem lokalen Medium gehalten (/opt/iobroker/backups). Heute ist nach dem Backup der iobroker nicht mehr erreichbar gewesen, über putty konnte ich zugreifen und sehen, dass die Platte voll war. Im Backup-Verzeichnis lag die unkomprimierte Datenbank (11GB) neben den Archiven, scheinbar ist im Laufe des gestrigen Tages die Datenbank das entscheidende Bisschen größer geworden, so dass umkopieren und dann komprimieren nicht mehr funktioniert. Die Festplatte vergrößern (VM) möchte ich erst einmal nicht, da stoße ich dann an Hardwaregrenzen.
Gäbe es folgende Möglichkeiten:

1. Den MYSQL Dump zur Komprimierung nicht lokal sondern auf dem FTP- oder NAS Server zu erstellen (ich nutze FTP)
2. Lokal nur 1 (parametrierbar) Sicherung zu behalten, aber auf dem FTP- oder NAS Server eine unterschiedliche Anzahl (parametrierbar).

Danke vorab und Gruß!

**Comment by simatec** [comment]
Deine Vorstellungen sind mit FTP nicht machbar, da die fertigen Backups lediglich als Kopie auf dem FTP Server abgelegt werden.
Wenn du dein NAS hier besser nutzen willst, wähle NFS oder CIFS ... Somit hast du nichts mehr lokal.
Als zusätzliche Sicherungsquelle kannst du dann auch noch eine Cloud in Backitup wählen.
