### ISSUE TITLE
Mysql Backup funtioniert nicht in Docker

### ISSUE THREAD

**Issue by nkleber78** [simatec/ioBroker.backitup#58]
Das Mysql Backup funktioniert nicht, wenn ioBroker innerhalb eines Docker containers ausgeführt wird. Das ist z.b. auf allen Synology Geräten der Fall. Wird mysqldump im Paket mitgeliefert? ggf. wäre es sinnvoll das zu tun damit das System immer zuverlässig funktioniert. Interessant ist zusätzlich noch die Meldung "[minimal/mysql] mysqldump: Got error: 2002: "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")" when trying to connect. Denn in meinem Fall verwende ich keine Sockets sondern es geht über den localhost / Port 3307. So ist auch der SQL Adapter eingestellt 
![image](https://user-images.githubusercontent.com/35381530/48695563-c29b6b80-ebdf-11e8-916a-78715274ba77.png)

**Comment by simatec** [comment]
Hallo,

die mysqldump wird nicht mitgeliefert.
Diese musst du schon selber installieren, da backitup Plattformübergreifend ist.
Wenn deine mysqldump nicht im Standardverzeichnis liegt, musst du bei backitup in der config den Pfad anpassen.

**Comment by nkleber78** [comment]
Ok soweit, die Frage stellt sich dann aber wohin soll ich das mysql bin verzeichnis mappen? Wo sucht das Backup? Docker erlaubt ja nicht dass ein Container auf den Host zugreift, sondern der Container kann immer nur innerhalb des Docker sein solange es kein Verzeichnis-Mappping auf den Host gibt. Hast du da Präferenzen. ggf. wäre es gut das in der Beschreibung zu erwähnen denn es wird immer mehr mit Docker gearbeitet, auch auf PC's nicht nur auf NAS wie Synology... Die Funktionalität eures Adapters finde ich nämlich sehr gut!

**Comment by nkleber78** [comment]
habe nun mysqldump mal zum test gemappt. Aber jetzt laufen ich in folgende Fehler. Was passiert da?
host.IOBroker | 2018-11-19 11:34:10.235 | error | instance system.adapter.backitup.0 terminated with code 0 (OK)
host.IOBroker | 2018-11-19 11:34:10.235 | error | Caught by controller[0]: at FSReqWrap.oncomplete (fs.js:123:15) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
host.IOBroker | 2018-11-19 11:34:10.234 | error | Caught by controller[0]: at WriteStream.<anonymous> (fs.js:2136:10)
host.IOBroker | 2018-11-19 11:34:10.234 | error | Caught by controller[0]: at WriteStream.emit (events.js:188:7)
host.IOBroker | 2018-11-19 11:34:10.234 | error | Caught by controller[0]: at emitOne (events.js:96:13)
host.IOBroker | 2018-11-19 11:34:10.234 | error | Caught by controller[0]: at WriteStream.g (events.js:292:16)
host.IOBroker | 2018-11-19 11:34:10.234 | error | Caught by controller[0]: at WriteStream.stream.once.fd (/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/30-mysql.js:19:25)
host.IOBroker | 2018-11-19 11:34:10.233 | error | Caught by controller[0]: at exports.spawn (child_process.js:370:9)
host.IOBroker | 2018-11-19 11:34:10.233 | error | Caught by controller[0]: at ChildProcess.spawn (internal/child_process.js:328:11)
host.IOBroker | 2018-11-19 11:34:10.233 | error | Caught by controller[0]: at exports._errnoException (util.js:1020:11)
host.IOBroker | 2018-11-19 11:34:10.232 | error | Caught by controller[0]: { Error: spawn EACCES
backitup.0 | 2018-11-19 11:34:09.693 | error | Error: spawn EACCES at exports._errnoException (util.js:1020:11) at ChildProcess.spawn (internal/child_process.js:328:11) at exports.spawn (child_process.js:370:9) at WriteStream.strea
backitup.0 | 2018-11-19 11:34:09.692 | error | uncaught exception: spawn EACCES

**Comment by nkleber78** [comment]
Hallo ,

habe noch etwas weiter getestet. Dabei ist mir aufgefallen dass es ja ein npm mysqldump gibt. mit diesem kann man einfach den dump erstellen. Somit wäre es doch perfekt man würde dieses command integrieren anstelle das file vom System zu verwenden. Oder spricht da aus deiner Sicht was dagegen? Das wäre dann eine gute Lösung für alle "Docker" user

**Comment by simatec** [comment]
Schauen wir uns an ...
