### ISSUE TITLE
backup history: autocorrection of '\' to '/' does not work

### ISSUE THREAD

**Issue by rg-engineering** [simatec/ioBroker.backitup#582]
I used a path '\home\user\projects\history' in history adapter to store history data. That adapter works well with that setting.
Then I tried to backup those history data. The nice feature "detect config" took that setting but history adapter was not able to store backups. I always got an error message like "could not compress undefined".
After some investigation I found the problem:

backitup wants the (correct) setting '/home/user/projects/history', an existing autocorrection does not work.

why?

` if (fs.existsSync(options.path)) {
` 
in 34-historyDB.js checks whether a path exists. This returns false with my (wrong) settings and so the complete autocorrection feature which follows in next lines of code is not executed. This leads to pth to be undefined and so nothing is compressed.

I would suggest to do autocorrection before calling fs.existsSync and an error log in else path of that check to inform user to check path settings...

**Comment by marios774** [comment]
Dem Fehler mit dem History muss ich mich anschließen, den habe / hatte ich auch.
```
[DEBUG] [historyDB] - compress from historyDB started ...
[ERROR] [historyDB] - [IGNORED] Backitup cannot found source "undefined" for compress!
```
Ich habe im History, den alten Pfad gelöscht, somit wird auf **opt/iobroker/iobroker-data/history** gespeichert.
<img width="732" alt="Bildschirmfoto 2022-02-05 um 11 21 51" src="https://user-images.githubusercontent.com/32393760/152638333-63300f59-b154-4caf-82f9-12c0c35e5da9.png">

Das ermitteln der Konfiguration im BackItUp hat den Pfad zwar gelöscht, der Fehler blieb.
Erst durch Eingabe des kompletten Pfades konnte ich das BackUp ordnungsgemäß erstellen.
<img width="343" alt="Bildschirmfoto 2022-02-05 um 11 32 12" src="https://user-images.githubusercontent.com/32393760/152638486-7849d8d8-680e-43d1-8ca4-456278e3363c.png">
