### ISSUE TITLE
InfluxDB backup suddenly not working anymore

### ISSUE THREAD

**Issue by atoerschen** [simatec/ioBroker.backitup#583]
Hello,

i am using influxDB now for more then a year. I use the backitup Adapter accordingly for also InfluxDB, CCU3, and iobroker itself.

Everything was working properly until 22.12.2021. This was the last backup of influxDB. CCU3 and Iobroker are still working properly.

However something happened on that day or better on 23.12.2021 . I got for the influxDB error messages in the backitup logfile.

i don't know what i have done in that time frame. I updated iobroker from 5.21. to 5.22. and i got problems after that. this was then fixed over the weekend with version 5.2.3
Other then that i have no clue what i have done else in order to provoke that outcome.

another effect is that Grafana is not showing anymore data before 23.12.2021. 

[DEBUG] [influxDB] - InfluxDB-Backup started ...
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[ERROR] [influxDB] - [IGNORED] Error: Command failed: influxd backup -portable -database iobroker "/opt/iobroker/backups/influxDB_2021_12_30-13_09_28_backupiobroker"
2021/12/30 13:09:29 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2s and retrying (0)...
2021/12/30 13:09:31 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2s and retrying (1)...
2021/12/30 13:09:33 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2s and retrying (2)...
2021/12/30 13:09:35 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2s and retrying (3)...
2021/12/30 13:09:37 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2s and retrying (4)...
2021/12/30 13:09:39 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2s and retrying (5)...
2021/12/30 13:09:41 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 3.01s and retrying (6)...
2021/12/30 13:09:44 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 11.441s and retrying (7)...
2021/12/30 13:09:56 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 43.477s and retrying (8)...
2021/12/30 13:10:39 Download shard 0 failed dial tcp [::1]:8088: connect: connection refused.  Waiting 2m45.216s and retrying (9)...
backup: dial tcp [::1]:8088: connect: connection refused

![image](https://user-images.githubusercontent.com/96652523/147750901-db59a970-13b9-4c22-bf74-6416ce5aa314.png)

**Versions:**  
 - Adapter version: <2.2.2>
 - JS-Controller version: <3.3.22> 
 - Node version: <14.18.2> 
 - Operating system: <Raspberry OS>

**Additional context**  
i run regulary apt-get update on my Raspberry 4, so therefore i am up to date with these updates also.

Thank you in advance

Andreas T.

**Comment by simatec** [comment]
I think that with an apt upgrade the influxdb was updated and now the permissions do not match.  Which version is installed?

**Comment by atoerschen** [comment]
Hello ,

the version is
InfluxDB v1.8.10 (git: 1.8 688e697c51fd)

Best
Andreas

**Comment by simatec** [comment]
Please check the permissions from Influxdb

**Comment by atoerschen** [comment]
Hello i found the following permissions:


pi@raspberrypi:~/docker/influxdb/data $ cd iobroker
-bash: cd: iobroker: Keine Berechtigung
pi@raspberrypi:~/docker/influxdb/data $ ls -l
insgesamt 8
**drwx------ 4 root root 4096 Jan  3  2021 _internal
drwx------ 4 root root 4096 Apr  5  2021 iobroker**
pi@raspberrypi:~/docker/influxdb/data $ cd _internal
-bash: cd: _internal: Keine Berechtigung
pi@raspberrypi:~/docker/influxdb/data $

**Comment by simatec** [comment]
Unfortunately, this is not a problem for Backitup, so the issue does not help here.  

I think it would be better to create an issue for the Docker Container.

**Comment by buanet** [comment]
> I think it would be better to create an issue for the Docker Container.

Please don't. As long as InfluxDB Backup is not supported when using Docker. We first need to test and make sure Influx DB Backup is working. For more details and progress follow here: https://github.com/buanet/ioBroker.docker/issues/202

Regards,
André

**Comment by atoerschen** [comment]
Hello, 
sorry for the late reply. 

my iobroker is located in the directory 



![Bildschirmfoto 2022-01-08 um 14 02 10](https://user-images.githubusercontent.com/96652523/148645228-687fb7d6-29a5-4791-9ca9-51c2b78864d0.png)

I have test also the backup of influxDB manually, but i cannot.  I get error messages also with this approach.

![Bildschirmfoto 2022-01-08 um 14 08 53](https://user-images.githubusercontent.com/96652523/148645355-b642916e-807f-4a28-a63e-db845f735b38.png)


Grafana has no data before December 23, 2021 anymore, but is still recording directly from InfluxDB until now.

![Bildschirmfoto 2022-01-08 um 14 11 55](https://user-images.githubusercontent.com/96652523/148645499-36fca022-90a7-43c3-b02f-65ad13d6eef9.png)


I have no clue anymore to solve this on my own.

Thank you for your help.

Best
Andreas

**Comment by simatec** [comment]
Port 8088 must also be configured correctly in the influx config.  
You can find all the important information about this in the documentation.

**Comment by BS-GIFHUB** [comment]
I have the same issue: 

[DEBUG] [influxDB] - InfluxDB-Backup started ...
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[ERROR] [influxDB] - [IGNORED] Error: Command failed: influxd backup -portable -database iobroker "/opt/iobroker/backups/influxDB_2022_01_11-22_33_16_backupiobroker"
Error: unknown shorthand flag: 'p' in -portable
See 'influxd -h' for help

**Comment by BS-GIFHUB** [comment]
influxdb is a fresh installation. Port is 8086 and version is 2.1.1

**Comment by simatec** [comment]
Backup for Influxdb 2.x is planned in Backup version 2.3.x.
