### ISSUE TITLE
Possibility to include node red in backups 

### ISSUE THREAD

**Issue by Claus1985** [simatec/ioBroker.backitup#588]
**Is your feature request related to a problem? Please describe.**
I use node red (ioBroker adapter) for a lot of different things. At the moment all scripts etc. have to be safed in a separate export/backup. 

**Describe the solution you'd like**
Possibility / Option within backitup to backup all node red flows and scripts (just about everything).

**Describe alternatives you've considered**
Manually this is a quick task since node red scripts can simply be exported and restored like blockly scripts. But it would be awesome if backitup could include this function for an automatism.

**Comment by DocGame69** [comment]
Ich beschäftige mich seit einigen Tagen auch intensiv mit Node Red. 
Besteht die Möglichkeit die Sicherung von Node Red mit einzubauen?

**Comment by MarkBpunkt** [comment]
Die gesamten NodeRed Flows sind in der normalen ioBroker Backup mit enthalten, da die Flows als Datenpunkt angelegt werden.
![grafik](https://user-images.githubusercontent.com/99531337/153704736-96b9f87d-76f9-4192-9c28-296c8ba28b3c.png)

Im Bedarfsfall könnte man die Flows manuell aus dem Backup rauskopieren.

M.

**Comment by Claus1985** [comment]
d.h. wenn ich mit backitup ein ioBroker Backup wieder einspiele ist NodeRed schon sowieso enthalten?
