### ISSUE TITLE
Feature Request - boolsches Objekt "success"

### ISSUE THREAD

**Issue by olderbag** [simatec/ioBroker.backitup#59]
Es gibt ja bereits die Objekte ..LastTime, in denen zu sehen ist, wann zuletzt ein Backup gemacht wurde.

Schön wären zusätzliche boolsche Objekte, die den Erfolg des letzten Backups darstellen:
minimalSuccess
totalSuccess
ccuSuccess

Damit hätte man direkt einen Indikator, den man auswerten könnte - z.B. um den Status true/false in direkt VIS darzustellen.

**Comment by simatec** [comment]
Schauen wir uns an, ist aber aktuell eigentlich nicht geplant ...

**Comment by simatec** [comment]
Kommt mit der nächsten Version ...
