### ISSUE TITLE
Falsche Benachrichtigung bei fehlgeschlagenem Dropbox-Backup

### ISSUE THREAD

**Issue by Standarduser** [simatec/ioBroker.backitup#592]
Wenn der Dropbox-Token nicht die korrekten Rechte enthält meldet Backitup im Log den Fehler `Dropbox: "missing_scope/."`
Die Fehlermeldung ist berechtigt, es lag ein Problem vor.

Dennoch wurde als Telegram-Benachrichtigung folgende Meldung ausgegeben:
"BackItUp: Eine neue iobroker  Sicherung wurde am 13. Januar 2022 um 18:31 Uhr erstellt, und in der Dropbox gespeichert."

Die Meldung ist falsch, da das Backup nicht gespeichert werden konnte.

**Comment by simatec** [comment]
Bugfix kommt in Version 2.3.x
