### ISSUE TITLE
Wunsch: Google Drive Integration

### ISSUE THREAD

**Issue by Starcon79** [simatec/ioBroker.backitup#60]
Hallo erstmal vielen Dank für den tollen Adapter.
Ich würde mir wünschen das neben Dropbox auch Google Drive integriert wird da ich Dropbox nicht nutze.
Ist dies möglich?
Wäre echt Klasse.

**Comment by simatec** [comment]
Ist für die Zukunft geplant ...

**Comment by pockeras** [comment]
Und warum ist Dropbox nicht mehr vorhanden?

**Comment by simatec** [comment]
Dropbox war nie weg ...
