### ISSUE TITLE
Mount of CIFS fails: Permission denied

### ISSUE THREAD

**Issue by walli545** [simatec/ioBroker.backitup#61]
Hi,
i am using version 0.3.8. 

After running a backup i get the following error message:
```
Error: Command failed: mount -t cifs -o user=ioBroker,password=<mypw>,rw,file_mode=0777,dir_mode=0777 //192.168.178.40/ioBroker-Backup /opt/iobroker/backups
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```

I tried to execute the command manually in the command line but i got this error:
`mount: only root can use "--options" option`.

If i execute the command with root the share is mounted successfully.

Now my question is if it is possible to run the backitup adapter with root or if there is a miss configuration from my side.

**Comment by simatec** [comment]
For the manual command you have to do it with "sudo".

The error is not due to backitup.
Since your config or your system is not in order.

Did you install cifs-utils?
If not, please install it first with "sudo apt-get install cifs utils" as described in the documentation.
