### ISSUE TITLE
Dark Theme. Button colors are low contrast

### ISSUE THREAD

**Issue by GermanBluefox** [simatec/ioBroker.backitup#614]
**Describe the bug**  
Regular buttons on the Dark theme are low contrasted. Used background #E0E0E0 and foreground #FFFFFF. There are too similar colors and it is not visible.
[https://i.imgur.com/aOqL9hI.png](https://i.imgur.com/aOqL9hI.png)

**To Reproduce**  
Admin driver 5.2.3 (stable)
1. Set the dark theme for admin'
2. Click on the 'Backup' point in the side panel (a similar problem with Alias Manager)
3. See button 'iobroker start backup' as background #E0E0E0 and foreground #FFFFFF.
4. Wait for 5-10 sec. Button 'iobroker start backup' has been self-updated to background #3399CC and foreground #FFFFFF. 

**Expected behavior**  
The button should be more contrasted

**Versions:**  
 - Adapter version: 5.2.3 stable
 - JS-Controller version: 3.3.22
 - Node version: 14.18.1
 - Operating system: Raspbian 11

**Additional context**

**Comment by simatec** [comment]
@GermanBluefox Thanks for your feedback. I will fix it in the next version

**Comment by simatec** [comment]
Here, my suggestion.
@GermanBluefox  what do you mean? I tried to use the react as a guide

Backitup Tab:
![image](https://user-images.githubusercontent.com/39792461/153215876-7963b9da-6c25-4422-a0dc-e781d3fdb72a.png)

react Design in Adapter Upload:
![image](https://user-images.githubusercontent.com/39792461/153216069-d2bc9cda-d0ba-48bf-bac2-617d4d43fd5b.png)

**Comment by simatec** [comment]
Fix in the next version 2.3.0
