### ISSUE TITLE
Please add possibility to save backup to OneDrive

### ISSUE THREAD

**Issue by FraatGIT** [simatec/ioBroker.backitup#615]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Please add possibility to save backup to OneDrive

**Describe alternatives you've considered**

**Additional context**

**Comment by jk-andersen** [comment]
+1

**Comment by Scrat94** [comment]
+1

**Comment by TimoGoerlich** [comment]
+1 hard

**Comment by simatec** [comment]
Currently there is no meaningful support for Onedrive.

When there is official support for this on npm I will reopen the issue

**Comment by FraatGIT** [comment]
Hallo, 
is this not a Onedrive support for npm ?
https://www.npmjs.com/package/onedrive-api

**Comment by firebowl** [comment]
Please please implement :)
