### ISSUE TITLE
Backitup adapater is just keeping one backup

### ISSUE THREAD

**Issue by monarc83** [simatec/ioBroker.backitup#617]
**Describe the bug**  
Backitup adapater is just keeping one backup even it is configured to keep the last 10 backup files

**Expected behavior**  
Keep the last 10 backup files and delete all older files

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/36295048/153493167-fb0f168f-f2cf-4540-a13e-f01e67b2c096.png)
![grafik](https://user-images.githubusercontent.com/36295048/153493800-233e9e14-4c07-48b4-b0f8-ec369cff54ca.png)

**Versions:**  
 - Adapter version: 2.2.4
 - JS-Controller version: 3.3.22
 - Node version: 14.19.0
 - Operating system: Container / buanet/iobroker / Linux version 5.10.28-Unraid

**Comment by monarc83** [comment]
Okay, for some strange reason, last evening it worked for the first time since some time. I will keep an eye on it, and report back in a couple of days.

**Comment by simatec** [comment]
Please also check the user rights in your path.

This is not the original backup path

**Comment by monarc83** [comment]
Yes, I linked it through container settings. Any better suggestions for a docker/container setup?

![grafik](https://user-images.githubusercontent.com/36295048/153585563-55976845-2698-4210-bba3-4a0ac36af0d1.png)

**Comment by simatec** [comment]
If you have a privileged container you can use nfs or cifs mount.

Otherwise FTP, dropbox, GoogleDrive and Webdav as storage options
