### ISSUE TITLE
influxdb2 probleme

### ISSUE THREAD

**Issue by krobipd** [simatec/ioBroker.backitup#619]
Hallo und erstmal vielen vielen dank für deine Arbeit.

habe soeben das neue Update auf Version 2.3 gemacht und natürlich sofort die InfluxDB 2 Integrierung ausprobiert.

habe da aber momentan so meine Schwierigkeit.
zum Anfang würde ich gerne vorschlagen, einen test button einzubauen bzw eine jetzt sichern Funktion. das wäre super vor allem beim konfig ausprobieren.

zum anderen klappt es bei mir einfach nicht.
ich hatte zuerst mal keinen Pfad angegeben und die Konfig übernommen dann gab es folgende Fehlermeldung:

> [iobroker] Error: Command failed: influx backup --bucket iobroker -t mein token "/opt/iobroker/backups/influxDB_2022_02_11-16_19_13_backupiobroker"/bin/sh: 1: influx: not found

dann hatte ich etwas Verständnisprobleme mit der aussage "Pfad mit dem Dateinamen zum influxd Programm". für mich hört sich das nach dem Pfad an, was du aber möchtest ist quasi komplett mit Datei. den mit /usr/bin hatte mir folgenden Fehler geworfen

> [iobroker] Error: Command failed: "/usr/bin" backup --bucket iobroker -t mein Token "/opt/iobroker/backups/influxDB_2022_02_11-16_29_02_backupiobroker"/bin/sh: 1: /usr/bin: Permission denied

dann hab ich kapiert das es "/usr/bin/influxd" sein muss, aber damit hab ich jetzt eine neue fehlermeldung

> [iobroker] Error: Command failed: "/usr/bin/influxd" backup --bucket iobroker -t mein Token "/opt/iobroker/backups/influxDB_2022_02_11-16_30_22_backupiobroker"Error: unknown flag: --bucketSee 'influxd -h' for help

mich wundert es sowieso etwas warum ich einerseits die Organisation nicht angeben muss wie im InfluxDB adapter und andererseits gibt es laut InfluxDB backup doku den parameter "bucket" gar nicht.

https://docs.influxdata.com/influxdb/v2.1/backup-restore/backup/

**Comment by simatec** [comment]
Du musst dir influx-cli installieren. Das wird generell für ein Backup der influxdb2 benötigt. 

Doku dafür kommt noch von mir. Musste die Beta leider etwas vorziehen

**Comment by krobipd** [comment]
super vielen dank 😊 
nach der installation und dem entfernen des Pfades (den ich ja vorher eingegeben hatte und standardmässig leer ist) hat das jetzt alles wunderbar und reibungslos funktioniert 🥳

vl kann man das in die doku mit aufnehmen.

vielen dank

**Comment by simatec** [comment]
Kommt noch mit in die Doku
