### ISSUE TITLE
Speicherverbrauch nach Backup hoch

### ISSUE THREAD

**Issue by eumats** [simatec/ioBroker.backitup#62]
Hallo,

ich nutze backitup aus einem Raspi 3. Nach dem Neustart der Instanz verbraucht der backitup ca. 32MB RAM (Quelle: iobroker -> Instanzen). Wenn dann über Nacht die Backups gelaufen sind, ist der RAM Verbrauch dauerhaft bei über 100MB. Nach einem Neustart der Instanz ist der Verbrauch dann wieder normal.
Aktuell behelfe ich mir damit, dass backitup jeden morgen neu gestartet wird. Das hat über wiederum negative Auswirkungen auf Backup-Jobs die nicht täglich laufen, sondern z.B. nur alle 3 Tage. Diese funktionieren dann nicht.
Der "hohe" Speicherverbrauch ist gerade auf dem Raspi auf des geringen RAMs schwierig.

Es wäre schön, wenn Ihr mal schauen könntet.

Ich nutze backitup in der Version 0.3.8 auf einem Multihostsystem bestehend aus 2 Raspi 3.

Nachtrag: Ich habe backitup bereits komplett deinstalliert und neu aufgesetzt. Ergebnis: ohne Veränderung.

Gruß
Björn

**Comment by simatec** [comment]
Das hat nichts mit backitup oder iob zu tun. 
Linux hat ein eingenes Speichermanagement und du brauchst dir keine Sorgen machen. 
Wenn RAM benötigt wird, wird das durch Linux organisiert und Speicher von der Instanz des Adapters freigegeben. 
Du musst den Adapter nicht einmL am Tag neustarten.
