### ISSUE TITLE
Error: Influxdb backup

### ISSUE THREAD

**Issue by Zen1717** [simatec/ioBroker.backitup#630]
Hallo,
ich habe das Update des Backitup Adapters durchgeführt. Seitdem bekomme ich immer diese Fehlermeldung, wenn versucht wird die Influxdb zu Backupen.

Adapter Version Backitup 2.3.3
Adapter Version Influxdb 1.9.5
IoBroker Version 5.2.3

[iobroker] Error: Command failed: influxd backup -portable -database inverters -host localhost:8088 "/opt/iobroker/backups/influxDB_2022_02_25-02_40_27_backupiobroker"2022/02/25 02:40:27 Download shard 0 failed dial tcp 127.0.0.1:8088: connect: connection refused. Waiting 2s and retrying (0)...2022/02/25 02:40:29 Download shard 0 failed dial tcp 127.0.0.1:8088: connect: connection refused. Waiting 2s and retrying (1)...2022/02/25 02:40:31 Download shard 0 failed dial tcp 127.0.0.1:8088: connect: connection refused. Waiting 2s and retrying (2)...2022/02/25 02:40:34 Download shard 0 failed dial tcp 127.0.0.1:8088: connect: connection refused. Waiting 2s and retrying (3)...2022/02/25 02:40:36 Download shard 0 failed dial tcp 127.0.0.1:8088: connect: connection refused. Waiting 2s and retrying (4)...2022/02/25 02:40:38 Download shard 0 failed dial tcp 127.0.0.1:8088: connect: connection refused. Waiting 2s and retrying (5)...2022/02/25 02:40:40 Download shard 0 failed dial tcp 127.0.0.1:8088: connect: connection refused. Waiting 3.01s and retrying (6)...2022/02/25 02:40:43 Download shard 0 failed dial tcp 127.0.0.1:8088: connect: connection refused. Waiting 11.441s and retrying (7)...2022/02/25 02:40:54 Download shard 0 failed dial tcp 127.0.0.1:8088: connect: connection refused. Waiting 43.477s and retrying (8)...2022/02/25 02:41:37 Download shard 0 failed dial tcp 127.0.0.1:8088: connect: connection refused. Waiting 2m45.216s and retrying (9)...backup: dial tcp 127.0.0.1:8088: connect: connection refused

Wie kann ich diesen Error beheben?
Danke

**Comment by simatec** [comment]
Zeige bitte mal deine Konfiguration vom Influx Adapter und die von Backitup für Influx

**Comment by Zen1717** [comment]
![backitup config](https://user-images.githubusercontent.com/100407227/155684773-e12099b0-13ad-4cc7-b5e8-a1a55fd16e6d.jpg)
![influxdb config](https://user-images.githubusercontent.com/100407227/155684776-1851f5c8-37c1-4229-ae04-657445ff92a7.jpg)

**Comment by BS-GIFHUB** [comment]
Bei mir auch (influxdb 2):

[DEBUG] [influxDB] - InfluxDB-Backup started ...
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[DEBUG] [influxDB] - 
[ERROR] [influxDB] - Error: Command failed: influx backup --bucket iobroker -t x1QgCzAn4Gbd3k2qeoKBy4BEgVUngQy4Hhn6bXso3Ci3XqZJZ1OWPJZmo8yl5o9RlgTSCdAOSssUlveW38iYEw== "/opt/iobroker/backups/influxDB_2022_02_25-14_40_59_backupiobroker"
Error: API compatibility check failed: Get "http://localhost:8086/health": dial tcp [::1]:8086: connect: connection refused

**Comment by simatec** [comment]
> ![backitup config](https://user-images.githubusercontent.com/100407227/155684773-e12099b0-13ad-4cc7-b5e8-a1a55fd16e6d.jpg)
> ![influxdb config](https://user-images.githubusercontent.com/100407227/155684776-1851f5c8-37c1-4229-ae04-657445ff92a7.jpg)

Installiere mal bitte die aktuelle Beta des InfluxDB Adapters. Muss mal nachfragen, warum die nicht im Stable ist. Sollte sie eigentlich schon.

**Comment by simatec** [comment]
> Bei mir auch (influxdb 2):
> 
> [DEBUG] [influxDB] - InfluxDB-Backup started ... [DEBUG] [influxDB] - Start InfluxDB Backup ... [DEBUG] [influxDB] - InfluxDB Backup tmp directory created [DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory [DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted [DEBUG] [influxDB] - [ERROR] [influxDB] - Error: Command failed: influx backup --bucket iobroker -t x1QgCzAn4Gbd3k2qeoKBy4BEgVUngQy4Hhn6bXsoxxxxxxxxxxxxxxxxxxxxxxxxxx "/opt/iobroker/backups/influxDB_2022_02_25-14_40_59_backupiobroker" Error: API compatibility check failed: Get "http://localhost:8086/health": dial tcp [::1]:8086: connect: connection refused

Eigentlich vermischst du hier Issues, da du nicht den selben Fehler hast. Du nutzt Influx 2, welches auch die Influxdb-cli voraussetzt. 

Da gab es bereits ein Issue siehe unten
https://github.com/simatec/ioBroker.backitup/issues/619#issuecomment-1036419009

**Comment by Zen1717** [comment]
> Installiere mal bitte die aktuelle Beta des InfluxDB Adapters. Muss mal nachfragen, warum die nicht im Stable ist. Sollte sie eigentlich schon.

Das habe ich noch nicht gemacht. Wo finde ich die Beta?

**Comment by simatec** [comment]
Stelle mal in Backitup die Influx Sicherung von Remote auf lokal. 
So wie ich das sehe, hat dein Backup so noch nie funktionieren können.

**Comment by Zen1717** [comment]
> Stelle mal in Backitup die Influx Sicherung von Remote auf lokal. So wie ich das sehe, hat dein Backup so noch nie funktionieren können.

In Backitup steht sie auf lokal 😅 (https://user-images.githubusercontent.com/100407227/155684773-e12099b0-13ad-4cc7-b5e8-a1a55fd16e6d.jpg)

**Comment by simatec** [comment]
Eigentlich sehr unwahrscheinlich, dass du zum Zeitpunkt des Backups auch den Typ Lokal gewählt hattest.
Dann würde die Fehlermeldung nicht den Remothost und Port ausgeben sondern wie folgt aussehen

`[ERROR] [influxDB] - [IGNORED] Error: Command failed: influxd backup -portable -database iobroker "/opt/iobroker/backups/influxDB_2022_02_25-21_02_24_testsys_backupiobroker"
/bin/sh: 1: influxd: not found`

siehe Code ...

https://github.com/simatec/ioBroker.backitup/blob/0179289f1f4c46e9212c3ec4ec31843d0e4f47c9/lib/scripts/12-influxDB.js#L70

Deine Fehlermeldung gibt den Host und den Port mit aus:

`[iobroker] Error: Command failed: influxd backup -portable -database inverters -host localhost:8088 "/opt/iobroker/backups/influxDB_2022_02_25-02_40_27_backupiobroker"2022/02/25`

Stelle mal auf Remote dann wieder auf lokal und speichere deine Einstellungen noch einmal.

Des Weiteren ist meine Empfehlung den Influxdb Adapter mal  mit der aktuellen Beta updaten.

**Comment by BS-GIFHUB** [comment]
Hallo, sorry wenn ich die Issues vermenge, aber ich habe influxdb-cli installiert und influxdb läuft bei mir auf einen anderen host.

**Comment by BS-GIFHUB** [comment]
Ich muss dass etwas detaillierter beschreiben. Ich habe den Adapter auf einem anderen host (MULTI Hosts System laufen) und das Backup wird damit lokal konfiguriert, was nicht stimmt.. Habe jetzt gesehen, dass er sich damit die falsch Konfiguration liest, also localhost statt die IP-Adresse des zweiten hosts.. Trage jetzt mal die IP-Adresse des zweiten Host ein und dann melde ich mich wieder.

**Comment by BS-GIFHUB** [comment]
Funktioniert als Remotesystem. 

Danke.

**Comment by Zen1717** [comment]
> Eigentlich sehr unwahrscheinlich, dass du zum Zeitpunkt des Backups auch den Typ Lokal gewählt hattest. Dann würde die Fehlermeldung nicht den Remothost und Port ausgeben sondern wie folgt aussehen
> 
> `[ERROR] [influxDB] - [IGNORED] Error: Command failed: influxd backup -portable -database iobroker "/opt/iobroker/backups/influxDB_2022_02_25-21_02_24_testsys_backupiobroker" /bin/sh: 1: influxd: not found`
> 
> siehe Code ...
> 
> https://github.com/simatec/ioBroker.backitup/blob/0179289f1f4c46e9212c3ec4ec31843d0e4f47c9/lib/scripts/12-influxDB.js#L70
> 
> Deine Fehlermeldung gibt den Host und den Port mit aus:
> 
> `[iobroker] Error: Command failed: influxd backup -portable -database inverters -host localhost:8088 "/opt/iobroker/backups/influxDB_2022_02_25-02_40_27_backupiobroker"`
> 
> Stelle mal auf Remote dann wieder auf lokal und speichere deine Einstellungen noch einmal.
> 
> Des Weiteren ist meine Empfehlung den Influxdb Adapter mal mit der aktuellen Beta updaten.

Der Influx Adapter ist noch nicht auf der Beta.
Backitup Einstellungen noch einemal eingestellt. 
Siehe Bilder

![backitup Log 27 02](https://user-images.githubusercontent.com/100407227/155878184-e5890d5e-4e63-436c-aa0b-3ffce3ff3cbb.jpg)
![backitup config 27 02](https://user-images.githubusercontent.com/100407227/155878186-cd8d4383-3c60-4453-b8ab-2818a3a1a73e.jpg)
![Log 27 02](https://user-images.githubusercontent.com/100407227/155878187-4bd855a1-5bc7-4bcf-8750-7405b7f0ba6d.jpg)

**Comment by simatec** [comment]
So wie es ausschaut ist deine InfluxDB nicht erreichbar. 

Prüfe doch mal, ob du sie bei einem manuellen Backup über Konsole überhaupt erreichen kannst. Sonst würde ich dir raten, dein komplettes System mal neuzustarten. 

Und nochmal zum Verständnis… Du hast Influx auf dem gleichen host laufen, wie der iobroker und bist sicher auf Version 1.x mit der Influxdb?

**Comment by Zen1717** [comment]
Die InfluxDB konnte ich auch nicht über die Konsole Backupen. Auch mit mehrmaligen neustarten. 
Da ich mein System sowieso auf eine SSD umbauen wollte. Setze ich mein System komplett neu auf. 

Ja mein System lief komplett auf einem Raspberry. Die InfluxDB lief auf der 1.x Version (extra noch einmal ausgeben lassen). Trotzdem Danke. 😄  👍

**Comment by simatec** [comment]
Wenn es auf der Konsole auch nicht geht, ist an der Influx Installation etwas schief. 

Backitup nutzt den Prozess des offiziellen Influx Backups
