### ISSUE TITLE
Syntax error while dumping mySQL database

### ISSUE THREAD

**Issue by Superwuzy** [simatec/ioBroker.backitup#631]
When trying to backup IOBroker, I'm getting the following error when trying to trigger a mysql dump:

> [ERROR] [mysql] - Error: Command failed: mysqldump  -u iobroker -p**** iobroker -h localhost -P 3306 > /opt/iobroker/backups/mysql_2022_02_26-10_28_51_backupiobroker.sql
> /bin/sh: 1: Syntax error: ")" unexpected

The error can be reproduced. MySQL runs without problems. The sql adapter rund without problems.

**Versions:**  
 - Adapter version: 2.3.3
 - JS-Controller version: 4.0.15
 - Node version: 16.4.0
 - Operating system: Linux iobroker 5.15.24-v7l+ #1526 SMP Fri Feb 18 14:57:32 GMT 2022 armv7l GNU/Linux

**Comment by simatec** [comment]
Can you please post your settings of backitup (mysql).

Do you have any special characters in your password?

Has the backup ever worked?
In version 2.3.3 the error handling is now more stringent

**Comment by viper-666** [comment]
I have the same Error, I used a MariaDB on my Synology NAS. 
First as I have a ")" in my password the error was the same as @Superwuzy wrote.
I changed the password but now I get this Error:
`[DEBUG] [mysql] - MySql-Backup started ...
[ERROR] [mysql] - Error: Command failed: mysqldump  -u iobroker -p**** iobroker -h 192.168.178.xxx -P 33xx > /opt/iobroker/backups/mysql_2022_03_13-18_03_30_backupiobroker.sql
/bin/sh: 1: cannot open 4Svj#W2Yv: No such file`
Where "4Svj#W2Yv" is the password of the user iobroker for the MariaDB database.
I think the syntax for the backup is wrong.
If I opened a ssh console on the ioboker raspi and type:
`mysqldump  -u iobroker -p iobroker -h 192.168.178.1xx -P 33xx > /opt/iobroker/backups/mysql_2022_03_1
3-17_19_47_backupiobroker.sql`
It asked for the password and after typing it in the backup runs.

**Comment by simatec** [comment]
Please try to work with a password without special characters.  
Linux commands always have a hard time with this.  

Alternatively, you can also try to write the password in the backup configuration with quotation marks.

**Comment by viper-666** [comment]
Thank's for your hint, but the NAS needs a special character for a database user I now used a "!" and all works.

**Comment by simatec** [comment]
Perfect!!
