### ISSUE TITLE
Multi Redis Support

### ISSUE THREAD

**Issue by EvilEls** [simatec/ioBroker.backitup#637]
Hi, 
I'm using two different Redis instances to store iobroker data.
one for states using rdb
another for objects and files using aof.

Atm the adapter only allows to backup one db.

Could you please add the possibility to add multiple Redis hosts?

Thanks in advance!

**Comment by simatec** [comment]
You can use master/slave backups with multiple instances for this.  

You can find out more about this in the Backitup documentation
