### ISSUE TITLE
Error: historyDB

### ISSUE THREAD

**Issue by Stefan-CH-87** [simatec/ioBroker.backitup#638]
Hallo

Ich habe heute den Backitup Adapter auf die Version: 2.3.3 hochgezogen und hatte dann mit dem History DB Adapter Probleme.
Er übernimmt den Speicherort von der History Datenbank nicht mit und schreibt irgend einen USB Anschluss rein.

`Started iobroker ...
[DEBUG] [iobroker] - host.Iobroker-Visu 11299 states saved

[DEBUG] [iobroker] - host.Iobroker-Visu 12575 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2022_02_27-10_51_23_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [historyDB] - compress from historyDB started ...
[ERROR] [historyDB] - Backitup cannot found source "undefined" for compress!`

Er schreibt den Speicherort: media/usb/history in den Adapter rein.

**Comment by simatec** [comment]
Noch kurz zur Info. Backitup ist was Fehlermeldungen abgeht, ab Version 2.3.x strickter. D.h. der Fehler war bei dir bereits vorher vorhanden nur wurde lief das Backup weiter und die meisten User prüfen ihre Backups nicht

**Comment by Stefan-CH-87** [comment]
Das habe ich dann auf Hinweis von einem User aus dem Forum gemacht und den richtigen Speicherort eingetragen. Ich hatte vorher die Version 2.2.4 darauf und da ist mir das wahrschienlich nie aufgefallen. 
Es hatte anscheinend noch ein anderer User auch das Problem: 
https://forum.iobroker.net/topic/52924/backitup-adapter-erzeugt-fehler-im-historydb/11?_=1645954543026

**Comment by simatec** [comment]
Ja wie gesagt, mit sehr großer Wahrscheinlichkeit sind deine History Backups alle Fehlerhaft, da der Fehler ignoriert wurde. 

Ab Version 2.3.x soll dass den Usern helfen, Fehler in der Config zu beheben, um auch wirklich sichere Backups zu haben

**Comment by Stefan-CH-87** [comment]
Ich habe schon mehrmals ein Backup zurückladen müssen, da es mir was zerschossen hatte, aber habe nie was gemerkt, das bei der History was fehlte oder falsch war. Aber ich bin auch nicht der Profi auf dem.

**Comment by simatec** [comment]
Hast du ein iobroker Backups wiederhergestellt oder ein History?

**Comment by Stefan-CH-87** [comment]
Komplettes Backup. Ist so eingestellt. Vielleicht hab ich das auch was komplett falsches verstanden und die History Daten werden nicht mit genommen oder schon?

![grafik](https://user-images.githubusercontent.com/100514436/155880170-ec3f45f3-a662-4928-9357-5fb804600e5c.png)

**Comment by simatec** [comment]
Wenn du den Restore des iobroker Backups ausführst, dann wird kein History Backup wiederhergestellt. Dafür musst du dann auch ein History Backup wählen. 

Zeige mal die Ausgabe von:

`ls -lah /opt/iobroker/backups`

**Comment by Stefan-CH-87** [comment]
`drwxrwxr-x+ 2 iobroker iobroker  12K Feb 27 11:47 .
drwxrwxrwx+ 6 iobroker iobroker 4.0K Feb 27 10:33 ..
-rw-rw-rw-+ 1 iobroker iobroker  14M Feb 26 14:21 2022_02_26-14_21_51_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker 127M Feb 27 11:12 historyDB_2022_02_27-11_11_29_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker 127M Feb 27 11:46 historyDB_2022_02_27-11_46_15_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  15M Jan 26 11:46 iobroker_2022_01_26-11_46_10_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  16M Feb  4 11:46 iobroker_2022_02_04-11_46_10_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  14M Feb 23 11:46 iobroker_2022_02_23-11_46_10_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  14M Feb 27 10:34 iobroker_2022_02_27-10_34_23_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  14M Feb 27 10:35 iobroker_2022_02_27-10_35_01_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  14M Feb 27 10:51 iobroker_2022_02_27-10_51_23_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  14M Feb 27 11:11 iobroker_2022_02_27-11_11_24_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  14M Feb 27 11:46 iobroker_2022_02_27-11_46_10_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  66K Jan 17 11:46 javascripts_2022_01_17-11_46_16_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  90K Jan 31 11:46 javascripts_2022_01_31-11_46_17_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  90K Feb  1 20:29 javascripts_2022_02_01-20_29_31_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  93K Feb 15 21:14 javascripts_2022_02_15-21_14_49_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  93K Feb 17 11:46 javascripts_2022_02_17-11_46_16_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker 105K Feb 22 11:46 javascripts_2022_02_22-11_46_16_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  95K Feb 27 11:12 javascripts_2022_02_27-11_12_06_backupiobroker.tar.gz
-rw-rw-rw-+ 1 iobroker iobroker  95K Feb 27 11:46 javascripts_2022_02_27-11_46_52_backupiobroker.tar.gz`

**Comment by simatec** [comment]
Ja wie gesagt, das Backup lief in älteren Versionen weiter und wenn man sich dann den Log nicht anschaut und auch nicht schaut, ob alle Backups erstellt wurden, dann hat man dies nicht mitbekommen.

Und genau aus diesem Grund arbeitet Backitup ab Version 2.3.x nun strickter.
