### ISSUE TITLE
No restore indocker on synoligy NAS possible

### ISSUE THREAD

**Issue by BenAhrdt** [simatec/ioBroker.backitup#640]
Its notpossible to restore some backup with the latest version.
I build a fresh docker container and creats abackup.
but if i wantto restore this backup the bachitup adapter brings the following message and restores nothing:
![image](https://user-images.githubusercontent.com/92173565/156064998-932f906d-d6d7-4c63-b486-3970ceed379b.png)

**Comment by simatec** [comment]
Currently the DEV version of the official iobroker docker container will go.  I think the version will be in the latest soon

**Comment by simatec** [comment]
I just saw that latest is probably up to date now.  So please use the latest version of the official Docker container

**Comment by BenAhrdt** [comment]
i use  the latest.
Nothing works. No restore,no shelly....

**Comment by simatec** [comment]
Please test the dev Container

**Comment by BenAhrdt** [comment]
?

**Comment by simatec** [comment]
docker pull buanet/iobroker:dev

At the moment I can't say when the version will be in the latest
