### ISSUE TITLE
Backup of History DB gets insane big

### ISSUE THREAD

**Issue by NewGitHubUser11** [simatec/ioBroker.backitup#649]
|Systemdata| My System|
|--|--|
|Hardwaresystem:| Proxmox Debian Celeron|
|Arbeitsspeicher:| 2GB |
|Festplattenart:| 16GB VM |
|Betriebssystem:| Debian 10 Buster |
|Node-Version:| 4.0.18 |
|Nodejs-Version:| 14.19.0 |
|NPM-Version:| 6.14.16 |
|Installationsart:| Skript |

English Version Below

Hallo,

Ich habe schon eine weile meinen ioBroker in einer Proxmox VM Laufen. 

Letzte Woche habe ich gesehen, das der Backitup Adapter einen Fehler meldet, das der Pfad für die HistoryDB nicht angegeben sei. Daraufhin habe ich meinen Pfad dort per Klick auf "Ermitteln der Konfiguration" im Backitup Adapter eingefügt: /opt/iobroker/

Daraufhin ist der Fehler verschwunden, und das Backup läuft sauber durch.
Jetzt eine Woche später habe ich gemerkt, das mein NAS auf dem das Backup täglich per NFS gespeichert wird in die Speicherbegrenzung geht. Die Backup Dateien wurden mit jedem Tag größer, 10gb ~50gb am letzten Tag 750gb!!
Und das bei meiner Installation auf einer 16GB VM Disk. Ich protokolliere 52 Werte und habe pro Tag ca. 350kb an Daten im Täglichen Backup Verzeichnis auf der VM.

Hat jemand eine Idee was hier passiert ist?

#######################

Hi

I'm running my ioBroker for a year in a Proxmox VM

last week I saw that the Backitup Adapter sends an Error, that the path of HistoryDB Backup is not set.
So I added my Path by clicking on recognise my configuration in the Backitup Adapter (/opt/iobroker/)

After that the error dissapeared and the Backup went fine.

A week later i noticed my NAS where the Backups were daily saved with NFS runs into limitation. The Backup data of HistoryDB were getting bigger and bigger from day to day. Starting with I think 10gb finishing with about 750gb on the last day the Space was suffiscient. But I only have a 16gb Drive in my VM and my 52 Values I am logging just use about 350kb per day when I look into the History folders on my Debian iobroker System.

Anybody with an idear about this ?

Thanks in advanced

**Comment by simatec** [comment]
Wenn deine History Daten in /opt/iobroker liegen, ist das kein Wunder. Damit sicherst du den kompletten iobroker Pfad. Lege deine History Daten an einen anderen Pfad. 

Bespiel: /home/iobroker/history

**Comment by NewGitHubUser11** [comment]
Okay, habe ich geändert, mal schauen ob's jetzt kompakt bleibt.
Dann ist oder war zur zeit meiner Installation der Standardpfad für den History Adapter ungünstig gewählt.
