### ISSUE TITLE
Rechteproblem mit mount

### ISSUE THREAD

**Issue by truegreyhound** [simatec/ioBroker.backitup#65]
[Mount of CIFS fails: Permission denied](https://github.com/simatec/ioBroker.backitup/issues/61) - das ist zumindest bei mir keine unkorrekte Installation, sondern mein ioBroker läuft nicht unter root und damit bekomme ich auch diesen Fehler, habe mir bisher damit beholfen dass in den jeweiligen Skripten nach jeden Update zu ändern, ist aber mittlerweile etwas mühselig.
Es wäre also schön. wenn in den Skripten bei mount und unmount ein sudo fest drin stehen würde, sollte unter root auch funktionieren.

**Comment by simatec** [comment]
Auch hier mal bitte deine Anpassungen posten. Dann prüfen wir das.

**Comment by truegreyhound** [comment]
in "01-mount.js" vor allen mount's/ umount's (aktuell die Zeilen 18, 33, 35 und 55) "sudo " einfügen, ist bei mir bei NFS nicht notwendig, aber wenn schon mal dabei ...

dito. in "98-umount.js" in der Zeile 12 vor dem umount

**Comment by simatec** [comment]
Werden wir berücksichtigen

**Comment by simatec** [comment]
Kommt in der nächsten Version ...
