### ISSUE TITLE
S3-compatibile object storage as backup destination

### ISSUE THREAD

**Issue by tnowak** [simatec/ioBroker.backitup#651]
This is a feature request.
It would be great to have S3-compatibile storage as one of backup destinations.
Backblaze B2 storage is cheap as dirt and for on-prem there are great solutions such as MinIO.
Cloud object storage is great for backups, easy to setup, secure and very reliable.

**Comment by simatec** [comment]
Due to a lack of testing possibilities, I don't see a reasonable integration possibility at the moment.

If there is something new, I will deal with the topic again.

Until then I close this issue for now
