### ISSUE TITLE
Adjust Detail-Backup from jarvis

### ISSUE THREAD

**Issue by mcuiobroker** [simatec/ioBroker.backitup#655]
Now in the detail-Backup from jarvis there are only the files from the internal backup from jarvis:

`opt/iobroker/iobroker-data/jarvis`

In this files are not all of the data from jarvis, only when they were changed.

The important DPs in jarvis are 9:
X = Instance
jarvis.X.settings
jarvis.X.css
jarvis.X.devices
jarvis.X.layout
jarvis.X.notifications
jarvis.X.widgets
jarvis.X.scripts
jarvis.X.theme
jarvis.X.info.pro

![image](https://user-images.githubusercontent.com/84818934/160470603-222255c9-b3a7-49e6-ab7c-4d71e14d8fbf.png)

So it is useful to have the DPs in the Detail-Backup from jarvis.
Thank you.

**Comment by simatec** [comment]
Comes in v2.6.x
