### ISSUE TITLE
cifs version konfigurierbar

### ISSUE THREAD

**Issue by truegreyhound** [simatec/ioBroker.backitup#66]
Mein NAS unterstützt aus bekannten Gründen die Version 1 nicht mehr, d. h., nach jeden Update muss ich ins mount-Skript und die Version anpassen, wäre schön, wenn das auch ein Konfigurationsparameter wäre.

**Comment by simatec** [comment]
Poste hier mal die Anpassungen, die du machen musst

**Comment by truegreyhound** [comment]
in "01-mount.js" vor allen mount's/ umount's (aktuell die Zeilen 18, 33, 35 und 55) "sudo " einfügen, ist bei mir bei NFS nicht notwendig, aber wenn schon mal dabei ...

dito. in "98-umount.js" in der Zeile 12 vor dem umount

**Comment by truegreyhound** [comment]
uups, das war das falsche issue, gilt für #65 

hier habe ich in der "01-mount.js" in der Zeile 33 "vers=1.0" in "vers=2.0" geändert bzw. in Zeile 35 an der selben Position wie in Zeile 33 hinzugefügt.

**Comment by simatec** [comment]
Schauen wir uns mal an ...

**Comment by simatec** [comment]
kommt in der nächsten Version ...
