### ISSUE TITLE
Make it possible to download backup via browser (Download button)

### ISSUE THREAD

**Issue by GermanBluefox** [simatec/ioBroker.backitup#664]
I as a user want to store saved backup on my PC via browser. For that I need a button for download.

**Comment by simatec** [comment]
I'll see if you can get it integrated. This is where it gets a bit complicated due to the different storage media that Backitup offers.

But I try to integrate it

**Comment by simatec** [comment]
Included from version 2.4.4.
Thanks @GermanBluefox  for your help
