### ISSUE TITLE
[ERROR] [historyDB] - Backitup cannot found source "undefined" for compress!

### ISSUE THREAD

**Issue by balferreira** [simatec/ioBroker.backitup#665]
**Describe the bug**  
Error while doing a backup

**To Reproduce**  
1. Go to Backup
2. Click on 'IOBROKER START BACKUP'

**Screenshots & Logfiles**  
![BugIoBrokerBackup](https://user-images.githubusercontent.com/23437809/160931937-a9dff817-4366-4a79-bacd-b230e5ed57d4.png)

`Started iobroker ...
[DEBUG] [iobroker] - host.ioiBroker 5172 states saved

[DEBUG] [iobroker] - host.ioiBroker 6198 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2022_03_30-21_10_48_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [historyDB] - compress from historyDB started ...
[ERROR] [historyDB] - Backitup cannot found source "undefined" for compress!`

**Versions:**  
 - Adapter version: 2.3.3
 - JS-Controller version: 4.0.21 
 - Node version: v14.19.1 
 - Operating system: Ubuntu 21.10 (GNU/Linux 5.13.19-2-pve x86_64)

**Comment by simatec** [comment]
Please Update on last Beta Version

**Comment by balferreira** [comment]
Can you tell me how to do that?

**Comment by simatec** [comment]
Change the Repo fom stable to Beta, install Backitup an then repo from beta to stable

**Comment by balferreira** [comment]
Sorry, but I'm not super skilled on ioBroker yet!

I'm trying to change here, is this the right place?

![Backitup_to_Beta](https://user-images.githubusercontent.com/23437809/161053305-becd3d74-8c5d-487e-9efe-9986920ada3a.png)

Otherwise could you please provide me a concrete way to change that?

**Comment by simatec** [comment]
Then wait a few more days. In the next few days the beta version will be stable

**Comment by balferreira** [comment]
I managed to upgrade to 2.4.3, but I'm getting the exactly same error.

![BackitUP_2_4_3](https://user-images.githubusercontent.com/23437809/161059017-f4de5f9b-78c7-404b-81b0-b0b266479f1c.png)

**Comment by balferreira** [comment]
now it works! Thanks
