### ISSUE TITLE
Backup path not found

### ISSUE THREAD

**Issue by kaybau** [simatec/ioBroker.backitup#668]
**Describe the bug**  
when starting Backitup, after it created temporarly data and try to copy it to local filesystem is shows the error:
"[ERROR] [cifs] - [IGNORED] Path "/media/pi/PI_BKP/Backitup" not found"

I copied and pasted the path on OS- it is there . it is 777 and owned by iobroker.
This happens in version 2.2.2 as well as in 2.3.3

**To Reproduce**  
NAS/copy is set to option "copy". (USB-)Path is created as "/media/pi/PI_BKP/Backitup"
Starting Backitup

**Expected behavior**  
copying backup data to configred path

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 2.2.2 and 2.3.3
 - JS-Controller version: 3.3.22
 - Node version: v12.22.9
 - Operating system: Debian

**Additional context**  
filesystem is a USB device which is successfully used by raspibackup and accessible by user iobroker 
:/media/pi/PI_BKP $ ls -l
insgesamt 24
drwxrwxrwx 2 iobroker iobroker  4096 Mär 31 14:12 Backitup

**Comment by simatec** [comment]
Please post the full debug log from the backup process

**Comment by kaybau** [comment]
Hello,
debug log has unfortunatley no valueable content:

<html><body>


backitup.0 | 2022-05-13 08:55:46.174 | error | [iobroker] Path "/media/pi/PI_BKP/Backitup" not found
-- | -- | -- | --
backitup.0 | 2022-05-13 08:55:46.173 | debug | [iobroker/cifs] Path "/media/pi/PI_BKP/Backitup" not found
backitup.0 | 2022-05-13 08:55:44.970 | debug | [iobroker/historyDB] done
backitup.0 | 2022-05-13 08:55:44.969 | debug | [iobroker/historyDB] Backup created: /opt/iobroker/backups/historyDB_2022_05_13-08_55_43_backupiobroker.tar.gz
backitup.0 | 2022-05-13 08:55:43.180 | debug | [iobroker/historyDB] compress from historyDB started ...
backitup.0 | 2022-05-13 08:55:42.578 | debug | [iobroker/influxDB] done
backitup.0 | 2022-05-13 08:55:42.572 | debug | [iobroker/influxDB] InfluxDB-Backup for is finish
backitup.0 | 2022-05-13 08:55:42.571 | debug | [iobroker/influxDB] InfluxDB tmp directory was successfully deleted
backitup.0 | 2022-05-13 08:55:42.567 | debug | [iobroker/influxDB] Try deleting the InfluxDB tmp directory
backitup.0 | 2022-05-13 08:55:42.566 | debug | [iobroker/influxDB] Backup created: /opt/iobroker/backups/influxDB_2022_05_13-08_55_41_backupiobroker.tar.gz
backitup.0 | 2022-05-13 08:55:41.680 | debug | [iobroker/influxDB] InfluxDB Backup tmp directory created
backitup.0 | 2022-05-13 08:55:41.679 | debug | [iobroker/influxDB] Start InfluxDB Backup ...
backitup.0 | 2022-05-13 08:55:41.679 | debug | [iobroker/influxDB] InfluxDB-Backup started ...
backitup.0 | 2022-05-13 08:55:41.527 | debug | [iobroker/iobroker] done
backitup.0 | 2022-05-13 08:55:40.431 | debug | [iobroker/iobroker] Backup created: /opt/iobroker/backups/iobroker_2022_05_13-08_54_09_backupiobroker.tar.gz
backitup.0 | 2022-05-13 08:54:31.345 | debug | [iobroker/iobroker] host.raspberrypi 30892 objects saved
backitup.0 | 2022-05-13 08:54:31.157 | debug | [iobroker/iobroker] host.raspberrypi 30164 states saved
backitup.0 | 2022-05-13 08:54:09.642 | debug | Backup has started ...
backitup.0 | 2022-05-13 08:54:06.658 | debug | sendTo "getSystemInfo" to system.adapter.admin.0 from system.adapter.backitup.0: linux


</body>
</html>

**Comment by simatec** [comment]
In the next version I have a little more debug log for "used copy path" in it

**Comment by kaybau** [comment]
Ok, will wait for next version to test it

**Comment by kaybau** [comment]
Hi,

same output:
"DEBUG] [iobroker] - host.raspberrypi 8835 states saved

[DEBUG] [iobroker] - host.raspberrypi 9629 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2022_06_21-13_55_13_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [influxDB] - InfluxDB-Backup started ...
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Backup created: /opt/iobroker/backups/influxDB_2022_06_21-13_55_37_backupiobroker.tar.gz
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[DEBUG] [influxDB] - InfluxDB-Backup for is finish
[DEBUG] [influxDB] - done
[DEBUG] [historyDB] - compress from historyDB started ...
[DEBUG] [historyDB] - Backup created: /opt/iobroker/backups/historyDB_2022_06_21-13_55_39_backupiobroker.tar.gz
[DEBUG] [historyDB] - done
[DEBUG] [cifs] - used copy path: /media/pi/PI_BKP/Backitup
[ERROR] [cifs] - Path "/media/pi/PI_BKP/Backitup" not found"

But the FS exits and is writeable:
pi@raspberrypi:/media/pi $ cd /media/pi/PI_BKP/Backitup
pi@raspberrypi:/media/pi/PI_BKP/Backitup $ df .
Dateisystem    1K-Blöcke  Benutzt Verfügbar Verw% Eingehängt auf
/dev/sda2       61220884 22362348  35718952   39% /media/pi/PI_BKP
pi@raspberrypi:/media/pi/PI_BKP/Backitup $ cd ..
pi@raspberrypi:/media/pi/PI_BKP $ ls -l
insgesamt 24
drwxrwxrwx  2 iobroker iobroker  4096 Mär 31 14:12 Backitup
drwx------  2 root     root     16384 Mär 30 15:29 lost+found
drwxr-xr-x 10 root     root      4096 Mai  9 03:13 raspbe

**Comment by simatec** [comment]
as can be seen with ls, the rights are not correct.
The user iobroker has no write permissions. 

You can simply test it in the console by creating a file with the following command.

`sudo -u iobroker echo  "test Backitup" >  /media/pi/PI_BKP/Backitup/test.txt`

**Comment by kaybau** [comment]
Hi,
the directory is owned by iobroker and has 777. Also the test file with your command is writeable.

pi@raspberrypi:/media/pi/PI_BKP $ ls -l
insgesamt 24
drwxrwxrwx  2 iobroker iobroker  4096 Jun 24 07:54 Backitup
drwx------  2 root     root     16384 Mär 30 15:29 lost+found
drwxr-xr-x 10 root     root      4096 Jun 24 03:14 raspberrypi
pi@raspberrypi:/media/pi/PI_BKP $ sudo -u iobroker echo "test Backitup" > /media/pi/PI_BKP/Backitup/test.txt
pi@raspberrypi:/media/pi/PI_BKP $ cd Backitup/
pi@raspberrypi:/media/pi/PI_BKP/Backitup $ ls -l
insgesamt 4
-rw-r--r-- 1 pi pi 14 Jun 24 07:57 test.txt
pi@raspberrypi:/media/pi/PI_BKP/Backitup $


Thanks 
Kay

**Comment by simatec** [comment]
There may be problems with the special characters in the path.
You can try putting the path in quotes in the config of backup.
Basically, I would try the path without special characters.

E.g: /media/pi/pibkp/Backitup

**Comment by kaybau** [comment]
Hi, I created and defined a new path without special characters, but same result:

DEBUG] [historyDB] - Backup created: /opt/iobroker/backups/historyDB_2022_06_30-14_14_12_backupiobroker.tar.gz
[DEBUG] [historyDB] - done
[DEBUG] [cifs] - used copy path: /media/pi/PIBKP/Backitup
[ERROR] [cifs] - Path "/media/pi/PIBKP/Backitup" not found

**Comment by simatec** [comment]
Mich verwundert das sehr ... gehe immernoch von einem Rechteproblem aus.
Erstelle doch mal einen Ordner mit dem Verzeichnis /home/iobroker

`sudo -u iobroker mkdir -p /home/iobroker/testDir`

Den Pfad `/home/iobroker/testDir` dann mal bitte in Backitup angeben und testen

**Comment by kaybau** [comment]
with a local path, instead of SD card it is working. I will test by my own to figure it out. Thanks for your support,
