### ISSUE TITLE
Backup Zeitdauer, offline zu lange

### ISSUE THREAD

**Issue by truegreyhound** [simatec/ioBroker.backitup#67]
Ein Komplett-Backup mit ioBroker stop dauert bei mir z. Z. ca 18 min. und wird direkt auf ein NAS gespeichert (ca. 1,5 GB).
Das sind mind. 19 Minuten, in denen der ioBroker nicht läuft und das hat bei mir schon zu einigen (nicht Lebenswichtigen aber unangenehmen) Störungen geführt.
Nach meinem Verständnis wird ioBroker "nur" beendet, um die aktuellen STATES zu sichern. Der Zeitpunkt der Sicherung der STATES sollte im Normalfall keinen zeitlichen Zusammenhang mit anderen Dateien (ausgenommen das Log) haben. D. h., wenn ioBroker den betroffenen Adaptern (ObjectDB/Redis, Log, u. a.) signalisieren würde "jetzt speichern" (STATES z. B. in eine spezielle Backupdatei/Verzeichnis und das Log mit einer neuen Datei starten), dann wäre eine Art Snapshot-Sicherung möglich und ioBroker könnte weiterlaufen.
Alternativ und weniger aufwändig wäre ein kurzer Stop des ioBroker, um STATES und Log in ein Backupverzeichnis zu kopieren und dann den ioBroker wieder zu starten.
Wenn ihr andere Lösungen seht, wäre ich auch dafür dankbar.

**Comment by simatec** [comment]
Das stoppen ist Ansichtssache. 
Ich nutze Redis und stoppe nix bei einem Backup. 
Auch ohne Redis bin ich der Meinung, ist ein Stop nicht notwendig.
