### ISSUE TITLE
Supporting backup of SQLLite database

### ISSUE THREAD

**Issue by HeinrichBerger** [simatec/ioBroker.backitup#676]
**Is your feature request related to a problem? Please describe.**
We are using ioBroker and with this, we are logging data by SQL protocol adapater which use e.g. SQLLite

**Describe the solution you'd like**
As far as we know the adapter doesn't support the backup of this sqllite databases generated by sql protocol adapter

**Describe alternatives you've considered**
We don't see any alternatives within the backup adapter

**Additional context**
No additonal comments

**Comment by simatec** [comment]
Comes in v2.6.x
