### ISSUE TITLE
Option to select only to restore data without installing Instance of adapters

### ISSUE THREAD

**Issue by mcuiobroker** [simatec/ioBroker.backitup#677]
For a `Test`-System I wish only to have the Data from the `Prod`-System.
So it would be possible to test a variant of Adapter-Versions with the Prod-Data.
So it could be nice to have an Option for "Only Data" - Restore from Complete-ioBroker-Backup.
Thank you.

**Comment by simatec** [comment]
This is not possible... Backitup relies on the js controller and uses backup/restore from the controller.  You could try an issue there.  but don't think that this really makes sense in the end

**Comment by simatec** [comment]
This is not possible... Backitup relies on the js controller and uses backup/restore from the controller.  You could try an issue there.  I don't think this makes any sense in the end though

**Comment by mcuiobroker** [comment]
Ok. Thank you.
