### ISSUE TITLE
Notification not working properly

### ISSUE THREAD

**Issue by SKB-CGN** [simatec/ioBroker.backitup#679]
Hi,
i noticed, that the Notification on Error might not be working as expected.

I changed the IP of my NAS due some clean-up and therefore BackItUp was not able to connect to the NAS anymore.
Normally, it should send an email to the mail.0. adapter, but this didnt happen.

As you can see the following test:
![2022-04-26 11_50_31-logs - ioBroker — Mozilla Firefox](https://user-images.githubusercontent.com/58603329/165273597-9177841c-af3e-48e3-ae1b-1ef68e0fe402.png)
![2022-04-26 11_49_52-backitup-0 - ioBroker — Mozilla Firefox](https://user-images.githubusercontent.com/58603329/165273604-36a3f2e4-b198-41cf-b4e3-9bcc9bb55a92.png)

**Comment by simatec** [comment]
Please post the full debug log from the backup process
