### ISSUE TITLE
Backup mittels SFTP

### ISSUE THREAD

**Issue by ipod86** [simatec/ioBroker.backitup#680]
Hallo,

ist es möglich zusätzliche zu ftp noch sftp zu integrieren?

Bei einer Sicherung auf einen externen Webserver finde ich persönlich eine unverschlüsselte Verbindung nicht so dolle.

**Comment by CarminKern** [comment]
Hallo mir geht es genauso, 
ich würde gerne mein Backups auf meinen Cluster speichern, so wie ich es schon mit vielen anderen Backups gemacht habe.

Eine FTP Übertragung finde ich äußerst kritisch, da hierbei unverschlüsselt übertragen wird. Deswegen sollte unbedingt eine SFT Verbindung im Code implementiert werden.

**Comment by simatec** [comment]
TLS for ftp coming in v2.6.x

**Comment by stklcode** [comment]
FTP über TLS ([Wiki](https://de.wikipedia.org/wiki/FTP_%C3%BCber_SSL)) ist _nicht_ SFTP ([Wiki](https://de.wikipedia.org/wiki/SSH_File_Transfer_Protocol)). Das eine ist FTP mit vorgelagerter Transportverschlüsselung, das andere ein unabhängiges, SSH-basiertes Transportprotokoll.

Wenn also tatsächlich nur ein SFTP-Server zur Verfügung steht, kommt man damit nicht weiter.

Geht es nur um die Transportverschlüsselung und hat man einen FTP-Server, der explizites TLS unterstützt (was auf die meisten zutrifft), ist das natürlich eine Alternative.

**Comment by simatec** [comment]
TLS und SFTP sind unterschiedliche Protokolle. 
TLS Unterstützung ist nun integriert. 
SFTP wird noch geprüft
