### ISSUE TITLE
Zigbee-Restore bricht mit Fehler ab

### ISSUE THREAD

**Issue by guergen1** [simatec/ioBroker.backitup#691]
Zigbee meldet Fehler beim Restore:
`Started restore ...
[DEBUG] [zigbee] - Start Zigbee Restore ...
[DEBUG] [zigbee] - Filename for Restore: /opt/iobroker/backups/zigbee.0_2022_05_05-00_22_55_slave-1_backupiobroker.tar.gz
[DEBUG] [zigbee] - zigbee tmp directory created: /opt/iobroker/backups/zigbee_0
[ERROR] [zigbee] - Zigbee Restore not completed
[ERROR] [zigbee] - Error: EPERM: operation not permitted, utime '/opt/iobroker/backups/zigbee_0/'
[EXIT] 0`

**Versions:**  
 - Adapter version: 2.4.6
 - JS-Controller version: 4.0.23
 - Node version: <node-version> 14.19.1
 - Operating system: Debian Bullseye

Auf meinem IO-Broker Master und auf dem Slave laufen die selben Versionen.
Das Backup-Verzeichnis wird mitels CIFS-root gemountet. 
Das Verzeichnis zigbee_0 wird auf dem NAS auch angelegtBackup´s werden erstellt, jedoch das restore wird mit dem o.g. Fehler im Fenster beendet.
Zusätzlich erscheint noch folgendesFenster: 
`Error:

{"errno":-1,"code":"EPERM","syscall":"utime","path":"/opt/iobroker/backups/zigbee_0/"}`

**Comment by simatec** [comment]
Du hast da anscheinend Berechtigungsprobleme. 
Backitup kann in den temporären Ordner nicht schreiben

**Comment by guergen1** [comment]
Das Backup findet doch statt, mit der Einstellung sudo. Warum dann nicht das restore? Das normale restore funktioniert ja

**Comment by simatec** [comment]
Da bringst du jetzt sicher etwas durcheinander. 
zeige mal den Inhalt deines kompletten Pfads mit ls

**Comment by guergen1** [comment]
Der temporäre Ordner wird auf dem NAS im backups-Verzeichnis erstellt, das "echte" backups-Verzeichnis ist leer.

Welche Inhalt möchtest du? Das NAS wird ja nur temporär gemountet!

**Comment by simatec** [comment]
Ich benötige die Rechte von deinem NAS Pfad und den dort erstellten temporären Ordner

**Comment by simatec** [comment]
Was hast du für ein NAS und wie sehen die Einstellungen für das NAS auf beiden Seiten aus?

**Comment by guergen1** [comment]
Es ist ein Synology-Nas.
Hier die Eigenschaft des temporären Ordners auf dem NAS:
![grafik](https://user-images.githubusercontent.com/34395245/167243998-919afbcc-291b-4c89-b877-d2feea69f461.png)
Und hier die Einstellung vom Adapter:
![grafik](https://user-images.githubusercontent.com/34395245/167244047-77776289-98f4-450f-9004-0248130798fa.png)

**Comment by guergen1** [comment]
Hier die Rechte des VErzeichnisses, während ich ein Backup mache: 
![grafik](https://user-images.githubusercontent.com/34395245/167244221-1956f228-2687-4bcc-b945-9e2135911c86.png)

**Comment by simatec** [comment]
Die Berechtigung wäre mir wichtig. 
SMB Version ist mit 2.0 auch nicht so optimal. 

Was sind das da noch alles für Ordner? Die sind im Backup Verzeichnis nicht so optimal. 

Warum nutzt du nicht NFS? Ist bei deiner Konstellation sicher die bessere Wahl

**Comment by guergen1** [comment]
SMB 2.0 ist nicht optimal, aber ich habe ab und zu Rechner hier, die kein SMB3 können. Damit ich nicht mische, habe ich 2.0 eingerichtet.
Die Dateien und VBerzeichnisse sind jetzt woanders, aber das hat nichts damit zu tun.
NFS hatte ich mal Probleme mit, daher eine CIFS-Einbindung.
Wie heisst das immer: Never change a running system ;-)

Hier die Berechtigung für das Backup-Verzeichnis:
![grafik](https://user-images.githubusercontent.com/34395245/167254600-49ff51ad-4620-4ca7-be63-1c9fc24f5419.png)

**Comment by simatec** [comment]
Ich benötige die Berechtigungen auf deinem NAS. Da wird doch alles geschrieben und die Berechtigungen des temporären Ordners „zigbee_0“

**Comment by guergen1** [comment]
Die Berechtigung des temporären Ordners zigbee_0 sieht genauso aus wie die des backups-Ordners.
Auf dem NAS 👍 
![grafik](https://user-images.githubusercontent.com/34395245/167261586-17c9009a-e4bb-4280-8643-40af30facab3.png)

**Comment by simatec** [comment]
Dann prüfe mal deinen User „backup“
Darf der auch Unterordner erstellen und darin schreiben? 

Wie gesagt, Backitup ist nicht für die Rechte zuständig. Das musst du als User managen

**Comment by guergen1** [comment]
Der User Backup erstellt das Verzeichnis, schreiben kann er darin auch

**Comment by simatec** [comment]
Das mag dein, aber hat er auch Berechtigungen in Unterordner zu schreiben. 
Frag doch einfach mal im Forum bzw. nutze da mal die Suchfunktion. Da gibt es unzählige Beiträge zu deinem NAS in Kombi mit Backitup. 

Backitup macht einen ganz normalen mount. 
Mein Vorschlag… wenn du Linux nutzt und dein NAS NFS unterstützt, sollte es die erste Wahl sein. 

CIFS oder früher Samba ist da eher in Richtung Windows sinnvoll. 

Schaue mal im Forum zu den richtigen Einstellungen.

**Comment by simatec** [comment]
Teste mal, ob die Version 2.4.7 hier läuft ... Ich habe mal versucht, dass die Rechte hingebogen werden. Ist natürlich nur möglich, wenn die Rechte auf deinem NAS auch korrekt sind.

**Comment by guergen1** [comment]
Fehlermeldung ist noch die selbe...

**Comment by simatec** [comment]
Es sollte eigentlich so aussehen

`xxxxx@iobroker-test:~$ ls -lah /opt/iobroker/backups
total 44M
drwxrwxrw-  2 root     users    4.0K May 18 21:14 .
drwxrwxr-x+ 6 iobroker iobroker 4.0K May 18 09:00 ..
-rw-rw-rw-  1 iobroker iobroker 8.8K May 16 15:53 grafana_2022_05_16-15_53_07_testsys_backupiobroker.tar.gz
-rw-rw-rw-  1 iobroker iobroker 8.8K May 16 23:36 grafana_2022_05_16-23_36_48_testsys_backupiobroker.tar.gz
-rw-rw-rw-  1 iobroker iobroker 8.8K May 17 23:36 grafana_2022_05_17-23_36_48_testsys_backupiobroker.tar.gz
-rw-rw-rw-  1 iobroker iobroker 176K May 16 15:53 influxDB_2022_05_16-15_53_01_testsys_backupiobroker.tar.gz
-rw-rw-rw-  1 iobroker iobroker 175K May 16 23:36 influxDB_2022_05_16-23_36_42_testsys_backupiobroker.tar.gz
-rw-rw-rw-  1 iobroker iobroker 178K May 17 23:36 influxDB_2022_05_17-23_36_42_testsys_backupiobroker.tar.gz
-rw-rw-rw-  1 iobroker iobroker  15M May 16 15:52 iobroker_2022_05_16-15_52_53_testsys_backupiobroker.tar.gz
-rw-rw-rw-  1 iobroker iobroker  15M May 16 23:36 iobroker_2022_05_16-23_36_20_testsys_backupiobroker.tar.gz
-rw-rw-rw-  1 iobroker iobroker  15M May 17 23:36 iobroker_2022_05_17-23_36_20_testsys_backupiobroker.tar.gz
-rw-rw-rw-  1 iobroker iobroker  11K May 16 15:53 javascripts_2022_05_16-15_53_13_testsys_backupiobroker.tar.gz
-rw-rw-rw-  1 iobroker iobroker  11K May 16 23:36 javascripts_2022_05_16-23_36_55_testsys_backupiobroker.tar.gz
-rw-rw-rw-  1 iobroker iobroker  11K May 17 23:36 javascripts_2022_05_17-23_36_54_testsys_backupiobroker.tar.gz
xxxxx@iobroker-test:~$`

Lösche erstmal den Ordner zigbee_0 und führe mal einen iob fix aus
