### ISSUE TITLE
JavaScript restore Funktioniert nicht

### ISSUE THREAD

**Issue by DerDoubleD** [simatec/ioBroker.backitup#692]
**Describe the bug**  
Ich hab in einem Blockl aus versehen einiges gelöscht und wollte es es deshalb wiederherstellen.
Da ich täglich Backups mache, dachte ich das es kein Problem ist.
Die Wiederherstellung läuft auch scheinbar problemlos durch, nur wird das Blockly nicht widerhergestellt.
Siehe Log unten...

**To Reproduce**  
1. Backup auswählen
2. Sicherung abrufen
3. javascript auswählen
4. Datum von gestern auswählen
5. Auf Backupdatei wiederherstellen klicken

**Screenshots & Logfiles**  
Started restore ...
[DEBUG] [javascripts] - Start Javascript Restore ...
[DEBUG] [javascripts] - Created javascript_tmp directory: "/opt/iobroker/backups/tmpScripts"
[DEBUG] [javascripts] - decompress started ...
[DEBUG] [javascripts] - javascript.0 is stopped
[DEBUG] [javascripts] - enabled Instances: javascript.0
[DEBUG] [javascripts] - Restore Script: Octoprint
[DEBUG] [javascripts] - Restore Script: Fenster_Offen
[DEBUG] [javascripts] - Restore Script: Gefrierschranküberwachung
[DEBUG] [javascripts] - Restore Script: Aktueller_Verbrauch
[DEBUG] [javascripts] - Restore Script: Benachrichtigung_Fehler
[DEBUG] [javascripts] - Restore Script: Benachrichtigung_Wartung
[DEBUG] [javascripts] - Restore Script: Restkapazitaet
[DEBUG] [javascripts] - Restore Script: Verbrauch_aus_Restkapa_berechnen
[DEBUG] [javascripts] - Restore Script: Kühlschranküberwachung_Technik
[DEBUG] [javascripts] - Restore Script: Sonnenbatterie_Berechnungen_Aktuell
[DEBUG] [javascripts] - Restore Script: Sonnenbatterie_Berechnungen_Tag
[DEBUG] [javascripts] - Restore Script: Sonnenbatterie_Status
[DEBUG] [javascripts] - Restore Script: Dimplex_WP_-_Berechnungen
[DEBUG] [javascripts] - Restore Script: Dimplex_WP_-_Meldungen
[DEBUG] [javascripts] - Restore Script: Dimplex_WP_-_Raumwerte
[DEBUG] [javascripts] - Restore Script: Dimplex_WP_Meldungen_lesen
[DEBUG] [javascripts] - Restore Script: Stromzähler_Wärmepumpe
[DEBUG] [javascripts] - Restore Script: Wasserzaehler
[DEBUG] [javascripts] - Restore Script: Wasserzaehler_Foto
[DEBUG] [javascripts] - Restore Script: Satbox_mit_TV_ausschalten
[DEBUG] [javascripts] - Restore Script: Tablet_laden_schalten
[DEBUG] [javascripts] - Restore Script: RPi_-_Warungen_senden
[DEBUG] [javascripts] - Restore Script: InfluxDB_Groesse
[DEBUG] [javascripts] - Restore Script: SpeedTest
[DEBUG] [javascripts] - Restore Script: 1_HowTo
[DEBUG] [javascripts] - Restore Script: Auf_Dashboard_zurückschalten
[DEBUG] [javascripts] - Restore Script: 1_Vorlage_HTML_Tabelle
[DEBUG] [javascripts] - Restore Script: 1_Vorlage_HTML_Tabelle_Erstellen
[DEBUG] [javascripts] - Restore Script: Fensterkontakte_HTML_Tabelle
[DEBUG] [javascripts] - Restore Script: HM_HTML_Tabelle
[DEBUG] [javascripts] - Restore Script: Rollo_HTML_Tabelle
[DEBUG] [javascripts] - Restore Script: Shelly_HTML_Tabelle
[DEBUG] [javascripts] - Restore Script: Tasmota_HTML_Tabelle
[DEBUG] [javascripts] - Restore Script: Temperatur_HTML_Tabelle
[DEBUG] [javascripts] - Restore Script: BatterieTabelle
[DEBUG] [javascripts] - Restore Script: Tabelle_mit_2_Werten
[DEBUG] [javascripts] - Restore Script: Tabelle_mit_3_Werten
[DEBUG] [javascripts] - Restore Script: Tabelle_mit_4_Werten
[DEBUG] [javascripts] - Restore Script: Tabelle_mit_5_Werten
[DEBUG] [javascripts] - Restore Script: Anrufe
[DEBUG] [javascripts] - Restore Script: Anwesend
[DEBUG] [javascripts] - Restore Script: Geraetestatus_senden
[DEBUG] [javascripts] - Restore Script: Klingel
[DEBUG] [javascripts] - Restore Script: AnnalenaFlaeschchen_Senden
[DEBUG] [javascripts] - Restore Script: Anwesenheit_Senden
[DEBUG] [javascripts] - Restore Script: Corona_Senden
[DEBUG] [javascripts] - Restore Script: Entsorgung_Senden
[DEBUG] [javascripts] - Restore Script: Kraftstoffpreise_Senden
[DEBUG] [javascripts] - Restore Script: Temperatur_mit_Telegram_senden
[DEBUG] [javascripts] - Restore Script: Ikea_Bewegungsmelder
[DEBUG] [javascripts] - Restore Script: Rollo_Auf_bei_Starkwind
[DEBUG] [javascripts] - Restore Script: Octoprint_Neu
[DEBUG] [javascripts] - Try deleting the Javascript tmp directory: "/opt/iobroker/backups/tmpScripts"
[DEBUG] [javascripts] - Javascript tmp directory "/opt/iobroker/backups/tmpScripts" successfully deleted
[DEBUG] [javascripts] - javascript.0 started
[DEBUG] [javascripts] - Javascript Restore completed successfully
[EXIT] javascript restore done
[EXIT] 0

**Versions:**  
 - Adapter version: 2.4.6
 - JS-Controller version: 4.0.23
 - Node version: 14.19.0
 - Operating system: raspian / docker

**Comment by simatec** [comment]
Wie heißt denn das Blockly? Hast du den JavaScript Adapter mal neugestartet?

**Comment by DerDoubleD** [comment]
Der Name ist Octorprint_Neu
Ja habe mehrmals versucht den adapter neu zu starten.
Habe absichtlich noch mehr aus dem blockly gelöscht um zu testen ob nach dem restore wieder was da ist. Leider nein.
Kann ich so einen restore auch händisch (Kommandozeile) durchführen?

**Comment by simatec** [comment]
Hast du die Pfadspiegelung im JavaScript Adapter aktiv?

**Comment by DerDoubleD** [comment]
Ja habe ich. Die scripte sind dort auch vorhanden.

**Comment by simatec** [comment]
Deaktiviere die mal … denke der spiegelt immer den alten Stand zurück

**Comment by DerDoubleD** [comment]
Dann hängt die Wiederherstellung.
Seit 5 Minuten steht es jetzt bei `Started restore ...`

JavaScript und Backup Adapter habe ich beide schon neu gestartet

**Comment by simatec** [comment]
Einfach noch mal den Restore starten

**Comment by DerDoubleD** [comment]
Leider immer das gleiche Ergebnis.
Bleibt bei Started restore hängen

**Comment by simatec** [comment]
Bitte den Debuglog posten … ansonsten ist es Glaskugel schauen

**Comment by DerDoubleD** [comment]
Im Debug auch umgestellt auf "alles" wird nichts angezeigt wieso es hängt.

Ich habe das Problem jetzt anders gelöst.
Trotzdem Danke für Deine Hilfe!!!
