### ISSUE TITLE
iobroker Backups werden immer abgebrochen 

### ISSUE THREAD

**Issue by derdoerk** [simatec/ioBroker.backitup#703]
Hallo, 

ich habe das Problem, dass meine ioBroker Updates ständig mit Fehler abgebrochen werden. Hierbei sync ich die Updates auf meine Synology via FTP. Der Zugriff via FTP funktioniert, da das auslesen alter Backups funktioniert. 

Das Merkwürdige hierbei ist, es hat mal funktioniert und irgendwann wurden die Backups einfach nicht mehr durchgeführt. 

Mach ich was falsch, muss etwas noch beachtet werden?

Gruß
Dirk

Laut Debug habe ich folgende Meldungen. 

Started iobroker ...
[DEBUG] [iobroker] start with {"type":"creator","time":"02:40","debugging":true,"slaveBackup":"Single","everyXDays":"1","deleteBackupAfter":0,"ftp":{"enabled":true,"type":"storage","source":"ftp","host":"192.168.0.160","debugging":true,"deleteOldBackup":true,"ownDir":true,"dir":"/Haussteuerung_Backup","dirMinimal":"/Haussteuerung_Backup","user":"Backup","pass":"****","port":"21","ignoreErrors":false},"ignoreErrors":false,"dir":"/opt/iobroker","yahka":{"enabled":true,"type":"creator","ftp":{"enabled":true,"type":"storage","source":"ftp","host":"192.168.0.160","debugging":true,"deleteOldBackup":true,"ownDir":true,"dir":"/Haussteuerung_Backup","dirMinimal":"/Haussteuerung_Backup","user":"Backup","pass":"****","port":"21","ignoreErrors":false},"cifs":{"enabled":false,"mountType":"Copy","type":"storage","source":"ftp","mount":"192.168.0.160","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":false,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"/Haussteuerung_Backup","dirMinimal":"sharename/backupDir","user":"","pass":"****","ignoreErrors":false},"dropbox":{"enabled":false,"type":"storage","source":"ftp","debugging":true,"deleteOldBackup":false,"accessToken":"****","dropboxAccessJson":"","dropboxTokenType":"custom","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"webdav":{"enabled":false,"type":"storage","source":"ftp","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","signedCertificates":true,"ignoreErrors":false},"googledrive":{"enabled":false,"type":"storage","source":"ftp","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"path":"/opt/iobroker/iobroker-data","nameSuffix":"","slaveSuffix":"","hostType":"Single","ignoreErrors":false},"javascripts":{"enabled":true,"type":"creator","ftp":{"enabled":true,"type":"storage","source":"ftp","host":"192.168.0.160","debugging":true,"deleteOldBackup":true,"ownDir":true,"dir":"/Haussteuerung_Backup","dirMinimal":"/Haussteuerung_Backup","user":"Backup","pass":"****","port":"21","ignoreErrors":false},"cifs":{"enabled":false,"mountType":"Copy","type":"storage","source":"ftp","mount":"192.168.0.160","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":false,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"/Haussteuerung_Backup","dirMinimal":"sharename/backupDir","user":"","pass":"****","ignoreErrors":false},"dropbox":{"enabled":false,"type":"storage","source":"ftp","debugging":true,"deleteOldBackup":false,"accessToken":"****","dropboxAccessJson":"","dropboxTokenType":"custom","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"webdav":{"enabled":false,"type":"storage","source":"ftp","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","signedCertificates":true,"ignoreErrors":false},"googledrive":{"enabled":false,"type":"storage","source":"ftp","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"slaveSuffix":"","hostType":"Single","nameSuffix":"","ignoreErrors":false},"historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"signal":{"enabled":false,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longSignalNotice","onlyError":false,"signalWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [iobroker] - host.iobroker 9727 states saved

**Comment by simatec** [comment]
Zeige mal deine Konfiguration für den FTP Zugang. 
Frage: Wenn du eine Synology hast, warum dann FTP? Hier wäre NFS oder CIFS die bessere Wahl

**Comment by derdoerk** [comment]
MOrjen

```
Started iobroker ...
[DEBUG] [iobroker] start with {"type":"creator","time":"02:40","debugging":true,"slaveBackup":"Single","everyXDays":"1","deleteBackupAfter":0,"ftp":{"enabled":true,"type":"storage","source":"ftp","host":"192.168.0.160","debugging":true,"deleteOldBackup":true,"ownDir":true,"dir":"/Haussteuerung_Backup","dirMinimal":"/Haussteuerung_Backup","user":"Backup","pass":"****","port":"21","ignoreErrors":false},"ignoreErrors":false,"dir":"/opt/iobroker","yahka":{"enabled":true,"type":"creator","ftp":{"enabled":true,"type":"storage","source":"ftp","host":"192.168.0.160","debugging":true,"deleteOldBackup":true,"ownDir":true,"dir":"/Haussteuerung_Backup","dirMinimal":"/Haussteuerung_Backup","user":"Backup","pass":"****","port":"21","ignoreErrors":false},"cifs":{"enabled":false,"mountType":"Copy","type":"storage","source":"ftp","mount":"192.168.0.160","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":false,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"/Haussteuerung_Backup","dirMinimal":"sharename/backupDir","user":"","pass":"****","ignoreErrors":false},"dropbox":{"enabled":false,"type":"storage","source":"ftp","debugging":true,"deleteOldBackup":false,"accessToken":"****","dropboxAccessJson":"","dropboxTokenType":"custom","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"webdav":{"enabled":false,"type":"storage","source":"ftp","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","signedCertificates":true,"ignoreErrors":false},"googledrive":{"enabled":false,"type":"storage","source":"ftp","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"path":"/opt/iobroker/iobroker-data","nameSuffix":"","slaveSuffix":"","hostType":"Single","ignoreErrors":false},"javascripts":{"enabled":true,"type":"creator","ftp":{"enabled":true,"type":"storage","source":"ftp","host":"192.168.0.160","debugging":true,"deleteOldBackup":true,"ownDir":true,"dir":"/Haussteuerung_Backup","dirMinimal":"/Haussteuerung_Backup","user":"Backup","pass":"****","port":"21","ignoreErrors":false},"cifs":{"enabled":false,"mountType":"Copy","type":"storage","source":"ftp","mount":"192.168.0.160","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":false,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"/Haussteuerung_Backup","dirMinimal":"sharename/backupDir","user":"","pass":"****","ignoreErrors":false},"dropbox":{"enabled":false,"type":"storage","source":"ftp","debugging":true,"deleteOldBackup":false,"accessToken":"****","dropboxAccessJson":"","dropboxTokenType":"custom","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"webdav":{"enabled":false,"type":"storage","source":"ftp","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","signedCertificates":true,"ignoreErrors":false},"googledrive":{"enabled":false,"type":"storage","source":"ftp","debugging":true,"deleteOldBackup":false,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"slaveSuffix":"","hostType":"Single","nameSuffix":"","ignoreErrors":false},"historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"signal":{"enabled":false,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longSignalNotice","onlyError":false,"signalWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [iobroker] - host.iobroker 9733 states saved
```

Also in den Debug ausgaben steht nur das drin, glaube nicht das es am FTP Zugang liegt, auch der normal backup via Putty läuft nicht durch.

![image](https://user-images.githubusercontent.com/79893009/170823582-20db7c5d-5689-4c8f-a4b2-3c446baa1b49.png)


Ich hab nur keine Ahnung warum.

Gruß
Dirk

**Comment by simatec** [comment]
Wie groß sind denn deine Backups?
Schaue mal, was in deinem Filesystem so rumliegt.
Ring-Adapter oder ESP-Home verursachen z.B. sehr viel Daten, die ein Backup crashen könnten

Ansonsten posten bitte mal den richtigen Debuglog aus den Logfiles ...
Und bitte im Codeformat. Ich kann so nichts erkennen
