### ISSUE TITLE
JavaScript restore bricht mit Fehler ab

### ISSUE THREAD

**Issue by joschi71r** [simatec/ioBroker.backitup#713]
Hallo,
beim Versuch JavaSripts mit Backitup wiederherzustellen, brich das Restore mit folgender Fehlermeldung ab

Error: {"errno":-1,"code":"EPERM","syscall":"utime","path":"/opt/iobroker/backups/tmpScripts/"}

Die Rechte des tmpScripts Verzeichnisses sind:
drwxrwxrwx  2 root     root        0 Jun 13 14:30 tmpScripts

iobroker fix ist gelaufen

Backitup Version 2.4.9
JavaScript version 5.7.0
Node-JS Version 12.22.6
 js-controller Version 4.0.23

Bin mit meiner Weisheit am Ende

**Comment by simatec** [comment]
Du musst die Rechte so anpassen, dass auch der User iobroker Zugriff hat

**Comment by simatec** [comment]
Dann lösche den Ordner Backups (vorher den Inhalt sichern) und starte im Anschluss Backitup neu

**Comment by joschi71r** [comment]
Mein Fehler!
Ich dachte das der Ordner backups lokal auf dem Raspi liegt. Jedoch ist das der Mountpoint für das NAS.
Der Fehler liegt also auf dem NAS.
Habe zwar noch keine Einstellung im NAS gefunden, so das die Wiederherstellung läuft. Aber wenigstens ist das Problem eingekreist.

**Comment by joschi71r** [comment]
Trotzdem, vielen Dank für deine Bemühungen.

**Comment by simatec** [comment]
Welches NAS nutzt du und was hast du für Einstellungen für den mount in Backitup und auf dem NAS?
