### ISSUE TITLE
Adapter merkt sich User und PW von Homematic CCU nicht

### ISSUE THREAD

**Issue by cribito79** [simatec/ioBroker.backitup#714]
Aktuell habe ich folgendes Problem bei dem automatischen Backup der RaspberryMatic. 

Vom Backitup Adapter wird im Log folgender Fehler ausgeworfen:

„[ccu]invalid credentials or too many Sessions“

Bei dem Zugangsdaten im Adapter ist mir aufgefallen das er „Admin“ immer wieder in „admin“ ändert. 
Wenn ich das Passwort manuell erneut eintrage wird ein Backup erstellt. 

Nach dem schließen des Adapters und einem erneuten Backup kommt wieder der o.g. Fehler. 

Version 2.4.5 und aktuell 2.4.9

**Comment by simatec** [comment]
Kann ich so leider nicht reproduzieren.
Auf allen Testsystemen funktioniert es wie es soll.

Hast du ggfs. Autovervollständigung oder der gleich aktiviert? Was passiert beim speichern der Einstellungen?

**Comment by cribito79** [comment]
Hallo
Danke für die schnelle Antwort. Es war tatsächlich die Autofill
Funktion. So simpel kann es sein. Kein Wunder das sich Admin immer
wieder in admin verwandelt hat.
Dennoch danke für die Mühe und den Tipp.

Am Mittwoch, dem 29.06.2022 um 01:11 -0700 schrieb simatec:
