### ISSUE TITLE
Beim Backup vom InfluxDB erfolgt Fehlermeldung influx not found

### ISSUE THREAD

**Issue by SurfGargano** [simatec/ioBroker.backitup#717]
Beim Backup vom InfluxDB erfolgt Fehlermeldung influx not found :
[DEBUG] [influxDB] - InfluxDB-Backup started ...
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[DEBUG] [influxDB] - 
[ERROR] [influxDB] - Error: Command failed: influx backup --bucket iobroker -t GkGcHZ0LM1QaWeMhV-jET_6jU3faChYcBFeKabrnAgorKfwFm5TAUZ5MiotijF8YgLJN6ttF4JtFHXavY-HZgA== "/opt/iobroker/backups/influxDB_2022_07_01-11_14_47_backupiobroker"
/bin/sh: 1: influx: not found

Ich habe InfluxDB 2.x mit Betriebssystem arm64
Adapter ist der neueste aus Beta 2.4.9

**Comment by simatec** [comment]
Dir fehlt auf deinem System influx-cli
https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch#influxdb-backup

**Comment by SurfGargano** [comment]
ok, danke. Hat geklappt.
