### ISSUE TITLE
Error: "PEM routines:get_name:no start line" when downloading local backups

### ISSUE THREAD

**Issue by mesche** [simatec/ioBroker.backitup#718]
**Describe the bug**  
An exception occurred when trying to download a local backup file via the browser

**To Reproduce**  
1. Go to 'Instances >BackItUp Settings'
2. Click on 'Restore tab'
3. Click on 'Show backup list button'
4. Click on 'Download icon'

**Expected behavior**  
Application provides file for download.

**Screenshots & Logfiles**  
```
warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
info	terminating
info	cleaned everything up...
error	Exception-Code: ERR_OSSL_PEM_NO_START_LINE: error:0909006C:PEM routines:get_name:no start line
error	Error: error:0909006C:PEM routines:get_name:no start line at Object.createSecureContext (_tls_common.js:130:17) at Server.setSecureContext (_tls_wrap.js:1331:27) at Server (_tls_wrap.js:1186:8) at new Server (https.js:70:3) at Object.createServer (https.js:106:10) at fileServer (/opt/iobroker/node_modules/iobroker.backitup/main.js:1402:35) at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.backitup/main.js:243:25)
error	unhandled promise rejection: error:0909006C:PEM routines:get_name:no start line
error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
debug	Download server could not be closed
debug	Backup list be read ...
```

**Versions:**  
 - Adapter version: v2.4.9
 - JS-Controller version: v4.0.23

**Additional context**  
Use self signed SSL cert in ioBroker

**Comment by simatec** [comment]
Is the file being downloaded?
I cannot reproduce the error with a self-signed certificate and a local download.

**Comment by mesche** [comment]
Node / Node.js: v14.19.3
NPM: v6.14.17

Which Config? Adapter?
Enabled backups: ioBroker & Postgresql
![image](https://user-images.githubusercontent.com/7409025/177173740-befecd22-4149-4026-b047-6f71c16039dd.png)
![image](https://user-images.githubusercontent.com/7409025/177174008-4f687435-c411-42f7-b1e1-30b08a8ece60.png)

**Comment by mesche** [comment]
I use Chrome.

Small recommendation: Please do not suppress technical errors/infos in the debug log like (easier debuggin ;-) )
´´´
        try {
            dlServer.close();
        } catch (e) {
            adapter.log.debug('Download server could not be closed');
        }
´´´

**Comment by simatec** [comment]
try & catch is expressly desired
I assume that you have a problem with the certificates.
Try it with other certificates or with the original ones and http

**Comment by mesche** [comment]
Correct, this is what the error says: "PEM routines:get_name:no start line"
But my certificates works ioBroker without problems. Following the same scheme I run over 10 other applications without problems too

**Comment by mesche** [comment]
The problem seems to be that the certificate is read out with the utf-8 encoding. If I use iso-8859-1 the following happens

![image](https://user-images.githubusercontent.com/7409025/177184068-97d940e7-a176-4f12-9dcc-e9075dd4cefc.png)

**Comment by simatec** [comment]
with self-signed certificate, https  and utf8

![GIF 04 07 2022 17-33-19](https://user-images.githubusercontent.com/39792461/177185305-5c716335-a953-4549-aa8d-7d3e29b6d1d0.gif)

**Comment by mesche** [comment]
Why do you assume that all PEM files are saved with UTF-8 encoding?

**Comment by simatec** [comment]
I don't know anything else... But we're more than welcome to test iso

**Comment by simatec** [comment]
I don't know why it shouldn't be utf8... We're welcome to test iso though

**Comment by simatec** [comment]
Please test the version of the Dev Branch with iso-8859-1

Installation via Github with the following link:
https://github.com/simatec/ioBroker.backitup/tarball/dev

**Comment by simatec** [comment]
https://www.namecheap.com/support/knowledgebase/article.aspx/9705/33/installing-an-ssl-certificate-on-nodejs/
Quote:
> The files can be read as buffers or as text (specifying the UTF-8 encoding) using the [FS (File System)](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html) module, or can be simply provided as strings with the certificate code in the PEM format.

**Comment by mesche** [comment]
Hello, it's me again. I have now looked at the code again a little more closely and found the problem. First of all. Encoding is not the main problem. Probably you can simply omit the encoding and read the data as byte.

´´´
fs.readFileSync(path.join(bashDir, 'iob.key'));
´´´

**Now to the actual problem:**

In a previous function, the certificates are written to new files.

´´´
fs.writeFileSync(path.join(bashDir, 'iob.key'), _cert.native.certificates[`${_adminCert.native.certPrivate}`]);
fs.writeFileSync(path.join(bashDir, 'iob.crt'), _cert.native.certificates[`${_adminCert.native.certPublic}`]);
´´´
In the further process, this only works, if the data is also stored directly in the ioBroker certificate settings.
But I use the other method and have stored the absolute paths of the files directly in the settings.

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/7409025/177208989-2f106f40-87d1-4d8a-93e7-252e4f92d4b1.png">

This is also a permitted and valid setting. Hope I was able to help you with the error analysis and a possible fix

**Comment by mesche** [comment]
Hacky/dirty workaround to proof the behavior

```
            try {
                privateKey = fs.readFileSync(path.join(bashDir, 'iob.key'), 'utf8');
                certificate = fs.readFileSync(path.join(bashDir, 'iob.crt'), 'utf8');

		if(fs.existsSync(privateKey)) { // variable contains path not content
                    privateKey = fs.readFileSync(privateKey);
		}

		if(fs.existsSync(certificate)) { // variable contains path not content
                    certificate = fs.readFileSync(certificate);
		}
......
```

**Comment by simatec** [comment]
Please test the current dev version
https://github.com/simatec/ioBroker.backitup/tarball/dev

**Comment by mesche** [comment]
Hi,
thank you for the fast fix. But I have a few minor comments/suggestions about it

1. Store cert infos in variables would make the code a little more readable and else blocks are not necessary
2. I think string cast is not necessary`${_adminCert.native.certPrivate}`
3. I think path.join() with one parameter is not necessary

```
                let adminCertPrivate = _cert.native.certificates[_adminCert.native.certPrivate];
                let adminCertPublic  = _cert.native.certificates[_adminCert.native.certPublic];

                if (adminCertPrivate.startsWith('/') && fs.existsSync(adminCertPrivate)) {
                    adminCertPrivate = fs.readFileSync(adminCertPrivate, 'utf8');
                }
                fs.writeFileSync(path.join(bashDir, 'iob.key'), adminCertPrivate);

                if (adminCertPublic.startsWith('/') && fs.existsSync(adminCertPublic)) {
                    adminCertPublic = fs.readFileSync(adminCertPublic, 'utf8');
                }
                fs.writeFileSync(path.join(bashDir, 'iob.crt'), adminCertPublic);
```

And yes! After this adjustment the download works for me

Thank you, regards  Esche

**Comment by simatec** [comment]
The fact that the certificates are stored in files has other reasons and nothing to do with the download function.
This is exclusively for the restore and is required.

Does the download work with the current dev version?

**Comment by mesche** [comment]
> The fact that the certificates are stored in files has other reasons and nothing to do with the download function. This is exclusively for the restore and is required.
> 
> Does the download work with the current dev version?

I think you misunderstood me. 

```
    let adminCertPrivate = _cert.native.certificates[_adminCert.native.certPrivate];
    let adminCertPublic  = _cert.native.certificates[_adminCert.native.certPublic];
```
  Clean code, easier access, avoid duplicate code.... etc...

Sorry for my bad english: `After *your* adjustment the download works for me`

**Comment by simatec** [comment]
Thank you for your feedback
