### ISSUE TITLE
Anpassung der Doku Installation influx-cli für influxDB2 mit Paketmanager

### ISSUE THREAD

**Issue by mcuiobroker** [simatec/ioBroker.backitup#721]
Installation laut Anleitung von influxData klappte es nicht.
https://docs.influxdata.com/influxdb/v2.3/tools/influx-cli/?t=Linux

https://forum.iobroker.net/topic/27267/test-adapter-iobroker-backitup-v2-4-x/2034

**Comment by simatec** [comment]
Das klappt schon .. läuft bei mir auch. 
aber es gibt inzwischen einen Weg über die aktuellen Pakete

**Comment by Grothesk242** [comment]
Repo legt man so an: 
```
wget -q https://repos.influxdata.com/influxdb.key
echo '23a1c8836f0afc5ed24e0486339d7cc8f6790b83886c4c96995b88a061c5bb5d influxdb.key' | sha256sum -c && cat influxdb.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdb.gpg > /dev/null
echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdb.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list
```

**Comment by mcuiobroker** [comment]
@Grothesk242 Das ist ja die normale Installation. Die habe ich ja gemacht. Ich sollte aber noch zusätzlich die infuxdb-cli installieren, obwohl bei der Installation gesagt wird, dass sie schon dabei ist?

**Comment by Grothesk242** [comment]
Auf dem System mit dem ioBroker muss der influxdb2-client installiert sein. 
Aus der README: 

> Um ein Backup einer InfluxDB 2.x erstellen zu können, muss Influx-CLI auf eurem System installiert sein. Dies ist sowohl bei einem lokalen als auch bei einem Remote Backup erforderlich.

**Comment by mcuiobroker** [comment]
@Grothesk242 Hab ich gerade gemacht. Ein Schritt weiter, jetzt kommt:
https://forum.iobroker.net/topic/27267/test-adapter-iobroker-backitup-v2-4-x/2067
