### ISSUE TITLE
Unterstützung des Backup von zwei Redis DBs

### ISSUE THREAD

**Issue by realmeto** [simatec/ioBroker.backitup#722]
Im ioBroker lassen sich die Objekte und Zustände getrennt aufbewahren. Ich habe das jetzt in zwei getrennte Redis DBs (jeweils ein eigener Service). Die DBs liegen jeweils im eigenen Arbeitsverzeichnis. Das ist auch erforderlich. Bei Backitup kann aber nur ein Pfad angegeben werden. So wird auch nur eine der DBs gesichert. Es wäre hilfreich, wenn es möglich wäre, einen zweiter Pfad anzugeben.

**Comment by simatec** [comment]
Dies ist bereits möglich ... Dafür wurde das Slave Backup eingeführt

**Comment by realmeto** [comment]
Das war zu einfach ;-). Auf die Idee bin ich nicht gekommen, da iobroker bei mir ja als Single läuf. Zweiter Pfad wäre zwar besser nachvollziehbar, funktionieren wird es aber so sicher auch gut. Danke!
