### ISSUE TITLE
sentry deaktiviert obwohl analysedaten senden an

### ISSUE THREAD

**Issue by krobipd** [simatec/ioBroker.backitup#724]
hallo mir gerade ein Neustart des adapter aufgefallen, ohne Grund.
und darin stand dann das sentry deaktiviert ist weil "ich das so eingestellt habe" in der Instanz.

in den Adapter Eigenschaften (also der Instanz) ist das Analysedaten senden aktiviert.

admin: 6.2.4
js controller: 6.0
Node.js: v16.16.0
NPM: 8.15.0
edit: sorry adapter version 2.4.10

<img width="175" alt="Bildschirmfoto 2022-07-22 um 16 16 39" src="https://user-images.githubusercontent.com/27220902/180458798-28b255eb-6475-4659-b31b-82136d4a71ff.png">
<img width="1114" alt="Bildschirmfoto 2022-07-22 um 16 17 00" src="https://user-images.githubusercontent.com/27220902/180458807-8d211135-2a6f-4f77-b2c8-48e070942861.png">

**Comment by simatec** [comment]
Das ist normal ... beim deaktivieren startet der Adapter neu.
Sentry musst du für Backitup auch nicht in den Instanzen oder Objekten deaktivieren.
Hier reicht es "Analysedaten senden" zu deaktivieren
