### ISSUE TITLE
Erstellung, eines Backups, lässt ioBroker abschmieren

### ISSUE THREAD

**Issue by senger1985** [simatec/ioBroker.backitup#727]
Nachdem ich, heute Nacht(2:00 Uhr) ein Backup, über den Adapter habe erstellen lassen, ist mir aufgefallen, dass der Admin nicht mehr erreichbar war.

Erst, als ich ein fix habe laufen lassen, konnte wieder auf den Admin zugreifen,

Da das Backup, nicht auf meinem Server gespeichert wurde, habe ich händisch, über den Adapter, ein weiteres Backup angestoßen,
Und siehe da, der Admin war wieder nicht erreichbar.(Zum Glück schien es nur ein "Schluckauf gewesen zu sein)
Alle Adapter haben sich neu gestartet.

**Versions:**  
 - Adapter version: 2.4.10
 - JS-Controller version: 4.0.23
 - Node version: V16.15.1
 - Operating system: Linux Proxmox

**Comment by simatec** [comment]
Bitte den Debuglog posten und bitte die Angabe zu deinem System. 
- Backupgröße
- RAM
- Systembeschreibung

**Comment by senger1985** [comment]
Backupgröße: 148.05 MB
RAM: 6 GB
Trotz, dass der Backitup-Adapter, auf "Debug" stand, wurde kein Logeintrag erzeugt.

**Comment by simatec** [comment]
Stoße mal bitte das Backup mit `iobroker backup` über die Konsole an und poste mal die Ausgaben

**Comment by senger1985** [comment]
io@io:~$ iobroker backup
host.io 16872 states saved
host.io 16374 objects saved
host.io Cannot pack directory /opt/iobroker/node_modules/iobroker.js-controller/tmp/backup: ENOSPC: no space left on device, write

**Comment by simatec** [comment]
Da hast du dein Problem 
Keine freier Speicherplatz

`df -h`

**Comment by senger1985** [comment]
Ich habe mal ein paar Backups, auf der Platte gelöscht und schaue mal, was das nächtliche Backup "anrichtet".

**Comment by senger1985** [comment]
Danke, für die Hilfe.
Läuft
