### ISSUE TITLE
Restoring NodeRed - automatically restore missing modules and data outside adapter config

### ISSUE THREAD

**Issue by mickym2** [simatec/ioBroker.backitup#730]
Instead of using the adapter config, there are in general a lot more advantages if the original pallet-manager can be used and in addition npm modules are installed automatically when used in function nodes. Why is the original package.json not restored in general and a npm install to restore all missing node_modules in the specific NodeRed instance. 

In addition - the whole directory should be restored (except the node_modules directory). The lib folder with own flow libraries and other node specific configurations are lost as well.

**Comment by simatec** [comment]
Please open an issue in the NodeRed Adapter.
The backup is created according to the iobroker standard.
There are some adaptions in the NodeRed Adapter necessary.

**Comment by mickym2** [comment]
Done. Corresponding issue has been opened: https://github.com/ioBroker/ioBroker.node-red/issues/321
