### ISSUE TITLE
No restore for NodeRed instances with activated project function 

### ISSUE THREAD

**Issue by mickym2** [simatec/ioBroker.backitup#731]
If someone uses the project function in a NodeRed instance nothing will be restored. As the flows are stored in the project subdirectory - and this folders remain empty - all flows are lost. 
All flows are lost. The complete project directory subtree needs to be restored, to have the local github repository back which contains the history of the projects. 

In addition all other directories remain empty as well. lib directory for own flow library and data which are stored from specific node types and contain specific informations (like cronplus etc.)

All node_modules should be restored automatically by restoring a package.json with their dependencies and executing a local npm install.  (see https://github.com/simatec/ioBroker.backitup/issues/730)

**Comment by simatec** [comment]
Please open an issue in the NodeRed Adapter.
The backup is created according to the iobroker standard.
There are some adaptions in the NodeRed Adapter necessary.

**Comment by mickym2** [comment]
Done! Corresponding issue has been opened here: https://github.com/ioBroker/ioBroker.node-red/issues/320

**Comment by Apollon77** [comment]
@simatecThe problem is that there is content in the directory that can not be backed up by js.controller (a node_modules) - at least not before we "learn" how to exclude content in a directory from backup :-(

So yes a backiutup "custom solution" could be an idea to allow backing up iobroker-data/node-red.X dirs and exclude the node_modules

**Comment by simatec** [comment]
@mickym2 Can you please post me the exact path and the contents of the folder times post

**Comment by mickym2** [comment]
@simatec I explained everything very detailed here: https://github.com/ioBroker/ioBroker.node-red/issues/320

In summery everything has to be backuped of the /opt/iobroker/iobroker-data/node-red.X dir - excluding the /opt/iobroker/iobroker-data/node-red.X/node_modules directories. Those can be restored when running npm install in the /opt/iobroker/iobroker-data/node-red.X/ directory.

**Comment by mickym2** [comment]
The only option to  lower the backup size further - if a user doesn't want to restore the history of the flows - but without knowing, what happened if the local git repository is empty or missing files  or if node-red will create a new empty structure. So the history is then the only thing which is a significant part of the backup size and is under projects directory in .git and .objects.

**Comment by Apollon77** [comment]
I have also no idea if backup/restore of a ".git" content is a good idea ... but yes could get veeery bg depending on the history

**Comment by mickym2** [comment]
> I have also no idea if backup/restore of a ".git" content is a good idea ... but yes could get veeery bg depending on the history

But needs to be tested - if an empty git can be restored or created by NodeRed itself - and may be it should be an option in the backup procedure if history should be included or not. The problem if you have a restore where you can't recover the previous functionality is in my opinion the most important problem. As many users rely only on the functionality of the backit up adapter and have no images etc. - it will be a disaster if they got back a corrupt installation.

**Comment by simatec** [comment]
Comes in v2.6.x
