### ISSUE TITLE
Backitup offers no manual backup for yahka

### ISSUE THREAD

**Issue by mickym2** [simatec/ioBroker.backitup#737]
Since a new backup topic has been added to backup the yahka settings, it seems that yahka backups are only created via scheduled backups. There is no possibility to create an manual backup.

**Comment by simatec** [comment]
yahka backups are an option of iobroker backup and cannot be created individually

**Comment by mickym2** [comment]
But if i run a iobroker backup manually no yahka backup is done.

**Comment by mickym2** [comment]
Oh sorry my mistake :( - I didn't found the file - but is there.
