### ISSUE TITLE
Prevent local backups

### ISSUE THREAD

**Issue by fgotzens** [simatec/ioBroker.backitup#739]
**Bug Report**
In the instance settings of `iobroker.backitup.0` I only have "WebDAV" enabled, but still I see local backups being written to 
`/opt/iobroker/backups/`

**Expected behavior**  
I expect these to not being written locally if not asked for, since I would like to prevent write access to my microSD card as much as possible.

**Versions:**  
 - Adapter version: v2.4.10
 - ioBroker version: v6.2.17
 - JS-Controller version: <js-controller-version> v4.0.23
 - Node version: <node-version> v16.17.0
 - Operating system: Linux RaspberrypiOS

**Comment by simatec** [comment]
This behavior is intentional and normal.
Only one copy is stored in the clouds.
If you do not want to have the backups locally, you should think about a NAS.

**Comment by fgotzens** [comment]
> This behavior is intentional and normal. Only one copy is stored in the clouds. If you do not want to have the backups locally, you should think about a NAS.

OK, many thanks, after enabling a NAS it works (i.e. it stops writing locally). 
Still, I think this is not obvious to the average user, could you maybe add this piece of information in some form of a text box in the settings page?
