### ISSUE TITLE
total backup nur lokal

### ISSUE THREAD

**Issue by Monox83** [simatec/ioBroker.backitup#741]
Moin, ich sicher die Backups per NFS auf mein lokales NAS, das funktioniert auch gut mit
grafana
HomeMatic
influxdb
iobroker
javascript
yahka

nur die total backups landen lokal und kann man erst finden wenn ich das nfs unmounte.

**Versions:**  
 - Adapter version: 2.4.12
 - JS-Controller version: 4.0.23
 - Node version: 16.13.1
 - Operating system: Debian Bullseye

Grüße Monox

**Comment by simatec** [comment]
Was bitte meinst du mit total Backups?

**Comment by Monox83** [comment]
unter /opt/iobroker/backups liegen
total-2022_08_27-00_00_13_backupiobroker.tar.gz, das NFS wird in den gleichen Ordner gemundet und dort liegen dann die anderen Files.

**Comment by simatec** [comment]
Was hast du da für eine Version von Backitup?
Das Total Backup gibt es seit 3 Jahren nicht mehr

**Comment by Monox83** [comment]
okay....

v2.4.12

das letzte Snapshot von dem System ist von April 2020, also kann die erst installation gut 3 Jahre her sein.

vielleicht mal den adapter löschen mit allen Ordnern und neu installieren?
