### ISSUE TITLE
MariaDB now needs MariaDB-Client in order to complete backups

### ISSUE THREAD

**Issue by baennjer** [simatec/ioBroker.backitup#748]
**Describe the bug**  
In the docu its pointed out to have mySQL-Client installed in order to be able to backup SQL data too.
But with newer MariaDB versions its neccessary to have MariaDB-Client installed instead, otherwise backup will not finish and throw the following error:
mysqldump: Couldn't execute 'SELECT COLUMN_NAME........... Unknown table 'COLUMN_STATISTICS' in information_schema (1109)

**To Reproduce**  
Have newer MariaDB and mySQL-Client installed

**Expected behavior**  
A completing backup is expected.

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: <newest>
 - JS-Controller version: <newest>
 - Node version: <16.17.0> 
 - Operating system: <Ubuntu 22.04>

**Additional context**  
The documentation should be updated

**Comment by simatec** [comment]
If you have MariaDB installed, then of course you must have the appropriate client.

**Comment by baennjer** [comment]
Well I found out today after some search in the net, but I would recomend to put this info into the documentation. Because in my older installation MariaDB didnt have any issues with mySQL-Client, but in newer MariaDB version it is an issue. 
Just wanted to prevent other users from running into same issue.

**Comment by simatec** [comment]
Thanks for the tip. I will adapt the docu for this

**Comment by baennjer** [comment]
Thanks. Thats very helpfull.
