### ISSUE TITLE
unknown short hand flag error

### ISSUE THREAD

**Issue by waterchill** [simatec/ioBroker.backitup#749]
Hi  I get this error when starting a backup for influx v2. How can I fix it?

[ERROR] [influxDB] - Error: Command failed: influxd backup -portable -database iobroker "/opt/iobroker/backups/influxDB_2022_09_16-13_17_32_backupiobroker"
Error: unknown shorthand flag: 'p' in -portable
See 'influxd -h' for help

**Comment by simatec** [comment]
Install influxdb-cli on the system and configure backitup correctly.  you have selected the V1 in the config.

**Comment by waterchill** [comment]
Thank you now it works. I forgot to switch to v2
