### ISSUE TITLE
Wunsch: WOL integration 

### ISSUE THREAD

**Issue by kugelkopf123** [simatec/ioBroker.backitup#75]
Hallo! 

Vielen Dank für diesen wunderbaren Adapter! 
Ich backupe auf meinem NAS. Dieses ist jedoch nur bei Bedarf erreichbar. Vielleicht wäre es möglich eine Wake on Lan Option zu integrieren. Sprich: Adresse ist nicht Erreichbar, dann > WOL + 25 Sek. Wartezeit und dann erst der Beginn des Backups. Evtl. mit der Möglichkeit die Wartezeit selbstständig einzustellen. 

Viele Grüße!

**Comment by peoples0815** [comment]
Habe im Forum folgendes gefunden um das schonmal via Script zu erledigen:
`createState("javascript.0.PC1starten", 0);   // Generiert beim starten den Datenpunkt, wenn nicht vorhanden
var wol = require('wake_on_lan');         // Lädt von ioBroker die das nötige Paket
var myPC1 = "00:11:22:33:44:55";         // MAC definieren


// Ab hier automatisch
on({id: "javascript.0.PC1starten", change: 'any'}, function (obj) {
   wol.wake(myPC1);
   log("Script WOL - PC1 aufgeweckt", "info");
    }

);`

Mit dem Hinweis dass man Zusätzliche NPM-Module installieren muss „node-wol“ dann sollte das Script gehen.

**Comment by simatec** [comment]
Ist ab Version 1.0.1 integriert ;-)
