### ISSUE TITLE
Grafana backup funktioniert leider nicht

### ISSUE THREAD

**Issue by tommedIO** [simatec/ioBroker.backitup#750]
**Describe the bug**  
Ich nutze den BackItUp Adapter um Iobroker, InfluxDB und Grafana zu sichern. Die ersten beiden werden perfekt gesichert. Nur leider wird kein Backup für Grafana mit abgelegt.

**Screenshots & Logfiles**  
`Started iobroker ...
[DEBUG] [mount] - noserverino option: false
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=sybackup,password=****,rw,file_mode=0777,dir_mode=0777,vers=2.0 //172.20.1.1/BACKUPS/ioBroker/ /opt/iobroker/backups"
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.raspberrypi4 11564 states saved

[DEBUG] [iobroker] - host.raspberrypi4 14145 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2022_09_22-20_23_08_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [influxDB] - InfluxDB-Backup started ...
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Backup created: /opt/iobroker/backups/influxDB_2022_09_22-20_23_21_backupiobroker.tar.gz
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[DEBUG] [influxDB] - InfluxDB-Backup for is finish
[DEBUG] [influxDB] - done
[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Try deleting the old grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - old grafana_tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[DEBUG] [grafana] - Created grafana_tmp directory
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
[DEBUG] [grafana] - found Dashboard: wasserverbrauch
[DEBUG] [grafana] - found Dashboard: err_kg
[DEBUG] [grafana] - found Dashboard: err_eg
[DEBUG] [grafana] - found Dashboard: err
[DEBUG] [grafana] - found Dashboard: status
[DEBUG] [grafana] - found Dashboard: luftung
[DEBUG] [grafana] - found Dashboard: stromverbrauch
[DEBUG] [grafana] - found Dashboard: luftdaten
[DEBUG] [grafana] - found Dashboard: err_og
[DEBUG] [grafana] - found Dashboard: heizung
[DEBUG] [grafana] - found Dashboard: garten
[DEBUG] [grafana] - start Grafana backup compress ...
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - cannot found Grafana Backup files
[DEBUG] [grafana] - done
[DEBUG] [cifs] - used copy path: /BACKUPS/ioBroker/
[DEBUG] [cifs] - done
[DEBUG] [clean] - done
[DEBUG] [telegram] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[DEBUG] [umount] - mount activ, umount is started ...
[DEBUG] [umount] - umount successfully completed
[DEBUG] [umount] - done
[EXIT] 0`

**Versions:**  
 - Adapter version: 2.4.12
 - JS-Controller version: 4.0.23 
 - Node version: 14.17.5 
 - Operating system: raspian

**Comment by simatec** [comment]
Tritt dieses Problem schon immer auf, oder erst nach einem Update?

**Comment by tommedIO** [comment]
Ich hatte das Backup für Grafana leider noch mit keiner Version lauffähig.

simatec ***@***.***> schrieb am Do., 22. Sept. 2022, 22:08:

**Comment by simatec** [comment]
Als erstes würde ich mal zum testen das NAS abschalten und nur lokal sichern.
Sollte es dort laufen, hast du ein Rechteproblem auf deinem NAS.

Des Weiteren prüfe bitte Username, Passwort und APIKey von Grafana.
Diese Daten müssen in Backitup korrekt konfiguriert sein.

Das ApiKey muss für einen Admin konfiguriert sein und darf nicht abgelaufen sein.

Weiter auch prüfen, dass in Backitup das richtige Protokoll konfiguriert ist. Standard ist http.
Sollte dein Grafana https nutzen, musst du dies anpassen.

Das bitte alles prüfen und ggfs. anpassen.

**Comment by SirFlour** [comment]
ich hatte auch das problem und jetzt funktioniert es. ich glaube ich habe den admin token benutzt und nochmal dabei das admin pw eingegeben. ne fehlermeldung, ob hier ggf die dateien die man gefunden hat nicht kopiert werden können wäre gut. oder aber das wird hiermit gesagt "[DEBUG] [grafana] - cannot found Grafana Backup files" :)

**Comment by tommedIO** [comment]
Ich habe das Problem nun gefunden. Es war eine Konfiguration, die ich (vermutlich als Unwissenheit) bei der Inbetriebnahme der Grafanainstallation eingestellt hatte. Bei mir war in der Grafana.ini "allow_sign_up" auskommentiert. Die Zeile habe ich nun wieder aktiviert und damit funktioniert das Backup.
