### ISSUE TITLE
Backup always gets out of schedule

### ISSUE THREAD

**Issue by TZanke** [simatec/ioBroker.backitup#759]
**Describe the bug**  
My NAS is only available on Sunday night 3-9 am. So i set the BackItUp schedule to 6 am every 7 days. Because it is not possible to set a start date, i was forced to do this at a sunday. After doing so, the schedule shows the next backup at "2. october 2022 6 am". Perfect! BUT it is not doing so. Today (i tried it at least for the last 2 months) BackItUp shows me this:

![image](https://user-images.githubusercontent.com/1613368/193401953-6ff518a8-b1fb-4769-9d6c-a9cf75042ef7.png)

Why in the world does the scheduled date always change to saturday or a complete other day in the week?! It is supposed to do it on sunday as it correctly told me some days ago. But see the screenshot, this night he also had some premature ... backup running. This makes me totaly crazy. I just like to have a scheduled backup each Sunday morning, nothing special.

**To Reproduce**  
1. Wait for a sunday
2. Schedule a backup for 6 am every 7 days
3. verify next schedule date on backItUp page
4. wait for the next sunday
5. backup was not executed because some other date is shown

**Expected behavior**  
 I just like to have a scheduled backup each Sunday morning.

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: 2.4.12
 - JS-Controller version: 4.0.23
 - Node version: Node.js: v16.17.1
 - Operating system: Raspberry Pi OS 10 (Buster)

**Additional context**  
-

**Comment by simatec** [comment]
Unfortunately, your idea of backups does not correspond to that of Backitup.

But you can disable the automatic backups in Backitup and start them manually after a cron job.

The disadvantage of a manual backup is that the old backups are not deleted.
You would have to do this manually.

Here is an example....

`schedule("0 6 * * 0", async function () {
  setState("backitup.0.oneClick.iobroker"/*Execute iobroker backup*/, true);
});
schedule("0 7 * * 0", async function () {
  setState("backitup.0.oneClick.ccu"/*Execute CCU backup*/, true);
});`

**Comment by TZanke** [comment]
I've done it with Blockly, it is working like a charm. Thank you!
