### ISSUE TITLE
MySQL Backup - to many connections

### ISSUE THREAD

**Issue by darkiop** [simatec/ioBroker.backitup#761]
**Describe the bug**  
Immer zur Laufzeit des ioBroker Bacups (incl. DB Backup):
![grafik](https://user-images.githubusercontent.com/205119/193729628-e766fdab-d1fb-4a4f-abb1-19695e914f18.png)

Gefunden dazu hatte ich dieses Issue:
https://github.com/simatec/ioBroker.backitup/issues/242

**Versions:**  
Zur Umgebung: ioBroker und MariaDB (10.5.15) laufen jeweils in einem eigenen LXC unter Debian Bullseye.

**Additional context**  
Wie wäre es mit einem Schalter um den ioBroker.sql Adapter zur Laufzeit des Backups optional zu stoppen? Oder ein Object für Backitup das 'Backup = aktiv' anzeigt. Dann könnte man darauf triggern und bei Bedarf Adapter stopppen.

**Comment by simatec** [comment]
Du kannst die Optionen "--quick --single-transaction" in Backitup aktivieren.
Damit sollte das Problem gelöst werden

**Comment by darkiop** [comment]
Test Erfolgreich. Danke dir!
