### ISSUE TITLE
Creating Google Drive Auth token not possible anymore

### ISSUE THREAD

**Issue by Sleepwalker56** [simatec/ioBroker.backitup#766]
Hi,
it is not possible to create the token via the given link in the adapter. It states that the current method is not supported anymore. See this site for more info: https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

Try to get a new access token for Google Drive

**Versions:**  
 - Adapter version: 2.4.12
 - Operating system: Raspi OS Lite 11, 64bit

**Comment by simatec** [comment]
Fix in v.2.5.0
