### ISSUE TITLE
Backupfiles from Dropbox are not shown for restore

### ISSUE THREAD

**Issue by Standarduser** [simatec/ioBroker.backitup#771]
My BackItUp adapter is configured to upload backup files into my Dropbox - this works fine.
It's also configured to keep the last 5 Backups.

But if I want to select a backup for restore I can't see the latest backups, just 5 old ones. At the moment there are 9 backup files instead of 5.

**iobroker_2022_09_28-02_00_13_backupiobroker.tar.gz
iobroker_2022_10_01-02_00_10_backupiobroker.tar.gz
iobroker_2022_10_04-02_00_10_backupiobroker.tar.gz
iobroker_2022_10_07-02_00_10_backupiobroker.tar.gz
iobroker_2022_10_10-02_00_10_backupiobroker.tar.gz**
iobroker_2022_10_13-02_00_10_backupiobroker.tar.gz
iobroker_2022_10_17-18_00_12_backupiobroker.tar.gz
iobroker_2022_10_19-02_00_10_backupiobroker.tar.gz
iobroker_2022_10_19-07_10_45_backupiobroker.tar.gz

In debug mode there are following messages in log file:
```
2022-10-19 16:34:29.597 - info: backitup.0 (463496) Loglevel changed from "warn" to "debug"
2022-10-19 16:34:46.384 - debug: backitup.0 (463496) telegram-instance: telegram.0
2022-10-19 16:34:51.339 - debug: backitup.0 (463496) Backup list cannot be read ...
2022-10-19 16:34:51.340 - debug: backitup.0 (463496) Backup list cannot be read ...
2022-10-19 16:34:51.341 - debug: backitup.0 (463496) Backup list cannot be read ...
2022-10-19 16:35:27.545 - debug: backitup.0 (463496) Backup list cannot be read ...
2022-10-19 16:35:27.545 - debug: backitup.0 (463496) Backup list cannot be read ...
2022-10-19 16:35:27.546 - debug: backitup.0 (463496) Backup list cannot be read ...
```

**Comment by simatec** [comment]
Ich benötige ein paar mehr Angaben.
Der Fehler ist für mich nicht reproduzierbar.

Auf meinen Testsystemen können alle Backups aus der Dropbox gelesen werden.

**Comment by Standarduser** [comment]
Sorry, I don't have more information due to poor debug logging of BackItUp. 

But I noticed that a newer backup gets displayed when I delete an older one. 

Maybe the problem gets solved if all available backups are displayed, regardless howmany the adapter is configured to keep.

**Comment by simatec** [comment]
What bad debug logging?

Do not understand the statement.
I need more info, screenshots etc.

All my test systems show all backups from dropbox and this is the first time I've heard this message from you.

What names do your backups have and what else is in the directories?

Please more info

**Comment by Standarduser** [comment]
poor != bad (just to say)
Sorry if this was a misunderstanding.

Okay, even if I don't really have more information I will try to explain a little bit more.
I got that issue described in the first post and was able to solve this by deleting all backups and start from beginning.

But I'm able to reproduce it (it's a little bit different from above).

Now at this moment I have a Dropbox folder which contains only backups made with BackItUp adapter (22 files).
This is a screenshot from Dropbox web ui:
<img width="891" alt="dropbox-files" src="https://user-images.githubusercontent.com/8029204/197832544-00070aea-7674-4fff-a828-b49f196aaa0c.png">

You can count 7 ioBroker backups.

Next screenshot is from BackItUp:
<img width="1259" alt="backitup-files" src="https://user-images.githubusercontent.com/8029204/197833053-ecb6f983-fab9-426e-852f-b995571695df.png">

You can count 3 ioBroker backups.

This is what BackItUp writes into log:
<img width="1195" alt="backitup-log" src="https://user-images.githubusercontent.com/8029204/197833866-bc420dbe-cd38-4ff3-8274-4642e34369a8.png">

What else can I provide to help?

**Comment by simatec** [comment]
Ich kann deinen Fehler leider nicht nachstellen.

<img width="1167" alt="Bildschirmfoto 2022-10-30 um 13 28 48" src="https://user-images.githubusercontent.com/39792461/198878501-9684fa54-4e91-487b-9173-47f3d0fdf2f8.png">

Prüfe mal, ob eventuell Dateien in der dropbox beschädigt sind. 
Was auch noch zu empfehlen ist, dass man Unterordner für die Backups anlegt.
Also sprich, iobroker und Homematic trennen.

Dies kannst du in Backitup einstellen

**Comment by simatec** [comment]
Another option would also be to renew your token. You can do this in the Backitup menu.

**Comment by mibr85** [comment]
ich hänge mich mal mit dran bei mir besteht das gleiche Problem.
wenn ich auf Sicherungen abrufen klicke passiert gar nix
![image](https://user-images.githubusercontent.com/56867583/204170845-36c4f074-12b4-4423-ade7-40b1773137c5.png)

Instanz steht auf Debug aber im log wird nach dem start nur das angezeigt:
![image](https://user-images.githubusercontent.com/56867583/204170932-fff47c67-63cd-4b6f-be78-16c2192de2e3.png)

einstellungen im Drobox Tab:
![image](https://user-images.githubusercontent.com/56867583/204171051-e58eb595-8994-4bb9-a24e-b351424cbcfe.png)

Token ist neu von heute

**Comment by simatec** [comment]
Ich kann das Problem nicht nachstellen.
Habe auch auf der Testumgebung einen neuen Token geholt und ich kann im Config Menü und über den Backitup Tab die Backups holen.
Was mir aufgefallen ist, bei dir stehen die Default Verzeichnisse in der Config. 
Eigentlich sind das Platzhalter. Stimmen die denn mit deinen Dropbox-Pfaden überein?

**Comment by simatec** [comment]
![image](https://user-images.githubusercontent.com/39792461/204256778-c1071c82-e015-4d73-8831-13e43507fafb.png)

![image](https://user-images.githubusercontent.com/39792461/204257036-0e8560b9-4a45-4970-8782-43dbcfe4cea4.png)

**Comment by mibr85** [comment]
Verzeichnisse passen
![image](https://user-images.githubusercontent.com/56867583/204258200-1b48d4e7-d501-43f3-9f8b-bf5ce217230f.png)
Kann es denn mit der Installation in Docker zu tun haben?

**Comment by simatec** [comment]
Nein... Mein Testsystem ist auch auf Docker

**Comment by simatec** [comment]
Zeige mal im Pfad `/opt/iobroker/node_modules/iobroker.backitup` die Ausgabe von folgenden Befehl

`npm ls`

**Comment by simatec** [comment]
Sieht gut aus... Ich würde einfach mal den Container durchstarten

**Comment by mibr85** [comment]
leider keine änderung :-(

**Comment by simatec** [comment]
Kannst du die Backups Lokal abrufen? Prüfe dort mal bitte die rechte der Backups, die unter /opt/iobroker/backups liegen

`ls -lah /opt/iobroker/backups`

**Comment by mibr85** [comment]
![image](https://user-images.githubusercontent.com/56867583/204290855-d15234fc-6bed-49c0-9f18-33b3b3cf21a0.png)

**Comment by mibr85** [comment]
wenn ich auf Sicherungen Abrufen clicke
![image](https://user-images.githubusercontent.com/56867583/204312166-99242f34-6a39-49b9-9b83-9b5a4bf20eac.png)

kommt das fenster und es passsiert nix auch nach 30min nicht
![image](https://user-images.githubusercontent.com/56867583/204312319-ca2f43df-6aba-4e26-91f3-91118c509e91.png)

**Comment by simatec** [comment]
Ich gehe davon aus, dass deine Rechte nicht korrekt sind. 
Was hast du denn für eine Container Version laufen?
Da schonmal ein Update des Containers gemacht?

**Comment by simatec** [comment]
Wie ist hier der Stand beim testen?

**Comment by mibr85** [comment]
Sorry hatte bis jetzt keine Zeit zum nachschauen:
![grafik](https://user-images.githubusercontent.com/56867583/206130091-41971351-08c2-47f3-90f9-0c5323122f95.png)
Update vom Container hab ich noch nicht gemacht.

**Comment by mibr85** [comment]
Container Update durchgeführt.
![grafik](https://user-images.githubusercontent.com/56867583/206156638-b85987b0-9700-4be7-9bf7-cfda265b236e.png)

Problem weiterhin vorhanden:
![grafik](https://user-images.githubusercontent.com/56867583/206156538-05e2b2e4-2546-4315-bb38-f56c77fab990.png)
