### ISSUE TITLE
Backup wird nicht ausgeführt

### ISSUE THREAD

**Issue by Chaot1** [simatec/ioBroker.backitup#773]
Auf Version 2.5.0 wird das Backup nicht mehr ausgeführt. Estaucht auch keine Fehlermeldung auf.
Beim Manuellen Starten kommt im Fenster
started iobroker ....

und dann nichts mehr.
Zurück auf 2.4.16 funktioniert wieder alles.

**Comment by simatec** [comment]
Bitte Debuglog anschalten und das Ergebnis vom log beim Backupprozess hier posten. 

Nutzt du GoogleDrive?

**Comment by Chaot1** [comment]
Ja, ich nutze Google Drive.
Nachdem ich jetzt 2 oder 3 mal die Versionen gewechselt habe funktioniert es plötzlich fehlerlos. Keine Ahnung warum. Das Log war vorher immer leer.
Ich werde mal das beobachten und hier einstweilen schließen.

**Comment by simatec** [comment]
Du hast aber schon beim Update auf 2.5.0 die Breaking Change gelesen und auch so umgesetzt?

**Comment by Chaot1** [comment]
Ja, alles haarklein so ausgeführt. Insgesamt 3 mal nach jedem Update auf die 2.5.0. 
Ich vermute fast das da irgendwas aufgehängt war was sich irgendwie wieder geklärt hat.

**Comment by Chaot1** [comment]
Funktioniert NIcht:
`<html>
<body>


backitup.0 | 2022-10-24 06:36:27.250 | debug | telegram-instance:
-- | -- | -- | --
backitup.0 | 2022-10-24 06:26:31.477 | debug | [iobroker/googledrive] Google Drive: Copy iobroker_2022_10_24-06_26_05_backupiobroker.tar.gz...
backitup.0 | 2022-10-24 06:26:29.066 | debug | [iobroker/iobroker] done
backitup.0 | 2022-10-24 06:26:27.989 | debug | [iobroker/iobroker] Backup created: /opt/iobroker/backups/iobroker_2022_10_24-06_26_05_backupiobroker.tar.gz
backitup.0 | 2022-10-24 06:26:14.031 | debug | [iobroker/iobroker] host.ioBroker 24267 objects saved
backitup.0 | 2022-10-24 06:26:11.028 | debug | [iobroker/iobroker] host.ioBroker 25213 states saved
backitup.0 | 2022-10-24 06:26:05.784 | debug | Backup has started ...
backitup.0 | 2022-10-24 06:25:57.128 | debug | telegram-instance:
backitup.0 | 2022-10-24 06:25:55.200 | debug | detect last backup file: iobroker_2022_10_23-11_20_56_backupiobroker.tar.gz
backitup.0 | 2022-10-24 06:25:55.197 | debug | detect backup file 3 from googledrive: iobroker_2022_10_21-05_00_10_backupiobroker.tar.gz
backitup.0 | 2022-10-24 06:25:55.197 | debug | detect backup file 2 from googledrive: iobroker_2022_10_23-11_05_07_backupiobroker.tar.gz
backitup.0 | 2022-10-24 06:25:55.195 | debug | detect backup file 1 from googledrive: iobroker_2022_10_23-11_20_56_backupiobroker.tar.gz
backitup.0 | 2022-10-24 06:25:51.098 | info | [iobroker] backup was activated at 05:00 every 1 day(s)
backitup.0 | 2022-10-24 06:25:51.018 | debug | Backitup has recognized a linux system
backitup.0 | 2022-10-24 06:25:50.949 | info | starting. Version 2.5.0 in /opt/iobroker/node_modules/iobroker.backitup, node: v16.18.0, js-controller: 4.0.23
backitup.0 | 2022-10-24 06:25:50.118 | debug | Plugin sentry Initialize Plugin (enabled=true)
backitup.0 | 2022-10-24 06:25:50.040 | debug | States connected to redis: 127.0.0.1:6379
backitup.0 | 2022-10-24 06:25:50.024 | debug | States create User PubSub Client
backitup.0 | 2022-10-24 06:25:50.022 | debug | States create System PubSub Client
backitup.0 | 2022-10-24 06:25:50.013 | debug | Redis States: Use Redis connection: 127.0.0.1:6379
backitup.0 | 2022-10-24 06:25:49.905 | debug | Objects connected to redis: 127.0.0.1:9001
backitup.0 | 2022-10-24 06:25:49.894 | debug | Objects client initialize lua scripts
backitup.0 | 2022-10-24 06:25:49.721 | debug | Objects create User PubSub Client
backitup.0 | 2022-10-24 06:25:49.720 | debug | Objects create System PubSub Client
backitup.0 | 2022-10-24 06:25:49.675 | debug | Objects client ready ... initialize now


</body>
</html>`

**Comment by simatec** [comment]
Hast du einen neuen Api Token über Google erzeugt und diesen in die Backitup Config eingefügt?

**Comment by Chaot1** [comment]
Token ist neu.
Es hat ja gestern auch zwei mal manuell funktioniert.

**Comment by simatec** [comment]
Ich werde das noch einmal prüfen

**Comment by simatec** [comment]
Bitte teste die v2.5.1

**Comment by Chaot1** [comment]
Manuell läuft. Automatisch werde ich mal heute Nacht prüfen.
