### ISSUE TITLE
Include Backups for HAM (Homebridge accessories manager)

### ISSUE THREAD

**Issue by unstressable** [simatec/ioBroker.backitup#778]
Would be nice to implement an backup funktion for:
https://github.com/ioBroker/ioBroker.ham

Details about making a backup is here:
https://github.com/homebridge/homebridge/wiki/Backup-and-Restore

Thank you so much!

**Comment by simatec** [comment]
iobroker.ham is included in iobroker backup

**Comment by unstressable** [comment]
> iobroker.ham is included in iobroker backup

ok, nice to know.
Why isn't there an extra option to enable/disable as seen for YAHKA.

**Comment by simatec** [comment]
yahka also stores data outside of the iobroker backup.  You have to do the backup of your Homebridge yourself.  Backitup does not support this, nor is it planned.  The developers certainly created opportunities there.
