### ISSUE TITLE
No automatic upload to Google Drive for scheduled backup

### ISSUE THREAD

**Issue by borisholowka** [simatec/ioBroker.backitup#779]
Automatic backup is performed correctly. The files are stored correctly on the Raspberry Pi4. However, despite correct connection, they are not uploaded to Google Drive.
If the backup is triggered manually, it works. A new token with a new connection to Google Drive unfortunately did not lead to success.

Adapter Version: 2.4.12
Backed up by: iobroker, Javascript, Zigbee

CPU: 41,02 %
RAM: 81,1 %
Betriebszeit: 0h
Verfügbar: 4.0.23
Installiert: 4.0.23
Ereignisse: ⇥32 / ↦15
Plattform: linux
Betriebssystem: linux
Architektur: arm
CPUs: 4
Geschwindigkeit: 1800 MHz
Modell: ARMv7 Processor rev 3 (v7l)
RAM: 7.7 GB
System-Betriebszeit: 23:15:34
Node.js: v16.18.0
time: 1667110822094
timeOffset: -60
Adapter-Anzahl: 443
NPM: 8.19.2
Datenträgergröße: 29.1 GB
Freier Festplattenspeicher: 23.9 GB
Betriebszeit: 1 T. 00:03:12
Aktive Instanzen: 27
Pfad: /opt/iobroker/
aktiv: true
_nodeCurrent: 16.18.0
_nodeNewest: 16.18.0
_nodeNewestNext: 16.18.0
_npmCurrent: 8.19.2
_npmNewest: 8.19.2
_npmNewestNext: 8.19.2

**Comment by simatec** [comment]
Please use v2.5.2

**Comment by borisholowka** [comment]
Same Issue with v2.5.2

It also doesn't show in the overview that Backup was successfully:
![image](https://user-images.githubusercontent.com/86146555/198958007-27f4e813-151c-4011-8255-780ee30a9b6b.png)

**Comment by simatec** [comment]
Have you renewed the API key according to the update instructions?
