### ISSUE TITLE
Unmount bevor MySQL fertig ist. Bei NAS CIFS SMB. 

### ISSUE THREAD

**Issue by kugelkopf123** [simatec/ioBroker.backitup#78]
Der Ordner wird manchmal nicht ausgeworfen nach dem Abschluss eines Kompletten Backups + MySQL.  Auch bei Komplettes Backup + MySQL + Dropbox. 
Als Beispiel, der angehängte Log:

`[DEBUG] [history] - backitup.0.history.html
[DEBUG] [umount] start with {"mountType":"CIFS","type":"storage","source":"Local","mount":"//192.168.XXX.XXX","fileDir":"/opt/iobroker/node_modules/iobroker.backitup","smb":"vers=2.0","sudo":false,"deleteOldBackup":true,"ownDir":true,"bkpType":"Minimal","dir":"/RaspiBackup/ioBrokerBackup_complete","dirMinimal":"/RaspiBackup/ioBrokerBackup_default","dirTotal":"/RaspiBackup/ioBrokerBackup_complete","user":"raspiXXX","pass":"****","backupDir":"/opt/iobroker/backups"}
[DEBUG] [mysql] - done
[EXIT] 0
[DEBUG] [mysql] - MySql File deleted!`

**Comment by simatec** [comment]
Das haben wir bereits gefixt. 
Sollte es nach einem backup nicht möglich sein, einen umount durchzuführen, da noch Dateien bearbeitet werden, wird beim nächsten ausführen eines backups vorher geprüft, und dann der umount durchgeführt ... die Meldung ist also zu ignorieren...

**Comment by kugelkopf123** [comment]
Das ist schade! Weil dadurch bis zum nächsten Morgen, wenn das nächste Backup angestoßen wird, mein NAS nicht in den Ruhezustand geht. Beim erstellen des neuen Backups unmounted er wieder nicht und das Spiel geht von vorne los.

**Comment by simatec** [comment]
Dann setze erwas zeitversetzt einen Neustart von backitup unter Instanzen. 
Somit wird backitup neu gestartet und der umount ausgeführt
