### ISSUE TITLE
Backup von deCONZ (Zigbee)

### ISSUE THREAD

**Issue by Mephisto090** [simatec/ioBroker.backitup#780]
Hallo,

Zigbee kann ja schon gesichert werden. Macht es sin ein Backup für deCONZ einzubauen?

**Comment by simatec** [comment]
Das Issue gab es schon. 
Deconz unterstützt dies leider nicht. 
geht am Ende nur über das Webif von Deconz

**Comment by Mephisto090** [comment]
Alles klar danke
