### ISSUE TITLE
backitup error or my fault?

### ISSUE THREAD

**Issue by DcFamas** [simatec/ioBroker.backitup#787]
Hey there,
I really don't get this failure:

`<html><body>

backitup.0 | 2022-11-03 02:00:35.382 | error | [iobroker/clean] Backup files not deleted from /opt/iobroker/backups because some errors.
-- | -- | -- | --
backitup.0 | 2022-11-03 02:00:34.621 | error | [iobroker/ftp] Error: /ioBroker/javascripts_2022_11_03-02_00_33_backupiobroker.tar.gz: Permission denied.
backitup.0 | 2022-11-03 02:00:34.614 | error | [iobroker/ftp] Error: /ioBroker/grafana_2022_11_03-02_00_28_backupiobroker.tar.gz: Permission denied.
backitup.0 | 2022-11-03 02:00:34.606 | error | [iobroker/ftp] Error: /ioBroker/zigbee.0_2022_11_03-02_00_27_backupiobroker.tar.gz: Permission denied.
backitup.0 | 2022-11-03 02:00:34.596 | error | [iobroker/ftp] Error: /ioBroker/iobroker_2022_11_03-02_00_20_backupiobroker.tar.gz: Permission denied.
backitup.0 | 2022-11-03 01:30:24.621 | error | [ccu/clean] Backup files not deleted from /opt/iobroker/backups because some errors.
backitup.0 | 2022-11-03 01:30:23.847 | error | [ccu/ftp] Error: /ioBroker/homematic_2022_11_03-01_30_21_3.65.6.20220723_backupiobroker.tar.sbk: Permission denied.

</body>
</html>`

Do I have some issues with my ftp server, or are the rights of the folder the problem? The ioBroker fixer.sh won't fix this permission.

Thank you and best regards :)

**Comment by simatec** [comment]
What are the user permissions in the backup folder?

`ls -lah /opt/iobroker/backups`

**Comment by DcFamas** [comment]
`root@ioBroker:/home/administrator# ls -lah /opt/iobroker/backups
insgesamt 28K
drwxrwxr-x+ 7 iobroker iobroker 4,0K 18. Okt 09:19 .
drwxrwxr-x+ 8 iobroker iobroker 4,0K 28. Okt 23:29 ..
drwxrwxr-x+ 2 iobroker iobroker 4,0K 18. Okt 09:19 Heizung
drwxrwxr-x+ 2 iobroker iobroker 4,0K 18. Okt 09:19 Kamera
drwxrwxr-x+ 5 iobroker iobroker 4,0K 18. Okt 09:19 scripte
drwxrwxr-x+ 6 iobroker iobroker 4,0K 18. Okt 09:20 scripts
drwxrwxr-x+ 2 iobroker iobroker 4,0K  7. Aug 2021  Uhrzeit
root@ioBroker:/home/administrator#`

The FTP is my FRITZ!Box, I use an own user "ftpuser" with these permissions:
![grafik](https://user-images.githubusercontent.com/35306967/199931194-3ca10bd1-0310-4887-b3a3-a3ea9aeac5bd.png)

########

I have found the failure. The folder /iobroker, which I configured in the instance wasn't created on the FRITZ!Box.
Sorry and thank you! :)
