### ISSUE TITLE
Grafana API Key replaced by Service Account

### ISSUE THREAD

**Issue by Panoru84** [simatec/ioBroker.backitup#788]
With Grafana v9.2.3 the **API key** is deprecated and replaced by  something called **Service Account**.
I couldn't figure out how to use this with Backitup
 
1. Update Grafana to latest version v9.2.3
2. Click on Configuration and check for Service Account

Can this already be used with backitup?

Information about Grafana Service Accounts:
https://grafana.com/docs/grafana/latest/administration/service-accounts/

Thanks for you help!

**Comment by simatec** [comment]
As far as I can understand now, the token is used.

There is a user here who has successfully tested this

https://forum.iobroker.net/post/872607

**Comment by Panoru84** [comment]
@simatec 
I think this issued is not yet solved.
Your link doesn't cover the new Service Account topic, isn't it about HTTPS?

**Comment by simatec** [comment]
The link also refers to the service account

**Comment by simatec** [comment]
<img width="1271" alt="Bildschirmfoto 2022-11-13 um 16 27 06" src="https://user-images.githubusercontent.com/39792461/201529755-d862d3c8-549c-48cb-b377-95f7f88103cb.png">

**Comment by Panoru84** [comment]
Sorry, I don't get it. 
Darf ich auf deutsch schreiben?
Ich hab gerade nochmal im Forum gelesen, aber da steht doch nicht welche Einstellungen man im ioBroker im Adapter machen muss, wenn Grafana auf ServiceAccount umgestellt ist oder?
Ich kann keinen API Key mehr erzeugen bei mir. Nur noch die Tokens, die oben auf deinem Screenshot sind.
Und wenn ich das Konzept richtig verstanden habe (das muss aber nicht sein) sind diese Tokens nicht direkt mit einem User verknüpft.
So oder so sehe ich Backitup Adaper nur "Grafana API-Key" und nicht ServiceAccount Token oder ähnliches.

Sorry wenn ich auf dem Schlauch stehe

**Comment by simatec** [comment]
Dafür habe ich dir doch den Screenshot gemacht. 
so wie zu sehen kannst du den Service Token erzeugen und diesen anstelle des Api Keys eintragen. 
In Backitup wird es in der nächsten Version eine Änderung Übersetzung geben

**Comment by SKB-CGN** [comment]
Hallo,
welche Version wird dies sein? 2.8.1 ist installiert.
Ich habe einen Service Account angelegt und bekomme dennoch folgenden Fehler:

```
[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
[ERROR] [grafana] - Error on Grafana Datasource Request
[ERROR] [grafana] - Error on Grafana Dashoard Request: AxiosError: Request failed with status code 401
[DEBUG] [grafana] - start Grafana backup compress ...
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[ERROR] [grafana] - cannot found Grafana Backup files
```

**Comment by simatec** [comment]
Es war nur eine Änderung der Übersetzung bzw. der Beschreibung des Token Menüs
Der Service-Token funktioniert. 
Bitte erzeuge einen Service-Token mit vollen Adminrechten und benutzte als User Admin und das dementsprechende Passwort.

https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch#grafana-backup
