### ISSUE TITLE
Google Drive token can not be restored

### ISSUE THREAD

**Issue by JanGehring** [simatec/ioBroker.backitup#789]
After the latest update I am not able to reactivate my Google Drive token.
I constantly get an error message if I try to do so:

{"error":"invalid_grant","error_description":"Bad Request"}

**Comment by simatec** [comment]
please follow the warnings when updating and create a new token.  Google had changes here.

**Comment by JanGehring** [comment]
There are no warnings and also deleting the old token on google and creating a complete new one will have the same result.

**Comment by simatec** [comment]
Backitup Version?

**Comment by JanGehring** [comment]
2.5.4

I tried again this morning - after about 15 tries yesterday and it worked this morning. Backup was created successfully. Thanks for your help.

**Comment by simatec** [comment]
> After the latest update I am not able to reactivate my Google Drive token. I constantly get an error message if I try to do so:
> 
> {"error":"invalid_grant","error_description":"Bad Request"}

Which version did this message come with?
Do you have a complete debug log?
