### ISSUE TITLE
GoogleDrive authorization not working with 2.5.4

### ISSUE THREAD

**Issue by Niko11111** [simatec/ioBroker.backitup#790]
After updating to 2.5.4 I needed to authorize again at GoogleDrive. After following the link in the backitup menue I granted the authorization. Then the Google Drive goes to a new page with only a long string of numbers and letters. If I reload this page it tells me "bad request". Backitup still shows me the link. Restarting iobroker does not help. If I click the backitup link again, Google Drive tells me, the the service already has access. So it looks like the authorization works on googles side, but backitup does not get the info. Did not do a new install of backitup.

**Comment by simatec** [comment]
You have to copy the long token shown on the page and paste it into the backup config.

**Comment by Niko11111** [comment]
@simatec Oh I am sorry to bother you with such a dump question. I did not see the text that says: "Enter token here..." Thank you. now it is working again
