### ISSUE TITLE
Grafana not work

### ISSUE THREAD

**Issue by pmaster555** [simatec/ioBroker.backitup#795]
[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is not available: Error: unable to verify the first certificate
[DEBUG] [grafana] - Grafana is not available!
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[DEBUG] [grafana] - Grafana Backup cannot created ...
[DEBUG] [grafana] - done

**Comment by simatec** [comment]
Please post your Config

**Comment by pmaster555** [comment]
grafana config? or ... ?

**Comment by pmaster555** [comment]
![изображение](https://user-images.githubusercontent.com/22826842/202236465-cec23bda-7fcb-4124-9425-7343f95502df.png)

im disable this and ok

**Comment by simatec** [comment]
That‘s ok…
