### ISSUE TITLE
Error "no Answer" after sending new Dropbox token

### ISSUE THREAD

**Issue by mibr85** [simatec/ioBroker.backitup#796]
**Describe the bug**  
Get an unspezified Error "no Answer" after sending a new Dropbox token.

**To Reproduce**  
1. Click Refresh dropbox Token
2. Click on the link and login to dropbox
3. copy and paste the token to ioBroker
4. click on Send
5. Error comes up

**Expected behavior**  
backups possible again to Drobbox

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/56867583/204120821-47323db5-8194-4817-82fb-6d1b514ab70c.png)
![grafik](https://user-images.githubusercontent.com/56867583/204120859-a5c6869b-280c-44ce-b67e-6e990225df8c.png)

**Versions:**  
 - Adapter version: v2.5.4
 - JS-Controller version: v4.0.15
 - Node version: v14.19.0
 - Operating system: Debian

**Additional context**

**Comment by simatec** [comment]
Please Test the last Version 2.5.6

**Comment by mibr85** [comment]
2.5.6 installed but same problem

**Comment by simatec** [comment]
I checked the whole thing. There is currently a problem with the Axios package. I hope the Axios developers will fix this soon

**Comment by simatec** [comment]
Please use v2.5.7

**Comment by mibr85** [comment]
Yessss. Perfect backup running again.
Thanks a lot for your quick response and solution
