### ISSUE TITLE
Adapter kann nicht von 2.5.6 auf 2.5.7 aktualisiert werden

### ISSUE THREAD

**Issue by Menne01** [simatec/ioBroker.backitup#799]
Moin,
der Adapter kann nicht von 2.5.6 auf 2.5.7 aktualisiert werden.

![grafik](https://user-images.githubusercontent.com/89869516/204258708-26639d01-2cb2-4ad3-bd14-b9bede3ffd27.png)

Es ist aber node.js 16.18.1 installiert.

![grafik](https://user-images.githubusercontent.com/89869516/204259107-aabe55b6-a0d9-44d2-adca-d0da9a905c20.png)

**Comment by simatec** [comment]
Zeige mal die Ausgabe von folgenden Befehlen.

`
node -v
nodejs -v
npm -v
`

**Comment by simatec** [comment]
Würde auf jeden Fall den Link setzen

**Comment by Menne01** [comment]
Nach dem hinzufügen des symbolischen Links geht es jetzt. Vieleicht sollte mal die Installations-Anleitung überarbeitet werden.
