### ISSUE TITLE
Benachrichtigung per Matrix

### ISSUE THREAD

**Issue by dontobi** [simatec/ioBroker.backitup#800]
**Is your feature request related to a problem? Please describe.**
Ich habe kürzlich den Matrix Adapter installiert. Leider wird dieser unter Benachrichtigung in den Backitup Einstellungen angeboten. 

**Describe the solution you'd like**
Unterstützung für den Matrix Adapter.

**Describe alternatives you've considered**
Keine

**Additional context**
[ioBroker.matrix-org](https://github.com/oelison/ioBroker.matrix-org)

**Comment by simatec** [comment]
Support for matrix-org comes in v.2.6.x

**Comment by dontobi** [comment]
Ich habe inzwischen die Version 2.6.2 am laufen und leider habe ich keine Benachrichtigung per Matrix bekommen. Das Backup wurde hingegen erstellt.

Ich gehe davon aus, dass die Ausführung des senTo noch angepasst werden muss. Hier ein Beispiel der Syntax:
```sendTo("telegram.0", "send", { text: 'Erinnerung: Morgen wird die gelbe Tonne geleert.' });
sendTo("matrix-org.0", "Erinnerung: Morgen wird die gelbe Tonne geleert.");
 sendTo("lovelace.0", "send", { title: "Erinnerung", message: "Morgen wird die gelbe Tonne geleert." });```

Wie man sehen kann nutzt lovelace und auch telegram eine ähnliche Syntax. Der Matrix Adpater hingegen verzichtet auf das "send". Ich vermute mal, dass es daran liegen wird.
