### ISSUE TITLE
YAHKA Restore funktioniert nicht

### ISSUE THREAD

**Issue by unstressable** [simatec/ioBroker.backitup#808]
Nachdem ich ein heute paar YAHKA Geräte hinzugefügt habe und das Backup von gestern eingespielt hab, sind die neuen Geräte noch immer da?

Backitup sagt mir aber, dass alles erfolgreich ist.

**Comment by simatec** [comment]
Kannst du bitte den Debuglog posten

**Comment by unstressable** [comment]
hier ist es:

`<html>
<body>


backitup.0 | 2022-12-04 16:35:56.022 | debug | [yahka] yahka.0 started
-- | -- | -- | --
backitup.0 | 2022-12-04 16:35:55.961 | debug | [yahka] Yahka Restore completed successfully
backitup.0 | 2022-12-04 16:35:55.960 | debug | [yahka] Yahka tmp directory was successfully deleted
backitup.0 | 2022-12-04 16:35:55.957 | debug | [yahka] Try deleting the Yahka tmp directory
backitup.0 | 2022-12-04 16:35:55.956 | debug | [yahka] Yahka Database is successfully restored
backitup.0 | 2022-12-04 16:35:52.679 | debug | [yahka] yahka.0 stopped
backitup.0 | 2022-12-04 16:35:52.652 | debug | [yahka] old Yahka database directory was successfully deleted
backitup.0 | 2022-12-04 16:35:52.631 | debug | [yahka] yahka tmp directory created: /opt/iobroker/backups/yahka_0.hapdata
backitup.0 | 2022-12-04 16:35:52.626 | debug | [yahka] Filename for Restore: /opt/iobroker/backups/yahka.0_2022_12_04-16_32_12_xyz_backupiobroker.tar.gz
backitup.0 | 2022-12-04 16:35:52.623 | debug | [yahka] Start Yahka Restore ...
backitup.0 | 2022-12-04 16:35:34.650 | debug | Backup list be read ...


</body>
</html>`

**Comment by unstressable** [comment]
Hatte zuvr ein Backup gemacht, danach in YAHKA ein gerät "Test" angelegt und das Backup wieder eingespielt.
Das Gerät "Test" ist nach wie vor da.

Im JavaScript Adapter ist das gleiche Problem.
Hier muss man zuvor erst den Spiegelordner löschen, oder ein Filesystem "Touch" machen. Dann hat es dort funktioniert.

**Comment by simatec** [comment]
Bitte die v2.5.9 testen

**Comment by unstressable** [comment]
gleiches Problem.
Nach dem Backup hinzugefügtes Testgerät ist nach Restore noch vorhanden.
Nach dem Backup verändertes altes Gerät bleibt nach Restore verändert und geht nicht auf Wert vor dem Backup zurück.

Getestet mit YAHKA, JavaScript kann ich aktuell nicht testen.
