### ISSUE TITLE
Modify CIFS mount options

### ISSUE THREAD

**Issue by Grothesk242** [simatec/ioBroker.backitup#819]
Please add mount options 
uid=iobroker,gid=iobroker 
for CIFS mounts. 
New mount command should look like this: 

```
sudo mount -t cifs -o username=iobroker,password=***,noserverino,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=3.1.1 //111.222.333.444/path/to/iobbackups /opt/iobroker/backups
```

This should avoid error messages like: 
Error: EPERM: operation not permitted, utime '/opt/iobroker/backups/zigbee_0/'
and also does not confuse users since the backup files now are owned by the familiar 'iobroker' and not 'root'.

**Comment by Grothesk242** [comment]
See PR 
https://github.com/simatec/ioBroker.backitup/pull/820

**Comment by simatec** [comment]
v2.5.10
