### ISSUE TITLE
Update von 2.5.4 auf 2.5.9 funktioniert nicht 

### ISSUE THREAD

**Issue by Xerxes55** [simatec/ioBroker.backitup#822]
Keine Fehler in der logfile
**Logfiles**  

$ iobroker upgrade backitup@2.5.9
host.raspberrypi Adapter "system.adapter.backitup.0" is stopped.
Installing iobroker.backitup@2.5.9... (System call)
upload [19] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/adapter-settings.js adapter-settings.js application/javascript
upload [14] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/es/translations.json i18n/es/translations.json application/json
upload [13] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
upload [12] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/it/translations.json i18n/it/translations.json application/json
upload [11] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
upload [10] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
upload [9] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
upload [8] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
upload [7] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/index.html index.html text/html
upload [6] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/index_m.html index_m.html text/html
upload [5] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/index_m.js index_m.js application/javascript
upload [4] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/style.css style.css text/css
upload [3] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/tab_m.css tab_m.css text/css
upload [2] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/tab_m.html tab_m.html text/html
upload [1] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/tab_m.js tab_m.js application/javascript
upload [0] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/words.js words.js application/javascript
host.raspberrypi Adapter "system.adapter.backitup.0" is started
Process exited with code 0

**Versions:**  
 - Adapter version: 2.5.4
 - JS-Controller version: 4.0.23
 - Node version: v12.22.8
 - Operating system: Linux buster

**Comment by simatec** [comment]
Ich würde mal das System komplett neustarten und im Anschluss noch einmal versuchen.

**Comment by Xerxes55** [comment]
Ich habe schon Raspi und Adapter neu gestartet, ohne Erfolg.

**Comment by simatec** [comment]
Hast du über Konsole versucht zu updaten?

**Comment by Xerxes55** [comment]
Gerade durchgeführt, kein Erfolg!

**Comment by simatec** [comment]
Bitte poste die Konsolenausgabe

**Comment by Xerxes55** [comment]
pi@raspberrypi:~ $ iob stop
pi@raspberrypi:~ $ iob update
No connection to databases possible ...
pi@raspberrypi:~ $ sudo iob update
Used repository: stable
Adapter    "admin"        : 6.3.3    , installed 6.3.3
Adapter    "alexa2"       : 3.23.2   , installed 3.23.2
Adapter    "backitup"     : 2.5.9    , installed 2.5.4  [Updatable]
Adapter    "discovery"    : 3.1.0    , installed 3.1.0
Adapter    "fb-checkpresence": 1.1.20, installed 1.1.20
Adapter    "fhem"         : 1.6.3    , installed 1.6.3
Adapter    "heatingcontrol": 2.9.3   , installed 2.9.3
Adapter    "icons-material-png": 0.1.0, installed 0.1.0
Adapter    "info"         : 1.9.19   , installed 1.9.19
Adapter    "iot"          : 1.11.9   , installed 1.11.9
Adapter    "iqontrol"     : 2.0.0    , installed 2.0.0
Adapter    "javascript"   : 6.0.3    , installed 6.0.3
Controller "js-controller": 4.0.23   , installed 4.0.23
Adapter    "scenes"       : 2.3.9    , installed 2.3.9
Adapter    "simple-api"   : 2.7.0    , installed 2.7.0
Adapter    "socketio"     : 4.2.0    , installed 4.2.0
Adapter    "terminal"     : 0.2.6    , installed 0.2.6
Adapter    "tr-064"       : 4.2.16   , installed 4.2.16
Adapter    "vis"          : 1.4.15   , installed 1.4.15
Adapter    "web"          : 4.3.0    , installed 4.3.0
Adapter    "whatsapp-cmb" : 0.2.2    , installed 0.2.2
Adapter    "ws"           : 1.3.0    , installed 1.3.0
Adapter    "yahka"        : 0.13.1   , installed 0.14.0
Adapter    "zigbee"       : 1.7.6    , installed 1.7.6
pi@raspberrypi:~ $ sudo iob upgrade self
Host    "raspberrypi"    is up to date.
pi@raspberrypi:~ $ sudo iob upgrade

This upgrade of "backitup" will introduce the following changes:
==========================================================================
-> 2.5.9:
dependencies dropbox-v2-api updated
Fix Zigbee Restore
Fix Yahka Restore
Fix Javascript Restore
Fix Dropbox Error Messages

-> 2.5.8:
Fix iobroker Backup
dependencies updated

-> 2.5.7:
Axios 1.1.3 added
Added ukrainian language

-> 2.5.6:
Fix Grafana Backup
Fix Downloadserver
Translation updated

-> 2.5.5:
Design Fix
Docker DB Support added
==========================================================================

Would you like to upgrade backitup from @2.5.4 to @2.5.9 now? [(y)es, (n)o]: y
Update backitup from @2.5.4 to @2.5.9
host.raspberrypi Adapter "system.adapter.backitup.0" is stopped.
NPM version: 6.14.15
Installing iobroker.backitup@2.5.9... (System call)
upload [19] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/adapter-settings.js adapter-settings.js application/javascript
upload [18] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/backitup.png backitup.png image/png
upload [17] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/backitup.svg backitup.svg image/svg+xml
upload [16] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/de/translations.json i18n/de/translations.json application/json
upload [15] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/en/translations.json i18n/en/translations.json application/json
upload [14] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/es/translations.json i18n/es/translations.json application/json
upload [13] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
upload [12] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/it/translations.json i18n/it/translations.json application/json
upload [11] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
upload [10] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
upload [9] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
upload [8] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
upload [7] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/index.html index.html text/html
upload [6] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/index_m.html index_m.html text/html
upload [5] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/index_m.js index_m.js application/javascript
upload [4] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/style.css style.css text/css
upload [3] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/tab_m.css tab_m.css text/css
upload [2] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/tab_m.html tab_m.html text/html
upload [1] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/tab_m.js tab_m.js application/javascript
upload [0] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/words.js words.js application/javascript
host.raspberrypi Adapter "system.adapter.backitup.0" is started

**Comment by simatec** [comment]
Man führt kein sudo aus.
Da schein dann an deinem System generell etwas nicht in Ordnung zu sein.
Mache mal folgendes:

`iob stop`
`iob fix`
`sudo reboot now`

Und lasse bei allen iob Befehlen das sudo weg

Des Weiteren würde ich node updaten. Node12 ist so gut wie End of Life
Debian Buster ist auch End of Life. Auch hier bitte auf Bullseye upgraden

**Comment by Xerxes55** [comment]
Auch nach dem fix und reboot keine Änderung.

**Comment by simatec** [comment]
Dann würde ich wirklich mal dein System komplett updaten und auf Stand bringen.
Aktuell wurde die v2.5.9 über 14.000 mal installiert.
Das Problem liegt also nicht an der Version, sondern an deinem System.

**Comment by Xerxes55** [comment]
ok, verstanden. Danke für die Hilfe. Vor solchen updates habe ich etwas Angst. Meistens geht da was schief. Bin kein Linux Profi.

**Comment by simatec** [comment]
Nimm am einfachsten eine neue SD und flashe die aktuelle Version.
Im Anschluss kannst du mit einer Befehlszeile iobroker mit allen Abhängigkeiten installieren.

Backup einspielen und alles läuft wieder.
Der Aufwand sind nur 10-15 Minuten und du hast zur Sicherheit noch immer die alte SD.

**Comment by Xerxes55** [comment]
Habe das komplette System aktualisiert auch Backitup ist jetzt ok. Noch mal danke!

**Comment by simatec** [comment]
Done
