### ISSUE TITLE
Fehler in Telegram-Nachricht

### ISSUE THREAD

**Issue by lonisgree** [simatec/ioBroker.backitup#823]
Moin,
wenn der Adapter eine Telegram-Nachricht absendet, hat der Text ein paar Fehler anstatt:

_BackItUp:
Eine neue iobroker  Sicherung wurde am 21. Dezember 2022 um 02:00 Uhr erstellt, und in Google Drive gespeichert._

muss es sein:

_BackItUp:
Eine neue ioBroker-Sicherung wurde am 21. Dezember 2022 um 02:00 Uhr erstellt und in Google Drive gespeichert._

sein. Es wäre toll, wenn man diesen Fehler beheben könnte. Ist ja höchstwahrscheinlich nur ein Übersetzungsfehler.

LG LonisGree

**Comment by simatec** [comment]
Du kannst dich gerne auf der Weblate Plattform bei den Übersetzungen beteiligen
https://weblate.iobroker.net/projects/adapters/backitup/
