### ISSUE TITLE
Thema Onedrive Integration "reakitivieren"

### ISSUE THREAD

**Issue by tecfreakz** [simatec/ioBroker.backitup#825]
Moin zusammen,

inzwischen gibt's in npm OneDrive seit über einem Jahr offiziell supportet, siehe https://www.npmjs.com/package/onedrive-api.

Es kamen auch immer wieder mal Fragen in den letzten 2 Jahren auf, ob backitup das als Festure bekommen kann.

Könnte man das Thema "reaktivieren"?

Interesse meinerseits besteht auch ;-)

Alter Thread, der aufgrund damals noch fehlendem support von OneDrive in npm geschlossen wurde: https://github.com/simatec/ioBroker.backitup/issues/249

**Comment by firebowl** [comment]
Ich würde auch darum bitten. Hab gerade mal zum Testen auf einem openmedivault die Verbindung zu Onedrive aktiviert. Klkappt recht problemlos. Wäre echt cool wenn man seine Sicherungen direkt im Onedrive ablegen könnte.

**Comment by simatec** [comment]
Ich hatte es schon mehrfach erklärt, dass es mit der API und dem npm Paket alleine nicht getan ist. Hier muss bei Microsoft ne APP registriert werden und eine aufwendige Authentifizierung programmiert werden.

Also wie bereits geschrieben, ist das ein sehr großer Aufwand und ihr vergesst bei allem Respekt bei euren Forderungen immer wieder, dass wir das hier alles in unserer Freizeit entwickeln und die User leider nur fordern fordern fordern ...

Mal ein kleines Beispiel.... Backitup nutzen ca. 60.000 User, aber mal ne Spende für die Mühe und Arbeit, die ein Entwickler hat, kommt von einer Handvoll an Usern ....

**Comment by firebowl** [comment]
Finde es befremdlich das auf eine freundliche Anfrage so eine pissige Antwort kommt.
So bringt man Nutzer bestimmt dazu mal etwas zu spenden.

**Comment by simatec** [comment]
Es ist keine wie du sie nennst „pissige“ Antwort. 
Ich habe lediglich nochmal erklärt, dass eine Implementierung nicht so ohne weiteres möglich ist. Man benötigt einiges mehr als ein npm Paket. 

Da ich das schon mehrmals hier geschrieben habe, musste ich halt mal die Blumen weglassen 😉

**Comment by firebowl** [comment]
Dann kam das bei mir vielleicht falsch an. ;)

Ich ging auch davon aus, dass man bestehende Implementierungen [wie](https://github.com/abraunegg/onedrive) nutzen kann. Ich wusste nicht das Du die Authentifizierung neu machen oder eine eigene App einreichen musst.

**Comment by simatec** [comment]
Nein leider kann man da nix nutzen. 
Es ist schon sehr aufwändig und benötigt für die Authorisierung einen Server und ein Redirct URL. 

Ich habe diese mühevollen Prozesse bereits bei Dropbox und GDrive durch. 

Selbst die App registrieren ist eein Wochenlanger, teilweise monatelanger Prozess, bis dann die Freigabe von Microsoft dann kommt. 

Ich versuche mit den User Wünschen immer schnell und zeitnahe zu reagieren, aber beim Thema Onedrive ist es wirklich nicht so einfach. 

Ich werde mal mit @GermanBluefox reden, ob wir über die Server von iobroker eine Authorisierung aufbauen können. 

Aber selbst dann wird es einige Zeit in Anspruch nehmen. 
Hier muss man schauen, wie es zeitlich sich da entwickelt

**Comment by tecfreakz** [comment]
Nabend!

Na hier ist ja was los. Ich hatte nicht die Absicht eine Art bashing zu starten.

Um das klar zu stellen und dringend hervor zu heben:

Ich weiß durchaus Wert zu schätzen, dass die Software hier ehrenamtlich entwickelt und supported wird. Ganz großen Respekt dafür! Donates sind durchaus angebracht! Der iobroker mit backitup ist ein wahnsinnig mächtiges und vielseitiges Tool für's smarthome. Kommerziell wäre so ein Teil unbezahlbar für jeden, insofern bitte größten Respekt für jede Sekunde Entwicklungsarbeit, die hier jemand reinsteckt! Es passiert aus Leidenschaft und eigenem Antrieb von Menschen, die Bock darauf haben und gerne teilen, nicht aus kommerzielle Gründen, das darf bitte niemand vergessen!

Ich habe das Thema bei mir inzwischen mit rclone auf nem ubuntu lxc Container auf proxmox gelöst, der mir onedrive auf ein volume spiegelt und gecached backups hochlädt. Via Samba greife ich mit backitup drauf zu und das funktioniert auch echt super.

Ist denke aber das ist nicht für jeden machbar. Viele haben den iobroker auf nem raspberry oder noch schwächerer Hardware laufen und haben keinen Schimmer von proxmox und sind überhaupt froh, wenn sie die linux console möglichst wenig bis gar nicht sehen müssen 😂

Insofern... Nice to have. Wie viel Spende würde es Kosten? Ich hätte auch Bier und Grill anzubieten in der Nähe von Hamburg 😜

**Comment by simatec** [comment]
Es würde nichts kosten, denn wir machen das hier alle aus Spaß an der Freude und nicht des Geldes wegen. 
Es war lediglich ein kleiner Denkanstoß nicht immer nur zu fordern, sondern auch mal tiefer hinter die Kulissen zu schauen. 
sowohl aus Sicht der freiwilligen Entwickler, als auch mal tiefer sich so ein Thema mit der Onedrive Api anzuschauen. 
Wenn man sich bei npm das Paket angeschaut hätte und sich damit auseinandersetzen würde, hätte man gesehen, dass man damit wunderbar Down- und Upload machen kann… aber wo kommt der Token her? Wie geht funktioniert die Schnittstelle zur Cloud? Wie erhält man den Refreshtoken? Gibt es eine App bei Microsoft Azure? Was muss die App können? 

Genau das wollte ich damit anstoßen. 

Es ist nicht mal eben in 10 Minuten und auch nicht in 10 Stunden gemacht.

**Comment by simatec** [comment]
So ich habe jetzt 2 Tage dran gesessen und eine Schnittstelle gebaut, damit man sich mit der Onedrive Cloud connecten kann. 

Die Doku ist extrem bescheiden und Fehlerhaft. 
Ein Upload funktioniert schonmal in meinem Testumgebungen. 

Die ganze Api von Onedrive ist aber weiterhin mist

**Comment by simatec** [comment]
Nein Nürnberg oder Hamburg sind eher selten meine Ecke ;-)

**Comment by tecfreakz** [comment]
Na gut 😉 ich hab Mal 30€ Donate da gelassen! Dafür müssten ein paar Bier und ne gute Currywurst gehen 🤏

Ganz großes Dankeschön nochmal dafür, wirklich Klasse und es bringt schlussendlich ja vielen hier was!

Ich bin aber ehrlich gesagt etwas geschockt, wie wenig backitup vom iobroker nutzen. Entweder hat der iobroker nicht so viele Nutzer, die meisten haben eigene viel bessere Backup Lösungen (was ich stark anzweifeln würde) oder viele fahren schlicht keine Backups.

Mir ist mal der Pi abgeraucht und ich hatte es auch schon, dass ein paar Updates das PiOS zerschossen haben. Mittlerweile läuft es aus proxmox, aber auch da kann immer was Passieren. Da ist man schon froh, wenn man relativ wenig Aufwand einfach restoren kann

**Comment by simatec** [comment]
Vielen Dank für deine Spende ...
Wie meinst du das mit wenig Leute nutzen Backitup?
Ich finde es sind recht viele Leute, die den Adapter inzwischen zur Sicherung ihrer ioBroker Installation nutzen.
Hier mal ein paar Zahlen...

Stand heute gibt es 77.739 ioBroker Installationen und im Verhältnis dagegen Stand heute 58.401 Installationen von Backitup.

Du hast schon recht, dass Onedrive sicher sinnvoll ist, da dies viel von Usern genutzt wird.
Trotzdem bleibe ich dabei... Die API ist nicht wirklich gut im Vergleich zu Google oder Dropbox und die Doku zur API ist ne Katastrophe ...

Habe ca. 10-15 Stunden nur damit verbracht, eine Anmeldung und Token-Austausch zum laufen zu bekommen.
Das ist dann im gesamten Prozess mit Upload, Download, löschen und list nur ein sehr kleiner Teil der eigentlichen Integrierung.

Genau aus dem Grund war ich kein Freund der Integration... Habe das schon ne lange Zeit verfolgt und war nie so richtig überzeugt ... Halt Microsoft ...

**Comment by simatec** [comment]
Function comes in v.2.6.x

**Comment by tecfreakz** [comment]
Hi zusammen,

mal ein Feedback nach 3 Jahren: OneDrive läuft absolut stabil und problemlos bei mir im iobroker. Vielen Dank noch mal für die Erweiterung im BackItUp Adapter!

Grüße :)
