### ISSUE TITLE
Old backup don't get deleted if transfer of one failed

### ISSUE THREAD

**Issue by Standarduser** [simatec/ioBroker.backitup#829]
BackItUp is configured to backup
* ioBroker
* Homematic CCU
* Javascript
* InfluxDB
* Grafana
* Yahka
and to push them to dropbox.

The InfluxDB backup got too large to transfer it to Dropbox (allowed size seems to be between 311,4MB and 315,9MB).

While the Homematic backup worked fine all the time (5 backups available locally and on Dropbox as configured), all the others were in the correct number on Dropbox (the last 5 as configured) but weren't deleted locally, even if just the transfer of one backup failed.

In my opinion, all backups that ran correctly and were transferred should only be kept locally in the set amount, and the backup where the transfer failed also to prevent the hard disk / sd card from being written to capacity.

**Comment by simatec** [comment]
this is intentional... if an error occurs during the backup process, it will not be deleted.  

Solution quite clear ... fix errors

**Comment by simatec** [comment]
An error with incorrect folder permissions does not occur out of nowhere. 
When I set up Backitup, I should also check the settings here and see if everything is running correctly.

The philosophy will not change. If an error occurs, it will not be deleted. 

Better an old backup than none
