### ISSUE TITLE
 [Featurerequest] Backup Archiv Protection

### ISSUE THREAD

**Issue by vr6syncro** [simatec/ioBroker.backitup#83]
Moin,

wäre es möglich das Backup beim Packen direkt zu verschlüsseln?
Auch die Wiederherstellung  dann nur mit Passwort?

**Comment by simatec** [comment]
Schauen wir uns mal an. 
Die Frage ist nur, wofür das zwingend benötigt wird

**Comment by vr6syncro** [comment]
Zwingend benötigt nein. Allerdings enthalten die Backups Login/Private - Daten. Von daher sollte man von der Seite vorsichtig mit dem Backup umgehen.

Nun gut ein Hacker hat die gepackte Datei schnell gecrackt aber falls die Datei in sonstige Hände gerät muss ja nicht jeder gleich alle Daten vom SmartHome haben.
