### ISSUE TITLE
Google Drive: Error: Unknown system error -116: Unknown system error -116

### ISSUE THREAD

**Issue by Fladinator666** [simatec/ioBroker.backitup#830]
Hab schon eine Weile ein Problem mit den Backitup Adapter. NAS (CIFS) alleine funktioniert. Google Drive alleine funktioniert. Wenn ich aber beides zusammen machen möchte kommt immer der Fehler vom Google Drive. Der Ordner wird in Google Drive erstellt. Ist aber leer.

Versions:
 - Adapter version: 2.5.9
 - JS-Controller version: 4.0.23
 - Node version: v16.18.1
 - Operating system: linux

![backup neu](https://user-images.githubusercontent.com/55363702/210287620-7c8b1f0b-b545-408c-9c72-2a2a72036b31.PNG)

**Comment by simatec** [comment]
Die NAS Option „noserverino“ muss aktiv sein und smb bitte auf 3.1.1 stellen

**Comment by Fladinator666** [comment]
@simatec Danke so funktioniert es und kommt kein Fehler mehr.
