### ISSUE TITLE
Backitup löscht alte Backups nicht, warum?

### ISSUE THREAD

**Issue by LK1976** [simatec/ioBroker.backitup#836]
Ich habe in Backitup eingestellt, dass nur eine Sicherung vorgehalten werden soll. Warum werden dann die alten Sicherungen nicht gelöscht?

![grafik](https://user-images.githubusercontent.com/121298651/211153672-00a52839-6c2e-455f-9877-b296cf07d478.png)

Der Debug-Log siehgt wie folgt aus:

Started iobroker ...
[DEBUG] [iobroker] start with {"type":"creator","workDir":"/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js","time":"02:40","debugging":true,"slaveBackup":"Single","everyXDays":"1","deleteBackupAfter":0,"ftp":{"enabled":true,"type":"storage","source":"local","host":"lkro1976.selfhost.eu","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/FRITZ/ioBrocker","dirMinimal":"/backupDir/iobroker","user":"internet","pass":"****","port":"21","ignoreErrors":false},"ignoreErrors":false,"dir":"/opt/iobroker","yahka":{"enabled":true,"type":"creator","ftp":{"enabled":true,"type":"storage","source":"local","host":"lkro1976.selfhost.eu","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/FRITZ/ioBrocker","dirMinimal":"/backupDir/iobroker","user":"internet","pass":"****","port":"21","ignoreErrors":false},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":"local","mount":"","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=3.1.1","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"sharename/backupDir","dirMinimal":"sharename/backupDir","user":"","pass":"****","ignoreErrors":false},"dropbox":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessToken":"****","dropboxAccessJson":"","dropboxTokenType":"custom","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"webdav":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","signedCertificates":true,"ignoreErrors":false},"googledrive":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"newToken":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false,"accessJson":"****"},"path":"/opt/iobroker/iobroker-data","nameSuffix":"","slaveSuffix":"","hostType":"Single","ignoreErrors":false},"javascripts":{"enabled":true,"type":"creator","ftp":{"enabled":true,"type":"storage","source":"local","host":"lkro1976.selfhost.eu","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/FRITZ/ioBrocker","dirMinimal":"/backupDir/iobroker","user":"internet","pass":"****","port":"21","ignoreErrors":false},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":"local","mount":"","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=3.1.1","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"sharename/backupDir","dirMinimal":"sharename/backupDir","user":"","pass":"****","ignoreErrors":false},"dropbox":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessToken":"****","dropboxAccessJson":"","dropboxTokenType":"custom","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"webdav":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","signedCertificates":true,"ignoreErrors":false},"googledrive":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"newToken":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false,"accessJson":"****"},"slaveSuffix":"","hostType":"Single","nameSuffix":"","ignoreErrors":false},"historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"none","onlyError":false,"telegramWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"pushover.0","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"whatsapp-cmb.0","NoticeType":"shortWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"signal":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"","NoticeType":"longSignalNotice","onlyError":false,"signalWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [iobroker] - host.iobroker 2695 states saved

[DEBUG] [iobroker] - host.iobroker 3216 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2023_01_07-14_41_15_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [javascripts] - Created javascript_tmp directory: "/opt/iobroker/backups/tmpScripts"
[DEBUG] [javascripts] - found Script: An-_und_Abwesenheitserkennung_über_TR-064-Adapter
[DEBUG] [javascripts] - found Script: Zeitschaltuhr_gsicilia82
[DEBUG] [javascripts] - found Script: Zeitschaltuhr_Pittini
[DEBUG] [javascripts] - found Script: Zeitcluster__Stunden__unter_JAVASCRIPT_anlegen
[DEBUG] [javascripts] - found Script: Zeitcluster__Stunden__unter_JAVASCRIPT_jede_volle_Stunde_aktualisieren
[DEBUG] [javascripts] - found Script: Steckdose_abends_einschalten
[DEBUG] [javascripts] - found Script: Steckdose_je_Anwesenheitsstatus_abends_einschalten
[DEBUG] [javascripts] - found Script: Steckdose_je_Anwesenheitsstatus_abends_ausschalten
[DEBUG] [javascripts] - found Script: Steckdose_abends_ausschalten
[DEBUG] [javascripts] - Try deleting the Javascript tmp directory: "/opt/iobroker/backups/tmpScripts"
[DEBUG] [javascripts] - Javascript tmp directory "/opt/iobroker/backups/tmpScripts" successfully deleted
[DEBUG] [javascripts] - Backup created: /opt/iobroker/backups/javascripts_2023_01_07-14_41_26_backupiobroker.tar.gz
[DEBUG] [javascripts] - done
[DEBUG] [yahka] - found yahka database: yahka.0
[DEBUG] [yahka] - done
[DEBUG] [ftp] start with {"type":"storage","source":"local","host":"lkro1976.selfhost.eu","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/FRITZ/ioBrocker","dirMinimal":"/backupDir/iobroker","user":"internet","pass":"****","port":"21","ignoreErrors":false,"deleteBackupAfter":0}
[DEBUG] [ftp] - FTP connected.
[DEBUG] [ftp] - Send iobroker_2023_01_07-14_41_15_backupiobroker.tar.gz
[DEBUG] [ftp] - Send javascripts_2023_01_07-14_41_26_backupiobroker.tar.gz
[DEBUG] [ftp] - Send yahka.0_2023_01_07-14_41_26_backupiobroker.tar.gz
[DEBUG] [ftp] - done
[DEBUG] [clean] - done
[DEBUG] [whatsapp] - [iobroker] used WhatsApp-Instance: whatsapp-cmb.0
[DEBUG] [whatsapp] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [whatsapp] start with {"type":"creator","workDir":"/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js","time":"02:40","debugging":true,"slaveBackup":"Single","everyXDays":"1","deleteBackupAfter":0,"ftp":{"enabled":true,"type":"storage","source":"local","host":"lkro1976.selfhost.eu","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/FRITZ/ioBrocker","dirMinimal":"/backupDir/iobroker","user":"internet","pass":"****","port":"21","ignoreErrors":false},"ignoreErrors":false,"dir":"/opt/iobroker","yahka":{"enabled":true,"type":"creator","ftp":{"enabled":true,"type":"storage","source":"local","host":"lkro1976.selfhost.eu","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/FRITZ/ioBrocker","dirMinimal":"/backupDir/iobroker","user":"internet","pass":"****","port":"21","ignoreErrors":false},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":"local","mount":"","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=3.1.1","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"sharename/backupDir","dirMinimal":"sharename/backupDir","user":"","pass":"****","ignoreErrors":false},"dropbox":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessToken":"****","dropboxAccessJson":"","dropboxTokenType":"custom","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"webdav":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","signedCertificates":true,"ignoreErrors":false},"googledrive":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"newToken":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false,"accessJson":"****"},"path":"/opt/iobroker/iobroker-data","nameSuffix":"","slaveSuffix":"","hostType":"Single","ignoreErrors":false},"javascripts":{"enabled":true,"type":"creator","ftp":{"enabled":true,"type":"storage","source":"local","host":"lkro1976.selfhost.eu","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/FRITZ/ioBrocker","dirMinimal":"/backupDir/iobroker","user":"internet","pass":"****","port":"21","ignoreErrors":false},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":"local","mount":"","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=3.1.1","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"sharename/backupDir","dirMinimal":"sharename/backupDir","user":"","pass":"****","ignoreErrors":false},"dropbox":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessToken":"****","dropboxAccessJson":"","dropboxTokenType":"custom","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"webdav":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","signedCertificates":true,"ignoreErrors":false},"googledrive":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"newToken":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false,"accessJson":"****"},"slaveSuffix":"","hostType":"Single","nameSuffix":"","ignoreErrors":false},"historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"none","onlyError":false,"telegramWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"pushover.0","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"whatsapp-cmb.0","NoticeType":"shortWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de","time":"07. Januar 2023 um 14:41 Uhr"},"signal":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"","NoticeType":"longSignalNotice","onlyError":false,"signalWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"backupDir":"/opt/iobroker/backups","influxDBEvents":[],"mySqlEvents":[],"pgSqlEvents":[]}
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[DEBUG] [historyHTML] start with {"type":"creator","workDir":"/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js","time":"02:40","debugging":true,"slaveBackup":"Single","everyXDays":"1","deleteBackupAfter":0,"ftp":{"enabled":true,"type":"storage","source":"local","host":"lkro1976.selfhost.eu","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/FRITZ/ioBrocker","dirMinimal":"/backupDir/iobroker","user":"internet","pass":"****","port":"21","ignoreErrors":false},"ignoreErrors":false,"dir":"/opt/iobroker","yahka":{"enabled":true,"type":"creator","ftp":{"enabled":true,"type":"storage","source":"local","host":"lkro1976.selfhost.eu","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/FRITZ/ioBrocker","dirMinimal":"/backupDir/iobroker","user":"internet","pass":"****","port":"21","ignoreErrors":false},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":"local","mount":"","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=3.1.1","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"sharename/backupDir","dirMinimal":"sharename/backupDir","user":"","pass":"****","ignoreErrors":false},"dropbox":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessToken":"****","dropboxAccessJson":"","dropboxTokenType":"custom","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"webdav":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","signedCertificates":true,"ignoreErrors":false},"googledrive":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"newToken":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false,"accessJson":"****"},"path":"/opt/iobroker/iobroker-data","nameSuffix":"","slaveSuffix":"","hostType":"Single","ignoreErrors":false},"javascripts":{"enabled":true,"type":"creator","ftp":{"enabled":true,"type":"storage","source":"local","host":"lkro1976.selfhost.eu","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/FRITZ/ioBrocker","dirMinimal":"/backupDir/iobroker","user":"internet","pass":"****","port":"21","ignoreErrors":false},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":"local","mount":"","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=3.1.1","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"sharename/backupDir","dirMinimal":"sharename/backupDir","user":"","pass":"****","ignoreErrors":false},"dropbox":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessToken":"****","dropboxAccessJson":"","dropboxTokenType":"custom","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"webdav":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","signedCertificates":true,"ignoreErrors":false},"googledrive":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"newToken":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false,"accessJson":"****"},"slaveSuffix":"","hostType":"Single","nameSuffix":"","ignoreErrors":false},"historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de","time":"07. Januar 2023 um 14:41 Uhr"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"none","onlyError":false,"telegramWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"pushover.0","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"whatsapp-cmb.0","NoticeType":"shortWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"signal":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"","NoticeType":"longSignalNotice","onlyError":false,"signalWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"backupDir":"/opt/iobroker/backups","influxDBEvents":[],"mySqlEvents":[],"pgSqlEvents":[]}
[DEBUG] [historyJSON] start with {"type":"creator","workDir":"/opt/iobroker/node_modules/iobroker.js-controller/iobroker.js","time":"02:40","debugging":true,"slaveBackup":"Single","everyXDays":"1","deleteBackupAfter":0,"ftp":{"enabled":true,"type":"storage","source":"local","host":"lkro1976.selfhost.eu","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/FRITZ/ioBrocker","dirMinimal":"/backupDir/iobroker","user":"internet","pass":"****","port":"21","ignoreErrors":false},"ignoreErrors":false,"dir":"/opt/iobroker","yahka":{"enabled":true,"type":"creator","ftp":{"enabled":true,"type":"storage","source":"local","host":"lkro1976.selfhost.eu","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/FRITZ/ioBrocker","dirMinimal":"/backupDir/iobroker","user":"internet","pass":"****","port":"21","ignoreErrors":false},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":"local","mount":"","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=3.1.1","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"sharename/backupDir","dirMinimal":"sharename/backupDir","user":"","pass":"****","ignoreErrors":false},"dropbox":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessToken":"****","dropboxAccessJson":"","dropboxTokenType":"custom","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"webdav":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","signedCertificates":true,"ignoreErrors":false},"googledrive":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"newToken":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false,"accessJson":"****"},"path":"/opt/iobroker/iobroker-data","nameSuffix":"","slaveSuffix":"","hostType":"Single","ignoreErrors":false},"javascripts":{"enabled":true,"type":"creator","ftp":{"enabled":true,"type":"storage","source":"local","host":"lkro1976.selfhost.eu","debugging":true,"deleteOldBackup":true,"ownDir":false,"dir":"/FRITZ/ioBrocker","dirMinimal":"/backupDir/iobroker","user":"internet","pass":"****","port":"21","ignoreErrors":false},"cifs":{"enabled":false,"mountType":"NFS","type":"storage","source":"local","mount":"","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=3.1.1","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":false,"ownDir":false,"dir":"sharename/backupDir","dirMinimal":"sharename/backupDir","user":"","pass":"****","ignoreErrors":false},"dropbox":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"accessToken":"****","dropboxAccessJson":"","dropboxTokenType":"custom","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false},"webdav":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"username":"username","pass":"****","url":"https://example.com/remote.php/dav/files/username/","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","signedCertificates":true,"ignoreErrors":false},"googledrive":{"enabled":false,"type":"storage","source":"local","debugging":true,"deleteOldBackup":false,"newToken":false,"ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","ignoreErrors":false,"accessJson":"****"},"slaveSuffix":"","hostType":"Single","nameSuffix":"","ignoreErrors":false},"historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de","time":"07. Januar 2023 um 14:41 Uhr"},"telegram":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"none","onlyError":false,"telegramWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"pushover.0","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"whatsapp-cmb.0","NoticeType":"shortWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"signal":{"enabled":true,"notificationsType":"WhatsApp","type":"message","instance":"","NoticeType":"longSignalNotice","onlyError":false,"signalWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"backupDir":"/opt/iobroker/backups","influxDBEvents":[],"mySqlEvents":[],"pgSqlEvents":[]}
[EXIT] 0

Dennoch sind die alten Backups nach wie vor vorhanden?!

![grafik](https://user-images.githubusercontent.com/121298651/211153751-214e51c1-0982-4ef4-bfd2-684a9b5c0274.png)

Auffällig ist auch, dass trotz FTP Backup die lokalen Backups erhalten bleiben. Soll (muss) das so sein? Ich hätte erwartet, dass wenn nach FTP gesichert wird, kein lokales Backup weggeschrieben wird.

**Comment by simatec** [comment]
Backups werden grundsätzlich nur bei einem automatischen Backup gelöscht. 
Bei manuellen Backups wird nie gelöscht. 

Wenn du die veraltete FTP Methode verwendest, wird lokal und zusätzlich auf dem FTP Server gespeichert. 

Grundsätzlich würde ich aber an deiner Stelle dein Backup Konzept überdenken. Lediglich 1 Backup vorzuhalten kann dir irgendwann zum Verhängnis werden.

**Comment by LK1976** [comment]
OK, Danke und verstanden. Das ist nur ein Backup vorhalte, war nur zu Testzwecken. Letztendlich sind mehrere Backups vorzuhalten natürlich sinnvoller. Du sagst, dass FTP eine veraltete Methode ist. Welche Methode würdest Du mir denn empfehlen, wenn ich auf die FRITZ!Box sichern möchte?

**Comment by simatec** [comment]
Fritzbox würde CIFS das sinnvollste sein. 
Für die Fritzbox mit aktuellen OS die Option Noserverino aktivieren und smb 3.1.1 auswählen.

**Comment by LK1976** [comment]
Vielen Dank für Deine Unterstützung. Ich habe es nun bei mir umgestellt!
