### ISSUE TITLE
Pushover Prio

### ISSUE THREAD

**Issue by Baenker** [simatec/ioBroker.backitup#837]
Ich nutze die Option das Backitup mir eine Pushover schickt wenn ein Backup erstellt wird. Ich lasse automatisch wöchentlich ein Backup um 2 Uhr Nachts erstellen.

des Weiteren nutze ich Pushover für viele wichtige Informationen im Haus. Z. B. Nachts Bewegung wo keine sein soll oder Wassereinbruch wo keiner sein soll. Dafür habe ich mein Nachtfokus beim iPhone so eingestellt das Pushover immer durch kommt. Von den Piep werde ich somit wach und kann nach dem rechten sehen. Gott sei Dank bisher weder das eine noch das andere erlebt.

Bei unwichtigen Sachen die mir per Pushover nachts geschickt werden habe ich deshalb ein Prio von -1 vorgegeben. Das bewirkt das Pushover still ist aber ein Badge in der App zeigt. Ich nutze dafür bei mir einen Hausstatus (wenn alle schlafen und Info unwichtig Priorität -1 sonst Prio so lassen wie sie ist)

Backitup verschickt sein "Backup erstellt" aber entweder ohne Prio oder mit einer höheren Priorität. Das heißt mein iPhone macht laut "piep". Somit raubt Backup mir meinen Schlaf :-)

Ich fände es gut wenn man die Prioritäten vorgeben könnte beim Backup. Richtig cool wäre wenn man sagen könnte von Uhrzeit x bis y Priorität z außerhalb der Zeit Priorität a

**Comment by simatec** [comment]
Du kannst in den Einstellung von Backitup die "stille Benachrichtigung" aktivieren und wirst somit Nachts nicht mehr geweckt

**Comment by Baenker** [comment]
Ich habe es aktiviert. Vielen Dank für die Erklärung und natürlich Danke für den Adaoter
