### ISSUE TITLE
NAS / Copy - CIFS - SMBv2

### ISSUE THREAD

**Issue by cm86** [simatec/ioBroker.backitup#84]
Hallo,
ich habe das Problem, das sich das sich das Mount Verzeichnis nicht korrekt mounted.
Wenn ich es per SSH manuell Mounte kommt auch ein File an.
Also vor ausführen des Backups

Hier mal das Debug-Log. 
`Gestartet...
[DEBUG] [mount] start with {"mountType":"CIFS","type":"storage","source":"Local","mount":"10.0.0.89","fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","smb":"vers=2.0","sudo":true,"deleteOldBackup":true,"ownDir":false,"bkpType":"Minimal","dir":"/3TB01/Programme/Linux/iobroker/","dirMinimal":"sharename/backupDir","dirTotal":"sharename/backupDir","user":"Administrator","pass":"****"}
[ERROR] [mount] - [undefined sudo: no tty present and no askpass program specified

[ERROR] [mount] - [IGNORED] Error: Command failed: sudo mount -t cifs -o username=Administrator,password="xxxxxxxx",rw,file_mode=0777,dir_mode=0777 //10.0.0.89/3TB01/Programme/Linux/iobroker/ /opt/iobroker/backups
sudo: no tty present and no askpass program specified

[DEBUG] [minimal] start with {"type":"creator","time":"02:00","debugging":true,"everyXDays":"1","deleteBackupAfter":0,"mysqlEnabled":false,"redisEnabled":false,"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"Local","mount":"//10.0.0.89","fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","smb":"vers=2.0","sudo":true,"deleteOldBackup":true,"ownDir":false,"bkpType":"Minimal","dir":"/3TB01/Programme/Linux/iobroker/","dirMinimal":"sharename/backupDir","dirTotal":"sharename/backupDir","user":"Administrator","pass":"****","context":{"fileNames":[],"errors":{},"done":[],"types":[]},"adapter":null},"dir":"/opt/iobroker","redis":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"Local","host":"","deleteOldBackup":false,"ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal","dirTotal":"/backupDir/total","user":"","pass":"","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"Local","mount":"10.0.0.89","fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","smb":"vers=2.0","sudo":true,"deleteOldBackup":true,"ownDir":false,"bkpType":"Minimal","dir":"/3TB01/Programme/Linux/iobroker/","dirMinimal":"sharename/backupDir","dirTotal":"sharename/backupDir","user":"Administrator","pass":"\"xxxxxxxx\""},"dropbox":{"enabled":false,"type":"storage","source":"Local","deleteOldBackup":false,"accessToken":"","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal","dirTotal":"/backupDir/total"},"path":"/var/lib/redis"},"history":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":null,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [minimal] - Backup created: /opt/iobroker/backups/minimal_2019_01_04-23_25_07_backupiobroker.tar.gz

[DEBUG] [minimal] - done
[DEBUG] [cifs] start with {"mountType":"CIFS","type":"storage","source":"Local","mount":"//10.0.0.89","fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","smb":"vers=2.0","sudo":true,"deleteOldBackup":true,"ownDir":false,"bkpType":"Minimal","dir":"/3TB01/Programme/Linux/iobroker/","dirMinimal":"sharename/backupDir","dirTotal":"sharename/backupDir","user":"Administrator","pass":"****","backupDir":"/opt/iobroker/backups","deleteBackupAfter":0}
[DEBUG] [cifs] - done
[DEBUG] [clean] start with {"deleteBackupAfter":0}
[DEBUG] [clean] - done
[DEBUG] [telegram] start with {"type":"creator","time":"02:00","debugging":true,"everyXDays":"1","deleteBackupAfter":0,"mysqlEnabled":false,"redisEnabled":false,"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"Local","mount":"//10.0.0.89","fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","smb":"vers=2.0","sudo":true,"deleteOldBackup":true,"ownDir":false,"bkpType":"Minimal","dir":"/3TB01/Programme/Linux/iobroker/","dirMinimal":"sharename/backupDir","dirTotal":"sharename/backupDir","user":"Administrator","pass":"****","context":{"fileNames":["/opt/iobroker/backups/minimal_2019_01_04-23_25_07_backupiobroker.tar.gz"],"errors":{},"done":["minimal"],"types":["minimal"]},"adapter":null},"dir":"/opt/iobroker","redis":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"Local","host":"","deleteOldBackup":false,"ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal","dirTotal":"/backupDir/total","user":"","pass":"","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"Local","mount":"10.0.0.89","fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","smb":"vers=2.0","sudo":true,"deleteOldBackup":true,"ownDir":false,"bkpType":"Minimal","dir":"/3TB01/Programme/Linux/iobroker/","dirMinimal":"sharename/backupDir","dirTotal":"sharename/backupDir","user":"Administrator","pass":"\"xxxxxxxx\""},"dropbox":{"enabled":false,"type":"storage","source":"Local","deleteOldBackup":false,"accessToken":"","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal","dirTotal":"/backupDir/total"},"path":"/var/lib/redis"},"history":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":null,"systemLang":"de","time":"04. Januar 2019 um 23:25 Uhr"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [telegram] - [minimal] used Telegram-Instance: telegram.0
[DEBUG] [telegram] - done
[DEBUG] [history] start with {"type":"creator","time":"02:00","debugging":true,"everyXDays":"1","deleteBackupAfter":0,"mysqlEnabled":false,"redisEnabled":false,"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"Local","mount":"//10.0.0.89","fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","smb":"vers=2.0","sudo":true,"deleteOldBackup":true,"ownDir":false,"bkpType":"Minimal","dir":"/3TB01/Programme/Linux/iobroker/","dirMinimal":"sharename/backupDir","dirTotal":"sharename/backupDir","user":"Administrator","pass":"****","context":{"fileNames":["/opt/iobroker/backups/minimal_2019_01_04-23_25_07_backupiobroker.tar.gz"],"errors":{},"done":["minimal"],"types":["minimal"]},"adapter":null},"dir":"/opt/iobroker","redis":{"enabled":false,"type":"creator","ftp":{"enabled":false,"type":"storage","source":"Local","host":"","deleteOldBackup":false,"ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal","dirTotal":"/backupDir/total","user":"","pass":"","port":"21"},"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"Local","mount":"10.0.0.89","fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","smb":"vers=2.0","sudo":true,"deleteOldBackup":true,"ownDir":false,"bkpType":"Minimal","dir":"/3TB01/Programme/Linux/iobroker/","dirMinimal":"sharename/backupDir","dirTotal":"sharename/backupDir","user":"Administrator","pass":"\"xxxxxxxx\""},"dropbox":{"enabled":false,"type":"storage","source":"Local","deleteOldBackup":false,"accessToken":"","ownDir":false,"bkpType":"Minimal","dir":"/backupDir","dirMinimal":"/backupDir/minimal","dirTotal":"/backupDir/total"},"path":"/var/lib/redis"},"history":{"enabled":true,"type":"message","entriesNumber":"25","systemLang":"de","time":"04. Januar 2019 um 23:25 Uhr"},"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":null,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","systemLang":"de"},"backupDir":"/opt/iobroker/backups"}
[DEBUG] [history] - done
[DEBUG] [umount] start with {"mountType":"CIFS","type":"storage","source":"Local","mount":"//10.0.0.89","fileDir":"/opt/iobroker/node_modules/iobroker.backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","smb":"vers=2.0","sudo":true,"deleteOldBackup":true,"ownDir":false,"bkpType":"Minimal","dir":"/3TB01/Programme/Linux/iobroker/","dirMinimal":"sharename/backupDir","dirTotal":"sharename/backupDir","user":"Administrator","pass":"****","backupDir":"/opt/iobroker/backups"}`

Des Weiteren ist mir aufgefallen, dass bei Passwörtern mit Sonderzeichen keine "Gänsefüßchen" gesetzt werden.
Dies führt auch zu Fehlern.
--> WorkAround ist die Gänsefüßchen mit in die Passwortzeile häckeln
--> Passwort: Kennwort1? --> Passwort: "Kennwort1?"

**Comment by simatec** [comment]
Bitte im Forum lesen ... Dein sudo verlangt beim Aufruf das root Passwort ...
Deshalb die Fehlermeldung. 

Im Forum gibt es Lösungen, wie du mit sudo ohne Passwortabfrage arbeiten kannst

**Comment by cm86** [comment]
Ok thx. schon gelöst...
