### ISSUE TITLE
IQontrol Integration in die zu sichernden Komponenten

### ISSUE THREAD

**Issue by Elektrickser** [simatec/ioBroker.backitup#846]
Da mittlerweile die Nutzer von IQontrol mittlerweile stetig mehr werden und die Backup-Lösung vom Adapter, mit Download und Upload, eher umständlich zu sichern ist, könnte eine Integration in den Backup-Adapter einen Vorteil für viele Anwender schaffen.

**Comment by simatec** [comment]
IQontrol wird doch im iobroker Backup gesichert?

**Comment by Elektrickser** [comment]
NA dann hab ich nix gesagt. 
Ich hab bis jetzt immer das Backup manuell im Adapter von Iqontrol gemacht und die JSON-Datei heruntergeladen. Musste aber auch noch nicht auf ein Backup zurückgreifen. 
Da ich im Backup-Adapter keine Option von I-Qontrol gefunden habe, ging ich davon aus, dass dies nicht gesichert wird.
