### ISSUE TITLE
Keine Backup Datei von iobrocker beim Manuellen Sichern

### ISSUE THREAD

**Issue by heitec11** [simatec/ioBroker.backitup#847]
Beim Manuellen Backup: "Jetzt sichern" wird keine Backup Datei vom iobrocker angelegt.
Von den anderen ausgewählten Komponten hingegen schon.
Beim Automatischen Backup funktionert es und im Verzeichnis sind die entsprechenden letzten Dateien.

Auszug aus dem Log:

Started iobroker ...
[DEBUG] [iobroker] - host.raspberrypi 4353 states saved
[DEBUG] [iobroker] - host.raspberrypi 4997 objects saved
[DEBUG] [iobroker] - done
[DEBUG] [influxDB] - InfluxDB-Backup started ...
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Backup created: /opt/iobroker/backups/influxDB_2023_01_21-18_22_50_backupiobroker.tar.gz

[DEBUG] [webdav] - Start WebDAV Upload ...
[ERROR] [webdav] - WebDAV: File "/opt/iobroker/backups/iobroker_2023_01_21-18_22_40_backupiobroker.tar.gz" not found
[DEBUG] [webdav] - WebDAV: Copy influxDB_2023_01_21-18_22_50_backupiobroker.tar.gz...

**Comment by simatec** [comment]
Stelle mal die Instanz auf debug und schaue was im Log steht. 
Hast du einen iobroker fix mal durchlaufen lassen?
Ist dein iob System up2date?

**Comment by heitec11** [comment]
Mit Debug funktioniert es.
Anschließend noch mal im Info Modus, aber dann kommt wieder die Meldung:
[iobroker/webdav] WebDAV: File "/opt/iobroker/backups/iobroker_2023_01_23-15_41_04_backupiobroker.tar.gz" not found

und die Datei ist wirklich nicht da....
