### ISSUE TITLE
Zigbee2mqtt database 

### ISSUE THREAD

**Issue by DutchmanNL** [simatec/ioBroker.backitup#848]
As we have a native Integration now for zigbee2mqtt https://github.com/o0shojo0o/ioBroker.zigbee2mqtt it would be cool , like for grafana, to have the possibility to backup the zigbee2mqtt configuration + database by cifs/nfs or local folder location

happy to discuss in Discord @simatec @o0shojo0o ☺️

**Comment by simatec** [comment]
Do you have some information for me what to look for and how to backup?

**Comment by DutchmanNL** [comment]
> Do you have some information for me what to look for and how to backup?

it depends on implementation, in most cases zigbee2mqtt runs in an separated docker container.
Directory contains these files:

configuration.yaml
coordinator_backup.json
database.db
log
state.json

My suggestion would be to just specify a file path (or in generic allow specific file paths to be used)
In my situation I would mount the zigbee volume into the docker of iobroker directly, others my want to use cifs/nfs for that purpose

**Comment by simatec** [comment]
Comes in v2.6.x
