### ISSUE TITLE
Allow database backups also in docker environment

### ISSUE THREAD

**Issue by DutchmanNL** [simatec/ioBroker.backitup#849]
Currently capability for backup of influxDB, MySql etc is disabled if ioBroker runs in an docker environment.
For me this makes no sense, I would like to use backitup to backup my remote located influxDB

BackitUp perfectly supports that, but option is disabled because it runs in docker.
Please provide capability, also for docker hosted setups, to make database backups

**Comment by buanet** [comment]
If you run the official Docker image, please read the docs.
If you build your own, simply place the following file inside your container to make the optional available:
`/opt/scripts/.docker_config/.backitup`

Regards,
André

**Comment by simatec** [comment]
Support for Docker is included. 
Please read the Docker Docu

**Comment by DutchmanNL** [comment]
> If you run the official Docker image, please read the docs. If you build your own, simply place the following file inside your container to make the options available: `/opt/scripts/.docker_config/.backitup`

A great, thought I read the docu but missed this part 😔

> 
> If you want to know why we did this, let's discuss it on discord. :)
> 
> Regards, André

I can imagine 😂😂😂
