### ISSUE TITLE
Upload file to Dropbox more than 150 Mb

### ISSUE THREAD

**Issue by XHunter74** [simatec/ioBroker.backitup#854]
Could you split backup archive to parts to avoid Dropbox limitations? For example by 100 Mb. Actually, it is a standard feature of zip.

**Comment by simatec** [comment]
As far as I know, this is only possible for buisiness accounts

**Comment by XHunter74** [comment]
I meant something different. Currently I organized backup of Postgres db to Dropbox in the next way: I am archiving .pgsql using next command: zip -s 100m $filename_zip $filename and then upload files to Dropbox without any issues.

**Comment by simatec** [comment]
OK I'm talking about an upload session here.
Splitting a backup is not an option for an iobroker backup

**Comment by XHunter74** [comment]
Why? I am uploading files in one session and Dropbox processes it correctly. You should use batch upload feature of dropbox-v2-api package.

**Comment by simatec** [comment]
this is about the restore.  The js controller expects a backup file in tar.gz and no individual zip files.  it does not work that way

**Comment by XHunter74** [comment]
Easier to convert archives to the proper format than to lose all data in one 'perfect' day. I discovered suddenly that my database was not reserved after three months when size of the file grow. We can't force users to buy premium Dropbox subscription but can resolve the issue in another way.

**Comment by simatec** [comment]
I'll take a look at that when I get a chance

**Comment by simatec** [comment]
The structure of Backitup does not give an option to split zip's.
This means that a zip file is no longer recognized in the restore and a restore is no longer possible.

If files are larger than 150 MB, I recommend to look for alternatives to Dropbox.

OneDrive support comes as of v2.6.x
Furthermore options like GoogleDrive, WebDav (Nextcloud) would be possible.

Another option is to rent a storage box from Hetzner for little money.
There you can upload your data via CIFS, WebDav etc. without size limit.

Splitting into single zips will not be supported by Backitup.

**Comment by XHunter74** [comment]
_'OneDrive support comes as of v2.6.x'_ - sounds good!

**Comment by simatec** [comment]
Dropbox file upload up to 350 GB added in v.2.6.6
