### ISSUE TITLE
Influxdb im anderen Docker

### ISSUE THREAD

**Issue by lolax80** [simatec/ioBroker.backitup#855]
Hallo,

ich habe den iobroker, grafana und und influxdb in verschiedenen Container laufen.
Leider funktioniert das Backup von influxdb v1.x nicht.

Ich bitte um Hilfe

`[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory
[DEBUG] [influxDB] - InfluxDB tmp directory was successfully deleted
[DEBUG] [influxDB] - 
[ERROR] [influxDB] - Error: Command failed: influxd backup -portable -database iobroker -host 192.168.69.2:8086 "/opt/iobroker/backups/influxDB_2023_02_04-19_59_07_backupiobroker"
/bin/sh: 1: influxd: not found`

**Comment by simatec** [comment]
Steht im Log… influxd ist nicht installiert. 
Schaue mal in der Doku von Backitup und in der Doku vom Docker Container

**Comment by buanet** [comment]
Das hier ist nicht der Ort für Support. Doku gibt es hier: https://docs.buanet.de/iobroker-docker-image/docs/#backup
Bei Fragen steht die Community (Forum, Discord, Facebook, Telegram) zur Verfügung.
@simatec Aus meiner Sicht ist der Issue zu schließen.

MfG,
André
