### ISSUE TITLE
Always errors during influxdb backup

### ISSUE THREAD

**Issue by homecineplexx** [simatec/ioBroker.backitup#856]
ich hab in der Backitup Instanz unter InfluxDb auf "Detect Config" geklickt und dann ein Backup versucht, dabei kommt immer dieser Fehler. Was mach ich da falsch?

das ist meine Influxdb-Instanz:
![image](https://user-images.githubusercontent.com/43374575/217169237-8f6d427d-904d-4e83-af58-952d1c47e13a.png)

in /etc/influxdb/influxdb.conf hab ich folgendes eingetragen
bind-address = "192.168.1.7:8088"

`
backitup.0 | 2023-02-07 07:13:44.789 | error | [iobroker] Error: Command failed: influxd backup -portable -database iobroker -host 192.168.1.7:8086 "/opt/iobroker/backups/influxDB_2023_02_07-07_13_44_iobroker_backupiobroker" /bin/sh: 1: influxd: not found
-- | -- | -- | --
backitup.0 | 2023-02-07 07:13:44.787 | error | [iobroker/influxDB] /bin/sh: 1: influxd: not found
backitup.0 | 2023-02-07 07:13:44.784 | error | [iobroker/influxDB] Error: Command failed: influxd backup -portable -database iobroker -host 192.168.1.7:8086 "/opt/iobroker/backups/influxDB_2023_02_07-07_13_44_iobroker_backupiobroker"
`

**Comment by simatec** [comment]
Wenn du eine Remoteverbindung zu deiner Influxdb hast, muss auf dem ioBroker System der influx Client laufen.
https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch#abh%C3%A4ngigkeiten

**Comment by homecineplexx** [comment]
und das brauch ich nur für das Backup??
sonst hab ich das ja auch nicht

**Comment by simatec** [comment]
Ja genau … influxd wird für das Backup benötigt

**Comment by homecineplexx** [comment]
und wie oder was genau muss ich da auf meinem iobroker host installieren?

**Comment by simatec** [comment]
Steht doch alles in der Doku

`sudo apt update && sudo apt install influxdb

sudo service influxdb start `

**Comment by homecineplexx** [comment]
super, das hat wirklich funktioniert....du bist mein held!!!!!
GROSSES DANKE auch für die Entwicklung
