### ISSUE TITLE
mounting cifs fails if password contains "'"

### ISSUE THREAD

**Issue by kscholty** [simatec/ioBroker.backitup#859]
**Describe the bug**  
I try to backup to a cifs drive. The password contains `'` The mount command fails with 
`/bin/sh: 1: Syntax error: Unterminated quoted string`

**To Reproduce**  
1. Configure a NAS/COPY backup for a CIFS drive.
2. Use a password containing `'`
4. Run the backup and check the output. 

**Expected behavior**  
The drive can be mounted for backup

**Screenshots & Logfiles**  
Outtput looks like this (username has been replaced by xxxxxxx)
```
Started iobroker ...
[DEBUG] [mount] - noserverino option: false
[DEBUG] [mount] - cifs-mount command: "mount -t cifs -o username=xxxxxxx,password=****,domain=WORKGROUP,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=3.1.1 //openmediavault/backupiobroker /opt/iobroker/backups"
[DEBUG] [mount] - first mount attempt with smb option failed. try next mount attempt without smb option ...
[DEBUG] [mount] - cifs-mount command: "mount -t cifs -o username=xxxxxxx,password=****,domain=WORKGROUP,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //openmediavault/backupiobroker /opt/iobroker/backups"
[ERROR] [mount] - [undefined Error: Command failed: mount -t cifs -o username=xxxxxxx,password=****,domain=WORKGROUP,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //openmediavault/backupiobroker /opt/iobroker/backups
/bin/sh: 1: Syntax error: Unterminated quoted string

[ERROR] [mount] - Error: Command failed: mount -t cifs -o username=xxxxxxx,password=****,domain=WORKGROUP,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //openmediavault/backupiobroker /opt/iobroker/backups
/bin/sh: 1: Syntax error: Unterminated quoted string

```

**Versions:**  
 - Adapter version: 2.5.12
 - JS-Controller version: 4.0.24 
 - Node version: v14.21.2 
 - Operating system:  Ubuntu 22.04.1 LTS (jammy)

**Additional context**  
I can mount the drive from the console using exactly the command  shown in the error screen but with a properly quoted password.

**Comment by simatec** [comment]
if your password has special characters, save it in quotation marks in Backup.  Your password shouldn't be that long.

**Comment by kscholty** [comment]
That does not work. Was of course the first thing I tried.
Let's assume the password is  Pass'Word

Using Pass'Word fails with "Syntax error: Unterminated quoted string"
Using "Pass'Word" same result "Syntax error: Unterminated quoted string"
Using Pass\'Word, same result "Syntax error: Unterminated quoted string"
Using Pass''Word, permission denied

Which type of quotes to you have in mind?

**Comment by simatec** [comment]
You can test on a cli. 
Passwords with special characters can cause problems in the Linux CLI. 
 you can try `password` in the cli

**Comment by simatec** [comment]
Please test the current Github-Version
