### ISSUE TITLE
IoBroker backup not found

### ISSUE THREAD

**Issue by DeckardCain2014** [simatec/ioBroker.backitup#863]
I noticed recently only the zigbee backups are saved to my Google Drive. The ioBroker backup itself is missing. 
Here is my debug log:
`Started iobroker ...
[DEBUG] [iobroker] - host.iobroker-pi 8311 states saved

[DEBUG] [iobroker] - host.iobroker-pi 9615 objects saved

[DEBUG] [iobroker] - done
[DEBUG] [zigbee] - found zigbee database: zigbee.0,zigbee.1
[DEBUG] [zigbee] - done
[ERROR] [googledrive] - Google Drive: File "/opt/iobroker/backups/iobroker_2023_02_15-13_27_48_backupiobroker.tar.gz" not found
[DEBUG] [googledrive] - Google Drive: Copy zigbee.0_2023_02_15-13_28_04_backupiobroker.tar.gz...
[DEBUG] [googledrive] - Google Drive: Copy zigbee.1_2023_02_15-13_28_05_backupiobroker.tar.gz...
[DEBUG] [googledrive] - done
[DEBUG] [clean] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[EXIT] 0`

**Comment by simatec** [comment]
Your System is not OK. Please post the Output from cli with `iobroker backup`

**Comment by DeckardCain2014** [comment]
host.iobroker-pi 8311 states saved
host.iobroker-pi 9615 objects saved
/usr/bin/iobroker: line 8: 15788 Killed                  node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js "$@"

**Comment by DeckardCain2014** [comment]
ok thanks!
