### ISSUE TITLE
no dropbox backup and telegram notification if FTP backup doesn't work

### ISSUE THREAD

**Issue by Diginix** [simatec/ioBroker.backitup#868]
For some days my FTP server was down and in this time backitup doesn't create any other external backup (dropbox) and I didn't receive any notification about that problem.
The log each time contains:
```
2023-02-18 05:30:27.143 - error: backitup.0 (265609) [iobroker/ftp] Error: connect ECONNREFUSED 192.168.2.13:21
2023-02-18 05:30:27.150 - error: backitup.0 (265609) [iobroker] Error: connect ECONNREFUSED 192.168.2.13:21
```
I would had thought that this setting should inform me about such problems:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/39678667/219952487-0bc5c20d-d14a-454a-848a-7af1e54a958c.png">

adapter: 2.6.0
nodejs: 16.19.1
js-controller: 4.0.24

**Comment by simatec** [comment]
Please post the complete debuglog from the backup process

**Comment by Diginix** [comment]
For this I would have to kill my FTP again and start manually a backup. This is no option atm.
I will keep it in mind, but should be reproducible for everyone with an unreachable FTP target.
