### ISSUE TITLE
SQLite3 backup not working

### ISSUE THREAD

**Issue by jroegner** [simatec/ioBroker.backitup#871]
**Describe the bug**  
SQLite3 is checked as part of the backup. In the SQLITE3 tab the config is read b the sql.0 instance. 
After the backup the log says:
_[iobroker] error on backup process: Error when executing script "sqlite": ReferenceError: adapter is not defined Please check the config of backitup and execute "iobroker fix"_
Full path and fix installations script makes no change

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/66469064/220676906-bf3fa95a-80e9-47e3-8016-656ab53036b4.png)

**Versions:**  
 - Adapter version: 2.6.1
 - JS-Controller version: 4.0.24
 - Node version: 16.19.1
 - Operating system: Raspbian GNU/Linux 10 (buster)

**Comment by simatec** [comment]
Fix in v2.6.2
