### ISSUE TITLE
update of adpater not possible due to missing node version

### ISSUE THREAD

**Issue by github-ps1304** [simatec/ioBroker.backitup#878]
**Describe the bug**  
An update 2.6.4 is available for backitup adapter - Update is not showing a node version even though I have version 16.19.1 installed.

**To Reproduce**  
1. Go to adapter view
2. Click on 'Update backitup adapter.'
3. See error: node (>=12.0.0):

**Expected behavior**  
update adapter to newest version.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 2.6.3
 - JS-Controller version: 4.0.24
 - Node version: 16.19.1
 - Operating system: Ubuntu Server 22.04 LTS
![backitup-error](https://user-images.githubusercontent.com/79707394/221504466-448362e7-0f88-47c1-817d-012b5c9b7a62.png)

**Comment by simatec** [comment]
This is not a problem from the adapter. The adapter only specifies the node version.
The verification takes place elsewhere.

Please show the output of:

```
node - v
nodejs -v
npm -v
```

**Comment by github-ps1304** [comment]
node -v
v16.19.1
npm -v
8.19.3
nodejs -v
Command 'nodejs' not found, but can be installed with:
sudo apt install nodejs

should I simply run the install command?

**Comment by github-ps1304** [comment]
after trying the instal command I did receive the followeing message:
nodejs ist schon die neueste Version (16.19.1-deb-1nodesource1).

**Comment by simatec** [comment]
Please link your node binary to nodejs

**Comment by github-ps1304** [comment]
dou you have instructions or hints how to do that? thanks

**Comment by simatec** [comment]
Please show the output of:

`which node && which nodejs`

**Comment by github-ps1304** [comment]
which node && which nodejs
/usr/bin/node

**Comment by simatec** [comment]
`sudo ln -s /usr/bin/node /usr/bin/nodejs`

**Comment by github-ps1304** [comment]
TX - very helpful !!!

**Comment by github-ps1304** [comment]
great support - TX

**Comment by simatec** [comment]
https://github.com/sponsors/simatec ;-)
