### ISSUE TITLE
Kommentarfeld für Sicherungen

### ISSUE THREAD

**Issue by Charlie-2222** [simatec/ioBroker.backitup#886]
Sowohl bei der manuellen Sicherung als auch nachträglich, bei automatischen Sicherungen würde ich mir ein Kommentarfeld wünschen.
Hier könnten Informationnen zum Backup wie zum Beispiel 
"vor Ändferung xxx" oder
"vor update  xxx" oder
"..."
eingetragen werden.
So kann eine Sicherung für eine eventuell nötigen Fehleranalyse einfacher wieder gefunden werden.

**Comment by simatec** [comment]
Und wo soll das eingetragen werden? Du drückst einen Button oder es wird automatisch nach Zeit gestartet… 

verstehe den Sinn darin ehrlich gesagt nicht

**Comment by simatec** [comment]
Im Tab "iobroker" hast du die Möglichkeit einen Namenszusatz zu definieren.
Aber alles andere macht kein Sinn.
Da muss du schon selber deine Kommentare dann erweitern, wenn du es benötigst.

**Comment by Charlie-2222** [comment]
...war nur eine Idee, die automatischen Sicherungen im Nachhinein (im Restore Dialog) mit einem Kommentar zu versehen, und bestenfalls mit einem Flag von der automatischen Löschung auzunehmen. (eine Sicherung war "old school" immer mit einem Kommentar versehen wenn man sie aus dem Kreislauf genommen, oder aus speziellen Gründen erstellt hat)

Natürlich kann ich auch im ioBroker Tab den Sicherungsnamen ändern und eine weitere Sicherung anstoßen, oder die Sicherung auf File Ebene umbenennen und den Kommentar im Notepad pflegen.

Ich kann verstehen, wenn andere Themen als wichiger eingestuft werden.
btw...  Danke für den sehr hilfreichen Backup Adapter, denn ich privat frei nutzen darf !

**Comment by simatec** [comment]
Meine Antwort war auch nicht bös gemeint... Es ist halt einfach so, dass bei 60.000 Nutzern jeder so seine Vorstellungen und Wünsche hat, die teilweise halt einfach zu speziell sind und nicht den Weg in den Adapter finden können.

Hier sind schon sehr sehr viele Wünsche eingeflossen und ja ich bin ehrlich .... teilweise zu viel.
Am Ende muss man eine gesunde Mischung zwischen Funktionsumfang und Bedienerfreundlichkeit schaffen
