### ISSUE TITLE
Nach Update Kein Start mehr

### ISSUE THREAD

**Issue by quorle** [simatec/ioBroker.backitup#89]
Hallo, ich habe heute folgendes geupdatet:

1. Den JS-Controller auf 1.5.3
2. Den Backitup-Adapter auf 1.0.2

Jetzt startet der Adapter nicht mehr. Habe den Adapter mal debug gestellt und hier steht folgendes im Log:

`

backitup.0 | 2019-01-06 12:56:59.850 | info | terminating
-- | -- | -- | --
backitup.0 | 2019-01-06 12:56:59.347 | error | at tryOnImmediate (timers.js:768:5)
backitup.0 | 2019-01-06 12:56:59.347 | error | at runCallback (timers.js:814:20)
backitup.0 | 2019-01-06 12:56:59.347 | error | at Immediate.createInstancesObjects [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:830:13)
backitup.0 | 2019-01-06 12:56:59.347 | error | at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:869:54)
backitup.0 | 2019-01-06 12:56:59.347 | error | at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5290:18)
backitup.0 | 2019-01-06 12:56:59.347 | error | at Adapter.emit (events.js:208:7)
backitup.0 | 2019-01-06 12:56:59.347 | error | at emitNone (events.js:106:13)
backitup.0 | 2019-01-06 12:56:59.347 | error | at Adapter.main (/opt/iobroker/node_modules/iobroker.backitup/main.js:555:5)
backitup.0 | 2019-01-06 12:56:59.347 | error | at createBashScripts (/opt/iobroker/node_modules/iobroker.backitup/main.js:489:16)
backitup.0 | 2019-01-06 12:56:59.347 | error | at Object.fs.unlinkSync (fs.js:1061:18)
backitup.0 | 2019-01-06 12:56:59.347 | error | Error: ENOENT: no such file or directory, unlink '/opt/iobroker/node_modules/iobroker.backitup/lib/stopIOB.sh'
backitup.0 | 2019-01-06 12:56:59.347 | error | uncaught exception: ENOENT: no such file or directory, unlink '/opt/iobroker/node_modules/iobroker.backitup/lib/stopIOB.sh'
backitup.0 | 2019-01-06 12:56:59.331 | info | starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.backitup, node: v8.15.0

`

**Comment by simatec** [comment]
War ein Bug in der Version 1.0.2. 
bitte auf Version 1.0.3 via github updaten. 
(Oben über den Button mit der Katze in dem Adapter Tab)
