### ISSUE TITLE
Start backitup via bash  

### ISSUE THREAD

**Issue by JM2014** [simatec/ioBroker.backitup#893]
Hi, 
is it possible (and supported) to start backitup via bash?
I am using the iobroker under a normal linux system and would like to automate the backup.
By using a bash script which can be started via SSH I would win more flexibility. 

Thankyou
Juergen

**Comment by simatec** [comment]
Backitup is already automated.
For this, you can simply set a time in the menu of Backitup when the BAckup should be executed.

Alternatively, you can of course also trigger a manual backup via a script.

For this you have to control the object "backitup.0.oneClick.iobroker", which would be possible e.g. from a bash script via http-request.

Please note that Backitup will consider this as a manual backup and will not delete old backups automatically.

Translated with www.DeepL.com/Translator (free version)

**Comment by JM2014** [comment]
Thankyou for the quick response.
