### ISSUE TITLE
CIFS Mount funktionier nicht

### ISSUE THREAD

**Issue by libertyx82** [simatec/ioBroker.backitup#90]
Ich erhalte in der Konsole des iobroker immer folgenden Fehler

``[ERROR] [mount] - [IGNORED] Error: Command failed: sudo mount -t cifs -o username=xx,password=xxxxx,rw,file_mode=0777,dir_mode=0777 //192.168.2.251/Backup/IoBroker/backups /opt/iobroker/backups``

Gebe ich das gleich per SSH ein
`sudo mount -t cifs -o username=xx,password=xxxxx,rw,file_mode=0777,dir_mode=0777 //192.168.2.251/Backup/IoBroker/backups /opt/iobroker/backups`
Funktioniert es.

**Comment by simatec** [comment]
Musst du per Konsole dann das root Passwort eingeben?

**Comment by libertyx82** [comment]
Oooh ja klar, aber ohne sudo geht es nicht, da sagt er dann "mount options only with sudo"

**Comment by libertyx82** [comment]
Fragt sich nur, mit welchem User das ausgeführt wird, dem mit dem neuen Installationsscript
http://www.iobroker.net/docu/?page_id=8323&lang=de
Hat der iobroker einen eignen User "iobroker"

**Comment by simatec** [comment]
soweit ich weiß, ist der User "iobroker"
