### ISSUE TITLE
Keine Möglichkeit ein Backup mit Backitup zu machen, wenn der Ring Adapter installiert ist.

### ISSUE THREAD

**Issue by gitknd** [simatec/ioBroker.backitup#905]
In den Issues vom Ring Adapter wird berichtet, dass ein Backup bei installieren Ring Adapter fehlschlägt. Vermutlich muss aber wohl eher der Backitup Adapter angepasst werden.

Hier der Link zum Issue im Ring Adapter: https://github.com/iobroker-community-adapters/ioBroker.ring/issues/433

Kurz gefasst wird anscheinend das iobroker Backuparchiv nicht erzeugt, wenn der Ring Adapter installiert ist.
Die Zeile 
[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_xxxx_xx_xx-xx_xx_xx_backupiobroker.tar.gz
fehlt dann.

**Comment by simatec** [comment]
Dann ist es grundsätzlich ein Problem im Ring Adapter. 
Backitup nutzt den js-controller für den kompletten Backup Prozess. 
ist also identisch zum cli Befehl „iob backup“

führe den Befehl auf der cli aus und du du wirst für das Issue vom Ring Adapter die benötigen Infos als Output bekommen

**Comment by gitknd** [comment]
Danke, aber das mit der Heimatfilm Sammlung bin nicht ich. Den Fehler hatte vorher schon jemand anderes gemeldet (Blacky...) und ich habe mich nur mit eingeklinkt, da ich den Fehler nun auch habe. Bei mir liegen keine Videos und Screenshots unter iobroker. 
iob backup ergab bei mir übrigens nur

host.iobroker 21875 states saved
host.iobroker 24497 objects saved
/usr/bin/iob: line 8: 23619 Killed                  gosu iobroker node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js "$@"

**Comment by simatec** [comment]
Ja genau … dein System hat ein Problem und deshalb kann kein Backup ausgeführt werden. 
gut du hast ein anderes Issue verlinkt. Aber am Ende liegt es am Ring Adapter. 
Beim Backup werden alle settings der Adapter als json gelesen und wenn da ein Adapter etwas verhaut, scheitert das Backup

**Comment by gitknd** [comment]
Gibt es eine Möglichkeit die konkrete Ursache seitens Backitup weiter einzugrenzen ? Die Debug Informationen sind nicht ausreichend und bisher zeichnet sich auch keine Lösung ab. Medienfiles sind wie gesagt nicht dabei.

**Comment by simatec** [comment]
Ich hatte es weiter oben schon geschrieben. Backitup nutzt den identischen Prozess vom CLI Befehl "iob backup"
Dieser wird über den js-controller gesteuert.
Du hast in deinem Ring-Adapter irgendwas in der Config schief, was dir den json File beim Backup zerhaut.
Ich kenne den Ring Adapter nicht. Hast du irgendwo in der Config irgendwelche Passwörter mit Sonderzeichen oder sonst irgendwo Sonderzeichen oder Leerzeichen? Das wären alles Ansätze, die du erstmal prüfen kannst.

Der Backitup Adapter hat hier keinerlei Einfluss oder Bewandtnis. Das Issue ist hier leider an der falschen Stelle

**Comment by gitknd** [comment]
Die Config bietet nicht viel. Ein Token (den habe ich aber auch schonmal rausgenommen), sowie Dateinamen für Foto und Video (da habe auch auch schon alles Verdächtige mal entfernt). Dann muss es irgendwo in den Tiefen des Adapters stecken und warte mal auf Reaktion des Adapter Entwicklers. Danke aber trotzdem
