### ISSUE TITLE
InfluxDB - Flag --skip-verify

### ISSUE THREAD

**Issue by pphlwmarcel** [simatec/ioBroker.backitup#912]
Ich habe in meiner Installation von InfluxDB 2.x https im Einsatz. Leider funktioniert die Trust Beziehung zwischen der Influx CLI und der Remote InfluxDB noch nicht so ganz. 

Grundsätzlich ist es möglich im influx backup Befehl das Flag --skip-verify mitzugeben, was aber von Backitup aktuell nicht getan wird.

Ich habe es aktuell quick and dirty so konfiguriert im Adapter
![image](https://user-images.githubusercontent.com/14854093/227571351-01d5d788-7759-47cd-8a59-ca88781a0a9b.png)
Damit funktioniert es auch ;-)

Wäre aber schön, wenn es einen Haken für das skip-verify gibt, wenn https schon unterstützt wird.

**Comment by simatec** [comment]
Bitte teste die Version 2.6.15

**Comment by simatec** [comment]
Nur bei influxdb 2.x und https

**Comment by pphlwmarcel** [comment]
OK, funktioniert wie geplant. Für mich ist das so ausreichend. Zukünftig könnte es andere Benutzer geben, die gerne die Wahl hätten ob die Zertifikate geprüft werden sollen oder nicht. Eine Checkbox die das Flag hinzufügt oder eben nicht könnte diese Anforderung erfüllen.

Von meiner Seite aus kann der Issue aber auch so geschlossen werden.
