### ISSUE TITLE
Backup/Restore zigbee2mqtt auf anderem Server

### ISSUE THREAD

**Issue by MarkSau** [simatec/ioBroker.backitup#922]
Ich habe zwei zigbee2mqtt iobroker Instanzen laufen. Beide verweisen auf andere Systeme außerhalb des iobrokers.
Dies würde ich gerne ebenfalls durch backupit sichern. Ein Remote Zugriff auf die Verzeichnisse ist möglich, aber den user iobroker gibt es dort nicht. Funktionieren würde z.b. "scp -r root@192.168.0.17:/opt/zigbee2mqtt/data/ /tmp".
Ist das umsetzbar?

**Comment by simatec** [comment]
Mit shell Befehlen arbeitet der Adapter nicht. 
wenn du die Pfade sichern möchtest, muss auf diesem Host ein iobroker Slave laufen. 
Damit kannst du dann über die Multihost Option sicher
