### ISSUE TITLE
Permit error since update to 2.6.16

### ISSUE THREAD

**Issue by Draygv2** [simatec/ioBroker.backitup#924]
Since the update I'm not able to backupt the iobroker manually.

`Started iobroker ...
[DEBUG] [mount] - noserverino option: true
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=iobroker,password=****,noserverino,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=2.0 //10.0.0.10/Software/IOBroker/Backup /opt/iobroker/backups"
[DEBUG] [mount] - first mount attempt with smb option failed. try next mount attempt without smb option ...
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=iobroker,password=****,noserverino,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //10.0.0.10/Software/IOBroker/Backup /opt/iobroker/backups"
[ERROR] [mount] - [undefined Error: Command failed: sudo mount -t cifs -o username=iobroker,password=****,noserverino,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //10.0.0.10/Software/IOBroker/Backup /opt/iobroker/backups
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

[ERROR] [mount] - Error: Command failed: sudo mount -t cifs -o username=iobroker,password=****,noserverino,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //10.0.0.10/Software/IOBroker/Backup /opt/iobroker/backups
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)`

The auto backup is working fine with this night. But manually was not possible yesterday and today.
![image](https://user-images.githubusercontent.com/62559741/231406612-703e4992-f55a-40bf-8af3-2f2ab54b4f2a.png)

**Versions:**  
 - Adapter version: 2.6.16
 - JS-Controller version: 18.15.0
 - NPM version: 9.5.0
 - Operating system: ubuntu

**Comment by simatec** [comment]
the manual and automatic backup are completely identical processes.
Also, nothing has changed in the mount version

**Comment by simatec** [comment]
Please restart your System first

**Comment by Draygv2** [comment]
I had to shorten the pw and kick the special characters. Thanks for your help :)
