### ISSUE TITLE
DOCU / WIKI: Klrstellung Unterschiede zu iobroker backup (Befehlszeileneingabe)

### ISSUE THREAD

**Issue by mcm1957** [simatec/ioBroker.backitup#925]
Im WIKI stehen folgende einleitende Infos:

> Es werden hier identisch dem Standard Backup des js-controllers alle States und Objects, sowie die Nutzerdateien wie z.B. VIS gesichert.
> Auch der Restore ist komplett identisch dem CLI Befehl iobroker restore <backupname> des js-controller

Für mich stellt sich nun die Frage ist der Adapter nun "nur" ein GUI Warpper um iobroker backup / restore und eine cron-Erweiterung für automatisches Starten? Oder gibts da noch mehr Unterschiede? Der Hinweis auf die Datenbanken läßt dies vermuten. 
Ist die Eingabe von iobroker backup auf der Commandline ident zu einem backitup Luaf ? Ich glaube nicht - aber es liest sich eigentlich fast so. ä

Es wär für Neulinge m.E. sinnvoll eine klare Info zu ergänzen was denn backitup zusätzlich (oder weniger) als iob backup macht, d.h. eine möglichst genaue Liste was unterschiedlich zur Commandline ist, wann man welches Tool sinnvoll einsetzt und ob z.B. das eine oder das andere Tool 100% Backup garantiert (abgesehen davon dass man jedes Backupsystem auf einem Testystem mal testen sollte ...)

**Comment by simatec** [comment]
edit v2.6.17

**Comment by mcm1957** [comment]
DANKE für die SUPER Klarstellung. Mir ist nun kalr, was denn den Unterschied / Vorteil ausmacht.
Und das in "Null-Zeit".
