### ISSUE TITLE
Keine täglichen Backups mehr seit Version 2.6.16

### ISSUE THREAD

**Issue by mbhomie007** [simatec/ioBroker.backitup#926]
![image](https://user-images.githubusercontent.com/64688879/231699193-48208f3f-59e5-43c2-acc6-896583000e8d.png)

![image](https://user-images.githubusercontent.com/64688879/231699266-33a320f9-2328-423f-aac0-ffe99766d4a6.png)

![image](https://user-images.githubusercontent.com/64688879/231701049-be197e59-8a34-425f-b935-145000d11598.png)

Die täglichen Backups werden von meiner Homematic-CCU und meiner IOBroker Konfig nicht mehr täglich ausgeführt.

Mit vorherigen Versionen wurde alle Backups immer korrekt täglich ausgeführt und auch auf er Übersichtsseite wurden die letzten und die nächsten Backups angezeigt.

Die manuelle Ausführung klappt auch nicht mehr.
![image](https://user-images.githubusercontent.com/64688879/231700013-8e95fccf-8127-4d73-b790-3e7387e8c900.png)

![image](https://user-images.githubusercontent.com/64688879/231700195-224a8ef1-7a8e-4ccd-929a-677a1d6d1c80.png)

Adapter Neustart bringt keine Besserung.

![image](https://user-images.githubusercontent.com/64688879/231701972-c2bb284a-14d5-4582-b204-d8d12dfa2edc.png)

**Comment by simatec** [comment]
Du hast Probleme mit deiner Verbindung zum NAS.
Da wurde allerdings nix geändert.

Gebe das Passwort mal neu ein und teste auch mal das Backup ohne NAS... als nur lokal

**Comment by mbhomie007** [comment]
Habe nun mein Raspberry 4 mal komplett neu gestartet.

Die manuellen Backups wurden nun erfolgreich ausgeführt inklusive NAS.

Allerdings endet das Backup der ioBroker Sicherung in einer Enlosschleife:

![image](https://user-images.githubusercontent.com/64688879/231710036-e8310de2-453e-4562-af48-88be6deb911d.png)

Jarvis war sonst immer mit aktiviert, nur noch nicht eingerichtet.
Sonst endete es aber nicht in einer Endlosschleife sondern wurde einfach übersprungen.

**Comment by simatec** [comment]
Was für eine Endlosschleife. Sehe ich auf deinen Bildern nicht. 
bitte Debuglog posten

**Comment by mbhomie007** [comment]
Siehe meinen Beitrag oben.
Der blaue Balken läuft und läuft, der Vorgang wird nicht abgeschlossen.
Der Debug log ist leer.

**Comment by simatec** [comment]
Aktiviere in Backitup Noserverino für den mount auf die Fritzbox

**Comment by mbhomie007** [comment]
Super! Das halt geholfen, nun ist es korrekt durchgelaufen.
Ich hoffe, dass nun auch wieder die täglichen Backups durchlaufen.

Vielen Dank für deinen schnellen Support. 💯

**Comment by simatec** [comment]
https://github.com/sponsors/simatec
