### ISSUE TITLE
Bei Fehlerhaftem CCU Backup wird Mail versendet dass Backup erfolgreich

### ISSUE THREAD

**Issue by jogicom** [simatec/ioBroker.backitup#93]
Hallo, bin neu zu "Backitup" gestossen, mir ist aufgefallen, dass die Backup routine weiter läuft, wenn z.B. ein "mount" nicht geklappt hat. In so einem Fall, sollte man auch per Mail informiert werden.

Bei einem CCU Backup, hatte ich in den Einstellungen aus versehen einen falschen UserName für die CCU hinterlegt, ein Backup (manuell gestartet) hat zwar in den DebugMeldungen vermerkt, dass UserName oder Passwort falsch sind, es kam aber trotzdem eine Mail, dass das BU erfolgreich war. Evt. könnte mal das NAS nicht Online sein, was passiert dann? Oder die CCU ist offline...

Ich habe hier eine Synology DS per SMB2 gemountet. Frage: SMB3 würde auch funktionieren, warum kann das in den Einstellungen nicht ausgewählt werden?

Trotzdem finde ich den Adapter SUPER, wo war der versteckt, dass ich ihn erst heute gefunden habe :-) Tolle Arbeit!

**Comment by simatec** [comment]
in Version 1.0.5 gefixt
