### ISSUE TITLE
Error when backing up postrgesql

### ISSUE THREAD

**Issue by ChriD** [simatec/ioBroker.backitup#930]
Hi,

I am getting following error when backing up postrgesql

`pg_dump: error: connection to database "iobroker" failed: could not translate host name "43@10.0.0.140" to address: Name or service not known`

I've tried to use localhost as host but the same error occurs.

`pg_dump: error: connection to database "iobroker" failed: could not translate host name "43@localhost" to address: Name or service not known`

I am not sure where the `43` from the host name comes from. Shouldn't this be the user?

**Comment by simatec** [comment]
Please show your Config

**Comment by ChriD** [comment]
Oh sorry, of course! I used the "Detect Config" button. 
![image](https://user-images.githubusercontent.com/2505067/232248976-7b3f0dc6-a64d-4638-8e5c-300ef969554b.png)

The raw data
![image](https://user-images.githubusercontent.com/2505067/232249133-2c24bff6-15d6-472a-860d-fbb49f0a80ff.png)

**Comment by simatec** [comment]
I assume that your password here has some special characters and this causes a problem to resolve the command line.

Please check your password and change it so that there are no quotes or other special characters.

The 43 seems to come from your password.

It looks like your password ends with '43 or "43.

**Comment by ChriD** [comment]
Hell! You may be right! I'l try it in the evening. But it looks like this is the case!
Thanks!

**Comment by simatec** [comment]
I suspect your problem is an @ in the password.
You can try to enter the password in quotes or use a password without special characters

Example: "Pass@word"
