### ISSUE TITLE
{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8088}

### ISSUE THREAD

**Issue by Duffy987** [simatec/ioBroker.backitup#931]
**Describe the bug**  
Beim Versuch ein Backup von influxDB2 auf eine neue iob installation zurück zu spielen kommt folgender Fehler
{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8088}

When trying to restore a backup from influxDB2 to a new iob installation, the following error occurs
{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8088}

**To Reproduce**  
1. Go to 'Backup Adapter'
2. Click on 'restore -> backup retrieve -> NAS -> select Backup influxdb -> Restore backup file'
4. See error: {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8088}

**Expected behavior**  
I would expect the backup to be restored on the new iob installation
Note iob and history was restored with no problems

**Screenshots & Logfiles**  
(https://forum.iobroker.net/assets/uploads/files/1681748706908-back.png)

**Versions:**  
 - Adapter version: <2.6.16>
 - JS-Controller version: <js-controller-version>  4.0.24
 - Node version: <node-version>  16.19.1
 - Operating system: <Resperrypi OS 64Bit with Desktop >

**Additional context**

**Comment by simatec** [comment]
Ist Infuxdb installiert? Nicht der Adapter, sondern die Datenbank selber?

zeige mal bitte, welche influx Version bei dir installiert ist

**Comment by Duffy987** [comment]
Jetzt wirds peinlich, wo finde ich die?
Instanzeinstellungen: influxdb.0 v3.2.0, das meinst du ja vermutlich nicht oder?

Ich habe es gerade noch einmal versucht mit einem wiederherstellen des Backups. Der Fehler kommt nicht mehr aber es wird auch nichts wiederhergestellt ;-(

Ich bin Anfänger bitte habe etwas Nachsicht.

Gruß Duffy

**Comment by simatec** [comment]
Naja wenn du das System neu aufgesetzt hast, musst du nicht nur iobroker sondern auch influx installieren. Das Backup ist doch nur die Datenbank. 

Influxdb muss du vorher installieren

**Comment by Duffy987** [comment]
Das habe ich natürlich schon gemacht, ich kann es auch öffnen und Daten aufzeichnen nur nur nicht das Backup wiederherstellen

**Comment by Duffy987** [comment]
Gerne kann ich dir Log Files schicken wenn du mir sagst wie.

Gruß Duffy

**Comment by simatec** [comment]
Zeige bitte welche Version installiert ist? Stelle in Backitup influx auf lokal

**Comment by Duffy987** [comment]
Zeige bitte welche Version installiert ist?
InfluxDB v2.7.0 (habs gefunden)

-Stelle in Backitup influx auf lokal.- War auf "Lokal"

**Comment by simatec** [comment]
War auf deinem alten System auch die Influx 2.x installiert? Die Datenbanken zu 1.x sind nicht kompatibel. 

Lokal, weil laut deiner IP Influx auf dem hleichen System wie dein iobroker läuft

**Comment by Duffy987** [comment]
Ja auf dem alten war auch influxDB2 installiert. (SD mit der Installation existiert noch)
Und ja iob und influxdb2 laufen beide auf ein und dem selben Respberry 4 (4gb)

Viele Grüße Duffy

**Comment by simatec** [comment]
Influx-cli installiert? Das wird benötigt 
Steht in der Doku

**Comment by Duffy987** [comment]
wget -qO- https://repos.influxdata.com/influxdata-archive_compat.key | gpg --dearmor | sudo tee /usr/share/keyrings/influxdata-archive_compat.gpg > /dev/null

echo "deb [signed-by=/usr/share/keyrings/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/influxdb.list > /dev/null

sudo apt update
sudo apt full-upgrade

  | sudo apt install influxdb2
  | sudo service influxdb start

So habe ich es installiert, wie auch beim ersten mal.

**Comment by simatec** [comment]
Da fehlt Influx-cli

**Comment by simatec** [comment]
https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch#influxdb-backup

**Comment by Duffy987** [comment]
Ich habe influx-cli zwar noch nie wissentlich installiert aber ich versuche es gerne. 
Hast du mir bitte noch den Befehl, bzw was ist das dann überhaupt?

**Comment by Duffy987** [comment]
Meine Frage hat sich mit seiner Antwort überschnitten, sorry. 

Gruß Duffy

**Comment by simatec** [comment]
Lese doch bitte die Doku von Backitup. Da steht alles beschrieben. Im Forum sind etliche Beiträge dazu. 
wenn du auf deinem alten System deine Influx mit Backitup gesichert hast, dann war dort definitiv influx-cli drauf

**Comment by Duffy987** [comment]
Ok, auf dem alte System ging es zumindest mal zu sichern, Wiederherstellung hatte ich nie gebraucht. 

Verrätst du mir aber bitte noch was ich hier für dem Respberrypi4 64bit auswählen muss. 
(Man ist das alles kompliziert ;-( )

# amd64
wget https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.1-linux-amd64.tar.gz

# arm
wget https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.1-linux-arm64.tar.gz

schönen Abend noch und Viele Grüße

**Comment by simatec** [comment]
Da du die Repo schon angelegt hast, sollte eigentlich das ganze auch normal installierbar sein. 

Versuche mal bitte folgendes 

`sudo apt install influx-cli`

**Comment by Duffy987** [comment]
Ein netter iob Forumkollege hat mir gezeigt das ich den Influxdb-cli schon drauf habe. 

pi@raspberrypi:~ $ apt policy influxdb*
2 influxdb2-cli:
3
Installed: 2.7.1-2
4
Candidate: 2.7.1-2

Dann liegt es vielleicht doch nicht daran?

Viele Grüße

**Comment by Duffy987** [comment]
Hallo simatec,

hat leider nicht geklappt. Es fängt schon damit an das ich nicht weis wie man eine Backup Datei auf ein lokales Laufwerk zieht um es wiederherzustellen.

Der erste Versuch vom FTP ging schon mal wieder in die Hose und ich werde nun erst mal wieder mein Image auf die SD spielen.
Ich befürchte aber das das bei mir nichts wird mit der Backuperstellung/Wiederherstellung ;-(

In der Beschreibung steht unter anderem:

Bei der Neuinstallation ist kein Bucket neu anzulegen bzw. mindestens ein neuer Bucketname zu wählen.
Da komme ich schon ins schleudern.

Wiederspricht sich das nicht, KEIN Bucket neu anzulegen bzw. MINDESTENS ein neuer Bucket Name??

Gibt es die Beschreibung vielleicht auch für Deppen das wäre vielleicht meine Chance?

Viele Grüße Duffy

**Comment by simatec** [comment]
Ich denke mit deinen Fragen bist du im Forum besser aufgehoben.

**Comment by Duffy987** [comment]
Ok, danke trotzdem für deine Mühe. 

Gruß Duffy
