### ISSUE TITLE
Slave Backup startet nicht mehr

### ISSUE THREAD

**Issue by MarkSau** [simatec/ioBroker.backitup#934]
Es schaut so aus, das seit dem letzten Update auf 2.6.18 bzw. js-controller 5.0.1-ALPHA.0-20230418-EFA3E809 der Slave Backup nicht mehr angestoßen wird. 
Node.js: v18.16.0
NPM: 9.5.1
Konfiguriert ist der Master so:
![image](https://user-images.githubusercontent.com/22911084/233283662-c3fbf59c-3cff-43c6-ba07-584eff601a89.png)
![image](https://user-images.githubusercontent.com/22911084/233283735-94de6308-0e3e-4e92-b49d-aff6b432a396.png)
Der Slave so:
![image](https://user-images.githubusercontent.com/22911084/233283878-59543312-2629-4e07-b1a8-7f2e679bb1b4.png)
![image](https://user-images.githubusercontent.com/22911084/233283974-1b6655b9-8304-474f-b3d7-285d6e2e071f.png)

**Comment by MarkSau** [comment]
im Log erscheint diese Meldung:

<html>
<body>


backitup.0 | 2023-04-20 08:54:19.638 | error | error on slave Backup: Error: Parameter "options" needs to be a real object but type "string" has been passed
-- | -- | -- | --
backitup.0 | 2023-04-20 08:54:18.633 | error | error on slave State: Error: Parameter "options" needs to be a real object but type "string" has been passed


</body>
</html>

**Comment by simatec** [comment]
Bitte poste mal den gesamten Log vom Backupprozess

**Comment by simatec** [comment]
Fix in v2.6.19
