### ISSUE TITLE
Restore of Postgresql don't work

### ISSUE THREAD

**Issue by Failx92** [simatec/ioBroker.backitup#937]
Hello,

I get the following error message when I try to restore my SQL data:

[pgsql] pg_restore: error: input file appears to be a text format dump. Please use psql.

**Versions:**  
 - Adapter version: 2.6.16 for Backup and Restore
 - JS-Controller version: 4.0.24 
 - Node version: v18.16.0
 - Operating system: Linux/Docker Buanet

**Additional context**  
I moved my Iobroker installation from a VMware to a Docker,
everything worked so far except the SQL Restore.

I use the Iobroker Docker Image from Buanet with installed postgresql-13 (first I had only the client but that didn't work either).

And of course another Docker with postgresql-13 for the Database.

**Comment by simatec** [comment]
you would have to open an issue specifically for the Docker image or look for the error message on the Internet. Backitup just runs the command. Basically, in my opinion, the whole Docker container topic is not the perfect basis for such system links

**Comment by Failx92** [comment]
Maybe we can implement a workaround if the error appears?

Finally I was able to restore my data through the psql command:

psql -U username -d dbname < filename.sql

The command will work only if the database is newly created and still empty.

Is there a way to see which command arguments are executed with pg_dump?

**Comment by simatec** [comment]
https://github.com/simatec/ioBroker.backitup/blob/ccac06b4eb694e5e0573f06d3db2540ca0adcec8/lib/restore/pgsql.js#L10

**Comment by Failx92** [comment]
Hi,

did that ever work? I read the docs on postgres.org.

In my opinion, there is something wrong with the commands.

I think it must be

pg_dump --format=custom dbname > db.dump

the --format=custom let the pg_dump tool know that the restore tool pg_restore is used instead of psql.

and the restore command

pg_restore --clean --create --dbname=dbname db.dump 

the clean und create let the tool erase the existing database and create new. If I don't use that and the database exists the tool throws an error. 

I'm going to try around with the commands a bit more this week. 

Greetings

**Comment by simatec** [comment]
Please show your config of Backitup, the SQ adapter and your Docker container.

As far as I know, the restore command is working and has not caused any problems so far.

I assume there are problems in combination with Docker missing ports etc.

iobroker.backitup has to perform the restore over the network.

**Comment by Failx92** [comment]
Sorry I haven't had time yet, I'll keep you posted as soon as I can.

**Comment by Failx92** [comment]
Hi,
I tried a new clean Setup and the restore don't work in an native Environment. (to rule out the possibility of the docker problem)

The error persists: [pgsql] pg_restore: error: input file appears to be a text format dump. Please use psql.

You have to add the arguments pg_dump --format=custom and everything should be fine. 
Greetings

**Comment by simatec** [comment]
What exactly do you mean by arguments?
Where should they be added?

Like this?

`const cmd = `pg_dump --format=custom --dbname=postgresql://${options.user}:${options.pass}@${options.host}:${options.port}/${options.dbName} < ${fileNamePgsql}`;`

**Comment by Failx92** [comment]
Yes like this. 

Is there an easy way to test it with the addition?

**Comment by simatec** [comment]
You can test in v2.6.23

**Comment by simatec** [comment]
Have you been able to test the fix yet?

**Comment by simatec** [comment]
@Failx92 push!!

**Comment by simatec** [comment]
Is there any info here in the meantime? Otherwise I would close the issue...
