### ISSUE TITLE
für Zigbee Adapter

### ISSUE THREAD

**Issue by arteck** [simatec/ioBroker.backitup#94]
die Zigbee DB sollte mit in die Sicherung aufgenommen werden

/opt/ioroker/iobroker-data/zigbee_0/shepherd.db

**Comment by simatec** [comment]
Finde ich eine sehr gute Idee. 
Beim total wird sie ja mitgesichert. 
Aber beim minimal könnte das als Option mit rein.

**Comment by simatec** [comment]
Ändert sich er Pfad, wenn man mehrere Instanzen vom zigbee Adapter hat?

**Comment by Karatekid2407** [comment]
zigbee_0 sollte zu zigbee_1 werden.
Eine Abfrage aller zigbee ordner im Verzeichnis iobroker-data sollte das lösen.

**Comment by Michaelnorge** [comment]
Wird zigbee denn nun mitgesichert oder nicht?

**Comment by simatec** [comment]
Die Zigbee Datenbank liegt aktuell beim total backup mit im Archiv. 
Eine separate Sicherung kommt in den nächsten Versionen von backitup

**Comment by simatec** [comment]
Ab Version 1.1.4 ist die Sicherung der Zigbee Datenbank jetzt verfügbar ...
