### ISSUE TITLE
free space validation not valide

### ISSUE THREAD

**Issue by HGlab01** [simatec/ioBroker.backitup#942]
**Describe the bug**  
The adapter tells, that 1018MB are available which does not fit to the file systems.
In my point of view the available space of the installation (in my case `/opt`) should be used. 

**To Reproduce**  
Klick on the adapter setting page and very space with `df -h` (linux terminal)

**Screenshot**  
![image](https://user-images.githubusercontent.com/54232526/236819758-139556f0-6095-43b3-a70b-a64e4c76e174.png)

**Versions:**  
 - Adapter version: 2.6.19
 - JS-Controller version: 4.0.24
 - Node version: 16.20.0
 - Operating system: Ubuntu 18.04

**Comment by simatec** [comment]
Backitup gets the information from the states of iobroker.

`system.host.<your host>.diskFree`

You might have to open an issue at the js-controller to do this

**Comment by HGlab01** [comment]
> You might have to open an issue at the js-controller to do this

done!
