### ISSUE TITLE
influxdb unknown arguments: backup --bucket ...

### ISSUE THREAD

**Issue by Technikfan** [simatec/ioBroker.backitup#943]
**Describe the bug**  
The backup job fails for backup the local instance of influxdb.
The Message in iobroker says unknown arguments.

**To Reproduce**  
1. Everytime the backup-jobs starts
2. On SSH-Console with manual cpoy/paste the command above.

**Expected behavior**  
An backup from the influxdb

**Screenshots & Logfiles**  
`[iobroker/influxDB] unknown arguments: backup --bucket iobroker -t secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretse== /opt/iobroker/backups/influxDB_2023_05_09-02_40_27_smarthome-master_backupiobroker

[iobroker/influxDB] unknown arguments: backup --bucket iobroker -t secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretse== /opt/iobroker/backups/influxDB_2023_05_09-02_40_27_smarthome-master_backupiobroker

[iobroker] Error: Command failed: influx backup --bucket iobroker -t secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretse== "/opt/iobroker/backups/influxDB_2023_05_09-02_40_27_smarthome-master_backupiobroker"unknown arguments: backup --bucket iobroker -t secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretse== /opt/iobroker/backups/influxDB_2023_05_09-02_40_27_smarthome-master_backupiobroker`

**Versions:**  
 - Adapter version: <2.6.19>
 - JS-Controller version: <4.0.24>
 - Node version: <18.16.0>
 - Operating system: <Linux smarthome-master 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux>

**Additional context**  
Nothing

**Comment by simatec** [comment]
Have you installed the influx-cli?

https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch#influxdb-backup

**Comment by Technikfan** [comment]
Oh, thx. 
I'm sorry, i didn't read deep enough.
I was thinking this is only for remote instances, but now i understood, that is also for the local backup.
It works now for me.
Best regards
