### ISSUE TITLE
Grafana Backup doesn't work

### ISSUE THREAD

**Issue by sammie76-2** [simatec/ioBroker.backitup#946]
**Describe the bug**  
The grafana backup function doesn't work for me anymore. Seems to happen since an grafana update.  Grafana Version is: Grafana v9.5.2 (cfcea75916).

**To Reproduce**  
Automatic Backup of grafana activated.

**Expected behavior**  
The backup doesn't work an quits with an error (of grafana).

**Screenshots & Logfiles**  
[If applicable, add screenshots and logfiles to help explain your problem.](grafana: {"message":"Request failed with status code 401","name":"AxiosError","stack":"AxiosError: Request failed with status code 401\n at settle (/opt/iobroker/node_modules/iobroker.backitup/node_modules/axios/lib/core/settle.js:19:12)\n at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/iobroker.backitup/node_modules/axios/lib/adapters/http.js:570:11)\n at IncomingMessage.emit (node:events:525:35)\n at IncomingMessage.emit (node:domain:489:12)\n at endReadableNT (node:internal/streams/readable:1359:12)\n at processTicksAndRejections (node:internal/process/task_queues:82:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"appl)

**Versions:**  
 - Adapter version: 2.6.20
 - JS-Controller version: 4.0.24
 - Node version: 18.16.0
 - Operating system: debian linux

**Additional context**

**Comment by simatec** [comment]
In newer versions of Grafana there is no API token anymore. Here you have to create a service account with the role "Admin".

You have to store this token in the config of Backitup.

I just tested it with Grafana v9.5.2 (cfcea75916) and the backup runs without problems.

Service accounts and their tokens can be used to authenticate against the Grafana API. Find out more [here.](https://grafana.com/docs/grafana/latest/administration/service-accounts/)

**Comment by simatec** [comment]
Please post your Config from Backitup

**Comment by sammie76-2** [comment]
Ok.

**Comment by simatec** [comment]
Is Grafana on the same Host with iobroker?

**Comment by simatec** [comment]
Is the Token / Service Key for Admin Role?

**Comment by sammie76-2** [comment]
> Is Grafana on the same Host with iobroker?

Yes.

**Comment by simatec** [comment]
Please test without local IP. 
Try „localhost“ and „127.0.0.1“

**Comment by sammie76-2** [comment]
I now tried both (localhost and 127.0.0.1) it is both not working.

`[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
[ERROR] [grafana] - Error on Grafana Dashoard Request: AxiosError: Request failed with status code 401
[DEBUG] [grafana] - start Grafana backup compress ...
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[ERROR] [grafana] - cannot found Grafana Backup files
[DEBUG] [grafana] - done`

What i have done so far:
- I created a service token in grafana with the user admin and the admin role. 
- I put the name of the token (sa-iobroker_backitup-7facef4e-5568-4612-8074-64ee3d4e5f63) in the setting of backitup and entered the admin user with the password of admin user.


![2023-06-11_09h59_41](https://github.com/simatec/ioBroker.backitup/assets/73701785/20229fb9-3114-4108-bbcb-99c1a18dd300)

**Comment by simatec** [comment]
This is not ok

1. Go in Grafana to Tab "Service Accounts"
2. Click "Add service account"
3. Fill in the field as in the screenshot
![image](https://github.com/simatec/ioBroker.backitup/assets/39792461/b7e3f57a-9ba8-49a5-b6bc-35eae20760b0)
4. In the newly opened window please click "add service account token"
5. in the next popup you can enter a name and then click on "Generate token"
6. In the next popup (Service account token created) you will see the token that you have to copy there. Attention... the token is displayed only once
![image](https://github.com/simatec/ioBroker.backitup/assets/39792461/a07f95ef-6332-4cdc-ba4e-03322c2a570d)

**Comment by sammie76-2** [comment]
Thanks! Now ot works. Localhost and the correct token made it.
