### ISSUE TITLE
Backup of remote Influx DB fails if port 8088 is not set explicitly

### ISSUE THREAD

**Issue by Malombo** [simatec/ioBroker.backitup#949]
**Backup of a remote Influx DB fails if port 8088 is not set explicitly within the Backitup Instance Configuration for INFLUXDB.**

Logfile without explicite setting of the port 8088:
[DEBUG] [influxDB] - InfluxDB tmp directory "/opt/iobroker/backups/influxDB_2023_05_20-17_47_25_backupiobroker" successfully deleted
[DEBUG] [influxDB] - 2023/05/20 17:47:25 backing up metastore to /opt/iobroker/backups/influxDB_2023_05_20-17_47_25_backupiobroker/meta.00
[ERROR] [influxDB] - Error: Command failed: influxd backup -portable -database iobroker -host 192.168.178.202: "/opt/iobroker/backups/influxDB_2023_05_20-17_47_25_backupiobroker"
2023/05/20 17:47:25 Download shard 0 failed dial tcp 192.168.178.202:0: connect: connection refused.  Waiting 2s and retrying (0)...
2023/05/20 17:47:27 Download shard 0 failed dial tcp 192.168.178.202:0: connect: connection refused.  Waiting 2s and retrying (1)...
2023/05/20 17:47:29 Download shard 0 failed dial tcp 192.168.178.202:0: connect: connection refused.  Waiting 2s and retrying (2)...
2023/05/20 17:47:31 Download shard 0 failed dial tcp 192.168.178.202:0: connect: connection refused.  Waiting 2s and retrying (3)...
2023/05/20 17:47:33 Download shard 0 failed dial tcp 192.168.178.202:0: connect: connection refused.  Waiting 2s and retrying (4)...
2023/05/20 17:47:35 Download shard 0 failed dial tcp 192.168.178.202:0: connect: connection refused.  Waiting 2s and retrying (5)...
2023/05/20 17:47:37 Download shard 0 failed dial tcp 192.168.178.202:0: connect: connection refused.  Waiting 3.01s and retrying (6)...
2023/05/20 17:47:40 Download shard 0 failed dial tcp 192.168.178.202:0: connect: connection refused.  Waiting 11.441s and retrying (7)...
2023/05/20 17:47:52 Download shard 0 failed dial tcp 192.168.178.202:0: connect: connection refused.  Waiting 43.477s and retrying (8)...
2023/05/20 17:48:35 Download shard 0 failed dial tcp 192.168.178.202:0: connect: connection refused.  Waiting 2m45.216s and retrying (9)...
backup: dial tcp 192.168.178.202:0: connect: connection refused

**It all works perfectly if the Port 8088 ist set explicitly in the Backitup Instance Configuration for INFLUXDB.**

**Versions:**  
 - Adapter version: 2.6.19
 - JS-Controller version: 4.0.24
 - Node version: 18.16
 - Operating system: Debian 11.7

**Additional context**  
Runing on Proxmox 7.4-3; ioBroker in VM; influxdb 1.8.10 in Debian LXC container

**Comment by simatec** [comment]
Port 8088 must also be set in the backup configuration. 
Why should it work without? The port must be specified. 

Don't get your issue.

**Comment by Malombo** [comment]
I aussumed the port 8088 is used by default if it is not explicitly set/the field is left empty.
If the IP is set for remote backup, an error message / hint that the port need to be explicitly configured would be helpful - or alternatively use the port 8088 if left empty.

**Comment by simatec** [comment]
v2.6.22 added default Ports
