### ISSUE TITLE
Google Drive invalid_request

### ISSUE THREAD

**Issue by mariusgrams** [simatec/ioBroker.backitup#956]
**Describe the bug**  
I can't connect backitup with google drive anymore (v2.4.10) 

**To Reproduce**  
1. Install a new instance of backitup
2. Enable Google Drive
3. Click on Google drive tab
4. Click on blue button and link to get Google Drive access
5. Links shows: "400: invalid_request"

**Expected behavior**  
I expect to be able to log in with Google

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: v2.4.10
 - JS-Controller 4.0.24
 - Node version: 16.20.0
 - Operating system: Raspbian GNU/Linux 10 (buster)

**Additional context**  
Nothing
![image](https://github.com/simatec/ioBroker.backitup/assets/39212237/bec68c93-580c-4b11-9e21-3e313b35b522)

**Comment by simatec** [comment]
v2.4.10 is 1 Year old!
