### ISSUE TITLE
Data point in the object tree after the backup is complete

### ISSUE THREAD

**Issue by Sundancer78** [simatec/ioBroker.backitup#957]
Hello, 

I use the backup adapter to save the backup on my NAS. The NAS starts via WOL, the backup is copied, everything is great! Actually, the NAS should turn itself off after a period of idle time. For reasons unknown so far, it continues.
Now I wanted to use a script to shut down the NAS after a certain period of time. Works well so far, but annoying if you stream data elsewhere.
Now my question, is it possible to implement a data point in the backup object tree that jumps to any value after a complete backup, so that I can use it to shut down the NAS via script?

**Comment by simatec** [comment]
You can trigger the State from "backitup.0.output.line"
Backitup is finish == "[EXIT] 0"
