### ISSUE TITLE
Backup über Webdav auf MagentaCloud kaum möglich

### ISSUE THREAD

**Issue by heitec11** [simatec/ioBroker.backitup#958]
**Describe the bug**  
Backups von Influx Datenbanken mit mehr als 175 MB funktionieren kaum.

Bei dem einen System kommt die Fehlermeldung: 
"error: backitup.0 (4856) [iobroker/webdav] WebDAV: Error: socket hang up"

Bei einem zweiten System hängt sich der komplette Raspberry auf.

**Versions:**  
 - Adapter version: 2.6.23
 - JS-Controller version: 4.0.24
 - Node version: v18.16.1
 - Operating system: Linux / Raspbery 4 / v11

**Additional context**

**Comment by simatec** [comment]
Da wird dir wahrscheinlich der RAM ausgehen

**Comment by heitec11** [comment]
Bei dem einen System habe ich den Speicherort auf NAS umgestellt.
Da läuft es. Der RAM ist in der selben Größe von 2GB geblieben.

Braucht die Webdav Routine denn mehr RAM?

**Comment by simatec** [comment]
Ja da wird RAM benötigt
