### ISSUE TITLE
Error: backup path must be specified as a single positional argument

### ISSUE THREAD

**Issue by MichaelSchaaf999** [simatec/ioBroker.backitup#959]
**Describe the bug**  
Fehlermeldung im Log: Angaben im Backitup-Adapter anscheinend fehlerhaft?

**To Reproduce**  
...

**Expected behavior**  
Backup ohne Fehlermeldung

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

backitup.0 | 2023-06-27 01:05:28.511 | error | [iobroker] Error: Command failed: influx backup --bucket iobroker -t   "/opt/iobroker/backups/influxDB_2023_06_27-01_05_28_backupiobroker" Error: backup path must be specified as a single positional argument
-- | -- | -- | --
backitup.0 | 2023-06-27 01:05:28.511 | error | [iobroker/influxDB] Error: backup path must be specified as a single positional argument
backitup.0 | 2023-06-27 01:05:28.507 | error | [iobroker/influxDB]  Error: Command failed: influx backup --bucket iobroker -t   "/opt/iobroker/backups/influxDB_2023_06_27-01_05_28_backupiobroker"

**Versions:**  
 - Adapter version: <v2.6.23>
- JS-Controller version: <5.0.5>
- Node version: <18.16.0>
- Operating system: <Debian 4.19.269-1> in einer Proxmox-VM

**Additional context**

**Comment by simatec** [comment]
Ist das Influx Backup vollständig? Sieht mir eher so aus, als ob du influx-cli nicht installiert hast

**Comment by MichaelSchaaf999** [comment]
okay, und wie installiere ich das?

**Comment by simatec** [comment]
Schaue erstmal, ob es installiert ist...

`sudo apt policy influx*`

**Comment by MichaelSchaaf999** [comment]
![image](https://github.com/simatec/ioBroker.backitup/assets/53481090/e5bbb2cc-ee05-45d4-be87-ecad9e6ab600)

**Comment by simatec** [comment]
`sudo apt install influxdb2-cli`

**Comment by MichaelSchaaf999** [comment]
System updgraden: Wie mache ich das? Da gibt's doch sowas wie apt upgrade oder so?

Zum CLI:

![image](https://github.com/simatec/ioBroker.backitup/assets/53481090/2268d29f-11db-408a-866a-d81da60e20c1)

**Comment by simatec** [comment]
`sudo apt update && sudo apt install influxdb2-cli`

**Comment by MichaelSchaaf999** [comment]
![image](https://github.com/simatec/ioBroker.backitup/assets/53481090/1f2f11e5-c76a-41b7-a5ca-b3490b8640ae)

**Comment by simatec** [comment]
`wget -q https://repos.influxdata.com/influxdata-archive_compat.key`

 ` echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-archive_compat.key' | sha256sum -c && cat influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null`

 ` echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list`

`sudo apt update && sudo apt install influxdb2-cli`

**Comment by MichaelSchaaf999** [comment]
leider musste ich das alles per Hand eintippen, da CTRL-C und CTRL-V auf dem Mac in der VM-Konsole unter Proxmox nicht funktioniert.
Aber, Ergebnis:
![image](https://github.com/simatec/ioBroker.backitup/assets/53481090/6cfe0cd9-c139-49dc-9f01-14eb7063ab02)

**Comment by simatec** [comment]
Ich sehe keinen Token in dem Log?
Hast du den Token nicht eingetragen? Benutzerdaten und Token sind Pflicht

**Comment by MichaelSchaaf999** [comment]
wo muss man einen Token eintragen? Und woher bekommen wir den?

**Comment by MichaelSchaaf999** [comment]
Hier steht etwas mit "Token"...
Aber wenn ich den Button 
<img width="519" alt="image" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/ea656eb8-27c2-473a-88c8-c07d29a0f74d">
...betätige, kommt eine Meldung "Die Konfiguration wurde von influxdb.0 übernommen":

<img width="1113" alt="image" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/2ca1f35f-7103-4cea-958f-2d700414e72f">

**Comment by simatec** [comment]
Ich sehe da keinen Token ... Der Eintrag ist leer

**Comment by MichaelSchaaf999** [comment]
Ich hatte versucht, Anweisungen im Readme zu finden.
Habe aber nun in der influxdb-Instanz einen Token gesehen und den in der Backitup-Instanz eingesetzt.

<html><head></head><body>

backitup.0 | 2023-06-27 14:20:11.287 | error | [iobroker] Error: Command failed: influx backup --bucket iobroker -t  MjVkPdvDB55V65k4Yeftc_FqOUCM84cUxskAD3Ya-P3t8eYM6vwqYB8wTPwH8NPZGetTFgBcN3sGe2DEjlSG2w==  "/opt/iobroker/backups/influxDB_2023_06_27-14_20_10_backupiobroker" 2023/06/27 14:20:11 INFO: Downloading metadata snapshot Error: failed to backup metadata: failed to download metadata snapshot:  401 Unauthorized: read:authorizations is unauthorized
-- | -- | -- | --
backitup.0 | 2023-06-27 14:20:11.286 | error | [iobroker/influxDB]  Error: failed to backup metadata: failed to download metadata snapshot:  401 Unauthorized: read:authorizations is unauthorized
backitup.0 | 2023-06-27 14:20:11.286 | error | [iobroker/influxDB] 2023/06/27 14:20:11 INFO: Downloading metadata snapshot
backitup.0 | 2023-06-27 14:20:11.286 | error | [iobroker/influxDB]  Error: Command failed: influx backup --bucket iobroker -t  MjVkPdvDB55V65k4Yeftc_FqOUCM84cUxskAD3Ya-P3t8eYM6vwqYB8wTPwH8NPZGetTFgBcN3sGe2DEjlSG2w==  "/opt/iobroker/backups/influxDB_2023_06_27-14_20_10_backupiobroker"

</body></html>

**Comment by simatec** [comment]
Der Token ist nicht autorisiert für Backups. Du brauchst einen Admin-Token
https://github.com/simatec/ioBroker.backitup/wiki/Diverse-Anleitungen-f%C3%BCr-ioBroker.backitup#token-f%C3%BCr-influxdb-2x-backup-richtig-erstellen

**Comment by simatec** [comment]
Bitte schaue auch im Forum, hier das Issue ist dafür nicht geeignet.
Es ist kein Problem des Adapters.

**Comment by simatec** [comment]
> 401 Unauthorized: read:authorizations is unauthorized

Ist noch immer nicht der richtige Token

**Comment by MichaelSchaaf999** [comment]
Was kann ich anderes tun als dies:
<img width="251" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/ead6cc46-384f-4368-91c7-e83e52565685">

<img width="495" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/5ac47105-9e15-4f77-98ca-50c95250c54b">

[ERROR] [influxDB] - Error: Command failed: influx backup --bucket iobroker -t LqCPdY0hdUpmknWfuo7LIDFq7oiPpHcKShsqaVzcLlQP0xjuWQ3Q4KNJSmIXTFx5WsTewuWiYecoDPMjCHrUQw== "/opt/iobroker/backups/influxDB_2023_06_27-17_31_11_backupiobroker"
2023/06/27 17:31:11 INFO: Downloading metadata snapshot
Error: failed to backup metadata: failed to download metadata snapshot: 401 Unauthorized: read:authorizations is unauthorized

**Comment by MichaelSchaaf999** [comment]
Soll ich denn NOCHmal einen All Access API Token generieren? Zweimal hab ich das schon gemacht. Ohne Erfolg, der Adapter meldet immer Fehler.

**Comment by simatec** [comment]
Zeige doch mal bitte deine Einstellungen... Grundsätzlich bist du aber wie bereits erwähnt, im Forum mit deinem Problem besser aufgeheben.
In Issues geht es um Fehler und Features

**Comment by MichaelSchaaf999** [comment]
<img width="1185" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/da14489e-f7f6-4ab0-bfce-55c4de4372d2">

<img width="1185" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/96542241-3586-416f-ad12-9a514600acb8">

<img width="1185" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/0fcd4705-c712-429c-b8aa-7c59c3af7842">

<img width="1185" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/79d5fbce-18f1-498f-b72f-d0ce60dc4797">

<img width="1185" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/c3ed96b4-d564-4c81-9c64-798d46a4ca73">

<img width="1185" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/592ac57d-d092-46b5-aeaf-225190e1aaee">

<img width="1185" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/4f616e93-d9c2-418c-b0e3-cf721233d551">

<img width="1185" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/be610691-6aba-4e49-bb0f-6ced85980153">

<img width="1185" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/6716b10f-9932-4daa-905f-40a3841218a5">

**Comment by simatec** [comment]
Was sagt denn `influx auth list -t <TOKEN> --json`

**Comment by MichaelSchaaf999** [comment]
wenn ich mich nicht vertippt habe (leider funktioniert cut and paste in der Proxmox-iOBroker-Console nicht, also ganzen Token eingetippt), dann kommt auch der Fehler:
![image](https://github.com/simatec/ioBroker.backitup/assets/53481090/51745d20-ef3a-49b3-9569-1604af87499e)

**Comment by simatec** [comment]
Dann hast du leider den Token falsch erstellt... Hast du nicht den Admin Token aus der Influx Installation notiert oder gesichert?
Wie du ihn wiederherstellst, ist in dem Link oben beschrieben

**Comment by simatec** [comment]
PS: Bei mir geht Copy&Paste am Mac... Was nutzt du für ein Terminal?

**Comment by MichaelSchaaf999** [comment]
In Promox ist eine VM mit dem iOBroker: Die Console ist ein "noVNC" Fenster, das ich dort aufmachen kann. Das geht auch gut: Allerdings kann es kein paste aus dem Clipboard.

**Comment by MichaelSchaaf999** [comment]
Console vom Mac auf iOBroker:
michaelschaaf@Michaels-MacBook-Pro-2 ~ % ssh michael@192.168.178.201
ssh: connect to host 192.168.178.201 port 22: Connection refused

**Comment by MichaelSchaaf999** [comment]
Betreffend Deine Anleitungen unter https://github.com/simatec/ioBroker.backitup/wiki/Diverse-Anleitungen-f%C3%BCr-ioBroker.backitup#token-f%C3%BCr-influxdb-2x-backup-richtig-erstellen: 
- Das erste gelistete Token ist NICHT "das Operator-Token", sondern das "admin's Token".
- Damit läuft BackitUp aber auch auf den Fehler.

Ich habe diese Tokens in Influx, konnte jetzt den Befehl ausführen (mit dem "LqCPdY0hd..."-Token):

admin's Token
<img width="413" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/0bbddb47-34f5-4700-b7ad-1e774109ee4b">
Usw

manuell angelegter all-access-Token, eigentlich für BackitUp
<img width="414" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/b9e9b5b5-9680-421a-aa25-c3da473ce4aa">
Usw

noch ein weiterer manuell angelegter all-access-Token
<img width="420" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/b59c3445-232b-4d6d-8154-bf4fd0490df3">
Usw

Wenn ich, wie in der Anleitung https://github.com/simatec/ioBroker.backitup/wiki/Diverse-Anleitungen-f%C3%BCr-ioBroker.backitup#token-f%C3%BCr-influxdb-2x-backup-richtig-erstellen empfohlen, das Backup mit dem admin's Token manuell ausführe:
influx backup -- bucket iobroker --host http://192.168.178.201:8086 -t NYSWvZssOLdQInfdbYIsXrd0BXYknyt-13kYzYahWcDD1qRSGs4kLyeLamtzZoNqpRT-_xBqDbxUMLMNRObnqA== "/tmp/influx-test"   

...kommt dies:
![grafik](https://github.com/simatec/ioBroker.backitup/assets/53481090/024f8a2f-9896-4e63-8400-95ac9b23be67)

**Comment by simatec** [comment]
> * Das erste gelistete Token ist NICHT "das Operator-Token", sondern das "admin's Token".

Ist am Ende das selbe... Aber genau den benötigst du für die rechte bei einem Backup

**Comment by MichaelSchaaf999** [comment]
Die Begrifflichkeit von "Operator" und "admin's" Token ist schon etwas verwirrend. Aber egal.

NYSWvZssOLdQInfdbYlsXrd0BXYknyt-13kYzYahWcDD1qRSGs4kLyeLamtzZoNqpRT-_xBqDbxUMLMNRObnqA==
...ist ja dann nach unserem allgemeinen Verständnis das Admin's Token mit dem es gehen sollte.

Der auth-command sagt: 
influx auth list -t NYSWvZssOLdQInfdbYlsXrd0BXYknyt-13kYzYahWcDD1qRSGs4kLyeLamtzZoNqpRT-_xBqDbxUMLMNRObnqA== --json

![grafik](https://github.com/simatec/ioBroker.backitup/assets/53481090/857337ba-b041-425d-b585-4e4c6622ddf9)

<img width="253" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/a3dd04b9-af27-4eab-9d10-83681c224cfb">

Aber der manuelle Backitup-command zeigt Fehler:

influx backup -- bucket iobroker --host http://192.168.178.201:8086 -t NYSWvZssOLdQInfdbYlsXrd0BXYknyt-13kYzYahWcDD1qRSGs4kLyeLamtzZoNqpRT-_xBqDbxUMLMNRObnqA== "/tmp/influx-test"   

<img width="454" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/d2579d67-3c22-411a-851d-69da0687228d">

Also mit dem anscheinend richtigen Admin's Token läuft Backitup nicht.

**Comment by MichaelSchaaf999** [comment]
HomeMatic CCU: Jetzt sichern...
...führt zu Logeintrag

backitup.0 | 2023-06-30 15:13:05.884 | error | [ccu] Error: self-signed certificate
-- | -- | -- | --
backitup.0 | 2023-06-30 15:13:05.884 | error | [ccu/ccu] Error: self-signed certificate

Und im Ausführungsfenster:
Started ccu ...
[DEBUG] [mount] - mount activ... umount is started before mount!!
[DEBUG] [mount] - umount successfully completed
[DEBUG] [mount] start with {"mountType":"CIFS","type":"storage","source":"cifs","mount":"192.168.178.75","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":true,"ownDir":true,"dir":"/_Backups_MacBook/CCU_Backups","dirMinimal":"/_Backups_MacBook/Raspi1_IOBroker/Komplett","user":"Backups","pass":"****","ignoreErrors":false}
[DEBUG] [mount] - noserverino option: false
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=Backups,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=1.0 //192.168.178.75/_Backups_MacBook/CCU_Backups /opt/iobroker/backups"
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [ccu] - CCU-Backup started ...
[ERROR] [ccu] - Error: self-signed certificate
[DEBUG] [ccu] start with {"type":"creator","time":"01:30","debugging":true,"everyXDays":"3","deleteBackupAfter":0,"signedCertificates":true,"ignoreErrors":false,"cifs":{"enabled":true,"mountType":"CIFS","type":"storage","source":"cifs","mount":"//192.168.178.75","debugging":true,"fileDir":"/opt/iobroker/iobroker-data/backitup","wakeOnLAN":false,"macAd":"20:DE:20:DE:20:DE","wolTime":"25","smb":"vers=1.0","sudo":true,"cifsDomain":"","clientInodes":false,"deleteOldBackup":true,"ownDir":true,"dir":"/_Backups_MacBook/CCU_Backups","dirMinimal":"/_Backups_MacBook/Raspi1_IOBroker/Komplett","user":"Backups","pass":"****","ignoreErrors":false,"context":{"fileNames":[],"errors":{},"done":["umount","mount"],"types":[]},"adapter":null,"ccuEvents":[]},"historyHTML":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"historyJSON":{"enabled":true,"type":"message","entriesNumber":"25","ignoreErrors":false,"systemLang":"de"},"telegram":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"telegram.0","SilentNotice":false,"NoticeType":"longTelegramNotice","User":"allTelegramUsers","onlyError":false,"telegramWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"email":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"email.0","NoticeType":"longEmailNotice","emailReceiver":"xxx@xxx.com","emailSender":"xxx@xxx.com","onlyError":false,"emailWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"pushover":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","SilentNotice":false,"NoticeType":"longPushoverNotice","deviceID":"","onlyError":false,"pushoverWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"whatsapp":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longWhatsappNotice","onlyError":false,"whatsappWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"signal":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longSignalNotice","onlyError":false,"signalWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"matrix":{"enabled":true,"notificationsType":"Telegram","type":"message","instance":"","NoticeType":"longMatrixNotice","onlyError":false,"matrixWaiting":0,"hostName":"","ignoreErrors":false,"systemLang":"de"},"host":"192.168.178.200","user":"Admin","usehttps":true,"pass":"****","ccuEvents":[],"ccuMulti":false,"backupDir":"/opt/iobroker/backups"}

...endet nicht, bleibt so stehen.

**Comment by MichaelSchaaf999** [comment]
**Summary:**

NYSWvZssOLdQInfdbYlsXrd0BXYknyt-13kYzYahWcDD1qRSGs4kLyeLamtzZoNqpRT-_xBqDbxUMLMNRObnqA==
...ist ja dann nach unserem allgemeinen Verständnis das Admin's Token mit dem es gehen sollte.

**Der auth-command funktioniert mit diesem Token:**
influx auth list -t NYSWvZssOLdQInfdbYlsXrd0BXYknyt-13kYzYahWcDD1qRSGs4kLyeLamtzZoNqpRT-_xBqDbxUMLMNRObnqA== --json

<img width="807" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/81b99d63-fd38-4529-a8f8-323fb1e3b69d">



**Aber der manuelle Backitup-command mit diesem Token zeigt Fehler:**

influx backup -- bucket iobroker --host http://192.168.178.201:8086/ -t NYSWvZssOLdQInfdbYlsXrd0BXYknyt-13kYzYahWcDD1qRSGs4kLyeLamtzZoNqpRT-_xBqDbxUMLMNRObnqA== "/tmp/influx-test"

<img width="454" alt="grafik" src="https://github.com/simatec/ioBroker.backitup/assets/53481090/e553bbf0-7b55-4523-8bf8-fd4c2a481f63">


**Also mit dem anscheinend richtigen Admin's Token läuft Backitup nicht.**

Die Information "Dann hast du leider den Token falsch erstellt... " ist nicht zielführend, weil dieser Token ja anscheinend doch richtig ist, nur nicht mit BackitUp funktioniert.
Der Hinweis "Grundsätzlich bist du aber wie bereits erwähnt, im Forum mit deinem Problem besser aufgeheben." ist auch nicht zielführend, weil ich ja nicht mit anderen Awendern Ratespielchen durchführen möchte, sondern vom Ersteller des Adapters fundierte Hinweise zur Lösung erwarte.

So ist der Adapter BackitUp leider NICHT brauchbar und nicht zu empfehlen, deshalb werde ich ihn wohl löschen müssen.

**Comment by simatec** [comment]
> HomeMatic CCU: Jetzt sichern... ...führt zu Logeintrag
> 
> backitup.0	2023-06-30 15:13:05.884	error	[ccu] Error: self-signed certificate
> backitup.0	2023-06-30 15:13:05.884	error	[ccu/ccu] Error: self-signed certificate

Nimm den Hacken "Nur signierte Zertifikate zulassen" raus

**Comment by simatec** [comment]
> Die Information "Dann hast du leider den Token falsch erstellt... " ist nicht zielführend, weil dieser Token ja anscheinend doch richtig ist, nur nicht mit BackitUp funktioniert. Der Hinweis "Grundsätzlich bist du aber wie bereits erwähnt, im Forum mit deinem Problem besser aufgeheben." ist auch nicht zielführend, weil ich ja nicht mit anderen Awendern Ratespielchen durchführen möchte, sondern vom Ersteller des Adapters fundierte Hinweise zur Lösung erwarte.
> 

Finde ich ziemlich vermessen von dir, da wir zum einen in unserer Freizeit für Leute wie dich diese Adapter und das ganze ioBroker System entwickeln und zum anderen der Adapter Backitup die offizielle Backup Methode von Influx nutzt.
Also sind deine Beschwerden über den richtigen oder falschen Token nicht in backitup zu suchen, sondern bei den Entwicklern von Influx richtig aufgehoben.
Dort wird auch eindeutig angegeben, dass du den Root-Autorisierungstoken (der Token, der für den ersten Benutzer im [InfluxDB-Setup-Prozess](https://docs.influxdata.com/influxdb/v2.0/get-started/) erstellt wurde).

https://docs.influxdata.com/influxdb/v2.0/backup-restore/backup/#

Wenn du keine Anleitungen liest, suche nicht bei den Adaptern die Schuld.

Auch in den Anleitungen von Backitup wird immer wieder auf die Doku von InfluxDB hingewiesen.

Nochmal, wir machen hier diese Arbeit genau für euch in unserer Freizeit und stellen alles kostenlos zur Verfügung.
Da kann man sich solche Post sparen und das Forum mit der Community ist genau für solche Fragen und Hilfestellungen die richtige Adresse!!


> So ist der Adapter BackitUp leider NICHT brauchbar und nicht zu empfehlen, deshalb werde ich ihn wohl löschen müssen.

Keiner zwingt dich dazu ... Aber jammere nachher nicht, wenn dein System Schrott ist und du kein vernünftiges Backup hast... Aber wahrscheinlich ist dann auch der iobroker schuld ...

**Comment by MichaelSchaaf999** [comment]
Nein-nein, natürlich liegt es nicht an Backitup.

Nochmal final eine kleine **Summary**:

- Jetzt fand ich bzw. jetzt schreibst Du, dass influxdb vom "_root authorization token_" spricht, den der influx backup command verlangt. Bislang hatte dies Token bei Dir immer andere und unterschiedliche Namen. Und Deine "Diverse Anleitungen für ioBroker.backitup" benutzen das Wort "_root..._" überhaupt nicht.

- Deine "Diverse Anleitungen für ioBroker.backitup" sprechen allerdings vom "_Operator-Token (manchmal auch als Master-Token bezeichnet)_" (Zitat-Ende) und nicht von diesem "root authorization token". Auch die Bezeichnung "_Admin-Token_" benutzt Du. 

- Deine Anleitung "Token für InfluxDB 2.x Backup richtig erstellen" spricht davon, dass man dafür ein "_ein all-access API Token_" erstellen soll - das ist anscheinend nicht richtig, weil Backitup damit nicht läuft.

- Das erste gelistete Token beim "_influx auth list..._" command ist laut Deiner Beschreibung "das Operator-Token", "_Das Operator-Token in den ioBroker.backitup Adapter Einstellungen eintragen_", aber laut influxdb-Doku muss es das "root authorization token" sein und das ist etwas anderes als ein Operator-Token. 

- Und das erste gelistete Token ist bei uns das Admin's Token, damit funktioniert Backitup aber irgendwie auch nicht.  

- Wie man ein Admin's Token wiederherstellt beschreibst Du: "_Hast du nicht den Admin Token aus der Influx Installation notiert oder gesichert? Wie du ihn wiederherstellst, ist in dem Link oben beschrieben_". Doch, ich habe diesen Admin's Token.
Leider funktioniert Dein Link auf "https://www.rajchert.net/?p=1026" aber **nicht**: "Connection timed out Error code 522".

Wenn Du selbst keine influxdb-Anleitungen liest bzw. falsch bzw. missverständlich wiedergibst (das ist, glaube ich, das Hauptproblem) und viele verschiedene Begriffe für das Token benutzt, dann muss man sich nicht wundern, dass das alles nicht eindeutig ist. 
Aber natürlich liegt es nicht am Adapter Backitup und nicht an der dazugehörigen Doku. Denn Dein Rat lautet ja, dass wir "bei den Entwicklern von Influx richtig aufgehoben" sind. Vielen Dank dafür. 

Da nützt auch Dein mimimi-wir-machen-alles-in-unserer-Freizeit-und-stellen-alles-kostenlos-zur-Verfügung nichts, wenn Deine Doku und Deine Hinweise einfach irreführend und auch teilweise falsch sind.
Liefere doch bitte erstmal fehlerfreie und unmissverständliche Anleitungen für Backitup, bevor Du über die Nutzer schimpfst und auf die Entwickler von influxdb verweist. Schon mal was von Qualitätssicherung gehört? Im User Acceptance Test hat Dein Adapter samt sog. Dokumentation auf jeden Fall schlechte Karten, da bist Du durchgefallen.

Soweit also "ein Stern", besser "kein Stern". Keine Empfehlung.

Und als Nachsatz: Wenn mein System sich mal schrotten sollte, dann habe ich genügend andere Backups, und Deine Unterstellung "_wahrscheinlich ist dann auch der iobroker schuld_" ist völlig aus der Luft gegriffen.

**Comment by simatec** [comment]
Sorry.. da bist du an der falschen Adresse... Die Anleitung zum wiederherstellen des Token ist nicht von mir, sondern aus der [Community](https://forum.iobroker.net/post/963732)... Darum auch die Bitte, dich an das Forum zu wenden. Dort sind viele User, die sich bis ins kleinste Detail damit beschäftigen.

Wenn du weiterhin der Meinung bist, hier beleidigend zu sein, werde ich dich sperren und deine Beiträge löschen.

Das was du hier schreibst, ist eine absolute Frechheit und respektlos gegenüber allen Entwicklern.
Wegen Leuten wie dir, wird es auf lange Sicht solche Projekte wie den iobroker nicht mehr geben.

Keine will sich so eine Frechheit geben und sich für seine freiwillige Arbeit (und glaube mir, hier steckt sehr viel Freizeit drin) beleidigen lassen.

Kauf dir ein System für ein paar tausend Euro und lass es mit dem iobroker einfach sein und uns in Ruhe unsere Freizeitarbeit machen
