### ISSUE TITLE
iOBroker.backitup: Adapter und Dokumenation mangelhaft und fehlerhaft

### ISSUE THREAD

**Issue by MichaelSchaaf999** [simatec/ioBroker.backitup#964]
Lieber simatec,

Beiträge löschen ist immer die ultima ratio, wenn jemand nicht mehr weiter weiß.
Wenn sich simatec handgreiflichen Argumenten gegenüber nicht mehr gewachsen zeigt und auf berechtigte fachliche Mängel und Kritik mit keinem Wort mehr eingeht, dann bestätigt das meine Annahme, dass da ja irgendwas an der Kritik ja wohl dran sein muss.
**Beleidigend war ich übrigens zu keinem Zeitpunkt.** Wenn Du aber sachliche Kritik an Deiner fehlerhaften und missverständlichen Dokumentation als Beleidigung auffasst, dann hast Du ein Problem. Daran solltest Du mal arbeiten und nicht einfach nur Beiträge löschen.

Und wenn Du dann noch zudem den iOBroker als "Freizeitarbeit" charakterisierst, dann wird das die iobroker-GmbH nicht sonderlich freuen. Immerhin machen die mit dem Produkt Business. 
Wenn ich Dich da aber missverstanden haben sollte und Du den Begriff "Freizeitarbeit" nur auf Dich und Deine Arbeit an Adapter und Dokumentation beziehst, dann sei es so. 

Entwickler haben übrigens meine höchste Anerkennung, sofern sie qualitativ gute Arbeit abliefern und nicht nur rumbasteln. Und insofern verdienen sie auch meinen höchsten Respekt. Wenn sie allerdings fehlerhafte Arbeit abliefern und dann auch sachlich fachlicher Kritik daran nicht aufgeschlossen gegenüberstehen, dann endet meine Anerkennung. Und wenn sie dann noch Meinungsäußerung durch Löschen von Beiträgen quittieren, dann endet auch mein Respekt. 

p.s.: Der Link von Dir zur Anleitung zum Wiederherstellen des Tokens in der Community ist nicht von der Community - das ist DEIN Link. Und der ist **fehlerhaft**, sorry. Das hast Du anscheinend nicht richtig verstanden: Der von Dir in Deinem Beitrag wiedergegebene **Link ist falsch**. Warum verweist Du da auf die Community? DU hast einen falschen Link in DEINEM Beitrag.
In DEINEM Beitrag _"https://github.com/simatec/ioBroker.backitup/wiki/Diverse-Anleitungen-f%C3%BCr-ioBroker.backitup#token-f%C3%BCr-influxdb-2x-backup-richtig-erstellen_" gibt es bei Dir den Punkt 5:
"_5. Wenn es keinen solchen Eintrag gibt, dann wurde das Operator-Token gelöscht. Auch das kann repariert werden. Hier ist ein [Link](https://www.rajchert.net/?p=1026) zu einem Artikel Link_".
Der Artikel, den Du meinst, mag in der Community stehen, aber Dein darauf verweisender Link ist FALSCH.
Was an "falscher Link" hast Du nicht verstanden? Es kommt eine Fehlermeldung, wenn man diesem Link durch Anklicken folgen möchte. Und das liegt nicht in der Verantwortung der Community, das liegt in DEINER Verantwortung. 
Und das ist auch nicht beleidigend, das ist fachliche/sachliche Kritik.

**Comment by simatec** [comment]
Ich werde deine Aussagen bezüglich deiner nicht sachlichen und fehlerhaften Argumenten nicht weiter kommentieren.

Nur generell nochmal, das [Wiki](https://github.com/simatec/ioBroker.backitup/wiki/Diverse-Anleitungen-f%C3%BCr-ioBroker.backitup) ist mit Beiträgen von Usern aus dem [Forum ](https://forum.iobroker.net/topic/63694/aufruf-zur-unterst%C3%BCtzung-f%C3%BCr-backitup-wiki?page=1) entstanden und nicht von mir geschrieben.

Die offizielle Dokumentation zum Adapter findest du [hier](https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch)

Die Richtigkeit der Beiträge und Änderungsvorschläge kannst du gerne in dem Thread im Forum diskutieren.
Und ja... ein Link kann auch mal down sein... Für Abschaltungen von externen Webseiten kann keiner was und als @ostfrieseunterwegs diesen Beitrag geschrieben hat, war der Link aktuell.

Du unterstellst mir Dinge und beleidigst mich in den Issue und genau aus diesem Grund habe ich das Issue gelöscht.
Ich habe dir mehrere Tage Hilfe und immer wieder Tipps gegeben, um gemeinsam dein Problem zu lösen.

Deine Reaktion kann ich von daher nicht verstehen.

Und noch einmal zur Aufklärung... iobroker ist ein Open-Source Projekt und "ALLE" Entwickler machen das in ihrer Freizeit.
Kein Entwickler ist in der iobroker GmbH angestellt und bekommt Geld für seine Arbeit.

Die iobroker GmbH gibt es für kommerzielle Dinge, wie Cloud etc.

Wenn du nun weiterhin der Meinung bist, hier zu beleidigen, ohne irgendwelche Dinge und Zusammenhänge zu sehen und zu verstehen, dann werde ich dich hier sperren!

Wie @Apollon77 dir bereits schon einmal geschrieben hat, wenn du ein System mit 24/7 Support erwartest, dann musst du dich bei kommerziellen Lösungen umschauen.

iobroker ist ein Open Source Projekt, wo alle Entwickler in ihrer Freizeit dran arbeiten und manchmal kann es halt sein, dass da auch andere Dinge wie Job und Familie Priorität haben.

Wen dies für dich ein Problem ist, dann solltest du ein kommerzielles System erwerben.

**Comment by Apollon77** [comment]
@MichaelSchaaf999 Hi, ich möchte zu einem Aspekt in der Diskussion gern noch meinen Senf dazu geben, um sicherzustellen das hier keine unklaren Vorstellungen herrschen.

ioBroker ist ein Open-Source-Projekt und wird daher zu sehr großen Teilen von freiwilligen Entwicklern gestemmt. Das gesamte System (!!) existiert auf dieser Basis und wird in der Freizeit und "nebenher" entwickelt. Auch ENtwickler haben unterschiedliche Kenntnisstufen und wir fruen uns über jeden der etwas beisteuert auch wenn es mal nicht perfekt ist. Die User - ist die Erwartung im gegenzug - sollten verständnisvoll reagieren. Keiner macht absichtlich Fehler, aber sie passieren nun mal.

Es ist korrekt das es auch die ioBroker GmbH gibt, welche bestimmte Dienstleistungen rund um ioBroker anbietet, aber damit auch zB das Forum, die Webseite und viele andere "Infrastrukturthemen" des Open-Source-Projekts finanziert und bereitstellt. Aber auch die Entwicklungsleistung der GmbH kommt zu gewissen Teilen dann wieder dem Open-Source-projekt bzw einzelnen Adaptern zugute - oder sind spezialaufträge.

Alles in allem ist exakt EIN Entwickler bei der ioBroker GmbH angestellt, der auch gleichzeitig deren Geschäftsführer ist.

In dem Zuge ist es korrekt das die GmbH natürlich ein Interesse an einem gesunden Projekt hat, aber genauso auf die vielen freiwilligen Entwickler, ich bin einer davon, @simatec aber genauso. angewiesen ist.
Backitup ist ein wichtiger Adapter, aber dennoch Open-Source und bereitgestellt von @simatec in seiner Freizeit.

Open-Source lebt davon das die Entwickler und die User gut zusammenarbeiten und sich gut unterstützen. Auf Fehler hinweisen und den Entwickler unterstützen es zu beheben ist daher essentiell. Das trifft auch auf Doku zu. Von daher ist backitup froh über jeden User der Doku u.ä. bereitstellt - so ist das Wiki entstanden. Bei Fehlern sagen oder direkt ändern ... so sollte es laufen.

Mir ist durchaus bewusst das vor allem das Thema Webseite, Doku u.ä. bei ioBroker eine große Schwachstelle ist - da sind wir Ressourcenmäßig nicht gut aufgestellt ... Es fehlen Freiwillige die sich mal um soetwas kümmern ...  Meist sind die Entwickler die schlechtesten dokumentierer - weil Sie viel zu tief drin stecken ... Ist ein Dilemma ...

Aber wie immer gilt ... gemeinsam kriegt man alles gewuppt.

Ingo
