### ISSUE TITLE
The temporary directory "/opt/iobroker/backups/grafana_tmp" could not be deleted

### ISSUE THREAD

**Issue by barznet** [simatec/ioBroker.backitup#965]
**Describe the bug**  
Backup automatisch oder manuell, spielt keine Rolle. Backup auf Sinology (cifs/smb)

Ordner "grafana_tmp" auf Sinology kann problemlos manuell gelöscht werden. Der Prozess selbst läuft korrekt ab, wenn ich das richtig verstanden habe. Backup Datei grafana_2023_07_03-1.._backupiobroker.tar.gz ist vorhanden.

Ich habe schon alles mögliche probiert, kann leider den Fehler nicht finden. 

**Screenshots & Logfiles**  

**BackupIT** 

![instances - iobroker 2023-07-03 14-03-03](https://github.com/simatec/ioBroker.backitup/assets/8721373/27bce056-4019-455f-852f-7e10e541202c)

**Sinology** 

![image](https://github.com/simatec/ioBroker.backitup/assets/8721373/ff3e73f9-298d-4d77-8a99-f4866c5e4ae6)

**Synology Backup Pfad:** 

![image](https://github.com/simatec/ioBroker.backitup/assets/8721373/ec08eb9b-ef8b-4aa1-8ae9-af4ba4b38416)

**Iobroker** 

![michael — michael@iobroker: :opt:iobroker:backups — ssh michael@192 168 178 100 — 184×55 2023-07-03 14-06-17](https://github.com/simatec/ioBroker.backitup/assets/8721373/89559aed-7360-43b1-b264-865360e2c5f1)

`Started iobroker ...
[DEBUG] [mount] - noserverino option: false
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=backup_iobroker,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=3.0 //192.168.178.28/backup_iobroker /opt/iobroker/backups"
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.iobroker 21441 states saved

[DEBUG] [iobroker] - host.iobroker 24270 objects saved

[ERROR] [iobroker] - host.iobroker One or more optional files are corrupted: host.iobroker /opt/iobroker/node_modules/iobroker.js-controller/tmp/backup/files/vis.0/HeatingControl/iobroker-heatingcontrol-vis-master/.vscode/launch.json is not a valid json file

[ERROR] [iobroker] - host.iobroker Please ensure that self-created JSON files are valid

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2023_07_03-13_52_02_backupiobroker.tar.gz

[DEBUG] [iobroker] - done
[DEBUG] [zigbee] - found zigbee database: zigbee.0
[DEBUG] [zigbee] - done
[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
[DEBUG] [grafana] - found Dashboard: general-alerting
[DEBUG] [grafana] - found Dashboard: wetter
[DEBUG] [grafana] - found Dashboard: thermostat
[DEBUG] [grafana] - found Dashboard: proxmox
[DEBUG] [grafana] - found Dashboard: bwm_og
[DEBUG] [grafana] - found Dashboard: warmepumpe
[DEBUG] [grafana] - found Dashboard: samsung-tab-akku
[DEBUG] [grafana] - found Dashboard: h2o
[DEBUG] [grafana] - start Grafana backup compress ...
[DEBUG] [grafana] - Backup created: /opt/iobroker/backups/grafana_2023_07_03-13_52_11_backupiobroker.tar.gz
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
**[ERROR] [grafana] - The temporary directory "/opt/iobroker/backups/grafana_tmp" could not be deleted. Please check the directory permissions and delete the directory manually**
[DEBUG] [grafana] - done
[DEBUG] [jarvis] - Created jarvis_tmp directory: "/opt/iobroker/backups/tmpJavis0"
[DEBUG] [jarvis] - found Jarvis Instance: 0
[DEBUG] [jarvis] - start Jarvis Backup for Instance 0...
[DEBUG] [jarvis] - /opt/iobroker/iobroker-data/jarvis/0 copy success!
[DEBUG] [jarvis] - Created states_tmp directory: "/opt/iobroker/backups/tmpJavis0/states"
[DEBUG] [jarvis] - settings "notifications" not found
[DEBUG] [jarvis] - settings "widgets" not found
[DEBUG] [jarvis] - settings "scripts" not found
[DEBUG] [jarvis] - settings "pro" not found
[DEBUG] [jarvis] - Try deleting the Jarvis tmp directory: "/opt/iobroker/backups/tmpJavis0"
[DEBUG] [jarvis] - Jarvis tmp directory "/opt/iobroker/backups/tmpJavis0" successfully deleted
[DEBUG] [jarvis] - Backup created: /opt/iobroker/backups/jarvis.0_2023_07_03-13_52_17_backupiobroker.tar.gz
[DEBUG] [jarvis] - done
[DEBUG] [cifs] - used copy path: /backup_iobroker
[DEBUG] [cifs] - done
[ERROR] [clean] - Backup files not deleted from /opt/iobroker/backups because some errors.
[DEBUG] [clean] - done
[DEBUG] [telegram] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[DEBUG] [umount] - mount activ, umount is started ...
[DEBUG] [umount] - umount successfully completed
[DEBUG] [umount] - done
[EXIT] 0`

**Versions:**  
 - Adapter version: 2.6.23
 - JS-Controller version: 4.0.24
 - Node version: 18.16.0
 - Operating system: Debian 11 (in Proxmox)

**Comment by simatec** [comment]
Wie sehen die Berechtigungen für den Freigabeordner aus? So wie ich es aktuell sehe, hast du keine Berechtigung für die Unterordner.
Backups werden erstellt, aber der tmp ordner kann nicht gelöscht werden.

Schaue dir mal das grafana Backup an.
Das sollte vollständig sein.
Zeige mal bitte die Einstellungen für die Ordner- und Benutzerrechte

**Comment by barznet** [comment]
Ich vermute, dass das Problem bei neuer DSM Version von Synology liegt. Am 29 Juni habe ich ein Update eingespielt. Seitdem funktioniert Backup nicht korrekt. Das war https://www.synology.com/de-de/releaseNote/DSM?model=DS720%2B#ver_64570-1

**Comment by barznet** [comment]
Hier ist alles korrekt:

![Homeserver - Synology NAS 2023-07-03 15-39-28](https://github.com/simatec/ioBroker.backitup/assets/8721373/29ca28a8-f2cf-4065-ab32-383ef0067937)

**Comment by simatec** [comment]
Versuche mal NFS ... Die Synology kann das ja und es ist eigentlich die bessere Wahl
Dafür musst du auf deinem iob System aber nfs-common installieren

**Comment by barznet** [comment]
Danke für den Tipp, habe gewechselt und damit das Problem gelöst.

**Comment by simatec** [comment]
> Danke für den Tipp, habe gewechselt und damit das Problem gelöst.

Ist für Linux Systeme definitiv der bessere Weg ... Super, dass du es gelöst bekommen hast
