### ISSUE TITLE
Backup auf USB-Stick kopieren (Pfad wird nicht gefunden)

### ISSUE THREAD

**Issue by RALFISBORN** [simatec/ioBroker.backitup#967]
Hallo,

ich erstelle aktuell die Backups lokal (Standardpfad von Backitup). Jedoch möchte ich diese gerne zusätzlich auf einen angeschlossenen USB-Stick kopieren. 

Hier wird jedoch der eingestellte Pfad nicht gefunden obwohl dieser dem Pfad im Explorer entspricht:
![Fehlermeldung](https://github.com/simatec/ioBroker.backitup/assets/47441243/14a851fd-493a-4462-887b-e16e7988ea70)

**Das sind die Einstellungen im Adapter dazu:**
![Adapter-Einstellungen](https://github.com/simatec/ioBroker.backitup/assets/47441243/387e8258-b9ee-4c04-ab7b-1ad225fbd1f7)

Der Stick ist als exfat formartiert.

Im Log File werden auch nur folgende Infos angezeigt:
backitup.0
	2023-07-06 20:16:03.445	error	[iobroker] Path "/media/fritz/USB-STICK/IOBroker" not found
backitup.0
	2023-07-06 20:16:03.443	error	[iobroker/cifs] Path "/media/fritz/USB-STICK/IOBroker" not found

Was muss ich den Adapter/Stick/System konfigurieren, damit das Backup auf den USB-Stick abgelegt wird?

Das Setup (OS, Version, etc.) entspricht dem Issue:
https://github.com/simatec/ioBroker.backitup/issues/966

Vielen Dank

**Comment by simatec** [comment]
Wo ist der Stick genau gesteckt? Da schaut so nach Fritzbox aus

**Comment by RALFISBORN** [comment]
Nein der steckt direkt lokal am PC.

**Comment by simatec** [comment]
Dann zeige mal bitte die Rechte des Sticks... Kann der User "iobroker" darauf zugreifen (schreiben und löschen)?

`ls -lah /media/fritz/USB-STICK/IOBroker`

**Comment by RALFISBORN** [comment]
Ok, das scheint wohl ein Rechteproblem zu sein.

Ausgabe: ls -lah /media/fritz/USB-STICK/IOBroker
drwxr-xr-x 2 fritz fritz 128K Jul  6 19:29 .
drwxr-xr-x 5 fritz fritz 128K Jul  6 22:18 ..

Wie füge ich denn den Benutzer "iobroker" hinzu?

**Comment by simatec** [comment]
Den User und die Group kannst du mit folgenden Befehl ändern...

`sudo chown iobroker:iobroker /media/fritz/USB-STICK/IOBroker`

**Comment by RALFISBORN** [comment]
Dann kommt leider die Meldung: 
chown: der Eigentümer von '/media/fritz/USB-STICK/IOBroker' wird geändert: Vorgang nicht zulässig

**Comment by simatec** [comment]
Hmmm ist schon etwas blöd mit der Formatierung.
Der lief vorher ja sicher in einer Fritzbox. Gibt es die noch? Falls ja, würde ich einen CIFS Mount machen und dort die Backups ablegen.

Falls nicht, rate ich dir, den Stick in ext4 zu formatieren und sauber in das System einzubinden.

**Comment by RALFISBORN** [comment]
Ne, wie gesagt der Benutzer heißt nur leider Fritz :D. Aber der Stick war wirklich definitiv noch nicht mal in der Nähe einer FritzBox ;)

Ok, Danke für die Ansätze. Ext4 ist dann immer blöd, wenn ich den Stick auch unter Windows verwenden möchte.

Ich hab mir jetzt mal so beholfen:
- Ne .sh Datei erstellt, welche mit rsync die Dateien über den Benutzer fritz synchronisiert:
rsync -r -t -v --progress --delete --modify-window=1 -s /opt/iobroker/backups /media/fritz/USB-STICK/IOBroker

- Diese führe ich dann über einen Cronjob regelmäßig aus und synchronisiere dadurch die Backitup Backups mit den Stick.

Wie gesagt, es dient ja nur rein zum spiegeln der Dateien und muss daher nicht in Echtzeit synchronisiert werden.

So klappts dann auch wunderbar.

Aber Danke für die Hilfe ;)
