### ISSUE TITLE
Redis Backup Size 0kb

### ISSUE THREAD

**Issue by ChWeiler** [simatec/ioBroker.backitup#968]
**Describe the bug**  
Das Backup läuft durch und am Schluss kommt der Fehler: Backup files not deleted from /opt/iobroker/backups because some errors. 

**To Reproduce**  
1. Backup iobroker mit Redis

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: v2.6.23
 - JS-Controller version: 5.02
 - Node version: v18.15.0
 - Operating system: Debian 11

```
Started iobroker ...
[DEBUG] [mount] - noserverino option: false
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=backup,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=3.0 //192.168.178.201/backup/iobroker/iobroker_std /opt/iobroker/backups"
[DEBUG] [mount] - mount successfully completed
[DEBUG] [mount] - done
[DEBUG] [iobroker] - host.iobroker 29103 states saved

[DEBUG] [iobroker] - host.iobroker 33642 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2023_07_10-12_56_16_backupiobroker.tar.gz
This backup can only be restored with js-controller version up from 4.1

[DEBUG] [iobroker] - done
[DEBUG] [redis] - Start Redis Backup ...
[DEBUG] [redis] - Try deleting the old redis tmp directory: "/opt/iobroker/backups/redistmp"
[DEBUG] [redis] - old redis tmp directory "/opt/iobroker/backups/redistmp" successfully deleted
[DEBUG] [redis] - Created new redistmp directory
[DEBUG] [redis] - detected redis file: objects.rdb | file type: rdb
[DEBUG] [redis] - detected redis file: states.rdb | file type: rdb
[DEBUG] [redis] - Backup created: /opt/iobroker/backups/redis_2023_07_10-12_56_28_backupiobroker.tar.gz
[DEBUG] [redis] - Try deleting the redis tmp directory: "/opt/iobroker/backups/redistmp"
[DEBUG] [redis] - redis tmp directory "/opt/iobroker/backups/redistmp" successfully deleted
[DEBUG] [redis] - done
[DEBUG] [cifs] - used copy path: /backup/iobroker/iobroker_std
[DEBUG] [cifs] - done
[ERROR] [clean] - Backup files not deleted from /opt/iobroker/backups because some errors.
[DEBUG] [clean] - done
[DEBUG] [telegram] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
[DEBUG] [umount] - mount activ, umount is started ...
[DEBUG] [umount] - device is busy... wait 2 Minutes!!
[DEBUG] [umount] - umount successfully completed
[DEBUG] [umount] - done
[EXIT] 0
```

![image](https://github.com/simatec/ioBroker.backitup/assets/10938014/4d1a4a60-208a-4d0c-802d-ff70406f2e2d)

**Comment by simatec** [comment]
Schau mal [hier](https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch#redis-backup) in der Doku

`sudo usermod -a -G redis iobroker`
`sudo reboot`

**Comment by simatec** [comment]
Da hat sich aber in den letzten Versionen nichts geändert. Welche Version hast du laufen?
Hast du dein System mal neugestartet?

**Comment by ChWeiler** [comment]
Versionsnummer: Adapter version: v2.6.23
System wurde mehrere male schon neu gestartet.
Ich habe zwei rdb-Dateien. Eine für states und eine für objects.
Die sind auf einer Proxmox-VM. Redis hat zwei Instanzen. Eine für States (Port 6379) und Objects (Port 6380).

![image](https://github.com/simatec/ioBroker.backitup/assets/10938014/0245a4cb-2f6a-4ddb-ac88-17c6673c3d05)

![image](https://github.com/simatec/ioBroker.backitup/assets/10938014/ef091da4-0a12-4a74-b501-336d7821bad2)

**Comment by simatec** [comment]
Zeige mal bitte die Redis Einstellungen in Backitup.
Kannst du an irgendeinem Update festmachen, seit wann es nicht mehr läuft?
Eventuell js-controller Update?

Backitup selber hatte in v2.6.1 die letzten Änderungen für redis

**Comment by ChWeiler** [comment]
![image](https://github.com/simatec/ioBroker.backitup/assets/10938014/7eaa8b86-2479-4b2c-9b69-91af7cb919aa)

Ich habe auf den js-controler ein Update auf Version 5.02 gemacht.

![image](https://github.com/simatec/ioBroker.backitup/assets/10938014/f4613933-1d9d-482a-940e-439fe7de85ae)

**Comment by simatec** [comment]
Dann mache mal bitte ein Update... Aktuell ist die 5.0.7 ... Die 5.0.2 hatte noch ein paar kleinere Bugs

**Comment by ChWeiler** [comment]
ich habe die 4.0.24 wieder installiert. Es ist leider immer noch das gleiche Problem:
![image](https://github.com/simatec/ioBroker.backitup/assets/10938014/4fcff012-f00d-454a-a089-23bf7f22b2f2)

**Comment by ChWeiler** [comment]
Ich habe versucht herauszubekommen, wie das backup der Redis-DB gemacht wird. Habe aber leider im Code nichts gefunden.
Kann ich das irgendwie mal manuell anstoßen?

**Comment by simatec** [comment]
OK, dann gehen wir mal etwas tiefer.

Nimm mal in den Einstellungen von Backitup den letzten Slash weg

`/var/lib/redis`

Dann zeige mir mal bitte den Inhalt von dem Ordner

`ls -lah /var/lib/redis`

Dazu würde ich gerne mal die Rechte deines Users "iobroker" sehen

`cat /etc/group | grep iobroker`

**Comment by simatec** [comment]
Ok ... habe mir deine Config jetzt nochmal mit den 2 Files angeschaut.
So wie du es mit zwei Instanzen aufgebaut hast, müsstest du auch eine zweite Slave Instanz von Backitup erstellen.

Also wie folgt:
- neue Instanz von Backitup erstellen und diese Instanz als Slave konfigurieren (Der Slave-Namenszusatz ist optional).
- In der Slave Instanz aktivierst du nur Redis und gibts den Pfad `/var/lib/redis/states.rdb` an

- Die erste Instanz von Backitup erstellst du als Master und wählst unter Slaves die Slave Instanz aus. 
- Optional kannst du auch das stoppen der Slave Instanzen aktivieren (schadet nicht bei etwas schwachen RAM)
- im Master änderst du den Redis Pfad auf `/var/lib/redis/objects.rdb`

Wenn du jetzt über den Master das Backup startest, wird erst alles beim Master ausgeführt und im Anschluss dann das Slave Backup gestartet.

Vorteil dabei ist auch, dass du bei einer Wiederherstellung States und Objects getrennt voneinander wiederherstellen kannst.

**Comment by simatec** [comment]
Kein Problem ... Helfe sehr gerne 👍
