### ISSUE TITLE
Keine Fehlermail bei einem Mount ERROR

### ISSUE THREAD

**Issue by jogicom** [simatec/ioBroker.backitup#969]
**Fehlerbeschreibung**  
Bei einem Mount Error versendet BackitUp keine Fehlermail, auch das manuelle ausführen dieses Backups scheint bei der Fehlermeldung stehen zu bleiben.

**Reproduktion des Fehlers**  
1. erstelle eine Datensicherung für CCU auf ein NAS, wobei das Zielverzeichnis auf dem NAS existiert
2. Führe die Datensicherng manuell aus
3. Ergebnis OK
4. Lösche das Zielverzeichnis auf dem NAS oder verweigere die Berechtigung
5.  Führe die Datensicherung nochmals aus
6. Ergebnis = Die Datensicherung wird nicht beendet
7. Bei Ausführung per schedule, wird in diesem Fall keine Fehler EMail versendet und der Fehler bleibt unbemerkt

**Erwartetes Verhalten**  
Bei einem fehlerhaften mount, sollte BackitUp dies auch per EMail als Fehler melden, der Fehler wird zwar im ioBroker log verzeichnet, aber nicht weiter gemeldet.

**Screenshots & Logfiles**  
Verhalten bei Mount fehler (kein exit):
```
Started ccu ...
[DEBUG] [mount] - mount activ... umount is started before mount!!
[DEBUG] [mount] - umount successfully completed
[DEBUG] [mount] - noserverino option: false
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=ioBroker,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=3.0 //mydrive.de/AutoBackup/Homematic /opt/iobroker/backups"
[DEBUG] [mount] - first mount attempt with smb option failed. try next mount attempt without smb option ...
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=ioBroker,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //mydrive.de/AutoBackup/Homematic /opt/iobroker/backups"
[ERROR] [mount] - [undefined Error: Command failed: sudo mount -t cifs -o username=ioBroker,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //mydrive.de/AutoBackup/Homematic /opt/iobroker/backups
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

[ERROR] [mount] - Error: Command failed: sudo mount -t cifs -o username=ioBroker,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //mydrive.de/AutoBackup/Homematic /opt/iobroker/backups
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
```

**Versions:**  
 - Adapter version: 2.6.23
 - JS-Controller version: 4.0.24 
 - Node version: v18.16.1 
 - Operating system: linux (RaspberryPi 4) Raspian aktuell

**Additional context**  
Sieht aus, als ob BackitUp nach einem Mountfehler auf irgendetwas wartet und dadurch das manuelle (und auch automatische?) Backup nicht beendet.

Siehe auch [ioBrokerForum](https://forum.iobroker.net/topic/66809/backitup-sendet-keine-fehlermail-bei-einem-mount-error?_=1689154378898)

**Comment by simatec** [comment]
Fix in v2.7.0
