### ISSUE TITLE
Widerherstellung Fehlerhaft

### ISSUE THREAD

**Issue by lammy000** [simatec/ioBroker.backitup#975]
**Describe the bug**  
After a restore over the webinterface my VIS don't show some Widgets of materialdesigne BETA adapter

**To Reproduce**  
1. Go to 'Restore'
2. and wait
3. after the restore is complete, all "BETA" Adapter was not installed
4. the VIS Adapter can not load the BETA Visuals, in my case the problem comes from the materialdesign adapter
5. an reinstall not helped and i must used my "timeshift" backup function to rescue my system

**Versions:**  
 - Adapter version: v2.6.23
 - JS-Controller version: 4.0.24
 - Node version: Node.js: v16.18.1
 - Operating system: ubuntu 22
 - vis-materialdesign.0 v0.5.9
 - vis-material.0 v0.1.3
 - vis-material-advanced.0 v1.7.2
 - vis-material-webfont.0 v0.0.3

**Comment by simatec** [comment]
This is not a problem of Backitup. Backitup only restores the files and configs. The restore or the installation is done after the restart of the iobroker.

The topic is also known under VIS ... see link.

https://github.com/ioBroker/ioBroker.vis/issues/440

**Comment by simatec** [comment]
The Restore is from js-Controller remove and reinstall is ever for this Process. 

Backitup is only the GUI for Restore.

**Comment by lammy000** [comment]
Thanks for comment ... it was for my problem the correct way because all other bring me an damaged und runable VIS ;-)
