### ISSUE TITLE
WOL options configurable

### ISSUE THREAD

**Issue by flwilk** [simatec/ioBroker.backitup#978]
I'd like to have the wakeonlan option configurable to do something like this:

wakeonlan -i 192.168.10.255 -p 9 dd:ee:19:24:ac:fe (fake mac!)

With this settings and a proper configured port forward you have the option to wake a device in another subnet.

A german howto: https://www.heimnetz.de/anleitungen/firewall/opnsense/opnsense-wake-on-lan-ueber-vpn/

Would be great to add this feature. 

Alternative: Where to edit the code?

**Comment by simatec** [comment]
Backitup works with the npm Package [node-wol](https://www.npmjs.com/package/node-wol)

**Comment by flwilk** [comment]
Great, so the only thing needed is a field for the port an the ip-adress and it will work

**Comment by simatec** [comment]
Please test v2.8.0

**Comment by flwilk** [comment]
Works like a charm!

Thanks a lot!

**Comment by simatec** [comment]
thx ...
