### ISSUE TITLE
Fragen bzgl. Speicherort, Ausführungszeit, Vorhaltezeiten 

### ISSUE THREAD

**Issue by n0valis** [simatec/ioBroker.backitup#986]
Dies ist kein Bugreport, obwohl es vielleicht einer sein/werden könnte, aber ich möchte eigentlich erstmal ein paar Fragen klären wenn es recht ist, weil ich mir nicht sicher bin, ob backitup überhaupt verantworlich ist.

Ich habe mit der Festlegung NAS/kopieren (täglich um 22 Uhr) eigentlich einen externen Speicherort definiert, aber da die geplante Ausführung nie funktioniert, macht dies keinen Sinn mehr für mich. Das ist Problem #1. 
Warum das nicht funktioniert ist mir schleierhaft, vielleicht hat es mit der clock des Raspi zu tun, keine Ahnung, cronjobs funktionieren jedenfalls. Die Durchführung des Backups  an sich funktionert, nur eben zu total obsoleten Zeiten, Nachts um 4 oder morgens um 9 oder so. Meist ist das NAS dann gar nicht an und das Backup scheitert natürlich. Ist das NAS zur Durchführungszeit an, dann klappt auch das Backup.

Ich habe dann irgendwie zufällig entdeckt, dass die Backups auch lokal angelegt werden.
Der Speicheort /opt/iobroker/backups wird scheinbar aus irgendwelchen Gründen geheim gehalten und kannn auch nicht definiert werden? Warum ist das so? Das ist Problem Nummer#2

Im Backupverlauf sind nur die erfolgreichen Backups zum NAS aufgeführt. Nicht jedoch die gescheiterten/nicht durchgeführten.
Auch nicht die erfolgreichen lokalen Backups. Warum ist das so? Macht imho wenig Sinn.

Die Vorhaltezeit ist auf 5 eingestellt. Was auf den NAS auch stimmt. Die lokalen Backups enthalten jedoch 14 Versionen. Problem #3

Mit anderen Worten: Wenn nicht irgendwo im geheimen noch ein Backupprozeß läuft, dann ist das Verhalten des lokalen Backups völlig intransparent und nicht nachvollziehbar.
Da bei mir die zeitliche Steuerung nicht funktioniert - was auf dem Computer ein Backitup-exklusives Problem ist - dann mache ich lieber ein lokales Backup und spiegele das per cronjob zum NAS.
Aber dafür wäre natürlich eine Konfigurationsmöglichkeit nötig.
Im Moment finden man noch nichtmal die Angabe für den Pfad der lokalen Backups irgendwo.

Für sachdienliche Hinweise wäre ich dankbar.

local:
![localbackup](https://github.com/simatec/ioBroker.backitup/assets/24315173/fa392948-3f9c-483d-9304-fa18289ac97d)

NAS:
![NASbackup](https://github.com/simatec/ioBroker.backitup/assets/24315173/787be5c2-10b6-410b-ae74-becaa40151c1)

**Comment by buanet** [comment]
@n0valis Hast du dich mit deinen Fragen mal an die ioBroker Community gewandt? Dies hier ist normalerweise nicht der Ort um fragen zur Funktion/ zum Verständnis eines Adapters zu stellen. Es ist immer sehr ärgerlich und zeitraubend wenn Entwickler sich zu solchen Themen äußern müssen, die auch erfahrenere Anwender in der Community beantworten können.
Eine gute Anlaufstelle für deine Fragen wäre zum Beispiel das ioBroker Forum: https://forum.iobroker.net/
Hier gibt es massig Lesestoff zu Backitup und viele erfahrene User die mit lesen und helfen wo sie können. 

MfG,
André

**Comment by n0valis** [comment]
> 



> Hast du dich mit deinen Fragen mal an die ioBroker Community gewandt?

Nein, ich dachte ich wende mich mit so exakt die Programmierung betreffenden Issues besser an den direkt Verantwortlichen.
Aber wenn du das ärgerlich findest dann ist das OK. So wichtig ist das ganze jetzt auch nicht.
Im Forum würde ich lieber nicht nachfragen, dazu sind meine Anliegen glaube ich zu speziell.
Es sind echte issues und keine Verstädnissfragen.
Und wieso glaubst du dass ich die Zeit und die Lust hätte "massig Lesestoff" zu Backitup zu konsumieren.
Manchmal muss man sich schon wundern.
Kleiner Tip: Mach doch einfach die local Backups transparent und konfigurierbar.
Dann wäre der Adapter besser.

**Comment by buanet** [comment]
Dein Ernst jetzt???
Du hast doch genau so angefangen:

> Dies ist kein Bugreport, obwohl es vielleicht einer sein/werden könnte, aber ich möchte eigentlich erstmal ein paar Fragen klären wenn es recht ist, weil ich mir nicht sicher bin, ob backitup überhaupt verantworlich ist.

Und jetzt plötzlich:

> Es sind echte issues und keine Verstädnissfragen.

What?

> Im Forum würde ich lieber nicht nachfragen, dazu sind meine Anliegen glaube ich zu speziell.

What??? Genau dafür ist das Forum da! Mach ein Thema auf und dir wird geholfen und alles was du nicht verstehst wird dir erklärt.

> Und wieso glaubst du dass ich die Zeit und die Lust hätte "massig Lesestoff" zu Backitup zu konsumieren.

Suchfunktion sagt dir was? Dass es massig Stoff gibt, heißt nicht dass du alles lesen musst, sondern dass schon vieles beantwortet wurde.
Doku hast du aber schon gelesen, oder? 

> Manchmal muss man sich schon wundern.

Das tue ich gerade. Wo bist du denn falsch abgebogen? 

> Kleiner Tip: Mach doch einfach die local Backups transparent und konfigurierbar.
Dann wäre der Adapter besser.

Keule, den Ball mal ganz flach halten. Ich habe keine Aktien in dem Adapter, sondern dir lediglich den Hinweis gegeben deine Fragen doch erstmal im Forum zu klären. Der Grund ist, dass sich sonst an meiner Stelle unser lieber @simatec mit dir auseinandersetzen müsste. Und bei dem was du gerade ablässt, bin ich froh dass er seine Zeit noch nicht darauf verschwendet hat. :)

--------------------------------------------

Und jetzt beweise ich dir noch, dass du die Doku nicht gelesen hast:

Du: 

> Der Speicheort /opt/iobroker/backups wird scheinbar aus irgendwelchen Gründen geheim gehalten und kannn auch nicht definiert werden? 

Die Doku: 

> Jedes Backup wird standardmäßig im Verzeichnis /opt/iobroker/backups/ abgelegt.
Quelle: https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch#backuptypen

------------

Alter, echt jetzt. Tu den Entwicklern einen gefallen. Schließ diesen Issue, lies die Doku und stell deine Fragen zur Arbeitsweise des Adapters im Forum (auch wenn sie noch so speziell sind!!!).
Und wenn du dann tatsächlich ein Problem beim Adapter fest stellst, oder einen Feature-Wunsch hast, oder die Doku unvollständig ist, fang nochmal von vorne an und untermauere deinen Issue mit Logfiles, der exakten Konfiguration und den im Forum gesammelten Fakten, sodass dieser schnell und unkompliziert, ohne viele Nachfragen, von den Entwicklern abgearbeitet werden kann. So bekommst du von mir keine weiteren dummen Antworten und @simatec muss nicht unnütz seine Freizeit opfern...
Danke. 

MfG,
André

**Comment by simatec** [comment]
ioBroker verwendet die Systemzeit deines Hostsystems ... Wenn die nicht stimmt, kann dass weder ioBroker noch Backitup wissen.

Stelle die Systemzeit ein bzw. prüfe sie ....

`timedatectl`

`sudo timedatectl set-timezone Europe/Berlin`

Zu allem anderen hat @buanet bereits alles gesagt und ich schließe mich dem zu 100% an... Solche Issue sind einfach nur zum wegrennen und gehören geschlossen.

**Comment by n0valis** [comment]
Moin,
Ich finde eure Annahmen stellenweise haarsträubend.
Man wird angemacht weil man Fehler meldet und nicht im Forumm vorher alles abgegrast hat, dokus gelsen hat etc.
Das ist völlig realitätsfremd und gehört ins Land Nerdistan.

Zur von mir angesprochenen Transparenz gehört auch ein mindesmaß an info im Produkt selbst und nicht nur ins 
Wiki.
Wo ich war aber nichts gefunden habe.

Es gibt hunderte Adapter, soll man da von jedem die Herkunft aufspüren und Wiki durchlesen wenn mal was nicht geht.
Wenn ihr öfters im Forum Probleme zu lösen hättet, dann wüsstest ihr wie oft das neben einer erfolgreichen Lösung auch genauso oft in endlosen Diskussionen, falschen Ratschlägen, offtopic Labereien und schlicht zeitraubender Zeitverschwendung endet.
Mit gezielten Fragen an der Quelle ist man in der Regel besser bedient und oft nach ein zwei Runden fertig. 
Meistens funktioniert das hier auf Github gut und effizient.
Das ihr da kein Bock drauf habt ok eure Sache.
Ich habe gezielt meine Probleme beschrieben und in Fragen gekleidet. zB das die BAckups nicht geplant durchgeführt werden.
Und auch gesagt dass das ein Backitup exklusives Problem ist. Wie du da darauf kommst. dass die Systemzeit nicht stimmt ist mir schleierhaft.
Wie ich bereiets sagte "cronjobs funktionieren jedenfalls".
Es istgerade kurz nach 9:
# timedatectl
               Local time: Tue 2023-09-05 21:03:07 CEST

Das meiste was "Alter, echt jetzt" buanet von sich gegeben hat ist einfach arroganter Müll: "Und jetzt beweise ich dir noch, dass du die Doku nicht gelesen hast:" und nicht weiter kommentarwürdig.

und für dich simatec noch etwas konstruktive Kritik:
Niemand will buddeln gehen wenn es mal nicht so funktioniert wie gedacht. Deswegen ist eine vernüftige Strukturierung und Übersicht der Information das wichtigste neben dem eigentlichen Programm. Backitup hat da mM nach ein paar Defizite.

zB: Im Backupverauf wird nicht angezeigt wo lokale Backups liegen, nocht mal das welche gemacht werde. Jaja ich weiß
"Keule, den Ball mal ganz flach halten" buanet hat ja gesagt das steht im Wiki. Es gehört aber auch in die Übersicht des programms. Es gibt extra einen Menupunkt für Backiitup, also warum dort nicht unterbringen. NObrainer.

Wenn ich den Punkt NAS / Kopieren in den Haupteinstellungen anklicker erscheint ein zusätzlicher Reiter für die Einstellungen des Verbindungstyp etc. DAs habe ich zuerst gar nicht bemerkt. Habe mich erstmal gewundert warum dort nichts passiert.
Das kann doch genausogut in den Haupteinstellungen erfolgen direkt unterhalb von dem Punkt wo man es aktiv schaltet.
Oder alternativ einen fixen ReiterSpeicherorte mit allen Einstellungen für alle Speicherorte.

Genauso die EInstellungen unter iobroker. Da steht jetzt nur Sicherungszeit und Anzahl etc. 
Das sind doch defakto auch Haupteinstellungen und rechtfertigen nicht wirklcih einen eigenen Reiter. Es wird dadurch nur komplizierter und unübersichicher.

**Comment by buanet** [comment]
> Man wird angemacht weil man Fehler meldet und nicht im Forumm vorher alles abgegrast hat, dokus gelsen hat etc.
Das ist völlig realitätsfremd und gehört ins Land Nerdistan.

Du hast offenbar keine Ahnung wie der Hase läuft. 

> Zur von mir angesprochenen Transparenz gehört auch ein mindesmaß an info im Produkt selbst und nicht nur ins Wiki.

Nein, eben nicht. Admin Oberflächen sind zum Konfigurieren da. Nicht zum Beschreiben der Funktion einer jeden Option. Die "Transparenz" ist, dass der Entwickler eben eine Doku/ ein Wiki oder eine Readme anbietet in der man nachsehen kann. An deinem Backofen sind auch nur Symbole. Wenn du wissen willst was sie bedeuten, schaust du in der Bedienungsanleitung nach... 

> Wo ich war aber nichts gefunden habe.

Das kann doch aber nicht unser Problem sein? Da musst du doch deine eigenen Skills überprüfen...

> Es gibt hunderte Adapter, soll man da von jedem die Herkunft aufspüren und Wiki durchlesen wenn mal was nicht geht.

Brauchst du nicht "aufspüren". Drei Punkte, Fragezeichen, Klick! Direkter Link zur Doku. 
![image](https://github.com/simatec/ioBroker.backitup/assets/16137672/f6646b30-9668-4c49-81c6-73daa4c532b6)
![image](https://github.com/simatec/ioBroker.backitup/assets/16137672/e1b79c43-f219-45f9-9310-5a2f37bdc647)

Doku/ Wiki lesen? Überraschung! JA, wir erwarten dass du das tust! 

> Wenn ihr öfters im Forum Probleme zu lösen hättet, dann wüsstest ihr wie oft das neben einer erfolgreichen Lösung auch genauso oft in endlosen Diskussionen, falschen Ratschlägen, offtopic Labereien und schlicht zeitraubender Zeitverschwendung endet.

Falsche Annahme! Wir sind beide auch im Forum aktiv und lesen mit. Wenn User Unterstützung brauchen, unterstützen wir. Und ja, wir wissen dass es dort nicht immer einfach ist...

> Mit gezielten Fragen an der Quelle ist man in der Regel besser bedient und oft nach ein zwei Runden fertig.

Hast du eigentlich eine Vorstellung davon, wie zeitaufwändig das für Entwickler ist jede dumme Frage tausendmal beantworten zu müssen? Siehe das Beispiel mit dem Speicherpfad? Und dann das Ganze auch noch während unserer Freizeit? Genau aus diesem Grund investieren wir Zeit in Doku/ Wiki...

> Meistens funktioniert das hier auf Github gut und effizient.

Dann hast du nicht verstanden wozu die Issues da sind. In jedem Fall nicht für Frage und Antwort spielchen mit Leuten die schlicht zu faul sind eine Doku zu lesen!!! Das wird hier gar nicht gern gesehen...

> Das meiste was "Alter, echt jetzt" buanet von sich gegeben hat ist einfach arroganter Müll: "Und jetzt beweise ich dir noch, dass du die Doku nicht gelesen hast:" und nicht weiter kommentarwürdig.

Damit hast es aber kommentiert.  Danke für die Beleidigung. 

Kommentare zum Rest spare ich mir jetzt mal. Das zeigt alles m.E. nur, dass du der Meinung bist, dass immer alles so funktionieren muss, wie du es dir denkst oder es für dich vielleicht praktisch wäre. Mir fehlt hier ein bisschen die Fähigkeit, oder zumindest die Bereitschaft sich auf das Bedienkonzept des Adapters einzulassen.... Jede Software hat Verbesserungspotenzial und ioBroker speziell auch was die Oberfläche angeht, aber wir sind hier halt nicht bei Wünsch dir was. Wenn du schon so ein großartiger Frontend-Designer bist, dann stelle uns doch deine Visionen einfach mal in einem separaten Issue als "Feature Request" vor, sodass die Community das diskutieren kann... ioBroker ist ein OpenSource Community Projekt lebt nunmal nur von und durch die Community...

Da du aber schon nichts von deiner kostbaren Zeit, die ja offenbar kostbarer als die der ioBroker Entwickler ist, opfern willst um lästige Dokus zu lesen oder im Forum/ Internet zu recherchieren, denke ich, dass wir von dir dahingehend nichts außer Meckern über die potenziellen Unzulänglichkeiten der Software erwarten können. Schade.

MfG,
André

**Comment by simatec** [comment]
@n0valis Eigentlich habe ich mir abgewöhnt zu solchen Issues überhaupt etwas zu schreiben oder darauf zu reagieren... meine Zeit ist mir dafür zu kostbar...
Darum gleich vorweg... Solltest du gegenüber @buanet noch einmal beleidigend werden, lösche ich das Issue und du wirst gesperrt!

Nun zu deinen Themen.
> Ich habe mit der Festlegung NAS/kopieren (täglich um 22 Uhr) eigentlich einen externen Speicherort definiert, aber da die geplante Ausführung nie funktioniert, macht dies keinen Sinn mehr für mich. 
Warum das nicht funktioniert ist mir schleierhaft, vielleicht hat es mit der clock des Raspi zu tun, keine Ahnung, cronjobs funktionieren jedenfalls. Die Durchführung des Backups an sich funktionert, nur eben zu total obsoleten Zeiten, Nachts um 4 oder morgens um 9 oder so. Meist ist das NAS dann gar nicht an und das Backup scheitert natürlich. Ist das NAS zur Durchführungszeit an, dann klappt auch das Backup.

Bitte poste deine komplette Config des Adapters als JSON-File
Backitup unterstützt auch WOL und kann dein NAS aufwecken... Dies musst du im Reiter "NAS/Kopieren" konfigurieren

Um zu überprüfen, mit welcher tatsächlichen Zeit iobroker arbeitet, musst du ebenfalls ein paar mehr Infos liefern.

Führe folgenden Script aus und poste hier die Logausgaben:
```
console.log(`iobroker Systemzeit: ${formatDate(new Date(), "hh:mm:ss")}`);

exec('timedatectl', async (error, result, stderr) => {
    console.log(`OS Systemzeit: ${result}`);
    
});
```

Des Weiteren zeige hier, wie viele Instanzen von Backitup laufen...
Eine komplette Debug-Log Ausgabe des Backup-Vorgangs bitte hier auch posten.

> Ich habe dann irgendwie zufällig entdeckt, dass die Backups auch lokal angelegt werden.
Der Speicheort /opt/iobroker/backups wird scheinbar aus irgendwelchen Gründen geheim gehalten und kannn auch nicht definiert werden? Warum ist das so?

Der Backup-Pfad /opt/iobroker/backups ist kein geheimer Pfad, ist in der [iobroker Doku](https://www.iobroker.net/#de/documentation/README.md) und in der [Backitup Doku](https://github.com/simatec/ioBroker.backitup/wiki) überall dokumentiert, ist und wird nicht konfigurierbar sein, da dies vom System (js-controller) fest vorgegeben ist.
Ein wenig Selbststudium ist nötig, um iobroker zu nutzen... 

> Im Backupverlauf sind nur die erfolgreichen Backups zum NAS aufgeführt. Nicht jedoch die gescheiterten/nicht durchgeführten.
Auch nicht die erfolgreichen lokalen Backups. Warum ist das so? Macht imho wenig Sinn.

Da du keine lokalen Backups konfiguriert hast, sondern deine Backups aufs NAS gehen, werden sie auch nicht als lokale Backups angezeigt.
Backitup arbeitet nach dem Sicherheitsprinzip und erstellt auch ohne ein einbinden des NAS Laufwerks ein Backup, welches dann zumindest lokal ist und man es sich im Anschluss wegsichern kann.
Dieses Verhalten ist genau so gewollt, denn lieber ein Backup lokal, als kein Backup.
Da in dem Fall dein NAS nicht eingebunden werden konnte und damit ein fehler beim Backup-Prozess entstanden ist, werden alte Backups nicht gelöscht.

Dies ist die Prozessdur bei jeglichen Fehlern während eines Backups. 
Des Weiteren werde jegliche Fehler im Log dokumentiert und auch ein Hinweis, dass aufgrund eines Fehlers alte Backups nicht gelöscht werden.

Auch hier liegt es nicht in der Verantwortung von Backitup die Logs zu prüfen, sondern in der Verantwortung des Nutzer. Backitup stellt jegliche Informationen zur Verfügung.

D.h. im Klartext, du hast einen Fehler beim Backup und es wird nicht gelöscht... Du hast ein Fehler bei der Verbindung zum NAS, die Backups werden lokal abgelegt und es gibt Hinweise im Log und per konfigurierten Messagenger.

Sind lokale Backups konfiguriert, werden diese selbstverständlich in der History angezeigt. ... Bei dir sind sie aber nicht konfiguriert..

![image](https://github.com/simatec/ioBroker.backitup/assets/39792461/823e82b9-dc39-4d35-bb35-fa802d0f26c9)

> Da bei mir die zeitliche Steuerung nicht funktioniert - was auf dem Computer ein Backitup-exklusives Problem ist

Es kann kein exklusives Problem von Backitup sein... Bitte poste die Ausgabe von:

`iob diag`

> Und wieso glaubst du dass ich die Zeit und die Lust hätte "massig Lesestoff" zu Backitup zu konsumieren.

Wozu schreiben wir im iobroker diese Wiki's und Anleitungen? Ein wenig Selbststudium sollte hier auch von dir kommen. Wir schreiben diese langen und umfangreichen Anleitungen nicht aus langerweile und bitte vergiss an der Stelle nicht, dass es sich bei iobroker um ein Open-Source Projekt handelt, wo jeder Entwickler seine Freizeit für die User von iobroker opfert... Und glaube mir, es fließt sehr viel Freizeit in die Entwicklung und ich bin ehrlich... Auf Aussagen und Äußerungen, wie sie von dir kommen, hat kein Entwickler Lust und du bist einer der Gründe, warum die Open-Source Welt mit seinen ehrenamtlichen Entwicklern immer kleiner wird.

> Zur von mir angesprochenen Transparenz gehört auch ein mindesmaß an info im Produkt selbst und nicht nur ins
Wiki.
Wo ich war aber nichts gefunden habe.

Die Infos gibt es ausreichend in der Konfigurationsoberfläche und im Tab-Menü... reicht dies nicht aus, geht man im Menü einfach auf das Fragezeichen und liest mal nach... Dafür gibt es die Doku... Auch das Forum, Facebook und Discord sind Anlaufstellen, wo einem sofort geholfen wird. Ich beantworte immer die Fragen und helfe auf allen Plattformen ... aber nicht in diesem Ton und der Art und Weise, den du hier an den Tag legst.

> Es gibt hunderte Adapter, soll man da von jedem die Herkunft aufspüren und Wiki durchlesen wenn mal was nicht geht.

JA!!

> Niemand will buddeln gehen wenn es mal nicht so funktioniert wie gedacht. Deswegen ist eine vernüftige Strukturierung und Übersicht der Information das wichtigste neben dem eigentlichen Programm. Backitup hat da mM nach ein paar Defizite.

Knapp 66.000 Nutzer von Backitup haben bisher die Strukturierung nie bemängelt .... Also kann sie nicht wirklich so schlecht sein, wie du sie wahrnimmst...

> Im Backupverauf wird nicht angezeigt wo lokale Backups liegen, nocht nicht mal das welche gemacht werden

Wenn lokale Backups konfiguriert sind, werden sie auch in der History angezeigt (siehe Bild oben) Das Thema Backuppfad hatten wir auch weiter oben schon und ist bekannt. Es steht in jeder Doku und ist der iobroker Standardpfad für Backup und Restore!!

> Wenn ich den Punkt NAS / Kopieren in den Haupteinstellungen anklicker erscheint ein zusätzlicher Reiter für die Einstellungen des Verbindungstyp etc. DAs habe ich zuerst gar nicht bemerkt. Habe mich erstmal gewundert warum dort nichts passiert.
Das kann doch genausogut in den Haupteinstellungen erfolgen direkt unterhalb von dem Punkt wo man es aktiv schaltet.
Oder alternativ einen fixen ReiterSpeicherorte mit allen Einstellungen für alle Speicherorte.

Da bist du leider auch der Erste von rund 66.000 Nutzern, die nicht mitbekommen, dass ein Reiter in der Tableiste freigeschaltet wird, wenn man Optionen im Hauptmenü auswählt.
Die Struktur von Backitup hat sich seit Jahren für die User bewährt und wird nicht geändert!!

> Genauso die EInstellungen unter iobroker. Da steht jetzt nur Sicherungszeit und Anzahl etc.
Das sind doch defakto auch Haupteinstellungen und rechtfertigen nicht wirklcih einen eigenen Reiter. Es wird dadurch nur komplizierter und unübersichicher.

Auch das haben die Nutzer bisher immer eigenständig und ohne Hilfe gefunden und konfigurieren können... Hier wird es auch keine Änderungen geben und die Struktur ist übersichtlich und hat Konzept.

> Das meiste was "Alter, echt jetzt" buanet von sich gegeben hat ist einfach arroganter Müll: "Und jetzt beweise ich dir noch, dass du die Doku nicht gelesen hast:" und nicht weiter kommentarwürdig.

Erstmal ist deine Aussage hier unter der Gürtellinie und beleidigende Aussagen respektiere ich hier in keiner Weise.
Zum anderen hat @buanet recht und du sagst selber auch, dass du keinen Bock hast die Doku zu lesen. 
In der [Doku ](https://github.com/simatec/ioBroker.backitup/wiki/ioBroker.backitup-Wiki-Deutsch#backuptypen) ist klar geschrieben, dass lokale Backups im Standard Backuppfad von iobroker landen und dieser sich unter /opt/iobroker/backups befindet.


Wenn du nun bereit bist, die Doku zu lesen, dich über die Möglichkeiten und Optionen von Backitup zu informieren, du hier vernünftige Infos wie Logs, Config und die abgefragten Infos bringst, dann helfe ich gerne... Sollten aber deine Antworten weiterhin so ausfallen, wie bisher, passiert das bereits oben angekündigte...

**Comment by n0valis** [comment]
"Es ist immer sehr ärgerlich und zeitraubend wenn Entwickler sich zu solchen Themen äußern müssen"
"meine Zeit ist mir dafür zu kostbar..."
"Wo bist du denn falsch abgebogen?" "Alter, echt jetzt"
"muss nicht unnütz seine Freizeit opfern..."
"Knapp 66.000 Nutzer von Backitup haben bisher die Strukturierung nie bemängelt"

Und ich habe also jemanden beleidigt indem ich gesagt habe er ist arrogant?
Wenn ich jemanden beleidigen wollte, dann hätte ich wohl gesagt ihr seid ein narzistischer, selbstgerechter Haufen.
Aber selbst das wäre offensichtlich keine Beleidigung gewesen.
Ihr habt das Problem dass ihr denkt alle müssten euch auf den Knien entgegenrutschen dafür das ihr Opensource Software macht, obwohl sie es bei keinem seriösen Softwareuntenehmen über die erste Klippe schaffen würde.
Kritikfähigkeit Zero-1

Unsere Vorstellungen davon was angebracht ist werden wohl nicht deckungsgleich werden.
Um stundenlang Dokus zu lesen, Diagnoselogs zu erstellen und zu analysieren und Konversationen wie diese zu führen
ist mir meine Zeit auch zu Schade. Aber 66000 Freunde von Backitup sind ja superhappy, deshalb möchte ich euch in eurer Wohlfühlbubble nicht weiter belästigen.
Ich mache das Backup lieber selbst.

**Comment by simatec** [comment]
Ich habe dir konstruktive Themen an die Hand gegeben und die Bitte Infos zu liefern, um dir zu helfen... 
Da du dies nicht willst und wieder Beleidigend warst, brauchst du als keine Hilfe ... 

Ich denke du suchst dir besser eine iot Lösung, die es über die erste Klippe schaffen kann... In der iobroker Community bist du leider fehl am Platz

**Comment by buanet** [comment]
@simatec
Komm, mach weg den issue. Es ist alles gesagt.
Hilfe gibt es im Forum. Die Dokus ist m. E. vollkommen in Ordnung und er hat ja gesagt er macht sein Backup jetzt lieber selbst. 
Problem gelöst. 

Im Übrigen ist das hier auch wieder eine Beleidigung, zwar indirekt, aber genau so gemeint.

> Wenn ich jemanden beleidigen wollte, dann hätte ich wohl gesagt ihr seid ein narzistischer, selbstgerechter Haufen.

MfG,
André

**Comment by simatec** [comment]
@buanet Ich habe @n0valis blockiert

**Comment by simatec** [comment]
@buanet Ich lasse das Issue mal noch stehen, damit wir eventuell mal im Dev-Meeting die generelle Umgangsweise mit solchen Issues besprechen können.
