### ISSUE TITLE
State roles do not meet iobroker requirements

### ISSUE THREAD

**Issue by mcm1957** [simatec/ioBroker.backitup#988]
**Describe the bug**  
Some states use incorrect roles.

According to https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md#indicators-boolean-read-only states with role INDICATOR must be of type BOOLEAN.

iobrokerLastTime and ccuLastTime are of type string but have role indicator.

**Expected behavior**  
All roles respect the specifications of https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md

**Versions:**  
 - Adapter version: 2.6.19
 - JS-Controller version: 0.5.12
 - Node version: v18.17.1
 - Operating system: windows 11

**Comment by simatec** [comment]
Fix in v2.8.1
