### ISSUE TITLE
Namenszusatz auch für Mysql Backup verwenden

### ISSUE THREAD

**Issue by homecineplexx** [simatec/ioBroker.backitup#99]
hallo

ist es evenutell möglich diesen Namenszusatz, den man bei "Standard Backup" angibt auch für das MysqlBackup zu verwenden, damit man weiß zu welchem RPI das MysqlBackup gehört?

lg

**Comment by homecineplexx** [comment]
bzw auch diesen namenszusatz irgendwie in der benachrichtigung zu verwenden, damit man weiß welches backup gut und welche schief gegangen ist

**Comment by simatec** [comment]
Schauen wir uns mal an

**Comment by simatec** [comment]
added at Release 1.4.0
