### ISSUE TITLE
Error Files could Not be deleted

### ISSUE THREAD

**Issue by DPO99** [simatec/ioBroker.backitup#991]
**Describe the bug**  
Backitup was Not able to delete old files

**To Reproduce**  
Start Automatic Backup

**Expected behavior**  
Old Backups should be deleted
.
**Screenshots & Logfiles**  
2023-09-21 23:00:45.031 - error: backitup.0 (156610) [iobroker/clean] Backup files not deleted from /opt/iobroker/backups because some errors.

**Versions:**  
 - Adapter version: 2.8.1
 - JS-Controller version: 4.0.24
 - Node version: 18.18.0
 - Operating system: Bullsyeye

**Additional context**  
Backup should saved in NAS, dont know why He wants to delete in opt/iobroker/backups

**Comment by simatec** [comment]
Please post the full Debuglog from Backup Process

**Comment by DPO99** [comment]
Fehler bisher nicht mehr aufgetreten.
