### ISSUE TITLE
Changed behaviour with redis-cli 7.x

### ISSUE THREAD

**Issue by Marc-Berg** [simatec/ioBroker.backitup#993]
When backing up a remote RedisDB **without a user/password**, the following command is executed:

`redis-cli -u 'redis://:@redishost:6379' --rdb /opt/iobroker/backups/redistmp/dump.rdb`

Note the characters ":@" after "//".

redis-cli version **6.x** issues a warning, but performs the backup anyway:

`redis-cli -u 'redis://:@redishost:6379' --rdb /opt/iobroker/backups/redistmp/dump.rdb`
`Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.`
`Warning: AUTH failed`
`sending REPLCONF capa eof`
`SYNC sent to master, writing bytes of bulk transfer until EOF marker to '/opt/iobroker/backups/redistmp/dump.rdb'`
`Transfer finished with success after 7666929 bytes`
`Transfer finished with success.`

With redis-cli version 7.x (which comes with Debian 12/bookworm), the backup aborts:

`redis-cli -u 'redis://:@redishost:6379' --rdb /opt/iobroker/backups/redistmp/dump.rdb`
`Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.`
`AUTH failed: WRONGPASS invalid username-password pair or user is disabled.`

**Expected behavior**  
Remove the characters ":@", if there is no user/password.

**Versions:**  
 - Adapter version: 2.8.1
 - JS-Controller version: 4.0.24 / 5.0.12
 - Node version:  18.18
 - Operating system: Debian 12

**Comment by simatec** [comment]
Please test the current Github Version

**Comment by Marc-Berg** [comment]
The Redis-Backup now works without User/Password.
