### ISSUE TITLE
WOL funktioniert nicht mehr

### ISSUE THREAD

**Issue by Standarduser** [simatec/ioBroker.backitup#999]
Mit der Adapter-Version 2.8.1 wird trotz unveränderter Einstellungen mein Synology-NAS nicht mehr geweckt.
Die Mac-Adresse stimmt und funktioniert auch bei WOL über andere Adapter.

Zugehörige Fehlermeldungen tauchen zwar im Log-File auf, eine Benachrichtigung per Telegram erfolgt jedoch nicht (Haken bei "Benachrichtigung nur bei Fehlern" gesetzt)

**Comment by simatec** [comment]
Bitte zeige deinen Debuglog und die Einstellungen für WOL

**Comment by Standarduser** [comment]
Aus dem Log bekommt man leider nicht viel heraus. Das sind die Meldungen, die dabei entstehen:

Quelle | Zeit | Debug | Nachricht
-- | -- | -- | --
backitup.1 | 2023-10-02 15:13:34.966 | error | [iobroker] Error: Command failed: sudo mount -t cifs -o username=srv-iobroker1,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.243.10/backup/iobroker /opt/iobroker/backupsmount error(113): could not connect to 192.168.243.10Unable to find suitable address.
backitup.1 | 2023-10-02 15:13:34.966 | error | [iobroker/mount] mount error(113): could not connect to 192.168.243.10Unable to find suitable address.
backitup.1 | 2023-10-02 15:13:34.966 | error | [iobroker/mount] Error: Command failed: sudo mount -t cifs -o username=srv-iobroker1,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.243.10/backup/iobroker /opt/iobroker/backups
backitup.1 | 2023-10-02 15:13:34.966 | error | [iobroker/mount] mount error(113): could not connect to 192.168.243.10Unable to find suitable address.
backitup.1 | 2023-10-02 15:13:34.965 | error | [iobroker/mount] [undefined Error: Command failed: sudo mount -t cifs -o username=srv-iobroker1,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.243.10/backup/iobroker /opt/iobroker/backups
backitup.1 | 2023-10-02 15:13:28.823 | debug | [iobroker/mount] cifs-mount command: "sudo mount -t cifs -o username=srv-iobroker1,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.243.10/backup/iobroker /opt/iobroker/backups"
backitup.1 | 2023-10-02 15:13:28.822 | debug | [iobroker/mount] first mount attempt with smb option failed. try next mount attempt without smb option ...
backitup.1 | 2023-10-02 15:13:22.656 | debug | [iobroker/mount] cifs-mount command: "sudo mount -t cifs -o username=srv-iobroker1,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=3.1.1 //192.168.243.10/backup/iobroker /opt/iobroker/backups"
backitup.1 | 2023-10-02 15:13:22.656 | debug | [iobroker/mount] noserverino option: false
backitup.1 | 2023-10-02 15:10:22.655 | debug | Backup has started ...
backitup.1 | 2023-10-02 15:10:22.655 | debug | [iobroker/mount] Wake on LAN wait 180 Seconds for NAS!
backitup.1 | 2023-10-02 15:10:22.651 | debug | The local storage check was completed successfully. On the host "srv-iobroker1" are currently 15232 MB free space available!
backitup.1 | 2023-10-02 15:10:17.692 | debug | The local storage check was completed successfully. On the host "srv-iobroker1" are currently 15232 MB free space available!
backitup.1 | 2023-10-02 15:10:11.896 | info | Loglevel changed from "error" to "debug"

So ist es konfiguriert:
<img width="1844" alt="Bildschirmfoto 2023-10-02 um 15 20 35" src="https://github.com/simatec/ioBroker.backitup/assets/8029204/60111842-0bfa-475f-9991-3cafeb0e98ae">

**Comment by simatec** [comment]
Welchen Pfad verwendet dein NAS für WOL?

**Comment by Standarduser** [comment]
Ich habe nichts verstellt oder umgebogen, insofern müsste das der Port 9 sein, soweit ich weiß.

**Comment by simatec** [comment]
In Version 2.8.1 gab es eine Erweiterung für WOL. 
Diese nutzt jetzt neben der MAC auch IP und Port. 
Darum wäre es gut, wenn du schaust, welchen Port dein NAS für WOL nutzt

**Comment by Standarduser** [comment]
Ich konnte leider kein Dokument finden, in dem das spezifiziert ist. In verschiedenen Foren wird von Port 9 gesprochen

**Comment by simatec** [comment]
Schaue auch, ob dein Router den Port durchlässt

**Comment by simatec** [comment]
Kann das Issue hier geschlossen werden?

**Comment by Standarduser** [comment]
Ich hatte noch keine Gelegenheit, den Port 7 auszuprobieren. Das schaffe ich frühestens Ende nächster Woche. 

Worauf du leider nicht eingegangen bist ist der Punkt, dass trotz fehlgeschlagenem Backup keine Telegram-Benachrichtigung gesendet wurde.

**Comment by simatec** [comment]
> Zugehörige Fehlermeldungen tauchen zwar im Log-File auf, eine Benachrichtigung per Telegram erfolgt jedoch nicht (Haken bei "Benachrichtigung nur bei Fehlern" gesetzt)

Kommen denn generell Nachrichten an? Laut Codeprüfung sollten Nachrichten bei einem Fehler im Mount kommen

**Comment by TotKu** [comment]
Hallo,
auch ich habe ein Problem mit WOL (Version 2.8.1)
Die im lokalen Netzwerk vorhandene NAS (Buffalo Linkstation LS-WVL) startet nicht mit der Funktion "Wake on LAN" aus dem BackItUp - weder auf Port 7 noch auf Port 9. Auf der Firewall ufw ist Port 7 und 9 offen.
Setzte ich im Putty den Befehl "sudo /usr/sbin/etherwake -i eth0 <Mac Adresse>" ab startet die NAS.
Die identen zugehörigen Fehlermeldungen wie beim @Standarduser sind bei mir ebenso im Debuglog.

**Comment by simatec** [comment]
Bitte mal die aktuelle Github Version testen und direkt von Github installieren

**Comment by TotKu** [comment]
Hallo,
der Autostart der NAS funktioniert jetzt einwandfrei.
Aber die eigentliche Sicherung startet nicht =>
`Started iobroker ...
[DEBUG] [mount] - Wake on LAN wait 120 Seconds for NAS!
[DEBUG] [mount] - Wake on LAN MAC-Address: 4C:E6:76:92:A2:AE
[DEBUG] [mount] - noserverino option: false
[DEBUG] [mount] - cifs-mount command: "mount -t cifs -o username=Datensicherung,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=1.0 //192.168.115.200/Datensicherung/Raspberry /opt/iobroker/backups"
[DEBUG] [mount] - first mount attempt with smb option failed. try next mount attempt without smb option ...
[DEBUG] [mount] - cifs-mount command: "mount -t cifs -o username=Datensicherung,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.115.200/Datensicherung/Raspberry /opt/iobroker/backups"
[ERROR] [mount] - [undefined Error: Command failed: mount -t cifs -o username=Datensicherung,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.115.200/Datensicherung/Raspberry /opt/iobroker/backups
mount.cifs: permission denied: no match for /opt/iobroker/backups found in /etc/fstab

[ERROR] [mount] - Error: Command failed: mount -t cifs -o username=Datensicherung,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.115.200/Datensicherung/Raspberry /opt/iobroker/backups
mount.cifs: permission denied: no match for /opt/iobroker/backups found in /etc/fstab`

**Comment by TotKu** [comment]
Hallo nochmals,
war mein Fehler, durch das gestrige Testen hatte ich in der Konfig "Als root-Benutzer mounten (sudo)" noch deaktiviert.
Jetzt läuft alles wieder perfekt.
Danke für den prompten Support!

**Comment by TotKu** [comment]
mir ist soeben aufgefallen, dass bei "Sicherung abrufen" über "NAS / Kopieren" kein WOL erfolgt.

**Comment by simatec** [comment]
Das ist richtig .. Ist ja auch ein manueller Abruf, wo man im Vorfeld schauen muss, ob das NAS erreichbar ist.

**Comment by simatec** [comment]
Fix in v2.8.3

**Comment by Standarduser** [comment]
> Das ist richtig .. Ist ja auch ein manueller Abruf, wo man im Vorfeld schauen muss, ob das NAS erreichbar ist.
> 
> 

Laut der Logausgabe wird der NAS aber trotzdem geweckt und der Adapter wartet die eingestellte Zeit für das Aufwecken

**Comment by simatec** [comment]
Bitte poste den log mal

**Comment by Standarduser** [comment]
Das ist die Log-Ausgabe beim manuellen Starten des Backups mit Version 2.8.1 (darauf bezog sich ja das Ticket):
```Started iobroker ...
[DEBUG] [mount] - Wake on LAN wait 180 Seconds for NAS!
[DEBUG] [mount] - noserverino option: false
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=srv-iobroker1,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=3.1.1 //192.168.243.10/backup/iobroker /opt/iobroker/backups"
[DEBUG] [mount] - first mount attempt with smb option failed. try next mount attempt without smb option ...
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=srv-iobroker1,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.243.10/backup/iobroker /opt/iobroker/backups"
[ERROR] [mount] - [undefined Error: Command failed: sudo mount -t cifs -o username=srv-iobroker1,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.243.10/backup/iobroker /opt/iobroker/backups
mount error(113): could not connect to 192.168.243.10Unable to find suitable address.

[ERROR] [mount] - Error: Command failed: sudo mount -t cifs -o username=srv-iobroker1,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.243.10/backup/iobroker /opt/iobroker/backups
mount error(113): could not connect to 192.168.243.10Unable to find suitable address.```

<img width="1451" alt="Bildschirmfoto 2023-10-12 um 13 34 42" src="https://github.com/simatec/ioBroker.backitup/assets/8029204/05a52a0d-598c-488a-9f46-7c2dbba7c155">

**Comment by Standarduser** [comment]
Mit Version 2.8.4 scheint der NAS ordentlich geweckt zu werden, auch beim manuellen Backup.

Nach wie vor kommt jedoch keine Fehlermeldung, wenn das Backup scheitert, weil der NAS nicht erreichbar ist. Wenn ich mir das so anschaue, und es sich dabei nicht nur um einen Darstellungsfehler handelt, dann scheint der Backup-Prozess trotz Scheiterns niemals zu enden, denn nach 20 Minuten warten sehe ich nach wie vor den Aktivitätsbalken durchs Bild laufen.

<img width="1355" alt="Bildschirmfoto 2023-10-12 um 14 07 15" src="https://github.com/simatec/ioBroker.backitup/assets/8029204/c6c0f851-ff85-4b29-8db3-be46d31cb47e">

Ich könnte mir also gut vorstellen, dass die Benachrichtigung über ein fehlgeschlagenes Backup deswegen nie auf meinem Handy eintrifft.

**Comment by simatec** [comment]
Sollte in v2.8.5 gefixt sein

**Comment by Standarduser** [comment]
Ich habe jetzt 2.8.6 aus dem Latest installiert und die Meldung, dass der Mount fehlgeschlagen ist, kam nun per Telegram. Vielen Dank also dafür.

Was mich jedoch wundert ist, dass das Backup trotzdem stattfindet und aufgrund des Fehlers am Ende nicht gelöscht wird. Besteht dann nicht die Gefahr, dass der Speicher auf der HDD/SSD/SD-Karte vollläuft und das gesamte System stirbt?

```
Started iobroker ...
[DEBUG] [mount] - Wake on LAN wait 180 Seconds for NAS!
[DEBUG] [mount] - Wake on LAN MAC-Address: 00:11:32:b0:b2:5a
[DEBUG] [mount] - noserverino option: false
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=srv-iobroker1,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777,vers=3.1.1 //192.168.243.10/backup/iobroker /opt/iobroker/backups"
[DEBUG] [mount] - first mount attempt with smb option failed. try next mount attempt without smb option ...
[DEBUG] [mount] - cifs-mount command: "sudo mount -t cifs -o username=srv-iobroker1,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.243.10/backup/iobroker /opt/iobroker/backups"
[ERROR] [mount] - [undefined Error: Command failed: sudo mount -t cifs -o username=srv-iobroker1,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.243.10/backup/iobroker /opt/iobroker/backups
mount error(113): could not connect to 192.168.243.10Unable to find suitable address.

[DEBUG] [mount] - Error: Command failed: sudo mount -t cifs -o username=srv-iobroker1,password=****,rw,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777 //192.168.243.10/backup/iobroker /opt/iobroker/backups
mount error(113): could not connect to 192.168.243.10Unable to find suitable address.

[DEBUG] [iobroker] - host.srv-iobroker1 24670 states saved

[DEBUG] [iobroker] - host.srv-iobroker1 27486 objects saved

[DEBUG] [iobroker] - Backup created: /opt/iobroker/backups/iobroker_2023_10_14-17_17_45_backupiobroker.tar.gz

[DEBUG] [iobroker] - This backup can only be restored with js-controller version up from 4.1

[DEBUG] [iobroker] - done
[DEBUG] [influxDB] - InfluxDB-Backup started ...
[DEBUG] [influxDB] - Start InfluxDB Backup ...
[DEBUG] [influxDB] - InfluxDB Backup tmp directory created 
[DEBUG] [influxDB] - Packed 105MB so far...
[DEBUG] [influxDB] - Packed 216MB so far...
[DEBUG] [influxDB] - Packed 327MB so far...
[DEBUG] [influxDB] - Packed 433MB so far...
[DEBUG] [influxDB] - Backup created: /opt/iobroker/backups/influxDB_2023_10_14-17_18_00_backupiobroker.tar.gz
[DEBUG] [influxDB] - Try deleting the InfluxDB tmp directory: "/opt/iobroker/backups/influxDB_2023_10_14-17_18_00_backupiobroker"
[DEBUG] [influxDB] - InfluxDB tmp directory "/opt/iobroker/backups/influxDB_2023_10_14-17_18_00_backupiobroker" successfully deleted
[DEBUG] [influxDB] - InfluxDB-Backup for is finish
[DEBUG] [influxDB] - done
[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
[DEBUG] [grafana] - found Dashboard: netzwerk
[DEBUG] [grafana] - found Dashboard: homematic
[DEBUG] [grafana] - found Dashboard: hardware-uberwachung
[DEBUG] [grafana] - found Dashboard: ipad-vis
[DEBUG] [grafana] - found Dashboard: dashboard
[DEBUG] [grafana] - start Grafana backup compress ...
[DEBUG] [grafana] - Backup created: /opt/iobroker/backups/grafana_2023_10_14-17_18_56_backupiobroker.tar.gz
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[DEBUG] [grafana] - done
[DEBUG] [javascripts] - Created javascript_tmp directory: "/opt/iobroker/backups/tmpScripts"
[DEBUG] [javascripts] - found Script: Datum_Uhrzeit
...
[DEBUG] [javascripts] - found Script: Skript_1
[DEBUG] [javascripts] - Try deleting the Javascript tmp directory: "/opt/iobroker/backups/tmpScripts"
[DEBUG] [javascripts] - Javascript tmp directory "/opt/iobroker/backups/tmpScripts" successfully deleted
[DEBUG] [javascripts] - Backup created: /opt/iobroker/backups/javascripts_2023_10_14-17_19_02_backupiobroker.tar.gz
[DEBUG] [javascripts] - done
[DEBUG] [yahka] - found yahka database: yahka.0
[DEBUG] [yahka] - done
[DEBUG] [cifs] - used copy path: /backup/iobroker
[DEBUG] [cifs] - done
[ERROR] [clean] - Backup files not deleted from /opt/iobroker/backups because some errors.
[DEBUG] [clean] - done
[DEBUG] [telegram] - done
[DEBUG] [historyHTML] - new history html values created
[DEBUG] [historyHTML] - done
[DEBUG] [historyJSON] - new history json values created
[DEBUG] [historyJSON] - done
```

**Comment by simatec** [comment]
Dafür kommt ja die Meldung und ab und an sollte man sein System prüfen. 
Lieber ein Backup lokal, als kein Backup. 
und gelöscht wird kein altes Backup, wenn ein Fehler auftritt

**Comment by Standarduser** [comment]
Das dachte ich mir schon. Danke.
